### PR TITLE
Add cur extension for url-loader

### PR DESCRIPTION
**Pull request by yitzchak**
## References

https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

## Code changes

CSS cursor attribute allows multiple files as fallbacks including Windows cursors (`.cur`), PNG, etc. Some packages in npm come packaged with `.cur` files and therefore will fail in webpack during installation.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by telamonian** [comment]
Though I for one have never seen a `.cur` file, this does appear to be kosher. I'll pull this in, unless anyone has objections.

@yitzchak Out of curiosity, what's an example of a package that will cause webpack to fail without a `cur` loader?

**Comment by yitzchak** [comment]
@telamonian Thanks! The package that I currently have the issue with is [kekule](https://www.npmjs.com/package/kekule). Working on a widget version.

**Comment by blink1073** [comment]
Congratulations on your first contribution to JupyterLab @yitzchak!

**Comment by yitzchak** [comment]
Thanks @blink1073!

**Pull request merged**
