### PR TITLE
Update yarn.lock file

### PR DESCRIPTION
**Pull request by jasongrout**
I deleted the yarn.lock and reinstalled to pick up any new updates.

I'm not insisting this be merged, since we did just update a few weeks ago. Thoughts on having one last refresh before we pin things down?

### CODE REVIEW

**Comment by vidartf** [comment]
I was able to remove some duplicates locally by running `jlpm yarn-dedpulicate -s fewer yarn.lock`.

**Comment by jasongrout** [comment]
Refreshed and deduplicated

**Comment by jasongrout** [comment]
Most of the prettier changes came from the improvement https://prettier.io/blog/2019/06/06/1.18.0.html#stop-breaking-simple-template-literals-5979-by-jwbay

**Comment by ian-r-rose** [comment]
:shipit: :ship:

**Pull request merged**
