### PR TITLE
Check if process is declared before optional chaining in makeSettings

### PR DESCRIPTION
**Pull request by xiaochen-db**
This fixes https://github.com/jupyterlab/jupyterlab/issues/12213.

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

Looks like this needs a small link fix:

image

Which should have been fixed by `pre-commit.ci` normally, but it doesn't seem to be the case here.

**Comment by xiaochen-db** [comment]
I pair-programed with @jasongrout and we tested the current `makeSettings` change with `process` being removed from the `builder/src/webpack.config.base.ts` (see https://github.com/jupyterlab/jupyterlab/pull/12461), and we found JupyterLab can still launch correctly. We decided to go with the current change in this pull request but remove `process` in future as it's deemed more controversial

**Review by fcollonval — APPROVED** [review]
LGTM

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.4.x

**Pull request merged**
