### PR TITLE
Update workspaces to automatically resolve.

### PR DESCRIPTION
**Pull request by afshin**
#### Fixes https://github.com/jupyterlab/jupyterlab/issues/6210

- [x] Removes the workspace from file browser "copy shareable link", returning a simple `tree` URL.
- [x] Makes `resolve-workspace` behavior automatic and removes the query string parameter and redirect dialog.

### CODE REVIEW

**Comment by jasongrout** [comment]
#6210 explicitly mentions: 

> However, when I am trying to share this notebook to non-technical background ppl, it becomes a problem.

Perhaps one part of the problem is having the new workspace dialog, but perhaps another part is even having the mention of a workspace at all. My workspaces are likely quite different from your workspaces, so there is no reason for a link from me to include my workspace information. Instead, it seems to me that the link should elide the workspace information, as mentioned in #6210, and just have the `/tree` url. Thoughts?

**Comment by jasongrout** [comment]
Just having the /tree url essentially is putting the file into a user's default workspace, which I think is simpler and more likely to satisfy the "non-technical background ppl", than opening a seemingly random workspace of yours that happens to be named the same as mine.

**Comment by jasongrout** [comment]
CC also the OP: @bobmayuze

**Comment by afshin** [comment]
@jasongrout That is a reasonable solution. `resolve-workspace` is still broken, but maybe solving it in a different PR is a better move.

**Comment by afshin** [comment]
Actually, the `resolve-workspace` issues still need to happen here because even if we create just a `/tree` URL, that can collide with the default workspace, so adding the `resolve-workspace` param will fix that ... if it works.

**Comment by jasongrout** [comment]
> Actually, the `resolve-workspace` issues still need to happen here because even if we create just a `/tree` URL, that can collide with the default workspace, so adding the `resolve-workspace` param will fix that ... if it works.

True, good point.

**Comment by bobmayuze** [comment]
We could probably have something like a binder to host the notebooks statically? Such as having a **Copy Static Shareable Link** which will create a static file to serve the current notebook just like google docs ReadOnly shareable link?  Other folks could reference this static page whenever they need to, but they won't be able to run any code in that way. One way to solve it is by adding a **fork this notebook to my workspace** or something like that.

**Comment by afshin** [comment]
@bobmayuze The copy shareable link functionality is intended as a lowest common denominator thing that doesn't necessary require a public internet connection, it's meant to simply mimic what you can already do in the classic interface. What you are suggesting would be a good candidate for an extension, though.

**Comment by afshin** [comment]
@jasongrout This problem is making me realize you were right to suggest that `resolve-workspace` be the default behavior.

If we make all workspace resolution happen automatically we allow users to create new workspaces by typing the URL but always making sure they land somewhere useful if the URL they wanted is currently occupied. Then users would not need to know some special URL parameter to get the behavior they surely want, which is for the URL they entered to *work*.

**Comment by afshin** [comment]
We could remove that whole dialog, actually. That was UX scaffolding.

**Comment by afshin** [comment]
Right now, the risk is that the **user gets annoyed by the persistent dialog frequently**. Removing that annoyance changes the risk to **user forgot a previous workspace's name**. We can fix that by adding a help menu item that lists the saved sessions that are returned by the REST request `GET /lab/api/workspaces`.

Which of these should be in this PR? All three or some subset? My inclination is all three. But I'm also happy to break them out into separate pull requests.

- [ ] Remove the workspace from file browser "copy shareable link", have it just be a `tree` URL.
- [ ] Make `resolve-workspace` behavior automatic and remove the query string parameter.
- [ ] Add list of active sessions to help menu.

**Comment by jasongrout** [comment]
> My inclination is all three

I'm happy to review all three in this PR, if it's easier for you.

**Comment by jasongrout** [comment]
Hmmm...maybe it would be better to do "Add list of active sessions to help menu." in a different PR, since it involves at least some UX consideration about where to put that list.

**Comment by afshin** [comment]
Okay good plan. Let's have the first two in this PR.

**Comment by ian-r-rose** [comment]
ping @mpacer

**Pull request merged**
