### PR TITLE
Restore compact notebook layout on mobile

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/11516

## Code changes

- [x] Format input and output prompts based on the `only screen and (max-width: 760px)` CSS media query that was removed in https://github.com/jupyterlab/jupyterlab/pull/9831.
- [x] Add UI Test

## User-facing changes

Restore back the more compact notebook layout on mobile:

https://user-images.githubusercontent.com/591645/147733322-9914d32c-6690-4cfe-96c2-f8d68944f258.mp4

## Backwards-incompatible changes

None

### CODE REVIEW

**Review by fcollonval — COMMENTED** [review]
Thanks @jtpio 

It would be nice to add a UI test for this using https://playwright.dev/docs/test-configuration#local-configuration for setting the viewport.

**Comment by jtpio** [comment]
> add a UI test for this

Absolutely. This was one of the observations from https://github.com/jupyterlab/jupyterlab/issues/11516 so we can catch these regressions more easily.

**Review by fcollonval — APPROVED** [review]
Thanks a lot @jtpio

**Comment by jtpio** [comment]
@meeseeksdev please backport to 3.2.x

**Pull request merged**
