### PR TITLE
remove session error dialog redundant error message to avoid repeated display

### LINKED ISSUE #10809: Session context error dialog print error message twice
## Description

The error message in Session error dialog appears twice. 
By review the source code. can clearly find the message print twice, the code is quite simply.
https://github.com/jupyterlab/jupyterlab/blob/00b7ed51df46ed7d3a75eed7f3bdad3089d90e0e/packages/apputils/src/sessioncontext.tsx#L957

## Reproduce

Dont need for this step. can find this problem by a simple code review. https://github.com/jupyterlab/jupyterlab/blob/00b7ed51df46ed7d3a75eed7f3bdad3089d90e0e/packages/apputils/src/sessioncontext.tsx#L957

## Expected behavior

The error message in Session error dialog appears only once.

## Context

- Operating System and version: macos 11.5.1
- Browser and version:  Chrome 90
- JupyterLab version:  ~3.1.0

<details><summary>Troubleshoot Output</summary>
<pre>
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
nothing

</pre>
</details>

### PR DESCRIPTION
**Pull request by franckchen**
## References

Fixes #10809

### CODE REVIEW

**Comment by franckchen** [comment]
> Thanks @franckchen.
> 
> Could you update the PR description to add a reference to the associated issue (something like _Fixes #<issue_id>_). This will create link in GitHub and automatically close the issue when the PR good merged.

Ok. Thanks. I forgot. Now I added and I also modified my commit message.

**Review by fcollonval — APPROVED** [review]
Thanks a lot @franckchen for the quick update.

This looks good to me.

**Comment by fcollonval** [comment]
We have some trouble with the CI for now. So I'll let this one open to give it a chance when those troubles are fixed.

**Comment by blink1073** [comment]
Kicking CI

**Pull request merged**
