### PR TITLE
Align Extension manager buttonbar right

### LINKED ISSUE #14021: Install buttons in the extension manager are left aligned
## Description

Install buttons in the extension manager are left aligned rather than right, which seems to be more common in JLab.

## Reproduce

1. Open Extension Manager
2. Note how install buttons are aligned

image

## Expected behavior

Install buttons in the extension manager are right-aligned.

## Context

Operating System and version: MacOS 12.6.3
Browser and version: Chrome version 109.0.5414.87 (Official Build) (arm64)
JupyterLab version: head-of-master (WIP 4.0.0)

### PR DESCRIPTION
**Pull request by andrii-i**
## References

- Fixes #14021

## Code changes

Justifies Extension Manager buttonbar to flex-end so that buttons are right-aligned. 

## User-facing changes

Extension Manager buttonbar is right-aligned

Before:
image

After:
Screenshot 2023-03-15 at 5 42 00 PM
Screenshot 2023-03-15 at 5 42 04 PM

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by andrii-i** [comment]
bot please update snapshots

**Comment by andrii-i** [comment]
Kicking CI

**Comment by krassowski** [comment]
:+1: There is a conflict in `galata/test/jupyterlab/completer.test.ts-snapshots/completer-with-doc-panel-jupyterlab-linux.png` which needs to be resolved locally.

**Comment by andrii-i** [comment]
Kicking CI

**Comment by andrii-i** [comment]
Currently Linux Tests / check_links (pull_request) fails because there is a dead link in ``YDocument <https://jupyter-ydoc.readthedocs.io/en/latest/api/classes/YDocument.html>`` string in [source/extension/documents.rst](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/extension/documents.rst) at line 42

**Comment by andrii-i** [comment]
Issue is not related to this PR, see issue #14248 and PR #14243

**Comment by andrii-i** [comment]
@krassowski it's all green now. Could you please give it a look and merge if possible? Thank you

**Review by krassowski — APPROVED** [review]
Thank you!

We may decide to rework the placement of button with a more encompassing review of extension manager UX in the future but for now I believe this is an improvement for the design that we currently have.

**Comment by andrii-i** [comment]
Thank you @krassowski

**Pull request merged**
