### PR TITLE
Allow Object type for option mode in CodeMirrorEditor.IOption

### PR DESCRIPTION
**Pull request by BoPeng**
The `mode` option of [`CodeMirrorEditor.IOption`](https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/src/editor.ts#L937) is passed to [editor.setOption(option, value)](https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/src/editor.ts#L1206) and calls [`codemirror.setOption`](https://codemirror.net/doc/manual.html#setOption) where the [`mode` option](https://codemirror.net/doc/manual.html#config) accepts both a string (e.g. `python`) and an object (e.g. `{name: 'python', version: 3}`). 

Existing definition of [`mode`](https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/src/editor.ts#L937)

```
mode?: string | Mode.ISpec;
```
does not accept the latter case. This PR adds `Object` to the type definition and allows the specification of complete codemirror mode.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
I'm not sure I understand the use case here. Perhaps when you are setting the mode option and it is an object, you can cast it to a `Mode.ISpec`? It would look something like
```typescript
editor.setOption('mode', { name: 'python', version: 3 } as Mode.ISpec);
```
This way, you don't lose the type safety that Typescript affords in the interfaces.

**Comment by BoPeng** [comment]
I am not sure the conversion would be allowed since `ISpec` has fixed fields

```
  export
  interface ISpec {
    ext?: string[];
    name?: string;
    mode: string;
    mime: string;
  }
```
and CodeMirror can accept arbitrary options (e.g. all the Advanced Configuration Options listed for [python mode](https://codemirror.net/3/mode/python/index.html)).

**Comment by ian-r-rose** [comment]
If the `Mode.ISpec` interface is incorrect (and it seems you are right that it is), then I would rather fix the interface than allow for any object to be passed in. I think that we could allow for arbitrary additional JSON properties by doing
```
  export
  interface ISpec {
    ext?: string[];
    name?: string;
    mode: string;
    mime: string;
    [x: string]: JSONValue;
  }
```

**Comment by BoPeng** [comment]
For object-typed `value` in [`setOption(mode, value)`](https://codemirror.net/doc/manual.html#config), `name` is required and all others are optional and mode-specific. You will set`mode` and `mime` as optional in `ISpec`, and having all fields optional is perhaps equivalent to `any`.

**Comment by BoPeng** [comment]
It would work for me but I am not sure if it is safe to do so because `ISpec` must have been defined with non-optional `mime` and `mode` for a reason.. Since @blink1073 wrote the code, perhaps he should comment on this.

**Comment by BoPeng** [comment]
I think there are some mixed up usages of `ISpec` here. 

ISpec reflects `CodeMirror.modeInfo` (e.g. [this structure](https://github.com/codemirror/CodeMirror/blob/32f3d3e95b15e2403684bd75b13a6315a84b4ce9/mode/meta.js#L15)) and is the object returned by CodeMirror functions such as [CodeMirror.findModeByMIME](https://github.com/codemirror/CodeMirror/blob/32f3d3e95b15e2403684bd75b13a6315a84b4ce9/mode/meta.js#L178), and JupyterLab's [findBest](https://github.com/jupyterlab/jupyterlab/blob/184d160f88fd214c608e496d54cb602e4cb40b1f/packages/codemirror/src/mode.ts#L96) function, which is in turn used as

```
setOption('mode', spec.mime)
```
as show in [loadMode of CodeMirror](https://github.com/codemirror/CodeMirror/blob/master/demo/loadmode.html#L49) and [JupyterLab](https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/src/editor.ts#L543). Therefore `ISpec` should not be passed directly to `editor.setOption('mode')` [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/src/editor.ts#L1206) without type checking.

I think a proper fix should be

1. Allow the mode to be `string | Object | ISpec`
2. In [`setOptions`](https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/src/editor.ts#L1181), handle mode as something like
```
    case 'lineWrap':
      if (value instanceof string) {
        let spec = findBest(val);
        editor.setOption('mode', spec.mime);
      } else if (value instanceof ISpec) {
        editor.setOption('mode', val.mime);
      } else {
        editor.setOption('mode', val);
      }
```

Of course `Object` can be properly defined as

```
  export
  interface ICodeMirrorMode {
    name: string;
    [key: string]: JSONValue;
  }
```

**Comment by vidartf** [comment]
> if (value instanceof ISpec)

FYI: You cannot use `instanceof` with interfaces.

**Comment by BoPeng** [comment]
Because I do not see from the source code `value` of `ISpec` type passed to `CodeMirrorEditor.setOption('mode', value)` directly (it would not work anyway), I think we should 
define `ICodeMirrorMode`

```
  export
  interface ICodeMirrorMode {
    name: string;
    [key: string]: JSONValue;
  }
```

and replace `mode` definition in 

```
  export
  interface IConfig extends CodeEditor.IConfig {
    /**
     * The mode to use.
     */
    mode?: string | Mode.ISpec;
```

with 

```
  export
  interface IConfig extends CodeEditor.IConfig {
    /**
     * The mode to use.
     */
    mode?: string | Mode.ICodeMirrorMode;
```

Does this sound like a good plan?

**Comment by ian-r-rose** [comment]
I think that is the correct fix. The other entries in `Mode.ISpec` are not documented anywhere, as far as I can tell, and not consistently applied. I don't think we necessarily need to rename the interface, though.

**Comment by BoPeng** [comment]
I have submitted a patch to define `IMode` and use it for option `mode` of `CodeEdit.IConfig`. The `Mode.ISpec` interface reflects CodeMirror [`modeInfo`](https://github.com/codemirror/CodeMirror/blob/32f3d3e95b15e2403684bd75b13a6315a84b4ce9/mode/meta.js#L15) and will continue to be used for functions such as [findBest](https://github.com/jupyterlab/jupyterlab/blob/184d160f88fd214c608e496d54cb602e4cb40b1f/packages/codemirror/src/mode.ts#L96).

**Pull request merged**
