### PR TITLE
Add raw-loader to devDependencies

### PR DESCRIPTION
**Pull request by maartenbreddels**
Used for loading pieces of text from a file, I'm using it in [ipyvolume](https://github.com/maartenbreddels/ipyvolume) for GL shaders.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Hi Afshin,

that's the behaviour that I expected as well, that it would use the dependency's devDependency. However, when I do:
```bash
$ conda create -n jlab_raw_loader -c conda-forge jupyterlab
$ source activate jlab_raw_loader
$ jupyter labextension install jupyterlab-volume
```
jupyterlab-volume is [found here](https://github.com/maartenbreddels/ipyvolume/blob/master/jslab/package.json)
 and the ipyvolume package [here](https://github.com/maartenbreddels/ipyvolume/tree/master/js)

And it gives me:
```bash
Module not found: Error: Can't resolve 'raw-loader' in '/Users/maartenbreddels/miniconda3/envs/jlab_raw_loader/share/jupyter/lab/staging/node_modules/ipyvolume/src'
 @ ./~/ipyvolume/src/scatter.js 73:26-75 79:46-95 85:48-97 91:65-114
 @ ./~/ipyvolume/src/index.js
 @ ./~/jupyterlab-volume/index.js
 @ ./build/index.out.js
....
```
Adding raw_loader to this file (as I did in the PR) fixed it, does that make sense?

cheers,

Maarten

FIY:
```bash
$ ls /Users/maartenbreddels/miniconda3/envs/jlab_raw_loader/share/jupyter/lab/staging/node_modules/ipyvolume/node_modules        jlab_raw_loader
@jupyter-widgets css-loader       d3-dispatch      d3-format        d3-time          style-loader
@jupyterlab      d3               d3-dsv           d3-queue         d3-time-format
```

**Comment by afshin** [comment]
The line you added to `package.app.json` **does** need to exist, but it should not be added by a person. If you add it to just `package.json`, the next release of JupyterLab will first create a new `package.app.json` file which will contain all of the dependencies in the package.

That's why you are seeing it work when you modify that file, but the actual bugfix is to modify the main `jupyterlab/package.json` and then to make a new JupyterLab release.

cc: @blink1073 just in case I'm incorrect about this.

**Comment by blink1073** [comment]
That is correct.

**Comment by maartenbreddels** [comment]
Just for my understanding, why did the raw-loader not end up in `/Users/maartenbreddels/miniconda3/envs/jlab_raw_loader/share/jupyter/lab/staging/node_modules/ipyvolume/node_modules` ?

**Comment by blink1073** [comment]
Because `package.app.json` is used to create `staging/package.json`, but we only update `package.app.json` when making a release.

**Comment by afshin** [comment]
Because even though it's a dependency, it was accidentally omitted from `jupyterlab/package.json` the last time we made a release and it never got populated into the `package.app.json` file.

That's why when you modify that file, it works for you, as well.

**Comment by blink1073** [comment]
We weren't using the `raw-loader` in the last release, only in master.

**Comment by maartenbreddels** [comment]
But it's a devDependency of ipyvolume, why isn't it there?

**Comment by blink1073** [comment]
Because only the `devDependencies` of the top level package are installed by `npm install`.

**Comment by maartenbreddels** [comment]
Ok, so dependencies and devDependencies are treated different in that sense. Thanks.

**Pull request merged**
