### PR TITLE
Typographical design for the beta

### PR DESCRIPTION
**Pull request by ellisonbg**
* Better separation of ui, content and code typography.
* Unified font scales for content and headings.
* Careful consistency checks between markdown docuemnt and notebooks to amek sure that headings look similar - that cells don't add too much margin above and below.
* Lots of small fixes to various things in rendered HTML.
* fine tuning font colors.
* Use system fonts if available (SF on Mac, Segoe on Win, Helvetica, Arial)

Current PR light:

screen shot 2017-12-20 at 7 00 48 pm

Current PR dark:

screen shot 2017-12-20 at 7 01 37 pm

Master:

screen shot 2017-12-20 at 7 11 53 pm

### CODE REVIEW

**Comment by ellisonbg** [comment]
Fixes #2854

**Comment by ellisonbg** [comment]
Rebased and fixed the link colors - in the above screenshots the L/D theme link colors are reversed - we need light colored links in the dark theme and darker in the light theme for contrast purposes.

**Comment by ellisonbg** [comment]
I am still loading Google Fonts, but we can do away with that if we decide on a good set of system based monospaced fonts. That can come in a separate PR - we should merge this ASAP to avoid lots of conflicts and rebasing...

**Comment by blink1073** [comment]
Looks great, thanks!

**Pull request merged**
