### PR TITLE
Clean up Release Scripts and Test in CI

### PR DESCRIPTION
**Pull request by afshin**
## References
Progress toward jupyterlab/jupyterlab#8195

## Code changes

- Adds a new step to separate NPM publish from the Python release prep
- Adds a smart check for whether published packages are available with up to 10 minutes of sleep
- Adds dry run capability to release process and a test in CI
- Adds a `?reset` to `browser_check` to avoid workspace files influencing the check
- Adds `jupyter_packaging` to `install_requires`, to avoid needing to separately install it to run `python setup.py`

## User-facing changes
N/A

## Backwards-incompatible changes
N/A

### CODE REVIEW

**Comment by blink1073** [comment]
cc @goanpeca @jasongrout

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by jasongrout** [comment]
+1 on separating out the python release preparation. Things look good looking through the code, though I haven't done a release to test it.

Thanks!

**Comment by blink1073** [comment]
I'm making an alpha release right now to try it out.

**Comment by blink1073** [comment]
Easy peasy: https://pypi.org/project/jupyterlab/3.1.0a3/

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.0.x

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.0.x

**Pull request merged**
