### PR TITLE
Refresh yarn.lock.

### PR DESCRIPTION
**Pull request by jasongrout**
I deleted the yarn.lock and did a `jlpm install` to refresh the packages contained in it.

### CODE REVIEW

**Comment by blink1073** [comment]
LGTM, thanks!

**Comment by vidartf** [comment]
Has this gotten / should this get a pass through `yarn-deduplicate -s fewer` to help reduce deduping and consequently final bundle size?

**Comment by jasongrout** [comment]
I did not run it through yarn-deduplicate.

**Comment by jasongrout** [comment]
I did a test running `yarn-deduplicate -s fewer` and then comparing `jlpm run build:dev:prod`. The end result was that this PR (i.e., current master) generates pretty much identically-sized static js files, with one exception where current master (this PR) is 5K *less* than using `yarn-deduplicate -s fewer`.

**Pull request merged**
