### PR TITLE
Integrate open tabs into running panel

### PR DESCRIPTION
**Pull request by ellisonbg**
Todo:

- [x] Make sure the tabsmanager extension is properly and fully removed.
- [x] Hide shutdown buttons and/or section when there are no running items (post-3.0).
- [x] Wire up document icons in open tabs (this can be done after 3.0 if needed).
- [x] Change "SHUT DOWN" text to close icon on a per item basis.
- [x] Change close icon for each section to appropriate text title (Close All, Shutdown All, etc.)
- [x] Remove old open tabs extension.
- [x] Separate index.ts for running extension into separate files.
- [x] Wire up translator for open tabs section.

## References

https://github.com/jupyterlab/jupyterlab/issues/8650

## Code changes

* Adds new section and associated manager and running items to the running extension to represent open tabs.
* Adds optional `detail` to `IRunningItem` to provide a second column of information after the label.
* Adds optional `shutdownLabel`, `shutdownAll`, `shutdownAllConfirmationText`, `shutdownItemIcon` to `IRunningSessions.IManager` to allow sections to customize language and iconography of "shutting down".

## User-facing changes

* No more separate left panel for open tabs.
* Open tabs section is present in the running panel.

Screen Shot 2020-09-04 at 12 19 00 PM

## Backwards-incompatible changes

None.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Updated screenshot:

Screen Shot 2020-08-23 at 5 10 23 PM

**Comment by ellisonbg** [comment]
@blink1073 I will need help on this PR briefly to make sure I am properly removing all the artifacts for the old tabmanager extension.

**Comment by ellisonbg** [comment]
OK, all major things have been addressed other than needing to make sure the old tabmanager extension has been fully and properly removed. Screenshot in initial comments has been updated to reflect the current state.

**Comment by ellisonbg** [comment]
Looks like the tests are failing due to some unrelated documentation links.

**Review by blink1073 — APPROVED** [review]
LGTM, thanks!  I caught one extra integrity change.

**Comment by ellisonbg** [comment]
This is ready to be merged.

**Comment by ellisonbg** [comment]
Nevermind, merge conflict, rebasing.

**Comment by ellisonbg** [comment]
Rebased, should be ready for merging.

**Comment by ellisonbg** [comment]
Also, this is a pain to rebase each time we release (lots of conflicting package.json files), so if we can merge before the next release, that would be nice :-)

**Review by blink1073 — APPROVED** [review]
Thanks!

**Pull request merged**
