### PR TITLE
Update the publish command

### PR DESCRIPTION
**Pull request by blink1073**
Update the publish command to run integrity and not update python

### CODE REVIEW

**Comment by jasongrout** [comment]
running integrity looks good to me, and I'll take your word on the not updating python part. It would be great to sometime to have some docs on how you do a release.

**Comment by blink1073** [comment]
Aside from Release.MD?

**Comment by jasongrout** [comment]
> Aside from Release.MD?

Whew, there it is, right there!

**Comment by blink1073** [comment]
Ha, yep. 😉

**Pull request merged**
