### PR TITLE
Added scroll to Running Panel

### PR DESCRIPTION
**Pull request by kulsoomzahra**
## References

Fix https://github.com/jupyter/notebook/issues/6559

## Code changes

The code changes allow access to all sections of the Running Panel (by scrolling).

## User-facing changes

**Before**

[before.webm](https://user-images.githubusercontent.com/46336830/195672378-05bbe6ba-4084-49d3-93c8-2d936a3ae119.webm)

**After**

[after.webm](https://user-images.githubusercontent.com/46336830/195671350-5d05356a-3d8b-4adc-8c6b-b0cc280b52bb.webm)

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks for working on this @kulsoomzahra!

**Comment by jtpio** [comment]
Not sure the Documentation UI tests failure is relevant, it also seems to be failing on other PRs and the latest commit: https://github.com/jupyterlab/jupyterlab/commit/eadc4262a438c467262f5a61da6cb8d5036e97a0

**Review by fcollonval — APPROVED** [review]
Thanks @kulsoomzahra 

Indeed CI failure is not related. It seems that some math font improvements:

image

above is the old expectation - below is the new snapshot; we can see that the dots are more centered above the variables.

**Comment by krassowski** [comment]
This led to a regression in other panels like file browser:

| Before (single scrollbar) | After (double scrollbar) |
|-----|------|
|  Screenshot from 2022-10-15 14-54-15  | Screenshot from 2022-10-15 14-54-10 |

I will create a new issue for this.

**Pull request merged**
