### PR TITLE
Launcher UX improvements

### PR DESCRIPTION
**Pull request by ellisonbg**
## References

Partial fix for #3795 intended for 1.0. A more ambitious improvement is being done in #5953.

## Code changes

* Each launcher card now has a valid `tabindex` and pressing enter when a card is focused will call `onclick` to open the activity. This enables keyboard interaction with the launcher.
* The title of the card is now the kernel name if it is a notebook or console.

## User-facing changes

* Name of kernel now wraps to 2 lines to make longer kernel names visible.
* Additional styling for active and focus states of cards.

Screen Shot 2019-06-10 at 3 07 06 PM

More examples:

Screen Shot 2019-06-10 at 3 09 36 PM

## Backwards-incompatible changes

None.

### CODE REVIEW

**Comment by blink1073** [comment]
Rebase needed, the CSS will go in base.css following #6395

**Comment by blink1073** [comment]
Ha, I was about to rebase this, but it is against your master branch.  :wink:

**Comment by tgeorgeux** [comment]
Looks good for the minimum we ought to do pre 1.0. Small nit-pick, is it possible to shrink the two lines when there's only one line of text? The margins start looking a little off-balance on the 'other' category. I think it makes sense to leave it for now and address in launcher re-design.

**Comment by jasongrout** [comment]
Failed test is unrelated async timeout in notebook tests.

**Comment by jasongrout** [comment]
This does need to be rebased, though!

@ellisonbg - @blink1073 pointed out that this PR is from your master branch. IIRC, GitHub doesn't allow us to push to your master branch, so we can't do this rebase for you :).

**Comment by jasongrout** [comment]
Superseded by #6587

**Pull request closed without merging**
