### PR TITLE
Compose only the needed property when transforming the settings

### LINKED ISSUE #10872: Toolbar error when opening the file editor on 4.0.0a4
## Description

There are issues on master relating to toolbar, which might be the root cause of the https://github.com/jupyterlab/jupyterlab/pull/10868#issuecomment-901369268

## Reproduce

1. Open a new empty file editor
2. Open console
3. See error in the console:

```
index.ts:863 Uncaught TypeError: extender[label] is not a function
    at Object.delegateLabel (index.ts:863)
    at caption (index.ts:648)
    at CommandRegistry.caption (index.es6.js:242)
    at Object.propsFromCommand (toolbar.tsx:863)
    at Object.children (toolbar.tsx:659)
    at UseSignal.render (vdom.ts:256)
    at finishClassComponent (react-dom.development.js:17485)
    at updateClassComponent (react-dom.development.js:17435)
    at beginWork (react-dom.development.js:19073)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
delegateLabel @ index.ts:863
caption @ index.ts:648
CommandRegistry.caption @ index.es6.js:242
propsFromCommand @ toolbar.tsx:863
(anonymous) @ toolbar.tsx:659
render @ vdom.ts:256
finishClassComponent @ react-dom.development.js:17485
updateClassComponent @ react-dom.development.js:17435
beginWork @ react-dom.development.js:19073
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22779
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
enqueueSetState @ react-dom.development.js:12467
Component.setState @ react.development.js:365
UseSignal.slot @ vdom.ts:252
invokeSlot @ index.es6.js:459
emit @ index.es6.js:416
Signal.emit @ index.es6.js:99
CommandRegistry.notifyCommandChanged @ index.es6.js:147
(anonymous) @ index.tsx:491
invokeSlot @ index.es6.js:459
emit @ index.es6.js:416
Signal.emit @ index.es6.js:99
(anonymous) @ shell.ts:1416
(anonymous) @ index.es6.js:519
step @ index.es6.js:75
(anonymous) @ index.es6.js:56
(anonymous) @ index.es6.js:49
__awaiter @ index.es6.js:45
factory @ index.es6.js:517
Poll._execute @ index.es6.js:371
execute @ index.es6.js:310
requestAnimationFrame (async)
(anonymous) @ index.es6.js:314
step @ index.es6.js:75
(anonymous) @ index.es6.js:56
fulfilled @ index.es6.js:46
Promise.then (async)
step @ index.es6.js:48
(anonymous) @ index.es6.js:49
__awaiter @ index.es6.js:45
Poll.schedule @ index.es6.js:274
Debouncer.invoke @ index.es6.js:592
_onLayoutModified @ shell.ts:1377
_onCurrentChanged @ shell.ts:1360
invokeSlot @ index.es6.js:459
emit @ index.es6.js:416
Signal.emit @ index.es6.js:99
FocusTracker._setWidgets @ index.es6.js:12514
FocusTracker._evtFocus @ index.es6.js:12532
FocusTracker.handleEvent @ index.es6.js:12495
_focusContent @ mainareawidget.ts:245
onActivateRequest @ mainareawidget.ts:166
Widget.processMessage @ index.es6.js:1401
invokeHandler @ index.es6.js:442
sendMessage @ index.es6.js:187
runMessageLoop @ index.es6.js:492
requestAnimationFrame (async)
enqueueMessage @ index.es6.js:461
postMessage @ index.es6.js:229
Widget.update @ index.es6.js:1209
set @ index.es6.js:8244
TabBar._evtMouseDown @ index.es6.js:8722
TabBar.handleEvent @ index.es6.js:8540
Show 13 more frames
react-dom.development.js:20085 The above error occurred in the <UseSignal> component:

    at UseSignal (http://localhost:8854/static/lab/packages_ui-components_lib_index_js.01e719bc4f74d236be47.js:3037:9)
    at CommandToolbarButtonComponent (http://localhost:8854/static/lab/packages_ui-components_lib_index_js.01e719bc4f74d236be47.js:2636:125)
```

Screenshot from 2021-08-18 20-27-42

## Expected behavior

No errors.

## Context

- Browser and version: Chrome 92
- JupyterLab version: 4.0.0a4

### PR DESCRIPTION
**Pull request by fcollonval**
## References

The user text editor configuration are not taken into account because the custom transformation is not loading properties other than the toolbar one.

Not addressing ~~#10872~~ but addressing https://github.com/jupyterlab/jupyterlab/pull/10868#issuecomment-901369268

## Code changes

Initialize the composite and user settings with the default values. Then override only the property requiring transformation.

## User-facing changes

Text editor are taken into account.

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by Mithil467** [comment]
I ran this branch, and noticed that the error was still occuring twice for me.
I am not sure if this helps but printing the value of `label` and `extender[label]` here
https://github.com/jupyterlab/jupyterlab/blob/5a9da1aa1dd286483858a10a06d4161303567148/packages/mainmenu-extension/src/index.ts#L849
gives this in console output -
image

As we see, the value of `extender[label]` is undefined for label `runCaption`.

**Comment by fcollonval** [comment]
Thanks for testing it out @Mithil467 

This is tricky and live in some chicken-egg problem it seems because it appears randomly in the tests I did (and did not appear when I prepare this PR :confused: ). So it is still needed to correct the Text editor user configuration. But indeed it does not address #10872

**Comment by krassowski** [comment]
Would it make sense to add a very simple Galata test to ensure that the user settings are being used when creating an editor?

**Review by krassowski — APPROVED** [review]
Does what it says. If you have time to add a galata test, I can suggest testing with:

```
{
    "editorConfig": {
        "rulers": [
            40
        ]
    }
}
```

**Comment by fcollonval** [comment]
@meeseeksmachine please backport to 3.1.x

**Pull request merged**
