### PR TITLE
Fix legacy support for icons-as-css-background

### PR DESCRIPTION
**Pull request by telamonian**
## References

https://github.com/jupyterlab/jupyterlab/issues/7887#issuecomment-590426912
https://github.com/jtpio/jupyterlab-extension-examples/pull/70#issuecomment-592125370

All interfaces that had an `.iconClass` field now also have an `.icon` field. If `icon` is undefined and `iconClass` is a non-empty string, the interface in question will fall back to the old icon behavior: instead of rendering an svg inside of a container, it will simply set `class=iconClass` on the container.

However, as [spotted by @jtpio](https://github.com/jtpio/jupyterlab-extension-examples/pull/70#issuecomment-592125370), the legacy icons-as-css-background weren't showing up. It turns out that although the DOM was being set up correctly, the icon styling is no longer set up to correctly display background images (eg `background-size` was unset).

## Code changes

Added/fixed up some icon-related CSS classes, and made some small tweaks to the icon stylesheets. All legacy icons should now show up correctly.

## User-facing changes

Icons-as-css-background should now all be visible. The PR also includes a fix for the coloring of Blueprint icons (currently only used in a "search" icon in the search bars of the extension manager and the json document widget)

## Backwards-incompatible changes

NA

### CODE REVIEW

**Comment by jasongrout** [comment]
Is this needed in 2.0?

**Comment by telamonian** [comment]
In theory there shouldn't be any user visible problems. Instead, some extension devs will be curious/irked as to why their old-style filetype/toolbar/launcher card icons suddenly aren't visible when they try to migrate to 2.0. The solution for them will be to migrate to `LabIcon`. Which is kind of the desired outcome anyway?

**Comment by telamonian** [comment]
So I guess I'd say it should go in, but only if it doesn't significantly delay us cutting the final release

**Comment by jasongrout** [comment]
@blink1073 - your call, then, since you are planning to cut the release tomorrow.

**Comment by jtpio** [comment]
> In theory there shouldn't be any user visible problems. Instead, some extension devs will be curious/irked as to why their old-style filetype/toolbar/launcher card icons suddenly aren't visible when they try to migrate to 2.0. The solution for them will be to migrate to LabIcon. Which is kind of the desired outcome anyway?

Maybe this could be listed as part of the migration guide indeed. That sounds like a reasonable option for now, although it would be nice to have in 2.0.x or 2.x.

**Comment by telamonian** [comment]
I've fixed/tested legacy icon support for:

- filetype icons
  - main area tabs
  - tab manager tabs
  - sidebar tabs
  - filebrowser listing
- command icons
  - launcher section header
  - launcher card
  - menu items
- settings editor item icons
- toolbar button icons

I think that covers all of the places where an icon passed into core by an extension can get used

**Comment by telamonian** [comment]
@saulshanabrook I believe this was included as part of the 2.0.0 release, not a 2.1.x release

**Comment by saulshanabrook** [comment]
Ah thanks for the catch max!

**Pull request merged**
