### PR TITLE
Show kernel ID for notebooks and consoles in list view

### LINKED ISSUE #15991: Display kernel ID in the list view of kernels in the sidebar
> about the table view; should we display the kernel id in a second column (a bit like last modified in the file browser)? Otherwise the kernels section does not bring lots of information compare to the open tabs.

_Originally posted by @fcollonval in https://github.com/jupyterlab/jupyterlab/pull/15845#pullrequestreview-1933776385_
            

Quick first mockup (probably should be aligned more to the right and maybe does not need the parentheses, but just to give the idea what this is about):

mockup

### PR DESCRIPTION
**Pull request by gderocher**
## References
Fixes #15991 

## Code changes
Added name() function to return the name of children (previously done by label). 
Reimplemented label function to display kernel ID through a ReactNode. 

## User-facing changes
Kernel ID displays for all notebooks and consoles in both list and tree view. 
Planning on updating so the ID only shows in list view. 

After Changes: 
image
image

### CODE REVIEW

**Comment by krassowski** [comment]
Thanks for starting this @gderocher. To make it show up conditionally you will need to add something like:

```css
.jp-mod-kernel-widget .jp-RunningSessions-item-label-kernel-id {
   display: none;
}

.jp-mod-running-list-view .jp-mod-kernel-widget .jp-RunningSessions-item-label-kernel-id {
   display: inline;
}
```

to [`packages/running/style/base.css`](https://github.com/jupyterlab/jupyterlab/blob/main/packages/running/style/base.css)

**Comment by krassowski** [comment]
It also looks like this PR needs rebasing or merging with the main branch to resolve conflicts.

**Comment by krassowski** [comment]
I would suggest you try rebasing on `main` and force push to this PR.

**Comment by RyanWilson20** [comment]
Should have the merge all set now. Should we do anything to remove all the extra tags that got added in the mishap?

**Comment by krassowski** [comment]
This looks like a problem with labeler - it should remove the labels automatically.

**Comment by krassowski** [comment]
@gderocher are you interested in finishing up this PR? Is it ready for review (currently it is still marked as a draft)?

**Review by fyqazainol — APPROVED** [review]

**Comment by krassowski** [comment]
Needs some work around `undefined` state:

running-modal-actual

**Review by krassowski — APPROVED** [review]
Thank you @gderocher!

**Pull request merged**
