### PR TITLE
Update Python icon to be PSF Trademark compliant

### LINKED ISSUE #13023: Trademark issue with wrong use of an altered Python logo in Jupyter Lab Launcher
## Description

Hi there, I am Marc-Andre Lemburg, co-chair of the PSF Trademarks Committee. We have become aware of an issue with the use of the Python logo in Jupyter Lab:

gafflfbmefdngbfl

The blue logo changes the shape of the logo and is thus not correct use of the logo according to our trademark guidelines: https://www.python.org/psf/trademarks-faq/

Could you please replace the logo with the correct unchanged logo (as seen for other items in the screenshot) ? That would resolve the issue.

If you have questions regarding the correct use of the Python logo, please write to the PSF Trademarks Committee <psf-trademarks@python.org>.

Thank you.

## Reproduce

Open the "Launcher" in Jupyter Lab.

## Expected behavior

See above.

### PR DESCRIPTION
**Pull request by ajbozarth**
The current python icon was custom made for JupyterLab in it's early alpha phase and doesn't comply with the PSF Trademark.

## References

Fixes #13023

## Code changes

This replaces that icon with one derived from the offical icon svg as provided at https://www.python.org/community/logos/

In order to support use as a `LabIcon` and use JupyterLab styling the svg was simplified. The remaining svg uses the same paths and the same colors, but without the opacity gradient.

## User-facing changes

The blue Python icon used across JupyterLab (e.g., in file browser and launcher) has been replaced with the official dual color logo.

Screenshots:

Light Mode:
Screen Shot 2022-09-01 at 11 24 19 AM

Light Mode (file selected):
Screen Shot 2022-09-01 at 11 24 29 AM

Dark Mode:
Screen Shot 2022-09-01 at 11 24 50 AM

Dark Mode (file selected):
Screen Shot 2022-09-01 at 11 25 05 AM

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by ajbozarth** [comment]
@malemburg and @DavidMertz does this update address your concerns? And should I email a link to this PR to psf-trademarks@python.org about using the icon or should I include any other information?

**Comment by ellisonbg** [comment]
I believe this PR (https://github.com/jupyterlab/jupyterlab/pull/12673) has the same change but also improves the underlying CSS class structure. But fine with the idea in either case.

**Comment by ajbozarth** [comment]
@ellisonbg That point was brought up during todays dev call and it was decided that given the issue was raised by the PSF Trademark Committee that we should expedite this and open a separate PR. Also while opening this PR I found that the icon it that PR (which I provided) was not derived from the currently available version of the Python Logo. So I actually derived the svg in this PR from scratch based on the official svg.

I do believe that we should also make the changes in #12673 as well and intentionality did not include any of the pitched css classes from that PR in the new svg file here (it will have to make those updates after rebasing)

**Comment by ellisonbg** [comment]
Sounds like a good plan, thanks

**Comment by ajbozarth** [comment]
Update: I have email confirmation that the PSF Trademark Committee has approved of the updated icon, the email response has also been forwarded to the Council for the record.

**Comment by malemburg** [comment]
On 01.09.2022 01:57, Alex Bozarth wrote:
> @malemburg <https://github.com/malemburg> and @DavidMertz 
> <https://github.com/DavidMertz> does this update address your concerns? 
> And should I email a link to this PR to ***@***.*** 
> ***@***.***> about using the icon or should I 
> include any other information?

This is fine, thanks.

-- 
Marc-Andre Lemburg
http://www.malemburg.com/

**Comment by fcollonval** [comment]
bot please update snapshots

**Review by fcollonval — COMMENTED** [review]
Thanks a lot @ajbozarth 

I triggered the integration test snapshot update and we will be good to go.

> License CI failure is not related to this one.

**Comment by krassowski** [comment]
Can we add a little bit of margin so that the icon is not bigger than all other icons (see snapshots below). I think it does not have to be as wide as it was with the blue icon, but I believe it would be more consistent if the overall size of the icons was the same as of the notebook icon.

Screenshot from 2022-09-01 09-50-23
Screenshot from 2022-09-01 09-50-00
Screenshot from 2022-09-01 09-49-45

**Comment by ajbozarth** [comment]
> Can we add a little bit of margin so that the icon is not bigger than all other icons

I would argue that this is bad practice for svgs. Spacing and markings like that should be handled with css, not hard-coded into the svg files.

Based on your point though it would be worth a followup to remove the extra margin from our other svgs and update our css to address the change. We could potential tackle this alongside the changes in https://github.com/jupyterlab/jupyterlab/pull/12673

**Comment by krassowski** [comment]
I'm indifferent to that, but since all other icons have padding and we are going to backport this PR to 3.4 I would suggest keeping the padding for now and changing as you suggest in a follow up PR.

**Comment by ajbozarth** [comment]
>  we are going to backport this PR to 3.4

I'd be willing to commit a padded version in a back port for easier compatibility but I'd rather not commit a bad practice SVG to master, but if most reviewers agree with you I'm willing to back off on this.

For fair reference here's the same screenshots as above with a proportional margin added the the SVG file (I have it saved locally for now):
Screen Shot 2022-09-01 at 11 24 19 AM
Screen Shot 2022-09-01 at 11 24 29 AM
Screen Shot 2022-09-01 at 11 24 50 AM
Screen Shot 2022-09-01 at 11 25 05 AM

**Comment by ajbozarth** [comment]
> I'm willing to back off on this

After discussing this with my team and doing a bit more research it seems there is one big use case for SVGs having extra white space and it matches a few of our use cases: icons designed to sit inline with text. In that case the extra space allows for better alignment with tails in letters like y and g. As such I'll push my update as pictured above.

**Comment by ajbozarth** [comment]
bot please update snapshots

**Comment by krassowski** [comment]
Thanks! I will close and re-open to kick the CI for some reason bot commits did not trigger full run.

**Review by fcollonval — APPROVED** [review]
Thanks @ajbozarth for the PR, @malemburg for the support and all others involved.

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.4.x

**Comment by ajbozarth** [comment]
I'll follow the back port steps and open that PR shortly

**Pull request merged**
