### PR TITLE
Build cleanup

### PR DESCRIPTION
**Pull request by blink1073**
- Fix resolving dependencies for linked packages
- Fix installation of dependencies for installed packages on npm 5

### CODE REVIEW

**Comment by SimonBiggs** [comment]
I had a regression with installation with the following extension when upgrading to 0.28.0rc0:
https://github.com/SimonBiggs/jupyterlab-form

Let me know if you would like anymore info. I imagine a rc1 is probably coming out after this pull request so I'll let you know how that one goes.

**Comment by blink1073** [comment]
Were you using `jupyter labextension link`?  The first bullet is meant to fix a regression with `link`.  The second is meant to fix the problem you had in #3082 where you had needed to `jupyter lab clean` when installing an extension with npm 5.

**Comment by SimonBiggs** [comment]
I was using link. Did you want me to try with just a plain install?

**Comment by blink1073** [comment]
I'd say wait for `rc1` and try link again.

**Comment by SimonBiggs** [comment]
If it is any help, I gave just a plain install a try and it also regresses. The error message occurs during the webpack. I'll retry on master branch.

```bash
WARNING in ./~/@angular/compiler/@angular/compiler.es5.js
(Emitted value instead of an instance of Error) Cannot find source file 'compiler.es5.ts': Error: Can't resolve './compiler.es5.ts' in '/home/simon/.pyenv/versions/3.5.3/share/jupyter/lab/staging/node_modules/@angular/compiler/@angular'
 @ ./~/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js 7:0-72
 @ ./~/jupyterlab-form/lib/index.js
 @ ./build/index.out.js
```

**Comment by SimonBiggs** [comment]
Can confirm that after updating my local branch to include this pull request the regression still occurs.

**Comment by blink1073** [comment]
@SimonBiggs, does it work if you make this modification to `webpack.config.js` and run `jupyter lab build`?  https://github.com/angular/angular-cli/issues/7115#issuecomment-318144405

**Comment by SimonBiggs** [comment]
@blink1073 If this is an issue on my end I'm happy to wait until later if you like. Just let me know.

When you say `webpack.config.js` do you mean the config sitting in `lab/staging` ? I myself am not using any webpack in my own extension, on purpose, I'm leaving that to jupyterlab.

**Comment by blink1073** [comment]
If you change the one in `lab/staging` you can run `npm run build` from that directory.  Running `jupyter lab build` overwrites the `webpack.config.js` using the one in the source directory.

**Comment by SimonBiggs** [comment]
So, the `source-map-loader` line looks like the following:

```json
{ test: /\.js$/, use: ['source-map-loader'], enforce: 'pre', exclude: /vega-lite/},
```
It seems like the wrong thing to do to exclude node_modules at all in this case :/... Unfortunately I don't really know what that link of code is doing so I can't grok where I should go with it.

**Comment by blink1073** [comment]
Hmm, we could instead update the `include` to be `/@jupyterlab/`.

**Comment by SimonBiggs** [comment]
I'm really quite beginner in all this, so I'm not entirely sure what that means.

**Comment by blink1073** [comment]
I'm looking into it now.

**Comment by SimonBiggs** [comment]
kk

**Pull request merged**
