### PR TITLE
Await pending directory change in filebrowser model.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Possible fix for #4009.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
@timkpaine For posterity, can you comment on whether this fixes the issue?

I am not completely convinced that there is *no* way to generate a race condition after this fix, since there is some subtle logic involving scheduling auto-refreshes of the file browser model (which are not awaited). However, I think this should at least address one class of race condition.

**Comment by timkpaine** [comment]
@ian-r-rose sure, this seems to fix the particular issue of when you specify a default_url pointing to something like `/lab/tree/path/to/dir`, where that dir has \<\<\< # of files of the top level dir. Previously, the initial listing of the top level dir came back after the subdirectories, and clobbered the file browser (while leaving the launcher pointing to the subdir).

**Comment by timkpaine** [comment]
@ian-r-rose this should also resolve the race condition of `cd` ing between directories quicker than they can be fetched and ending up in the wrong one. (though as you said, this may also have bad interplay with the auto refresh `cd`s).

**Comment by ian-r-rose** [comment]
I think `cd`ing into multiple directories should work okay, since those should be properly `await`ed or handled in a `Promise` resolver. I believe the problem here is in the initial `refresh()` called upon construction of the file browser model, which is not `await`ed.

I'm trying to construct a test that will catch this, but it's fiddly stuff.

**Comment by blink1073** [comment]
Thanks!

**Comment by blink1073** [comment]
@meeseeksdev, backport to 0.34.x

**Pull request merged**
