### PR TITLE
Clean up Frontend Typings

### PR DESCRIPTION
**Pull request by jtpio**
## References

This is a continuation of #11196.

## Code changes

- [x] Allow alternate `ServiceManager` implementations in `JupyterFrontEnd`.  Specifically this allows the use of a mock manager.
- [x] Make the `JupyterLab.IOptions` more permissive: do not require a shell when options are given and allow a shell that meets the `ILabShell` interface
- [x] Change the `language` used in the mock `irkernel` to get some diversity in the kernel data for testing purposes
- [x] Document breaking changes in https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#jupyterlab-3-x-to-4-x. **edit**: docs preview available here: https://jupyterlab--11537.org.readthedocs.build/en/11537/extension/extension_migration.html#api-breaking-changes

## User-facing changes

None

## Backwards-incompatible changes

Consumers relying on the concrete `ServiceManager` have to be updated.

### CODE REVIEW

**Comment by jtpio** [comment]
Some tests are failing due to the major version bump, since the packages have not been published to npm yet.

**Comment by jtpio** [comment]
For reference this seems to be working fine on Binder:

image

Also the major version bump does not prevent the prebuilt `jupyterlab-link-share` extension defined here to be activated:

https://github.com/jupyterlab/jupyterlab/blob/a353063ba61cf6298e853ab3ad841f73da07032e/binder/environment.yml#L5

Although webpack logs some warnings in the dev tools console:

image

**Comment by jtpio** [comment]
The failing CI checks will require a new `4.0` alpha release to be done as a follow-up. Which I'm happy to do after the PR is merged.

This will also help other PRs that introduce breaking changes to avoid merge conflicts on many packages, since the version bump is done here in one go. And closes https://github.com/jupyterlab/jupyterlab/pull/11600.

cc @blink1073 if you would like to have a quick look, since this is a continuation of the original PR started in https://github.com/jupyterlab/jupyterlab/pull/11196, now rebased onto the latest `master`.

**Review by blink1073 — APPROVED** [review]
Thanks for picking this up @jtpio, looks good to me!

**Comment by jtpio** [comment]
Thanks @blink1073!

Moving forward with this and making a new alpha release right after.

**Pull request merged**
