### PR TITLE
Add cell tool with dropdown menu at property inspector

### PR DESCRIPTION
**Pull request by AdrySky**
## References

[Cell tools for editable, collapsed, and scrolled state · Issue #6078 · jupyterlab/jupyterlab · GitHub](https://github.com/jupyterlab/jupyterlab/issues/6078)
Not a checkbox but a dropdown menu.

## Code changes

- Add cell tool selector in notebooktools
- Add 4 option to the selector (Read-Only, Non-Deletable, Collapsed, Output-Scrolled)
- Put the cell tool selector above the slide type selector

## User-facing changes

A faster option at the property inspector to make the cell's non-editable, non-deletable, input-collapsed and output scrollable

### Added cell tool at property inspector
Cell tool

### 4 option to choose from
4 option

## Notes

Still works in progress. Not a clean code as most of the codes are cramp in a single file. The code still does what it intended. For the 'Collapsed' option, as the collapser div still exist, it'll cause conflict when chosen it while clicking the collapser div.

### CODE REVIEW

**Comment by telamonian** [comment]
This seems like a neat idea.

Without getting into the code for the moment, there's an obvious problem with the UI/UX design in the current version of this PR: your four cell states:

> (Read-Only, Non-Deletable, Collapsed, Output-Scrolled)

are not mutually exclusive. For example, it's easy to imagine a non-deletable cell that has also been collapsed. However, your "Cell Tools" dropdown element will only allow one of these flags to be set on a cell at a time. Thus, you're going to need a different approach to UI.

**Comment by telamonian** [comment]
Also, "Cell Tools" is an ambiguous name. Something like "Cell Flags" or "Cell Options" would be more descriptive and clearer

**Comment by AdrySky** [comment]
I was intended to push this to my forked repo but accidentally pushed here. I was not meant to show my horrible work to everyone.   

Anyway, thank you @telamonian for the feedback and advice. Yeah, a lot of things needed to be done as you can only use one flag at a time. I wanted to use a checkbox UI but don't know how. I also don't know how to import dependencies in a file. Is there any docs for me to read that can help solve this issue?

Also, should I close this PR since it's an accidental PR?

**Comment by telamonian** [comment]
> I wanted to use a checkbox UI but don't know how.

When you're starting out, by far the best to way to learn how to do UI in jlab is to start by just copying existing code and then modifying that. The closest extant thing to what you'd want is the "find/replace options" UI:

image

which is implemented in [`packages/documentsearch`](https://github.com/jupyterlab/jupyterlab/blob/398fcb1498895dbf244ce868597115de4352e263/packages/documentsearch/src/searchoverlay.tsx#L309-L351):

https://github.com/jupyterlab/jupyterlab/blob/398fcb1498895dbf244ce868597115de4352e263/packages/documentsearch/src/searchoverlay.tsx#L309-L351

The downside is that the checkbox component here is react based, which might make that code snippet a bit harder to wrap your head around at first. This is a pretty simple component, though, so overall it will hopefully be easy enough to work with. The one catch is that in order to write react code, you have to use the `*.tsx` file ending instead of `*.ts`.

> Also, should I close this PR since it's an accidental PR?

We're happy to have your PR, and you're more than welcome to keep working on it here. Just keep the PR in draft until it's  ready for review. And if you need any specific help, feel free to ask on https://discourse.jupyter.org/ or https://gitter.im/jupyterlab/jupyterlab

**Pull request closed without merging**
