### PR TITLE
Update interface shot with Lorenz example.

### PR DESCRIPTION
**Pull request by jasongrout**
The Lorenz equation example is one of the most-used notebooks for the classic Notebook, so there's something comforting about using it for our Lab example. This screenshot also shows off tearing out outputs with controls, which is nice. Also, the example illustrates something has been painful before, i.e., having a library file side by side with the notebook.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
The current interface page has all of the screenshots and videos using the same (or at least similar) layout, from the `jupyterlab-demo` repository, which gives it a nice consistency.

**Comment by jasongrout** [comment]
ah, good point. You mean the files shown particularly? And you probably noticed I manually adjusted the file browser width...

**Comment by jasongrout** [comment]
or do you also mean the explicit layout, i.e., how things are arranged?

**Comment by ian-r-rose** [comment]
Yes, I meant the explicit layout.

Also, very tricky with the file browser width :)

**Comment by jasongrout** [comment]
I think we should change the default. Working at this small screensize, the width is taking up a *lot* of room.

**Comment by jasongrout** [comment]
Okay. How about I put this screenshot in the very top-level overview? http://jupyterlab.readthedocs.io/en/stable/

**Comment by ian-r-rose** [comment]
That sounds good to me.

I agree that the filebrowser is a bit large, though we should also look at the width-requirements of the other tab panels.

**Comment by jasongrout** [comment]
> we should also look at the width-requirements of the other tab panels.

Agreed. I'll file a PR.

**Comment by jasongrout** [comment]
@ian-r-rose - how about that?

**Comment by ian-r-rose** [comment]
Thanks!

**Pull request merged**
