### PR TITLE
Remove Blueprint

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/6890
Closes https://github.com/jupyterlab/jupyterlab/issues/6590
Quid of https://github.com/jupyterlab/jupyterlab/issues/7574

## Code changes

- Drop Blueprint JS
- Add some React components to replace those from Blueprint:
  - `Button`
  - `Collapse`
  - `InputGroup`
- Remove unused components: `Select` and `Checkbox`
- Remove unused exported `Intent`
- [x] Bump major version of `@jupyterlab/ui-components`

Additional changes:
- Example tests are now using Playwright instead of puppeteer
- ServerConnection has been modified to tolerant undefined `process.env` (following removing a webpack patch for Blueprint in the examples)
- Explicitly resolve react to v17 because storybook is requiring v16. This results in two versions of react in `node_modules` that generates error on unit tests rendering a react LabIcon.
- [x] Start 4.0 migration guide

## User-facing changes

N/A (Hopefully - although the components are simpler and may lack some advanced transition or shadow effects).

## Backwards-incompatible changes

Downstream extensions using the proxied Blueprint component will need to explicitly use the Blueprint component as only the part of the API used in JupyterLab core was added to the remaining components.

Style changes:
- Shift of 1px of icon in button due to the removal of the blueprint icon wrapper (did not find where that additional pixel is coming). But the size of the button itself is not changed.
- BlueprintJS was defining a default font size of 14px on `body`. This has been replace by a font size of `var(--jp-ui-font-size1)` that equals 13px. This impacts the text in the inspector panel when the current widget is not a notebook for example. But at least all texts are themed. So I considered that regression as acceptable.

### CODE REVIEW

**Comment by krassowski** [comment]
From screenshots it seems that there are significant changes in top/bottom margin/padding of buttons and other elements (like TOC, where I think we should keep more compact layout). Are you planning to address those in this PR?

**Comment by fcollonval** [comment]
> From screenshots it seems that there are significant changes in top/bottom margin/padding of buttons and other elements (like TOC, where I think we should keep more compact layout). Are you planning to address those in this PR?

Yes I think it makes more sense to have almost no visual regression on this one. I need to look a bit deeper in the change you are mentioning as they don't come from the explicitly used components but from general style rules leaking outside Blueprint component that are no more imported. Hopefully they are not too many of them...

**Comment by fcollonval** [comment]
There is a one-pixel change on toolbar button icon:

code-cell-diff

In Blueprint js there is an additional `span` element wrapping the icon that get a height of _icon height + 1px_. But I cannot figure out where this additional pixel is coming from. As this does not change the height of the button itself, I updated the screenshot assuming this is an acceptable visual regression.

**Comment by fcollonval** [comment]
> FYI Impact on the bundle size using the info from the check release step

master 4c8bcf7

assets by info 7.62 MiB [immutable]
  assets by chunk 4.75 MiB (id hint: vendors)
    assets by status 3.32 MiB [big] 7 assets
assets by chunk 2.79 MiB (auxiliary id hint: vendors)
  assets by path *.svg 1.73 MiB 3 assets
  assets by path *.eot 363 KiB 3 assets
  assets by path *.ttf 362 KiB 3 assets
  assets by path *.woff 203 KiB 3 assets
  assets by path *.woff2 164 KiB
    asset 1551f4f60c37af51121f106501f69b80.woff2 76.4 KiB [emitted] (auxiliary id hint: vendors)
    asset d878b0a6a1144760244ff0665888404c.woff2 74.9 KiB [emitted] (auxiliary id hint: vendors)
    asset 7a3337626410ca2f40718481c755640f.woff2 12.9 KiB [emitted] (auxiliary id hint: vendors)
asset third-party-licenses.json 275 KiB [emitted] [big]
asset index.html 1.56 KiB [emitted]
orphan modules 5.08 MiB [orphan] 1288 modules
runtime modules 111 KiB 14 modules
built modules 14.2 MiB (javascript) 4.59 KiB (share-init) 4.59 KiB (consume-shared) [built]
  modules by path ./node_modules/ 14.2 MiB
    javascript modules 14.2 MiB 1047 modules
    json modules 33.2 KiB 6 modules
  provide-module modules 4.59 KiB 112 modules
  consume-shared-module modules 4.59 KiB
    modules by path consume shared module (default) @jupyterlab/ 3.65 KiB 41 modules
    modules by path consume shared module (default) @lumino/ 588 bytes 14 modules
  modules by path ./build/ 23.5 KiB
    ./build/bootstrap.js 3.86 KiB [built] [code generated]
    ./build/index.out.js + 1 modules 19.7 KiB [built] [code generated]


---

This PR c7be037

assets by info 6.41 MiB [immutable]
  assets by chunk 3.54 MiB (id hint: vendors)
    assets by status 2.11 MiB [big] 6 assets
assets by chunk 2.79 MiB (auxiliary id hint: vendors)
  assets by path *.svg 1.73 MiB 3 assets
  assets by path *.eot 363 KiB 3 assets
  assets by path *.ttf 362 KiB 3 assets
  assets by path *.woff 203 KiB 3 assets
  assets by path *.woff2 164 KiB 3 assets
asset third-party-licenses.json 205 KiB [emitted]
asset index.html 1.56 KiB [emitted]
orphan modules 4.47 MiB [orphan] 1156 modules
runtime modules 110 KiB 14 modules
built modules 12.4 MiB (javascript) 4.59 KiB (share-init) 4.59 KiB (consume-shared) [built]
  modules by path ./node_modules/ 12.4 MiB
    javascript modules 12.4 MiB 963 modules
    json modules 33.2 KiB 6 modules
  provide-module modules 4.59 KiB 112 modules
  consume-shared-module modules 4.59 KiB
    modules by path consume shared module (default) @jupyterlab/ 3.65 KiB 41 modules
    modules by path consume shared module (default) @lumino/ 588 bytes 14 modules
  modules by path ./build/ 23.5 KiB
    ./build/bootstrap.js 3.86 KiB [built] [code generated]
    ./build/index.out.js + 1 modules 19.7 KiB [built] [code generated]

**Comment by krassowski** [comment]
> In Blueprint js there is an additional span element wrapping the icon that get a height of icon height + 1px. But I cannot figure out where this additional pixel is coming from. As this does not change the height of the button itself, I updated the screenshot assuming this is an acceptable visual regression.

It looks better to me after, so I would call it an improvement ;)

**Comment by krassowski** [comment]
Would it be a good idea to start writing extension migration guide for 4.0 in this PR to document this change?

**Comment by jasongrout** [comment]
> Explicitly resolve react to v17 because storybook is requiring v16. This results in two versions of react in `node_modules` that generates error on unit tests rendering a react LabIcon.

What advantage do we have from storybook? I've had problems with storybook in the past when trying to upgrade packages as well. Is anyone using storybook in JupyterLab?

**Comment by fcollonval** [comment]
Personally I never used storybook in JupyterLab. So I'm fine to drop it (although I would suggest doing it in a separate PR).

**Comment by krassowski** [comment]
The new implementation of `InputGroup` does not implement style for `disabled` attribute; on 3.x:

Screenshot from 2021-10-29 19-18-46

On this PR:

Screenshot from 2021-10-29 19-18-53

The blueprint styles for the disabled state for input group:

```css
    background: rgba(206, 217, 224, 0.5);
    -webkit-box-shadow: none;
    box-shadow: none;
    color: rgba(92, 112, 128, 0.6);
    cursor: not-allowed;
    resize: none;
```

Let's add at least cursor and background (does not have to be exactly the same)

**Review by krassowski — COMMENTED** [review]
Looks great, I would suggest two changes before merging:
- adding the missed style for `disabled` state of `InputGroup`
- reviewing suggestions on the documentation grammar and the missing 3.0 → 3.1 heading

The visual tests show three changes:
- The toolbar icons moved one pixel up, which looks better than before (visually more centered) so I would like to keep this change as mentioned earlier
- There is also some (sub-?)pixel change in top/bottom margins of outputs after images, visible on `galata/test/galata/notebook.spec.ts-snapshots/example-run-galata-linux.png` and `galata/test/jupyterlab/notebook-run.test.ts-snapshots/notebook-panel-0-jupyterlab-linux.png` but I could not figure it out when comparing the elements with inspector. I believe that it is acceptable, just documenting the change here.
- Very minor and non-blocking, the font size in inspector got reduced (`galata/test/jupyterlab/sidebars.test.ts-snapshots/opened-sidebar-jp-property-inspector-jupyterlab-linux.png`) by 1px; it is not critical to change, I think that  larger font is better here because the centered text may be missed on larger monitors.

**Comment by fcollonval** [comment]
Thanks for reviewing @krassowski 

>     * Very minor and non-blocking, the font size in inspector got reduced (`galata/test/jupyterlab/sidebars.test.ts-snapshots/opened-sidebar-jp-property-inspector-jupyterlab-linux.png`) by 1px; it is not critical to change, I think that  larger font is better here because the centered text may be missed on larger monitors.

BlueprintJS was defining a default font size of 14px on body. This has been replaced by a font size of var(--jp-ui-font-size1) that equals 13px. This impacts the text in the inspector panel when the current widget is not a notebook for example. But at least all texts are themed. So I considered that regression as acceptable.

**Review by krassowski — APPROVED** [review]
LGTM, thank you!

**Comment by jtpio** [comment]
>  FYI Impact on the bundle size using the info from the check release step

This is also a nice side-effect!

**Pull request merged**
