### PR TITLE
Update reference snapshot for the completer UI test

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/11843

## Code changes

Update reference snapshot.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
UI Tests CI check is now green: https://github.com/jupyterlab/jupyterlab/runs/4792657220?check_suite_focus=true

image

**Review by fcollonval — APPROVED** [review]
Thanks a lot @jtpio

**Comment by jtpio** [comment]
@meeseeksdev please backport to 3.3.x

**Comment by jtpio** [comment]
@meeseeksdev please backport to 3.2.x

**Pull request merged**
