### PR TITLE
Update to lerna 4

### PR DESCRIPTION
**Pull request by jtpio**
## References

Which should help fix security issues with some dependencies.

## Code changes

Dependency update.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thank you!

**Review by fcollonval — APPROVED** [review]
Thanks

CI errors are not related

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.1.x

**Comment by blink1073** [comment]
I'm handling the manual backport now

**Pull request merged**
