### PR TITLE
Update several extensions readme files to delete old content.

### PR DESCRIPTION
**Pull request by jasongrout**
## References

This was based on suggestions at https://discourse.jupyter.org/t/what-is-the-2022-way-to-display-javascript-in-a-python-notebook-in-jupyter-lab/12318 by @mwouts.

## Code changes

Updates some extension readme files that were out of date.

## User-facing changes

None.

### CODE REVIEW

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/what-is-the-2022-way-to-display-javascript-in-a-python-notebook-in-jupyter-lab/12318/3

**Review by jtpio — APPROVED** [review]
Thanks for the cleanup!

**Review by fcollonval — APPROVED** [review]
Thanks a lot indeed

Should we backport this to 3.3.x to update the README on npm in case people end up there?

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.3.x

**Comment by jtpio** [comment]
> Should we backport this to 3.3.x to update the README on npm in case people end up there?

Sounds good :+1:

**Pull request merged**
