### PR TITLE
Theme refactor

### LINKED ISSUE #2165: Split default-theme into multiple packages
We have a `default-theme` that contains the theme assets (icons, images), and light/dark theme CSS variables. This layout is going to make is really difficult to build custom themes. We should split it into packages:

* `theme-assets` = everything but the variables.css
* `theme-light` = the light theme
* `theme-dark` = the dark theme

@blink1073 I am thinking we should also have each individual package throw its CSS on the page separately?

### PR DESCRIPTION
**Pull request by ellisonbg**
Fixes #2165 by splitting into multiple packages.

### CODE REVIEW

**Comment by ellisonbg** [comment]
@blink1073 @jasongrout I talked to @sccolbert tonight about this and he thinks we can simplify all this and it will all just work:

* Have each extension import its own CSS files
* Don't include the main css in in the index template
* Disabling an extension will cause its css to not be loaded onto the page.

I will continue to work on simplifying this stuff in the PR, but if this pans out, we can treat themes as lab extensions and just disable them.

**Comment by ellisonbg** [comment]
Closing in favor of #2205.

**Comment by bigquant** [comment]
hello, @ellisonbg, 

when there's a main.css, i did compress and postfix wen build. After the refactor, how to do this?

`    "buildrelease": "webpack && uglifyjs --compress -o build/main.bundle.js --mangle -- build/main.bundle.js && myth build/main.css build/main.css && uglifycss --expand-vars --ugly-comments --output build/main.css build/main.css",
`

**Comment by blink1073** [comment]
Hi @bigquant, we could optionally use the [postcss-loader](https://github.com/postcss/postcss-loader) with a flag to `jupyter lab build`.  Do you mind opening a new issue?

**Pull request closed without merging**
