### PR TITLE
Adjust text alignment in the menu bar

### LINKED ISSUE #16108: Items in main menu bar slightly too low
In Notebook 7.1 and Lab 4.2 beta, items in main menu bar are 1–2 pixels below the center.

In JupyterLab (top) and Jupyter Notebook (bottom) you can see that the pulldown menus have a very similar appearance.

image

The code seems to be imported from the `@jupyterlab/application` package:

https://github.com/jupyterlab/jupyterlab/blob/41be86d5142a793ab9cb8b9eb99f92a33c8dc441/packages/application/style/menus.css#L33-L39

This was originally found by @ellisonbg during a bug bash for Notebook 7.0.0a17, and reported in https://github.com/jupyter/notebook/issues/6786 .

### PR DESCRIPTION
**Pull request by JasonWeill**
## References

Fixes #16108.

## Code changes

Updates menu bar position calculation per @krassowski here: https://github.com/jupyterlab/jupyterlab/issues/16108#issuecomment-2035610870

## User-facing changes

Before:

Screenshot 2024-04-09 at 4 07 30 PM

After:

This is a one-pixel change, a very subtle change in the positioning of menu bar items' titles within the menu bar area.

Screenshot 2024-04-09 at 4 07 46 PM

## Backwards-incompatible changes

None.

### CODE REVIEW

**Comment by JasonWeill** [comment]
please update snapshots

**Comment by JasonWeill** [comment]
Reverted two screen shots per @krassowski:

* galata/test/documentation/general.test.ts-snapshots/shortcuts-help-documentation-linux.png
* galata/test/jupyterlab/notebook-run.test.ts-snapshots/notebook-panel-1-jupyterlab-linux.png

**Comment by krassowski** [comment]
It looks like the examples snapshots need to be updated too. You can download them from https://github.com/jupyterlab/jupyterlab/actions/runs/8637562234/attempts/1?pr=16142 (I restarted the job out of habit before realising why it is failing).

**Review by krassowski — APPROVED** [review]
Thank you @JasonWeill!

**Pull request merged**
