### PR TITLE
Remove unused requires for the tree-resolver plugin

### PR DESCRIPTION
**Pull request by jtpio**
## Code changes

Remove unused `requires` from the `@jupyterlab/application-extension:tree-resolver` plugin, to make it easier to reuse in other lab-based applications.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jasongrout** [comment]
This looks okay to me. @afshin, can you give it a quick look as well - I don't want to mess anything up this close to 3.0.

**Comment by jtpio** [comment]
Yes it would be nice to double check these requires were not added on purpose to sync with the other plugins.

**Comment by jasongrout** [comment]
> Yes it would be nice to double check these requires were not added on purpose to sync with the other plugins.

Yes, that's the only thing I could think of (i.e., that they create an ordering to the plugins). If that's the reason for these dependencies, a comment should be added to the code :).

**Comment by jtpio** [comment]
Just checked locally for potential cases where this could be an issue, for example when launching lab with a path to a notebook.

It seems to be fine. Although it would also be ok to keep these `requires` and add comments instead, if we are not sure whether removing them would introduce issues.

**Comment by jasongrout** [comment]
Let's go for it (since there is no comment there warning us otherwise). If it introduces a problem, we can put them back in.

**Pull request merged**
