### PR TITLE
Redesign of sidebars and buttons

### PR DESCRIPTION
**Pull request by ellisonbg**
This moves the L/R sidebars to be icon based and fixes some issues with our buttons. Still working on the last bits, but targeting for 0.34.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Here is the direction:

screen shot 2018-08-12 at 9 15 51 pm

@tgeorgeux

**Comment by ian-r-rose** [comment]
Cool stuff. This, together with L/R docking will go a long way, I think.

I get the metaphor of the running icon, but to me it also looks a lot like the [exit sign](https://en.wikipedia.org/wiki/Exit_sign), which is a touch confusing. I wonder if something like the run button used on the notebook toolbar, or the kernel icon developed for the status bar, might be clearer.

**Comment by vidartf** [comment]
Does this change require that extensions supply its own icon, or is this change for core extensions only? In general, I'm missing a mechanism for extensions to supply icons that work well with themes (although the PR with `isLight` for the theme helps quite a bit).

**Comment by tgeorgeux** [comment]
This looks good. Did you play around at all with the idea of a smaller 'tab' portion when selected? I'm curious if it would help the selected tab stand out a little bit more. Either way is good with me, looks a lot better than what we had!

**Comment by ellisonbg** [comment]
@vidartf extensions can still use text and it will render fine. If they want to provide an icon:

1) It has to be in our themes, or
2) it has to be shipped with the extension and use the new isLight logic to style itself. That is one reason we were holding off on this one.

@ian-r-rose yeah, we sat with the designers for hours on Friday hunting for good icons to use. I agree with your points, but probably still prefer to running person by a slight margin: The "play" button doesn't quite capture that this panel lets you *view* things that are running but doesn't allow you to run them. The kernel icon doesn't capture that it lists terminals as well. Are you ok with us "running" with this one for now and see how it goes?

**Comment by ian-r-rose** [comment]
Yep, no objection to moving forwards with this for now. I do see the possibility of people confusing it with a exiting/quitting-type action, but we shall see!

**Comment by ellisonbg** [comment]
OK a short update in light of the upcoming release. The current state of PR now has refactored toolbar buttons that are ready for the final styling. Will keep pushing hard on it...

**Comment by ellisonbg** [comment]
Making lots of progress, final todo list:

- [ ] Refactor kernel name button in `apputils/toobar.tsx`
- [ ] Finish styling running sidebar
- [ ] Fix buttons in advanced settings editor
- [ ] Fix styling of dialog buttons
- [ ] Make sure tests are ok
- [ ] Changelog entry

**Comment by ellisonbg** [comment]
@blink1073 Here is the status: everything is working and all styles are updated. However, my brain is mush so I haven't finished fixing the tests. Not sure exactly what is worth doing as the original tests made strong assumptions about the `ToolbarButton` rendering itself in a particular way, with particular children and all as a phosphor Widget + native DOM nodes. In the new approach the Widget is a very thin wrapper around a react component - so none of the properties, event or methods that were there make sense any more. Some of the tests could probably be fixed easily by someone more awake that me, but it also may make sense to delete some of them. This PR is such a huge improvement, I do think it should be merged for 0.34. I will be around briefly in the morning 8-9am PT and then later in the day.

**Comment by ellisonbg** [comment]
OK I am back and will work on the tests now...

**Comment by ellisonbg** [comment]
OK I think the test are passing. I am running them locally and just pushed to let CI do its thing too.

**Comment by ellisonbg** [comment]
OK tests should be fixed now. Rerunning locally and on CI.

**Comment by blink1073** [comment]
Very nice, thanks!

**Comment by nanoant** [comment]
@ellisonbg Just wanted to ask if menu bar is still white in the latest iteration of the design. FYI I reported some issue #4148 about that. If not I am attaching this PR to my issue, as I believe menu should be gray -- which is btw. less intrusive, like rest of the tab bars, and only actively selected item in the menu should be white as it was in the original #16 design.

**Comment by stonebig** [comment]
for Jupyterlab-0.34.2 ?

**Pull request merged**
