### PR TITLE
Bump lerna

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Dependabot alerts https://github.com/jupyterlab/jupyterlab/security/dependabot/82

## Code changes

Bump lerna
Remove unused key in `lerna.json`

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @fcollonval.

Looks like there might be a change missing to the top-level `package.json`?

Also the CI checks didn't seem to be triggered.

**Comment by fcollonval** [comment]
> Looks like there might be a change missing to the top-level `package.json`?

I only run yarn upgrade as dependabot. But sure I can bump the dependency.

**Comment by jtpio** [comment]
The diff seems to be showing unrelated changes: 

image

**Comment by fcollonval** [comment]
> The diff seems to be showing unrelated changes

As mentioned in the description, I took the chance to update URL registry to be consistent and align with https://github.com/jupyterlab/jupyterlab/pull/12742

I can do that in another PR if needed.

**Comment by jtpio** [comment]
> I can do that in another PR if needed.

ah ok, yes that would make it easier to track.

**Comment by fcollonval** [comment]
CI failure is not related

**Pull request merged**
