### PR TITLE
Allow for a global track timing setting

### PR DESCRIPTION
**Pull request by mlucool**
## Code changes

This allows for a global default of whether or not to record timing metadata into the notebook file or not.

## User-facing changes

A notebook setting was added to allow user to opt into this change.

## Backwards-incompatible changes
None.

### CODE REVIEW

**Comment by mlucool** [comment]
cc @Madhu94 

A few comments:
1. I choose to default this new feature off, but I think it would be best to default this on
2. I feel like the toggle notebook timing is not required anymore. I have left this in and they do not fight each other (the toggle gets preference), but it feels somewhat contrived as a notebook setting instead of a global setting.

**Comment by saulshanabrook** [comment]
Hey @mlucool thank you for implementing this. We (@tgeorgeux, @jasongrout, @ellisonbg) had a  discussion about this feature and decided that it might be simpler to just remove the notebook level metadata and just use the global setting, defaulting to off.

If it is off and there is existing execution time, then it should delete the `execution` metadata key when a cell is executed.

**Comment by saulshanabrook** [comment]
@mlucool Lemme know if you want me to tackle this change.

**Comment by mlucool** [comment]
Thanks @saulshanabrook for looking. Sure, you can remove the notebook level feature.

**Comment by saulshanabrook** [comment]
I removed the feature, originally added in https://github.com/jupyterlab/jupyterlab/pull/6864, now I have to update the tests.

**Comment by saulshanabrook** [comment]
I tried this locally and it seems to work. @afshin took a look at it and didn't have any objections.

**Pull request merged**
