### PR TITLE
Automated Changelog Entry for 3.4.5 on 3.4.x

### PR DESCRIPTION
**Pull request by fcollonval**
Automated Changelog Entry for 3.4.5 on 3.4.x
```
Python version: 3.4.5
npm version: @jupyterlab/repo-top: 0.0.1
npm workspace versions:
@jupyterlab/builder: 3.4.5
@jupyterlab/buildutils: 3.4.5
@jupyterlab/template: 3.4.5
@jupyterlab/application-top: 3.4.5
@jupyterlab/example-app: 3.4.5
@jupyterlab/example-cell: 3.4.5
@jupyterlab/example-console: 3.4.5
@jupyterlab/example-federated: 2.5.5
@jupyterlab/example-federated-core: 2.5.5
@jupyterlab/example-federated-md: 2.5.5
@jupyterlab/example-federated-middle: 2.5.5
@jupyterlab/example-federated-phosphor: 2.5.5
@jupyterlab/example-filebrowser: 3.4.5
@jupyterlab/example-notebook: 3.4.5
@jupyterlab/example-terminal: 3.4.5
@jupyterlab/galata: 4.3.5
@jupyterlab/mock-extension: 3.4.5
@jupyterlab/mock-consumer: 3.4.5
@jupyterlab/mock-provider: 3.4.5
@jupyterlab/mock-token: 3.4.5
@jupyterlab/application: 3.4.5
@jupyterlab/application-extension: 3.4.5
@jupyterlab/apputils: 3.4.5
@jupyterlab/apputils-extension: 3.4.5
@jupyterlab/attachments: 3.4.5
@jupyterlab/cell-toolbar: 3.4.5
@jupyterlab/cell-toolbar-extension: 3.4.5
@jupyterlab/cells: 3.4.5
@jupyterlab/celltags: 3.4.5
@jupyterlab/celltags-extension: 3.4.5
@jupyterlab/codeeditor: 3.4.5
@jupyterlab/codemirror: 3.4.5
@jupyterlab/codemirror-extension: 3.4.5
@jupyterlab/completer: 3.4.5
@jupyterlab/completer-extension: 3.4.5
@jupyterlab/console: 3.4.5
@jupyterlab/console-extension: 3.4.5
@jupyterlab/coreutils: 5.4.5
@jupyterlab/csvviewer: 3.4.5
@jupyterlab/csvviewer-extension: 3.4.5
@jupyterlab/debugger: 3.4.5
@jupyterlab/debugger-extension: 3.4.5
@jupyterlab/docmanager: 3.4.5
@jupyterlab/docmanager-extension: 3.4.5
@jupyterlab/docprovider: 3.4.5
@jupyterlab/docprovider-extension: 3.4.5
@jupyterlab/docregistry: 3.4.5
@jupyterlab/documentsearch: 3.4.5
@jupyterlab/documentsearch-extension: 3.4.5
@jupyterlab/extensionmanager: 3.4.5
@jupyterlab/extensionmanager-extension: 3.4.5
@jupyterlab/filebrowser: 3.4.5
@jupyterlab/filebrowser-extension: 3.4.5
@jupyterlab/fileeditor: 3.4.5
@jupyterlab/fileeditor-extension: 3.4.5
@jupyterlab/help-extension: 3.4.5
@jupyterlab/htmlviewer: 3.4.5
@jupyterlab/htmlviewer-extension: 3.4.5
@jupyterlab/hub-extension: 3.4.5
@jupyterlab/imageviewer: 3.4.5
@jupyterlab/imageviewer-extension: 3.4.5
@jupyterlab/inspector: 3.4.5
@jupyterlab/inspector-extension: 3.4.5
@jupyterlab/javascript-extension: 3.4.5
@jupyterlab/json-extension: 3.4.5
@jupyterlab/launcher: 3.4.5
@jupyterlab/launcher-extension: 3.4.5
@jupyterlab/logconsole: 3.4.5
@jupyterlab/logconsole-extension: 3.4.5
@jupyterlab/mainmenu: 3.4.5
@jupyterlab/mainmenu-extension: 3.4.5
@jupyterlab/markdownviewer: 3.4.5
@jupyterlab/markdownviewer-extension: 3.4.5
@jupyterlab/mathjax2: 3.4.5
@jupyterlab/mathjax2-extension: 3.4.5
@jupyterlab/metapackage: 3.4.5
@jupyterlab/nbconvert-css: 3.4.5
@jupyterlab/nbformat: 3.4.5
@jupyterlab/notebook: 3.4.5
@jupyterlab/notebook-extension: 3.4.5
@jupyterlab/observables: 4.4.5
@jupyterlab/outputarea: 3.4.5
@jupyterlab/pdf-extension: 3.4.5
@jupyterlab/property-inspector: 3.4.5
@jupyterlab/rendermime: 3.4.5
@jupyterlab/rendermime-extension: 3.4.5
@jupyterlab/rendermime-interfaces: 3.4.5
@jupyterlab/running: 3.4.5
@jupyterlab/running-extension: 3.4.5
@jupyterlab/services: 6.4.5
@jupyterlab/example-services-browser: 3.4.5
node-example: 3.4.5
@jupyterlab/example-services-outputarea: 3.4.5
@jupyterlab/settingeditor: 3.4.5
@jupyterlab/settingeditor-extension: 3.4.5
@jupyterlab/settingregistry: 3.4.5
@jupyterlab/shared-models: 3.4.5
@jupyterlab/shortcuts-extension: 3.4.5
@jupyterlab/statedb: 3.4.5
@jupyterlab/statusbar: 3.4.5
@jupyterlab/statusbar-extension: 3.4.5
@jupyterlab/terminal: 3.4.5
@jupyterlab/terminal-extension: 3.4.5
@jupyterlab/theme-dark-extension: 3.4.5
@jupyterlab/theme-light-extension: 3.4.5
@jupyterlab/toc: 5.4.5
@jupyterlab/toc-extension: 5.4.5
@jupyterlab/tooltip: 3.4.5
@jupyterlab/tooltip-extension: 3.4.5
@jupyterlab/translation: 3.4.5
@jupyterlab/translation-extension: 3.4.5
@jupyterlab/ui-components: 3.4.5
@jupyterlab/ui-components-extension: 3.4.5
@jupyterlab/vdom: 3.4.5
@jupyterlab/vdom-extension: 3.4.5
@jupyterlab/vega5-extension: 3.4.5
@jupyterlab/testutils: 3.4.5
```

After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | jupyterlab/jupyterlab  |
| Branch  | 3.4.x  |
| Version Spec | next |
| Since | v3.4.4 |

### CODE REVIEW

**Comment by jtpio** [comment]
From this run which seems to correspond to this PR: https://github.com/fcollonval/jupyter_releaser/runs/7762067370?check_suite_focus=true

There is the following in the logs:

```
COMMAND: git fetch origin --filter=blob:none --quiet 3.4.x
COMMAND: git stash
Saved working directory and index state WIP on 3.4.x: ffebe0590 [ci skip] New version
COMMAND: git checkout -b changelog-de3a4ed8188111ed85b96f32d1645301 origin/3.4.x
Switched to a new branch 'changelog-de3a4ed8188111ed85b96f32d1645301'
branch 'changelog-de3a4ed8188111ed85b96f32d1645301' set up to track 'origin/3.4.x'.
COMMAND: git merge --squash --strategy-option=theirs stash
```

I don't recall seeing these git commands before so it might be related.

**Comment by fcollonval** [comment]
The PR to blame is https://github.com/jupyter-server/jupyter_releaser/pull/358

The reason for the bump version to be introduced is the switch from `git stash apply` to `git merge`.

The former was indeed restoring only the changelog changes. But the git merge is bringing those changes and the lerna commit that bumped the version.

If I stop the process before the `make_changelog_pr`. The current change is:

```
On branch 3.4.x
Your branch is ahead of 'origin/3.4.x' by 1 commit.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   CHANGELOG.md
```

But the branch history is:

```
* b8f2067a6 (HEAD -> 3.4.x, tag: node-example@3.4.5, tag: @jupyterlab/vega5-extension@3.4.5, tag: @jupyterlab/vdom@3.4.5, tag: @jupyterlab/vdom-extension@3.4.5, tag: @jupyterlab/ui-components@3.4.5, tag: @jupyterlab/ui-components-extension@3.4.5, tag: @jupyterlab/translation@3.4.5, tag: @jupyterlab/translation-extension@3.4.5, tag: @jupyterlab/tooltip@3.4.5, tag: @jupyterlab/tooltip-extension@3.4.5, tag: @jupyterlab/toc@5.4.5, tag: @jupyterlab/toc-extension@5.4.5, tag: @jupyterlab/theme-light-extension@3.4.5, tag: @jupyterlab/theme-dark-extension@3.4.5, tag: @jupyterlab/testutils@3.4.5, tag: @jupyterlab/terminal@3.4.5, tag: @jupyterlab/terminal-extension@3.4.5, tag: @jupyterlab/template@3.4.5, tag: @jupyterlab/statusbar@3.4.5, tag: @jupyterlab/statusbar-extension@3.4.5, tag: @jupyterlab/statedb@3.4.5, tag: @jupyterlab/shortcuts-extension@3.4.5, tag: @jupyterlab/shared-models@3.4.5, tag: @jupyterlab/settingregistry@3.4.5, tag: @jupyterlab/settingeditor@3.4.5, tag: @jupyterlab/settingeditor-extension@3.4.5, tag: @jupyterlab/services@6.4.5, tag: @jupyterlab/running@3.4.5, tag: @jupyterlab/running-extension@3.4.5, tag: @jupyterlab/rendermime@3.4.5, tag: @jupyterlab/rendermime-interfaces@3.4.5, tag: @jupyterlab/rendermime-extension@3.4.5, tag: @jupyterlab/property-inspector@3.4.5, tag: @jupyterlab/pdf-extension@3.4.5, tag: @jupyterlab/outputarea@3.4.5, tag: @jupyterlab/observables@4.4.5, tag: @jupyterlab/notebook@3.4.5, tag: @jupyterlab/notebook-extension@3.4.5, tag: @jupyterlab/nbformat@3.4.5, tag: @jupyterlab/nbconvert-css@3.4.5, tag: @jupyterlab/mock-token@3.4.5, tag: @jupyterlab/mock-provider@3.4.5, tag: @jupyterlab/mock-extension@3.4.5, tag: @jupyterlab/mock-consumer@3.4.5, tag: @jupyterlab/metapackage@3.4.5, tag: @jupyterlab/mathjax2@3.4.5, tag: @jupyterlab/mathjax2-extension@3.4.5, tag: @jupyterlab/markdownviewer@3.4.5, tag: @jupyterlab/markdownviewer-extension@3.4.5, tag: @jupyterlab/mainmenu@3.4.5, tag: @jupyterlab/mainmenu-extension@3.4.5, tag: @jupyterlab/logconsole@3.4.5, tag: @jupyterlab/logconsole-extension@3.4.5, tag: @jupyterlab/launcher@3.4.5, tag: @jupyterlab/launcher-extension@3.4.5, tag: @jupyterlab/json-extension@3.4.5, tag: @jupyterlab/javascript-extension@3.4.5, tag: @jupyterlab/inspector@3.4.5, tag: @jupyterlab/inspector-extension@3.4.5, tag: @jupyterlab/imageviewer@3.4.5, tag: @jupyterlab/imageviewer-extension@3.4.5, tag: @jupyterlab/hub-extension@3.4.5, tag: @jupyterlab/htmlviewer@3.4.5, tag: @jupyterlab/htmlviewer-extension@3.4.5, tag: @jupyterlab/help-extension@3.4.5, tag: @jupyterlab/galata@4.3.5, tag: @jupyterlab/fileeditor@3.4.5, tag: @jupyterlab/fileeditor-extension@3.4.5, tag: @jupyterlab/filebrowser@3.4.5, tag: @jupyterlab/filebrowser-extension@3.4.5, tag: @jupyterlab/extensionmanager@3.4.5, tag: @jupyterlab/extensionmanager-extension@3.4.5, tag: @jupyterlab/example-terminal@3.4.5, tag: @jupyterlab/example-services-outputarea@3.4.5, tag: @jupyterlab/example-services-browser@3.4.5, tag: @jupyterlab/example-notebook@3.4.5, tag: @jupyterlab/example-filebrowser@3.4.5, tag: @jupyterlab/example-federated@2.5.5, tag: @jupyterlab/example-federated-phosphor@2.5.5, tag: @jupyterlab/example-federated-middle@2.5.5, tag: @jupyterlab/example-federated-md@2.5.5, tag: @jupyterlab/example-federated-core@2.5.5, tag: @jupyterlab/example-console@3.4.5, tag: @jupyterlab/example-cell@3.4.5, tag: @jupyterlab/example-app@3.4.5, tag: @jupyterlab/documentsearch@3.4.5, tag: @jupyterlab/documentsearch-extension@3.4.5, tag: @jupyterlab/docregistry@3.4.5, tag: @jupyterlab/docprovider@3.4.5, tag: @jupyterlab/docprovider-extension@3.4.5, tag: @jupyterlab/docmanager@3.4.5, tag: @jupyterlab/docmanager-extension@3.4.5, tag: @jupyterlab/debugger@3.4.5, tag: @jupyterlab/debugger-extension@3.4.5, tag: @jupyterlab/csvviewer@3.4.5, tag: @jupyterlab/csvviewer-extension@3.4.5, tag: @jupyterlab/coreutils@5.4.5, tag: @jupyterlab/console@3.4.5, tag: @jupyterlab/console-extension@3.4.5, tag: @jupyterlab/completer@3.4.5, tag: @jupyterlab/completer-extension@3.4.5, tag: @jupyterlab/codemirror@3.4.5, tag: @jupyterlab/codemirror-extension@3.4.5, tag: @jupyterlab/codeeditor@3.4.5, tag: @jupyterlab/celltags@3.4.5, tag: @jupyterlab/celltags-extension@3.4.5, tag: @jupyterlab/cells@3.4.5, tag: @jupyterlab/cell-toolbar@3.4.5, tag: @jupyterlab/cell-toolbar-extension@3.4.5, tag: @jupyterlab/buildutils@3.4.5, tag: @jupyterlab/builder@3.4.5, tag: @jupyterlab/attachments@3.4.5, tag: @jupyterlab/apputils@3.4.5, tag: @jupyterlab/apputils-extension@3.4.5, tag: @jupyterlab/application@3.4.5, tag: @jupyterlab/application-top@3.4.5, tag: @jupyterlab/application-extension@3.4.5) [ci skip] New version
```

So by merging the stash branch, we bring the stashed changes and the new version commit.

**Comment by fcollonval** [comment]
> Although was the issue already happening before the 0.23.0 release of jupyter_releaser?

It happens for me on the commit merging https://github.com/jupyter-server/jupyter_releaser/pull/358. And the last time I used it successfully was to do the 4.0 prerelease three commits before (sha 42bb75e635e7e8958809336c2428c42226f6a782).

**Comment by jtpio** [comment]
> The PR to blame is [jupyter-server/jupyter_releaser#358](https://github.com/jupyter-server/jupyter_releaser/pull/358)

Ah good catch. Didn't notice that changelog PR also had other changes.

**Comment by jtpio** [comment]
Just tried with a simple extension and while the changelog PR is correctly generated: https://github.com/jupyterlab-contrib/jupyterlab-cell-flash/pull/32

The check release workflow fails with the following: https://github.com/jupyterlab-contrib/jupyterlab-cell-flash/runs/7766995009?check_suite_focus=true

```
COMMAND: git checkout -b changelog-f910df6e18aa11ed9f1611ea265f32fd origin/main
Switched to a new branch 'changelog-f910df6e18aa11ed9f1611ea265f32fd'
branch 'changelog-f910df6e18aa11ed9f1611ea265f32fd' set up to track 'origin/main'.
COMMAND: git merge --squash --strategy-option=theirs stash
merge: stash - not something we can merge
```

So yeah probably https://github.com/jupyter-server/jupyter_releaser/pull/360 will help with this.

**Comment by fcollonval** [comment]
Closing as erroneous

**Pull request closed without merging**
