### PR TITLE
Move document mode switch to separate plugin

### PR DESCRIPTION
**Pull request by jasongrout**
## Code changes

- Abstracts out the mode switch to be a generic ui-component switch
- Moves the mode switch to application-extension as a new plugin, so it can be disabled
- Adds the keyboard shortcut to the title
- Changes the visible label to just "Mode" - the caption still says "Single-Document mode (<shortcut>)"

## User-facing changes

Adds the keyboard shortcut to the title, and changes the visible label to just "Mode"

Screen Shot 2020-11-03 at 4 40 35 AM
Screen Shot 2020-11-03 at 4 40 13 AM

### CODE REVIEW

**Comment by jtpio** [comment]
Nice!

> Abstracts out the mode switch to be a generic ui-component switch

This might also address https://github.com/jupyterlab/jupyterlab/issues/8010 (at least for a first version)

**Comment by jtpio** [comment]
> Changes the visible label to just "Mode" - the caption still says "Single-Document mode ()"

An interesting idea to reduce even more the space taken by the label could be to move the label "inside" the switch.

For example: https://blueprintjs.com/docs/#core/components/switch

image

image

(although it's not clear whether this pattern is widely adopted or recommended)

**Comment by jasongrout** [comment]
> One way to reduce even more the space taken by the label could be to move the label "inside" the switch.

Ah, then the text actually becomes button text, rather than a separate label. That does seem more controversial, so let's leave that for another PR/discussion.

**Comment by jtpio** [comment]
> That does seem more controversial, so let's leave that for another PR/discussion.

Absolutely, this can be deferred to https://github.com/jupyterlab/jupyterlab/issues/8010

**Comment by jtpio** [comment]
Looks like this test would need to be updated?

https://github.com/jupyterlab/jupyterlab/blob/df4d2b11e48702445198bca3ddf38e658d1e8f4c/packages/application/test/shell.spec.ts#L160-L165

**Comment by jtpio** [comment]
Just tested on Binder and it looks great!

We'll probably want to update first the tests to fix `js-application` (https://github.com/jupyterlab/jupyterlab/pull/9270#issuecomment-721720428).

Also as a follow for 3.x it would be interesting to see if the switch component could be reused for the debugger too.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jasongrout** [comment]
> Looks like this test would need to be updated?

Done in 1f02451

**Comment by jtpio** [comment]
Thanks!

**Pull request merged**
