### PR TITLE
Observablemap

### PR DESCRIPTION
**Pull request by ian-r-rose**
Interface for and implementation of an observable map, as per the discussion in #1697

### CODE REVIEW

**Comment by ian-r-rose** [comment]
I'll remove the linking logic for the moment.

**Comment by blink1073** [comment]
:boom:

**Comment by blink1073** [comment]
@ian-r-rose, @ellisonbg, I'm thinking that the metadata of the notebook and cells should also use this map instead of our existing solution, agreed?

**Comment by ian-r-rose** [comment]
Yes, I agree. I am currently working towards that, in fact, in the Realtime branch.

**Comment by ian-r-rose** [comment]
Though there is no reason not to do it sooner :)

**Comment by ellisonbg** [comment]
Nice! I gave it a quick read through (in class now) and it looks great. I will leave detailed review to @blink1073

**Comment by blink1073** [comment]
bigyes

**Pull request merged**
