### PR TITLE
Fix Vega-Embed version 

### PR DESCRIPTION
**Pull request by domoritz**
so that we don't yet update Vega-Lite to version 3 since Altair does not yet support it.

### CODE REVIEW

**Comment by domoritz** [comment]
hmm, I ran `jlpm run integrity` locally but it doesn't make a difference.

**Comment by blink1073** [comment]
Hmm, odd.  I pushed the integrity change.

**Comment by blink1073** [comment]
Thanks!

**Comment by domoritz** [comment]
Hmm, odd... and thanks!

**Pull request merged**
