### PR TITLE
Fix operator precedence.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes jupyterlab/jupyterlab-google-drive#138.

Bug was introduced by yours-truly in #4757.

### CODE REVIEW

**Comment by blink1073** [comment]
Error is legit:

```
$ tsc && node build.js
../notebook-extension/src/index.ts:509:24 - error TS2345: Argument of type 'string | number | true | ReadonlyJSONObject | ReadonlyJSONArray' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.
509       return createNew(cwd, kernelName);
                           ~~~
```

**Comment by ian-r-rose** [comment]
Thanks, updated.

**Comment by blink1073** [comment]
I'll release 0.34.1 after this

**Comment by stonebig** [comment]
does it mean extensions like pyviz_comms **must** now point to 18.3 ?

https://github.com/pyviz/pyviz_comms/blob/master/package.json#L32.L35

**Comment by ian-r-rose** [comment]
No, they should be fine, @stonebig

**Comment by stonebig** [comment]
ok.

**Pull request merged**
