### PR TITLE
Update to `@jupyter/ydoc` 1.1.1

### PR DESCRIPTION
**Pull request by jtpio**
## References

Update to `@jupyter/ydoc` 1.1.1.

To grab the fix from https://github.com/jupyter-server/jupyter_ydoc/pull/186 that landed in `1.1.1`: https://github.com/jupyter-server/jupyter_ydoc/releases/tag/v1.1.1

For reference the changelog for `1.1.0`: https://github.com/jupyter-server/jupyter_ydoc/releases/tag/v1.1.0

## Code changes

- [x] Dependency update.
- [x] Fix incorrect test expectation

## User-facing changes

Should be none for regular JupyterLab / Jupyter Server users.

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Looking at the changelog it should be fine to backport this to `4.0.x`.

**Comment by krassowski** [comment]
The test failure is relevant, I guess the test expectation was wrong?

**Comment by jtpio** [comment]
Yes looks like the assumption was wrong. Will push a commit to fix the tests.

**Comment by jtpio** [comment]
Done in https://github.com/jupyterlab/jupyterlab/pull/15177/commits/36ce377463cc428bb5180c1b14bf7331829c817d

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 4.0.x

**Comment by krassowski** [comment]
It looks like a backport PR for this one was not created. Was this intentional?

**Comment by fcollonval** [comment]
This is an oversight - thanks for the ping @krassowski

**Pull request merged**
