### PR TITLE
Move notebook logging plugin to notebook-extension package

### PR DESCRIPTION
**Pull request by jasongrout**
## Code changes

We had a plugin that logged notebook output. For historical reasons, it was in the logconsole-extension package (basically so that we could introduce the logconsole-extension package into jlab 1.x with backwards compatibility).

It probably makes more sense for this extension to be in the notebook-extension package. One argument for it to stay in the logconsole-extension package is that the log console extension still depends on notebook to do automatic switching between log sources based on the current active notebook. At some point that may (should?) be changed to allow you to select the log source from the log console ux, however.

This isn't a huge deal, so if you don't want to merge it this close to the 2.0 release, that's fine.

## User-facing changes

None.

## Backwards-incompatible changes

This moves one of the plugins exported by the log console extension to the notebook extension.

### CODE REVIEW

**Comment by jasongrout** [comment]
Adding to the 2.0 milestone for consideration, but feel free to bump to 3.0 if there are concerns or reservations. It's not a huge deal, it's just putting plugins where they belong more naturally.

**Comment by blink1073** [comment]
I think this makes sense to get it before the 3.0 RC if you want to rebase

**Comment by jasongrout** [comment]
I'll do it right now for the beta, since it is an api-breaking change

**Comment by jasongrout** [comment]
Rebased on master

**Pull request merged**
