### PR TITLE
Add license header fix job

### PR DESCRIPTION
**Pull request by fcollonval**
## References

https://github.com/jupyterlab/jupyterlab/pull/12534#issuecomment-1196430896

## Code changes

Add job to ensure license header on files

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by fcollonval** [comment]
- Staging failure is expected - alternatively I can ignore them from the header license check
- UI test failure is not related; seem like a new flaky test :cry:

**Comment by jtpio** [comment]
> * alternatively I can ignore them from the header license check

Yes that would be great if possible.

**Review by jtpio — APPROVED** [review]
Looks good, thanks!

Just restarted the failed check to be sure, otherwise it should be good to go.

**Comment by jtpio** [comment]
Thanks!

**Pull request merged**
