### PR TITLE
Improvements to dialog UX

### LINKED ISSUE #5617: Sreamlining dialog UX
There is the potential for a lot of dialogs in jupyterlab (as well as in classic notebooks). Sometimes, the dialogs can act more as speedbumps in your work than the safety stops they are intended as. As such, I think I see two patterns that can help alleviate this:
1. Have all commands that produce an "are you sure?" dialog take an argument that skips it, and ensure that one can bind shortcuts to supply that argument. It would be nice if this followed a consistent pattern for argument names.
2. Make a dialog utility / option to include a checkbox to "Remember my choice" / "Do not show this dialog again". This would store the choice in the settings, and any stored choice would automatically be returned.

### PR DESCRIPTION
**Pull request by seawolf42**
Fixes #5617 

This is the beginnings of a fix for this issue. I'll need help understanding exactly how to resolve this for the `console-extension` tool, and finalizing actually prompting the user to remember the selected result. As per direction from @ellisonbg creating the PR to determine what should happen next.

**Screenshots**
If applicable, add before and after screenshots to help show the issue being fixed, or the appearance of a new feature.

### CODE REVIEW

**Comment by fcollonval** [comment]
@seawolf42 and @ellisonbg what is the current status of this feature?

I start looking into #5241 for which persistent user choice will be needed. It will help and ensure consistency if I can build on this feature.

Cheers

**Comment by seawolf42** [comment]
@fcollonval I started work but got stuck. @ellisonbg asked me to go ahead and create the PR so somebody else could pick up where I left off and I haven't been tracking since that point.

**Comment by fcollonval** [comment]
@seawolf42 thanks for the quick feedback. Could you grant me "collaborator" status on your Jupyterlab fork, so I can commit directly on the PR branch - avoiding starting a new one?

**Comment by blink1073** [comment]
Closing as stale, please feel free to reopen if you'd like to pick this back up

**Pull request closed without merging**
