### PR TITLE
URL functionality user documentation.

### PR DESCRIPTION
**Pull request by afshin**
This PR adds user documentation for `workspaces`, `tree` URLs, workspace `clone`, and workspace `reset` URLs.

### CODE REVIEW

**Comment by afshin** [comment]
cc: @willingc @choldgraf

**Comment by choldgraf** [comment]
woot! lemme know when you'd like a pair of 👀 to review

**Comment by afshin** [comment]
@choldgraf I think I'm done with this pass, actually. So please do.

**Comment by jzf2101** [comment]
Will pull and build in a bit @afshin

**Comment by choldgraf** [comment]
wohoo!

**Comment by afshin** [comment]
cc: https://github.com/jupyterlab/jupyterlab/issues/3673

**Pull request merged**
