### PR TITLE
Clean up context menu for directories and allow cut-copy-paste

### LINKED ISSUE #3236: Duplicate action has no effect on directories
Problem: Under the Files tab, if you right-click on a directory and select the "Duplicate" action, the folder is not duplicated and there is no response.

Expected behavior: 
(1) A new directory is created with the same name suffixed with "Copy" or something like the behavior seen when Duplicate is performed on files, OR alternatively,
(2) no "Duplicate" option is available for directories.

I'm using JupyterLab version 0.28.5.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #3236.

### CODE REVIEW

**Comment by ellisonbg** [comment]
+1 to these. Are we still waiting to convert this to the universal context menus?

**Comment by ian-r-rose** [comment]
My recollection is that the universal context menu conversion was blocked by the dynamic population of the `Open With` submenu.

**Comment by blink1073** [comment]
Correct. I put it back to WIP because I realized directories can't be copied by the server but I didn't bring my laptop with me to the hospital.

**Comment by blink1073** [comment]
I verified that cut/paste worked earlier.

**Pull request merged**
