### PR TITLE
Make the command palette modal

### PR DESCRIPTION
**Pull request by ellisonbg**
## References

https://github.com/jupyterlab/jupyterlab/issues/7039

## Code changes

Adds a `ModalCommandPalette` that wraps the existing command palette widget, removes from left panel.

## User-facing changes

Screen Shot 2020-08-10 at 10 52 12 PM

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by vidartf** [comment]
If you are using lab from a mobile device, what will be the UX for opening the palette with this change? The loss of a large friendly button could be a pretty big demerit.

**Comment by ellisonbg** [comment]
I have added a relatively complete test suite for the `ModalCommandPalette` in the most recent commit. Because the actual `CommandPalette` is tested thoroughly in lumino, I have not added additional tests for it. I am still seeing the random test failures we are seeing in other PRs related to sessioncontext. This should be ready for final review + merge.

**Comment by krassowski** [comment]
Would it be easily possible to reuse this modal UI for other lists, like for a list of files to implement "quick open" functionality?

**Comment by ellisonbg** [comment]
This view is pretty wired to the command palette. However, for the quick open capability, why not just add a new set of commands that will appear in this modal command palette with a common prefix (like "Open: ")? Put another way, this view won't help for arbitrary model lists that have search, but if the list items are just a command that triggers actions, we should use the command registry and modal command palette by registering new commands. Can you talk more about the "quick open" idea - after playing with this PR I was have been thinking about adding a bunch of new commands to do common things.

**Comment by krassowski** [comment]
So there is:
- https://github.com/parente/jupyterlab-quickopen
- https://www.jetbrains.com/pycharm/guide/tips/navigate-to-file/ (see the video)
- https://blog.jetbrains.com/idea/2020/05/when-the-shift-hits-the-fan-search-everywhere/ (even more useful and powerful!)
- https://code.visualstudio.com/docs/editor/editingevolved#_open-symbol-by-name
https://code.visualstudio.com/docs/editor/editingevolved#_quick-file-navigation

I know I could parametrize the arguments of commands, but even if it was easy to add potentially hundreds of files as commands, this might not allow for customized rendering of list items.

**Comment by bollwyvl** [comment]
To echo @vidartf's point: requiring a three-key chord to get one of the most powerful and extensible feature-discovery features seems like a significant loss. I'd love to see this more durably placed on the screen, for example:
- in the huge gulf of whitespace at the end of the top area
- sticky to the top in the launcher (another whitespace gulf)
- keep the existing command palette, offering this new one under a new, shorter chord

To the point of configuration: the [repl.it](https://blog.repl.it/clui) exploration is cool as well. If commands did more to [advertise](https://github.com/jupyterlab/lumino/issues/58) their options, many complex commands wouldn't even require a dedicated width or block-the-world dialog (gah) to configure a few small options.

**Comment by ellisonbg** [comment]
@krassowski Ahh, I hadn't see the quick open extension of @parente - very nice. I think the scope of that is different and large enough that a new experience for that probably makes sense. The main part of this PR that might be useful for other usage cases, is the `ModalCommandPalette` which is really just a modal wrapper of another `Widget`. There are a few ways in which it is wired to the `CommandPalette` but I think those would be easy to relax.

@bollwyvl I will jot down some notes tomorrow on the user feedback, user stories, pain points etc. that led to this proposal.

**Comment by ellisonbg** [comment]
I have pushed a change that introduces a setting that allows the user to switch back to a left panel command palette. It mostly works, but there is something odd going on though with the advanced setting editor and layout restorer. @afshin are you around this week to help debug?

**Comment by ellisonbg** [comment]
I *think* this is now working and ready to go, but can't full test because of https://github.com/jupyterlab/jupyterlab/issues/8958

**Comment by ellisonbg** [comment]
All feedback addressed, everything working, tests pass locally. Once the tests pass here, this is ready for merge.

**Comment by ellisonbg** [comment]
Fixes #7039

**Comment by ellisonbg** [comment]
I pushed a linting fix, test failures in apputils are unrelated to this PR.

**Comment by jasongrout** [comment]
@ellisonbg said he was going to make a menu item for the command palette in a separate PR. I'll wait for that PR before merging both.

**Pull request merged**
