### PR TITLE
Debugger: Fix CSS for variables inspecting

### PR DESCRIPTION
**Pull request by martinRenou**
## References

Fix debugger CSS for the variable inspector

## Code changes

Some CSS changes

## User-facing changes

Before:

before

After:

after

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Yeah! Thanks for the fix.

**Review by fcollonval — CHANGES_REQUESTED** [review]
@martinRenou would you mind removing the updated galata/test/documentation/general.test.ts-snapshots/running-layout-documentation-linux.png as the new one is not correct.

**Review by fcollonval — APPROVED** [review]
Thanks @martinRenou

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.4.x

**Comment by SylvainCorlay** [comment]
Let's backport this to 3.x!

**Comment by martinRenou** [comment]
I'll do the backport :) Thanks!

**Pull request closed without merging**
