### PR TITLE
[WIP] Enable building of sibling installs with shallowly nested workspaces

### PR DESCRIPTION
**Pull request by telamonian**
## References

jupyterlab/jupyterlab-data-explorer#82

## Code changes

Some extensions (eg [jupyterlab-data-explorer](https://github.com/jupyterlab/jupyterlab-data-explorer), [ipywidgets](https://github.com/jupyter-widgets/ipywidgets), etc) are structured as packages with workspaces that represent sub-packages. `yarn` [doesn't normally support such nested workspaces](https://yarnpkg.com/lang/en/docs/workspaces/#toc-limitations-caveats). This PR tweaks the `yarn` settings (via `package.json`) and other parts of the build system to allow for limited/shallow support for nested workspaces, down to one extra level of nesting.

Thus, with this PR, the following sibling build will work properly:

```
jlpm run add:sibling https://github.com/jupyterlab/jupyterlab-data-explorer.git && jlpm build
```

even though the packages of interest (`dataregistry`, `dataregistry-extension`) are nested within the workspaces of the top level package in that repo.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by telamonian** [comment]
Uggh, the hacks I made to support nesting apparently break a lot of `lerna` CLI commands pretty badly. For now, consider this WIP

**Comment by blink1073** [comment]
Nested workspaces are coming in yarn 2.0 (currently in 2.0.0-rc.5): https://next.yarnpkg.com/features/workspaces#how-to-declare-a-worktree.

**Comment by blink1073** [comment]
Oh wow!  There is a new [portal](https://github.com/yarnpkg/berry/blob/d4323462701190788b34e3eea6c5e8a016ce1d29/packages/gatsby/content/features/protocols.md#whats-the-difference-between-link-and-portal) dependency type that does exactly what we want for our `labextension link` I think.   I wonder if you can have a portal to another workspace...

**Comment by blink1073** [comment]
The list of [new features](https://github.com/yarnpkg/yarn/issues/6953) for yarn 2.0 is amazing!

**Comment by telamonian** [comment]
> The list of [new features](https://github.com/yarnpkg/yarn/issues/6953) for yarn 2.0 is amazing!

I agree. I did see the nested workspaces/worktree stuff. Certainly it would be a much more straightforward solution that anything I've come up with so far:

- replace all `lerna` commands
- hack the copy of `yarn.js` that we ship with Jlab

I actually asked over at yarnpkg/berry#447 (berry hosts the yarn 2.0 dev branch) if it was ready to try out. I'll see what they have to say. If it's coming soon-ish (say, in time for Jlab 2.0), I'll probably just close this PR and lend a hand with upgrading yarn when the time comes.

**Comment by telamonian** [comment]
Also, I thought you were taking a break, @blink1073!

**Comment by blink1073** [comment]
Ha, thanks, point taken

**Comment by blink1073** [comment]
Closing in favor of #8037

**Pull request closed without merging**
