### PR TITLE
Bump marked.js (and types) to pull fix for rendering

### LINKED ISSUE #10171: Markdown details no longer works in 3.x but worked in 2.x
In `2.x` this would work:
```python
<details>
  <summary>Click to get a detailed explanation.</summary>
  
  ## Selecting Offsets
  1. something
    * something 1
    * something 2
        * something 2.1
    |pre-offset|post-offset|formula|
    |--|--|--|
    |-1|1|1-(-1)|
    |-2|2|2-(-2)|
    |-3|3|3-(-3)|
    |-4|4|4-(-4)|
    |-5|5|5-(-5)|
    ...
  2. something else
     * something else 1
    |pre-offset|post-offset|formula|
    |--|--|--|
    |-14|3|3-(-14)|
    |-15|4|4-(-15)|
    |-16|5|5-(-16)|
    |-17|6|6-(-17)|
    |-18|7|7-(-18)|
    ...
  
</details>
```

and would look like this:
image

However, after upgrading to `3.x` (I am on 3.0.14), it now does not render and looks like this:
image

### PR DESCRIPTION
**Pull request by krassowski**
## References

Fixes #10171

## Code changes

None, but should I pin the version in package.json, or should I just update the lock file for such PRs?

## User-facing changes

Markdown within HTML tags should be correctly rendered as per specification.

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
@afonit you may want to test it on binder here.

**Comment by afonit** [comment]
@krassowska ,
that worked.  Thank you so much.

The indented version works again.

I did try the un-indented version that works in jlab 3.x and that now doesn't work (not sure if it should with the fix)

**Comment by krassowski** [comment]
All versions I tried are working fine for me. Could you please provide a reproducible example that does not work?

PS. If you ping me rather than my wife I will be able to respond faster.

**Comment by afonit** [comment]
@krassowski sorry about pinging the wrong person,
I just opened the binder link that the bot provided above.

I just did it again - and both examples worked.  Perhaps I did something wrong the first time.

Glad all the examples are working.

Thank you for lending your expertise and making this fix happen, this is pretty great.

**Comment by krassowski** [comment]
> @krassowski sorry about pinging the wrong person,

No worries, it's fun to pick on this as everyone is doing so for over month now ;)

Also glad it works for you now!

**Review by blink1073 — APPROVED** [review]
Thanks!

**Pull request merged**
