### PR TITLE
new ui test: clicking the TOC should scroll the notebook panel

### PR DESCRIPTION
**Pull request by parmentelat**
## References

as suggested by @krassowski in
https://github.com/jupyterlab/jupyterlab/pull/15184
here's a ui test to check that clicking a header in the TOC does scroll to ensure that heading becomes visible

this PR should help reproduce issue #14591

## Code changes

only a new ui test is added:
- opening a reasonably long notebook
- clicking on the last header
- show result in the nb viewport having scrolled to near the bottom of the notebook

**note** that the expected output (the snapshot) needs more work because
- my laptop is a mac so I could produce only the `darwin` version of the snapshot, my understanding is that a `linux` version is desirable too
- more importantly, as of this writing, the jupyterlab code breaks this test, so the snapshot in this PR is just an indication of what it should become

## User-facing changes

n/a

## Backwards-incompatible changes

n/a

### CODE REVIEW

**Comment by parmentelat** [comment]
please update galata snapshots

**Comment by parmentelat** [comment]
the snapshot now correctly describes the expected behaviour (seeing the bottom of the notebook)
it is still named in `darwin` though, I'm not sure if that matters or not

also I have been able to run this test on top of #15184, and can confirm it does fix the issue - this is how I produced the correct snapshot

**Comment by parmentelat** [comment]
after the automatic snapshot update, we have:
- the linux snapshot that is the actual result of the test, so it's broken
- the darwin snapshot, which I created manually using the fix, which shows the expected outcome (the bottom of the notebook)
-

**Comment by fcollonval** [comment]
Thanks a lot @parmentelat 

The snapshots are always os scoped as you realized. This is the reason the CI is generating and using only the _linux_ variant - basically the _darwin_ one will have to be removed before merging.

Would you mind merging this into #15184? This will ease the generation of the correct snapshot and the validation of the PR actually fixing the code.

**Comment by parmentelat** [comment]
ok @fcollonval 
I added the test in #15184
closing this one then

**Pull request closed without merging**
