### PR TITLE
Cell collaborators list

### PR DESCRIPTION
**Pull request by martinRenou**
## References

https://github.com/jupyterlab/jupyter_collaboration/issues/109

## Code changes

- Add a new CollaboratorsList react component.
- Synchronise current users between collaborators

## User-facing changes

There are two different options I explored here. 

---

### Over the cell

The first one is showing the list in the top-right of the cell:

collabicons

---

### In the cell header

The second one (current state of the PR) is showing the list in the cell header:

collab2

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by martinRenou** [comment]
I didn't explore the right-gutter solution discussed in https://github.com/jupyterlab/jupyterlab/issues/11555#issuecomment-989687674, as it will not work in the case of rendered Markdown cells, which would be unfortunate.

I have a personal preference for the first option (over the cell), it takes less space, and is easier to read.
It might hide the code content, but we could technically fix this by hiding the collaborator list if the user mouse goes over it (when the user wants to see/select code).

**Comment by hbcarlos** [comment]
> I have a personal preference for the first option (over the cell), it takes less space, and is easier to read.

I prefer the first option too. The downside is that we could cover code/text, but I think this will happen in a few cases since, for example, markdown cells tend to start with a title (it is rare that the title takes the whole line).

**Comment by martinRenou** [comment]
As discussed with @SylvainCorlay we might be able to improve the cell-header proposition by changing the style of the header itself (slightly different background color, solid border etc).

**Comment by martinRenou** [comment]
It might also be possible to show the collaborator list as a column at the right of the cell, though the amount of space for small cells is limited

**Comment by jtpio** [comment]
Looks like this PR could be closed and ported over to https://github.com/jupyterlab/jupyter_collaboration?

**Pull request closed without merging**
