### PR TITLE
Topbar menu items importance

### LINKED ISSUE #10091: Topbar menu items importance
An issue that has come up a couple of times, is people interested in providing only a subset of the menu items available in the topbar menus, that they thought were more important. For example, "**Restart Kernel and Run All**" is probably more important than "**Restart Kernel and Run up to Selected Cell**" which could still be made available as a command in the palette.

A solution to that issue would be for these items to have a **weight** or **importance level**,  and to only show items that are beyond a certain threeshold when running lab in a light mode (very much like we have log levels for messages).

### PR DESCRIPTION
**Pull request by fcollonval**
## References

This is a first trial to fix #10091.

## Code changes

I followed the suggestion of @jasongrout and define a setting in the `mainmenu-extension` package that is used to set the `isVisible` callback on command.

This is not fully satisfactory as not all commands are defined in the `mainmenu-extension` package. For example the _restart kernel and run up to selected cell_ cannot be hidden as it is define in the notebook package. I therefore wonder if it could be directly implemented in lumino by adding the ability to customize (aka hide or not) menu item independently of the `isVisible` command method. Then the `mainmenu-extension` would update the menu item visibility when the setting is changed.

## User-facing changes

None by default

Example:
| Before | After |
| --- | --- |
| image | image |

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @fcollonval for exploring this :+1:

**Comment by isabela-pf** [comment]
Thanks for bringing this up at this week's JupyterLab meeting @fcollonval! I have a few questions about some of the user-facing interactions other than the end result.

- How is this change made by users? Do you have a screenshot of how the option appears in settings?
- How is this abridged list made/prioritized? Is it configurable or pre-defined which are the most important items?
- Does this only influence the main menu? Does this interact with the command palette at all?
- Is this intended as it's own sort of thing, or is it intended to overlap with something like the recent simple mode (that may be the wrong name; I remember quite a discussion but not the naming result)? It sounds like it has similar motivation.

(Feel free to let me know if any of those questions were confusing!)

**Comment by fcollonval** [comment]
Thanks for the interest @isabela-pf 

I'll start by your last question to describe the context a bit more.

> * Is this intended as it's own sort of thing, or is it intended to overlap with something like the recent simple mode (that may be the wrong name; I remember quite a discussion but not the naming result)? It sounds like it has similar motivation.

A customer is building an app based on JupyterLab and he would like to change the default menu (basically reduce the number of entry to favor one clear way for doing things). So the idea is to make separated.

That said, it could be interesting to link it to UI mode.

> * How is this change made by users? Do you have a screenshot of how the option appears in settings?

This is quick prototype; the command ids have been added manually. This is definitely not the best user experience approach. But something like that would be sufficient to address the primary objective.

> * How is this abridged list made/prioritized? Is it configurable or pre-defined which are the most important items?

This demo is not touching the order; just the visibility.
 
> * Does this only influence the main menu? Does this interact with the command palette at all?

The goal is to modify only the menus. So that commands can still be accessed through the palette for interested user.

**Comment by krassowski** [comment]
Thanks for starting this, customizing the menus in the interface is indeed a big feature that JupyterLab is currently missing.

What about **context menus**? It is also quite long and I (as a user) would like to hide some entries. Would it make sense to move the settings somewhere else and have both `hiddenMenuEntries` and `hiddenContextMenuEntries` in one place? I would indeed favour a consistency in that any entries could be hidden rather than only those configured in `mainmenu-extension` (so the lumino modification pathway).

Also, being able to change the order would be very nice too indeed, but I imagine this could be a separate PR, adding something like `menuEntriesRanks` and `contextMenuEntriesRanks` which would override the default ranks.

**Comment by SylvainCorlay** [comment]
@isabela-pf @krassowski one approach that we have discussed is for menu items to have a weight (defaulting to some value when un-specified), and to pick a " verbosity level" as a global configuration parameter in JupyterLab.

I imagine two use cases for using a low threeshold value:
 - people who don't use menus much and only the command palette, who also don't want their visual space cluttered with lots of options
 - deployments where it is determined that too many options confuse the users.

With this approach, a single value can be used to reduce the number of commands made available in the topbar, or in context menus.

**Comment by krassowski** [comment]
I don't believe that using a single threshold is the best way to go forward. There is no objective weight for a command (I for one believe that "Restart Kernel and Run up to Selected Cell" is more important than "Restart Kernel and Run All" - contrary to what you mentioned in the original issue). Using a system of ranks + enabled/disabled would allow users to have a full control over the order of items (and their visibility), allowing for things like https://github.com/jupyterlab/jupyterlab/issues/10091#issuecomment-833269878.

Could the idea of a single threshold be replaced with a groups of "preset" values for `hiddenMenuEntries` + `menuEntriesRanks` (+ `hiddenContextMenuEntries`, etc)? If you produce three or four presets you should be able to easily satisfy most users **and** they will be able to follow up with customizing the exact commands they want (and in which order).

**Comment by SylvainCorlay** [comment]
> (I for one believe that "Restart Kernel and Run up to Selected Cell" is more important than "Restart Kernel and Run All" - contrary to what you mentioned in the original issue)

I think that we would need to learn that from user testing (what is more important). In that case, "Restart Kernel and Run up to Selected Cell" is really oddly specific compared to the other one...

**Comment by isabela-pf** [comment]
> I think that we would need to learn that from user testing (what is more important).

I agree that we don't know for sure what menu items are most important to the most people without testing, but I'm not sure where this puts this PR at the moment. Are there plans to do user testing around this?

If not, I think @krassowski's suggestion of having a few presets or having a system where users can configure what the more limited menus might be. I think this keeps it general enough to be useful to a range of users while still meeting your customer's needs.

**Comment by fcollonval** [comment]
I agree with the trouble of a single threshold. So I'm working on an alternate approach with finer grain control on which items to display: https://github.com/jupyterlab/jupyterlab/pull/10254.

**Pull request closed without merging**
