### PR TITLE
Use tree/table buttons to display debugger variables view mode

### PR DESCRIPTION
**Pull request by karlaspuldaro**
## References
 Implements enhancement described in #9425 

## Code changes
Remove the toggle switch for variables view mode and replace it with buttons representing tree/table views, making the button role more visually clear to the user

debugger-variables-UI

### CODE REVIEW

**Comment by isabela-pf** [comment]
This is a great choice @karlaspuldaro. Thanks for doing this work!

**Comment by jasongrout** [comment]
I think using toggle buttons over a mode switch looks great. Thanks!

**Review by afshin — APPROVED** [review]
Thank you @karlaspuldaro! This is great 👍

**Comment by jtpio** [comment]
Thanks it looks great!

Looks like it might need an integrity fix, but otherwise it looks good :+1:

**Comment by karlaspuldaro** [comment]
@jtpio integrity was verified locally. Any chance the failure is coming from the warnings in unchanged files?

**Comment by jtpio** [comment]
@karlaspuldaro I think it was because the integrity script checks the new icons are also in `deprecated.css`.

Just pushed a change to the branch that should fix it.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by lawrence-z-arabii** [comment]
Any ideas why 'table view' is only partly of variable's window height and has its own scrollbar? jupyterlab 3.0.14

[jupyterlab 3.0.14]

image

**Pull request merged**
