### PR TITLE
[docker] Allow non-unique GID

### LINKED ISSUE #15663: docker build failed because user group with GID 20 already exists
## Description

First execute the script: `sh docker/start.sh`
The GID of my computer user is 20
截屏2024-01-19 18 20 28

error: 
`groupmod: GID '20' already exists`
截屏2024-01-19 18 23 06

reason:
in start.sh
    `docker build  --build-arg NEW_MAMBA_USER_ID=$UID --build-arg NEW_MAMBA_USER_GID=$GID $ROOT_DIR -f $SCRIPT_DIR/Dockerfile -t $IMAGE_TAG`
The default variable `ARG NEW_MAMBA_USER_GID=57440` of the `docker/Dockerfile` file has been overwritten to `20`

## Reproduce

sh docker/start.sh

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### LINKED ISSUE #15709: Docker run fails to build image
## Description
I run `docker/starth.sh dev` as suggest in the docks I get the following error
`COPY failed: forbidden path outside the build context: ../binder/environment.yml ()`

## Reproduce
Theoretically the description is enough, its probably some config error. 

## Expected behavior
The image builds and runs

## Context
Operating system: Manjaro linux
Docker Version: 24.0.7
Jupyter Lab commit hash: 558c60f069a33201ab7b2ba

### PR DESCRIPTION
**Pull request by trungleduc**
## References
Closes #15663 
Closes #15709

## Code changes

- Update the docker file to allow non-unique GID
- Remove un-needed dependencies
- Fix context path
- Update docker test workflow, in addition to the scheduled run, any PR with `[docker]` in the title also triggers the workflow.

### CODE REVIEW

**Comment by trungleduc** [comment]
@FoSuCloud could you checkout this PR and test the new docker file?

**Comment by FoSuCloud** [comment]
You are right, but when I execute `sh ./docker/start.sh` or `sh docker/start.sh` in the `root directory`, an error will be reported.
截屏2024-01-27 16 02 29

**Comment by trungleduc** [comment]
> You are right, but when I execute `sh ./docker/start.sh` or `sh docker/start.sh` in the `root directory`, an error will be reported. 截屏2024-01-27 16 02 29

Do you have this error with this PR?

**Comment by FoSuCloud** [comment]
> > You are right, but when I execute `sh ./docker/start.sh` or `sh docker/start.sh` in the `root directory`, an error will be reported. 截屏2024-01-27 16 02 29
> 
> Do you have this error with this PR? Could you try with `bash`?

I have replaced it with the latest code of this PR, but I still have this problem
截屏2024-01-27 17 50 03
截屏2024-01-27 17 50 14
and i has use `bash`


截屏2024-01-27 17 51 09
截屏2024-01-27 17 51 20

**Comment by trungleduc** [comment]
are you using MacOS? Since docker does not run natively in MacOS, something may be different in the context handling. I don't have a Mac machine to try it out, and the `mac-os` Github Action machine does not have `docker` installed to test the script in the CI

**Comment by FoSuCloud** [comment]
> are you using MacOS? Since docker does not run natively in MacOS, something may be different in the context handling. I don't have a Mac machine to try it out, and the `mac-os` Github Action machine does not have `docker` installed to test the script in the CI您使用的是 MacOS 吗？由于 docker 不在 MacOS 中本地运行，因此上下文处理中可能会有所不同。我没有 Mac 机器来试用它，并且没有 `docker` 安装 `mac-os` Github Action 机器来测试 CI 中的脚本

yes, i use macos

**Review by fcollonval — APPROVED** [review]
Thanks @trungleduc

**Pull request merged**
