### PR TITLE
Bump canvas to version with nodejs 18 binaries

### LINKED ISSUE #13782: Bumping NodeJS to 18 in maintainer-tools broke the CI
## Description

In https://github.com/jupyterlab/maintainer-tools/pull/174, nodejs was upgraded to 18 by default. This breaks our CI because no binary package for npm package `canvas` can be found and node fails to build the package on the default image.

See e.g. https://github.com/jupyterlab/jupyterlab/actions/runs/3930731145

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fix #13782

## Code changes

Bump `canvas` package to the latest (2.9.1 -> 2.11.0) so a binary file is available for nodejs 18

The devDependencies have not been modified as there is no new feature needed.

> The devDependencies

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Maybe do this as part of https://github.com/jupyterlab/jupyterlab/pull/13722?

**Comment by fcollonval** [comment]
I prefer to go fast with this to fix the CI and let Jason the time to finish #13722

**Comment by jtpio** [comment]
As you wish, bumping `canvas` was likely the last item to address to finish https://github.com/jupyterlab/jupyterlab/pull/13722.

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.6.x

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.5.x

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.6.x

**Pull request merged**
