### PR TITLE
Add scroll past end for codemirror documents

### LINKED ISSUE #813: TextEditor, allow scroll past EOF
Most editor allow to scroll past the end of a file, for example vim:

screen shot 2016-08-30 at 10 43 50

Which is extremely useful to have code at programmer eye level. 

The current text editor in JupyterLab does not seem to allow that when the text in the editor is longer than the editor window; it is far from critical, but I think is important for the long term usage of the editor. 

It might be just a codemirror option though I have not investigated.

### LINKED ISSUE #2993: File Editor crops last line
When a document gets large enough to use the full  `div` height, then the last line of the file in the file editor gets cropped.
toolbar1
It appears to me that the culprit is the microtoolbar on the file editor. When I manually give it a height of zero, the editor shows the last line properly:
toolbar2

cc @ellisonbg

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #813.  Fixes #2993.

<image src="https://user-images.githubusercontent.com/2096628/30494744-fa94215e-9a0e-11e7-8d99-5aeb30baaf86.png" width=400>

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Is there a way to set the length of the scoll-past-end buffer? It looks really long to me (including adding a scrollbar to a short document when it entirely fits in the div).

**Comment by blink1073** [comment]
No, it isn't configurable.  cf https://github.com/codemirror/CodeMirror/blob/master/addon/scroll/scrollpastend.js

**Comment by jasongrout** [comment]
I've really missed this. Thanks!

**Comment by ian-r-rose** [comment]
Maybe it's just my machine, but the extra padding doesn't seem to do a very good job calculating the necessary amount. For even a two-line file it pads so much that there is a scroll bar:
scroll

**Pull request merged**
