### PR TITLE
Upgrade yarn to 1.7 in devDependencies

### PR DESCRIPTION
**Pull request by gnestor**

### CODE REVIEW

**Comment by jasongrout** [comment]
huh, I thought this would pull in an updated upath?

**Comment by jasongrout** [comment]
Huh, it does seem that yarn 1.7 needs upath 1.0.5 to fix node 10 support: https://github.com/yarnpkg/yarn/pull/5769#issue-185185717. We have upath 1.0.4 right now in the lock file.

**Comment by jasongrout** [comment]
Thanks. Changes look good to me. I'll test it out in node 10.

**Comment by ian-r-rose** [comment]
Thanks!

**Pull request merged**
