### PR TITLE
Adds the variable reference to the key of the component

### PR DESCRIPTION
**Pull request by hbcarlos**
## References
Solves #11023 

## Code changes
Adds the variable reference to the key of the component

## User-facing changes
N/A

## Backwards-incompatible changes
N/A

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @hbcarlos!

Waiting for the Binder to finish building to double check it fixes the issue, but otherwise the diff looks good :+1:

**Comment by jtpio** [comment]
> Waiting for the Binder to finish building

Looks like the Binder fails to build, which seems to be something else (maybe on Binder / repo2docker side):

image

**Comment by fcollonval** [comment]
The error seems transient. I succeeded to launch the binder.

**Comment by jtpio** [comment]
This appears to work fine on Binder when reproducing the steps from the screencast in https://github.com/jupyterlab/jupyterlab/issues/11023#issue-990834328:


https://user-images.githubusercontent.com/591645/132633105-c4234ce7-e58d-4de0-be8f-411ec14d1cef.mp4

**Comment by jtpio** [comment]
The tree being misaligned when the `function variables` is expanded is a different issue.

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.1.x

**Pull request merged**
