### PR TITLE
Fix issue #13569: `source_hidden` not effective.

### LINKED ISSUE #13569: Cell `source_hidden` metadata is not effective on loading a notebook.
## Description

A cell whose input is hidden does not stay hidden after the notebook is closed and reopened.

## Reproduce
1. Create a new notebook, create a new cell, input `print("Hello world")`, and execute it.
2. Then click the left side to hide the source, and save the notebook.
3. Close the notebook, and open it again. The source code is still visible.

## Expected Behavior

The source code should remain hidden.

## Context

jupyterlab >= 4.0.0a31

## Proposed Solution

The root cause seems to be that, on loading the notebook, the following code is executed before the cell is ready, when `this.placeholder` is `true`. Perhaps should enclose the entire block by `this.ready.then(() { })`?

https://github.com/jupyterlab/jupyterlab/blob/e658b6f28e3501968e7fe8e211677c5378be14d0/packages/cells/src/widget.ts#L421-L430

### PR DESCRIPTION
**Pull request by yczhangsjtu**
## References

Fixes #13569

### CODE REVIEW

**Comment by yczhangsjtu** [comment]
This pull request is trying to fix #13569.

**Review by fcollonval — COMMENTED** [review]
Thanks @yczhangsjtu 

I pushed an improved version that ensure that `Cell.placeholder` is consistent with `Cell.ready`. And in addition I fixed the `outputHidden` case that suffer the same issue.

**Comment by yczhangsjtu** [comment]
Thanks a lot @fcollonval. Hope this fix appears in the next version soon.

**Comment by fcollonval** [comment]
Kicking the CI

**Pull request merged**
