### PR TITLE
Pin pywinpty, as the most recent release is causing problems.

### PR DESCRIPTION
**Pull request by ian-r-rose**
This is an attempt to fix build errors on appveyor.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@ian-r-rose, what error are you seeing? Our new release fixes critical several problems detected before.

**Comment by ian-r-rose** [comment]
Thanks for checking @ccordoba12! We are seeing some errors on our appveyor builds
```
Terminals not available (error was DLL load failed: The specified module could not be found.)
```
https://ci.appveyor.com/project/jupyterlab/jupyterlab/build/1.0.7256/job/wqbtk7igkmsax32e?fullLog=true#L4491

I'm not sure what is causing it at the moment...

**Comment by ian-r-rose** [comment]
I want to open an issue on winpty, but I don't quite have enough info yet to be very helpful :smile:

**Comment by ccordoba12** [comment]
We switched from compiling pywinpty with Visual Studio to Mingw because we were required to by the Anaconda guys. And that seems what's causing this problem.

We'll try to come up with a new release as soon as we can and let you know about it.

**Comment by ian-r-rose** [comment]
Thanks for the quick response @ccordoba12.

**Comment by ian-r-rose** [comment]
I think we should merge this so that our CI is working, then revert it as soon as we have a fix upstrem.

**Comment by andfoy** [comment]
I cannot find any error after performing a clean install of Python, pywinpty and the Notebook. I'll try to debug this error via AppVeyor RDP

**Pull request merged**
