### PR TITLE
chore(xterm): updating xterm to 2.4.0

### LINKED ISSUE #1863: Update to xterm 2.4
https://github.com/sourcelair/xterm.js/releases/tag/2.4.0

### PR DESCRIPTION
**Pull request by alexandercbooth**
Closes #1863.

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks again!

**Comment by alexandercbooth** [comment]
My pleasure!

Has the idea of using something like [greenkeeper](https://greenkeeper.io/) for dependencies ever been discussed?

**Comment by blink1073** [comment]
Good call, I just turned it on, let's see how it goes.

**Comment by alexandercbooth** [comment]
Nice! Hopefully helps out a little.

**Pull request merged**
