### PR TITLE
Link to the documentation in the extension manager federated dialog

### PR DESCRIPTION
**Pull request by jtpio**
## References

Minor fix to the extension manager dialog to link to the documentation.

## Code changes

Add a `<a>` element to create a link to the documentation.

Also add the `--extensions-in-dev-mode` flag to the Binder dev mode to make it easier to test with third-party (federated) extensions.

### Before

ext-manager-nolink

### After
ext-manager-link

### CODE REVIEW

**Review by jasongrout — APPROVED** [review]
Looks good to me. Thanks!

**Comment by jtpio** [comment]
Looks like the Binder dev mode fails to build:

image

**Comment by jtpio** [comment]
Seems to be building fine with node 14.

Looks like node 15 was recently added on conda-forge, which could explain why we haven't seen this before:

image

**Comment by jtpio** [comment]
For reference, to test this change on the Binder dev mode which adds the `--extensions-in-dev-mode` flag:

[Binder](https://mybinder.org/v2/gh/jtpio/jupyterlab/link-extension-manager?urlpath=lab-dev)

Then in a terminal: 

```
mamba install -c conda-forge/label/jupyterlab_rc -c conda-forge/label/jupyterlab_server_rc jupyterlab-python-file
```

or:

```bash
python -m pip install jupyterlab-python-file
```

Then reload the page to see the entry in the extension manager.

**Comment by jasongrout** [comment]
Thanks!

**Pull request merged**
