### PR TITLE
Pin tornado >=6.2.0

### PR DESCRIPTION
**Pull request by davidbrochart**
## References

We are seeing errors on Binder with master branch that could be related to Tornado:
```
[D 07:27:52.414 NotebookApp] 101 GET /binder/jupyter/user/jupyterlab-jupyterlab-gij02he9/lab-dev/api/yjs/text:file:setup.py (91.160.50.123) 0.650000ms
[I 07:27:52.414 NotebookApp] Trying to establish websocket connection to ws://localhost:48159/binder/jupyter/user/jupyterlab-jupyterlab-gij02he9/lab-dev/api/yjs/text:file:setup.py
[E 07:27:52.417 NotebookApp] Uncaught exception GET /binder/jupyter/user/jupyterlab-jupyterlab-gij02he9/lab-dev/api/yjs/text:file:setup.py (91.160.50.123)
    HTTPServerRequest(protocol='http', host='notebooks.gesis.org', method='GET', uri='/binder/jupyter/user/jupyterlab-jupyterlab-gij02he9/lab-dev/api/yjs/text:file:setup.py', version='HTTP/1.1', remote_ip='91.160.50.123')
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/websocket.py", line 956, in _accept_connection
        await open_result
      File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 672, in open
        return await super().open(self.port, path)
      File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 494, in open
        return await self.proxy_open('localhost', port, proxied_path)
      File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 444, in proxy_open
        await start_websocket_connection()
      File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 435, in start_websocket_connection
        self.ws = await pingable_ws_connect(request=request,
      File "/srv/conda/envs/notebook/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
        future.result()
    tornado.httpclient.HTTPClientError: HTTP 404: Not Found
```

## Code changes

Require `tornado >=6.2.0`.

## User-facing changes

None.

## Backwards-incompatible changes

None.

### CODE REVIEW

**Comment by jtpio** [comment]
> File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 672, in open

Probably there is something going on with `jupyter_server_proxy` in the middle.

**Comment by davidbrochart** [comment]
Note that `jupyter_server_ydoc` is a jupyter-server extension now.

**Comment by fcollonval** [comment]
Testing this PR on Binder, the websocket opens. But the file content is empty (for file and notebook).

**Comment by davidbrochart** [comment]
> the websocket opens

Really? I saw a 404.

**Comment by fcollonval** [comment]
Here is what I tried

- opening an existing file: it actually endlessly opens websockets

Peek 2022-07-29 11-25

**Comment by davidbrochart** [comment]
Indeed, the `tornado.httpclient.HTTPClientError: HTTP 404: Not Found` is in `.jupyter-server-log.txt`.

**Comment by jtpio** [comment]
Normally `.jupyter-server-log.txt` is for the "top-level" notebook server not the proxied JupyterLab iirc.

**Comment by jtpio** [comment]
Still seeing the empty notebook issue:

https://user-images.githubusercontent.com/591645/181738763-182e3cc9-3502-4dbd-885d-2e85fc5e2111.mp4

**Comment by jtpio** [comment]
Based on this:

https://github.com/jupyterlab/jupyterlab/blob/b88fee6ab324785d72be76a96e33de1b60087c54/binder/jupyter_notebook_config.py#L22

I would have expected the logs to be in `jupyterlab-dev.log`, but the file appears to be empty:

image

**Comment by jtpio** [comment]
> I would have expected the logs to be in `jupyterlab-dev.log`, but the file appears to be empty:

Actually its content can be inspected by opening a terminal and executing `cat jupyterlab-dev.log`:

image

**Comment by fcollonval** [comment]
Yes the current state makes any document (file or notebook) empty.

**Comment by jtpio** [comment]
Some logs:

```
[D 2022-07-29 10:27:00.795 ServerApp] Kernel args: {'kernel_name': 'python3', 'cwd': '/home/jovyan'}
[D 2022-07-29 10:27:00.797 ServerApp] 201 POST /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/sessions?1659090420728 (127.0.0.1) 38.88ms
[W 2022-07-29 10:27:00.937 ServerApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
[D 2022-07-29 10:27:00.939 ServerApp] 200 GET /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/sessions?1659090420879 (127.0.0.1) 3.11ms
[W 2022-07-29 10:27:00.944 ServerApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
[D 2022-07-29 10:27:00.947 ServerApp] 200 GET /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/metrics/v1?1659090420894 (127.0.0.1) 3.43ms
[W 2022-07-29 10:27:01.032 ServerApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
[D 2022-07-29 10:27:01.034 ServerApp] 200 PATCH /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/sessions/df3c85f2-1694-4a6c-b83c-d515f951922d?1659090420981 (127.0.0.1) 2.66ms
[W 2022-07-29 10:27:01.037 ServerApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
[D 2022-07-29 10:27:01.038 ServerApp] 200 GET /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/kernels?1659090420985 (127.0.0.1) 2.88ms
[W 2022-07-29 10:27:01.038 LabApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
[D 2022-07-29 10:27:01.040 LabApp] 204 PUT /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/lab/api/workspaces/default?1659090420995 (127.0.0.1) 4.65ms
[W 2022-07-29 10:27:01.082 ServerApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
[D 2022-07-29 10:27:01.082 ServerApp] Using contents: services/contents
[W 2022-07-29 10:27:01.084 ServerApp] 404 GET /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/yjs/json:notebook:Untitled2.ipynb (127.0.0.1) 3.17ms referer=None
[W 2022-07-29 10:27:01.176 ServerApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
[D 2022-07-29 10:27:01.178 ServerApp] 200 GET /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/sessions?1659090421133 (127.0.0.1) 2.05ms
[W 2022-07-29 10:27:01.180 ServerApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
[D 2022-07-29 10:27:01.181 ServerApp] 200 PATCH /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/sessions/df3c85f2-1694-4a6c-b83c-d515f951922d?1659090421130 (127.0.0.1) 2.28ms
[D 2022-07-29 10:27:01.272 ServerApp] Initializing websocket connection /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/kernels/b65d992b-4d98-4775-9376-f7821dd4eba6/channels
[W 2022-07-29 10:27:01.274 ServerApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
[D 2022-07-29 10:27:01.274 ServerApp] Requesting kernel info from b65d992b-4d98-4775-9376-f7821dd4eba6
[D 2022-07-29 10:27:01.275 ServerApp] Connecting to: tcp://127.0.0.1:40339
[W 2022-07-29 10:27:01.281 ServerApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
[D 2022-07-29 10:27:01.281 ServerApp] Found kernel python3 in /srv/conda/envs/notebook/share/jupyter/kernels
[D 2022-07-29 10:27:01.282 ServerApp] Found kernel xpython-raw in /srv/conda/envs/notebook/share/jupyter/kernels
[D 2022-07-29 10:27:01.282 ServerApp] Found kernel xpython in /srv/conda/envs/notebook/share/jupyter/kernels
[D 2022-07-29 10:27:01.285 ServerApp] 200 GET /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/kernelspecs?1659090421239 (127.0.0.1) 5.05ms
[W 2022-07-29 10:27:01.416 ServerApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
[D 2022-07-29 10:27:01.416 ServerApp] Using contents: services/contents
[W 2022-07-29 10:27:01.418 ServerApp] 404 GET /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/yjs/json:notebook:Untitled2.ipynb (127.0.0.1) 2.58ms referer=None
[D 2022-07-29 10:27:01.509 ServerApp] Received kernel info: {'status': 'ok', 'protocol_version': '5.3', 'implementation': 'ipython', 'implementation_version': '8.2.0', 'language_info': {'name': 'python', 'version': '3.8.13', 'mimetype': 'text/x-python', 'codemirror_mode': {'name': 'ipython', 'version': 3}, 'pygments_lexer': 'ipython3', 'nbconvert_exporter': 'python', 'file_extension': '.py'}, 'banner': "Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) \nType 'copyright', 'credits' or 'license' for more information\nIPython 8.2.0 -- An enhanced Interactive Python. Type '?' for help.\n", 'help_links': [{'text': 'Python Reference', 'url': 'https://docs.python.org/3.8'}, {'text': 'IPython Reference', 'url': 'https://ipython.org/documentation.html'}, {'text': 'NumPy Reference', 'url': 'https://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy Reference', 'url': 'https://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib Reference', 'url': 'https://matplotlib.org/contents.html'}, {'text': 'SymPy Reference', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas Reference', 'url': 'https://pandas.pydata.org/pandas-docs/stable/'}]}
[D 2022-07-29 10:27:01.510 ServerApp] 101 GET /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/kernels/b65d992b-4d98-4775-9376-f7821dd4eba6/channels?session_id=444c9be7-fd29-4607-8f77-119e687a5f2a (127.0.0.1) 239.31ms
[D 2022-07-29 10:27:01.511 ServerApp] Opening websocket /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/kernels/b65d992b-4d98-4775-9376-f7821dd4eba6/channels
[D 2022-07-29 10:27:01.511 ServerApp] Getting buffer for b65d992b-4d98-4775-9376-f7821dd4eba6
[D 2022-07-29 10:27:01.511 ServerApp] Connecting to: tcp://127.0.0.1:50823
[D 2022-07-29 10:27:01.512 ServerApp] Connecting to: tcp://127.0.0.1:40339
[D 2022-07-29 10:27:01.512 ServerApp] Connecting to: tcp://127.0.0.1:42939
[D 2022-07-29 10:27:01.513 ServerApp] Connecting to: tcp://127.0.0.1:53231
[D 2022-07-29 10:27:01.513 ServerApp] Connecting to: tcp://127.0.0.1:40339
[D 2022-07-29 10:27:01.513 ServerApp] Connecting to: tcp://127.0.0.1:42939
[D 2022-07-29 10:27:01.515 ServerApp] Nudge: attempt 1 on kernel b65d992b-4d98-4775-9376-f7821dd4eba6
[D 2022-07-29 10:27:01.520 ServerApp] Nudge: IOPub received: b65d992b-4d98-4775-9376-f7821dd4eba6
[D 2022-07-29 10:27:01.520 ServerApp] Nudge: resolving iopub future: b65d992b-4d98-4775-9376-f7821dd4eba6
[D 2022-07-29 10:27:01.521 ServerApp] Nudge: shell info reply received: b65d992b-4d98-4775-9376-f7821dd4eba6
[D 2022-07-29 10:27:01.521 ServerApp] Nudge: resolving shell future: b65d992b-4d98-4775-9376-f7821dd4eba6
[D 2022-07-29 10:27:01.523 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (idle)
[D 2022-07-29 10:27:01.525 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (idle)
[D 2022-07-29 10:27:01.532 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (busy)
[D 2022-07-29 10:27:01.533 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (idle)
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[D 2022-07-29 10:27:01.630 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (busy)
[IPKernelApp] WARNING | No such comm: d256a176-28ef-4528-947b-97d94d6a6065
[D 2022-07-29 10:27:01.631 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: comm_close
[D 2022-07-29 10:27:01.633 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (busy)
[D 2022-07-29 10:27:01.636 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (idle)
[D 2022-07-29 10:27:01.638 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (busy)
[D 2022-07-29 10:27:01.640 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (idle)
[D 2022-07-29 10:27:01.643 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (idle)
[D 2022-07-29 10:27:01.683 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (busy)
[D 2022-07-29 10:27:01.685 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (idle)
[D 2022-07-29 10:27:01.692 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (busy)
[D 2022-07-29 10:27:01.694 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (idle)
[D 2022-07-29 10:27:01.790 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (busy)
[D 2022-07-29 10:27:01.792 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (idle)
[W 2022-07-29 10:27:01.823 LabApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
[D 2022-07-29 10:27:01.824 LabApp] 204 PUT /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/lab/api/workspaces/default?1659090421793 (127.0.0.1) 2.63ms
[D 2022-07-29 10:27:01.870 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (busy)
[D 2022-07-29 10:27:01.872 ServerApp] activity on b65d992b-4d98-4775-9376-f7821dd4eba6: status (idle)
[W 2022-07-29 10:27:01.903 ServerApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
[D 2022-07-29 10:27:01.903 ServerApp] Using contents: services/contents
[W 2022-07-29 10:27:01.904 ServerApp] 404 GET /binder/jupyter/user/davidbrochart-jupyterlab-p5hcirer/lab-dev/api/yjs/json:notebook:Untitled2.ipynb (127.0.0.1) 2.81ms referer=None
[W 2022-07-29 10:27:02.357 ServerApp] Clearing invalid/expired login cookie username-notebooks-gesis-org
```

**Comment by davidbrochart** [comment]
> Normally `.jupyter-server-log.txt` is for the "top-level" notebook server not the proxied JupyterLab iirc.

I don't know how Binder works, but by "top-level notebook" do you mean it's actually using some parts of the legacy notebook?
`jupyter_server_ydoc` doesn't have the Jupyter nbextension, only the Jupyter server extension.

**Comment by jtpio** [comment]
It's actually more something specific to `jupyter-server-proxy`: https://github.com/jupyterhub/jupyter-server-proxy

The top-level notebook server is the one with PID 25 on the screenshot below.
The JupyterLab instance used when following the Binder link (under `/lab-dev`) is the one with PID 27

image

**Comment by davidbrochart** [comment]
I opened https://github.com/jupyter-server/jupyter_server_ydoc/pull/20, I think it is because `jupyter_server_ydoc` didn't support the server base URL.

**Comment by jtpio** [comment]
Ah nice thanks @davidbrochart for catching this!

**Pull request closed without merging**
