### PR TITLE
Fix extension toggling at different level

### PR DESCRIPTION
**Pull request by divyansshhh**
## References
Fixes jupyterlab/jupyterlab#16101

## Code changes
Changed the _AppHandler.toggle_extension method to look into all levels to decide whether an extension is enabled or not, if it's not, we change the page_config at the specified level

### CODE REVIEW

**Comment by krassowski** [comment]
> If an extension is [disabled] at the sys-prefix level, it can't be enabled at the user level.

I think this was intentional prior to having extension locks. This guaranteed that admin could disable extension globally and user would not be able to change it.

Now that we have plugin locks this change makes sense to me.

This looks like a step in the right direction, but we would need some tests to:
- ensure that plugin cannot be toggled if locked at the higher level
- ensure that `jupyter labextension list` reflects the expected status

Those can be added in the "usage" tests group.

**Comment by divyansshhh** [comment]
@krassowski I was trying to do the requested changes for this PR but on running the `disable` command for any extension, I get the following message and nothing changes in my `~/.jupyter/labconfig/page.json` file.

```
╰─⠠⠵ jupyter-labextension disable bqplot --level user
Starting with JupyterLab 4.1 individual plugins can be re-enabled in the user interface. While all plugins which were previously disabled have been locked, you need to explicitly lock any newly disabled plugins by using `jupyter labextension lock` command.
```

Is there something I'm missing?

**Comment by divyansshhh** [comment]
FYI, this also needs jupyterlab/jupyterlab_server#448

**Comment by divyansshhh** [comment]
@krassowski can you re-run the checks here now that jupyterlab_server 2.27.0 is released (I don't have the perms to)

**Comment by divyansshhh** [comment]
@krassowski the failures seem unrelated to this PR, can you take a look and let me know if this is good to merge?

**Review by krassowski — APPROVED** [review]
Thank you @divyansshhh!

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.1.x

**Pull request merged**
