### PR TITLE
Use latest pywinpty version on Appveyor

### PR DESCRIPTION
**Pull request by andfoy**
See https://github.com/spyder-ide/pywinpty/issues/105
I'm creating this PR only to test the CI building process failure on AppVeyor

### CODE REVIEW

**Comment by andfoy** [comment]
We're missing the ``libgcc_s_dw2-1.dll`` library. I'll add it to the pywinpty wheel release and try once again.

**Comment by andfoy** [comment]
``libwinpthread-1.dll``

**Comment by ccordoba12** [comment]
@ian-r-rose, your tests are now passing thanks to @andfoy's work, so this one is ready to be merged.

**Comment by ian-r-rose** [comment]
Thanks @andfoy and @ccordoba12 for the quick fix!

**Pull request merged**
