### PR TITLE
Build cleanup

### LINKED ISSUE #5017: Build Quality of Life Improvements
- We need to add the following to `webpack.config.js`: `optimization: minimizer: [new UglifyJsPlugin({ cache: process.platform !== "win32" })]`, to help avoid the path length restriction on Windows.  I ran into this today on a machine where I don't have admin access to make a change to the registry. 

     I was getting paths like the following: `node_modules\\\\.cache\\\\uglifyjs-webpack-plugin\\\\content-v2\\\\sha512\\\\f0\\\\d9\\\\41b44207c2fa7189a30f3b6aeb8e22585bd4b0a78f8de3894c218f5b16de8ff9e48f3e54f767f6f69f99b6ba0a41538dd5b163d436d72ceb0ba4f3d4fbd`

- We should also consider making `dev_build` the default option for `jupyter lab build` (and `labextension install`), and only uglify when explicitly asked, to avoid taking up large amounts of CPU, RAM, and time.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #5017 

- Do not cache during uglify on Windows to avoid creating long paths
- Use `dev_mode` by default when building (but ship prod mode files)
- Run the test builds directly, since a failing TS build does not stop the build, cf https://github.com/webpack-contrib/karma-webpack/issues/66.  Fixes the errors that running the builds directly exposed.
- Display the version and app directory when building

### CODE REVIEW

**Comment by blink1073** [comment]
CI is being really mean today:

```
error Couldn't find package "@phosphor/algorithm@^1.1.2" required by "@jupyterlab/apputils@^0.17.2" on the "npm" registry.
```

(oh rly?: https://www.npmjs.com/package/@phosphor/algorithm).  Ugh...)

**Comment by blink1073** [comment]
Pip installs are also failing randomly:

```
+pip install -q -e '.[test]'
Command "/home/travis/virtualenv/python2.7.14/bin/python -c "import setuptools, tokenize;__file__='/home/travis/build/jupyterlab/jupyterlab/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/travis/build/jupyterlab/jupyterlab/
```

**Comment by ian-r-rose** [comment]
Hm, needs a rebase?

**Comment by blink1073** [comment]
Rebased.

**Comment by ian-r-rose** [comment]
Thanks!

**Pull request merged**
