### PR TITLE
Fixes behavior of `maxNumberOutputs`

### LINKED ISSUE #12321: maxNumberOutputs break ipdb
## Description

Ipdb output appears to count as mime renders. It removes the latest renders _and_ clicking to show complete output makes things worse by breaking future output.

## Reproduce

Set `maxNumberOutputs` to 50 and run this example:
```
import ipdb
def inf_loop():
    i = 0
    while True:
        print(i)
        i += 1
ipdb.runcall(inf_loop)
```
Press "n", then hold down the <ENTER> key until at least 50 "next" commands have been processed. If one clicks on the "click this message to get the complete output", it'll often show some of the buffered output. Press "n" again and hold <ENTER>. You'll see the scrollbar and output display fluttering around, but it just keeps deleting and reappending the output that appeared when clicking on the warning. No new output appears.

16260-1-0_trimmed_ipdb_output

## Expected behavior

It works the same as `maxNumberOutputs=0`.

## Context
- JupyterLab version: 3.3.0

### LINKED ISSUE #12497: `maxNumberOutputs` breaks interactive cell outputs
## Description

this issue is a superset of #12321

There is a (critical?) bug in the current implementation of `maxNumberOutputs` (a user setting from `notebook-extension`) that breaks ipdb functionality by default for our whole user base. The bug will also affect any other situation in which output is added iteratively to an `OutputArea`.

When the output limit is reached for a given cell, a warning message is displayed instead of further outputs. Currently, clicking on the warning message will remove the warning and flush all outputs that had been queued *up to that specific that point in time*. If further outputs are generated afterwards, as in the ipdb use-case, none of them will be displayed.

## Reproduce

See #12321 for a repro case (@mlucool)

## Expected behavior

`maxNumberOutputs` should either:

  a) behave in a paginated way. Once `maxNumberOutputs` of outputs are shown, display the warning. If the warning is clicked, show up to `maxNumberOutputs * 2` outputs before displaying a new warning. If that warning is clicked, keep going until `maxNumberOutputs * 3`, and so forth

  b) behave as a one-time flood control. Once `maxNumberOutputs` of outputs are shown, display the warning. If the warning is clicked, show all further outputs

Currently I'm leaning towards b) as the correct behavior. It may still cause performance hiccups, but at least in that case said hiccup will be caused directly by a user's input/explicit request.

## Context

The `maxNumberOutputs` machinery is currently implemented in two functions:

https://github.com/jupyterlab/jupyterlab/blob/12c5ed914d6336d1f72fc8f71ec98fcffb0aa57f/packages/outputarea/src/widget.ts#L426-L469

https://github.com/jupyterlab/jupyterlab/blob/12c5ed914d6336d1f72fc8f71ec98fcffb0aa57f/packages/outputarea/src/widget.ts#L488-L499

### PR DESCRIPTION
**Pull request by telamonian**
## References

fixes #12321, fixes #12497

## Code changes

Fixes code/logic implementing the behavior of `maxNumberOutputs`. Of the two choices for correct behavior that I mentioned in #12497:

> a) behave in a paginated way. Once `maxNumberOutputs` of outputs are shown, display the warning. If the warning is clicked, show up to `maxNumberOutputs * 2` outputs before displaying a new warning. If that warning is clicked, keep going until `maxNumberOutputs * 3`, and so forth
> 
> b) behave as a one-time flood control. Once `maxNumberOutputs` of outputs are shown, display the warning. If the warning is clicked, show all further outputs

I went for now with option b). The code in this PR is designed to make switching to option a) straightforward, if we decide that's better. Also includes some streamlining of typing and conditional logic in `OutputArea`.

## User-facing changes

Fixes behavior of `maxNumberOutputs`; no more lost outputs.

## Backwards-incompatible changes

none

### CODE REVIEW

**Review by fcollonval — COMMENTED** [review]
Thank @telamonian 

Would you mind adding a test for this as it is a tricky corner case?

**Comment by telamonian** [comment]
Thanks for the quick feedback, @fcollonval. I appreciate it

> Would you mind adding a test for this as it is a tricky corner case?

Sounds good to me in theory. I assume Galata could be used for such a test? I've not had a chance to use it yet. Could you point me to some existing examples of good/relevant test cases in the code base?

**Comment by telamonian** [comment]
Also, can someone explain to me in full what `OutputArea._outputTracker` is supposed to do/how it works? I have questions, eg:

https://github.com/jupyterlab/jupyterlab/blob/0e73292d40ee6a4bf7b2d3443e6e0acced9b1edd/packages/outputarea/src/widget.ts#L488-L489



Pinging @goanpeca @afshin

**Comment by telamonian** [comment]
I tackled the TODO in `OutputArea` about improving the styling of the element that gets shown on output overflow:

https://github.com/jupyterlab/jupyterlab/blob/0e73292d40ee6a4bf7b2d3443e6e0acced9b1edd/packages/outputarea/src/widget.ts#L467

Before:

image

After:

image

**Comment by fcollonval** [comment]
> Sounds good to me in theory. I assume Galata could be used for such a test? I've not had a chance to use it yet. Could you point me to some existing examples of good/relevant test cases in the code base?

Thanks for the interest @telamonian 
The best example for your case is certainly the notebook run test: https://github.com/jupyterlab/jupyterlab/blob/master/galata/test/jupyterlab/notebook-run.test.ts
The idea is to create a test notebook with prepopulate cells. Then execute it and do the test/interaction needed.

You may be interested in setting non-default value for `maxNumberOutputs`. You can achieve that using the same fixture than that test:

https://github.com/jupyterlab/jupyterlab/blob/6b79e85a380a631c0b71d74162c041d8c175f0e7/galata/test/jupyterlab/collapsible-headings.test.ts#L63-L69

**Comment by fcollonval** [comment]
Thanks for improving the styling

> maybe it should be white text on the blue background of `--jp-brand-color1`?

I like the current proposition. I fear that white on blue background is too much highlighting for this feature.

**Comment by fcollonval** [comment]
> Also, can someone explain to me in full what `OutputArea._outputTracker` is supposed to do/how it works? I have questions, eg:
> 
> https://github.com/jupyterlab/jupyterlab/blob/0e73292d40ee6a4bf7b2d3443e6e0acced9b1edd/packages/outputarea/src/widget.ts#L488-L489

The output tracker is only used when copying a output. So I would say the warning should not be tracked.

https://github.com/jupyterlab/jupyterlab/blob/6b79e85a380a631c0b71d74162c041d8c175f0e7/packages/notebook-extension/src/index.ts#L1293

**Comment by telamonian** [comment]
Oh wow. #11689 has conflict-ed this PR to heck and back

@fcollonval So did the code you added in https://github.com/fcollonval/jupyterlab/commit/9c6d84c243bd65dc239c6bb89ecc6e82b8d1fec5 already fix the underlying issues behind #12321 and #12497? Jeez, you could have given me a little warning...

Assuming the issues really are already fixed, what's your opinion on how we should resolve this PR? Is there anything that should be kept over what currently in master? I guess there is still at least the styling improvement for the overflow widget

**Comment by fcollonval** [comment]
> Jeez, you could have given me a little warning...

Sorry that PR was so large and hanging for so long I was sure this one will go through first. My goal there was not to fix any specific issue; just to clean up the code as the first approach to refactor the search through notebook was using new search engine per output type (approach finally dropped as too complex).

So I definitely would say this PR is needed.

**Comment by afshin** [comment]
Hey Max, sorry about that! I took a long time reviewing @fcollonval's PR and ended up causing a painful rebase for you!

**Comment by fcollonval** [comment]
Working on the rebase

**Comment by fcollonval** [comment]
@telamonian I rebased the code - using the simpler approach of displaying everything when the link is clicked. I added an exception, if one of the output is requesting an input, all previous outputs will be displayed and the provided answer is certain to be displayed (but not subsequent outputs). Finally I added integration tests.

**Review by afshin — APPROVED** [review]
Cheers Max and Frédéric!

**Comment by jtpio** [comment]
Nice, thanks all!

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.4.x

**Pull request merged**
