### PR TITLE
ToC: nests methods/classes within previous toc entries for .py files.

### LINKED ISSUE #10477: ToC: nested functions/classes are not indented in ToC
### Problem

Nested functions/classes are not indended in ToC.  

e.g. given code:
```python
class Dog:
    def bark():
        pass
```

Users will currently see in ToC:
```
class Dog
def bark
```

But it would be preferable if they saw:
```
class Dog
    def bark
```

### Proposed Solution

Keep track of indentation in order to appropriately nest functions/classes

### Additional context

This issue was originally raised by @stefansimik on jupyterlab-toc project, see https://github.com/jupyterlab/jupyterlab-toc/issues/140.

I submitted a PR implementing changes to make this work to jupyterlab-toc and was asked to resubmit it here: https://github.com/jupyterlab/jupyterlab-toc/pull/153

Thanks!

### PR DESCRIPTION
**Pull request by hottwaj**
## References

Fixes #10477
ported from PR153 on jupyterlab-toc, see https://github.com/jupyterlab/jupyterlab-toc/pull/153

## Code changes

in ToC, keep track of indentation level so that classes/methods can be appropriately nested within ToC

## User-facing changes

given code:

```python
class Dog:
    def bark():
        pass
```

Users would previously see in ToC:

```
class Dog
def bark
```

With this change users will see in ToC:

```
class Dog
    def bark
```

## Backwards-incompatible changes

None

Thanks!

### CODE REVIEW

**Comment by fcollonval** [comment]
Thank you for pushing this PR.

Short update because your example is actually working. So this is the problem:

```py
class A:
    def b():
        def c():
            pass
        class B:
            pass
```

**Before**

image

**After**

image

**Review by fcollonval — APPROVED** [review]
LGTM

Would you mind adding a UI test?

**Comment by hottwaj** [comment]
Thanks, will look into the UI test.  Should this capture the ToC output of e.g. your example above?

**Comment by fcollonval** [comment]
> Thanks, will look into the UI test. Should this capture the ToC output of e.g. your example above?

Yes this will be awesome. Let me know if you need pointer with the UI test machinery.

**Comment by hottwaj** [comment]
Hi there, as I just mentioned on #10475 I submitted this PR while briefly off work with a new baby, and since then have gone back to work with even less free time than before :) 

I would love to finish work on this but it will be a while before I can squeeze it in.  If someone else has a moment to finish please go ahead, and sorry for not being able to prioritise this higher.

Thanks!

**Comment by jtpio** [comment]
@fcollonval is this PR still relevant after the TOC refactor in https://github.com/jupyterlab/jupyterlab/pull/12374?

**Pull request closed without merging**
