### PR TITLE
Remove issue templates to use the organization ones

### PR DESCRIPTION
**Pull request by fcollonval**
This is a follow-up of https://github.com/jupyterlab/.github/pull/1.

~~This adds two new entries to the template issue panel to redirect users to Gitter and discourse.~~

Xref: https://github.com/jupyterlab/team-compass/issues/117#issuecomment-875801069

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

Maybe we could even make them apply to the whole organization by placing them in https://github.com/jupyterlab/.github/blob/master/.github/ISSUE_TEMPLATE/config.yml?

**Comment by fcollonval** [comment]
Thanks for the suggestion @jtpio

It looks like if a repository defines its own `ISSUE_TEMPLATE` folder, the organization configuration will be ignored. For example, at the organization level, there is already a Gitter link - but it is not showing in jupyterlab or jupyterlab-git (both have a local ISSUE_TEMPLATE folder).

Should we remove the templates at the repository level to prefer the one at the organization level?

**Comment by jtpio** [comment]
> Should we remove the templates at the repository level to prefer the one at the organization level?

I think it would make sense? Historically, the https://github.com/jupyterlab/.github repo was added after the issue templates were already created in the individual repos.

**Comment by fcollonval** [comment]
Ok I'll bring the subject on tomorrow's dev meeting.

**Review by goanpeca — APPROVED** [review]

**Comment by jtpio** [comment]
> Ok I'll bring the subject on tomorrow's dev meeting.

Sounds good :+1:

**Comment by jtpio** [comment]
This should be good to go now (done in https://github.com/jupyterlab/.github/pull/1).

This is what it looks like on a repo in the `jupyterlab` organization:

image

**Comment by fcollonval** [comment]
Working as expected:

image

**Pull request merged**
