### PR TITLE
Don't convert JSON arrays to strings

### PR DESCRIPTION
**Pull request by gnestor**
Replacement of https://github.com/jupyterlab/jupyterlab/pull/4469

(I accidentally submitted a PR against my master branch)

### CODE REVIEW

**Comment by gnestor** [comment]
@jasongrout This one just reuses the `extract` function directly above it to do the deep-copying. I think this is how it worked originally, then that `JSONExt.isArray` snuck in for some reason.

**Comment by jasongrout** [comment]
ah, good catch! I'd collapse those two lines into one (we don't need that `item` variable anymore), and I think we have a winner!

**Comment by jasongrout** [comment]
Sure enough! https://github.com/gnestor/jupyterlab/commit/217d6fa01e889d94e14ad8ab4cdff357fbed8f07#diff-4a0fd4e225cc19332cda5c8141fe1310L243

**Comment by gnestor** [comment]
Yep! So "convert multi-line strings to strings" sound like it probably serves a purpose... Is this meant to handle streams of text?

**Comment by jasongrout** [comment]
It's meant to handle this case in the spec where long strings are broken by lines: https://nbformat.readthedocs.io/en/latest/format_description.html#display-data (i.e., the multiline string lines, see https://github.com/jupyterlab/jupyterlab/blob/64183d8f944c310f36ba09617734043a67d61969/packages/coreutils/src/nbformat.ts#L76, https://github.com/jupyterlab/jupyterlab/blob/64183d8f944c310f36ba09617734043a67d61969/packages/coreutils/src/nbformat.ts#L83

I guess the real question here is: have those multiline strings been taken care of at this point in the code. I think so, and in fact it looks like things have been JSON.parsed as well. However, the typing indicates that it is still expecting something that might contain those multiline strings.

**Pull request merged**
