### PR TITLE
Check if cell is disposed before accessing in cell tools.

### PR DESCRIPTION
**Pull request by ian-r-rose**

### CODE REVIEW

**Comment by sccolbert** [comment]
What case are you hitting where you are accessing a disposed model?

**Comment by ian-r-rose** [comment]
When the model is stored in a remote store (like Google Drive), the fields on the cell model (such as `metadata`) are no longer valid after the notebook is disposed, even though there is still a reference to the cell model in the cell tools widget.

I know the cell model is going to change, but it seemed this was a pretty minor fix.

**Comment by sccolbert** [comment]
👍

**Comment by blink1073** [comment]
Thanks!

**Pull request merged**
