### PR TITLE
Clarifies workflow to export as Reveal.js slides

### LINKED ISSUE #5018: Workflow to create a slide presentation?
Dear All, 
What is the current workflow to create a slide presentation out of a **JupyterLab** notebook?

I understand that in the [classic] Jupyter Notebook the workflow is:
1. View → Cell Toolbar → Slideshow
2. Then each cell will have a menu to choose from Slide, Sub-slide, etc., ...
3. On the terminal: 
$ jupyter nbconvert foo.ipynb --to slides --post serve

Thanks,
Temok

### PR DESCRIPTION
**Pull request by duarteocarmo**
Closes #5018

## References
This addresses issues #5018 and other exporting doubts that might come in the future. 

## Code changes

Added a new `docs/source/user/export.rst` file for future detailed explanations on exporting notebooks. (particularly how to export as `.pdf`)

Also added two screenshots to illustrate cases. 

## User-facing changes

A new section on the documentation pages:
Screen Shot 2019-06-05 at 14 45 48
Screen Shot 2019-06-05 at 14 45 36

## Backwards-incompatible changes

None.

### CODE REVIEW

**Comment by duarteocarmo** [comment]
@jasongrout what do you think about this? To help out with #5018

**Comment by jasongrout** [comment]
Thanks! This list is built dynamically depending on what nbconvert offers, so maybe mentioning something about how they might have different options depending on their nbconvert configuration, but here are some common export options might make sense.

**Comment by duarteocarmo** [comment]
@jasongrout adding that as we speak

**Comment by duarteocarmo** [comment]
@jasongrout and @blink1073 added nbconvert note. 
Not sure why some of the integrations tests are failing tough. 
`Cmd.exe exited with code '1'.`

**Comment by blink1073** [comment]
Thanks!  The failure is unrelated.

**Comment by duarteocarmo** [comment]
@jasongrout and @blink1073 thanks for letting me contribute!

I [wrote a blog post](https://duarteocarmo.com/misc/2019/06/08/open-source-contribution.html) about the process if you’re interested 😅

**Comment by blink1073** [comment]
Awesome, thank you for writing that up!  Would you consider us making it a guest post on the Jupyter blog?

**Comment by blink1073** [comment]
Also, I am curious as to what you think is needed to make Jupyterlab ready for prime time, as you say.

**Comment by duarteocarmo** [comment]
@blink1073 of course! Anything I should do?

**Comment by duarteocarmo** [comment]
Well, I think the project is very close, but a couple of things are still buggy (rendering, pdf conversion, themes, syntax), and a lot of the extension/add on ecosystem hasn’t migrated yet to jupyter lab.

**Comment by blink1073** [comment]
I'm not actually sure how the process works for guest posts, I'll find out and get back to you 😀.  If you have specific bugs that you're seeing, please open some issues.  😉

**Comment by duarteocarmo** [comment]
Ok, that sounds good!

I’ll keep opening issues for whatever I see in the future. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
