### PR TITLE
Cleanup of kernel selector

### LINKED ISSUE #278: Switch kernel Dialog issues.
I used the command palette to switch kernel.

The dialog seem to have extra-option that are weird:
- None
- And the name of my current notebook.

The None seem strange, the name of current notebook is I guess because you want a way to allow notebook to attach in a simpleway to existing kernels.

screen shot 2016-07-09 at 12 42 28

May I suggest to name this section "already existing kernels", and the first one "Start new kernel" using `optgroups` instead of disables lines ?

Also if I click cancel, my current notebook kernel is still shut down, so I think that might be a bug.

### LINKED ISSUE #1389: New notebook pulldown looks a bit busted
When I hit the plus button in the upper left and ask to make a new notebook, my pulldown in the dialog looks like this:

screenshot from 2016-12-06 14-21-19

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #278.  Fixes #1389.

screen shot 2017-01-20 at 7 13 36 am

screen shot 2017-01-20 at 7 25 13 am

### CODE REVIEW

**Comment by blink1073** [comment]
cc @cameronoelsen @Carreau

**Comment by afshin** [comment]
👍

**Comment by Carreau** [comment]
Sweet ! Looks great !

**Comment by cameronoelsen** [comment]
Much better :) 👍

**Pull request merged**
