### PR TITLE
Adding memory usage warning with nbresuse

### PR DESCRIPTION
**Pull request by Gsbreddy**
This PR will address the issue Adding memory usage warning with nbresuse #8280

### CODE REVIEW

**Comment by blink1073** [comment]
Hi @Gsbreddy, thanks for making your first contribution!  It looks like the linter isn't happy, can you please run `jlpm run lint` locally and push those changes?  Also, can you please include a screenshot showing the style change?

**Comment by Gsbreddy** [comment]
Sure thing.

**Comment by Gsbreddy** [comment]
Hey @blink1073 , I checked the lint and pushed the changes.

**Comment by blink1073** [comment]
Thanks!  Can you please also include a screenshot of the statusbar showing the warning style?  You can trigger high memory usage in ipykernel with something like `a = [1] * (10 ** 6)`.

**Comment by Gsbreddy** [comment]
Let me build lab and get that for ya.

**Comment by Gsbreddy** [comment]
Here you go.
image

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/nbresuse-seeking-new-maintainers/2530/11

**Pull request merged**
