### PR TITLE
Pull out filebrowser context menu download UI into separate plugin so it can be disabled easily

### PR DESCRIPTION
**Pull request by DianeHu**
## References

Partially addresses #5274, I'll be making additional PRs to pull download UI into separate plugins for other extensions.

## Code changes

Pulled all download UI code in filebrowser-extension into a separate plugin so that it can be disabled easily if a user wants to customize a JL environment to not have those features available. Specifically, filebrowser-extension adds the download and copy download link commands into the context menu, so those two commands can now be easily set to not display.

## User-facing changes

No user-facing changes with the extension enabled as is. If @jupyterlab/filebrowser-extension:download is disabled (the ID for the new plugin), then the context menu will no longer show download or copy download link as an option:
image

## Backwards-incompatible changes

None

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by AgoCan** [comment]
May I ask, How to use it?

**Comment by jtpio** [comment]
@AgoCan once JupyterLab 3.1 is out, it will be possible to disable the plugin with the following command:

```bash
jupyter labextension disable @jupyterlab/filebrowser-extension:download
```

You might also want to try it with the next 3.1 alpha release when it's published.

**Comment by AgoCan** [comment]
@jtpio thanks

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/build-customized-jupyerlab-from-source-code/1887/6

**Comment by cwchung85** [comment]
I have tried the following:
jupyter labextension disable @jupyterlab/filebrowser-extension:download

This works great! When I right click the right mouse, Download or Download Link entry do not show up any more! Thanks!

Now, the File -> Download entry is still present. Does it require a different disable? Please advise.

Thanks!

**Pull request merged**
