### PR TITLE
Add 0.32 release notes.

### PR DESCRIPTION
**Pull request by ian-r-rose**

### CODE REVIEW

**Comment by jasongrout** [comment]
I added two more changes: the change that forced services to have a major version bump, and a note that kernels now indicate restarts in the kernel.

Looks good to me! I'll merge when we are satisified the tests pass.

**Comment by ian-r-rose** [comment]
@jasongrout Right now, the changelog is autogenerated from the GitHub release notes. We can abandon this approach and author it directly, but I don't think we should be doing a mixture. What do you think?

**Comment by ian-r-rose** [comment]
(I agree with flagging the services change, that was an oversight).

**Comment by jasongrout** [comment]
Sorry, didn't realize it was autogenerated. Can you make the two changes
there?

Jason

**Comment by ian-r-rose** [comment]
Happy to make the changes there. We can also abandon the auto-generation, if we think it's a good idea. That script can easily be a one-time thing that we just used to get our initial changelog.

**Comment by jasongrout** [comment]
Looks good to me!

**Pull request merged**
