### PR TITLE
Small issues on tests

### PR DESCRIPTION
**Pull request by hbcarlos**
## Code changes
Add `jlpm run build:test` command to the main `package.json`
Remove test commands from debugger-extension
Solve an issue in shared-model tests

## User-facing changes
N/A

## Backwards-incompatible changes
N/A

cc @jtpio

### CODE REVIEW

**Review by fcollonval — APPROVED** [review]
LGTM thanks @hbcarlos 

> CI failure is not related

**Comment by fcollonval** [comment]
@hbcarlos does this need to be backported to 3.2.x?

**Comment by hbcarlos** [comment]
It is not necessary, but we can backport it.

**Comment by fcollonval** [comment]
Thanks I prefer not to if it is not needed.

**Comment by jtpio** [comment]
Thanks Carlos for the cleanup :+1:

**Pull request merged**
