### PR TITLE
MNT: Allow web app to update lab.html via configData.

### PR DESCRIPTION
**Pull request by danielballan**
In order to place JupyterHub links within JupyterLab, I need a way to place configuration from the `NotebookApp` (or, to be more exact, the `SingleUserNotebookApp`) which is the only component that knows the `hub_prefix` and `hub_host`, into lab.html.

After digging through the configuration-related code for awhile, I can't see a way to do that. This PR is one possible way forward which I think follow the current idioms. Unlike my [previous attempt](https://github.com/jupyterlab/jupyterlab/pull/1071), it does not put any hub-specific code in the JupyterLab.

### CODE REVIEW

**Comment by blink1073** [comment]
I think we should do this by reserving a key in the webapp settings that the application writes directly.

**Comment by danielballan** [comment]
How directly? Does the key hold raw HTML?

**Comment by blink1073** [comment]
Wow, that's pretty direct.  I was thing just a dictionary.

**Comment by danielballan** [comment]
A dictionary sounds direct enough to me too. (I wasn't sure if you had in mind a need for even *more* flexibility, but a dict is more general across different front-ends.) I'll push a reimplementation.

**Comment by blink1073** [comment]
Page content should still be in a regular plugin.

**Comment by danielballan** [comment]
For naming... `webapp.public_settings`? `published_settings`?

**Comment by blink1073** [comment]
page_config_data?

**Comment by danielballan** [comment]
That sounds right to me. This is much simpler. I force-pushed the new implementation.

**Pull request merged**
