### PR TITLE
Add a dependency graph generator to buildutils.

### PR DESCRIPTION
**Pull request by jasongrout**
Using something like 

```
node ./buildutils/lib/dependency-graph.js --no-phosphor —no-jupyterlab— no-devDependencies --lerna --lerna-exclude '^@jupyterlab/(test|buildutils)' --graph-options "ratio=0.3; concentrate=true;" > deps.graph
```
then
```
dot -Tpdf -O deps.graph 
```
we can get a pretty nice dependency graph for the jupyterlab packages, which aids in understanding how dependencies come into JupyterLab and how they are related to each other.

[deps.graph.pdf](https://github.com/jupyterlab/jupyterlab/files/2462477/deps.graph.pdf)

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Should any of this make its way into https://github.com/jupyterlab/jupyterlab/blob/master/docs/scripts/graph-dependencies.js?

**Comment by jasongrout** [comment]
Thanks. I missed that script. It's a *bit* different (this one relies on the yarn.lock for the information), but I think the functionality from the two could probably be merged.

**Comment by ian-r-rose** [comment]
Yeah, they serve different purposes. The one I linked to is intended to visualize the dependency graph of the core `@jupyterlab` packages (less the extensions for primarily visual clutter reasons). But it's possible that a large amount of it could be consolidated.

**Comment by jasongrout** [comment]
Yep. I tried to build this dependency graph generator general enough that it may be possible to generate a graph substantially like that one with the options in this one.

**Comment by jasongrout** [comment]
That generates the graph at https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#plugins ?

It isn't recursive, so it is a little different. I could probably add a few more options to my program to cover the usecase, but perhaps as another PR?

**Comment by ian-r-rose** [comment]
That's right.

I think it would be fine to leave it for another PR.

**Pull request merged**
