### PR TITLE
Fix the lines placeholder taking up too much space

### PR DESCRIPTION
**Pull request by krassowski**
## References

Fixes issue in https://github.com/jupyterlab/jupyterlab/issues/16364#issuecomment-2171826119

## Code changes

- [x] Adds a regression test
- [x] Fixes the issue by replacing `max-width: 0` on `.jp-GhostText-lineSpacer` with `text-wrap: none` to ensure the right number of lines is shown.

Longer explanation of the fix:

Previously `max-width: 0` was used to prevent the placeholder from expanding in width (and thus showing a spurious scrollbar when cell is narrow enough). However, it also meant that sometimes more lines were rendered because the width restriction was causing new line breaks to be added.

> This was a problem due to the necessity of using `display: inline-block` to animate font size reduction effectively.

Now, instead of using `max-width: 0` we use `text-wrap: none` which:
- prevents the horizontal scrollbar from showing when not needed and shows it when needed
- populates the vertical space to preserve the height

## User-facing changes

When user types a character that cancels the suggestion (e.g. `x` on gif below) the editor height now remains the same; as before, if they then press backspace the previous suggestion re-appears (as demonstrated on the gif).

| Before | After |
|--|--|
| before| after |

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
A few less important edge case:
- pasting multiple lines extends the height but if it the pasted height is less than the spacer we could just reduce the spacer height to limit jitter
- similarly tping a letter extends the scrollbar even if `text-wrap: none` is used

**Comment by krassowski** [comment]
There are more things that can be improved, but I am marking this as ready for review because I think this PR as of now addresses the most severe issue and can be easily backported; I will open additional PRs with more improvements.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.2.x

**Pull request merged**
