### PR TITLE
Render an empty widget if we don’t have a renderer for the mimebundle types.

### LINKED ISSUE #6216: "No renderer could be found for output" message in outputs
**Describe the bug**
When using the [scrapbook package](https://github.com/nteract/scrapbook), the `glue` function anywhere in a cell produces a confusing message:

```
No renderer could be found for output. It has the following MIME types: application/scrapbook.scrap.json+json
```

No outputs are expected for the `glue` function alone.

**To Reproduce**

```python
# !pip install nteract-scrapbook
import scrapbook as sb
sb.glue("hello", "world")
```
or

```python
# in the same cell:
x = "world"
sb.glue("hello", x)
x
```
You would expect "world" in output, but not the message. The message is prepended however:

**Screenshots**

jupyter-lab-no-render-message

**Expected behavior**
No output  or warning message

### PR DESCRIPTION
**Pull request by jasongrout**
## References

Fixes #6216

## Code changes

This does render a blank non-classed div for outputs corresponding to things we can’t render, since we need the list of widgets to correspond to the output messages. So it's not exactly like the classic notebook (which doesn't render anything for things it doesn't understand), but from a user perspective perhaps this is good enough.

I suppose another way to do this is instead of all of the special-casing with adding class names, just hide the widget, which should do a display:none. However, we should check to make sure that the widget children iteration counts hidden widgets.

## User-facing changes

There no longer is an error if we try to display a display_data message that has no recognizable mimetypes.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Looks good to me, thanks @jasongrout!

**Comment by vidartf** [comment]
Can we at least have a console log/warning? It seems bad to fail to render a cell output, with no hints to the user about what can have gone wrong.

**Comment by ian-r-rose** [comment]
A warning to the console sounds reasonable to me.

**Comment by jasongrout** [comment]
Note that in this case (with papermill workflow), having an unrecognized mime type was supposed to happen, so it could generate quite a few errors with a console log/warning. I think generally things will have at least a text/plain mimetype.

**Comment by vidartf** [comment]
Sure, I just won't respond to any ipywidgets questions that are about why they are only getting the repr string ;)

**Comment by jasongrout** [comment]
Those cases aren't affected by this, because they do have a text representation, so the code is happy before and after this change just the same.

**Comment by jasongrout** [comment]
(this codepath is only exercised if there is *no* mimetype understood - that should be extremely rare in most cases. Except when using papermill, apparently.)

**Comment by vidartf** [comment]
@jasongrout Or if the mimetype is unsafe.

**Comment by jasongrout** [comment]
> @jasongrout Or if the mimetype is unsafe.

Right, no mimetype understood includes the current safety level allowed. But again, the vast majority of mimebundles should have a text/plain representation (I thought *all* would), so this codepath isn't exercised hardly ever.

**Pull request merged**
