### PR TITLE
Resize isolated iframes on content height change

### LINKED ISSUE #5696: Height of isolated mimebundle output
When I display a mime bundle containing an entry of e.g. `text/html` with the metadata “isolated: true”, I get an iframe without height attribute/style, which results in a slim 150px high window.

Jupyterlab should infer the height for the iframe on `DOMContentReady` and once again at `load`.

### PR DESCRIPTION
**Pull request by flying-sheep**
Maybe fixes #5696. I’ll have to test if this works as intended. Maybe we could also detach the observer after 10s or so.

I don’t think debouncing is necessary since changes are going to be abrupt in iframes (as opposed to mouse dragging your window corner)

### CODE REVIEW

**Comment by jasongrout** [comment]
> I’ll have to test if this works as intended.

Just following up on this. Thoughts about whether this is a good solution and fixes the issue? Does it have other ramifications (primarily performance ones, I would think) that we should be aware of?

**Comment by flying-sheep** [comment]
I can’t seem to get a working dev environment.

I tried `python -m jupyterlab build` in my branch, but searching for my code in the build dir doesn’t yield any results: `rg heightChangeObserver .jupyter/lab/`

The following code should show if it works:

```py
from IPython.display import display, HTML
display(HTML("""
<script>
setTimeout(() => {
    document.querySelector('#test').style.height = '500px'
}, 1000)
</script>
<div id="test" style="background-color: red; height: 100px"></div>
"""), metadata=dict(isolated=True))
```

**Comment by blois** [comment]
I've not been able to get MutationObserver notifications for calculated properties such as scrollHeight- does this work for you?

For example, I would expect a log statement from:

```python
from IPython.display import display, HTML
display(HTML("""
<div></div>
<script>
const mo = new MutationObserver(() => {
    console.log(document.body.scrollHeight + 'px');
});
mo.observe(document.body, {
          attributes: true,
          attributeFilter: ['scrollHeight']
        });
setTimeout(() => {
    document.querySelector('#test').style.height = '500px'
}, 1000)
</script>
<div id="test" style="background-color: red; height: 100px"></div>
"""), metadata=dict(isolated=True))
```

I'm really curious though what 'isolated' is expected to do here- the iframe doesn't appear to have much isolation aside from separate globals- scripts can still traverse the boundary.

**Comment by flying-sheep** [comment]
ah! maybe we have to observe all subtree modifications??

**Comment by blois** [comment]
Your best bet will be to use a ResizeObserver if it is available on the platform:

```javascript
if ('ResizeObserver' in window) {
  const observer = new ResizeObserver(() => {
    console.log(document.body.scrollHeight + 'px');
  });
  observer.observe(document.body);
}
```

I'm still quite curious why you're using 'isolated'- as far as I know this is exceedingly uncommon and I worry that the current implementation may be misleading as to just how isolated it is (not very).

In particular the iframe is not sandboxed and the above code will not work for a sandboxed iframe.

**Comment by flying-sheep** [comment]
Yay, I just found a way: http://shorts.jeffkreeftmeijer.com/2014/resize_an_iframe_based_on_its_contents/

The `ResizeObserver` is exciting to know about, but we actually have a `resize` event being fired. A `ResizeObserver` is apparently for watching elements while we can watch the document.

**Comment by blois** [comment]
Since there really isn't isolation going on with this iframe you could do all of the resizing from user code running within the iframe. PostMessage also isn't required at all since there is no sandbox boundary. I'm still curious why isolation is desired.

Disclaimer- I work on Google Colaboratory where we sandbox all outputs by default and I have spent (too much) time on this specific problem.

Overall, ResizeObserver is the most reliable and performant solution to this problem, but it has very limited browser support right now.

If ResizeObserver is not available we use:

- MutationObserver using observe(document.body, {childList: true, subtree: true}).
- window.addEventListener('resize'), specifically to catch horizontal window resizes.
- document.documentElement.addEventListener('load') to catch image and CSS load events.

Then debounce them all with a 150ms timer.

This still won't catch size changes triggered by CSS transitions, ResizeObserver will.

**Comment by flying-sheep** [comment]
Thank you, that’s very helpful. I think horizontal resizes are not interesting here, since we’re just interested in vertically resizing the iframe, but the rest should be done.

**Comment by blois** [comment]
Horizontal resizes are used because it modifies text wrapping height.

**Comment by flying-sheep** [comment]
Well, my current fix uses a polyfill for a ResizeObserver, which is probably better than reinventing the wheel.

**Comment by blink1073** [comment]
Closing as stale, please feel free to rebase and reopen if you'd like to continue

**Comment by flying-sheep** [comment]
It’s not very nice to ignore a PR and then close it because you ignored it. But yeah, OK.

**Comment by afshin** [comment]
@flying-sheep
> ... please feel free to rebase and reopen if you'd like to continue

**Pull request closed without merging**
