### PR TITLE
Incrementally improve JupyterLab mobile UX

### PR DESCRIPTION
**Pull request by afshin**
This pull request opens some introductory work into supporting a better mobile experience in JupyterLab. It is an incremental step toward a more coherent mobile experience.

## References
#3275 

## Code changes
- Mobile device detection is based on matching this `@media` query: `only screen and (max-width: 760px)`
- Adds attribute `JupyterFrontEnd#format`, and signal `JupyterFrontEnd#formatChanged`
- Adds a new `@typeparam` to `JupyterFrontEnd` to allow a sub-class to define the `format` types an application supports. A sub-class can add or modify the application `format` options:
  multiple-format

## User-facing changes
If the media query matches a mobile browser after a resize or on page load, JupyterLab loads the `mobile` format, i.e., it switches the `DockPanel` to `single-document` mode and sets the status bar to hidden.

Desktop to mobile transition:
desktop-mobile-transition

Rendering in mobile Safari:
mobile-safari

## Backwards-incompatible changes
N/A

cc: @ajbozarth @jtpio @telamonian @tgeorgeux

### CODE REVIEW

**Comment by afshin** [comment]
Mobile device detection is based on matching this `@media` query: `only screen and (max-width: 760px)`:
media-query

**Comment by jtpio** [comment]
Really neat, thanks @afshin!

Maybe we'll also be able to use the tiny scrollbars from https://github.com/jupyterlab/jupyterlab/pull/8417 to make the main menu scrollable (in the next iteration).

**Comment by afshin** [comment]
Which is better: `JupyterFrontend.Format` or `JupyterFrontend.Medium` (similarly, `.medium` and `.mediumChanged`, etc.)?

**Comment by vidartf** [comment]
Nice! 👍  In a future PR, we would probably want to make the format be overridable by the user ("desktop"/"mobile"/"auto" ?). As long as we ensure the API at this point can accommodate that in a non-breaking way I'm happy for this to be the starting point!

**Comment by vidartf** [comment]
> As long as we ensure the API at this point can accommodate that in a non-breaking way

PS: I think it does, but my brain is mush today, so I'm going to leave it as a question 🤓

**Comment by jasongrout** [comment]
Excellent work! I love the idea!

In looking at the above screenshots - we should have someplace in the UX that gives the tab title when in single-document mode. Perhaps in the status bar or something. It's confusing what file I'm editing in single-document mode.

**Comment by afshin** [comment]
Cheers @jasongrout!

I think the status bar takes up too much valuable real estate so in this PR it actually hides itself when the format changes to mobile. I think it is good to show the user the file being modified. I'm not sure where yet, though. I would propose not solving that user experience issue in this PR, because the concepts in this PR should unblock others who want to improve the mobile experience. What do you think? Is it critical to solve that problem here?

**Comment by jasongrout** [comment]
> What do you think? Is it critical to solve that problem here?

Nope, not critical at all for this PR. Thanks again for your excellent work here.

**Comment by blink1073** [comment]
We can track single document mode improvements in #8292, which I just renamed

**Comment by saulshanabrook** [comment]
I targeted this as 3.0.0 b/c it seems to change the typevars for `JupyterFrontEnd`... I didn't look that closely though, if you feel like this is backwards compatible and should be targeted for 2.2.0, please change the milestone!

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/seeking-feedback-jupyterlab-single-document-mode-switch-position/6715/19

**Pull request merged**
