### PR TITLE
Remove some unused CSS styles and fix icon alignment in plugin list

### LINKED ISSUE #13001: Misaligned icons in settings editor UI
## Description

The fix was implemented in #11976, one of which was:

https://github.com/trungleduc/jupyterlab/blob/bae8ff2c14e821112f39f66c155814289211305f/packages/settingeditor/style/base.css#L146-L149

but then the `button`s were changed to `div`s in https://github.com/jupyterlab/jupyterlab/pull/12082/commits/6b37ab404952e81c896d02076e56544fc612aa11 (as buttons cannot hold child elements according to HTML spec) and the CSS is not effective anymore.

We really need visual regression tests here.

## Reproduce

Screenshot from 2022-08-24 22-25-29

## Expected behavior

Aligned

## Context

- Operating System and version: Linux Ubuntu
- Browser and version: Firefox, Chromium (to a lesser degree)
- JupyterLab version: 3.4.5

### PR DESCRIPTION
**Pull request by krassowski**
## References

Fixes #13001 (misaligned icons)

Removes unused styles:
- `.jp-DirListing-deadSpace` unused since https://github.com/jupyterlab/jupyterlab/commit/10537f4c8c69c0c9edf7cc94cb5f5c737e750822
- `.jp-openJSONSettingsEditor` unused since https://github.com/jupyterlab/jupyterlab/commit/94cc691d9eda5d9bae5c2abd6eb53d2c7cd53f87
- `.jp-OutputArea-stdin` unused since https://github.com/jupyterlab/jupyterlab/commit/c7b8f418cdcb9c245513b84e8cd864701f40db8a
- `.jp-PluginList .jp-SettingsHeader` unused since https://github.com/jupyterlab/jupyterlab/commit/6dc35dac7779da22f99a295016fa97484a208550
- `.jp-PluginList-Searcher` unused since https://github.com/jupyterlab/jupyterlab/commit/3f65d5519892f600032ab4c0d7a6176481b65496
- `.jp-RedirectForm` unused since https://github.com/jupyterlab/jupyterlab/commit/555d84b4175840f675cdfe0d99ea1c56ba39ed21
- `.lm-TabBar-WindowTabLabel` unused since (? it was added in 2016)

Removed rules to without traceable use:
- `.jp-Notebook-render *`
- `.jp-mimeType-highlight`

## Code changes

Fixes lettercase in `jp-pluginList-entry-label` class name (to `jp-PluginList-entry-label`).

## User-facing changes

| Before | After |
|------|--------|
| Screenshot from 2022-10-17 00-13-20 | Screenshot from 2022-10-17 00-12-57 |

## Backwards-incompatible changes

Class name with lettercase error could be retained on backport or not.

### CODE REVIEW

**Comment by krassowski** [comment]
UI Tests / Visual Regression Documentation test failure is unrelated, see https://github.com/jupyterlab/jupyterlab/issues/13243.

**Review by fcollonval — APPROVED** [review]
Thanks @krassowski 

Do you want to add the cases for 

- .jp-Notebook-render *
- .jp-mimeType-highlight

in this PR or in a follow-up?

**Comment by krassowski** [comment]
I added them in this PR now.

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.6.x

**Pull request merged**
