### PR TITLE
Fix default toolbar items

### PR DESCRIPTION
**Pull request by blink1073**
Supersedes #5395.

### CODE REVIEW

**Comment by jasongrout** [comment]
What about calling the toolbar-item function "toolbarItemFactory", to be consistent with the other "Factory" uses in the code? Or even just "toolbarFactory"?

**Comment by jasongrout** [comment]
Looking at this now...

**Comment by jasongrout** [comment]
I went a bit further after conversations about some ideas @blink1073 had about extending toolbars to rendermime extensions. You can test adding something to a toolbar with, for example:

```patch
diff --git a/packages/json-extension/src/index.tsx b/packages/json-extension/src/index.tsx
index d1b4c2f0d..096e1dcc2 100644
--- a/packages/json-extension/src/index.tsx
+++ b/packages/json-extension/src/index.tsx
@@ -75,7 +75,12 @@ const extensions: IRenderMime.IExtension | IRenderMime.IExtension[] = [
       name: 'JSON',
       primaryFileType: 'json',
       fileTypes: ['json', 'notebook'],
-      defaultFor: ['json']
+      defaultFor: ['json'],
+      toolbarFactory: () => {
+        let button = new Widget();
+        button.node.textContent = 'Hi!';
+        return [{ name: 'Button 1', widget: button }];
+      }
     }
   }
 ];
```

**Comment by blink1073** [comment]
LGTM!

**Pull request merged**
