### PR TITLE
Improve scrolling to heading

### LINKED ISSUE #14591: Table of Contents: selecting heading only scrolls to position the first time
## Description

When you select a heading in the table of contents, it automatically starts editing the cell. This is not preferred behavior for me, but I can live with it. More problematic, however, is that once the cell is in edit mode, clicking the header again in the ToC will not scroll to the cell. This happens even if you have currently selected/are editing another code or markdown cell, and can be true for multiple headers at the same time. Effectively, you could have an entire table of contents and none of the headers work!

## Reproduce

In the example notebook below: scroll up so that the heading h1 is offscreen. Click h1 in the table of contents, you get scrolled down to it and the cell enters edit mode. Scroll up and optionally select one of the filler cells; clicking the heading again in the table of contents does nothing. Only fixed when the markdown cell is run again.

## Expected behavior

When you click a heading cell in the table of contents, you should always be scrolled to it. In my opinion, it also shouldn't automatically start editing markdown cells, but that's of a secondary concern.

## Context

example notebook contents:
```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "1733768e-510c-4fef-b5b9-b086fd969d44",
   "metadata": {},
   "outputs": [],
   "source": [
    "filler = 4"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9d81f6ec-cbd8-49e7-908f-f315b26de2d3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "262057a5-f605-4e23-bf26-f0035189fd8c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "2f2d07fc-3bb6-4464-8dda-453d74d5766c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "f37c6c3a-204c-4b92-87d2-db1b28810597",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "cfe35aec-32c0-4d84-82c9-5324a66eab13",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f81f92a1-da97-430a-b785-d85024a600d5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "5c0f0966-852c-4c36-ab8e-fe37262c6826",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "b79cc1dd-a477-4049-8167-3ecd257377b7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "4eb14bda-aa6a-4e9a-83a7-c4829abba2fb",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "f996f5ec-5786-4225-bfc7-69f0a2f18c87",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "f07f2ffe-d486-47c0-a63c-5ec454ed9054",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "ab6f22c7-573b-4dd8-a15e-c188433e09f5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "2dc45e1b-c960-47cc-9c14-fe4b950e0810",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cc9db4bb-e736-410e-835b-bef8a971b4b5",
   "metadata": {},
   "source": [
    "## h1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "da7b7248-b994-410c-9b3a-ff3c7591a3be",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### LINKED ISSUE #14684: Scroll header cell into top of view upon TOC click
The old onClick behaviour of header items in the TOC extension was to scroll the header element into the top of the view. In the recent 4.0 release (amazing update by the way), where the TOC extension has been redone, it now scrolls the element into the center of the viewport. Personally I find having the element in the middle to be an odd UX, though I do suppose there may be others who perfer the new behaviour.

I believe the only required code change would be to set on `block: 'center'` at [`packages/notebook/src/toc.ts`](https://github.com/jupyterlab/jupyterlab/blob/f699d32d19e1687bf27e4c83318f50062adb0c5a/packages/notebook/src/toc.ts#L531) to `block: 'start'`. The best of both worlds would be for this to be configurable though.

### LINKED ISSUE #15215: Clicking on header in ToC leads to off-screen content
## Description

image

## Reproduce

1. Enable  windowing mode = full
2. Create a long notebook with some headings in markdown cells
3. Press on a heading in ToC
4. Main area to be incorrectly positioned leading to JupyterLab being unusable

## Context

- JupyterLab version: 4.0.6

No relevant logs.

### LINKED ISSUE #15228: Table of contents should not enter the edit mode of markdown cells
At least <s>three</s> four users reported that they strongly prefer the previous behaviour of table of contents navigation. In 3.x clicking on heading in ToC would scroll to the appropriate position. In 4.x it scrolls (when it works) and then enters the edit mode (unrenders the markdown cell).

> I am on  4.0.6.
> The current behavior of [ click on TOC -> scroll then start edit] is a change from previous behavior;
> the current behavior degrades the navigation experience for me, for no gain.
> I have many code cells inbetween heading cells. So my main intention when clicking a heading is to scroll to the start of such a section.  Almost never do I want to edit the cell I click on the TOC.
> It's worse when I don't notice that the cell I scrolled to was edited (again, because the behavior was changed), and keep going through my normal usage only for then having to find the cell that was left in edit mode and put it back into display mode so that proper navigation is restored.
> _Originally posted by @LunarLanding in https://github.com/jupyterlab/jupyterlab/issues/14591#issuecomment-1740461474_
            

> This would also solve the problem that appears some times when the hyperlinks of the TOC don't work and makes the navigation through the notebook cumbersome (I guess that is why the "Run all markdown cells" option exist)
> _Originally posted by @rodrigo-j-goncalves in https://github.com/jupyterlab/jupyterlab/issues/15165#issue-1915060209_

> When you select a heading in the table of contents, it automatically starts editing the cell. This is not preferred behavior for me, but I can live with it.
> _Originally posted by @minerharry in https://github.com/jupyterlab/jupyterlab/issues/14591#issue-1724821913_

Fourth user is the author of this issue :)

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #15228
Fixes #15215 (@krassowski - would you mind confirm this I'm unsure)
Fixes #14684
Fixes #14591

## Code changes

- Emit `onActiveHeadingChanged` in toc model even when the value is not changing
- Add a new attribute `scrollToTop` to the notebook ToC factory that is true by default but allows to configure the heading navigation scroll behavior
- Switch to command mode when in edit mode and jumping to a heading in a md cell

## User-facing changes

By default, jumping to a heading from the toc will not make the markdown cell turn in edit mode and will scroll it to the top of the view port.

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
I guess this could be backported to 4.0.x but without the new setting?

**Comment by fcollonval** [comment]
> I guess this could be backported to 4.0.x but without the new setting? 

I was thinking of backported it with the setting but changing the default value as lots of user consider scroll to top a better behavior.

**Review by krassowski — CHANGES_REQUESTED** [review]
Not sure if this fixes https://github.com/jupyterlab/jupyterlab/issues/15215 because that is not trivial to reproduce, but I did find a way to break this PR:

broke

**Comment by krassowski** [comment]
Sorry accidentally clicked submit too early, here is the traceback:

```ts
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at NotebookWindowedLayout.detachWidget (http://127.0.0.1:8889/static/lab/packages_notebook_lib_index_js.a0899e5b2c84c0887c94.js:9919:38)
    at NotebookWindowedLayout.removeWidget (http://127.0.0.1:8889/static/lab/packages_notebook_lib_index_js.a0899e5b2c84c0887c94.js:9806:18)
    at NotebookWindowedLayout.onChildRemoved (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:13723:14)
    at NotebookWindowedLayout.onChildRemoved (http://127.0.0.1:8889/static/lab/packages_notebook_lib_index_js.a0899e5b2c84c0887c94.js:9997:15)
    at NotebookWindowedLayout.processParentMessage (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:13522:22)
    at Notebook.notifyLayout (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:12938:26)
    at Notebook.processMessage (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:12918:22)
    at invokeHandler (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:9381:21)
    at Object.sendMessage (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:9135:13)
    at set parent [as parent] (http://127.0.0.1:8889/static/lab/jlab_core.ac50a29a806e5e41bc1f.js:12581:72)
exceptionHandler @ index.es6.js:377
```

followed by:

```ts
windowedlist.ts:1126 Uncaught Error: Inconsistent dataset index
    at Notebook._update (windowedlist.ts:1126:15)
    at windowedlist.ts:1005:16
```

**Comment by krassowski** [comment]
The error above is unrelated (it also happens in 4.0.8 and 4.1.0a3), I tracked it down to "Revert" breaking windowed notebooks, here is the issue: https://github.com/jupyterlab/jupyterlab/issues/15415.

**Comment by krassowski** [comment]
The failing test appears to reflect change in the behaviour and likely needs to be updated (or change in test settings):

| Expected | Actual |
|--|--|
| Screenshot from 2023-11-24 14-01-38 | Screenshot from 2023-11-24 14-01-35 |

**Comment by fcollonval** [comment]
bot please update the galata snapshots

**Review by krassowski — APPROVED** [review]
Thank you @fcollonval!

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.0.x

**Pull request merged**
