### PR TITLE
Fix: Toolbar doesn't update on paste.

### PR DESCRIPTION
**Pull request by brijsiyag**
In order to address delays in DOM layout updates, a `requestAnimationFrame` function is used for the code inside `_updateCellForToolbarOverlap`.
Fixes: #14569

### CODE REVIEW

**Comment by krassowski** [comment]
Thank you for working on this! There are some linting failures - the promises which were introduced by converting the `_updateCellForToolbarOverlap` to async would need to be handled:

Screenshot from 2023-05-27 11-46-17

An alternative would be to keep it sync and add `setTimeout` with callback inline.

Would `requestAnimationFrame` work here?

**Comment by brijsiyag** [comment]
Ooh, Thanks, I had no idea of requestAnimationFrame. It works pretty well.
I will update the code.

**Comment by brijsiyag** [comment]
@krassowski some tests are failing yet but I don't think these are related to my changes. PTAL !

**Comment by krassowski** [comment]
There is one visual regression test which actually gets fixed by this PR so relevant in a good sense:

bot please update galata snapshots

**Comment by krassowski** [comment]
I will close and reopen this PR to trigger CI jobs as those got stuck on bot update.

**Review by krassowski — APPROVED** [review]
Thank you @brijsiyag!

**Pull request merged**
