### PR TITLE
Make Consoles File-Backed

### PR DESCRIPTION
**Pull request by drorspei**
Hi there!
I've made consoles save a file with their cells' contents, addressing issue #260. It works like this:
1. A file is created when a console is created.
2. Before and after every execution, from console or attached notebook, the file is resaved.
3. If the panel/browser is closed, and you click on the console in the `Running` panel, the console widget reloads the saved file and restores the cells.

The cells are stored with their `toJSON` method, so this works with plots and other things cells can contain. I don't know if this works with widgets, though I'm guessing it doesn't, since I couldn't run `ipywidgets` in dev-mode. I tried `addsibling`, but kept getting npm errors...

There is also a new `Export to Notebook` option in the `Console` menu, which opens a file dialog to save the console as a (by default) `.ipynb` file. Once saved, you can open it from the `Files` panel, and it will be a normal notebook.

Things to discuss:
1. Using the checkpoint system: I didn't use the checkpoint system because personally I don't want a checkpoint, i.e. new file, after every execution (or after every so and so time). Since consoles are chronological, there's no point in saving more than one file. But, this causes the following problem: I don't know how to save to the `.ipynb_checkpoints` folder - the api returns error code 403. So the console documents are currently simply stored in the same path where they are running. Should this be changed?
One point in favor of not saving console documents in the `.ipynb_checkpoinds` folder is that even after the console is shutdown, the user can simply tack on the `.ipynb` file extension and open the file as a notebook. If the files are in the hidden folder, less users will understand this.

2. File default name and extension: I've naively put the uuid of the console into the file name without any extension. For example: `console-1-819a0f7c9ffdd73ecbf4cb74c0e58943`. I have no preference for what should be done. What do you think?

3. Times of save: I implemented a save after every cell update, so after both input and output (of console or attached notebook). This can be changed to once in every specified interval of time. What do you think?

I think that's it :)

PS: I would be grateful to anyone who can give me explicit instructions on how to clone, build, and run jupyter lab in dev-mode with ipywidgets. I'm running Ubuntu 15.10 with python 2.7.10, npm 3.10.10 and node 6.11.4.

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks for this, @drorspei!  We are in the process of releasing 0.28. I will come back and take a closer look after that.  AFAIK no one has tried running ipywidgets in `--dev-mode`.  Theoretically using [addsibling](https://github.com/jupyterlab/jupyterlab/blob/master/docs/extensions_dev.md) with https://github.com/jupyter-widgets/ipywidgets/tree/master/packages/jupyterlab-manager should work.

**Comment by blink1073** [comment]
It would be great if you can attend the JupyterLab developer's tomorrow to discuss this in person!  It is 1200 Eastern time at bluejeans.com/u/jupyter/.

**Comment by drorspei** [comment]
Cool cool. 
Sounds fun, I'll attend tomorrow.

**Comment by blink1073** [comment]
Summary of talk today:

- We can use the checkpoint system to save the state periodically, and use it when the console is launched from the "running" tab and is not open.
- ipywidgets does not yet export widget information in lab, so there is nothing to test there yet.
- We could potentially have an option to save to a public `.jpconsole` or `.ipynb` file periodically, but probably not yet in this PR.
- When saving to a notebook, we can ask the server for a notebook name by creating a new notebook file using the contents API.

**Comment by drorspei** [comment]
Ok!

I played a bit with the checkpoint methods to see what they do, and it goes like this:
- First there has to be a file outside the checkpoints folder,
- Then you can ask contents manager to save a checkpoint,
- If you delete the original file, the checkpoint is also removed.

So if we use the checkpoint system, there would have to be a file in the working directory which will always be identical to the hidden checkpoint file. What if instead the working directory file's name started with a ".", but no checkpoint?

I've also implemented the last bullet: when clicking Export we get a new notebook file from the api, push the console contents into the file, then open it.

**Comment by blink1073** [comment]
Hmm, if we have a local hidden file then we don't know when it is safe to remove it, and it would be easy to build up a lot of them (and not even notice because they don't show up in the UI nor by default in a terminal).

**Comment by drorspei** [comment]
Oh yeah, good point. 
How about we delete console documents once the console shuts down?

* I had some trouble with git, so I reset and pushed a single commit with the changes.

**Comment by blink1073** [comment]
We wouldn't be able to catch ones that are shut down when the client is closed.  I think making them public and making it an option whether to save them should cover our bases.

**Comment by drorspei** [comment]
So the user will enter her choice of having consoles backed by files or not. Sounds cool.
What should be the user interface for this?

**Comment by blink1073** [comment]
We can start by making available to the settings editor by providing a schema.

[Example schema](https://github.com/jupyterlab/jupyterlab/blob/01c9a6fd173925ed7b2cd99be7a8e3a4ea0d67c3/packages/fileeditor-extension/schema/plugin.json)
[Example usage](https://github.com/jupyterlab/jupyterlab/blob/01c9a6fd173925ed7b2cd99be7a8e3a4ea0d67c3/packages/fileeditor-extension/src/index.ts#L147)
[Docs](https://github.com/jupyterlab/jupyterlab/blob/01c9a6fd173925ed7b2cd99be7a8e3a4ea0d67c3/docs/extensions_dev.md#extension-settings)

**Comment by drorspei** [comment]
I added a schema for consoles with file-backing as the only option, set to false by default in order to keep the current default functionality.

**Comment by blink1073** [comment]
Nice!  I'll take a closer look tomorrow.


Sent from phone

________________________________

**Comment by blink1073** [comment]
This is excellent!

If we use a file extension (`.jpconsole`), then we can use the document registry to handle the files.  Documents opened this way have their own save handling: https://github.com/jupyterlab/jupyterlab/blob/master/packages/docmanager/src/savehandler.ts
That would also mean we could open the console from the file browser (and it would have the console icon).

An example is the CSV viewer: https://github.com/jupyterlab/jupyterlab/blob/master/packages/csvviewer-extension/src/index.ts#L44

**Comment by ellisonbg** [comment]
From a technical perspective, this approach looks good. But I am not sure that from a UX perspective it makes sense for all consoles to be file backed. The entire purpose of the console is for transitory, temporary, transient exploration. From this perspective, it is a feature, and the most important one of the console, that it doesn't save something to the file system. 

I am not opposed to us having files associated with consoles, but I think we need to think carefully about the UX first. Some options to explore:

* Don't create the files always?
* Offer export to file options?
* Think more carefully about what a `.jpconsole` file is for. A notebook file is nice because you can edit it. Would this be possible for a `.jpconsole` file? How would you edit it? As a notebook? Maybe we don't need a separate file format (just use ipynb?).
* Would enabling the console to *run* a notebook file help in these usage cases?

**Comment by drorspei** [comment]
Hi!

* Sorry I haven't finished this, my computer broke down and I was moving... Anyway, I got my shiny new Lenovo 920 today, and I'm back on this.  It's not exactly the same as the usage in cvs-viewer because it's possible to create new files, so I looked now at how notebook does it and I think I got it.

Now, here is why I am for file backing:

First of all, I keep accidentally closing the browser or tab. Having Jupyter in a browser means this happens to me a lot, and I'm sure I'm not the one with this problem. Then when I reopen - the console is empty. This just isn't right. If the console is still running, it makes UX sense to see what I've run up to now.

Given that, I now come to a main difference between @ellisonbg and me: what is the main feature of consoles. @ellisonbg claims the feature is derived from the console's virtue, that of being transient.  While I agree that consoles are for transient exploration, I do not agree with the deduction. Furthermore, I propose a different feature as the main one: the ability to use history between sessions. In fact, this possibility is the only reason I am using JupyterLab and not IPython/forks of idle/something else, and the lack of this possibility is the number one reason that I, everyone else in my company, and several other people I know at Google, Facebook etc., do *not* use Jupyter.
Since JupyterLab added consoles, I am now able to explore as I would in other interpreters.

Now that I've explained why I use JupyterLab, and consoles in particular, the following two reasons for allowing file backing will make sense. I understand the perspective from which consoles' main feature is transiency, and I acknowledge that from this perspective the following two reasons don't make sense at all.

Second reason: future ability to work over Google-drive. When I travel for work, I want to work with a colleague at the company's office on the same kernel, and that we would both see each other's entries. The Google-drive extension allows this for notebooks, and we have started using it. It is superb. Trouble is, both me and my colleagues prefer consoles to notebooks, mostly for command history, but also for the linear flow.  Having the ability to file back a console will make it possible to share over google drive. Once I finish this pull request I am planning on working on this.

Third reason: ipywidgets. I'm not sure why they need file backing, but that's what I understood from an open issue about ipywidgets in consoles. If you accept my reasoning for working in consoles in the first place, it should make sense that I would want to have ipywidgets working in them.

Fourth reason: saving plots for later. It happens to me a lot that I explore some data, and plot some graphs that I then find interesting, and I want to show them to a coworker. If consoles are file backed, I can open the file even after the console shutdown, and show my coworker what I did and what the graphs look like. In fact, I've already done this to much success (on my work computer I have the latest version of this pull request installed). It's true that I could have used a notebook from the beginning, but even without my personal preferences mentioned above, it is common to explore in a console and find interesting stuff.

As for ellisionbg's four questions:
1. The current pull request has a configure option to save to files, though it is global and not per file.

2. I've added a menu item to export to notebook.

3. Having the same file type would be confusing when opening: if the console is running it should open the tab as a console, and if it's not running it would open as a notebook.  What do you think?

4. Letting consoles run notebooks would be cool!  But they don't address my own needs listed above.

I'm glad a discussion is forming on this, I hope I can contribute to it :)

**Comment by saulshanabrook** [comment]
> First of all, I keep accidentally closing the browser or tab. Having Jupyter in a browser means this happens to me a lot, and I'm sure I'm not the one with this problem. Then when I reopen - the console is empty. This just isn't right. If the console is still running, it makes UX sense to see what I've run up to now.


I wonder if we could just save the console state to the model of the console widget. Then it would persist across, reloads, right? Since it was in the browser cache? Is the worry there that they would be too big to save in the browser?

**Comment by ian-r-rose** [comment]
The console model is not persisted across browser loads. If we put it in `localStorage` I think it would use up the space very quickly (most browsers only allocate a few megabytes for each site).

**Comment by saulshanabrook** [comment]
That makes sense. 

Another option would be to only create a file when the user tries to save the console and throw up a name prompt with a default name pre-filled.

**Comment by ellisonbg** [comment]
@drorspei many thanks for clarifying your usage cases - it is super helpful. I will think a bit more and reply.

**Comment by ellisonbg** [comment]
@drorspei ok getting back to this after a long period of travel. 

From the user experience perspective, you have made a really good point about the difference  meanings of transient in this case. I completely agree with you that it is really frustrating to not have a console reload with its content in history when you reload JupyterLab. I think having it reload from a file at that point is completely consistent with its primary usage case of being a transient scratchpad for users. Based on this I think we should move forward with this approach.

 A few other comment:

- For now I think it is fine for the configuration option to be global and not per file
- The export to notebook menu item is fantastic
- I do agree that the file extension should be different from that of a notebook.
- I would love to see this feature released with the upcoming 1.0 version, likely in January.

@drorspei do you have time to rebase? If not, someone else can give that a go. Again, sorry about the delay.

**Comment by drorspei** [comment]
Hi!

I was also away for a long time so no worries :)
Yeah I have some time these days and I would like to work on getting this ready for the release. 
I've cleared my weekend ^_^

**Comment by drorspei** [comment]
Hi hi
I've rebased over master (though it's already in conflict again!) and I'm getting some test failures. I'm not sure what they mean, can someone give me feedback on what to try?

**Comment by aschlaep** [comment]
After conversations with @jasongrout, we'll take this off of 1.0 for now, since this is looking like it may not be done in time.  Definitely appreciate the long-running work though!

**Comment by vidartf** [comment]
What is the remaining work in this PR? @aschlaep You mentioned that it might not be done in time for 1.0, but it isn't marked as WIP, and I see no review points that have not been answered?

**Comment by blink1073** [comment]
Closing as stale

**Pull request closed without merging**
