### PR TITLE
Monaco Integration

### PR DESCRIPTION
**Pull request by akosyakov**
Hey, it is our branch with Monaco integration.

Known issues:
1. webpack - monaco has its own loader and it does not play nicely with webpack, so we have to load it before JLab: https://github.com/Microsoft/monaco-editor/issues/18
2. overflow - monaco has so called content widgets: a suggest widget, a hover, a context menu, a command panel and so on. They are attached to an editor with the assumption that default overflow policy, i.e. visible, is used, so content widgets can escape the editor. JLab uses hidden as default and it leads to truncating content widgets. For our product we changed some JLabs styles to overcome the issues but it did not fix all glitches.
3. the suggest widget - for our product we disabled the JLab completer and registered a kernel based completion provider for Monaco
4. instance tracking and focus - we had to wrap an editor refresh in `setTimeout` block, otherwise Monaco sometimes calls focus before a new console is added to the tracker and it breaks synchronization -> https://github.com/jupyterlab/jupyterlab/issues/1384

### CODE REVIEW

**Comment by blink1073** [comment]
This is great!  I am confident we can overcome all of these issues.  Overcoming the loading issue is a good test of making our extension handling more robust.   It looks like points 2 and 3 are not yet reflected in this PR, and #1385 fixed number 4.

**Comment by akosyakov** [comment]
One more issue is event handling conflicts between Monaco and JLab: https://github.com/Microsoft/monaco-editor/issues/173. Workaround from here can be used: https://github.com/phosphorjs/phosphor/issues/163

**Comment by akosyakov** [comment]
@blink1073 unfortunately i don't have time now to continue working on it right now. regarding particularly the second issue i don't feel comfortable changing JLab styles

**Comment by blink1073** [comment]
I meant I didn't quite understand the extent of the CSS problem because the workarounds weren't included in the PR.

**Comment by akosyakov** [comment]
@blink1073 ok, i will add our workarounds as part of `monaco/index.css` later

**Comment by blink1073** [comment]
I played some with the Monaco loading issue.  The good news is that requirejs works just as well as the Monaco loader, and we can use `window.require()` to load the editor from the monaco plugin and resolve the activate function when that finishes.   However, had been specifically avoiding having an AMD loader on the page up to this point.   The `editor.main` file explicitly references `window.require`, so I don't think we can wrap it in a context (though I am happy to be wrong here).

@afshin, @jasongrout, thoughts?

**Comment by jasongrout** [comment]
> The editor.main file explicitly references window.require, so I don't think we can wrap it in a context (though I am happy to be wrong here).

I think you're right - I'm browsing the monaco github repo, and I can't find the actual editor code. Do you have a link to the file or directory where the editor code is?

**Comment by blink1073** [comment]
There is no link to point to, unfortunately.  The https://www.npmjs.com/package/monaco-editor-core package is a dump of a build made from this file, presumably: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/editor.main.ts.

**Comment by jasongrout** [comment]
Honest question: is monaco ready to be integrated into other applications? As in, is it packaged well enough to be an independent component? Reading some of the issues pointed out by @akosyakov make me question whether that's the case currently. 

(Also, I'm really glad that @akosyakov and others are helping the Monaco folks know how to package their code in a way that makes it easier to consume.)

**Comment by jasongrout** [comment]
> As in, is it packaged well enough to be an independent component?

Or perhaps even more relevant, are they committed to maintaining the code in a way that makes it easier to use in other applications?

**Comment by cgravill** [comment]
There are some instructions for Monaco from source here: https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md which may be more convenient than the npm builds while figuring things out. It also comes with a browser based test tool which may be helpful. Slight issue is that a commit today to VSCode has an issue, until resolved may want to use 4056cfc2640c85bc204fa9e0d8d1f85fb0dcaa96 

I work at Microsoft Research (not connected to the VSCode/Monaco team) and have been able to integrate Monaco into some of our web tools with custom languages. It's worked significantly better than other code editors I've tried. 

It's great to see this effort already as I'm also involved in the F# Jupyter kernel (https://github.com/fsprojects/IfSharp). We're really interested in getting better editor and completion support.

**Comment by blink1073** [comment]
Thank you for the insight, @cgravill.  A possible solution could be for the Monaco plugin to be a separate repo that uses the vscode source and repackages it using the JupyterLab extension builder.

**Comment by ellisonbg** [comment]
Hi all! How do folks feel about closing this PR? We can always re-open again when we are able to move forward again? Do we have an issue open to track Monaco related things?

**Comment by blink1073** [comment]
There is #135.  I say we close this PR with and put update about the loader issues there.
@akosyakov, thank you for driving this and making our code base more extensible in the process.

**Comment by ellisonbg** [comment]
Let's keep in touch about the next steps, closing...

**Pull request closed without merging**
