### PR TITLE
Add support for types in the completer

### PR DESCRIPTION
**Pull request by ellisonbg**
Recent versions of IPython add experimental support for adding type data to the list of completions. This is provided by the `reply.metadata._jupyter_types_experimental` field of the completer reply. Some of the main points of the PR:

* If the type data is provided by `_jupyter_types_experimental` render the types visually.
* Don't make any assumption about the values provided by the kernel. This is done to allow each kernel to provide their own unique type names.
* Visually encode the types using the category10 colormap of vega (https://github.com/vega/vega/wiki/Scales#scale-range-literals) and a lowercase first letter of the type name (so `function` becomes `f`).
* A bit of style cleanup of the completer.

This work uncovered some refactoring of the completer that we should probably do post-beta. I will open a separate PR describing that work.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Light theme:

screen shot 2018-01-01 at 11 48 35 am

Dark theme:

screen shot 2018-01-01 at 11 49 06 am

**Comment by rgbkrk** [comment]
Slick color choices! I think I might just have to switch nteract's current builtin.

**Comment by ellisonbg** [comment]
Based on feedback, new changes include:

* `typeMap` is an optional argument to `setOptions`
* Full text of the type is included in the completer UI to the R of the matched text.
* Align the completer.

Light theme:

screen shot 2018-01-04 at 11 30 23 am

Dark theme:

screen shot 2018-01-04 at 11 30 42 am

Once tests pass this should be ready to merge.

**Comment by rgbkrk** [comment]
Awww, I liked the green.

**Pull request merged**
