### PR TITLE
Left Area -> Left Sidebar in menu

### PR DESCRIPTION
**Pull request by jasongrout**
This builds on #3801 and adds one commit - merge #3801 first.

This changes the menu text to align with our terminology of "sidebar", i.e., the change is "Show Left Area" -> "Show Left Sidebar" in the menu and the analogous change in the command palette text. No APIs were harmed in the making of this PR.

In https://github.com/jupyterlab/jupyterlab/pull/3801#discussion_r165820501, there was some discussion about what "sidebar" technically meant. Is it just the vertical tabs? Is it just the left panel content? Is it both?

The only real change in this PR beyond #3801 is 056359e279fd392a748e9711e01219bf617bbbbb, which just reverts one of the last commits of #3801.

### CODE REVIEW

**Comment by jzf2101** [comment]
@jasongrout merged your old pr can you merge upstream?

**Comment by jasongrout** [comment]
It will work automatically...git will recognize and merge this properly

**Comment by jasongrout** [comment]
We may not want to merge this right now since it will probably make one or two screenshots out of date. I think the language in the menu is 'good enough' that it isn't totally confusing, so I'll push this to beta 2.

**Comment by ian-r-rose** [comment]
I have no objection to using "Left Sidebar". @jasongrout, am I correct in thinking that most of these changes have already been merged? If so, can we open a new PR with just the name changes?

**Comment by jzf2101** [comment]
It appears a lot of these changes have already been adopted.  What's the best way to test `packages/application-extension/src/index.tsx`?

**Comment by jasongrout** [comment]
Looks good to me!

**Pull request merged**
