### PR TITLE
Clean up source map loader

### PR DESCRIPTION
**Pull request by blink1073**
Only attempt to load source maps for top level dependencies.

### CODE REVIEW

**Comment by blink1073** [comment]
cc @SimonBiggs

**Comment by blink1073** [comment]
I verified that this still picks up our source maps but doesn't warn about `vega-lite`.

**Comment by SimonBiggs** [comment]
Lovely :)

**Comment by blink1073** [comment]
Did this work for the angular warning as well?

**Comment by SimonBiggs** [comment]
Unfortunately I haven't yet worked out how to apply an upstream pull request for testing purposes on my local machine.

**Comment by SimonBiggs** [comment]
Ahh scrap that, it's such a small change. I'll do it by hand. Brb.

**Comment by blink1073** [comment]
I have this function in my `~/.bashrc`, that I call as `gpr 3093` (note I use `upstream` as the name of my remote that points to the main repo):

```bash
function gpr() {
    git checkout master
    git branch -D pr/$1 2>/dev/null
    git fetch upstream pull/$1/head:pr/$1
    git checkout pr/$1
}
```

**Comment by SimonBiggs** [comment]
Ahh beautiful, on both accounts. This change to `webpack.config.js` fixes the Angular issue! :).

I haven't tried the upstream pull request trick, I'll give that a go some time today. Thank you :)

**Comment by blink1073** [comment]
Thanks for testing the rc!

**Comment by SimonBiggs** [comment]
You're very welcome :)

**Comment by SimonBiggs** [comment]
I also just tried out `jupyter lab --watch`. I made a change in my extension, it didn't seem to trigger a rebuild.

**Comment by blink1073** [comment]
What does `jupyter labextension list` show?

**Comment by blink1073** [comment]
Note that if you are writing in TypeScript, WebPack is only watching the compiled files.

**Comment by SimonBiggs** [comment]
Oh that is beautiful! :). I can verify that by running `npm run build` in my local extension directory the `jupyter lab --watch` server sees the change and updates :). Turn around time from minutes down to seconds.

**Comment by blink1073** [comment]
You can use a `watch: tsc -w` script.

**Comment by blink1073** [comment]
e.g. https://github.com/jupyterlab/jupyterlab/blob/98a75a615338e1bf316390b207fb57c7e7ae4612/packages/apputils/package.json#L29

**Comment by SimonBiggs** [comment]
Thanks @blink1073. I appreciate all the help :).

**Comment by SimonBiggs** [comment]
Building an extension for jupyterlab is exciting :). I can't wait until it all starts to fit together :).

Thank you again :).

**Comment by blink1073** [comment]
My pleasure, thanks for sharing your enthusiasm!

**Comment by SimonBiggs** [comment]
:)

**Pull request merged**
