### PR TITLE
WIP: Add execution time plugin

### PR DESCRIPTION
**Pull request by saulshanabrook**
This address https://github.com/jupyterlab/jupyterlab/issues/3320 by adding an execution time plugin. I based the design on the [Execute Time nbextension](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/execute_time#internals). However, instead of displaying the time below the cell, it shows it in the cell tools. It uses the same cell metadata format as that extension to store the times. Here is a gif of it in action:

.

It doesn't support these features that are present in the original extension:
* Displaying in UTC vs local time
* Specifying the time zone to parse the kernel provided times
* Recording the start time when the code is sent to the kernel (the "queue" time)
* Displaying the start time as a relative time ("a few seconds ago").
* Highlighting the execution time when it is changed
* Clearing timings when output is cleared

I chose to implement this as a separate package, instead of integrating it into the `cell` package. I wanted to do this to make sure it would be possible for any third party extension to achieve similar functionality without modifying a core package. However, this did require adding the `lastReplyMsg` property to the code cell model, which is a signal that fires whenever the cell receives an execute reply message from the kernel. I also refactored the execution count to use this signal.

Things I would like feedback on:

* There is probably a better way to display this information in the cell tool. The current text sometimes wraps which isn't ideal.
* In the `activate` function I am tracking whenever a `lastReplyMsg` changes on a cell model and updating its metadata. However, I do this by tracking every notebook and seeing when widgets are added and seeing if they are code cells. There might be a cleaner way to do this.
* Inside the cell tool, I am connecting to the active cell's metadata and re-rendering whenever the times are updated. This feels a bit verbose. I wonder if there is a way to extract out this "Select current value and then update whenever it changes" logic generally for a react component. I couldn't figure out how to do this in a nice generic way, for all the `IObservableXXX` types.
* Is adding the `lastReplyMsg` signal to the code cell model the right approach to let any extension hook into this logic?

### CODE REVIEW

**Comment by saulshanabrook** [comment]
I am unable to get this to build for the tests. It works locally when running `jupyter lab --dev --watch`:

```bash
$ yarn  run build:core
yarn run v1.3.2
$ cd jupyterlab/staging && jlpm && jlpm run build
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/@jupyterlab%2fexecution-time-extension: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/saul/projects/jupyterlab/jupyterlab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by saulshanabrook** [comment]
@blink1073 Do you know how I could get this to build, without first publishing the package?

**Comment by blink1073** [comment]
This won't work in `core` or `app` modes until the package is published, only in `--dev-mode`.

**Comment by saulshanabrook** [comment]
In the meeting, we decided:
* This should not be a separate extension, because there isn't an obvious other use case for  `lastReplyMsg` being exposed publicly.
* The UI should likely be more like the CoCalc UI

**Comment by saulshanabrook** [comment]
Closing this, since we don't want this is a separate extension. I will open a new PR integrating it into core and changing the UI.

**Comment by saulshanabrook** [comment]
I opened https://github.com/jupyterlab/jupyterlab/pull/4161

**Pull request closed without merging**
