### PR TITLE
We should run this command.

### PR DESCRIPTION
**Pull request by ian-r-rose**
This was giving me a mild panic until the fix became clear.

### CODE REVIEW

**Comment by blink1073** [comment]
https://www.youtube.com/watch?v=-u9zr6oF4uA

**Comment by blink1073** [comment]
This should be in `0.30.x`, correct?

**Comment by ian-r-rose** [comment]
Probably. Redo does not work without it.

**Comment by blink1073** [comment]
kk

**Comment by ian-r-rose** [comment]
(Although it has been broken for a while)

**Comment by blink1073** [comment]
Thanks!

**Comment by blink1073** [comment]
@meeseeksdev backport to 0.30.x

**Pull request merged**
