### PR TITLE
Rendermime celloutput gap issue(#7760)

### PR DESCRIPTION
**Pull request by ggbhat**
## References
#7760  

## Code changes
Set line height to normal for pre tag for rendermime.

## User-facing changes
Before:
image

After:
celfixed

## Backwards-incompatible changes
no

### CODE REVIEW

**Comment by telamonian** [comment]
Looks good! I can't really tell from the screenshots you posted: does changing `line-height` to `normal` just fix the issue with the gap between the colored blocks, or does it also reduce the actual spacing between the line of output?

**Comment by ggbhat** [comment]
> Looks good! I can't really tell from the screenshots you posted: does changing `line-height` to `normal` just fix the issue with the gap between the colored blocks, or does it also reduce the actual spacing between the line of output?

Actually it reduces space between line also. But am  not sure on what basis the line-height is set to 1.3077 for **pre** tag.
**var(--jp-code-line-height) has value** - 1.3077

**Comment by jasongrout** [comment]
Based on the pics, I think it's probably fine, at least to merge and test and see if we have any unintended consequences.

CC @tgeorgeux as well.

**Comment by saulshanabrook** [comment]
Thanks @ggbhat for fixing this! We can always revert if we hit issues.

**Pull request merged**
