### PR TITLE
[WIP] Add binder link to readme.

### LINKED ISSUE #3830: Add link to jupyterlab-demo binder in readme and docs
In the docs, it should probably be pretty close to the beginning, as a Try Now sort of thing.

See also #3173 

- [X] Add to docs - d363a34778767fa73125a28a0765955dad509bac
- [ ] Add to readme

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #3830

### CODE REVIEW

**Comment by blink1073** [comment]
We should wait for the workspace to be ready since it is part of the url

**Comment by jasongrout** [comment]
Sure. This PR can remind us to update the URL :). And update the docs URL.

I guess the docs binder URL is a bit of a catch-22 - we need the release to get the URL, but the URL to get the release...

**Comment by blink1073** [comment]
The readme doesn't affect the release because it isn't on rtd, this PR can come last.

**Comment by jzf2101** [comment]
@jasongrout do we want to put this on the README? I had originally thought we'd direct people to the demo repo itself first?

**Comment by jasongrout** [comment]
I think it makes a lot of sense to have a 'launch binder' link in the jupyterlab readme as sort of a 'try it now' button.

**Comment by jasongrout** [comment]
Add WIP to title, since we are waiting on getting a good binder link before updating this and merging it.

**Comment by blink1073** [comment]
She's alive!

**Pull request merged**
