### PR TITLE
Update app and federated examples

### PR DESCRIPTION
**Pull request by jasongrout**
## Code changes

When we started working on prebuilt extensions, we were iterating on the federated example. At some point, we shifted focus to the real files in `dev_mode/`, but then never carried back the iterated improvements to the federated example. This does that—updates the federated example with the lessons we learned as we kept iterating on core JupyterLab.

- [x] Update the federated example webpack config
- [x] Update and simplify the app example (for example, the list of extensions in package.json could be just a list rather than a dict)

### CODE REVIEW

**Comment by jasongrout** [comment]
Rebased on master to resolve some conflicts...

**Comment by jasongrout** [comment]
I think this is ready for review now.

**Review by blink1073 — APPROVED** [review]
LGTM, thanks!

**Comment by jasongrout** [comment]
The examples test was cancelled after 120m. That test is the most relevant one that should be passing, so I'll restart it in CI to make sure it passes.

**Comment by jasongrout** [comment]
Looks like the examples test is now failing with a known jedi error:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions
debug >> Status: idle
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'
```

**Comment by jasongrout** [comment]
Positive review, (relevant) tests now pass. Thanks!

**Pull request merged**
