### PR TITLE
Fix integration tests

### LINKED ISSUE #14885: UI tests for extension manager is broken
## Description

Following the update the JupyterLab logo on the GitHub organization, the extension manager integration tests are broken.

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #14885

## Code changes

None

> Update snapshots

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by fcollonval** [comment]
bot please update documentation snapshots

**Comment by jtpio** [comment]
Ah the logo actually doesn't render really well on the snapshots and in the extension manager:

image

image

So maybe we could upload a better one for the organization first?

**Comment by jtpio** [comment]
Otherwise the changes look good, thanks for looking into it :+1: 

The UI tests have been regularly failing for a couple of weeks now. Is there a way to bring the check back to green in this PR?

**Comment by fcollonval** [comment]
> The UI tests have been failing regularly for a couple of weeks now. Is there a way to bring the check back to green in this PR?

I'll rebase because I hope that https://github.com/jupyterlab/jupyterlab/pull/14865 will fix the benchmark test in the _UI Tests_ job

**Comment by fcollonval** [comment]
bot please update galata snapshots

**Comment by jtpio** [comment]
All green :heavy_check_mark: :tada:

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
@meeseeksdev please backport to 4.0.x

**Pull request merged**
