### PR TITLE
Feature/optional hidden cells button

### PR DESCRIPTION
**Pull request by schmidi314**
# References
First prototype for issue #11490 

Todo: Test scripts fail (probably I have to update them?) and not yet looked into galata.

## Code changes
* Added option `showHiddenCellsButton` to Notebook Settings and communicated it to `MarkdownCell` widget. Default = true.
* Made behavior of hidden cells button (show or not) and collapse arrow-head buttons (hover or not) dependent on this option .
* Added two somewhat larger arrow head svgs. Not sure about design, though.

## User-facing changes
* With the default `showHiddenCellsButton=true` option, the only noticeable difference are somewhat larger arrow head buttons (left of the headings).
* With `showHiddenCellsButton=false`, the arrow heads are always displayed (not only on hover) and the hidden cells button won't be displayed.

optional_hidden_cells_button

### CODE REVIEW

**Review by fcollonval — CHANGES_REQUESTED** [review]
Thanks for starting this @schmidi314 

> For this first review, I will focus on the implementation logic.

We can simplify the logic as the setting is part of the notebook config by toggling a class on the notebook panel instead of propagating the value down to all markdown cells (also because there is no need to set that flag per markdown cells). You should do that in the `StaticNotebook` constructor and in [_updateNotebookConfig](https://github.com/schmidi314/jupyterlab/blob/b5832321a7a383cdcdfbef59ba3b85dbd5e958a5/packages/notebook/src/widget.ts#L782) instead of looping on all cells.  
The name of the class should be `jp-mod-...` to highlight that it depends on the state/settings.

Regarding the icon, I would not use a different design for homogeneity. But it would indeed be good if the icon could be bigger.
Could you look how it looks for deeper title (like heading level 5 or 6) ? We don't want the icon to be bigger than the title ;-)

Let me know if you need pointers.

**Comment by fcollonval** [comment]
To scale the background image, you can find more information on https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Resizing_background_images

**Comment by schmidi314** [comment]
Thanks a lot @fcollonval for the review. I learned a lot. And, phew, took me a while to figure out what to do, but I think I know now what you meant. Well, it was high time to start learning CSS anyway :)

* I think it is sufficient to toggle the class in `_updateNotebookConfig` only since this method is called on construction anyway. Also, the `jp-mod-scrollPastEnd` is only set in in `_updateNotebookConfig()`. So, either both or none class toggles should go to the constructor, right?
* Admittedly, this method of showing/unshowing buttons is a lot leaner than what I had written. But it is also a lot harder to grasp for beginners like me that are not so familiar with CSS. I would have had a hard time to understand why the `maybeCreateOrUpdateExpandButton` creates a button that doesn't show up in some cases. So: I'd suggest to add a comment in `maybeCreateOrUpdateExpandButton` 
* In the present pull request I also cleaned up (IMHO) the `maybeCreateOrUpdateExpandButton` method a bit. Basically it was about renaming variables, removing duplicates and writing the button text to the right property. Should I redo this or is the code better as it is? I'll add a single commit for this and then you can decide if you want to keep it.

Since only the first commit of the present PR will survive, I'd like to close this one and add a new one. Any objections?

**Comment by fcollonval** [comment]
> Thanks a lot @fcollonval for the review. I learned a lot. And, phew, took me a while to figure out what to do, but I think I know now what you meant. Well, it was high time to start learning CSS anyway :)

Don't hesitate to bring question on the PR or on Gitter if comments are unclear or to concise. We are always eager to help new contributors - and thank you for that.

>     * I think it is sufficient to toggle the class in `_updateNotebookConfig` only since this method is called on construction anyway. Also, the `jp-mod-scrollPastEnd` is only set in in `_updateNotebookConfig()`. So, either both or none class toggles should go to the constructor, right?

Indeed both should be toggle to in the constructor. So calling `_updateNotebookConfig` there sounds good.

>     * Admittedly, this method of showing/unshowing buttons is a lot leaner than what I had written. But it is also a lot harder to grasp for beginners like me that are not so familiar with CSS. I would have had a hard time to understand why the `maybeCreateOrUpdateExpandButton` creates a button that doesn't show up in some cases. So: I'd suggest to add a comment in `maybeCreateOrUpdateExpandButton`

Go ahead, better documentation is always good.
FYI this kind of CSS tricks is common in Web UI. A good practice when figure out what happens is to introspect the DOM and the CSS rules applied on a particular element. Then to search in the code where is the style set (usually through setting a class or attributes typically).
 
>     * In the present pull request I also cleaned up (IMHO) the `maybeCreateOrUpdateExpandButton` method a bit. Basically it was about renaming variables, removing duplicates and writing the button text to the right property. Should I redo this or is the code better as it is? I'll add a single commit for this and then you can decide if you want to keep it.

Better code wording is better documentation; so feel free to do so (you should only be careful not to change the API).

> Since only the first commit of the present PR will survive, I'd like to close this one and add a new one. Any objections?

:+1:

**Pull request closed without merging**
