### PR TITLE
Change running side bar to use react

### PR DESCRIPTION
**Pull request by saulshanabrook**
Changes the RunningSessions widget to use react instead of phosphor. 

It also removes the ability to customize the renderer of the running widget, because I am not sure exactly how this should translate to the react world and don't see any examples using it in our codebase
(or on github).

I made a common component for the running terminals and sessions, because they shared a lot of the same UI and code.

I tried to hold the state in the lowest component possible. So I stored the models on separate list components, not all in one big one. I also tried to be cognizant of render times. I opted not to mess with the `shouldComponentUpdate` to optimize re-rendering. However, since, the kernels and the terminals state is stored in different components, when one's props change, it only re-renders that one.

### CODE REVIEW

**Comment by saulshanabrook** [comment]
Instead of looking at the total diff, you can look at the second commit to get the correct diff: https://github.com/jupyterlab/jupyterlab/pull/4512/commits/79e6f3c5cc27b1eec7508fcad07aecbacfcc65dc

**Comment by blink1073** [comment]
Nice, thanks!

**Comment by saulshanabrook** [comment]
@blink1073 thanks for taking a look at this.

**Comment by blink1073** [comment]
Cheers

**Pull request merged**
