### PR TITLE
Jest Conversion Continued

### PR DESCRIPTION
**Pull request by blink1073**
Follow up to #5251.  Running coverage on `coreutils` drops to 6sec from 17sec with this change.

- Converts `test-coreutils` to jest, to be used as a template.
- Adds a script to automatically perform most of the conversion.  The only additional work for `coreutils` beyond what this script does was handing a `PathExt` difference because we are now running in node.
- Uses a common jest config file that allows for CSS and file imports
- I tried to moved tests under `packages/<foo>/tests` since we do not need a common set of test source files (because of `testutils`), but that results in a circular dependency because `testutils` depends on some of the packages.
- Moves `services` to `tests/test-services`
- Moves `tsconfig` to root of each package so we don't have to use `/src` in the build or reference targets
- We need to make sure to import from `/src` for the package being tested so we get coverage.

```
$ yarn test --coverage
yarn run v1.9.4
$ python tests/run_test.py --coverage
[C 08:03:14.744 JestApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8838/?token=ea2853b595f03348097d207b623673e95fd484d8647638c7
 PASS  tests/src/activitymonitor.spec.ts
 PASS  tests/src/settingregistry.spec.ts
 PASS  tests/src/url.spec.ts
 PASS  tests/src/statedb.spec.ts
 PASS  tests/src/time.spec.ts
 PASS  tests/src/markdowncodeblocks.spec.ts
 PASS  tests/src/pageconfig.spec.ts
 PASS  tests/src/path.spec.ts
 PASS  tests/src/nbformat.spec.ts
-----------------------|----------|----------|----------|----------|-------------------|
File                   |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------------|----------|----------|----------|----------|-------------------|
All files              |    80.37 |    62.34 |    79.31 |    80.76 |                   |
 activitymonitor.ts    |      100 |      100 |      100 |      100 |                   |
 dataconnector.ts      |    33.33 |      100 |        0 |    33.33 |             42,59 |
 index.ts              |      100 |      100 |      100 |      100 |                   |
 markdowncodeblocks.ts |    97.37 |    88.89 |      100 |    97.37 |                54 |
 nbformat.ts           |    73.68 |    85.71 |    33.33 |    73.68 |... 67,474,481,488 |
 pageconfig.ts         |    73.91 |    53.85 |       70 |    73.91 |... 70,172,192,198 |
 path.ts               |      100 |      100 |      100 |      100 |                   |
 settingregistry.ts    |    77.46 |    62.16 |       78 |    78.74 |... 1061,1063,1067 |
 statedb.ts            |    90.43 |    72.22 |    93.33 |    90.11 |... 25,446,447,462 |
 text.ts               |    15.38 |     7.69 |    33.33 |    15.38 |... 64,65,66,67,71 |
 time.ts               |      100 |      100 |      100 |      100 |                   |
 url.ts                |    85.37 |    57.14 |    84.62 |    85.37 |... 25,130,132,134 |
-----------------------|----------|----------|----------|----------|-------------------|

Test Suites: 9 passed, 9 total
Tests:       103 passed, 103 total
Snapshots:   0 total
Time:        4.058s
✨  Done in 5.82s.
```

### CODE REVIEW

**Comment by blink1073** [comment]
There's too much fiddling with typings going on here, I'm going to wait for #5030 and then finish this.

**Comment by blink1073** [comment]
Ugh.  I used `git mv` for the `tsconfig` files but they must differ too much from the originals...

**Comment by rgbkrk** [comment]
Omg you're switching to jest. ❤️ ❤️ ❤️

**Comment by blink1073** [comment]
It has been painful to switch, but Jest is pretty amazing.   I'm already using it at work against Jlab packages, I just had to add a shim for a missing browser API that CodeMirror uses (which will come in a follow up PR here).

**Comment by blink1073** [comment]
cf https://discuss.codemirror.net/t/working-in-jsdom-or-node-js-natively/138 for the CodeMirror fix

**Comment by rgbkrk** [comment]
Likely similar to what nteract uses here:

https://github.com/nteract/nteract/blob/47f8b038ff129543e42c39395129efc433eb4e90/package.json#L68-L72

https://github.com/nteract/nteract/blob/master/scripts/test-shim.js

😅

**Comment by blink1073** [comment]
Nice, thanks!

**Pull request merged**
