### PR TITLE
Backport PR #10954 on branch 3.1.x (Improve release notes for 3.1)

### PR DESCRIPTION
**Pull request by Mithil467**
Backport PR #10954: Improve release notes for 3.1

### CODE REVIEW

**Comment by blink1073** [comment]
The link check failed because we had not yet backported https://github.com/jupyterlab/jupyterlab/pull/10699.  In progress now

**Comment by Mithil467** [comment]
Ok! Do I need to rebase once https://github.com/jupyterlab/jupyterlab/pull/10699 is merged?

**Comment by blink1073** [comment]
We should be able to close and open this PR after #11055 is merged to pick up the change

**Comment by blink1073** [comment]
Kicking CI

**Review by blink1073 — APPROVED** [review]
Thank you!

**Pull request merged**
