### PR TITLE
Unpin tornado (bump to 6.x) 

### LINKED ISSUE #6131: Unpin tornado dependency
#6123 rolled back our dependency on `notebook` due to some upstream issues with async kernel starts (or possibly tornado 6). We need to identify and fix these issues before making a release.

Edit: we have resolved the immediate issue with notebook in 5.7.8, but issues with tornado 6 remain.

### PR DESCRIPTION
**Pull request by Zsailer**
:tada: Unpin tornado! 🎉 

## References

Fixes #6131. 

This problem was caused by a bug in tornado that we fixed in tornadoweb/tornado#2670. 

## Code changes

Unpin tornado from `5.x` to `>=6.0.3` in `setup.py`.

### CODE REVIEW

**Comment by jasongrout** [comment]
Please let's just remove the pin completely, and not force people to upgrade to tornado 6 if they have reason to stay on tornado 5. There might also be a way to specifically say not between 6 and 6.0.2, but I think it's probably easier to just remove the pin and if they have a problem, ask them to upgrade to the latest tornado patch release.

**Comment by blink1073** [comment]
There's also a directive to install a pinned tornado in RELEASE.md

**Comment by vidartf** [comment]
An alternative way of writing it could be: `<6, >=6.0.3` (or `!=6.0.0, !=6.0.1, !=6.0.2` for a more explicit blacklist).

**Comment by Zsailer** [comment]
@vidartf Wait, can you blacklist dependencies in `setup.py` using `!=`?

**Comment by Zsailer** [comment]
Ok, I've blacklisted the tornado versions that throw the `"Already Reading"` error.

**Comment by blink1073** [comment]
@Zsailer, don't forget about RELEASE.md

**Comment by vidartf** [comment]
@Zsailer I went off these docs: https://docs.python.org/2/distutils/setupscript.html#relationships-between-distributions-and-packages

I did not test it myself though (maybe setuptools cares?).

**Comment by Zsailer** [comment]
@vidartf It looks like it works (and setuptools [honors this syntax](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies)). Great Find! 

@blink1073 I removed the tornado pinning directives in the RELEASE.md. Should I blacklist the problem versions (I'm thinking that might be overkill)?

**Comment by ian-r-rose** [comment]
Thanks for all the hard work on this one @Zsailer, looking forwards to putting it behind us!

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterlab-1-0-release-candidate-published/1438/8

**Pull request merged**
