### PR TITLE
Skip deprecated versions when looking for compatible extension versions.

### PR DESCRIPTION
**Pull request by jasongrout**
## References
See https://github.com/jupyterlab/jupyterlab/issues/6697

CC @vidartf 

## Code changes
Skip deprecated extension versions when looking for compatible versions to install.

### CODE REVIEW

**Comment by jasongrout** [comment]
@vidartf @athornton - with this change, `jupyter labextension install @jupyter-widgets/jupyterlab-manager --debug` correctly deduces that there is no non-deprecated published version of ipywidgets that is compatible with current master.

**Comment by jasongrout** [comment]
(whereas before, it would happily install a deprecated version).

I also checked and `jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.39.1` correctly installs the deprecated version that is not compatible with master since I explicitly asked for it.

**Comment by vidartf** [comment]
Nice. It does what it says on the tin. One possible improvement would be to only check for deprecation for otherwise valid packages, and then log to debug that we found a compatible version, but which was deprecated (possibly logging the deprecation warning that is stored in the `deprecated` field). I'm not sure if this is useful enough to warrant that though.

**Comment by jasongrout** [comment]
> I'm not sure if this is useful enough to warrant that though.

I'm not sure it's useful either. I think it should be a different PR, though. I don't think anyone will complain about having that warning.

**Pull request merged**
