### PR TITLE
Backport PR #11457 on branch 3.2.x (Only show the head of the outputs and ensure iopub outputs are correctly displayed)

### PR DESCRIPTION
**Pull request by fcollonval**

### CODE REVIEW

**Review by echarles — APPROVED** [review]
LGTM. The i18n CI failure have happened before on backport and is not related to this PR.

**Comment by echarles** [comment]
Thx @fcollonval

**Comment by krassowski** [comment]
> The i18n CI failure have happened before on backport and is not related to this PR.

It is related (the text of setting description was modified), but I would say that this is an acceptable to break translations here (i.e. users of fully-translated languages will see a regression in the form of missing translation for this string) because this is an important bugfix PR, and not a minor stylistic adjustment.

**Comment by echarles** [comment]
true, it is related, but acceptable to be broken. Thx for that precision.

**Pull request merged**
