### PR TITLE
Add yarn as a dev dependency.

### LINKED ISSUE #4459: Theme building issue
Many people have had trouble building the recent versions of jupyterlab. @jzf2101 [posted on gitter](https://gitter.im/jupyterlab/jupyterlab?at=5ae0806a27c509a7744d012d):

```bash
$ lerna run build:webpack --scope "@jupyterlab/theme-*-extension"
lerna info version 2.9.0
lerna info versioning independent
lerna info scope @jupyterlab/theme-*-extension
lerna ERR! build:webpack Errored while running script in '@jupyterlab/theme-dark-extension'
lerna ERR! execute callback with error
lerna ERR! Error: spawn yarn ENOENT
lerna ERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
lerna ERR!     at onErrorNT (internal/child_process.js:379:16)
lerna ERR!     at process._tickCallback (internal/process/next_tick.js:178:19)
lerna ERR!     at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
lerna ERR!     at startup (internal/bootstrap/node.js:201:19)
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
lerna ERR! build:webpack Errored while running script in '@jupyterlab/theme-light-extension'
{ Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'run', 'build:webpack' ],
  killed: false,
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd: 'yarn run build:webpack',
  timedOut: false,
  exitCode: 1 }
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c lerna run build:webpack --scope \"@jupyterlab/theme-*-extension\"
Directory: /Users/forde/Documents/jupyter_docs/jupyterlab
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/forde/Documents/jupyter_docs/jupyterlab/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c jlpm run integrity && jlpm run build:packages && jlpm run build:themes && cd dev_mode && jlpm run build
Directory: /Users/forde/Documents/jupyter_docs/jupyterlab
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/forde/Documents/jupyter_docs/jupyterlab/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c jlpm run build:dev
Directory: /Users/forde/Documents/jupyter_docs/jupyterlab
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/forde/Documents/jupyter_docs/jupyterlab/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Fordes-MacBook:jupyterlab forde$ conda install -c conda forge pip
Solving environment: failed
```

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #4459

### CODE REVIEW

**Comment by jasongrout** [comment]
@meeseeksdev, please backport to 0.32.x

**Comment by jasongrout** [comment]
@meeseeksdev backport to 0.32.x

**Comment by jasongrout** [comment]
@meeseeksdev backport to 0.32.x

**Comment by ian-r-rose** [comment]
LGTM!

**Comment by jasongrout** [comment]
@meeseeksdev backport to 0.32.x

**Comment by jzf2101** [comment]
@jasongrout FYI I pulled upstream and I still can't `jlpm run build` on master

```
jlpm run build
yarn run v1.6.0
$ jlpm run build:dev
$ jlpm run integrity && jlpm run build:packages && jlpm run build:themes && cd dev_mode && jlpm run build
$ node buildutils/lib/ensure-repo.js
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/Users/forde/Documents/jupyter_docs/jupyterlab/buildutils/lib/ensure-repo.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jasongrout** [comment]
Thanks @jzf2101. This is not the issue that this PR was solving. Can you open another issue so we can have a clean place to start diagnosing the problem?

**Pull request merged**
