### PR TITLE
Update dependencies

### LINKED ISSUE #7194: Upgrade packages for jlab 2.0
xterm just released 4.0, which we should probably try to upgrade to for jlab 2.0.

Actually, we should probably do a package upgrade/refresh cycle sometime just before 2.0, hence this issue.

### PR DESCRIPTION
**Pull request by lresende**
## Code changes

Few dependency updates in preparation for JupyterLab 2.0 release.

## Usage

Update all dependencies (except jupyterlab) to latest
`jlpm run update:dependency '^(?!@jupyterlab).*' latest --regex`

Update all dependencies (except jupyterlab, codemirror, xterm) to latest
`jlpm run update:dependency --regex '^(?!@jupyterlab|codemirror|@types/codemirror|xterm|linters).*' latest`

Depends on #7599 
Fixes #7194

### CODE REVIEW

**Comment by blink1073** [comment]
@lresende, are you able to run `jupyter lab --dev-mode` locally with these changes?  For me, the browser content never loads.

**Comment by lresende** [comment]
@blink1073 let me look at that

**Comment by lresende** [comment]
@blink1073 I looked at validating the behavior you described and it looks like this is a Firefox issue, as it's loading ok in Safari. @afshin also saw the same behavior. I will investigate it further to try to find the issue.

**Comment by lresende** [comment]
Just a quick update: 
`jupyter lab --debug --dev-mode` works in Chrome, Safari but fails in Firefox
`jupyter lab --debug --core-mode` seems to work fine in all browsers

I am still trying to identify what's going on with `dev-mode` in Firefox.

**Comment by blink1073** [comment]
We narrowed it down: css-loader@<3.3.2 works fine 3.3.3 and 3.40 do not work (it times out loading styles).  I couldn't think of a way to get a reproducible example to make an issue on the css-loader repo.

**Comment by blink1073** [comment]
We can't upgrade xterm yet because of https://github.com/xtermjs/xterm.js/issues/2620.   Our theme values are inherited from our CSS variables, which can include `rgba()` values, and currently only `#rrggbbaa` is supported.

**Comment by jasongrout** [comment]
> We can't upgrade xterm yet because of [xtermjs/xterm.js#2620](https://github.com/xtermjs/xterm.js/issues/2620). Our theme values are inherited from our CSS variables, which can include `rgba()` values, and currently only `#rrggbbaa` is supported.

We're at xterm 3.13.2. Can we upgrade to 4.2, since from the issue it appears that the issue is with 4.3.0?

**Comment by lresende** [comment]
> > We can't upgrade xterm yet because of [xtermjs/xterm.js#2620](https://github.com/xtermjs/xterm.js/issues/2620). Our theme values are inherited from our CSS variables, which can include `rgba()` values, and currently only `#rrggbbaa` is supported.
> 
> We're at xterm 3.13.2. Can we upgrade to 4.2, since from the issue it appears that the issue is with 4.3.0?

Yes, xterm 4.2.0 seems to work fine.

**Comment by lresende** [comment]
Thanks @blink1073 for helping debug some of the issues after some dependency updates. 
All known issues should have been fixed and this pr has also been rebased to latest master and is ready for review/merge if no other issues are discovered.

**Comment by blink1073** [comment]
Thanks @lresende!

**Pull request merged**
