### PR TITLE
Open Help menu's Jupyter Forum in a new browser tab by default

### LINKED ISSUE #10398: Jupyter Forum (discourse) does not open correctly in 3.1.0.a12
## Description

In Chrome and Firefox selecting `Help` → `Jupyter Forum` from the menu results in "Refused 

This menu entry was requested in #8678 and introduced in #9892

## Reproduce

1. Open "Help" menu
2. Select "Jupyter Forum"
3. See error "discourse.jupyter.org refused to connect."

Screenshot from 2021-06-13 10-35-01

Screenshot from 2021-06-13 10-36-32

## Expected behavior

The discourse is configured to allow embedding and opens ok

## Context

- JupyterLab version: 3.1.0.a12

### PR DESCRIPTION
**Pull request by isabela-pf**
## References

Fixes #10398

Based on [this comment](https://github.com/jupyterlab/jupyterlab/issues/10398#issuecomment-875142034) and feedback in the JupyterLab team meeting.

I also have to send never-ending thanks to @steff456 for support as I continue to edit typescript files without knowing typescript.

## Code changes

- [x] Adds the Jupyter Forum help option as its own constant that opens a link to the Jupyter discourse in a new browser tab (similar to Launch Classic Notebook)
- [x] Jupyter Forum appears in the command palette
- [x] Jupyter Forum appears as an item in the Help menu

I could use feedback on how to get this back in the Help menu. I've tried the following without success
- creating a `jupyter-forum.json` file the way that the the [About](https://github.com/jupyterlab/jupyterlab/blob/master/packages/help-extension/schema/about.json) and [Launch Classic Notebook](https://github.com/jupyterlab/jupyterlab/blob/master/packages/help-extension/schema/launch-classic.json) do
- manually adding it to the main menu [here](https://github.com/jupyterlab/jupyterlab/blob/62945366d491bd056a494bbdb59c5cfbbc619698/packages/mainmenu-extension/schema/plugin.json#L222)(which seems like bad practice)

## User-facing changes

The Jupyter Forum link opens in a new browser tab instead of a JupyterLab tab. The menu item also appears two entries higher.

## Backwards-incompatible changes

This removes Jupyter Forum from the [resources group](https://github.com/jupyterlab/jupyterlab/blob/62945366d491bd056a494bbdb59c5cfbbc619698/packages/help-extension/src/index.tsx#L232) and creates the new `jupyterForum` constant. 

I'm not sure whether or not that is backwards incompatible.

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks, this is looking good!

> (And right now it doesn't appear in the Help menu, but that should be fixed before merging.)

Let's convert the PR to a draft for now then?

> creating a `jupyter-forum.json` file the way that the the [About](https://github.com/jupyterlab/jupyterlab/blob/master/packages/help-extension/schema/about.json) and [Launch Classic Notebook](https://github.com/jupyterlab/jupyterlab/blob/master/packages/help-extension/schema/launch-classic.json) do

This should now be the preferred approach for adding items to the menu. Probably the configuration will be the same as for the launch classic command. Would you like to push a commit with what you have tried which might help see what is happening?

**Comment by isabela-pf** [comment]
Thanks for the feedback @jtpio! I must have been testing it wrong, because it looks like Jupyter Forum is back in the menu.

Now the main change is that Jupyter Forum is two items higher on the list than before.

**Comment by jtpio** [comment]
> Now the main change is that Jupyter Forum is two items higher on the list than before.

Probably we can tweak the `rank` option if needed? Otherwise I guess it's fine if it ranks higher.

**Comment by jtpio** [comment]
Looking good on Binder :+1: 

https://user-images.githubusercontent.com/591645/124929421-c5e9fc80-e000-11eb-862f-48c1d0ef5ee7.mp4

**Comment by jtpio** [comment]
Looks like the failing visual regression check is relevant, since the help menu has now changed: https://github.com/jupyterlab/jupyterlab/pull/10574/checks?check_run_id=3019258887

**Comment by isabela-pf** [comment]
Right now [About is at rank 0](https://github.com/jupyterlab/jupyterlab/blob/88b8c145ea95fd3654987d3a490a9b996905dfb2/packages/help-extension/schema/about.json#L9), [Launch Classic Notebook is at rank 1](https://github.com/jupyterlab/jupyterlab/blob/88b8c145ea95fd3654987d3a490a9b996905dfb2/packages/help-extension/schema/launch-classic.json#L13), Jupyter Forum is at 2, and [all other help items are rank 1000](https://github.com/jupyterlab/jupyterlab/blob/88b8c145ea95fd3654987d3a490a9b996905dfb2/packages/mainmenu-extension/schema/plugin.json#L223).

Jupyter Forum was originally in the middle of that lower group, but all those items currently have the same rank and are all brought into the menu as a group. I think that means I can only get the Jupyter Forum option above or below the group without rewriting the way those menu items are grouped. Or am I misunderstanding something?

**Comment by krassowski** [comment]
> Jupyter Forum was originally in the middle of that lower group, but all those items currently have the same rank and are all brought into the menu as a group. I think that means I can only get the Jupyter Forum option above or below the group without rewriting the way those menu items are grouped. Or am I misunderstanding something?

Yes, exactly. I think this is fine, we just need to update the reference screenshot. It can be done by downloading the new version of `general_opened_menu_help.png` from Artifacts on https://github.com/jupyterlab/jupyterlab/pull/10574/checks?check_run_id=3019258887 (ui-test-new-reference) and replacing the old file in https://github.com/jupyterlab/jupyterlab/tree/master/ui-tests/reference-output/screenshots in a commit explaining the update.

**Comment by isabela-pf** [comment]
That sounds like it should be a separate PR. Or is it supposed to be in this PR to keep it linked to why the change was made?

(Also thank you so much for the help @krassowski!)

**Comment by krassowski** [comment]
In this PR.

**Comment by krassowski** [comment]
Is it ready for review now?

**Comment by isabela-pf** [comment]
I was waiting for it to pass, but this works too!

**Comment by krassowski** [comment]
Ops, there is one more that needs updating I did not notice previously: `notebook_create_opened_menu_help.png`

**Review by krassowski — APPROVED** [review]

**Comment by krassowski** [comment]
Ok, looking at this plugin again, was using `newBrowserTab` instead an option?

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/allow-embedding-opening-from-within-jupyterlab/9578/9

**Pull request merged**
