### PR TITLE
Travis should check the integrity of the yarn lock file.

### PR DESCRIPTION
**Pull request by jasongrout**
Adding the yarn integrity check to travis tests

### CODE REVIEW

**Comment by blink1073** [comment]
I'm looking into the test failure in cells, it appears to be a race condition somewhere, since it happens randomly.

**Comment by blink1073** [comment]
Pushed a fix

**Comment by jasongrout** [comment]
> Pushed a fix

That test seems to want to test that the number of updates is bounded *above* ("should ignore being set to the same value"), i.e., that the number updates is not *more* than one, not bounded below.

**Comment by jasongrout** [comment]
I think https://github.com/jupyterlab/jupyterlab/pull/5427/commits/d615b16ee86d6c759e12245c185bc7701a11c715 (from https://github.com/jupyterlab/jupyterlab/pull/5427) is a more correct fix, but it still seems to not address the race condition, only makes it harder to hit.

**Pull request merged**
