### PR TITLE
Fix autocomplete in console

### LINKED ISSUE #11710: Autocomplete broken for console
## Description

I'm pretty sure autocomplete used to work in console as well. Now using tab adds a space.

## Reproduce
ipython-autocomplete

## Expected behavior

Autocomplete works with tab press in console.

## Context

Lab@3.2.5

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fix #11710

## Code changes

Add awareness to standalone cell to restore cursor activity event

## User-facing changes

Completer and cursor position are back in the console

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by jasongrout — APPROVED** [review]
This seems to fix the issue for me. Thanks!

**Comment by fcollonval** [comment]
@hbcarlos @dmonad would you mind having a look at this one?

**Review by echarles — APPROVED** [review]
Works for me.
Screenshot 2022-01-27 at 13 48 11

**Comment by echarles** [comment]
RTC (and awareness) behavior is also OK.

**Comment by hbcarlos** [comment]
Hi, @fcollonval thanks for fixing this issue! The PR LGTM!

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.3.x

**Comment by jtpio** [comment]
@meeseeksdev please backport to 3.2.x

**Comment by jtpio** [comment]
Backporting to 3.2.x based on the discussion in https://github.com/jupyterlab/jupyterlab/issues/11466#issuecomment-1024924812

**Pull request merged**
