### PR TITLE
Add a plugin to be able to swap the doc provider

### LINKED ISSUE #10252: Pluggable provider for real time collaboration
### Problem

For now the provider for real time collaboration is defined in the doc registry `Context`:

https://github.com/jupyterlab/jupyterlab/blob/27ecb2f9a22736c13a8b0e2722fbdf046d37c43c/packages/docregistry/src/context.ts#L92-L96

It relies on the backend exposing the `/api/yjs` endpoint, and uses the `WebsocketProviderWithLocks` to connect to it.

This should ideally be configurable, so extension authors could use a different provider if they would like to.

### Proposed Solution

One way to implement this would be to move that logic to a plugin in the `docmanager-extension` package.

In JupyterLab the plugin would still use the `WebsocketProviderWithLocks` class if `collaborative` is set in the page config, so pretty much the same behavior.

Third-party extensions could provide a different plugin and replace it using the existing mechanism to disable other extensions: https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html?#disabling-other-extensions

### Additional context

Alternative distributions could do something similar and not include the upstream JupyterLab plugin, and instead provide a custom one.

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes #10252 

Early draft for what it would look like to have a plugin that can be used to set custom providers. 

**TODO**

- [x] Move the doc provider instantiation to a plugin
- [x] Rename `IProvider` to `IDocumentProvider`
- [x] Docstrings for the `IDocumentProvider` interface
- [x] Move reading the page config option to the plugin?
- [x] Create a `docprovider-extension` package?

## Code changes

Move the creation of the provider in the document context to a plugin, which can then be disabled or replaced in other lab extensions and distributions.

## User-facing changes

None

## Backwards-incompatible changes

Add an optional parameter to some of the instantiation options.

### CODE REVIEW

**Comment by jtpio** [comment]
Rebased to grab https://github.com/jupyterlab/jupyterlab/pull/10258, so this PR can be tested on Binder with RTC enabled.

**Comment by echarles** [comment]
@jtpio quick feedbacks

- The token IDocumentProviderFactory defined in `docprovider` is provided with a plugin ` const docProviderPlugin: JupyterFrontEndPlugin<IDocumentProviderFactory> = {` in the `docmanager-extension`package. Is that inline with jupyterlab architecture? I mean, I was expected to see a new `docprovider-extension` package to do that job. A new package for that single bit may sound overkill, but it is like that in many other existing packages.

- What about `docregistry`. For now, the `IDocumentProviderFactory` is passed to the registry through options. Wouid it make sense to also inject it? In that case we would need to convert the docregistry to an extension, which is not the case now.

**Comment by jtpio** [comment]
> * I was expected to see a new `docprovider-extension` package to do that job. A new package for that single bit may sound overkill, but it is like that in many other existing packages.

Yes, it's still one of the remaining TODO items listed in https://github.com/jupyterlab/jupyterlab/pull/10256#issue-645807710.

This was also discussed yesterday during the RTC call (https://hackmd.io/UbnBH58hS8itoWgfiWT77A) and the conclusion was that it would indeed make sense to have a `docprovider-extension` package.

I can update this PR to add it.

**Comment by jtpio** [comment]
> * What about `docregistry`. For now, the `IDocumentProviderFactory` is passed to the registry through options. Wouid it make sense to also inject it? In that case we would need to convert the docregistry to an extension, which is not the case now.

Not sure yet. But probably something to think about as a follow-up?

**Comment by echarles** [comment]
> I can update this PR to add it.

Great!

> Not sure yet. But probably something to think about as a follow-up?

Looking more at the constructs, the Context is created by the docmanager which is injected with the correct IDocumentProviderFactory, so having an docregistry-extension does not make sense for that case.

Another enhancement would be to make the docregister/context a bit more agnostic, so not having to depend directly on the yjs library, so not having to maintain those 2 fields

```js
  private _ydoc: Y.Doc;
  private _ycontext: Y.Map<string>;
```

**Comment by jtpio** [comment]
The `splice_source` check fails because `docprovider-extension` is not published to `npm` yet.

**Comment by jtpio** [comment]
Added the `docprovider-extension` package (cc @echarles if you want to have a look).

Some CI checks will fail until the package is published to `npm`.

**Comment by echarles** [comment]
I have quickly scanned the diff and it LGTM. Do you have more to add before I review?

**Comment by jtpio** [comment]
Thanks.

I think it should be ready to go.

**Review by echarles — APPROVED** [review]
Reviewed and tested. LGTM. Let's wait 2 days before merging to get any further comment.

**Comment by jtpio** [comment]
Thanks @echarles.

A follow-up to this PR would be to publish the new `docprovider-extension` package to `npm` to fix the failing CI checks.

**Comment by blink1073** [comment]
Thanks @jtpio and @echarles!  I'll cut another alpha with this today (in a few hours), but will hold off merging until then so CI stays working.

**Comment by blink1073** [comment]
Releasing now

**Comment by blink1073** [comment]
https://github.com/jupyterlab/jupyterlab/releases/tag/v3.1.0a9

**Comment by echarles** [comment]
Thx @jtpio and @blink1073

**Pull request merged**
