### PR TITLE
Add 'merge cell above/below' commands with shortcuts

### LINKED ISSUE #6330: Lack of merge cell commands?
Notebook has "Merge Cell Above", "Merge Cell Below" commands.
But, I can't see under edit menu in the Jupyerlab.
It's very useful when cell need to be execute partially.
Also, it will be very convenient if I can run it inside the cell with a short key.

It likes,
1. Ctrl+Shift + - (Split Cell)
2. Execute and edit cell
3. Merge Cell Below (Ctrl+Shift+M)

Thanks.

## Lab Screenshot
lab

## Notebook Screenshot
notebook

### PR DESCRIPTION
**Pull request by krassowska**
## References

Fixes #6330

## Code changes

Added `mergeAbove` parameter in `mergeCells` function with default value `false`. When `false` this function will merge with a cell below, when `true` it will merge with a cell above.

## User-facing changes

Added "Merge cell above" and "Merge cell below" commands with keyboard shortcuts proposed in #6330 (Ctrl+Backspace for cell above and Ctrl+Shift+M for cell below). The options are displayed in the main menu and context menu (not sure if it should stay here as it's getting long).
"Merge selected cells" works the same.

Merge cell below/above gif

## Backwards-incompatible changes

I don't know of any.

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @krassowska!  Do you mind adding a test case to cover the new `mergeAbove` parameter?

https://github.com/jupyterlab/jupyterlab/blob/0e2310000f85f9ccbf7afc5ac32edb0ab542bf2c/packages/notebook/test/actions.spec.ts#L200

**Comment by krassowska** [comment]
Thank you @jtpio. I've added two tests. All tests are passing on my computer, but some other things are now failing on GitHub and I don't understand why.

**Review by blink1073 — APPROVED** [review]
Thank you!

**Comment by blink1073** [comment]
Kicking CI

**Comment by blink1073** [comment]
> Update after #10094

Good catch!

**Pull request merged**
