### PR TITLE
Fix Python test dependencies

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Pytest fixtures for Jupyter are now part of a separate package [pytest-jupyter](https://github.com/jupyter-server/pytest-jupyter).

## Code changes

Add the new test dependency
Remove unused `ui-tests` optional group dependency

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
👍🏼

**Comment by jtpio** [comment]
Looks like some Python tests (3.7?) give the following:

```
ERROR: Could not find a version that satisfies the requirement pytest-jupyter[server]; extra == "test" (from jupyterlab[dev,test]) (from versions: none)
```

**Comment by blink1073** [comment]
Ah, the plugin is 3.8+ currently

**Comment by fcollonval** [comment]
Yep I opened https://github.com/jupyter-server/pytest-jupyter/issues/29

Is it possible to lower the plugin package requirement or should we bump the minimal tested version to 3.8?

**Comment by blink1073** [comment]
Done: https://github.com/jupyter-server/pytest-jupyter/releases/tag/v0.5.1

**Comment by fcollonval** [comment]
The error on js-services needs to be addressed. But I'm merging as is as it solves the Python jobs to keep the ball rolling for other PRs.

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.6.x

**Comment by fcollonval** [comment]
Actually the `js-services` failures appeared before this one; see https://github.com/jupyterlab/jupyterlab/issues/13460

**Comment by jtpio** [comment]
Looks like some Python checks are failing on master after this PR was merged (168a53dd856f48bb2ce15cc5078bd132829d2efb): https://github.com/jupyterlab/jupyterlab/actions/runs/3583498754/jobs/6028998723

**Comment by blink1073** [comment]
Could be fixed by https://github.com/jupyter-server/pytest-jupyter/releases/tag/v0.5.3

**Comment by fcollonval** [comment]
Actually no - the renamed in https://github.com/jupyter-server/pytest-jupyter/pull/32 is impacting use because I modified the fixture name in this PR.

**Comment by fcollonval** [comment]
I'll open a follow-up fix

**Pull request merged**
