### PR TITLE
Enables private npm registry passing a npm-registry config flag

### LINKED ISSUE #4149: Make NPM registry configurable
Follow-up to #3608. The `_AppHandler.registry` should be configurable. This should allow for offline / firewalled deployments of JupyterLab by having it work against a local repository (at least it will be a step in the right direction), or simply allow people to use an alternative repo to `npmjs.org`.

### PR DESCRIPTION
**Pull request by pablolmiranda**
## References

This PR try to fix #4149 issue.

## Code changes

On the labextension command we add a npm-registry flag and propagate it downstream to commands._AppHandler to install extensions not present on 'https://registry.npmjs.org'.

### CODE REVIEW

**Comment by pablolmiranda** [comment]
Not sure if the issue is related to my changes

**Comment by blink1073** [comment]
Hi @pablolmiranda, thanks for doing this!  Yes, it looks like you'll need to update `uninstall_extension` as well:

```
TypeError: uninstall_extension() got an unexpected keyword argument 'npm_registry'
```

**Comment by pablolmiranda** [comment]
@blink1073 I have some mix feeling about the yarn install as well. Should it defines a new parameter for yarn registry or reuse the npm registry?

**Comment by blink1073** [comment]
Do you mean for the developer workflow, as in `jlpm`?

**Comment by pablolmiranda** [comment]
The `labextension` subcommand.
Right now, the workflow inside `labextension` uses `npm` and `yarn.` It uses `npm` to pack the extension and later uses `yarn` to install it.
The issue with this workflow is both commands use different registries. After my PR, the `npm` will use the `npm-registry` flag, or fallback to `https://registry.npmjs.org.` But `yarn` will try to reach `https://registry.yarnpkg.com`.
In this case, there is two option, force `yarn` to use the `npm` registry or add another flag to pass a `yarn` registry.
Thoughts?

**Comment by blink1073** [comment]
I don't think it matters that we use npm to pack, it is just creating a tarball of the contents of the package.

**Comment by blink1073** [comment]
Heads up, this PR needs a rebase.

**Comment by pablolmiranda** [comment]
@blink1073 it does matter. The `npm pack` command will not pack the package dependencies.
The later `yarn install` command will try to query the dependencies, and if it is not present on the `https://registry.yarnpkg.com`, it will fail the build.

**Comment by blink1073** [comment]
I see, I did not realize that was the behavior of yarn pack. O don't think we want to suddenly pack all of the dependencies without more discussion.  See https://github.com/jupyterlab/jupyterlab/issues/2065

**Comment by pablolmiranda** [comment]
In this case, we have two options:
 - Force `npm` and `yarn` to use the same registry
 - Add an additional flag `yarn-registry` to the subcommand

**Comment by blink1073** [comment]
I don't see why we need an npm registry at all.  npm pack is only dealing with the local assets, or am I missing something else?

**Comment by blink1073** [comment]
Hi @pablolmiranda, sorry if my last comment wasn't clear.  I meant that we shouldn't need an npm registry for the `npm pack` command itself.  Do you want to finish this PR?  If not, I can take it up.

**Comment by blink1073** [comment]
Note that yarn has deprecated https://registry.yarnpkg.org in favor of https://registry.npmjs.org: https://github.com/yarnpkg/yarn/issues/5891.

**Comment by blink1073** [comment]
(note there are a few merge conflicts now)

**Comment by pablolmiranda** [comment]
Hey @blink1073, if `yarn` registry is now deprecated, I don't think we need this PR.
`yarn` and `npm` will honor the `npm_config_npm_registry` environment config over any default the project has right now. Take a look at line 37963 of the [yarn.js](https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/staging/yarn.js) file.
So to install a private extension you will need to do:
        $ npm_config_npm_registry=<non default registry> jupyter labextension install <extension name>

Let me know your thoughts.

**Comment by blink1073** [comment]
@vidartf, what do you think of recommending `NPM_CONFIG_REGISTRY` as a soln to #4149?  As @pablolmiranda, yarn will pick that up and use it.

**Comment by blink1073** [comment]
Actually, I'm not sure whether yarn is actually doing that, based on 
https://github.com/yarnpkg/yarn/issues/2091
https://github.com/lerna/lerna/issues/1560#issuecomment-412572585

**Comment by vidartf** [comment]
Given that we call into npm/yarn at varying levels of nesting, I think something like an environment variable is the right mechanism to use. However, it does rely on:
- both npm and yarn accepting env vars for configuration of registry, and they override config files)
- env vars correctly propagating to subprocesses (at all levels of nesting)

If those can be satisfied, I would recommend the following logic for all official entry points:
- If the env vars are already set, let them be.
- If not, set the env vars from app configurable traits.
- If no config, leave undefined such that yarn/npm config files can be used.

**Comment by fcollonval** [comment]
This is superseded by #7109. The registry is overwritten by the registry specified in the yarn configuration.

**Pull request closed without merging**
