### PR TITLE
Add command to open find with replace

### PR DESCRIPTION
**Pull request by mlucool**
Adds a `Accel H` command by default which opens the find box with replace expanded. This mirrors how most editors and Microsoft products work.

## Code changes
Refactored the find command to add a find + replace option.

## User-facing changes

New default hotkey added.

### CODE REVIEW

**Comment by jasongrout** [comment]
A quick survey:

* VS Code: Replace is Alt Accel F (Replace in Files is Shift Accel H)
* MS Word: Replace is Shift Accel H

Also:
* Sublime Text: Replace is Alt Accel F
* PyCharm: Replace is Control R
* Atom: Replace in Buffer is Alt Accel F
* macOS text edit: Replace is Alt Accel F

On a mac, at least, it looks like the natural shortcut would be Alt Accel F. Thoughts?

**Comment by jasongrout** [comment]
> Refactored the find command to add a find + replace option.

But first, thanks for doing this!

**Comment by mlucool** [comment]
Interesting. I am using Windows 10 here is what I see:

Wordpad: Ctrl-H
Office Professional Plus 2016: Ctrl-H
Webstorm/PyCharm: Ctrl-R
Google Docs: Ctrl-H
Visual Studio Code: Ctrl-H

**Comment by jasongrout** [comment]
For Google Docs on macOS/Firefox, I see Accel Shift H brings up Find (and replace happens to be possible too from the dialog).

**Comment by jasongrout** [comment]
In 2.0, we'll have the ability to have platform-specific shortcuts. However, there is a philosophical decision - should we be consistent across platforms (like pycharm), or should we be consistent with the platform?

**Comment by mlucool** [comment]
I lean slightly towards platform specific hotkeys when there is a clear standard. This gives users a more "native" experience and matches what both google and msft have done. It lets us avoid using hotkeys that have meaning on one platform (e.g. Accel H to hide on mac).

Where is platform decided? I run my lab on linux but my browser is windows.

**Comment by mlucool** [comment]
I see this was moved to milestone future. Will this not be able to make the 2.0 cut?

**Comment by jasongrout** [comment]
It can still make it into 2.0 since it's not backwards incompatible. I think the biggest blocker at this point might be deciding the default keyboard shortcut. A way around that discussion is to take off the default keyboard shortcut for now (and users would be able to assign a custom keyboard shortcut).

**Comment by mlucool** [comment]
@jasongrout the hotkey has been removed. Please let me know of any other changes you'd like

**Comment by mlucool** [comment]
Ping @jasongrout as I am hoping to for this to make it into 2.0!

**Comment by mlucool** [comment]
> IMHO It's a bit of a mess currently, because the Search provider thing tries to not be aware of react, so you have these two different concepts of state management fighting over each other.

When I first worked on the improved find functionality, I also found this state in two places somewhat hard to grasp.

**Comment by blink1073** [comment]
Thanks!

**Pull request merged**
