### PR TITLE
Sort maintainers list in alphabetical order

### PR DESCRIPTION
**Pull request by lresende**
## References

Sort maintainers list in alphabetical order as described in `Team` section.

### CODE REVIEW

**Comment by afshin** [comment]
It looks like up until Vidar, we were originally sorted alphabetically by last name. Could we stick to that convention instead? I say this as the person whose first name and last name come first alphabetically 😉

**Comment by blink1073** [comment]
Ah, I didn't see @afshin's comment, I agree.

**Comment by lresende** [comment]
Good catch @afshin. I have updated with the proper order based on the last name. 

Having said that, it feels a little strange that we sort based on the last name, but don't use a display like `last name, name`. Anyway, for now, is consistent with the `label` that says it's based on alphabetical order.

**Comment by afshin** [comment]
Cheers!

**Pull request merged**
