### PR TITLE
Keyboard Shortcuts Plugin

### PR DESCRIPTION
**Pull request by roshancvp**
- Trying to add a keyboard shortcuts plugin that auto updates as more shortcuts are added
- See #695

### CODE REVIEW

**Comment by ellisonbg** [comment]
I take it that this is still a work in progress?

**Comment by roshancvp** [comment]
@ellisonbg Ah yes. The previous PR had some merge conflicts I couldn't resolve.

**Comment by ellisonbg** [comment]
One comment, let's make a subclass of `Widget` for this:

```typescript
class KeyboardShortcutViewer extends Widget {
  ...
}
```

And then put all of the virtual DOM stuff in there.

**Comment by sccolbert** [comment]
The benefit of making it a widget subclass is that you can encapsulate state. For example, the keybindings may change at runtime in the future, once we make a keybinding editor plugin. You'll want *this* plugin to re-render itself whenever that happens. So, your widget should connect to the `bindingsChanged`  signal and update itself whenever that signal is fired. Your rendering logic should go in the overridden `protected onUpdateRequest` method of your widget. Then just call `.update()` whenever you need the widget to render.

**Comment by ellisonbg** [comment]
Hi @roshancvp !!!

To help simplify the patterns of working with the virtual DOM APIS, we have created a new `VDomModel` and `VDomWidget` classes that encode the best practices for working with this API. These new APIs are documented here:

https://github.com/jupyter/jupyterlab/blob/master/tutorial/virtualdom.md

Could you update this PR to use these classes? Please let me know if you have any questions!

**Comment by charnpreetsingh185** [comment]
@roshancvp Mind if I pick up on where this left off?

**Comment by blink1073** [comment]
Any word on this @roshancvp, @charnpreetsingh?

**Comment by blink1073** [comment]
Closing this one since it will require a fresh start when implemented.

**Pull request closed without merging**
