### PR TITLE
Update theme-light-extension css path

### PR DESCRIPTION
**Pull request by SimonBiggs**
Fixes #

**Screenshots**
If applicable, add before and after screenshots to help show the issue being fixed, or the appearance of a new feature.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Thanks @SimonBiggs, the test failure seems legitimate. Perhaps the example tests need updating?

**Comment by SimonBiggs** [comment]
Ahh yes sorry. This was a little bit of a "fly by pull request" I should
have stopped to see why the tests failed. I'll have a look at it.

**Comment by saulshanabrook** [comment]
The examples seemed to build correctly for me, see https://github.com/jupyterlab/jupyterlab/pull/5887#issuecomment-457787129.

https://github.com/jupyterlab/jupyterlab/pull/5887 seems to be a superset of this one, so closing this one here.

Thanks for the contribution though!

**Comment by SimonBiggs** [comment]
All good :)

**Pull request closed without merging**
