### PR TITLE
Fix the debug modules model

### PR DESCRIPTION
**Pull request by echarles**
Fixes https://github.com/jupyterlab/jupyterlab/issues/11966

### CODE REVIEW

**Comment by echarles** [comment]
We need to respect the debug modules https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Modules

This PR updates the layout of the returned JSON (reply on the modules request) to respect the spec.

This is paring with the ipykernel PR https://github.com/ipython/ipykernel/pull/848

**Review by fcollonval — CHANGES_REQUESTED** [review]

**Comment by echarles** [comment]
Needed change has been done and CI failures are not related to this PR. This is ready to be merged.

**Review by fcollonval — APPROVED** [review]
Thanks @echarles

**Comment by echarles** [comment]
@fcollonval 👍

**Pull request merged**
