### PR TITLE
Extensions manager results sections

### LINKED ISSUE #5042: Extension Manager doesn't recognise when an install failed
As it says in the title. In my particular case the install failed with `JavaScript heap out of memory` but in the UI there was no indication of failure and the blue bar kept moving across.

Not sure if that's the case with all install errors or just with the particular one I observed.

### PR DESCRIPTION
**Pull request by vidartf**
- Fixes error handling during install (the await had gotten outside a try/catch block).
- Split extension view into two lists: One section for installed extensions, one for discovery (search results). To lessen registry hits, discovery is initially collapsed, and is not populated until expanded.

Closes #5042. Addresses discussion in #5055.

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks!  Integrity failure: `Please run `jlpm run lint` locally and push changes`

**Comment by vidartf** [comment]
@blink1073 I ran the command and pushed its changes, but the change seems a little weird?

**Comment by blink1073** [comment]
Hmm, yeah, `metapackage` shouldn't be in `dev_mode`

**Comment by vidartf** [comment]
The appveyor failure seems unrelated? Does anybody more familiar with the test suit want to look on the error before kicking it?

**Comment by vidartf** [comment]
lab-extmngr-sections

*For reference: A screenshot of the new sections*

**Comment by ellisonbg** [comment]
@vidartf - thank for working on this. I this this is a pretty solid approach and the design is good.

**Comment by ellisonbg** [comment]
@vidartf are you ok with this going in the next release (0.35)?

**Comment by vidartf** [comment]
I don't have any preference for which release it goes into. I have a few other improvements to the extension manager in the pipeline though (cf the various issues about it).

**Comment by blink1073** [comment]
Yep, thanks!

**Pull request merged**
