### PR TITLE
Debugger keyboard shortcuts

### PR DESCRIPTION
**Pull request by mnowacki-b**
## References
Issue: https://github.com/jupyterlab/jupyterlab/issues/9113

## Code changes

Adding keyboard shortcuts to `main.json` schema

### CODE REVIEW

**Comment by jtpio** [comment]
Nice, thanks @mnowacki-b :+1: 

Anyone who wants to try the keybindings can:

- click on the Binder link above
- install xeus python with `pip install xeus-python` in a terminal
- reload the page

**Comment by jasongrout** [comment]
Is this for 3.0?

**Comment by mnowacki-b** [comment]
@jasongrout 
It does not have to be. This PR was created to give the community a chance to try out the shortcuts to see if they work for everyone.

**Comment by jtpio** [comment]
Thanks @mnowacki-b, adding to the 3.1 milestone so it's on the list of things to look at after the 3.0 release :+1:

**Review by jtpio — APPROVED** [review]
Thanks, this looks like a good set of keyboard shortcuts!

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/shortcuts-for-stepping-through-break-points-in-debugger/9559/2

**Pull request merged**
