### PR TITLE
Build Vega bundles separately from other code

### LINKED ISSUE #6709: rc0: Bundled vega5 extension uses the wrong Vega-Lite version
It should be Vega-Lite 3.3, but it is Vega-Lite 2.7

To reproduce in a clean environment:
```
$ pip install --pre juptyterlab altair vega_datasets
$ jupyter lab
```
Open a new notebook and run
```python
import altair as alt

# load a simple dataset as a pandas DataFrame
from vega_datasets import data
cars = data.cars()

alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
).interactive()
```
Open the browser console and observe the warning:
```
The input spec uses vega-lite v3.3.0, but the current version of Vega-Lite is 2.7.0.
```

### PR DESCRIPTION
**Pull request by saulshanabrook**
## References

This fixes #6709, and is a follow up to #6572.
## Code changes

 It separates building
vega assets from the rest of our package management. That way, we can
avoid any hoisting issues that we were seeing (possibly from https://github.com/yarnpkg/yarn/issues/5520).
## User-facing changes

Fixes displaying vega lite 3

To test this, you can try this notebook which should render
both versions without errors:

https://gist.github.com/saulshanabrook/97c28550ab12e684adc3c325038537ce

### CODE REVIEW

**Comment by blink1073** [comment]
Did you mean to check in those two lock files?

**Comment by saulshanabrook** [comment]
Yeah I did, I figure it makes the builds more reproducible?

**Comment by blink1073** [comment]
Fair enough, this LGTM!

**Comment by jakevdp** [comment]
Thanks!

**Pull request merged**
