### PR TITLE
Update actions.spec.ts

### PR DESCRIPTION
**Pull request by kamalika0363**

### CODE REVIEW

**Comment by fcollonval** [comment]
@doesnots would you mind providing some background for this PR?

**Comment by fcollonval** [comment]
Thanks for reaching out

The file you are modifying is a test. So it will not have any impact on the software itself. Would you mind pointing or opening an issue with the problem you are facing (adding some small videos or screenshots would help a lot).

**Comment by doesnots** [comment]
@fcollonval thanks for pointing that out I guess I mishandled the files. I was trying to solve this issue https://github.com/jupyterlab/jupyterlab/issues/14299#issue-1648146481 
I'll try to get the solution. _

**Comment by fcollonval** [comment]
@doesnots I would suggest you ask for pointers on the issue.

**Comment by krassowski** [comment]
@doesnots what do you think about switching this PR to draft while you look further into a solution?

**Comment by krassowski** [comment]
It has been a year since last comment - I will close this PR, but please reopen if you get to finishing it.

**Pull request closed without merging**
