### PR TITLE
Use `maintainer-tools` base setup action

### PR DESCRIPTION
**Pull request by jtpio**
## References

Similar to https://github.com/jupyter-server/jupyter_server/pull/616

## Code changes

This removes a lot of boilerplate GitHub Action setup, which is now available as a proper action in the `maintainer-tools` repo: 

https://github.com/jupyterlab/maintainer-tools/blob/main/.github/actions/base-setup/action.yml

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio

**Comment by fcollonval** [comment]
Failure is on benchmark publication => safe to ignore.

**Comment by jtpio** [comment]
@meeseeksdev please backport to 3.3.x

**Comment by jtpio** [comment]
@meeseeksdev please backport to 3.2.x

**Pull request merged**
