### PR TITLE
WIP: Stop associated kernel when closing widget tab

### LINKED ISSUE #5241: Feature request: Closing a tab should shut down the kernel session
This is related to #4339  #5240 

At https://CognitiveClass.ai, we use JupyterLab to deliver course labs for our learners. Many of them end up with a lot of idle kernel sessions, possibly because they assume that closing a notebook tab is enough to end a kernel session. This causes out-of-memory issues and crashes for the learners.

To improve usability, it would be great if JupyterLab could be configured to automatically shut down the kernel session whenever a user closes the notebook tab associated with that kernel session.

### PR DESCRIPTION
**Pull request by fcollonval**
Fixes #5241

### CODE REVIEW

**Comment by fcollonval** [comment]
@saulshanabrook and @jasongrout 

I implemented a first version for closing the kernel associated with the tab (notebook or console). But it raises some questions:

- I decided to use the `connections` attribute of kernel model (see [Kernel REST API](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/api/api.yaml#/kernels/get_api_kernels__kernel_id_)). To determine if there are more than one connections on the current kernel. What do you think?
- If I understand the REST API right, this attribute is optional. Currently I decided to return `undefined` instead of a boolean status in such case. I'm not sure this is a good way to handle that particular case.
- I'm facing a strange behavior. If I close a notebook or console without closing the kernel and if I reopen the widget through the running tab, the kernel shutdown dialog is not prompted as the kernel connections number has been incremented. Moreover, looking at the `SessionManager`, once the notebook or the console is reopened, the `_sessions` `Set` contains one more `DefaultSession` identical to the existing one as it points to the same kernel and the same file. Is is a wanted behavior? Or is the JS `Set` not acting as a python `set`?
- The code interacting with the user is implemented in `apputils\ClientSession` as it seems the best place to bring dialog up. But that brings me trouble on where to store permanently the user choice settings for the kernel shutdown behavior - in which `schema` should it appears? Should it be separated for console and notebook?

**Comment by saulshanabrook** [comment]
@fcollonval Just to give you a heads up, Jason has been working on a large refactor of how kernels are managed internally: https://github.com/jupyterlab/jupyterlab/pull/4724

Last we talked, we were putting that refactor on the back burner until after the next release, but it might affect your work here. In which case, it might make more sense to pick this back up after that is merged.

But @jasongrout will know more in detail.

**Comment by ellisonbg** [comment]
for 1.0, what about a setting (default to current behavior) for auto-stopping kernels? At least then a user could go into settings and change it?

**Comment by ellisonbg** [comment]
And we could put a checkbox UI at the top of the relevant Running sections to make it easy for a user to toggle this

**Comment by goanpeca** [comment]
Hi @fcollonval is this PR still valid :) ?

**Comment by fcollonval** [comment]
Thanks for the ping. Let's close it. There is still something to do for the console of I remember correctly. But this is probably no more relevant.

**Pull request closed without merging**
