### PR TITLE
Fix handling of linked extensions

### LINKED ISSUE #6738: Better handling of linked packages
@SylvainCorlay reported this while working on the ipywidgets upgrade.  I'm going to come up with a repro, but the general idea is:

- make an extension that depends on a published library
- check out that library locally
- bump the version number 
- run jupyter labextension link

- change directories back to the extension 
- run jupyter labextension link

At this point, jupyter lab complains that it cannot find a published version of the linked dependency.

### PR DESCRIPTION
**Pull request by blink1073**
## References
Fixes #6738 

## Code changes
Uses `resolutions` for linked extensions and packages, so they do not need to be published to `npm`.  Also cleans up the handling of the creation of the packages in `staging/linked_packages`, which was sometimes resulting in the file not being populated there.

## User-facing changes
None

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by lresende** [comment]
@ajbozarth

**Comment by jasongrout** [comment]
Looks like it should work to me. Thanks!

**Comment by saulshanabrook** [comment]
cc @kgryte this should help with our linked extensions issue we were having in datastore and remove need for verdaccio

**Comment by blink1073** [comment]
@meeseeksdev backport to 1.x

**Pull request merged**
