### PR TITLE
Deleted Cells Metadata

### PR DESCRIPTION
**Pull request by richagadgil**
Added 'deleted cells' list to Notebook Model, keeps track of deleted cells since notebook last run with the help of NotebookActions @ellisonbg

### CODE REVIEW

**Comment by jasongrout** [comment]
I think I'm missing some context for why this is needed. What's the use case that we are solving here?

**Comment by richagadgil** [comment]
The list of deleted cells would help the reactive kernel know when a cell is allowed to redefine variables, or else cells could not redefine variables created in other cells even after the originals had been deleted.

**Comment by ellisonbg** [comment]
To elaborate a bit more. In our design work on a reactive kernel, we worked really hard to find the minimal set of changes to a Jupyter frontend that would be required to support reactive kernels. We are pretty confident we got it down to these two requirements:

* Cells have unique and persistent ids that are sent along with the kernel execute requests.
* Kernels can somehow figure out when cell have been deleted each time new code is run.

The exact and full reasons that these two things are required are a bit subtle. More than willing to go into it further, but describing it here would require more text than I have time for right now...

**Comment by blink1073** [comment]
Needs a `jlpm integrity` and commit.

**Comment by richagadgil** [comment]
Running `jlpm run integrity` did not change my git status -

**Comment by blink1073** [comment]
Thanks!  Note: we now run `integrity` as part of the commit hook (and it hopefully actually works).

**Pull request merged**
