### PR TITLE
Add page option `copyAbsolutePath` enabling to copy absolute path

### PR DESCRIPTION
**Pull request by pauky**
## References
Fixes https://github.com/jupyterlab/jupyterlab/issues/9485
Relates jupyterlab_server https://github.com/jupyterlab/jupyterlab_server/pull/405

## Code changes
add page option for copy absolute path, which can replace copy path that is relative.

## User-facing changes
None

## Backwards-incompatible changes
Obtain absolute paths instead of relative paths when copying paths in filebrowser.

### CODE REVIEW

**Review by fcollonval — APPROVED** [review]
Thanks @pauky 

Did you get the chance to test it locally?

**Comment by fcollonval** [comment]
> CI failure are not related

**Comment by fcollonval** [comment]
@pauky would you mind adding a note in the documentation about the new configuration for this at:

https://github.com/jupyterlab/jupyterlab/blob/main/docs/source/user/files.rst#L99

**Comment by pauky** [comment]
> @pauky would you mind adding a note in the documentation about the new configuration for this at:
> 
> https://github.com/jupyterlab/jupyterlab/blob/main/docs/source/user/files.rst#L99

Doc updated, please review it.

**Comment by fcollonval** [comment]
Thanks a lot @pauky for the patience.

> remaining CI failures are not related.

**Pull request merged**
