### PR TITLE
Fix JSON rendering

### PR DESCRIPTION
**Pull request by afshin**
Fixes https://github.com/jupyterlab/jupyterlab/issues/4711

The import of `Highlight` needs to use the import default `require` format. Newer versions of the libraries are also necessary for this fix.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
LGTM, thanks for the quick fix @afshin!

**Comment by jasongrout** [comment]
Ah, thanks!

Does this also work:`import Highlight from 'react-highlighter';`? I think that might be more the accepted convention.

**Comment by jasongrout** [comment]
So it sounds like this was a fallout from turning on the esModuleInterop flag over in #4698. Thanks - that error was really confusing to me.

**Comment by gnestor** [comment]
@afshin Can you explain under what circumstances we need to use `require` vs. original `import` now?

**Comment by jasongrout** [comment]
See #4714 - we should change it to `import Highlight from 'highlight';`

If we have a *real* es6 module (i.e., something that defines the `__esModule` property, then we can do `import * as thing from 'module';` to get the entire module. If we don't have a real es6 module, but instead a commonjs module that exports something else (like a function, etc.), we can't use that syntax because it is assuming that `thing` is a module. In that case, TS does some light magic to take that commonjs export and turn it into what looks like an es6 default export, i.e., so `import thing from 'module';` works.

Short story: use `import thing from 'module';` if you want the default export from an es6 module, *or* if you want the thing exported from a commonjs module. Use `import * as thing from 'module';` if you want the entire es6 module from an es6 module.

**Comment by jasongrout** [comment]
See "Support for import d from "cjs" form CommonJS modules with --esModuleInterop" from https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html for more information.

**Comment by afshin** [comment]
Cool, that was what was confusing to me: how did this break, because I imagined our versions had not changed. As I worked my way through the error messages, I saw one that said the error originated in a `span` element and that error was what bubbled up where the thing being imported from as `Highlight` turned out to be that modules `defaults` object instead of the constructor function that had been loaded before. So that means that the import never appeared broken and always compiled even after it switched from importing the constructor to importing an object.

**Comment by jasongrout** [comment]
Here is the magic that TS does: 

star import: https://github.com/Microsoft/tslib/blob/a921045169515012bd51cb6153c1eea692229c86/tslib.es6.js#L170

default import: https://github.com/Microsoft/tslib/blob/a921045169515012bd51cb6153c1eea692229c86/tslib.es6.js#L179

**Comment by gnestor** [comment]
Ok, so using the `--esModuleInterop` flag makes imports in Typescript more consistent with Babel and CommonJS? Sounds good to me 👍

I also like that we're using a tsconfigbase.json now 👍

**Pull request merged**
