### PR TITLE
Always refresh codemirror on focus

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by sccolbert** [comment]
What is this fixing?

**Comment by sccolbert** [comment]
Do you have any data on how long the refresh takes in a complicated JLab?

**Comment by blink1073** [comment]
Depends on the length of the text in the editor being focused, I measured 75ms for ~10,000 character lorem ipsum.

**Comment by sccolbert** [comment]
What about if there are a bunch of notebooks on the screen at the same time? We have some serious resize perf issues right now with multiple notebooks on the screen, I want to make sure we know what we're signing up for here.

**Comment by blink1073** [comment]
Having other large content does indeed make it slower.  We are already explicitly refreshing after showing (or when attaching and visible), which is the only [recommended](https://github.com/codemirror/CodeMirror/issues/2469#issuecomment-59429711) time to call `refresh()`.  Closing.

**Pull request closed without merging**
