### PR TITLE
Render placeholder at correct index

### PR DESCRIPTION
**Pull request by echarles**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/10895

## Code changes

Use the first entry in the map of cells to be rendered to define the index. Before, we were using the `_renderedCellsCount` value, which was fine before we took into account the collapsible cells (https://github.com/jupyterlab/jupyterlab/pull/10793)

## User-facing changes

The reproducer mentioned in https://github.com/jupyterlab/jupyterlab/issues/10895 should not fail.

## Backwards-incompatible changes

None.

### CODE REVIEW

**Comment by echarles** [comment]
Undrafting to get the binder link.

**Comment by echarles** [comment]
@krassowski This takes into account the regression introduced with the collapsible headers https://github.com/jupyterlab/jupyterlab/pull/10793 The reproducer on binder does not fail anymore for me. If would be great if you could take a look at it?

https://mybinder.org/v2/gh/datalayer-externals/jupyterlab/fix%2Frender-placeholder-at-correct-index?urlpath=lab-dev

Then we can discuss what would be the next steps to avoid failures with the virtual notebook. I can open a separated issues, but I can already highlight a few points here while we are discussing this fix. The initial idea was to have 2 cell "areas":

- The first one at the top of the notebook which are rendered directly.
- The second one after the first one, which are populated by placeholders, and then lazily renders when the browser is idle.

We were using in the second area an index which has shown to be broken after  https://github.com/jupyterlab/jupyterlab/pull/10793. This PR fixes that.

Still, there is the assumption that during the rendering of the second area, the user will not take actions to change the structure of the notebook. It is fine for him to run an existing cell, write in existing cell, save the notebook, restart the kernel... but I can see an issue if he inserts or deletes a cell, as the position of the cells to be rendered should be changed. We have 2 options to takes this behavior into account:

1. Disallow any structural change to the cells indices while the notebook is not fully rendered... in other words the "toRenderCell" map is empty
2. On insert/delete, update the indices of the "toRenderMap" according to the change, which is possible, but a bit cumbersome to write in code.

**Comment by krassowski** [comment]
I confirm that it does fix #10895 and does not fix https://github.com/jupyterlab/jupyterlab/issues/10840#issuecomment-903130229. I like this fix, it is very straightforward - it actually makes the code easier to understand. Should we add a test of any kind this one? @Doggie52 could we use your reproducer notebook to create a visual regression test for this bug?

> Disallow any structural change to the cells indices while the notebook is not fully rendered... in other words the "toRenderCell" map is empty

In my opinion if we will have a visual cue of loading, this could be an acceptable UX (barely, but acceptable). On the other hand, I am not convinced whether making good visual cues and prohibiting changes from triggering any susceptible code path will be easier than tracking the changes. I mean that a good UX would only prohibit very specific actions and only on a subset of cells: by the time we add the logic to handle all those actions we already covered the same places as we would if we instead implemented the index tracking/rebuilding (which is obviously more difficult in itself, but the extend places in code that need to be touched will not be so much different). Can you raise this tomorrow on the dev meeting (unfortunately I cannot attend it tomorrow)?

**Comment by Doggie52** [comment]
@krassowski I'm OK with sharing my beautiful `a = 1` expressions with the world, yes 😂 

On a serious note, let me know if you need anything further from me!

**Review by krassowski — APPROVED** [review]
LGTM

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.1.x

**Comment by echarles** [comment]
@meeseeksdev please backport to master

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/code-cells-not-rendering-on-jupyter-lab/10597/2

**Pull request merged**
