### PR TITLE
Fix workspace URL while cloning a workspace

### PR DESCRIPTION
**Pull request by aditya211935**
## Code changes
The logic for getting the default workspace while cloning from a default workspace is outdated. Additionally, `workspace.fetch()` requires only workspace's name, and not the base and app url.

These changes ensure that cloning a default workspace or any other workspace works correctly.

### CODE REVIEW

**Comment by aditya211935** [comment]
@jasongrout Any updates?

**Comment by aditya211935** [comment]
@afshin @fcollonval Any updates?

**Comment by aditya211935** [comment]
@jtpio any updates? Do I need to do something else to get it merged?

**Comment by krassowski** [comment]
@aditya211935 thank you for opening this PR. Would you mind explaining in a bit more detail what incorrect behaviour is this PR fixing? Is there an issue from the tracker which would be fixed by merging this PR? It is difficult to review without understanding the associated issue.

**Comment by aditya211935** [comment]
@krassowski Sure. There are two bugs that this PR aims to solve. I'm not aware of any issues created for these bugs.

1.
  a. Steps to reproduce
    - Open a default workspace by visiting `http(s)://<server:port>/<lab-location>/lab`.
    - Open some windows in the default workspace. This will ensure that there are some contents on default workspace.
    - Try to clone the default workspace into a custom workspace by following the instructions from here. https://jupyterlab.readthedocs.io/en/stable/user/urls.html#cloning-workspaces . Basically, do `http(s)://<server:port>/<lab-location>/lab/workspaces/foo?clone`
    - The windows that had been saved in the default workspace are not there.

   b. Video: https://www.loom.com/share/c5e74caa322e40f9abf647a0085733ff

2. 
  a. Steps to reproduce
    - Open a custom workspace by visiting `http(s)://<server:port>/<lab-location>/lab/workspaces/foo`.
    - Same as above, open some files.
    - Try to clone `foo` workspace into `bar` workspace by following the same documentation. 
    - Same thing happens. Foo is not cloned into bar.

  b. Video: https://www.loom.com/share/dd6f8f985e5842de87f505db4205064a

**Comment by krassowski** [comment]
I am indeed able to reproduce the incorrect behaviour in the latest release (3.4.5). There is also a [post on discourse](https://discourse.jupyter.org/t/i-can-not-open-more-than-one-notebook-in-the-same-workspace-with-links-any-longer-in-jl-3/9211) which indicates that workspace cloning was broken in JupyterLab 3 for some time.

@aditya211935 would you mind adding a test case for cloning the default workspace and for cloning a named workspace? It could go into https://github.com/jupyterlab/jupyterlab/blob/master/galata/test/jupyterlab/workspace.test.ts

**Comment by fcollonval** [comment]
@aditya211935 @ameerthehacker 

Could you add the following patch to this PR? It will add integration test for the feature:

```patch
diff --git a/galata/test/jupyterlab/workspace.test.ts b/galata/test/jupyterlab/workspace.test.ts
index f50aea49d2..f7b2f83a0e 100644
--- a/galata/test/jupyterlab/workspace.test.ts
+++ b/galata/test/jupyterlab/workspace.test.ts
@@ -151,4 +151,77 @@ test.describe('Workspace', () => {
 
     await expect(page.menu.getMenuItem(`Tabs>${mdFile}`)).toBeDefined();
   });
+
+  test('should clone the default workspace', async ({ page, tmpPath }) => {
+    // Given
+    await page.goto();
+
+    await page.filebrowser.open(`${tmpPath}/${nbFile}`);
+    await page.filebrowser.open(`${tmpPath}/${mdFile}`);
+    await Promise.all([
+      page.waitForResponse(
+        response =>
+          response.request().method() === 'PUT' &&
+          /api\/workspaces/.test(response.request().url()) &&
+          response.request().postDataJSON().data['terminal:1']
+      ),
+      page.waitForSelector('[role="main"] >> .jp-Terminal'),
+      page.menu.clickMenuItem('File>New>Terminal')
+    ]);
+
+    // When
+    await Promise.all([
+      // Wait for the workspace to be saved
+      page.waitForResponse(
+        response =>
+          response.request().method() === 'PUT' &&
+          /api\/workspaces/.test(response.request().url()) &&
+          response.request().postDataJSON().metadata['id'] === 'foo'
+      ),
+      page.goto('workspaces/foo?clone')
+    ]);
+
+    await expect(page.locator('[role="main"] >> .lm-TabBar-tab')).toHaveCount(
+      3
+    );
+    await expect(page.locator(`[role="main"] >> text=${mdFile}`)).toBeVisible();
+    await expect(page.locator(`[role="main"] >> text=${nbFile}`)).toBeVisible();
+  });
+
+  test('should clone the current workspace', async ({ page, tmpPath }) => {
+    // Given
+    await page.goto('workspaces/foo');
+
+    await page.filebrowser.open(`${tmpPath}/${nbFile}`);
+    await page.filebrowser.open(`${tmpPath}/${mdFile}`);
+    await Promise.all([
+      page.waitForResponse(
+        response =>
+          response.request().method() === 'PUT' &&
+          /api\/workspaces/.test(response.request().url()) &&
+          response.request().postDataJSON().data['terminal:1']
+      ),
+      page.waitForSelector('[role="main"] >> .jp-Terminal'),
+      page.menu.clickMenuItem('File>New>Terminal')
+    ]);
+
+    // When
+    await Promise.all([
+      // Wait for the workspace to be saved
+      page.waitForResponse(
+        response =>
+          response.request().method() === 'PUT' &&
+          /api\/workspaces/.test(response.request().url()) &&
+          response.request().postDataJSON().metadata['id'] === 'bar'
+      ),
+      page.goto('workspaces/bar?clone')
+    ]);
+
+    // Then
+    await expect(page.locator('[role="main"] >> .lm-TabBar-tab')).toHaveCount(
+      3
+    );
+    await expect(page.locator(`[role="main"] >> text=${mdFile}`)).toBeVisible();
+    await expect(page.locator(`[role="main"] >> text=${nbFile}`)).toBeVisible();
+  });
 });
```

**Comment by aditya211935** [comment]
@fcollonval Thanks for the tests, have added them. Apologies for the delay.

**Comment by fcollonval** [comment]
Thanks @aditya211935 

Don't apologies for the delay, we are not that responsive neither.

Would you mind fixing the linter complain:

```diff
diff --git a/galata/test/jupyterlab/workspace.test.ts b/galata/test/jupyterlab/workspace.test.ts
index 0905661..f7b2f83 100644
--- a/galata/test/jupyterlab/workspace.test.ts
+++ b/galata/test/jupyterlab/workspace.test.ts
@@ -155,7 +155,7 @@ test.describe('Workspace', () => {
   test('should clone the default workspace', async ({ page, tmpPath }) => {
     // Given
     await page.goto();
-  
+
     await page.filebrowser.open(`${tmpPath}/${nbFile}`);
     await page.filebrowser.open(`${tmpPath}/${mdFile}`);
     await Promise.all([
@@ -168,7 +168,7 @@ test.describe('Workspace', () => {
       page.waitForSelector('[role="main"] >> .jp-Terminal'),
       page.menu.clickMenuItem('File>New>Terminal')
     ]);
-  
+
     // When
     await Promise.all([
       // Wait for the workspace to be saved
@@ -180,18 +180,18 @@ test.describe('Workspace', () => {
       ),
       page.goto('workspaces/foo?clone')
     ]);
-  
+
     await expect(page.locator('[role="main"] >> .lm-TabBar-tab')).toHaveCount(
       3
     );
     await expect(page.locator(`[role="main"] >> text=${mdFile}`)).toBeVisible();
     await expect(page.locator(`[role="main"] >> text=${nbFile}`)).toBeVisible();
   });
-  
+
   test('should clone the current workspace', async ({ page, tmpPath }) => {
     // Given
     await page.goto('workspaces/foo');
-  
+
     await page.filebrowser.open(`${tmpPath}/${nbFile}`);
     await page.filebrowser.open(`${tmpPath}/${mdFile}`);
     await Promise.all([
@@ -204,7 +204,7 @@ test.describe('Workspace', () => {
       page.waitForSelector('[role="main"] >> .jp-Terminal'),
       page.menu.clickMenuItem('File>New>Terminal')
     ]);
-  
+
     // When
     await Promise.all([
       // Wait for the workspace to be saved
@@ -216,7 +216,7 @@ test.describe('Workspace', () => {
       ),
       page.goto('workspaces/bar?clone')
     ]);
-  
+
     // Then
     await expect(page.locator('[role="main"] >> .lm-TabBar-tab')).toHaveCount(
       3
@@ -224,4 +224,4 @@ test.describe('Workspace', () => {
     await expect(page.locator(`[role="main"] >> text=${mdFile}`)).toBeVisible();
     await expect(page.locator(`[role="main"] >> text=${nbFile}`)).toBeVisible();
   });
-});
\ No newline at end of file
+});
```

**Review by fcollonval — APPROVED** [review]
Thanks @aditya211935

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.4.x

**Pull request merged**
