### PR TITLE
Allow Angular and its templates within JupyterLab extensions

### PR DESCRIPTION
**Pull request by SimonBiggs**
This is my current attempt at making Angular templates work within JupyterLab extensions.

Guided by the Angular webpack documentation (https://angular.io/guide/webpack#modulerules) I have been attempting to make JupyterLab's staging webpack handle Angluar templates.

I have not yet been successful. But this is my progress thus far. [Now working].

This work is being done side by side with the jupyterlab-extension branch of scriptedforms:

https://github.com/SimonBiggs/scriptedforms/tree/jupyterlab-extension

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Heya @blink1073 :)

Is this a pull request that has a chance of getting accepted? Or is this not something that is wanted within JupyterLab?

**Comment by SimonBiggs** [comment]
Woo hoo! :) :) Okay, so ScriptedForms is now loading up as an extension. Wow :). Yeee haaaa. 'html-loader' was the issue, I just had to tell it to only run for .component.html files. That did the trick.

**Comment by SimonBiggs** [comment]
Ahh :) JupyterLab is beautiful :)

image

**Comment by SimonBiggs** [comment]
Fixes #4336

**Comment by ian-r-rose** [comment]
Scripted forms is looking *really* nice.

**Comment by SimonBiggs** [comment]
Heya @blink1073, when you get the chance your opinion on the appropriateness of this pull request would be greatly appreciated.

**Comment by blink1073** [comment]
Thanks for diving in to this, @SimonBiggs!  Our stance to date is that we support a small set of inputs and an extension should be distributed in in a form that can be consumed.  Is it possible in this case to pretransform the files?

**Comment by SimonBiggs** [comment]
Another thought, I am already hosting the transformed JavaScript files at `{baseurl}/scriptedforms/static/scriptedforms.js`

I tried a few ways to call those javascript files from within JupyterLab but to no avail. So that I am not getting users  to have two copies of all the js might it be worth me trying further down that path?

**Comment by SimonBiggs** [comment]
It looks like it is saying the "module" isn't within the "webpack modules" object:

image

In reality it is complaining that it can't find the 'polyfills' file, which is the first file import that it comes across in the first file it is hitting:

https://github.com/SimonBiggs/scriptedforms/blob/master/scriptedforms/src/main.ts#L32

**Comment by SimonBiggs** [comment]
I also attempted to collapse all of my files into a single main.js to see if that was the confusion. But then when I run `jupyter labextension install .` I get errors looking like the following:

```
<--- Last few GCs --->

[10719:0x3356000]   167122 ms: Mark-sweep 1423.4 (1489.3) -> 1423.3 (1492.8) MB, 709.6 / 0.0 ms  allocation failure GC in old space requested
[10719:0x3356000]   167836 ms: Mark-sweep 1423.3 (1492.8) -> 1423.3 (1461.8) MB, 714.1 / 0.0 ms  last resort GC in old space requested
[10719:0x3356000]   168551 ms: Mark-sweep 1423.3 (1461.8) -> 1423.3 (1461.8) MB, 714.5 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3f5b043a57c1 <JSObject>
    0: builtin exit frame: stringify(this=0x3f5b04388ff1 <Object map = 0x13a9ecc82ba1>,0x18a5950822d1 <undefined>,0x18a5950822d1 <undefined>,0x7cbb3056c39 <Object map = 0x38c4ecfc9f29>)

    1: arguments adaptor frame: 1->3
    2: toString [0x18a5950822d1 <undefined>:13814] [bytecode=0x19af76f03729 offset=28](this=0x4132c139fd9 <Object map = 0x13a9eccd1461>)
    3: minify [0x18a5950822d1 <undefi...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/home/simon/.nvm/versions/node/v8.10.0/bin/node]
 2: 0x11e73ec [/home/simon/.nvm/versions/node/v8.10.0/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/home/simon/.nvm/versions/node/v8.10.0/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/home/simon/.nvm/versions/node/v8.10.0/bin/node]
 5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/home/simon/.nvm/versions/node/v8.10.0/bin/node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/home/simon/.nvm/versions/node/v8.10.0/bin/node]
 7: v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [/home/simon/.nvm/versions/node/v8.10.0/bin/node]
 8: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/home/simon/.nvm/versions/node/v8.10.0/bin/node]
 9: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/home/simon/.nvm/versions/node/v8.10.0/bin/node]
10: v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/home/simon/.nvm/versions/node/v8.10.0/bin/node]
11: v8::internal::Builtin_JsonStringify(int, v8::internal::Object**, v8::internal::Isolate*) [/home/simon/.nvm/versions/node/v8.10.0/bin/node]
12: 0x34ee8558697d
```

**Comment by SimonBiggs** [comment]
...I'd be really keen for this pull request to be accepted... this attempting to get webpacked js pulled into JupyterLab is quite difficult :/ :(

**Comment by SimonBiggs** [comment]
As another point... when my javascript files are minified and just the jupyterlab packages are common chunked out, they take up 2 MB (minified). Not bad for just my extension but would it be an issue if every extension heavily dependent on JupyterLab packages brings their own recopy of JL?

**Comment by SimonBiggs** [comment]
Hi @jasongrout, I've seen a little window into all the working you've been doing in getting this release out the door :). Thank you for all your hard work :).

Feel free to not reply to this until after you have more time :).

Just so you get a feel of what I am aiming to do with ScriptedForms. I plan for creators of scripted forms to open up JupyterLab, create their forms, and debug them using the tooling provided within JupyterLab. An example of this debugging process might be to open up a console attached to the form and see the console display code as it is run.

Once they have created the form they will deploy their form as a standalone server extension apart from JupyterLab.

Ideally the same code for the standalone server extension can be used for the JupyterLab extension just with a few flags being triggered to make the code run a little differently.

Unfortunately I have no idea how I could transpile angular html template files. If I inlined all of the html within the js files that might work, but it is far from ideal.

I also completely understand your point 3.

In hindsight I have made this difficult by using Angular. ... But I have found extension building with Angular to be quite nice. :).

**Comment by saulshanabrook** [comment]
> Woo hoo! :) :) Okay, so ScriptedForms is now loading up as an extension. Wow :). Yeee haaaa. 'html-loader' was the issue, I just had to tell it to only run for .component.html files. That did the trick.


@SimonBiggs  I want to try to setup this locally on my machine. What steps should I take to install the scriptedforms jupyterlab extension? I am curious what it would look like to [use webpack inline loader specifications, instead of adding more loaders to jupyterlab](https://github.com/jupyterlab/jupyterlab-monaco/pull/3).

**Comment by SimonBiggs** [comment]
@saulshanabrook thank you so much for taking a look at this. Gives a few mins and I'll pull together clear steps.

**Comment by SimonBiggs** [comment]
```bash
git clone https://github.com/SimonBiggs/jupyterlab.git
cd jupyterlab
git checkout allow-angular-templates
pip install -e .
jlpm install

cd ../
git clone https://github.com/SimonBiggs/scriptedforms.git
cd scriptedforms/scriptedforms
jlpm
jlpm build
jlpm pip:install
jupyter labextension install .
```

**Comment by SimonBiggs** [comment]
Then copy the following file to your documents directory:

https://raw.githubusercontent.com/SimonBiggs/scriptedforms/master/example/example/detailed.md

and start up jupyter lab in the same directory as that markdown file. Right click on the file and go open with ScriptedForms.

**Comment by saulshanabrook** [comment]
@SimonBiggs Thank you! I am getting an issue when installing as a labextension

```bash
$ jupyter labextension install .
> /usr/local/bin/npm pack /Users/saul/projects/scriptedforms/scriptedforms
simonbiggs-scriptedforms-0.9.1.tgz

Errored, use --debug for full output:
ValueError: "/Users/saul/projects/scriptedforms/scriptedforms" is not a valid extension:
Missing extension module "src/main.ts.js"
```

**Comment by SimonBiggs** [comment]
See https://github.com/jupyterlab/jupyterlab/pull/4334/files#diff-f889c27ebc01f0305bbef39cfd65085bR1340

**Comment by saulshanabrook** [comment]
@SimonBiggs Ah, thanks.

**Comment by SimonBiggs** [comment]
@saulshanabrook any luck?

**Comment by saulshanabrook** [comment]
Yep! I am trying it without modifying jupyterlab to see how far that can get us.

Modify `package.json` with:

```json
  "main": "out-tsc/app/main.js",

  "files": [
    "out-tsc/app/"
  ],
```

```bash
yarn add --dev  copyfiles

# remove from dev dependencies and add to regular 
# so jupyterlab build can pick them up
yarn remove sass-loader node-sass
yarn add sass-loader node-sass

npx tsc -p src/tsconfig.app.json

npx copyfiles -u 1 './src/**/*.css' './src/**/*.scss' ./out-tsc/app/

jupyter labextension install --debug .
```

Gets me to here:

screen shot 2018-04-20 at 10 53 48 am

My current understanding of the Jupyterlab build system is that ideally everything it ingests should be [nice imports/requires](https://webpack.js.org/api/module-methods/). At this point, it seems like what's holding us back is the inability to include `variable-table.component.html` in the build.

I am gonna look into maybe building the template html into the build or including the url, reading https://medium.com/@frosty/angularjs-template-vs-templateurl-cdde055b7907

**Comment by SimonBiggs** [comment]
Careful, Angular != AngularJS

Best place to start is probably here:
https://angular.io/guide/webpack

And something like this looks promising:
https://github.com/rails/webpacker/issues/394#issuecomment-301920695

**Comment by saulshanabrook** [comment]
Oh that's how they differentiate between pre v2.0? Good to know, thanks!

**Comment by saulshanabrook** [comment]
I switched the templates to look like:


```
  templateUrl: require('file-loader!./landing-page.component.html')
```

and now I am just getting this compilation error. 
screen shot 2018-04-20 at 11 05 37 am

Which is reaching the edge of my understanding about angular compilation.

**Comment by SimonBiggs** [comment]
Yeah... :( everything I try seems to end up at a dead end. ...except this pull request...

**Comment by SimonBiggs** [comment]
Also if you run jupyter lab in --watch mode it doesn't minify the js. The js console errors end up being more informative that way...

**Comment by SimonBiggs** [comment]
what about !html-loader instead of file-loader?

**Comment by SimonBiggs** [comment]
@saulshanabrook I'm trying the following to pull in the sass:

import 'style-loader!css-loader!sass-loader!./theme.scss';

It's getting the following error though:

```
ERROR in ./~/sass-loader/lib/loader.js!./~/@simonbiggs/scriptedforms/jlab-build/vendors/theme.scss
Module parse failed: /home/simon/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/sass-loader/lib/loader.js!/home/simon/.pyenv/versions/3.6.4/share/jupyter/lab/staging/node_modules/@simonbiggs/scriptedforms/jlab-build/vendors/theme.scss Unexpected token (12:0)
You may need an appropriate loader to handle this file type.
| /* stylelint-disable material/no-prefixes */
| /* stylelint-enable */
| .mat-elevation-z0 {
|   box-shadow: 0px 0px 0px 0px rgba(0, 0, 0, 0.2), 0px 0px 0px 0px rgba(0, 0, 0, 0.14), 0px 0px 0px 0px rgba(0, 0, 0, 0.12); }
| 
 @ ./~/@simonbiggs/scriptedforms/jlab-build/vendors/angular-styles.js 3:0-35
 @ ./~/@simonbiggs/scriptedforms/jlab-build/main.js
 @ ./build/index.out.js
 @ multi whatwg-fetch ./build/index.out.js

```

**Comment by saulshanabrook** [comment]
@SimonBiggs Do you have `sass-loader` added as a regular dependency instead of a dev dependency? It needs to be, so that jupyterlab will pull it in when building.

I pushed my changed here: https://github.com/saulshanabrook/scriptedforms/commit/0d7097119b65dace06d698101342933cf02987d2

**Comment by saulshanabrook** [comment]
You might have to do `import * as htmlTemplate from 'html-loader!./variable-table.component.html';`

and change the declaration to 

```
declare module "html-loader!*.component.html" {
  const content: string;
  export = content;
}
```

**Comment by SimonBiggs** [comment]
It's working!

https://github.com/SimonBiggs/scriptedforms/compare/inline-webpack

**Comment by SimonBiggs** [comment]
Thanks @saulshanabrook !!! :)

It's not such a bad solution either. A good compromise. ... it was painful to get there... but it should get better as the tricks are learnt...

**Comment by saulshanabrook** [comment]
@SimonBiggs Wow! That's a surprise. Once maybe you have it all working, we could add some documentation on our end on how to include an angular project.

**Comment by SimonBiggs** [comment]
Yup, will do. Where best should the documentation go? Would it be worth
having a minimal example?

**Comment by saulshanabrook** [comment]
@SimonBiggs  I opened #4438 for this.

**Pull request closed without merging**
