### PR TITLE
Add ability to include third party extension in dev mode

### PR DESCRIPTION
**Pull request by saulshanabrook**
This PR adds the ability to run dev mode with third party extensions enabled.

Currently the only way to do this is with add-sibling which really messes up the working directory and also requires you to build the other extension with JuptyerLab itself. This causes all sorts of problems if the extensions are not written in exactly the same ES6/webpack way that JupyterLab itself is.

This PR adds the option to instead just install extensions as normal npm packages and require them to bring them in. I haven't tried it yet for local extensions, I mainly wanted this to test published extensions against master and not have the ability to edit them. 

## References

Possibly fixes https://github.com/jupyterlab/jupyterlab/issues/6911  and https://github.com/jupyterlab/jupyterlab/pull/7179.

Built to let me test plotly widgets against core for benchmarking in this PR https://github.com/jupyterlab/jupyterlab/pull/8020 to help address long load times for notebooks https://github.com/jupyterlab/jupyterlab/issues/4292

## Code changes

Adds a new key `externalExtensions` to the `jupyterlab` object in the `dev_mode/package.json`. By adding package to version mappings here you can make JupyterLab require them in dev mode and add them to the `dependencies`.

## User-facing changes

None.

## Backwards-incompatible changes

None.

### CODE REVIEW

**Comment by saulshanabrook** [comment]
Note I tested this locally with `@jupyter-widgets/jupyterlab-manager` and was able to run ipywidgets against master.

**Comment by echarles** [comment]
Does this support linked extensions?

**Comment by saulshanabrook** [comment]
@echarles no i dont believe so at the moment.

**Comment by saulshanabrook** [comment]
or maybe? haven't tried it.

**Comment by echarles** [comment]
This was not clear to me looking at the diff, hence my question :) I have looked sometime ago a way to develop aswell the core and an extension in watch mode, so I hope this can do the job.

**Comment by blink1073** [comment]
I think it would have to be a path to a tarball for local extensions for the same reason we currently do that in app mode: webpack would otherwise the local extensions' directory for dependencies.

**Comment by saulshanabrook** [comment]
This isn't backwards incompatible, so I think could be merged ASAP, barring objections. It's harder to work off of a bunch of in progress PRs together then if they just get merged into master.

**Comment by saulshanabrook** [comment]
I have been working around it for now, but I am confused what the values for the `extensions` and `mimeExtensions` in the `jupyterlab` key in the `dev_mode/package.json` are for:
https://github.com/jupyterlab/jupyterlab/blob/0731248dfdfba497d5a156c38b6e39b68bc8e790/dev_mode/package.json#L193

They are all empty! And the only place I see them being used is in the template to generate the imports:
https://github.com/jupyterlab/jupyterlab/blob/0731248dfdfba497d5a156c38b6e39b68bc8e790/dev_mode/index.js#L64

So the imports are generated with an extra slash on the end `require('@jupyterlab/notebook-extension/`, which seems like maybe it wasn't intended?

**Comment by saulshanabrook** [comment]
I updated this PR to properly copy the schemas for the extensions. I also consolidated the keys to one `externalExtensions`, instead of separating by whether they are mime extensions or not.

**Comment by saulshanabrook** [comment]
Any more feedback on this before we merge? I don't think it's perfect but it allows a new useful way of adding third party extensions to core.

**Comment by blink1073** [comment]
I think we'll need #7813 fixed first so we can get a clean build.

**Comment by blink1073** [comment]
Otherwise, 👍 to merging.

**Comment by saulshanabrook** [comment]
> I think we'll need #7813 fixed first so we can get a clean build.

Sounds good! Is there an issue for that?

**Comment by blink1073** [comment]
Ha, wrong issue, this is the one: https://github.com/jupyterlab/jupyterlab/issues/8244

**Comment by blink1073** [comment]
Docs failures seem legit, it might be from an interaction with other changes to this file:

```
___________ ERROR collecting docs/source/developer/extension_dev.rst ___________
....
E   docutils.utils.SystemMessage: <string>:268: (SEVERE/4) Unexpected section title.
E   
E   },
E   ...
------------------------------- Captured stderr --------------------------------
<string>:15: (ERROR/3) Unknown interpreted text role "ref".
<string>:29: (ERROR/3) Unknown interpreted text role "ref".
<string>:32: (ERROR/3) Unknown interpreted text role "ref".
<string>:256: (WARNING/2) Definition list ends without a blank line; unexpected unindent.
<string>:266: (ERROR/3) Unexpected indentation.
<string>:267: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
<string>:268: (SEVERE/4) Unexpected section title.

},
...
```

**Comment by saulshanabrook** [comment]
Thanks @blink1073, let's give this a go. Gotta love RST formatting!

**Comment by blink1073** [comment]
More docs fun:

```
/home/runner/work/jupyterlab/jupyterlab/docs/source/developer/extension_dev.rst:256: WARNING: Definition list ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
```

I'd also recommend a rebase to clean up the CI checks.

**Comment by blink1073** [comment]
Docs build is still failing (I'm on my phone so I don't have the traceback)

**Comment by saulshanabrook** [comment]
Sorry there was an extra leading space! Everything seems to be passing now :)

**Comment by blink1073** [comment]
Great, nice work!

**Pull request merged**
