### PR TITLE
Contain the tabs within the tabbar (do not use translation transform)

### PR DESCRIPTION
**Pull request by krassowski**
## References

This is a prerequisite for full adoption of `contain: strict` https://github.com/jupyterlab/lumino/issues/504.

Briefly, the current tab was using `transform: translateY()` style exceeding its box which means that we could not contain painting for it (i.e. it would have no effect).

## Code changes

- Re-implement the bottom border using opt-in approach - elements which need bottom border get it in `::after` pseudo-element rather than existing opt-out approach (element which should not have it is resized up and shifted down to cover the common border).
- Remove unnecessary CSS rule (`.lm-TabBar-tab.lm-mod-current:hover`)

## User-facing changes

Removes the jitter of the tab title when switching the active tab.

Old (see how "Launcher" title moves down upon activation):

old-tabbar

New (see no title movement upon activation):

new-tabbar

## Backwards-incompatible changes

I _think_ it can be safely backported, but would appreciate a second opinion.

### CODE REVIEW

**Comment by krassowski** [comment]
please update snapshots

**Comment by krassowski** [comment]
please update snapshots

**Comment by jtpio** [comment]
Kicking CI (https://github.com/jupyterlab/jupyterlab/issues/13505).

**Comment by jtpio** [comment]
> I _think_ it can be safely backported, but would appreciate a second opinion.

Looks like it should indeed be fine at first glance. Adding to the 3.6 milestone for consideration.

**Review by fcollonval — APPROVED** [review]
Thanks @krassowski

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.6.x

**Pull request merged**
