### PR TITLE
[WIP] Collaborative editing using Yjs

### PR DESCRIPTION
**Pull request by dmonad**
This PR implements collaborative editing in JupyterLab using the [Yjs shared editing framework](https://github.com/yjs/yjs). Yjs is an open-source framework to build collaborative applications using data structures (CRDTs) that sync automatically. 

Try it out now: [Binder](https://mybinder.org/v2/gh/QuantStack/jupyterlab/yjupyter?urlpath=lab-dev)

jupyter shared-editing demo

### Scope

The aim of this PR is to switch to Yjs as a data model for notebooks and text files. The ability to share content between users will be provided by separate plugins that connect the Yjs data model with other peers. Currently, this PR also implements a basic shared-editing server that synchronizes clients that open the same file. We will outsource this shared-editing server to a separate plugin.

### Status

There are a couple of known UI regressions and we probably have to do some refactoring. We are working on it. But this PR is already usable.

Known bugs:
* It is not possible to rename files
* Since outputs are shared, it is possible to display HTML script tags in the browsers of other users.
* Tests are broken
* Issues will be tracked here: https://github.com/QuantStack/jupyterlab/issues

### Quick installation guide

```sh
# optional: use conda
conda create -n yjupyter
conda activate yjupyter
conda install jupyterlab

# clone our branch
git clone git@github.com:QuantStack/jupyterlab.git --branch yjupyter
cd jupyterlab

# installation steps as usual for Jupyter development
pip install -e .
jlpm
jlpm build
jupyter lab --dev-mode 
```

## References

* Ticket to track Real Time Collaboration: https://github.com/jupyterlab/jupyterlab/issues/5382
* Using Lumino datastore by @saulshanabrook: https://github.com/jupyterlab/jupyterlab/pull/6871
* Jupyter Real Time Collaboration monorepo: https://github.com/jupyterlab/rtc

## Code changes

Currently, Jupyter Notebooks and several other components use ModelDB to model the notebooks' internal representation. It provides observable data structures that fire events when data is added or removed.

This PR replaces the IModel data model with Yjs' [shared types](https://docs.yjs.dev/api/shared-types) that provide the same functionality. Yjs is meant for building collaborative applications and provides many helpful, well-tested abstractions that reduce the complexity of this codebase significantly. For example, we removed several hundred lines of code that keep ModelDB in-sync with the CodeMirror editor. Instead, we use the [y-codemirror](https://github.com/yjs/y-codemirror) editor binding that keeps the editor in-sync with Yjs' data structures.

We are aware that this will break existing plugins that rely on the IModelDB interface. We want to make this upgrade as easy as possible and keep existing APIs (e.g. the event emitters) whenever possible.

We also restructured how the internal data is represented using the observable data structures. Before, we had a complex mixture of key-value stores and observable arrays based on ModelDB. With Yjs, we produced a nearly one-on-one mapping from a Yjs document to the `.ipynb` JSON format. `ydoc.toJSON()` is an existing method that converts a Yjs document to a JSON representation that is very similar to the `.ipynb` JSON format. Developers that are familiar with the JSON format will easily know how to work with the Yjs data model.

We also want to make it easier for plugins to provide additional features based on Yjs as a data model. A separate plugin could provide commenting features based on annotations on the Yjs document. Annotations are modeled using ["Relative Positions"](https://docs.yjs.dev/api/relative-positions) - a Yjs concept that makes it possible to assign information to a range of text while automatically adjusting for position changes.

Another complex problem that Yjs solves is selective undo/redo. We replaced the existing undo manager with a powerful Yjs-based alternative that enables you to selectively decide which changes you want to be able to undo. Text-modifications to the editor models and cell-insertions are tracked as "undoable", while other changes to the Yjs data model are not tracked (e.g. modifications on metadata and the computed output). The use-case for the selective undo manager is that you want to prevent users from undoing remote changes created by other users. 

ezgif-2-a0ba6221845f

Currently, this PR also implements a websocket server (in Python) to sync connected clients, and a hook to connect the Yjs data model to the server. We still use http-requests to save the notebook-content to the server. Concurrent access is prevented by acquiring a "lock" from the server before saving or initializing a resource.

We will outsource the server-implementation and the hook to a separate plugin to allow third-parties to implement their custom server. Applications that use Jupyter notebooks, like JupyterHub, will be able to add custom authorization and access control to the server. 

Yjs is network agnostic and doesn't need a server to perform conflict resolution. The implemented websocket server (79 lines of code) only forwards messages to other clients and implements a little custom logic (e.g. room-management and locking). This implementation is fully functional and yields little overhead. However, we want the Yjs data model to be accessible in Python as well. Next, we will be working on a Rust port of Yjs, including Python bindings, that will allow the server to parse the shared document and perform modifications.

### Next steps

- [ ] Fix the remaining bugs
- [ ] Possibly outsource the server to a separate plugin and provide extension-points to provide custom shared-editing servers. 
- [ ] Discuss problems that arise when implementing shared-editing in Jupyter (e.g. do we want to share output between users? should there be a shared kernel for a shared notebook?)

### CODE REVIEW

**Comment by jasongrout** [comment]
Since this is [WIP] (from the title), can we convert it to a Draft PR?

**Comment by dmonad** [comment]
Sure, of course!

**Comment by fperez** [comment]
Thanks for the great work @dmonad/team, much appreciated!!

I've been playing with it, with actual remote colleagues (not just dual-browsers) and it's performing very well so far. I wanted to note an issue that happened to me, though I'm not sure exactly how to reproduce it, but I saw it happen twice: when a new user joined, we saw clobbering of both a text (md) file and a notebook. Both got reset to a blank slate, erasing existing content that was there.  If I find out how to replicate I'll post more, but I figured I'd mention it...

Also, I noticed the console doesn't open.  Not just that RTC doesn't work, but it seems entirely not to start: it opens a blank page but with no kernel message or input prompt.  This might already be on your radar, but mentioning it just in case.

I'll post more as I use it. I think for now, deferring the complex semantic questions of shared kernels/execution authority/etc would be OK. We can start experimenting with the knowledge that sharing means giving the other person *full access* to your user, so for now it's a "high trust" action. We can then think about where/how finer control can be offered.

Thanks again!

**Comment by dmonad** [comment]
Hey @fperez, thanks for your feedback! 

Could you please pull again? It seems a couple of things broke when I rebased my branch. I fixed the loading issue in my last commit. 

> I'll post more as I use it. I think for now, deferring the complex semantic questions of shared kernels/execution authority/etc would be OK. We can start experimenting with the knowledge that sharing means giving the other person full access to your user, so for now it's a "high trust" action. We can then think about where/how finer control can be offered.

I like that. There are many questions that we need to figure out over time.

**Comment by fperez** [comment]
Thx @dmonad - FWIW the Console issue is still there, I just pulled and this is what I get:

image

The console tab starts but with no data/input prompt... Not urgent, just letting you know :)

**Comment by dmonad** [comment]
That's pretty critical I would say. The console should be working. It does work in the binder instance. It is possible that there are issues only reproducible in a certain environment. You might have more luck with a fresh installation. If it still doesn't work, let's hold off on this issue for a few weeks until this PR is in a better state. 

Regarding your previous comment that the editor flashes when you load a fresh instance: Thx, I didn't even notice that!

**Comment by agoose77** [comment]
The fact that this PR net removes lines of code and manages to add such cool features is rather exciting. Congratulations to all involved for their hard work, and thanks for making a Binder!

**Comment by fperez** [comment]
@dmonad - just to clarify, the above screenshot where the console doesn't work is taken from Binder. I've tested using the Binder multiple times and so far, the console has never worked for me.

No worries and not urgent, I just wanted to clarify where I was seeing the problem so you know. This can get fixed later...

**Comment by fperez** [comment]
BTW, jotting this down here as food for thought in the context of this PR. Once the dust settles a bit I'm happy to move this idea over into a separate issue, if it seems to make sense. But for now it seems sensible to keep the discussion in one place...

@ellisonbg and I were brainstorming how easy it would be now to build a really interesting "Slack-like client", but where each conversation was backed by an append-only log that's in practice a notebook. You could chat just like you do on Slack/chat tools, but with either markdown or code cells, thus requesting a kernel any time, making it possible to have code-based conversations. And at any point you could grab a copy from the log of that (which should be obviously append-only, read-only) as an editable document that would now be a shared notebook. This would create a super fluid transition from conversation to collaborative document-building - say a part of a chat looks interesting, you simply highlight the part you want, ask "copy as notebook" and start editing it with the other person now in-place, and boom, you have a document. Since we have such a close match between the message protocol and the file format, it seems to me the tools are there to make this very quickly.

Jupyter has always been about having very immediate, iterative access to the computer as a "thinking and conversation partner", and this gives us the tools to take that idea further, remaining pretty close to the core building blocks of our architecture.

**Comment by jasongrout** [comment]
@fperez - related to that, I remember William once mentioning something to the effect of any system with RTC eventually is (ab)used as a chat client. That led to him developing file-centered chat "rooms" and a robust chat client in CoCalc, supporting math rendering, etc. I think it makes a lot of sense for us to really explore providing a good chat solution as a place for conversations early on.

**Comment by fperez** [comment]
Agreed @jasongrout. In fact that's how I noticed the console wasn't working: I wanted to test how it behaved as it's got the basic feel of a chat client, once we add markdown input to it (you can fake it now with the `%%markdown` magic, but that's kind of clunky.

With the console machinery, once it supports input from multiple users, we basically have a primitive chat client. I agree with making it file-backed as well: our cell format is already a pretty good fit for that, I think, and relevant info like timestamp, author, etc. can fit into the metadata fields. 

Unless I'm missing something, we have the building blocks even closer than the bare RTC machinery (and I agree with @williamstein that any RTC tool ends up there quickly :). If I had a little more time right now I'd love to dive into prototyping this :)

**Comment by jochym** [comment]
I have played with the binder image a bit. It is great (considering the stage)!
Great work guys! We are (finally) getting closer to a much better solution than the Google based one (which taught me a lesson I think - corporations may pull anything from you at any time, now again with sync API).

Just a data point: The terminal works for me. But I have checked nglview (javascript/webgl based molecular display) and it does not show anything (except for NGLView() line).
Not complaining - just providing data.

**Comment by lukasheinrich** [comment]
many years ago I built a chat-like prototype for Jupyter - https://github.com/lukasheinrich/ipython-chat. I do think the idea is interesting

**Comment by krassowski** [comment]
It is a very much needed feature, thank you for working with the jupyterlab community on this!

A quick test-drive:
- critical: the console does not work for me too (I tested it both on the binder and locally with a fresh install); traceback below
- critical: completer does not work (instead tab is inserted)
- high impact: the API changes in this PR break [`jupyterlab-lsp`](https://github.com/krassowski/jupyterlab-lsp)
- high impact: the API changes in this PR break [`jupyterlab_code_formatter`](https://github.com/ryantam626/jupyterlab_code_formatter)
- high impact: [`jupyterlab-spellchecker`](https://github.com/ijmbarr/jupyterlab_spellchecker) does not seem to work either

Some of the breaking API changes that could possibly be avoided:
- removal of `notebook.model.cells.changed` and addition of `model.cellsChanged`
- `cell.model.value.text` got replaced by `model.getValue()` and `model.setValue()`; for consistence with the codebase could those retain getters and setters (of course ideally with the old interface)
- removal of `model.metadata.toJSON`

It would be nice if the new model retained the API of the old one for the sake of compatibility, but if this cannot be done, let's remember to list such API changes in the changelog.

The traceback after opening Python console:

```typescript
TypeError: Cannot read property 'source' of undefined
    at new CellModel (static/lab/packages_cells_lib_index_js.e691f4276579be9ff66a.js:806)
    at new CodeCellModel (static/lab/packages_cells_lib_index_js.e691f4276579be9ff66a.js:1072)
    at ModelFactory.createCodeCell (static/lab/packages_console_lib_index_js.c4d9dcc2b19f4845b4c7.js:1487)
    at CodeConsole._createCodeCellOptions (static/lab/packages_console_lib_index_js.c4d9dcc2b19f4845b4c7.js:1333)
    at CodeConsole.newPromptCell (static/lab/packages_console_lib_index_js.c4d9dcc2b19f4845b4c7.js:1215)
    at CodeConsole.onAfterAttach (static/lab/packages_console_lib_index_js.c4d9dcc2b19f4845b4c7.js:1173)
    at CodeConsole.Widget.processMessage (static/lab/jlab_core.444ae281694528081de0.js:23993)
    at invokeHandler (static/lab/jlab_core.444ae281694528081de0.js:20307)
    at Object.sendMessage (static/lab/jlab_core.444ae281694528081de0.js:20043)
    at static/lab/jlab_core.444ae281694528081de0.js:24695
```

I really like the approach of just swapping the model, but if you could also show that it works with existing extensions that users heavily rely on, it would be even better. It appears to me that many of the API changes could be avoided, reducing the diff and allowing better scrutiny of the changeset.

**Comment by ellisonbg** [comment]
@krassowski thanks for the feedback and testing, this is super helpful!

**Comment by jtpio** [comment]
btw if folks would like to try this PR with other people on the same Binder instance, the branch includes the [jupyterlab-link-share](https://github.com/jupyterlab-contrib/jupyterlab-link-share) to easily share the link to the server:

https://user-images.githubusercontent.com/591645/108040916-2ff80a00-703e-11eb-969d-aa44a35077a8.mp4

**Comment by jasongrout** [comment]
@SylvainCorlay @dmonad - FYI, on the agenda for today's dev meeting is a RTC demonstration in a few minutes by Eric and Pierre (using automerge, IIRC). Link at https://github.com/jupyterlab/jupyterlab/#weekly-dev-meeting

**Comment by fperez** [comment]
We were just testing an open notebook with a few collaborators, and saw a strange bug: simultaneously, the last 4 cells of the notebook got "reflowed" with all newlines getting removed.

The notebook originally looked like this:
image

And all of a sudden it jumped to this, while we were looking at it:

image

No idea how to replicate this as it happened in the middle of a work session, but worth mentioning... Interestingly, cells above these didn't change, only these four at the bottom.

[This is the notebook, in case it's of interest](https://github.com/espg/GeoFrame/blob/master/ExampleFetch.ipynb).

**Comment by fperez** [comment]
Further weird behavior: I tried fixing our notebook by uploading a fresh copy with a different name, and from that fresh version, copying a few whole cells and pasting them in. And now, when I paste those cells from a clean copy, they get pasted with their newlines gone. I'd never seen that kind of behavior, very odd... Mentioning it in case it helps anyone...

Just in case anyone from the team sees this and wants to check, the binder is [live here](https://hub-binder.mybinder.ovh/user/quantstack-jupyterlab-hfcxrx3t/lab-dev/lab/tree/00-CRYO/GeoFrame/ExampleFetch.ipynb?token=HfwFyVWdQP-ne3YVIfomsA), but this link will obviously only work for little while longer...

**Comment by fperez** [comment]
@jasongrout was the meeting recorded? I'd love to catch up but the meeting time conflicts with a weekly work meeting for me...

**Comment by willingc** [comment]
@fperez I asked the same question re: recording. Sylvain and @jasongrout said this morning that they didn't think so. It would be great if demos were done again that a recording is made :smile:

**Comment by jtpio** [comment]
This PR should also help using JupyterLab in multiple browser tabs: https://github.com/jupyterlab/jupyterlab/issues/3853

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/where-to-find-the-dev-state-of-real-time-collaboration-in-jupyterlab/2600/7

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/gathering-feedback-for-wikifunctions-proposal-based-on-jupyter-kernels/8159/2

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/suggestions-for-team-project-workflow/8182/1

**Comment by dmonad** [comment]
This work is superseded by https://github.com/jupyterlab/jupyterlab/pull/10118

**Pull request closed without merging**
