### PR TITLE
Toast notification

### LINKED ISSUE #689: Create proper notification system and area - Toast Notifications
Right now, there are lots of UI actions in JupyterLab that do something, but have no visual indication. An example is saving or renaming a notebook - the user gets no visual feedback those actions have completed or failed.

The existing notebook has a small area in the toolbar that provides notifications. We should:
- Create a notification API, plugin an UI for JupyterLab.
- Investigate other software that offers such functionality to properly design this.

### PR DESCRIPTION
**Pull request by fcollonval**
Following the integration of blueprint JS in the code base, this introduces a toasts container to emit notification to the user.

## References

Fixes #689

## Code changes

Preliminary note: `ui-components` has been modified to overwrite blueprint Sass variables with jp CSS properties. This will reduce the styling work for extension developers using blueprint.

In the package `statusbar` add a new plugin providing a `IToaster` token.

Usage example:

```ts    
    toaster.error({
      message: 'error'
    });
    toaster.warning({
      message: 'warning'
    });
    toaster.success({
      message: 'success'
    });
    toaster.info({
      message: 'info'
    });
    const ref = toaster.show({
      message: 'generic',
      timeout: 0,
      action: {
        label: 'clear',
        onClick: () => toaster.clear()
      }
    });
```

## User-facing changes

Notifications can be shown as toast with optionally one (and only one as per blueprint toast specification) action button.

The look is as follow:

image

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by fcollonval** [comment]
As I will be off for the next 2 weeks, here is the todo list and questions:

**ui-components** restyling

- [ ] Is it ok to do it (and therefore including some *Sass* dependencies) ?
- [ ] Setting sizes from CSS properties does not work as it is not compatible with Sass computation. Any idea how to circumvent this.
- [ ] In the icon conversion in `scripts\sass-convert-svg.js`, there is no equivalent for `small-minus`. Should we include something in the package?

**statusbar**

- [ ] Finish toast styling (in particular the button styling)
- [ ] Add unit tests
- [ ] Is there places in the code where we could you this already?

**Comment by blink1073** [comment]
Thanks for kicking this off, @fcollonval!  We did our final triage for features added 1.0 yesterday, so I'm marking this for 1.1.  Enjoy your time off!

**Comment by fcollonval** [comment]
> We did our final triage for features added 1.0 yesterday
can't wait to see it out there 😄 
> Enjoy your time off!
Thx

**Comment by echarles** [comment]
@fcollonval I had a quick look on the changes related to CSS. If I understand well, the `sass-inline-svg.js` converts the `style/bpvariable.scss` to `style/bpvariable.css` (with a bit of logic to change some blueprint svg to existing jlab svg, I guess this is to better fit the jlab look and feel). Is this correct? What about any change in the blueprint artifacts (new versions...). If we change the blueprint dependency in package.json, should the `style/bpvariable.scss` also be updated?

**Comment by gnestor** [comment]
@fcollonval Is there anyway to user test this?

**Comment by ellisonbg** [comment]
I would really like us to avoid having to muck with the scss files of blueprint. It is going to make it very painful. But I agree that it is pretty painful to have to style things purely with CSS. I have been mucking around with button styling over the weekend. Longer term, especially as we dive into accessibility, we may need to reconsider how we are working with blueprint - or possibly even our choice of it.

**Comment by echarles** [comment]
@ellisonbg 

> I would really like us to avoid having to muck with the scss files of blueprint.

The other way would be to simply accept 3rd party widget styling even it is does not completely integrate into jlab...

> ...we may need to reconsider how we are working with blueprint - or possibly even our choice of it.

Are you thinking to another toolkit, build jlab own, or any other option...?

**Comment by fcollonval** [comment]
@echarles 

> If I understand well, the sass-inline-svg.js converts the style/bpvariable.scss to style/bpvariable.css (with a bit of logic to change some blueprint svg to existing jlab svg, I guess this is to better fit the jlab look and feel). Is this correct? 

*Blueprint* specifies theme through SaSS variables. In order to customize a theme, those variables can be overwritten. Then using SaSS, the CSS style sheets tweaking *Blueprint* with the customization is generated and loaded instead of the standard *Blueprint* CSS style sheets.

In this PR, the customization is done in `ui-components/style/bpvariable.scss`. And the final customized style is obtained with the command `node-sass-chokidar --importer ../../node_modules/node-sass-package-importer/dist/cli.js --include-path ../../node_modules --functions ./scripts/sass-convert-svg.js ./style/ -o ./style/`. Finally the customized theme is loaded by `@import './bpvariable.css';` in `ui-components/style/index.css`.

The problem comes from the svg files. They are inline during the SaSS conversion using the script `sass-convert-svg.js`. To stay more faithful to JupyterLab theming, I create a customized convertion function to stop inlining the svg and instead use JupyterLab CSS variables.

> What about any change in the blueprint artifacts (new versions...). If we change the blueprint dependency in package.json, should the style/bpvariable.scss also be updated?

The files may be impact by a blueprint version change:

`style/bpvariables.scss` in cases:
* Blueprint changes some SaSS variable names
* Blueprint changes the top-level js sass file (imported at the end of the file).

`sass-convert-svg.js` in case:
* Blueprint changes the svg files inline in the CSS style sheet

Ressource: https://stackoverflow.com/questions/46199908/how-to-customize-blueprintjs-appearance-in-create-react-app

**Comment by fcollonval** [comment]
@ellisonbg Thanks for the review.

I'll modify the PR to not touch Blueprint styling. In parallel, I'm opening an issue on that. My point of view is that integrating a default react components library like blueprint (or something else) is a nice thing to have. It speeds up development, improve code robustness and reduce its maintenance cost (compare to starting a new one). But this means tweaking the CSS of that library to match JupyterLab theme. Otherwise extensions authors will introduce plenty of CSS rules due to the lack of a good look and feel integration by default.

**Comment by fcollonval** [comment]
@gnestor 

> Is there anyway to user test this?

Here is the example used to get the screenshot.

```typescript
const plugin: JupyterFrontEndPlugin<void> = {
  id: 'jupyterlab-plugin',
  requires: IToaster,
  autoStart: true,
  activate: (app: JupyterFrontEnd, toaster: IToaster) => {
    toaster.error({
      message: 'error'
    });
    toaster.warning({
      message: 'warning'
    });
    toaster.success({
      message: 'success'
    });
    toaster.info({
      message: 'info'
    });
    toaster.show({
      message: 'generic',
      timeout: 0,
      action: {
        label: 'clear',
        onClick: () => toaster.clear()
      }
    });
  }
};
```

**Comment by echarles** [comment]
Thx @fcollonval. FYI I see work on css #6530. Did you open a PR to discuss blueprint CSS? I am curious on how the toastr look like now thqt you don't change blueprint CSS (screenshot welcome :))

**Comment by fcollonval** [comment]
I completed a first version. For now, it is not used in the code. The place were it could make sense are some usage of `showErrorMessage` like in the `filebrowser` package. What do you think?

**Comment by fcollonval** [comment]
Closing this one as the consensus is to get ride of BlueprintJS.

Xref: https://github.com/jupyterlab/jupyterlab/issues/6890 https://github.com/jupyterlab/jupyterlab/issues/7574

**Pull request closed without merging**
