### PR TITLE
Updated Puppeteer version to v4.0.0

### PR DESCRIPTION
**Pull request by odidev**
## Code changes

Updated Puppeteer version to v4.0.0 in browser_check.py and updated eslint version to latest in package.json as the latest puppeteer version has support for aarch64 platform.

### CODE REVIEW

**Comment by blink1073** [comment]
Hi @odidev, thanks for the PR!  Can you please run `jlpm run lint` locally and push the changes to fix the integrity check?

**Comment by blink1073** [comment]
Congratulations on your first contribution to JupyterLab @odidev!

**Comment by odidev** [comment]
@blink1073, Thanks for approval and merging!!!

**Comment by odidev** [comment]
@blink1073 I am working on pyviz_comms and it has jupyterlab support could you please inform when will be the stable version for jupyterlab will be releasing ( with puppeteer v4.0.0 ) as currently, only the pre-release version of jupyterlab have that support.

**Comment by jasongrout** [comment]
Our goal is to have jlab 3.0 out by early October.

**Comment by odidev** [comment]
@blink1073 May I know when can we expect jupyterlab release.

**Pull request merged**
