### PR TITLE
Remove the non-null assertion on `IDebugger.ISources`

### LINKED ISSUE #10975: Remove the non-null assertion on `IDebugger.ISources`
A follow-up for this could be to try to remove the non-null assertion, since `IDebugger.ISources` might not be available.

_Originally posted by @jtpio in https://github.com/jupyterlab/jupyterlab/pull/10462#discussion_r696475570_

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fix #10975

## Code changes

debugger state will have empty cells list if the debugger source is not available.

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
Looks like the failing UI tests check is not relevant?

**Comment by fcollonval** [comment]
> Looks like the failing UI tests check is not relevant?

I confirm it is not relevant.

**Comment by jtpio** [comment]
Thanks!

**Pull request merged**
