### PR TITLE
Add sphinx-copybutton extension.

### PR DESCRIPTION
**Pull request by danielballan**
I think this would make the JupyterLab documentation more convenient to
use. See https://sphinx-copybutton.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by ellisonbg** [comment]
I am +1 on this, but looks like the tests are failing.

**Comment by danielballan** [comment]
Ah, I missed a comma. Fixed and force-pushed; we'll see if that does it....

**Comment by danielballan** [comment]
Hmm, the failure is:

```
Could not import extension sphinx_copybutton (exception: No module named 'sphinx_copybutton')
```

[link to line in build log](https://dev.azure.com/jupyterlab/jupyterlab/_build/results?buildId=2378&view=logs&jobId=6f807910-43ed-5cd8-ceaa-1aba4c5928ae&taskId=e833abef-9a43-57f4-3f21-3da357678b41&lineStart=716&lineEnd=717&colStart=1&colEnd=1)

I have added it to the `setup.py` and `docs/environment.yml`. Where else am I supposed to add it?

**Comment by ian-r-rose** [comment]
@danielballan I've pushed another commit adding `sphinx-copybutton` to the CI install. Hopefully that fixes the issue.

**Comment by danielballan** [comment]
Thanks, @ian-r-rose!

**Pull request merged**
