### PR TITLE
Improve documentation on galata setup

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Improve documentation on galata setup: #10706 and Gitter question.

## Code changes

Rename server configuration file for ui tests to match the name used in the documentation.

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by fcollonval** [comment]
@krassowski I saw in #11379 you changed some of the documentation. It would make sense to bring it in this repository, what do you think?

> I don't get the rename the `--config` option in #11379. It is an alias that should work:

```
--config=<Unicode>
    Full path of a config file.
    Default: ''
    Equivalent to: [--JupyterApp.config_file]
```

**Comment by krassowski** [comment]
Thanks! Please ignore my changes, I will undo them. I was tired and it looks like the issue was elsewhere. Sorry about it!

Would it be a good idea to add:

```python
ServerApp.port_retries = 0
```

so that we don't accidentally run tests on a different instance which happens to run on the default port? (This might have been my problem).

Possibly another improvement would be to change the default port to reduce a chance of a collision, but this might need more discussion.

**Comment by fcollonval** [comment]
> Would it be a good idea to add:
> 
> ```python
> ServerApp.port_retries = 0
> ```

Thanks this is a great suggestion

> Possibly another improvement would be to change the default port to reduce a chance of a collision, but this might need more discussion.

I fear the ship have sailed on this one as this means changing the default value in galata fixture. So that an upgrade of current user may induce unexpected broken configuration.

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.2.x

**Pull request merged**
