### PR TITLE
Update the extension tutorial to follow APOD

### PR DESCRIPTION
**Pull request by jaipreet-s**
## References

* #6463 
* #6568 

## Code changes

This updates the extension tutorial to follow https://github.com/jupyterlab/jupyterlab_apod. There are a bunch of TODOs which are delinated 

- [x] Update images for new extension
- [ ] Ensure the links to the repo have correct tags
- [x] Ensure cookie cutter seeds with the latest JLab interface
- [x] Do a final walkthrough (Errors reported in https://github.com/jupyterlab/jupyterlab/pull/6656#issuecomment-504128464)
- [ ] Replace one of the images with copyright
- [ ] Re-walkthrough using latest rc changes 

## User-facing changes

The doc build will show it visually

## Backwards-incompatible changes

* Existing links to the xkcd tutorial will start 404'ing because we renamed the file (https://jupyterlab.readthedocs.io/en/stable/developer/xkcd_extension_tutorial.html)

cc @ian-r-rose @jasongrout

### CODE REVIEW

**Comment by jaipreet-s** [comment]
I came across two issues

1. The first dependency addition of `@jupyterlab/apputils` causes a compile error unless I add the these lines to the `package.json`

```
"baseUrl": ".",
"paths": { "*": ["node_modules/@types/*"] },
```

2. After adding the restoring functionality, I get a compile error `Argument of type 'InstanceTracker<Widget>' is not assignable to parameter of type 'InstanceTracker<any>'`. This also happens with the state of the code at https://github.com/jupyterlab/jupyterlab_apod/commit/51b7210c0cd9ba14e5b0170d0694285660f7c455

**Comment by jasongrout** [comment]
I just updated the apod example to the RC0 release.

**Comment by jasongrout** [comment]
Thanks! I worked on updating this. I did notice that one of the screenshots has a copyrighted image, so we'll need to redo that one with a public domain picture.

**Comment by jaipreet-s** [comment]
Thanks. I added a couple of checklist items to remove the copyrighted image and re-run the tutorial on the latest RC.

The xkcd tutorial had tags to mark each checkpoint in the tutorial, and we'll need to add the same tags in APOD as well.

**Comment by jasongrout** [comment]
I force-pushed a change removing the copyrighted image, even from our git history (eventually).

**Comment by jasongrout** [comment]
I rewrote the one commit that added images, merged in master so that there aren't conflicts, then update a few other things. I also clarified the screenshot guidelines some more.

I've also updated the apod extension repo to work with the RC0.

Do you want to take another look at this, and try doing the screenshots again following the (clarified) guidelines at https://github.com/jupyterlab/jupyterlab/blob/b9f0c7d40e5aa7e71cd1b029af343ccab91165d8/docs/source/developer/documentation.rst#screenshots-and-animations ?

**Comment by jasongrout** [comment]
What do you think about renaming the file to something more generic that doesn't include "apod" so that if we ever change the example again, we don't break documentation links? Something like extension_tutorial.rst or something?

**Comment by jasongrout** [comment]
Rebased again on master to resolve merge conflicts.

**Comment by jaipreet-s** [comment]
> What do you think about renaming the file to something more generic that doesn't include "apod" so that if we ever change the example again, we don't break documentation links? Something like extension_tutorial.rst or something?

@jasongrout : Agreed. I'm a bit preoccupied this week but can get back to this next week. Does that timeline work?

**Comment by jasongrout** [comment]
I'll push forward if I can, and if it's not done, then you can take it up next week. Thanks!

**Comment by jasongrout** [comment]
@blink1073 - I think this is good to go now.

**Comment by jasongrout** [comment]
Docs failure was from forgetting to push the tags on the example solutions repo. I pushed them and restarted the docs test.

**Pull request merged**
