### PR TITLE
Do not load CSS of disabled federated extensions

### LINKED ISSUE #11728: CSS are loaded even for disabled extension
## Description

I ran into a css side-effect problem between an extension and a python module injecting html/css in notebook cells via repr. That specific problem was solved, but I wanted to find out how to deal with an extension conflict besides uninstalling it. It looks like disabled extensions can still have css loaded (appears in the DOM regardless of disabled or enabled). I wanted to check to see how a disabled extension is handled, whether it makes sense to prevent a disabled extension from importing anything, or if the only resolution is to uninstall. The context is a centrally managed Lab install where many extensions may exist, but users can choose to enable or disable specific extensions for themselves out of that set.

from @mlhenderson on [Gitter](https://gitter.im/jupyterlab/jupyterlab?at=61bbb163fd9244223e4b8744)

## Expected behavior

The styles are not loaded for disabled extensions.

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes #11728

## Code changes

- [x] Check for `PageConfig.Extension.isDisabled(data.name))` before loading the styles coming from federated extensions.
- [x] Document this behavior?

## User-facing changes

For example with a federated extension that adds the following CSS:

```css
#jp-topbar-spacer {
  background: blue;
}
```

**Before**

image

**After**

image

## Backwards-incompatible changes

This is a change of behavior that some deployments that have been depending on.

A new entry in this section of the docs could then be useful for reference purposes: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#extension-development-changes

### CODE REVIEW

**Comment by krassowski** [comment]
Is this still a draft?

**Comment by jtpio** [comment]
I think it was left as a draft to double check if there was any side-effect to this.

I'll rebase, fix the conflict and mark as ready.

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio

**Comment by mlucool** [comment]
@fcollonval can we backport this to 3.6? Maybe under a flag (which would be more code than the fix)?

**Comment by krassowski** [comment]
@meeseeksdev please backport to 3.6.x

**Pull request merged**
