### PR TITLE
Set focus when active cell changes only from mouse click

### LINKED ISSUE #12723: 3.4.3 breaks ctrl F functionality
## Description
When searching for text in CTRL+F mode, the searchtool loses focus whenever you hit the enter button. If the enter button is entered consecutively, jupyter starts editing the cell with the first match. Problem didn't not persist once I downgraded to jupyterlab 3.3.4

## Reproduce

1. launch jupyterlab v3.4.3
2.  hit ctrl F, search for a string
3. hit enter to get your first instance of the string
4. the searchbar has lost focus and you're now editing in the cell where you found the first instance of the string. 

## Expected behavior
The searchbar should not lose focus under any circumstances when I'm hitting the enter key.

## Context

- Operating System and version:  W11
- Browser and version:  Firefox and chrome
- JupyterLab version:  3.4.3

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #12723

## Code changes

Set focus when active cell changes only on click event

## User-facing changes

Pressing Enter when searching does not suppress search box focus

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by fcollonval** [comment]
please update galata snapshots

**Review by krassowski — APPROVED** [review]
Works for me.

**Comment by jtpio** [comment]
Thanks!

**Comment by jtpio** [comment]
@meeseeksdev please backport to 3.4.x

**Pull request merged**
