### PR TITLE
Fix handling of data URIs

### LINKED ISSUE #3796: Link mangling for contents manager breaks certain downloads
given a data frame:

```python
from IPython.display import HTML
import base64
csv = base64.b64encode(df.to_csv().encode()).decode()
html='<a download="download.csv" href="data:text/csv;base64,{payload}" target="_blank">Download</a>'.format(payload=csv)
HTML(html)
```

If you click on the download link, it raises a JS exception, which is clear because the link has been mangled.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #3796, cf #3862 for wider discussion about local URLs.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
@blink1073 Mind me pushing a couple of tests?

**Comment by blink1073** [comment]
Go for it!

**Comment by ian-r-rose** [comment]
Or just one, as it were.

**Comment by ian-r-rose** [comment]
Thanks!

**Pull request merged**
