### PR TITLE
Fixes context menu hit test to deal with svg nodes.

### LINKED ISSUE #7224: "Switch Sidebar Side" context menu item doesn't work if you right click on the sidebar tab's icon
If you right click on a sidebar tab and then select "Switch Sidebar Side", it won't work if you happened have right clicked on the tab icon. I'm pretty sure this broke because the icon is now a svg child node, instead of just a background image.

### PR DESCRIPTION
**Pull request by jasongrout**
## References

Fixes #7224

## Code changes

The context menu hit test now works for any node, not just html elements, though we only run the user-supplied function on html elements for backwards compatibility.

## User-facing changes

The Switch Sidebar context menu item should work now.

As well, this PR includes a fix for the styling of the right sidebar icons: previously, they were being rendered upside down.

## Backwards-incompatible changes

None. This should be safe to backport to 1.2 and 1.1.x.

### CODE REVIEW

**Comment by jasongrout** [comment]
CC @telamonian

**Comment by jasongrout** [comment]
@telamonian - can you review this?

**Comment by telamonian** [comment]
We may want to revisit the decision to ignore `SVGElement` nodes for Jlab `v2.0` (and probably give the whole context menu node hit test thing another pass in general). For now, minimizing compatibility surprises seems like a good idea.

Everything else looks good. I added a fix for the icon styling. The sidebar tab icons should now look the same on the right as they do on the left.

**Comment by jasongrout** [comment]
FYI, the tests failure is an unrelated issue (apparently NASA changed its API webpage, breaking a link in our docs). I've emailed NASA about it.

**Comment by telamonian** [comment]
@jasongrout I noticed about NASA. Leaving that aside, I think the PR is good to go. Mind if I merge it in?

**Comment by jasongrout** [comment]
@telamonian - are your changes also safe to backport to 1.2 and 1.1.x?

**Comment by jasongrout** [comment]
@telamonian - your changes look good to me. Feel free to merge if you think this is backwards compatible to 1.1.x.

**Comment by telamonian** [comment]
@meeseeksdev backport to 1.x

**Comment by telamonian** [comment]
what do you know, the backport call actually worked

**Pull request merged**
