### PR TITLE
fix changed username, pin pydantic<2 for CI

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- noted on #14102

## Code changes

- updates changed username of author of #14095
- use `python -m pip install` in CI script
  - pin `pydantic<2` for now (`copier` not yet compatible)

## User-facing changes

- n/a

## Backwards-incompatible changes

- n/a

### CODE REVIEW

**Comment by bollwyvl** [comment]
Fixed: https://github.com/jupyterlab/jupyterlab/actions/runs/5431905876/jobs/9878584216?pr=14780

**Comment by bollwyvl** [comment]
Trying `pydantic<2` pin for `copier` importability, see:

https://github.com/copier-org/copier/issues/1225

**Comment by bollwyvl** [comment]
@fcollonval nice, first full ci pass i've seen in a few days.

**Review by fcollonval — APPROVED** [review]
Thanks @bollwyvl

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 4.0.x

**Pull request merged**
