### PR TITLE
Remove the memory usage status bar item

### LINKED ISSUE #9363: Move the memory usage status bar item to the nbresuse repo
In https://github.com/jupyterlab/jupyterlab/pull/9349, we realize that it would be simpler for the memory usage status bar item to be moved to the `nbresuse` repo, and developed as a third-party extension.

This item currently lives in lab here:

https://github.com/jupyterlab/jupyterlab/blob/ae08605b296e45facb7da138414900f539b114a0/packages/statusbar-extension/src/index.ts#L327-L356

This would make it easier for `nbresuse` to move independently from JupyterLab, and avoid syncing on both repos for major releases.

The extension can be developed as federated / pre-built extension, using the new distribution system with pip and conda:

https://jupyterlab.readthedocs.io/en/latest/developer/extension_dev.html#goals-of-the-federated-extension-system

Which means that the extension would be automatically installed on `pip install nbresuse`, and would be seamless to the users since they already have to perform this step anyway.

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes #9363 

Remove the memory usage component from the status bar:

image

Which required users to install `nbresuse` with `pip install nbresuse` to have it activated.

## Code changes

Remove the memory usage status bar item from the code base, since it will be moved to the `nbresuse` repo as a third-party extension.

## User-facing changes

Once https://github.com/yuvipanda/nbresuse/pull/69 is merged and a new release of nbresuse, users will still be able to `pip install nbresuse` and the status bar item will be installed as a federated lab extension.

## Backwards-incompatible changes

The memory usage plugin was not exposing any token to the system, so it should be fine w.r.t sharing tokens.

However, other extensions and packages could technically import the component with:

```typescript
import { MemoryUsage } from '@jupyterlab/statusbar';
```

Which won't be possible after this change and when a new release of `@jupyterlab/statusbar` is published.

### CODE REVIEW

**Comment by jtpio** [comment]
Leaving as a draft for now, as there a bit of coordination to do with `nbresuse` (normally the last time), just to make sure to not confuse users.

> Which won't be possible after this change and when a new release of @jupyterlab/statusbar is published.

An alternative, if we want to get this change in 3.0, would be to keep the export of the memory usage component in the code base, so users could still import it with (but still remove the plugin that adds the status bar item):

```typescript
import { MemoryUsage } from '@jupyterlab/statusbar';
```

And remove `memoryUsage.tsx` and the export in 4.0.

**Comment by jtpio** [comment]
Adding to the 3.0 milestone to proceed with the removal before before the next major release.

`nbresuse` has now been moved to the `jupyter-server` organization and renamed to `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage

Once a release of `jupyter-resource-usage` is published with the federated / pre-built lab extension, users will be able to add the resource usage item back to the status bar, with a single `pip install jupyter-resource-usage`.

**Review by telamonian — APPROVED** [review]
LGTM! I think the current state is broken, and this should go in with the 3.0 update.

@jtpio Any chance of a release of `jupyter-resource-usage` happening in the next week or two (ie before the release of jlab 3.0)?

**Comment by jtpio** [comment]
> Any chance of a release of `jupyter-resource-usage` happening in the next week or two (ie before the release of jlab 3.0)?

Yes that's the idea. Would you like to check this PR too, which ports the code to `jupyter-resource-usage` and adopt the new distribution system? https://github.com/jupyter-server/jupyter-resource-usage/pull/69

**Comment by jasongrout** [comment]
Thanks!

**Pull request merged**
