### PR TITLE
Backport/3.2.x/11608 Toggle side-by-side rendering for current notebook

### PR DESCRIPTION
**Pull request by echarles**
Manual Backport to 3.2.x branch of Toggle side-by-side rendering for current notebook https://github.com/jupyterlab/jupyterlab/pull/11608

### CODE REVIEW

**Review by echarles — COMMENTED** [review]
CI green except check_i18n and enforce-label which I have seen failing also in previous backport PR. @fcollonval Can you confirm it is OK to merge?

**Comment by krassowski** [comment]
IMO this is 3.3 material. I wouldn't mind the translations experience breakage as much as the settings key change.

**Comment by echarles** [comment]
> IMO this is 3.3 material.

Correct. The way we will release 3.3 is to branch from `3.2.x`, this is why this PR targets `3.2.x`

**Comment by krassowski** [comment]
So I guess we should create the 3.3.x branch soon so we could still have the same workflow when backporting bug fixes to 3.2.x? I think we will need at least one more 3.2.x to fix the console completer regression.

**Comment by echarles** [comment]
I have added https://github.com/jupyterlab/jupyterlab/issues/11710 to the list of PR to go in 3.3.

I think the 3.3.x branch would typically be created just after the 3.3 release

I will merge this backport PR (green CI) unless anyone says otherwise.

**Comment by fcollonval** [comment]
> I think the 3.3.x branch would typically be created just after the 3.3 release

Actually this is not correct because, we need to be able to create patch release (for potential security fix).
Following the discussion at this week meeting, I'll create the 3.3.x branch.

> Thanks @krassowski for pointing this was merged.

**Comment by fcollonval** [comment]
To be able to rebase 3.3.x on 3.2.x up to the release date, I will revert this PR on 3.2.x and then re apply it targeting 3.3.x

**Comment by echarles** [comment]
> Actually this is not correct because, we need to be able to create patch release (for potential security fix).

I have read the discussion, but not completely clear on that.

After the 3.2 release, we have merged many features in 3.2.x branch. Is this one the only one to be reverted or do we have to do that for all the PRs merged in 3.2.x?

**Comment by fcollonval** [comment]
The trouble of this PR is that is changes a setting key name => hence it should be part of 3.3

As far as of 3.1.x and 3.2.x ([changelog link](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html)), there has been very few new features brought in patch releases. The only one I can spot that is actually not related to some fixes is https://github.com/jupyterlab/jupyterlab/pull/11533 that this PR is altering.

If we don't revert this one on 3.2.x and need to publish a new 3.2.# release, then this will break the behavior introduced in 3.2.5 as the side by side rendering setting is renamed.

**Comment by fcollonval** [comment]
> do we have to do that for all the PRs merged in 3.2.x?

So no only this one.

**Comment by echarles** [comment]
Sounds good. Thx for the explanations.

**Pull request merged**
