### PR TITLE
[WIP] Websocket Datastore

### PR DESCRIPTION
**Pull request by vidartf**
Adds two datastore adapters (WIP on phosphor repo):
- `LocalServerAdapter`, a local "loopback" adapter. Can be useful e.g. for testing.
- `WsAdapter`, a websocket based adapter. The WS code for this is compartmentalized in the separate `WsConnection` module.

The wire format for the `WsAdapter` messages is typed up in the `WsAdapterMessages` namespace.

### CODE REVIEW

**Comment by vidartf** [comment]
TODO:
- [ ] Keep up to date with any changes to the interface in phosphor repo.
- [ ] Add the WIP server implementation, and have it use the same wire format.
- [ ] Write tests.
- [ ] Write documentation.

**Comment by jasongrout** [comment]
@ian-r-rose @vidartf @saulshanabrook - is this PR still relevant, given the work that's been done in the datastore branches?

**Comment by vidartf** [comment]
This code is probably out of date, but I'll leave it to @ian-r-rose to possibly salvage some code from it, if he finds something useful. The loopback adapter could still be useful for testing, e.g. in the phosphor repo, or in our branch.

**Comment by blink1073** [comment]
Closing as stale, work has moved to the RTC repo

**Pull request closed without merging**
