### PR TITLE
remove reference to blueprint.js in css

### LINKED ISSUE #12331: Reference to Blueprint.js css should be removed
Now that blueprintjs is removed in https://github.com/jupyterlab/jupyterlab/pull/11173 we should make sure we completely remove reference to it, included in css.

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Replaces and closes #12332
Fixes #12331

## Code changes

Remove CSS rules for coping with BluePrint default styles

## User-facing changes

Light visual impact

## Backwards-incompatible changes

N/A but styles of extensions may require small changes to adapt to the new default styles.

### CODE REVIEW

**Comment by fcollonval** [comment]
@echarles I rebooted your PR. Before rebasing, I'm wondering if we should restore the focus outline deletion?


> Testing on Firefox the focus outline is more discrete than in the test snapshots.

**Comment by echarles** [comment]
> I'm wondering if we should restore the focus outline deletion?

If it give better rendering on Firefox, we can do that. I have mostly been impacted by the box-sizing and the font related related rules so far.

**Comment by fcollonval** [comment]
please update snapshots

**Comment by fcollonval** [comment]
please update documentation snapshots

**Comment by fcollonval** [comment]
please update documentation snapshots

**Comment by fcollonval** [comment]
please update snapshots

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by echarles** [comment]
Thank for this.

**Pull request merged**
