### PR TITLE
a test case to illustrate issue #14871

### PR DESCRIPTION
**Pull request by parmentelat**
## References

issue #14871

## Code changes

one more test case, with related input and outputs

**notes** 
- the test right now breaks, because of #14871 precisely
- also at first the outputs are made on darwin - will get rid of that once the correct linux outputs are produced

## User-facing changes

none

## Backwards-incompatible changes

none

### CODE REVIEW

**Comment by parmentelat** [comment]
also I had to run `git commit --no-verify`, the prettier stage was failing, even though `jlpm run prettier` seemed happy
please let me know how to deal with that

**Comment by krassowski** [comment]
`jlpm run prettier` is only prettier, there is also `eslint` which might have caught that `getSelectionRange` is unused and needs to be used or removed. In general `jlpm run lint` from root of the repo should work.

**Comment by parmentelat** [comment]
I must have misunderstood, I had the impression it was the prettier stage that was wrong..
anyway, I have removed the unused function and it is now all good wrt committing

**Comment by parmentelat** [comment]
trying to improve the situation, here's a few thoughts to share

###  level1

the first-level bug has to do with the search dialog having lasting effects
and indeed, it will be an obvious improvement 
if giving up on the search dialog (using either Escape or the cross icon) 
brings us back in a state where nothing is being searched

### level2

however, playing with the search a little more, I came to realize that, 
when the search dialog is still on, it feels like the job in charge of outlining stuff
sometimes has a very intrusive behaviour, notably putting some cells in edit mode while they were not,
which is imho wrong in itself, and worse still it often leads to arbitrary cells becoming in focus (in the viewport)
as a result this intrusion is very often devastatingly confusing for the user,
because it makes one lose one's train of thought by scrolling up or down with no apparent sense 


my own experience has been to face level2, so I tried to get rid off the issue by turning off the search dialog,
but it was not enough because of level1

So I guess what I'm saying is, I might eventually be able to fix stage1 as part of this PR, I'll try at least
but even so, there will remain some agreement to reach on how the search outlining business
is expected to behave, and imho the expected behaviour would be:
- no change of editing mode
- no scrolling whatsoever

but I guess that's just me
and apologies for getting a little off-track as compared to the initial target of this PR

**Comment by krassowski** [comment]
Thanks again for your work here @parmentelat, closing this in favour of https://github.com/jupyterlab/jupyterlab/pull/15443 which includes your commits from this PR. Pleas feel welcome to review.

**Pull request closed without merging**
