### PR TITLE
Fix manager isDisposed is not set

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Seen when analyzind the code.

## Code changes

Set _isDisposed to true when calling `dispose`. Otherwise it is never done as the attribute is private

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by fcollonval** [comment]
As expected b34e74b demonstrates the bug:
```
 FAIL  test/kernelspec/manager.spec.ts
  ● kernel/manager › KernelSpecManager › #isDisposed › should true when disposing

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      67 |       it('should true when disposing', () => {
      68 |         manager.dispose()
    > 69 |         expect(manager.isDisposed).toBe(true);
         |                                    ^
      70 |       })
      71 |     })
      72 |

      at Object.<anonymous> (test/kernelspec/manager.spec.ts:69:36)
```

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
@meeseeksdev please backport to 4.1.x

**Comment by jtpio** [comment]
@meeseeksdev please backport to 4.0.x

**Pull request merged**
