### PR TITLE
Notebook Cell Drag Drop

### LINKED ISSUE #641: Improved UI/UX for moving cells up or down
## Current summary

We plan on supporting moving cells through 3 approaches:
- [ ] Add move/up down commands (#189)
- [ ] Up/down buttons in the notebook toolbar
- [ ] Drag/drop
## Original comment

So I know there's a keyboard shortcut to move cells up or down, but I can never remember it and I always just use the buttons. I would love a toolbar that had the same buttons as the traditional notebook view.

### PR DESCRIPTION
**Pull request by blink1073**
cf #641.

cell-drag-drop

We are missing the ability to scroll down within a notebook while dragging.  cf https://github.com/jupyter-incubator/dashboards/pull/204/files.  I will address this in another PR.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Super awesome! We can have @cameronoelsen follow on with visual design

**Comment by SylvainCorlay** [comment]
@blink1073 this breaks dragging slider handles in widgets. Could we enable this behavior only on the output gutter? 

ping @jasongrout

**Comment by jasongrout** [comment]
Yes, it would be great if dragging was only triggered on the prompt, similar to how we only trigger pulling outputs out on the output prompt.

**Comment by cameronoelsen** [comment]
On it for the design!

**Comment by cameronoelsen** [comment]
After thinking about what the user will be expecting, I think it will be helpful to have two cases:
Single cell and multi cell drag and drop. It was actually very helpful to have the feature already implemented in master to think of solutions. Three key thoughts that we need to convey with the cell drag and drop feature, to make sure it isn't confusing and feels natural, are:
- Which cell is the user moving (singular or multiple)
- Where will the cell be inserted if let go (expected drop zone)
- As the user is moving a cell to drop into another notebook file, does the cell in the past file disappear or stay there until it has a new location?

With this approach, I think it solves all three of these questions:

When the user holds on a cell, the single cell will trail and hover behind the mouse's tail with an included short preview into what the body of the cell contains (if there is content within the cell). Once the cell is trailing behind the mouse, wherever the user points to inside an open notebook will outline the area with a dotted line of the expected drop zone (I think this is currently being conveyed with the blue line). When the user moves the trailing cell away from the original area in which it was presiding, the original cell will disappear from its location (currently it is making it semi-transparent as the user is moving it's location) and wherever the pointer is within a notebook, the dotted area will appear.

Here are mockups of what I believe the expected behavior should look like for single and multiple cell drag and drop:

### After the user has initially picked up a single cell to drag and drop:
#### Single Cell
single-cell

#### Multiple Cells (in this case 2 cells are selected)
multiple-cell

For the multiple cell, it will show the content preview for the topmost cell in the "stack" of cells. Instead of showing which "In []" value it is, the text on the left shows how many cells are selected (similar to the original implementation, just a little more subtle)

After the user moves the selected cell away from it's original location, the cell disappears and the cursor point will specify where in a notebook document the user is intending to drop the cell/cells. Here are two mockups showing the behavior:

### After the user has moved the cell and pointed to a new drop zone
#### Single Cell
single-cell-drop

#### Multiple Cells
multiple-drop

If the pointer is outside the notebook or does not hover over a new location, the cell will return to it's place. Tomorrow I will continue to iterate on the visual design as well!

**Pull request merged**
