### PR TITLE
Remove Storybook

### PR DESCRIPTION
**Pull request by jtpio**
## References

In https://github.com/jupyterlab/jupyterlab/pull/11648 we noticed some dependencies like `nth-check` are difficult to update and come from the dependency on `storybook`.

Storybook seems to be coming back often when we try to update dependencies, for example:

- https://github.com/jupyterlab/jupyterlab/pull/10516
- https://github.com/jupyterlab/jupyterlab/pull/10755

I'm not sure if anyone is currently using it? Which is why this PR proposes we just remove it. If someone is still using, then we should consider keeping it.

## User-facing changes

None

## Backwards-incompatible changes

Should be none.

### CODE REVIEW

**Comment by jtpio** [comment]
cc @telamonian if you have any input on this

**Comment by fcollonval** [comment]
Thanks for starting this.

We spoke briefly about that in https://github.com/jupyterlab/jupyterlab/pull/11173#issuecomment-935444879 @jasongrout  and I.

The agreement was indeed to drop it as no active developers use it (this is probably the reason it was never updated :wink:).

**Comment by jtpio** [comment]
Marking as ready as I'm not planning to make any more changes.

We can also leave it open for a bit so folks have time to comment. This can also be discussed at the next weekly meeting.

**Comment by jtpio** [comment]
Also the diff cleans up the `yarn.lock` quite a bit:

image

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio

**Comment by fcollonval** [comment]
Sorry I closed it a bit too quickly. I will raise the point at today's team meeting. And revert if needed.

**Pull request merged**
