### PR TITLE
Fix for Code Mirror width. Indentation changes made

### PR DESCRIPTION
**Pull request by pree-T**
Fix for the Code Mirror Width  issue #11696 . Indentation changes implemented.

### CODE REVIEW

**Review by fcollonval — APPROVED** [review]
Hey @pree-T, thanks for the latest changes.

One big comment about GitHub usage. You should not close and reopen a PR following a review. Simply keep pushing changes to the PR branch (actually you should use a different branch than master to do so). Otherwise it makes it difficult to follow discussion and reason changes occur (like this has already 3 associated PRs that have comment in it).

please consider reading the GitHub documentation for more information: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests

**Comment by pree-T** [comment]
Okay Sir! I will go through it. Actually I am relatively new to open source contribution and hence was unaware of it. Thanks a lot for all the support and guidance.

**Comment by fcollonval** [comment]
> Actually I am relatively new to open source contribution and hence was unaware of it. Thanks a lot for all the support and guidance.

Big hooray :tada:  then on completing this first PR as JupyterLab is not an easy beast :wink:

**Comment by pree-T** [comment]
> > Actually I am relatively new to open source contribution and hence was unaware of it. Thanks a lot for all the support and guidance.
> 
> Big hooray 🎉 then on completing this first PR as JupyterLab is not an easy beast 😉

Thank you Sir @fcollonval ! Will this PR be merged?

**Comment by jtpio** [comment]
Thanks!

**Pull request merged**
