### PR TITLE
Added basic theming for statusbar

### PR DESCRIPTION
**Pull request by telamonian**
The new statusbar is great, but visually it kind of sticks out like a sore thumb. Not only is it not set up to adapt to the built-in themes, its styling is hard to override in custom themes (since it's all written using `typestyle`, which mangles all of the `class` attrs). This PR contains a bare-bones solution that makes the statusbar use the theme's colors.

Dark:
image

Light:
image

Another option of course would be to add custom theming vars specifically for statusbar. This PR can be thought of as a stop-gap fix until a decision on precisely how statusbar should be themed is made.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Thanks @telamonian I agree that this should be done. There is another PR open right now with the same goal (#5960). Perhaps you can join forces?

**Comment by telamonian** [comment]
Hah, looks like we had almost exactly the same idea. Neat.

@ian-r-rose I saw your bullet points on the other PR:

- The colors I picked happen to address the concern you had about contrast with the filebrowser:

image

Personally I like the "flush" look for the gutters. If the left/right tab bars and the statusbar all have roughly the same styling then they look more like a coherent whole, and are less visually distracting. On the other hand, different people will have different opinions about the colors of their IDE, possibly even very strong ones (eg the existence of both this PR and #5960). Maybe it'll be worth it to break out at least the statusbar colors (background + text) into their own vars?

- I noticed the same issue with the white icons in the Light Theme:

image

I'll poke at that and see what I can do.

@gnestor My apologies for not seeing your PR when I was tinkering with this. Wanna figure this out?

**Comment by telamonian** [comment]
@ian-r-rose Okay, so it looks like it is theoretically possible/easy to style the `.svg` icons using CSS. The catch seems to be that in order to do so the `.svg`s need to be embedded in the HTML as plain text, and not as base64. I suppose the build system could be tweaked to accommodate?

**Comment by ian-r-rose** [comment]
I think that would be reasonable, but I'd probably prefer to do all the CSS icons in one go in a follow-up PR, rather than here or #5960. In the immediate term, I don't think it's too bad to include light/dark versions of the statusbar icons.

**Comment by telamonian** [comment]
Should those light/dark icons go in the default light/dark themes? Or would it be better to keep them in the `statusbar` pkg and switch them using `[data-theme-light='true']` style selectors?

**Comment by ian-r-rose** [comment]
I've been trying to keep the relevant packages responsible for their assets (so the notebook package gets the "trusted" icon). We have not been particularly consistent here, but I'd prefer the `[data-theme-light="true"]` approach, at least until we use the better approach of styling the SVGs directly.

**Comment by ian-r-rose** [comment]
cc @gnestor

**Comment by telamonian** [comment]
Okay, I think that's the last of the icons dealt with.

**Comment by telamonian** [comment]
My pleasure

**Comment by gnestor** [comment]
Thanks @telamonian! This is a more thorough pass than my PR. 

It looks like we lost the icon here:
image

We may want to style the `color` property of text in the status bar to be inverted when active/selected like the filebrowser does:
image

**Comment by telamonian** [comment]
Ah, good catch. It seems the problem is that the shell node (which has the `data-theme-light` attr) is a sibling of the node that contains that icon, not an ancestor. Sticky

**Comment by ian-r-rose** [comment]
image

**Comment by ian-r-rose** [comment]
I remember at the time I added the `theme-light` attribute I was unsure of whether it should be on `shell` or `body`. This probably means that the latter was a better choice 😕

**Comment by telamonian** [comment]
Maybe so, maybe so. But we must press on!

Is there a deep reason why `Popup` attaches to `body`? One potential fix might be to attach `Popup` to the node of its anchor instead.

**Comment by ian-r-rose** [comment]
I suspect it was attached to `body` so that it would float over whatever might be in the main area. But I'm not certain about that, and it may be equally okay to attach it to the application shell, or to the statusbar.

**Comment by jasongrout** [comment]
We also have a similar problem in bqplot, actually, where a popup tooltip is attached to the body, so it can't get the jlab theme.

On the other hand, it feels bad to affect things above shell. Perhaps there can be some configuration somewhere that tells where to put that theme css attribute, or perhaps the shell handles it through a convenience function, and we can default to body for jlab, but if we are embedded in a page we can give some other place.

**Comment by telamonian** [comment]
Short term, I think there are two pretty okay options:

- Add an option like `anchorNode?` to `Popup` that optionally allows for the explicit setting of the parent node. I just tested this and there was no obvious regression in terms of appearance or behavior, but I assume I'm missing something.

- The icon in question ends up on a dark-ish blue background, regardless of theme. That too might be something we want to change in the future, but for now it means that we can get away with just using the white version of the icon. Definitely the simplest approach.

**Comment by ian-r-rose** [comment]
@telamonian I am okay with either of the two options you mention. The second is definitely simpler, and is consistent with the behavior of the command palette magnifying glass icon.

**Comment by telamonian** [comment]
I took option two, since it seemed like the more aesthetically correct one at the moment.

As per @gnestor's suggestion, I changed the theming on a clicked button to match that of the theming on a clicked filebrowser listing:

image

**Comment by gnestor** [comment]
I checked out the latest and it looks good @telamonian 👍

**Comment by jasongrout** [comment]
One more thought about body vs shell and data attributes - it would be *very* easy to write a plugin that listened to theme changes and changed some body attribute for situations where there was a popup attached to the body that needed theming information.

**Comment by ian-r-rose** [comment]
Yep, the CSS attribute can be seen as more of a convenience. The datagrid, which styles in JS, does this:
https://github.com/jupyterlab/jupyterlab/blob/fd1b87f84da27d94a0c8b84deb108d24ff4cbfce/packages/csvviewer-extension/src/index.ts#L126-L138

**Comment by telamonian** [comment]
That makes sense (and thanks @ian-r-rose for the neat contrarian theming example). I am still curious though as to why the popup gets attached to body in the first place, instead of it's anchor widget. A comment in `Popup.IOptions` makes it seem like it might be a bug:

https://github.com/jupyterlab/jupyterlab/blob/fd1b87f84da27d94a0c8b84deb108d24ff4cbfce/packages/statusbar/src/components/hover.tsx#L188-L191

What's the benefit of attaching to body?

**Pull request merged**
