### PR TITLE
Post LabIcon cleanup; migrate last holdouts to LabIcon; fix icon styling

### LINKED ISSUE #7859: Some icons look "dimmer" with the Dark Theme in 2.0
Testing from the [current master](f17361c2d6ecf1b5ccae5b576266355150f09af2), some icons (mostly the check marks and submenu arrows) now look dimmer than before (1.x).

With 1.2.6:

image

With 2.0 / current master:

image

### PR DESCRIPTION
**Pull request by telamonian**
## References

fixes #7859, #7869, #7887 

This PR has two goals:

- [x] ~Fix up remaining weird edge case uses of LabIcon and remove all `LabIcon.UNSTABLE_foo` methods~
    - All gone!
- [x] ~migrate remaining holdout icon-as-css-background cases to LabIcon (the menu icons (see #7859) and a handful of others (like the log console icon, I think?))~
    - 100% of icons in jlab core are now set up and rendered using LabIcon

Fixing the above also involves some changes to lumino, so this PR includes a bump to lumino deps.

Also, some needed fixes for the icon styling system ended up involving some minor API breaking changes (some deprecated cruft was removed from a couple of function sigs, see below). So now this PR also includes a significant cleanup of icon styling code (see `ui-components/src/style/icon.ts`). The big news from that is that now users will be able to specify their own custom icon styling much more freely/completely than before.

## Code changes

A lot

## User-facing changes

No more visible icon regressions

## Backwards-incompatible changes

I deprecated/removed `RendererClass` from `LabIcon.IOptions` (which is used as the type of the args for `LabIcon.constructor`). `RendererClass` was part of a now-removed renderer mixin scheme for LabIcon, and was redundant/confusing wrt some of the other fields in `LabIcon.IOptions`.

### CODE REVIEW

**Comment by telamonian** [comment]
Progress update:

AFAIK, all icon issues are now fixed in this PR. If you spot differently, please tell me. Two exceptions:

- [ ] CommandPalette icons
- [ ] The "block"/"ban"/"clear" icon in the log console has been temp changed to just `closeIcon`

Getting submenus to render icons correctly took some true hackish weirdness in `MenuSvg`, if anyone cares to review:

https://github.com/jupyterlab/jupyterlab/blob/821537c385e7e2345bffeb5552afc0eb26b23138/packages/ui-components/src/icon/menusvg.ts#L44-L69

**Comment by ajbozarth** [comment]
I'll try to find time to review this between tonight and eod Monday

**Comment by telamonian** [comment]
...annnd done. With the icon fixes, anyway. This PR still needs:

- [ ] a rebase
- [ ] dependency update to pull in latest `@lumino/virtualdom`, etc packages
- [ ] misc cleanup

**Comment by telamonian** [comment]
@blink1073 @jasongrout I think this PR is now ready to go in, and should fix all of the currently outstanding icon issues. I deprecated a couple of function args while working on this PR, and since we're still in RC I made a judgement call and removed them (I added the details to the first post on this PR).

Though minor, said removals are technically breaking changes. With that in mind, I specifically saved the removals for the very last commit (dd9a3d3), so if everyone thinks this is a Bad Idea, the removals can be easily rolled back.

**Comment by telamonian** [comment]
I did an audit of the remaining icon-related CSS code left in the codebase. There are currently exactly 5 icons that are still being rendered using the old icon-as-css-background behavior:

- The up/down/left/right caret icons on the buttons on the end of the scrollbars of any lumino Datagrid
- The magnifying glass/search icon to the right of the search bar at the top of the command palette

The datagrid scrollbar icons will probably require some more fixes in lumino. In any case, migrating these particular icons to LabIcon isn't a high priority. Since they are all shown on top of a fixed color background (that doesn't change with the theme), their appearance should be correct in all themes regardless of rendering method

**Comment by blink1073** [comment]
I did another pass of the code and tested it on binder, looks good, thanks @telamonian!

**Pull request merged**
