### PR TITLE
Select the correct cell after multi-cell-deletion.

### LINKED ISSUE #4182: deleting multiple cells results in focused cell too far down
When I delete multiple selected cells, the focused cell isn't the one I expect. It appears the focused cell jumps down by the length of the selection give or take 1. In the gif, I'd expect the focus to be on the cell with the `4`.

jlab-delete

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes #4182

### CODE REVIEW

**Comment by jasongrout** [comment]
Looks like the two tests that were supposed to test for the correct behavior for this case are the ones that are failing. Are the tests in error?

Also, it seems that the docs for the action should have another sentence explaining that if the last cell is deleted, the previous cell is selected (cf. the test and code, vs. https://github.com/jupyterlab/jupyterlab/blob/8de8cf6d361329fe975627d09a0cc12a517eec4a/packages/notebook/src/actions.ts#L1446)

**Comment by ian-r-rose** [comment]
Yep, the tests were in error. They are fixed now.

**Comment by jasongrout** [comment]
I think deletion should handle discontiguous selections - in which case the logic should be that the new selected cell has index `max(todelete)+1 - len(deleted)` if we don't have the last cell selected, one less if the last cell is selected.

**Comment by ian-r-rose** [comment]
I'm not sure that's what the old test was intending to test. We currently don't surface any UI for discontinuous selections (and the name of the variable `prev` is pretty confusing if that were the case).

Handling discontinuous selections is also not what the documentation for the `deleteCells` function says, then then or now. I suspect it was really testing for incorrect behavior.

**Comment by jasongrout** [comment]
That may be true - I don't remember for sure. I do remember trying to test for discontiguous selections when it made sense.

Selections *can* be discontiguous, even if we don't expose a UI for it. So regardless of the test or intent of the test, I think our code should handle that case. Handling discontiguous selections was explicit - so that an extension could make a discontiguous selection and do stuff with it.

**Comment by jasongrout** [comment]
In any case, the code to handle the discontiguous selection case isn't that much more difficult. And we aren't using the convenience methods provided to return a guaranteed contiguous selection, so we should handle the discontiguous case.

**Comment by ian-r-rose** [comment]
The code to test for it *is* kind of subtle, though, since discontinuous selections introduce a bunch of new and distinct cases for what the active cell index should be post-deletion.

**Comment by jasongrout** [comment]
> The code to test for it is kind of subtle, though, since discontinuous selections introduce a bunch of new and distinct cases for what the active cell index should be post-deletion.

The docs just say the new cell is the cell after the last selected cell (if there is a cell after), which I think is very straightforward.

**Comment by ian-r-rose** [comment]
That's fairly straightforward, but I was wondering what the expected behavior is in the case of, say `del([2,5])`  I might expect `3` to be selected.

**Comment by ian-r-rose** [comment]
Although if I try to delete a discontinuous native text selection it places the cursor after the last bit of the multiselection.

**Comment by ian-r-rose** [comment]
Okay, updated for discontinuous selections.

**Comment by jasongrout** [comment]
> Weirdly, the previous tests were correct for the discontinous behavior

I thought I thought through discontinuous selections when doing the tests. Yes, it is weird that it just happened to work out!

**Comment by jasongrout** [comment]
oh nice - since the active cell index is clamped, we can just do the +1 and things just work out if that happens to be beyond the end.

**Comment by jasongrout** [comment]
It's still weird to me that `.reverse()` mutates *and* returns the array. But I guess that's javascript...

**Comment by jasongrout** [comment]
Looks good to me! Thanks!

**Pull request merged**
