### PR TITLE
Update `verdaccio`, start registry on `0.0.0.0` instead of `localhost`

### PR DESCRIPTION
**Pull request by jtpio**
## References

Some CI troubleshooting since the `release_test` check has been failing recently.

## Code changes

- [x] Update the `verdaccio` dependency in `@jupyterlab/buildutils`
- [x] Start the local registry on `0.0.0.0` instead of `localhost`

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
So `playwright` can be installed when passing the registry explicitly with `--registry https://registry.npmjs.org`.

image


Now need to check why the `@jupyterlab` are now failing to install:

```
error An unexpected error occurred: "http://localhost:4873/@jupyterlab%2flauncher: connect ECONNREFUSED ::1:4873".
```

**Comment by fcollonval** [comment]
I'm wondering if we don't get trouble because of the IPv6 addressing. But I don't know if we can go around that. Or maybe we need to use the same trick as for docker using 0.0.0.0 instead of localhost.

**Comment by jtpio** [comment]
> Or maybe we need to use the same trick as for docker using 0.0.0.0 instead of localhost.

Thanks @fcollonval for this it seems like it did the trick: 

image

I'm gonna clean up the other changes and maybe we can still keep the `verdaccio` update in the diff.

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio

**Comment by jtpio** [comment]
Looks like the [failing UI test](https://github.com/jupyterlab/jupyterlab/runs/7412720327?check_suite_focus=true) seems to be coming from the merge of https://github.com/jupyterlab/jupyterlab/pull/11638

**Comment by fcollonval** [comment]
I'm merging this one and going to address the UI tests separately.

**Pull request merged**
