### PR TITLE
Please add corrections to the Documents

### PR DESCRIPTION
**Pull request by BrianBassard**
## References
Cleaned up some of the language in the [Contribution Documentation](https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#writing-documentation).

## Code changes
Removed some unnecessary text in the document. Also added some text to make the documentation more clear.

## User-facing changes
As jlpm is listed later in the doc, I removed that from the header. I also added text to inform
 the user they could skip installing Node.js if they already have it installed on their computer. 

**Before:**
Before 1

**After:**
After 1

Added a small note behind the "pip install -e" command as the text is hard to read.

**Before:**
Before 2

**After:**
After 2

It might be beneficial to play with the text in the documentation so that it is more clear and legible. I'd suggest larger text, commands in bold, or potentially a stronger contrast to reflect command line styling. 

**Example 1:**
Example 1

**Example 2:**
Example 2

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks @BrianBassard!  It looks like you've checked in the generated html file instead of the changes to `contributing.rst`.

**Comment by BrianBassard** [comment]
Sorry about that! @blink1073 do I need to be concerned about the failed Linux Tests?

**Comment by blink1073** [comment]
The latest version looks like it was saved with an extra `.txt` by Windows, you may have to manually rename the file.

**Comment by blink1073** [comment]
> do I need to be concerned about the failed Linux Tests?

The usage test timeout is a known bug.  

The docs build is failing in the build stage.  You can find the output by:
- clicking on "Details",
- Expanding the failing section in the output
- Scrolling down to see the failure output

In this case it isn't because of your PR.

**Comment by blink1073** [comment]
@telamonian it looks like the docs got moved around in #8320

**Comment by BrianBassard** [comment]
@blink1073 It might be a windows thing as all of the `rst` files are followed by `txt`.

**Comment by blink1073** [comment]
Oh I see the disconnect, the file to edit is this one: https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/contributing.rst

**Comment by blink1073** [comment]
Confirmed, #8320 changed the URLs:

before: https://jupyterlab.github.io/jupyterlab/docregistry/interfaces/documentregistry.imodel.html
after:    https://jupyterlab.github.io/jupyterlab/interfaces/_docregistry_src_index_.idocumentwidget.html

**Comment by blink1073** [comment]
Making an issue for the above

**Comment by BrianBassard** [comment]
> Oh I see the disconnect, the file to edit is this one: https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/contributing.rst

Noted! Will correct.

**Comment by blink1073** [comment]
Opened https://github.com/jupyterlab/jupyterlab/issues/8616

**Comment by goanpeca** [comment]
Is this PR still valid @BrianBassard ?

Thanks! :)

**Comment by jweill-aws** [comment]
There hasn't been any activity on this pull request in over a year. As part of an effort to clean up this repository's pull requests, I'm closing this request. If you would still like to merge this code in, please reopen the request and resolve any outstanding merge conflicts. All of the code and comments will remain in place. Thank you for being part of the JupyterLab community!

**Pull request closed without merging**
