### PR TITLE
Fix Benchmark tests (revert #11607)

### LINKED ISSUE #11606: Benchmark tests broken following update of NodeJS in ubuntu image
## Description

[Benchmark tests](https://github.com/jupyterlab/jupyterlab/actions/workflows/benchmark.yml) are failing due to an update of NodeJS in the ubuntu image that is incompatible with CML action (to publish the benchmark image).

```
Error: The module '/usr/local/lib/node_modules/@dvcorg/cml/node_modules/mmmagic/build/Release/magic.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 83.
```

## Reproduce

Execute a benchmark job

## Expected behavior

No error

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
## References

**Follow-up for...**
* Fixes #11606
* #11607

## Code changes

This pull request introduces a better fix for #11606 as per the results of the ongoing investigation at https://github.com/iterative/setup-cml/issues/53#issuecomment-986673390.

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
Can be fixed on our side with https://github.com/iterative/setup-cml/pull/55; nevermind.

**Comment by 0x2b3bfa0** [comment]
Leaving this pull request open just to revert #11607

**Review by casperdcl — APPROVED** [review]

**Comment by fcollonval** [comment]
Thanks a lot for pushing the revert @0x2b3bfa0 

Waiting for the benchmark tests (that are using CML) :crossed_fingers:

**Comment by jtpio** [comment]
Thanks for the quick fix!

**Comment by jtpio** [comment]
CI all green.

**Pull request merged**
