### PR TITLE
Notify command changed

### LINKED ISSUE #4524: Show Left Area toggled command in palette not updated
The toggled state of the "Show Left Area" command is not shown/updated in a command palette when it should be. For example, having the command palette open, click the "Show Left Area" option to untoggle it. Then click on the command palette tab to re-open the left area. For me, the "Show Left Area" command remains untoggled in the command palette, but should be toggled since the left area is now open.

cf #4510

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes #4524, by calling `commands.notifyCommandChanged` in most of the extensions. As discussed in that issue, this is the intended way for rendered commands to know when they should be updated. I am not crazy about this solution since it results in a *lot* of redundant `notifyCommandChanged`, but it should remove edge cases like #4524.

It also involves a *bit* of an abuse of Typescript in a bunch of places, since I am iterating over the keys of the `CommandIDs` namespaces in the extensions (see also [this](https://github.com/Microsoft/TypeScript/issues/10998#issuecomment-248163332) comment). I am happy to entertain other ways to approach that.

### CODE REVIEW

**Comment by sccolbert** [comment]
Rather than notifying for all commands in a namespace, shouldn't you only notify for the ones which are *actually* invalid due to the change.

**Comment by sccolbert** [comment]
Do you think it would make sense to make the command id to `notifyCommandChanged` be optional, and if not provided, the downstream consumer should treat it as a wildcard, and assume that all rendered commands should be refreshed?

The original intent of the signal was to allow fine-grained control of what to re-render on the consumer's end. But the consumers are typically always going to be vdom-ish, then the point might be moot, and we can get away with a coarse grained "registry changed in some unspecified fashion" signal.

**Comment by ian-r-rose** [comment]
From the perspective of just having implemented this, I think the level of granularity required by `notifyCommandChanged` is more of a pain than an asset at the moment, especially with the knowledge that most renderers will use a vdom approach (as you point out).

So something like an optional argument to `notifyCommandChanged` sounds like it would be useful, and simplify the code here.

**Comment by ian-r-rose** [comment]
Also note: the `application-extension` calls `notifyCommandChanged` whenever the layout is modified. With a big-hammer `notifyCommandChanged`, this can take over all the places where more specific instance trackers call that, and they can all be removed.

**Comment by vidartf** [comment]
So if someone triggers a `notifyCommandChanged()` without command ID, all commands of *all* extensions get updated? This seems like a possible performance issue in the future if several "not-perfect" extensions are loaded (e.g. one or more extensions that never pass command id + one extension that performs an expensive operation in a command callback).

**Comment by sccolbert** [comment]
Misbehaving extensions can always kill the app. We can't protect ourselves from that. As it currently stands, I don't know of any code that is actually looking at the command id which changed anyway. The widget just calls `.update()` whenever any command changes. That update is conflated, and the widget uses vdom to render anyway.

**Comment by sccolbert** [comment]
And I think in all likelihood, the widget's which actually render commands will be core-maintained extensions.

**Comment by vidartf** [comment]
> Misbehaving extensions can always kill the app.

Sure, I'm just trying to ensure that it is harder to write a bad extension by accident.

> As it currently stands, I don't know of any code that is actually looking at the command id which changed anyway.

So, whenever anyone calls `notifyCommandChanged`, all of the `isEnabled` callbacks etc. on all commands will be called? These callbacks are the ones I'm concerned about. Consider e.g. this code: https://github.com/jupyter/nbdime/blob/master/packages/labextension/src/plugin.ts#L176-L208  It has some reasonable balances, but it should probably be cleaned up a lot better if this is going to be called a lot.

**Comment by vidartf** [comment]
PS: https://github.com/jupyterlab/jupyterlab/blob/29a939acb8f8d324cda52ae1c3886cbc96203254/packages/apputils/src/toolbar.ts#L230

**Comment by vidartf** [comment]
Looking at things closer, I guess the toolbar code is the only that does things that way (and I was the one who originally contributed that code, before I was very comfortable with phosphor). I assume that code needs a new looking at.

**Comment by ian-r-rose** [comment]
@sccolbert Do you think we can do a patch release of `@phosphor/widgets` with those updates, or should we proceed with this PR as is?

**Comment by jasongrout** [comment]
> Looking at things closer, I guess the toolbar code is the only that does things that way (and I was the one who originally contributed that code, before I was very comfortable with phosphor). I assume that code needs a new looking at.

Also, @gnestor's work on a react-based toolbar might obsolete it?

**Comment by sccolbert** [comment]
@ian-r-rose, I pinged you on another PR with the command palette icon
changes. Wanted to get both of those in at the same time. Can you take a
look at it?

**Comment by ellisonbg** [comment]
With new versions of phosphor widgets out, @ian-r-rose needs to update this PR. Should make it simpler. @afshin can you review this after those changes?

**Comment by ian-r-rose** [comment]
Okay, this is ready for a look. A lot of the logic that was in this PR has now been moved upstream into phosphor, so this is a net simplification of the codebase.

**Pull request merged**
