### PR TITLE
Remove items from the Toolbar

### PR DESCRIPTION
**Pull request by jtpio**
Hi,

I'm currently working on a [third-party extension](https://github.com/jtpio/jupyterlab-topbar) that makes use of the [`Toolbar`](https://github.com/jupyterlab/jupyterlab/blob/91af807f8422ba846bb295c3c87a6c60e05e5869/packages/apputils/src/toolbar.tsx#L177) from `@jupyterlab/apputils`.

For now the `Toolbar` interface lets users add items with a name and insert items at specific locations.

But it would also be useful to be able to remove items from a `Toolbar`, either by providing a name or an index.

It is already possible to set the parent of the item to `null` to remove it from the toolbar, but it requires keeping track of the Widget itself. 

So having methods such as `removeItem` or `removeItemAt` would give more control over the `Toolbar` layout to developers working on third-party extensions, and avoid having to use the lower level `layout.removeWidget` and `layout.removeWidgetAt`.

This change adds `removeItem(name: string)`, but there are other methods to consider:

```typescript
removeItemAt(pos: number)
// not about removing items but also useful for dynamic toolbars
swapItems(first: number, second: number)
swapItems(first: string, second: string)
```

Opening the PR early so this can be discussed before digging into it any further.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
The toolbars (as well as other container widgets) used to have `removeItem` functions, but those functions were removed way back in prehistory (https://github.com/jupyterlab/jupyterlab/issues/2228), since setting the `parent=null` was concluded to be the correct way to do that.

Is there a reason that it is undesirable to keep track of the `Widget` so you can remove it that way?

**Comment by jtpio** [comment]
Thanks @ian-r-rose for the pointer to #2228. I realized afterwards that calling `layout.removeWidget` and `layout.removeWidgetAt` is not the recommended way.

> Is there a reason that it is undesirable to keep track of the `Widget` so you can remove it that way?

I think the main motivation is to be able to remove a widget added by another extension (for instance the notebook extension) without having to look it up manually.

From a user perspective:
```typescript
toolbar.removeItem('save');
```

instead of:
```typescript
const pos = toArray(toolbar.names()).indexOf('save');
let layout = toolbar.layout as PanelLayout;
let widget = layout.widgets[pos];
widget.parent = null;
```

Quick example at: https://github.com/jtpio/potatoes/blob/6c93bda988361ba1d56068b2d88706f8dcebbe6e/toolbar/src/index.ts#L72-L76

**Comment by jasongrout** [comment]
How about this (not tested, but should be at least close to working code)?

```typescript
each(zip(toolbar.names, toolbar.children), ([name, widget]) => { if (name === 'save') {widget.parent = null;} })
```

**Comment by jasongrout** [comment]
> I think the main motivation is to be able to remove a widget added by another extension

I think in general it makes sense to discourage removing toolbar buttons from other extensions, right? Isn't it okay that if you are removing some other extension's feature, it's just a bit hard to remind you that that's not typically something you should do?

**Comment by jasongrout** [comment]
Or perhaps something like:
```typescript
[_, saveWidget] = (find(zip(toolbar.names, toolbar.children), [name, _ ] => name === 'save') || [-1, undefined]);
if (saveWidget) {
    saveWidget.parent = null;
}
```

**Comment by jtpio** [comment]
> I think in general it makes sense to discourage removing toolbar buttons from other extensions, right?

Yes in that case that makes sense.

For now I guess these `removeItem` methods can then live in their own (third party) subclass that extends `Toolbar`.

And also for reference, https://github.com/jupyterlab/jupyterlab/pull/6214/commits/2322e227ae8977ad811bbf790c9999b467b6d35b adds `removeWidgetAt` and uses the prefered `widget.parent = null` for removing items.

**Comment by jtpio** [comment]
Closing this one then.

Thanks @ian-r-rose and @jasongrout for your insights!

**Pull request closed without merging**
