### PR TITLE
Remove pink background from tracebacks

### LINKED ISSUE #7892: Feature Parity: Pink background for exceptions/tracebacks?
## Description

JupyterLab has a pink background:

image

The Classic Notebook doesn't:

image

## Reproduce

1. Run some code that raises an exception

## Expected behavior

Both should have the same background.

To me, it looks nicer without the background, because the pink color clashes with the text colors in the traceback, but this is of course a matter of taste.

## Context

If I'm not mistaken, the pink background was introduced in #1709 (more specifically in https://github.com/jupyterlab/jupyterlab/commit/a8b94adddabac196c630de9c5723c2e4ba0b1550) by @blink1073.

I don't know what the reason for this change was (or if there was a reason at all).

If the change was justified, it should be back-ported to the Classic Notebook, if not, it should be reverted.

### PR DESCRIPTION
**Pull request by mgeier**
## References

Fixes #7892.

## Code changes

Change `stderr` to `stdout`.

## User-facing changes

Less ugliness.

image

## Backwards-incompatible changes

None.

### CODE REVIEW

**Comment by jasongrout** [comment]
I'm +0 on the visual change. This PR goes beyond the visual change and also changes what error data is semantically (i.e., it changes the mimetype of the error data). Are there any other ramifications of that?

**Comment by mgeier** [comment]
> Are there any other ramifications of that?

I have no idea.

If you know a better way to do this, please let me know!

The problem this PR is trying to solve was introduced in https://github.com/jupyterlab/jupyterlab/commit/a8b94adddabac196c630de9c5723c2e4ba0b1550, where this has  been removed:

```js
const ERROR_CLASS = 'jp-OutputWidget-error';
```

... and the `stderr` case has been ab-used for tracebacks.

I would argue that using `stderr` is just as wrong as using `stdout` semantically, but at least when using `stdout` (as this PR suggests), the background color is correct.

In the long term, it would probably be good to re-introduce (or re-discover?) a separate "class" for this case?

But for now, I think this PR is at least a net improvement and a temporary fix.

**Comment by mlucool** [comment]
> Are there any other ramifications of that?

I think this would break [jupyterlab-skip-traceback](https://github.com/deshaw/jupyterlab-skip-traceback). I'm happy to fix the [usage of it]( https://github.com/deshaw/jupyterlab-skip-traceback/blob/master/src/SkipTracebackWidget.ts#L91.) to check for either.

**Comment by jweill-aws** [comment]
There hasn't been any activity on this pull request in over a year. As part of an effort to clean up this repository's pull requests, I'm closing this request. If you would still like to merge this code in, please reopen the request and resolve any outstanding merge conflicts. All of the code and comments will remain in place. Thank you for being part of the JupyterLab community!

**Pull request closed without merging**
