### PR TITLE
Revert "Prevent command shortcuts from preventing user input"

### LINKED ISSUE #15934: Ctrl + f triggle browser's find function, not find in notebook in 4.1.3
as title says, was also fine in 4.1.2

### PR DESCRIPTION
**Pull request by krassowski**
Reverts jupyterlab/jupyterlab#15790

Short-term alternative to https://github.com/jupyterlab/jupyterlab/pull/15913

The reasoning is that while https://github.com/jupyterlab/jupyterlab/pull/15913 does fix the issues reported in the core JupyterLab, jupyterlab/jupyterlab#15790 would have also broken custom shortcuts in extensions, which we cannot workaround the same way.

Fixes https://github.com/jupyterlab/jupyterlab/issues/15936
Fixes https://github.com/jupyterlab/jupyterlab/issues/15912
Fixes #15934
Closes https://github.com/jupyterlab/jupyterlab/pull/15913
Reopens https://github.com/jupyterlab/jupyterlab/issues/15744

### CODE REVIEW

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.1.x

**Comment by diyoyo** [comment]
😢

**Comment by krassowski** [comment]
The problematic shortcuts can be disabled with:

```json
{
  "shortcuts": [
    {
      "args": {},
      "command": "inline-completer:next",
      "keys": [
          "Alt ]"
      ],
      "selector": ".jp-mod-completer-enabled",
      "disabled": true
    },
    {
      "args": {},
      "command": "inline-completer:previous",
      "keys": [
          "Alt ["
      ],
      "selector": ".jp-mod-completer-enabled",
      "disabled": true
    },
    {
      "args": {},
      "command": "inline-completer:invoke",
      "keys": [
          "Alt \\"
      ],
      "selector": ".jp-mod-completer-enabled",
      "disabled": true
    }
  ]
}
```

**Comment by diyoyo** [comment]
@krassowski where is this block supposed to go, please?

**Comment by krassowski** [comment]
Settings → Settings Editor → JSON Settings Editor → Keyboard Shortcuts → User → paste → save

**Pull request merged**
