### PR TITLE
Backport PR #11128 on branch 3.2.x (Run comparative benchmark)

### PR DESCRIPTION
**Pull request by fcollonval**
Manual backport of #11128 

Bump galata version to 4.1.0

### CODE REVIEW

**Comment by fcollonval** [comment]
@jtpio is it the right way to bump galata package?

**Comment by jtpio** [comment]
Looks like it should be fine.

Although on master we are at `4.3.x`:

https://github.com/jupyterlab/jupyterlab/blob/b228e5d6cb4f4cdb5fc9ad09a24ad8accb727508/galata/package.json#L3

So hopefully we won't "catch up" here in the 3.2.x branch.

**Comment by jtpio** [comment]
Kicking CI as only a couple of checks were running.

**Comment by fcollonval** [comment]
> So hopefully we won't "catch up" here in the 3.2.x branch.

:crossed_fingers:

**Pull request merged**
