### PR TITLE
Change max-width for tables to 150px

### LINKED ISSUE #961: New table style truncates columns
Whilst I like the aesthetics of the new table styles introduced in #904 it appears that columns are being truncated so that you can't actually see your data!
image

IMHO it would be good if the columns expanded to fit the size of the content

### PR DESCRIPTION
**Pull request by dhirschfeld**
- Prevents truncation of datetimes
- Fixes #961

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks, let's take this for a spin.

**Comment by jorisvandenbossche** [comment]
@dhirschfeld Would you also like to do this for the classic notebook? (https://github.com/jupyter/notebook/pull/1776)

**Comment by gnestor** [comment]
@dhirschfeld I created a PR on notebook 👍

**Comment by dhirschfeld** [comment]
Beat me to it! Cheers :)

**Pull request merged**
