### PR TITLE
Update reference snapshots for the extension manager

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/12328

## Code changes

~Update sorting logic in the extension manager.~

Update the reference snapshots for the visual regression documentation checks.

## User-facing changes

~The order of the extensions in the extension manager might change and would not depend on the result from the npm query anymore.~

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
This can then be backported to 3.4.x and 3.3.x if needed.

**Comment by jtpio** [comment]
This approach has the downside of discarding the `score` returned by npm:

image

For example if an extension has more downloads it might be more relevant, and it would make sense to keep it higher in the list.

**Comment by jtpio** [comment]
So maybe we can instead just update the reference snapshots for now, and see if the scores change again later.

**Comment by fcollonval** [comment]
Thanks for looking into this @jtpio 

I'm :+1: to update the snapshots for now. A future stabilization would be to dump a npm request result and to serve it as mock answer for the tests.

**Comment by jtpio** [comment]
Just pushed the new snapshots, let's see if the check passes again now.

**Comment by jtpio** [comment]
The check is back to green:

image

> A future stabilization would be to dump a npm request result and to serve it as mock answer for the tests.

Sounds good, we can track that in a separate issue.

**Review by fcollonval — APPROVED** [review]
Thanks a lot @jtpio

**Comment by jtpio** [comment]
CI all green :tada:

**Pull request merged**
