### PR TITLE
Automated Changelog Entry for 3.3.1 on 3.3.x

### PR DESCRIPTION
**Pull request by jasongrout**
Automated Changelog Entry for 3.3.1 on 3.3.x
```
Python version: 3.3.1
npm version: @jupyterlab/repo-top: 0.0.1
npm workspace versions:
@jupyterlab/builder: 3.3.1
@jupyterlab/buildutils: 3.3.1
@jupyterlab/template: 3.3.1
@jupyterlab/application-top: 3.3.1
@jupyterlab/example-app: 3.3.1
@jupyterlab/example-cell: 3.3.1
@jupyterlab/example-console: 3.3.1
@jupyterlab/example-federated: 2.4.1
@jupyterlab/example-federated-core: 2.4.1
@jupyterlab/example-federated-md: 2.4.1
@jupyterlab/example-federated-middle: 2.4.1
@jupyterlab/example-federated-phosphor: 2.4.1
@jupyterlab/example-filebrowser: 3.3.1
@jupyterlab/example-notebook: 3.3.1
@jupyterlab/example-terminal: 3.3.1
@jupyterlab/galata: 4.2.1
@jupyterlab/mock-extension: 3.3.1
@jupyterlab/mock-consumer: 3.3.1
@jupyterlab/mock-provider: 3.3.1
@jupyterlab/mock-token: 3.3.1
@jupyterlab/application: 3.3.1
@jupyterlab/application-extension: 3.3.1
@jupyterlab/apputils: 3.3.1
@jupyterlab/apputils-extension: 3.3.1
@jupyterlab/attachments: 3.3.1
@jupyterlab/cells: 3.3.1
@jupyterlab/celltags: 3.3.1
@jupyterlab/celltags-extension: 3.3.1
@jupyterlab/codeeditor: 3.3.1
@jupyterlab/codemirror: 3.3.1
@jupyterlab/codemirror-extension: 3.3.1
@jupyterlab/completer: 3.3.1
@jupyterlab/completer-extension: 3.3.1
@jupyterlab/console: 3.3.1
@jupyterlab/console-extension: 3.3.1
@jupyterlab/coreutils: 5.3.1
@jupyterlab/csvviewer: 3.3.1
@jupyterlab/csvviewer-extension: 3.3.1
@jupyterlab/debugger: 3.3.1
@jupyterlab/debugger-extension: 3.3.1
@jupyterlab/docmanager: 3.3.1
@jupyterlab/docmanager-extension: 3.3.1
@jupyterlab/docprovider: 3.3.1
@jupyterlab/docprovider-extension: 3.3.1
@jupyterlab/docregistry: 3.3.1
@jupyterlab/documentsearch: 3.3.1
@jupyterlab/documentsearch-extension: 3.3.1
@jupyterlab/extensionmanager: 3.3.1
@jupyterlab/extensionmanager-extension: 3.3.1
@jupyterlab/filebrowser: 3.3.1
@jupyterlab/filebrowser-extension: 3.3.1
@jupyterlab/fileeditor: 3.3.1
@jupyterlab/fileeditor-extension: 3.3.1
@jupyterlab/help-extension: 3.3.1
@jupyterlab/htmlviewer: 3.3.1
@jupyterlab/htmlviewer-extension: 3.3.1
@jupyterlab/hub-extension: 3.3.1
@jupyterlab/imageviewer: 3.3.1
@jupyterlab/imageviewer-extension: 3.3.1
@jupyterlab/inspector: 3.3.1
@jupyterlab/inspector-extension: 3.3.1
@jupyterlab/javascript-extension: 3.3.1
@jupyterlab/json-extension: 3.3.1
@jupyterlab/launcher: 3.3.1
@jupyterlab/launcher-extension: 3.3.1
@jupyterlab/logconsole: 3.3.1
@jupyterlab/logconsole-extension: 3.3.1
@jupyterlab/mainmenu: 3.3.1
@jupyterlab/mainmenu-extension: 3.3.1
@jupyterlab/markdownviewer: 3.3.1
@jupyterlab/markdownviewer-extension: 3.3.1
@jupyterlab/mathjax2: 3.3.1
@jupyterlab/mathjax2-extension: 3.3.1
@jupyterlab/metapackage: 3.3.1
@jupyterlab/nbconvert-css: 3.3.1
@jupyterlab/nbformat: 3.3.1
@jupyterlab/notebook: 3.3.1
@jupyterlab/notebook-extension: 3.3.1
@jupyterlab/observables: 4.3.1
@jupyterlab/outputarea: 3.3.1
@jupyterlab/pdf-extension: 3.3.1
@jupyterlab/property-inspector: 3.3.1
@jupyterlab/rendermime: 3.3.1
@jupyterlab/rendermime-extension: 3.3.1
@jupyterlab/rendermime-interfaces: 3.3.1
@jupyterlab/running: 3.3.1
@jupyterlab/running-extension: 3.3.1
@jupyterlab/services: 6.3.1
@jupyterlab/example-services-browser: 3.3.1
node-example: 3.3.1
@jupyterlab/example-services-outputarea: 3.3.1
@jupyterlab/settingeditor: 3.3.1
@jupyterlab/settingeditor-extension: 3.3.1
@jupyterlab/settingregistry: 3.3.1
@jupyterlab/shared-models: 3.3.1
@jupyterlab/shortcuts-extension: 3.3.1
@jupyterlab/statedb: 3.3.1
@jupyterlab/statusbar: 3.3.1
@jupyterlab/statusbar-extension: 3.3.1
@jupyterlab/terminal: 3.3.1
@jupyterlab/terminal-extension: 3.3.1
@jupyterlab/theme-dark-extension: 3.3.1
@jupyterlab/theme-light-extension: 3.3.1
@jupyterlab/toc: 5.3.1
@jupyterlab/toc-extension: 5.3.1
@jupyterlab/tooltip: 3.3.1
@jupyterlab/tooltip-extension: 3.3.1
@jupyterlab/translation: 3.3.1
@jupyterlab/translation-extension: 3.3.1
@jupyterlab/ui-components: 3.3.1
@jupyterlab/ui-components-extension: 3.3.1
@jupyterlab/vdom: 3.3.1
@jupyterlab/vdom-extension: 3.3.1
@jupyterlab/vega5-extension: 3.3.1
@jupyterlab/testutils: 3.3.1
```

After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | jupyterlab/jupyterlab  |
| Branch  | 3.3.x  |
| Version Spec | next |
| Since | v3.3.0 |

### CODE REVIEW

**Comment by jasongrout** [comment]
Quick question for @jtpio or @blink1073 - does this require a manual forward porting to main?

**Comment by blink1073** [comment]
No, there should be a PR created automatically by the releaser.

**Comment by jasongrout** [comment]
> No, there should be a PR created automatically by the releaser.

Just double-checking - *this* PR was created automatically by the releaser (the changelog workflow), targeting the 3.3.x branch. You're saying there will be another PR created (by the full release workflow??) that ports these changelog entries to main?

**Comment by jasongrout** [comment]
Awesome, it did it!

(Actually, it seems it did it twice, since I had to run publish again after fixing an auth issue with npm. Perhaps that PR creation could run at the end of the publish stage, so that any problems in the publish step that require rerunning publish don't open a second PR?)

**Pull request merged**
