### PR TITLE
Remove datagrid as a singleton

### LINKED ISSUE #7303: Datagrid should not be a singleton
## Description
As of now, datagrid is listed as one of our singletons, and pinned to the 0.1 version.  This prevents extensions from utilizing newer versions of the datagrid since they will be forced to use the older version.  There is no sound reason for the datagrid to be a singleton, so removing it is the easiest solution.  Our existing csv package can continue to use an older version of the datagrid while other extensions like `jupyterlab-hdf` can upgrade to the newer one sooner.  This should be backported to 1.2.

### PR DESCRIPTION
**Pull request by blink1073**
## References
Fixes #7303 

## Code changes
Removes `datagrid` from the list of singletons, which removes it from the `resolutions`.

## User-facing changes
None

## Backwards-incompatible changes
None.  Our csv packages can continue to use the 0.1 version of datagrid while other extensions can use newer versions.

### CODE REVIEW

**Comment by blink1073** [comment]
cc @telamonian @sccolbert

**Comment by telamonian** [comment]
Lemme make sure I have the meaning of singleton straight. If a package is in the `singletonPackages` list, that means:

- It will also have an entry in `resolutions`
- When you try to install an extension, its compatibility is determined by its compatibility with the resolved versions of the packages in `singletonPackages`

Some questions:
- Are there any other important details about singleton packages?
- If a package is in `resolutions` but is not in `singletonPackages`, what exactly happens when you install an extension that depends on that package?

**Comment by blink1073** [comment]
- Right now, the `resolution` field is directly populated from the `singletonPackages` list, using a `~` version of the dependency used in the yarn workspace.   
- `singletonPackages` in general is used to mark packages that have shared state or interfaces.  This can also include `tokens`.  We will still have a concept of `singletonPackages` when we move away from building on the user's machine per https://github.com/jupyterlab/jupyterlab/issues/5672.

**Comment by sccolbert** [comment]
@telamonian Another example is any case where `instanceof` is used by a library on objects which get passed across module boundaries. If two versions of the package which created the prototype is used, the `instanceof` check will fail for one of them.

**Comment by vidartf** [comment]
I made a comment on the issue, but repeating here in a different way to ensure it is seen:

> other extensions can use newer versions.

What happens if someone tries to install that extension in lab 1.1 ?

**Comment by blink1073** [comment]
It would end up with the old version of datagrid unless we also backport to 1.1.

**Comment by jasongrout** [comment]
Thanks!

**Comment by jasongrout** [comment]
@meeseeksdev backport to 1.x

**Pull request merged**
