### PR TITLE
Debugger: check `hasCommand` before calling `notifyCommandChanged`

### PR DESCRIPTION
**Pull request by jtpio**
## References

This should fix https://github.com/jupyterlab/jupyterlab/issues/14023

## Code changes

Make sure a command is registered before calling `notifyCommandChanged`.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Review by fcollonval — COMMENTED** [review]
Thanks @jtpio 

Could we cache the list of commands to notify or make `notifyCommandChanged` call forgiven?

**Comment by jtpio** [comment]
Should we expect the `hasCommand` lookup to be expensive? An alternative could be to surround `notifyCommandChanged` with a try catch.

**Comment by fcollonval** [comment]
> Should we expect the `hasCommand` lookup to be expensive? An alternative could be to surround `notifyCommandChanged` with a try catch.

I don't know - but as they are so many commands in Lab, I guess it is not that cheap. But I'm fine moving forward as is.

**Comment by krassowski** [comment]
> Should we expect the hasCommand lookup to be expensive? An alternative could be to surround notifyCommandChanged with a try catch.

I would say no. Expectations aside, `hasCommand` is currently [implemented as a single `Map.has()` call](https://github.com/jupyterlab/lumino/blob/7438017b3a5a05353ae378f2c0d79799c3ad1533/packages/commands/src/index.ts#L92-L94) which is at least sublinear according to ECMA specification and in practice often implemented as O(1) so we should not worry here.

**Review by krassowski — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
Thanks both for the extra details and feedback.



> Expectations aside, `hasCommand` is currently [implemented as a single `Map.has()` call](https://github.com/jupyterlab/lumino/blob/7438017b3a5a05353ae378f2c0d79799c3ad1533/packages/commands/src/index.ts#L92-L94) which is at least sublinear according to ECMA specification and in practice often implemented as O(1) so we should not worry here.

Right that was also my understanding, thanks for providing this extra context :+1: Also `hasCommand` is used in another places in the JupyterLab code base.

**Pull request merged**
