### PR TITLE
Update changelog for 3.0.7

### PR DESCRIPTION
**Pull request by blink1073**
## References
Updates changelog for upcoming 3.0.7 release.

## Code changes
None

## User-facing changes
Updated changelog

## Backwards-incompatible changes
None

### CODE REVIEW

**Review by afshin — APPROVED** [review]
Thank you!

:+1:

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.0.x

**Comment by blink1073** [comment]
Cutting the release now...

**Comment by blink1073** [comment]
https://pypi.org/project/jupyterlab/3.0.7/

**Pull request merged**
