### PR TITLE
Enhanced settings UI, part 3

### PR DESCRIPTION
**Pull request by afshin**
**Adds a two-column setting editor:**

setting-editor

cc: @ellisonbg @cameronoelsen

### CODE REVIEW

**Comment by blink1073** [comment]
Buttons need styling to account for dark mode:

<image src="https://user-images.githubusercontent.com/2096628/29335435-43093a98-81d0-11e7-90e0-16ec1393eda5.png" width=400>

**Comment by afshin** [comment]
Is this a bugfix in the dark theme or in the setting editor. I mentioned this issue to @cameronoelsen because I thought it would go in the theme.

**Comment by blink1073** [comment]
I don't think the theme should influence a raw `button` node with no additional classes. I think we should use the CSS variables here.

**Comment by blink1073** [comment]
Looks good, thanks!

**Pull request merged**
