### PR TITLE
Remove ensure-max-old-space script

### PR DESCRIPTION
**Pull request by jasongrout**
## References

This change dropping the workaround for Node 10 was originally done in Dec 2019 in #7677, but then reverted in #8112 (to support node 10 in jlab 2.1).

## Code changes

This was a workaround for node 10 that allowed many users to compile JupyterLab without running out of memory (especially if they had lots of extensions installed). It is no longer needed for Node 12 or higher, where memory management is automatic. Node 10 is now in maintenance mode,  (since May 2019) and node 12 is also almost in maintenance mode (starting Nov 2020), so I think we can drop the Node 10 workaround.

Users still on Node 10 will still be able to manually increase their available memory by setting the environment variable NODE_OPTIONS=--max-old-space-size=4096, for example.

### CODE REVIEW

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/is-this-dirty-build-hack-acceptable-to-use-extensions-on-raspberry/6629/6

**Comment by jasongrout** [comment]
Not sure why the debugger test is failing:

```
+ pip install -U xeus-python
ERROR: Could not find a version that satisfies the requirement xeus-python (from versions: none)
ERROR: No matching distribution found for xeus-python
```

**Comment by jasongrout** [comment]
> Not sure why the debugger test is failing:

Ah, I had bumped the python version in the test scripts to 3.9, but I think xeus-python isn't released for python 3.9. I put it back down to python 3.8.

**Comment by jtpio** [comment]
> but I think xeus-python isn't released for python 3.9

That's right. We can bump the python version in the tests to use 3.9 once xeus-python supports it.

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
