### PR TITLE
Upgrade to TypeScript 3.9.2

### PR DESCRIPTION
**Pull request by jasongrout**
## Code changes

Update to Typescript 3.9, which was recently released.

### CODE REVIEW

**Comment by blink1073** [comment]
I'd love to see the time difference from after a `jlpm clean` to run `jlpm build:packages` before and after this change, just out of curiosity.

**Comment by jasongrout** [comment]
> I'd love to see the time difference from after a `jlpm clean` to run `jlpm build:packages` before and after this change, just out of curiosity.

No change - 2 seconds for each. I think the clean is not cleaning a cache.

**Comment by jasongrout** [comment]
I modified the commit message and re-pushed to rerun the tests.

**Comment by jasongrout** [comment]
Looks like an unrelated timeout. Thanks for the approval, @blink1073. Merging.

**Comment by saulshanabrook** [comment]
TODO: Check if this changes the typings emitted. If they don't change then we can merge this into 2.2 release instead of 3.0.

**Pull request merged**
