### PR TITLE
Add .yarnrc explicitly in Python setup

### PR DESCRIPTION
**Pull request by afshin**
## Code changes

Adds `.yarnrc` explicitly in Python setup

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by jasongrout** [comment]
Do we need a 2.0.3 for this?

**Comment by afshin** [comment]
> Do we need a 2.0.2 for this?

I think this should be back-ported to 1.2.x and also a patch release for 2.0.x, but as it's not a security consideration, I don't think it's critical how quickly we do it.

**Comment by jasongrout** [comment]
Thanks!

**Comment by jasongrout** [comment]
Since *this* PR will be released in 2.1, I changed the milestone to 2.1. The backport PR would be milestone 2.0 or 2.0.2...

**Comment by blink1073** [comment]
@meeseeksdev backport to 1.x

**Pull request merged**
