### PR TITLE
Force rerendering if changes happen during an update.

### LINKED ISSUE #14385: "Click to add a cell" is flaky on CI
> `jupyterlab/galata/test/jupyterlab/notebook-create.test.ts-snapshots/run-cells-jupyterlab-linux.png` needs to be fixed as the expectation is incorrect/"click to add a cell is" problematic here:

run-cells-expected

_Originally posted by @krassowski in https://github.com/jupyterlab/jupyterlab/issues/14344#issuecomment-1509848101_

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #14385

> Thanks a lot to @gabalafou for the reproducible test and @krassowski to find the root cause.

## Code changes

Force re-rendering the notebook if a change happens during a update.

## User-facing changes

The viewport content and height should be updated when needed.

## Backwards-incompatible changes

None

### CODE REVIEW

**Review by gabalafou — COMMENTED** [review]
I can confirm that this fixes https://github.com/jupyterlab/jupyterlab/issues/14385.

I think you're probably right that there's a bug here—as in, if an update is requested while a scroll repaint is queued, then we probably need to request another update after the scroll repaint is executed. (In the case of issue 14385, here's [the update request that happens while the scroll repaint is queued](https://github.com/jupyterlab/jupyterlab/blob/acb87d51ed0c489fb5a8f6781059024cf62f255b/packages/notebook/src/actions.tsx#L2222).)

However, I wonder if there's another bug at play. I was trying  to understand why `shift` + `enter` (run cell) was fine whereas `ctrl`/`accel` + `enter` (run cell and advance) was not, and this led me to some lines in the widget resize handler in the `WindowedList` class:

https://github.com/jupyterlab/jupyterlab/blob/acb87d51ed0c489fb5a8f6781059024cf62f255b/packages/ui-components/src/components/windowedlist.ts#L1048-L1058
The reason why the simple "run" commands work correctly is because they do NOT call `WindowedList.scrollToItem`, so when the markdown cell widget is resized, the second block of the above if-else, which calls `WindowedList.update`, is followed. But "run and advance" calls `WindowedList.scrollToItem`, which sets `this._scrollToItem`, so the widget resize handler follows the first block of the if-else, which doesn't request an update. 

I'm not familiar enough with the `WindowedList` class to understand the intent behind this if-else, but it seems a mistake not to queue an update request on when one of the widgets has triggered a resize event and the total size of notebook has changed.

I wonder if the code above should be:

```ts
   // If some sizes changed 
   if (this.viewModel.setWidgetSize(newSizes)) { 
     // Update the list 
     if (this._scrollToItem) { 
       this.scrollToItem(...this._scrollToItem).catch(reason => { 
         console.log(reason); 
       }); 
     }
     this.update(); 
   } 
```

**Comment by krassowski** [comment]
I did not have time to delve further, but just leaving a note to highlight that `Notebook Create › Run cells` is still failing on this PR in `UI Tests / Visual Regression Tests (pull_request)`.

**Comment by fcollonval** [comment]
Thanks @gabalafou I implemented your suggestion and the test works for me locally.

With only that `this.update` forced all the time your reproducible case is solved also. But I kept the original update re-trigger as indeed it seems required.

Let's see what is the CI test result now.

**Comment by fcollonval** [comment]
All tests are green. Merging it to include it in the next rc.

**Pull request merged**
