### PR TITLE
Update react-json-tree to 0.15.0

### PR DESCRIPTION
**Pull request by jtpio**
## References

Follow-up to https://github.com/jupyterlab/jupyterlab/issues/9297.

## Code changes

Dependency update for `react-json-tree` which should help fix warnings with react 17 as peer dependency.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Review by jasongrout — APPROVED** [review]
Looks good to me, thanks! I'm not sure if the failing test is relevant to this change.

**Comment by jasongrout** [comment]
On second thought, since this is just a warning that doesn't seem to harm anything, I don't think it's necessary to backport to 3.0.x.

**Comment by jtpio** [comment]
> I'm not sure if the failing test is relevant to this change.

I think the `examples` check has also failed for some of the other recent PRs. Just restarted it to see if it passes.

**Comment by jasongrout** [comment]
Thanks!

**Pull request merged**
