### PR TITLE
Run memory-leak tests on PR

### LINKED ISSUE #4359: Detect memory leaks
I recently talked to one of the researchers behind the [BLeak: Automatically Debugging Memory Leaks in Web Applications](https://github.com/plasma-umass/BLeak) project. It let's you define some state transitions for a web application and detect what memory was allocated that hasn't been reclaimed when you go back to the starting state.

For example, repeatedly opening a notebook, then closing it and stopping the server shouldn't grow the memory consumption. Same with creating and deleting a cell.

With this project, we could write tests for those things and see if we have memory leaks and try to find where they are coming from.

As a very simple first test, I just opened the Memory tab of the chrome debugger and saw that it went from 20MB up to like 60MB, increasing after I opened and closed the same notebook multiple times.

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Closes #4359

## Code changes

N/A

Use memory leak tests from `jupyterlab/benchmarks` repository after a PR has been approved or following the request `please run benchmarks` as PR comment.

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by fcollonval — COMMENTED** [review]
please run benchmark

**Review by fcollonval — COMMENTED** [review]
please run benchmark

**Review by fcollonval — COMMENTED** [review]
please run benchmark

**Review by fcollonval — COMMENTED** [review]
please run benchmark

**Review by fcollonval — COMMENTED** [review]
please run benchmark

**Review by fcollonval — COMMENTED** [review]
please run benchmark

**Review by fcollonval — COMMENTED** [review]
please run benchmark

**Comment by fcollonval** [comment]
CI failure is not related

**Comment by jtpio** [comment]
Looks like the CI failure might be relevant?

```
{"code":"ENOENT","errno":-2,"level":"error","message":"ENOENT: no such file or directory, stat './benchmark-results/lab-benchmark.svg'","path":"./benchmark-results/lab-benchmark.svg","stack":"Error: ENOENT: no such file or directory, stat './benchmark-results/lab-benchmark.svg'","syscall":"stat"}
```

**Comment by fcollonval** [comment]
> Looks like the CI failure might be relevant?

It is not - it is due to the branch pre-dating the switch to SVG output for benchmark report. We should merge it as soon as possible because new memory leaks have already appeared since a month and the PR authors are not notified.

**Comment by jtpio** [comment]
OK thanks.

Just did a quick rebase so it's on top of the latest `master`.

**Review by jtpio — APPROVED** [review]
Thanks!

Diff looks good, pending CI checks to complete.

**Comment by fcollonval** [comment]
Thanks @jtpio

**Pull request merged**
