### PR TITLE
Update maintainers affiliation

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Update some affiliation on the README

@marthacryan I updated yours - is it ok?
@krassowski Does your affiliation need to be changed?

## Code changes

None

## User-facing changes

none

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @fcollonval!

Curious if we should continue maintaining this list in the JupyterLab repo? Or just link to https://jupyterlab-team-compass.readthedocs.io/en/latest/team.html, which already contains the current list of council members?

**Comment by fcollonval** [comment]
> Curious if we should continue maintaining this list in the JupyterLab repo? Or just link to https://jupyterlab-team-compass.readthedocs.io/en/latest/team.html, which already contains the current list of council members?

Less maintenance is always good. It raises three questions:
- is the council a superset of the maintainers?
- is it ok to link the coming new frontend council?
- what about the "emeritus"? - I guess that list could be published on the team-compass too.

**Comment by fcollonval** [comment]
I opened an issue on the team-compass. So we can move forward with this while pushing forward the discussion.

**Review by jtpio — APPROVED** [review]
Thanks!

Maybe can wait a bit for @marthacryan to check if it looks good too?

**Comment by krassowski** [comment]
Just checking back @marthacryan?

**Pull request merged**
