### PR TITLE
Use posix paths explicitly

### LINKED ISSUE #11030: `jlpm run build` command modifies json files on windows due to path style differences
## Description

Following the [instructions](https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#installing-jupyterlab) on the contributing guidelines, running `jlpm run build` on windows results in changes to some of the json files.

<details><summary>git status output</summary>
<pre>
        modified:   builder/tsconfig.json
        modified:   buildutils/template/tsconfig.json
        modified:   buildutils/tsconfig.json
        modified:   galata/tsconfig.json
        modified:   packages/application-extension/tsconfig.json
        modified:   packages/application/tsconfig.json
        modified:   packages/apputils-extension/tsconfig.json
        modified:   packages/apputils/tsconfig.json
        modified:   packages/attachments/tsconfig.json
        modified:   packages/cells/tsconfig.json
        modified:   packages/celltags-extension/tsconfig.json
        modified:   packages/celltags/tsconfig.json
        modified:   packages/codeeditor/tsconfig.json
        modified:   packages/codemirror-extension/tsconfig.json
        modified:   packages/codemirror/tsconfig.json
        modified:   packages/completer-extension/tsconfig.json
        modified:   packages/completer/tsconfig.json
        modified:   packages/console-extension/tsconfig.json
        modified:   packages/console/tsconfig.json
        modified:   packages/coreutils/tsconfig.json
        modified:   packages/csvviewer-extension/tsconfig.json
        modified:   packages/csvviewer/tsconfig.json
        modified:   packages/debugger-extension/tsconfig.json
        modified:   packages/debugger/tsconfig.json
        modified:   packages/docmanager-extension/tsconfig.json
        modified:   packages/docmanager/tsconfig.json
        modified:   packages/docprovider-extension/tsconfig.json
        modified:   packages/docprovider/tsconfig.json
        modified:   packages/docregistry/tsconfig.json
        modified:   packages/documentsearch-extension/tsconfig.json
        modified:   packages/documentsearch/tsconfig.json
        modified:   packages/extensionmanager-extension/tsconfig.json
        modified:   packages/extensionmanager/tsconfig.json
        modified:   packages/filebrowser-extension/tsconfig.json
        modified:   packages/filebrowser/tsconfig.json
        modified:   packages/fileeditor-extension/tsconfig.json
        modified:   packages/fileeditor/tsconfig.json
        modified:   packages/help-extension/tsconfig.json
        modified:   packages/htmlviewer-extension/tsconfig.json
        modified:   packages/htmlviewer/tsconfig.json
        modified:   packages/hub-extension/tsconfig.json
        modified:   packages/imageviewer-extension/tsconfig.json
        modified:   packages/imageviewer/tsconfig.json
        modified:   packages/inspector-extension/tsconfig.json
        modified:   packages/inspector/tsconfig.json
        modified:   packages/javascript-extension/tsconfig.json
        modified:   packages/json-extension/tsconfig.json
        modified:   packages/launcher-extension/tsconfig.json
        modified:   packages/launcher/tsconfig.json
        modified:   packages/logconsole-extension/tsconfig.json
        modified:   packages/logconsole/tsconfig.json
        modified:   packages/mainmenu-extension/tsconfig.json
        modified:   packages/mainmenu/tsconfig.json
        modified:   packages/markdownviewer-extension/tsconfig.json
        modified:   packages/markdownviewer/tsconfig.json
        modified:   packages/mathjax2-extension/tsconfig.json
        modified:   packages/mathjax2/tsconfig.json
        modified:   packages/metapackage/tsconfig.json
        modified:   packages/nbformat/tsconfig.json
        modified:   packages/notebook-extension/tsconfig.json
        modified:   packages/notebook/tsconfig.json
        modified:   packages/observables/tsconfig.json
        modified:   packages/outputarea/tsconfig.json
        modified:   packages/pdf-extension/tsconfig.json
        modified:   packages/property-inspector/tsconfig.json
        modified:   packages/rendermime-extension/tsconfig.json
        modified:   packages/rendermime-interfaces/tsconfig.json
        modified:   packages/rendermime/tsconfig.json
        modified:   packages/running-extension/tsconfig.json
        modified:   packages/running/tsconfig.json
        modified:   packages/services/examples/browser/tsconfig.json
        modified:   packages/services/examples/typescript-browser-with-output/tsconfig.json
        modified:   packages/services/tsconfig.json
        modified:   packages/settingeditor-extension/tsconfig.json
        modified:   packages/settingeditor/tsconfig.json
        modified:   packages/settingregistry/tsconfig.json
        modified:   packages/shared-models/tsconfig.json
        modified:   packages/shortcuts-extension/tsconfig.json
        modified:   packages/statedb/tsconfig.json
        modified:   packages/statusbar-extension/tsconfig.json
        modified:   packages/statusbar/tsconfig.json
        modified:   packages/terminal-extension/tsconfig.json
        modified:   packages/terminal/tsconfig.json
        modified:   packages/theme-dark-extension/tsconfig.json
        modified:   packages/theme-light-extension/tsconfig.json
        modified:   packages/toc-extension/tsconfig.json
        modified:   packages/toc/tsconfig.json
        modified:   packages/tooltip-extension/tsconfig.json
        modified:   packages/tooltip/tsconfig.json
        modified:   packages/translation-extension/tsconfig.json
        modified:   packages/translation/tsconfig.json
        modified:   packages/ui-components-extension/tsconfig.json
        modified:   packages/ui-components/tsconfig.json
        modified:   packages/vdom-extension/tsconfig.json
        modified:   packages/vdom/tsconfig.json
        modified:   packages/vega5-extension/tsconfig.json
        modified:   testutils/tsconfig.json
        modified:   tsconfigdoc.json
</pre>
</details>

## Expected behavior
These files should not be modified.

## Context

- Operating System and version: Windows 10
- Browser and version: 
- JupyterLab version: Latest source on master commit - https://github.com/jupyterlab/jupyterlab/commit/094056ad2d728327dbeef26aabeee29ece584487

### PR DESCRIPTION
**Pull request by Mithil467**
## References
Fixes #11030 

## Code changes

1. Using `path.posix.join` instead of `path.join` (only where needed).
2. Using `.replace('\\', '/')` to convert win path to posix.
3. Commit updated format for the json files not regarding paths.

Turns out there is no inbuilt function in Node.js path module to convert win paths to posix. Hence used replace.

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thank you!

**Comment by blink1073** [comment]
The codeql failure looks legitimate, probably needs a fix like [this](https://dmitripavlutin.com/replace-all-string-occurrences-javascript/#2-replace-with-a-global-regular-expression)

**Review by goanpeca — APPROVED** [review]

**Comment by Mithil467** [comment]
> 
> 
> The codeql failure looks legitimate, probably needs a fix like [this](https://dmitripavlutin.com/replace-all-string-occurrences-javascript/#2-replace-with-a-global-regular-expression)

Oh yes, thanks! Fixed it.🙌🏼

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.1.x

**Comment by Mithil467** [comment]
Should I follow these instructions and try backporting?

**Comment by blink1073** [comment]
> Should I follow these instructions and try backporting?

Yes, please!

**Pull request merged**
