### PR TITLE
Give answered issues action permission to write

### PR DESCRIPTION
**Pull request by jasongrout**
## References

Follow up to #10575 

## Code changes

It seems the action is running now, but does not have permission to make changes. This gives the appropriate permission.

### CODE REVIEW

**Comment by jasongrout** [comment]
This also overrides the defaults for PRs so we don't automatically close them.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jasongrout** [comment]
It worked! https://github.com/jupyterlab/jupyterlab/runs/3034013346?check_suite_focus=true#step:2:1165

**Comment by blink1073** [comment]
Nice!

**Pull request merged**
