### PR TITLE
Add support for Gitpod editor

### PR DESCRIPTION
**Pull request by saulshanabrook**
Getting set up to contribute to JupyterLab can be time-consuming and daunting for new contributors. [Gitpod](https://gitpod.io/) is a way to edit open-source projects, in your browser, for free. It is similar to Github Codespaces, but unlike codespaces, is available for anyone. I have added a file to set up Gitpod, so that anyone could use it to edit JupyterLab and push their changes back.

This also enables "prebuilds" so that on every push to different branches, it will rebuild the project, so that when it opens up, it's pretty quick to start up! It takes under two minutes from my timing.

It doesn't enable any Github checks or comments for prebuilds on PRs, do avoid adding more noise. Although we could do that here, or at a later date. 

To try out this PR, [launch Gitpod from my fork](https://gitpod.io/#https://github.com/saulshanabrook/jupyterlab). Here is a GIF of trying it out!

You can see that the first automatic launch doesn't work (I think because the domain isn't right. Might be able to fix this). But if you click and open the port, either in the iframe or in a new page, that does work.

If this is merged in then new users can try it out, even if it isn't perfect. Until then, it's a little hard for new contributors to user gitpod, since they have to add this commit first, then add on top of it. 

## References

Replaces outdated PR I opened a while ago https://github.com/jupyterlab/jupyterlab/pull/7896

## Code changes

Adds config file for Gitpod and adds a link to readme

## User-facing changes

Screen Shot 2021-03-01 at 12 59 25 PM

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by trallard** [comment]
Hey Saul this looks great - I just checked this and have some suggestions:

- It would be worth adding some extensions to help folks with their development 

For example, to add prettier:

```yaml
vscode:
  extensions:
      - esbenp.prettier-vscode@5.9.2:/ZjVG4nabMGxTqOcyglnfQ==
```

-  From the docs: the suggested way to build the docs is by creating a conda env and then using the familiar `make html` command. It would be nice to have this done in the rebuild (conda env creation + build the docs)
- Of course the above implies that we would need to install conda beforehand.  I recently did this for Scipy (see [Scipy's gitpod.yaml](https://github.com/scipy/scipy/blob/master/.gitpod.yml) so can lend a hand if needed

**Comment by saulshanabrook** [comment]
Thanks, @trallard for the suggestions!

I will add some useful extension and have it build the docs (maybe the typedoc as well? I see we support building it, not sure where it's deployed). Maybe also get Sphinx to spin up a server so that they are served and can be viewed easily as well?

I opened #9891 to deal with the fact that the documentation install docs are out of date.

**Comment by trallard** [comment]
For docs - when working on Scipy I tried using `sphinx-autobuild` inside gitpod but perhaps due to how big their docs this was a bit too slow.  So an easy workaround was to build the docs as per usual and add the [liveserve extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) to check the output HTML. 

There is also this [restructured text extension](https://github.com/vscode-restructuredtext/vscode-restructuredtext) which I use locally quite a fair bit and tried it in Gitpod. The only cons I see with this is that it sometimes picks up the wrong Python interpreter and/or location of the `cponf.py` but this can be worked around adding a `.thea/settings.json` or `.vscode/settings.json` depending on the IDE you're using in gitpod (think in this case it's Thea)

**Review by jasongrout — APPROVED** [review]
This works really well, thanks Saul!

Would you prefer us merging this as-is and addressing Tania's enhancement suggestions on a different PR, or would you prefer us holding off on merging this for now?

**Comment by saulshanabrook** [comment]
Hey @jasongrout, if we wanted to merge this as is, I can open an issue for @trallard's suggestions.

That sounds good to me, since it "working" as is, even if not ideal.

**Comment by jasongrout** [comment]
Great, thanks again!

**Comment by saulshanabrook** [comment]
I opened #9928, thanks Jason and Tania!

**Pull request merged**
