### PR TITLE
Upgrade to React 17

### PR DESCRIPTION
**Pull request by tibdex**
## Code changes

This upgrades the version of React-related packages in `yarn.lock` and all the `package.json` to use React 17.

## User-facing changes

React 17 enables gradual React upgrades as explained in [their release notes](https://reactjs.org/blog/2020/10/20/react-v17.html#gradual-upgrades). I find it especially interesting for JupyterLab and its ecosystem of extensions. Indeed, it means that once React 18 comes out, a JupyterLab end-user could have one extension using React 18 and another one still using React 17 both coexisting without any issues.

## Backwards-incompatible changes

They are described too in [the release notes](https://reactjs.org/blog/2020/10/20/react-v17.html#other-breaking-changes) which mention:

> We’ve only had to change fewer than twenty components out of 100,000+ in the Facebook product code to work with these changes, so we expect that most apps can upgrade to React 17 without too much trouble.

### CODE REVIEW

**Comment by tibdex** [comment]
Do you think this could still be part of #8038 and the [3.0 milestone](https://github.com/jupyterlab/jupyterlab/milestone/48)?

**Comment by jasongrout** [comment]
Thanks. This also changes all of the `~` semver ranges to `^` - was that intentional?

**Comment by tibdex** [comment]
> This also changes all of the ~ semver ranges to ^ - was that intentional?

Most of the dependencies in the repo are declared with a `^`. I don't see what makes React dependencies special so I thought it would be more consistent to use `^` too instead of `~`.

If there is a reason for using `~` or if you prefer not to change that at the moment, I can switch back to`~`.

**Comment by jasongrout** [comment]
Git blame shows https://github.com/jupyterlab/jupyterlab/commit/8a0cb9a33cc6e7c37faea94785e3a7112cf5d70d (PR #3133) as the commit that switches from `^` to `~`. It doesn't give a reason there. IIRC, there was some discussion in the past about incompatibilities with various minor upgrades of react, so it was deemed safer to constrain to patch versions. Anyone else want to weigh in that remembers subtleties of react in jlab? @ian-r-rose, do you happen to remember?

**Comment by jtpio** [comment]
> Do you think this could still be part of #8038 and the 3.0 milestone?

Sounds like a good candidate for 3.0, especially if it can ease the workflow for extension authors.

**Comment by jasongrout** [comment]
I thought we were probably too close to 3.0, and historically upgrades across major versions have been tricky enough, that this wouldn't get enough testing to make it in to 3.0, at least unless someone volunteered. I realize it's supposed to be an easy upgrade, but it still is an upgrade that carries some risk and requires some energy for testing. Is there someone here that can do this testing and commit to fixing any fallout (or revert, I suppose), and who can also test what the effect is on extension authors maintaining a react component?

**Comment by tibdex** [comment]
> Is there someone here that can do this testing

If you have a manual test script to cover most of the JupyterLab supported interactions, I can try to follow it on this branch and see if everything still works.

**Comment by jtpio** [comment]
Not sure there is a test script, but the React widget example could be one of the first third-party extensions to check: https://github.com/jupyterlab/extension-examples/tree/master/react/react-widget

There are also other examples out there that make extensive use of React, for example: https://github.com/mamba-org/gator (aka `jupyter_conda`).

**Comment by tibdex** [comment]
I forked the extension examples and quickly [migrated `react-widget` (not the other workspace packages) to React 17](https://github.com/tibdex/extension-examples/commit/43e6d429751aa715904727c8c085e141317b2331). Then, I installed the extension on JupyterLab built from this branch.

I also made sure that React 17 was the only version used in all the workspace packages used by the JupyterLab app:

Screenshot 2020-11-04 at 17 29 54

Finally, I rebuilt JupyterLab with the `react-widget` extension enabled and started it. We can see that it works without errors:

jupyterlab-3-react-17

Of course, the `react-widget` extension doesn't do much, but I can confirm that this PR also works well with more feature-rich extensions such as the next version of the React-based [atoti extension](https://medium.com/atoti/dynamic-pivot-tables-in-notebooks-atoti-e4e4fd334ebc) I'm currently working on.

**Review by afshin — APPROVED** [review]
Thank you!

**Comment by jtpio** [comment]
Thanks @tibdex! 

We decided to include that change so it can be tested in the next rc release.

**Comment by jasongrout** [comment]
Thanks!

**Comment by fcollonval** [comment]
Small comment

blueprintjs added React 17 as peer dependency: https://github.com/palantir/blueprint/pull/4403
And everything is working for them. So this is a double good news for JupyterLab:
- No problem should be raised by blueprintjs dependency
- React 17 seems to fulfill its promise to be a transparent upgrade

> [material-ui](https://github.com/mui-org/material-ui/pull/23311) did the update too without much troubles neither except for a the clickaway listener.

**Pull request merged**
