### PR TITLE
Enable `full` notebook windowing mode by default

### PR DESCRIPTION
**Pull request by krassowski**
## References

- Closes https://github.com/jupyterlab/jupyterlab/issues/15258
- https://github.com/jupyterlab/jupyterlab/issues/15801

## Code changes

Enables `full` notebook windowing mode by default to gather wider user feedback during JupyterLab 4.2.0 pre-release testing. If we do not get far enough with tackling issues from https://github.com/jupyterlab/jupyterlab/issues/15258 before 4.2.0 we can revert this PR.

## User-facing changes

JupyterLab works faster when long notebooks are open.

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Linking to https://github.com/jupyter/notebook/issues/7231 as something we will likely want to fix if this becomes the default.

Unless Notebook still defaults to `defer` to avoid issues originally spotted in https://github.com/jupyter/notebook/pull/6855 (not sure these still apply though)

**Comment by krassowski** [comment]
Thanks, I added https://github.com/jupyter/notebook/issues/7231 to the list in https://github.com/jupyterlab/jupyterlab/issues/15258.

Looking at visual regression CI failures, something to consider is whether we want to pin some tests to use `defer` mode, or whether we want more tests to run in both `defer` and `full` mode. I think both solutions may be desirable, depending on specific test.

**Comment by krassowski** [comment]
```
[galata] › test/galata/notebook.spec.ts:22:7 › Notebook Tests › Create Markdown cell ───────────
```

| Before | After |
|---|--|
| image | image |


This one was taking snapshots of the entire main area; I think we should not do that.

**Comment by krassowski** [comment]
bot please update snapshots

**Comment by krassowski** [comment]
@gabalafou I hope the trimming of snapshots in this PR will make you happy :)

**Review by fcollonval — APPROVED** [review]
Thanks @krassowski

**Pull request merged**
