### PR TITLE
Update lumino

### PR DESCRIPTION
**Pull request by hbcarlos**
Update to latest lumino.

https://github.com/jupyterlab/lumino/releases/tag/v2022.1.13

## References
Needed here https://github.com/jupyterlab/jupyterlab/pull/11650

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

The failing Visual Regression check might be relevant: https://github.com/jupyterlab/jupyterlab/runs/4778247801?check_suite_focus=true

I restarted it just to double check

**Comment by fcollonval** [comment]
I confirm that the visual regression are legit and should be investigated.

**Comment by hbcarlos** [comment]
I updated the PR to use the new release with the fix.

I don't understand what is going on with this test https://github.com/jupyterlab/jupyterlab/runs/4818857443?check_suite_focus=true.
It looks like the integrity check went well, but the clean-up failed.

**Comment by jtpio** [comment]
> I don't understand what is going on with this test https://github.com/jupyterlab/jupyterlab/runs/4818857443?check_suite_focus=true.

Looks like the newer re-run passed: https://github.com/jupyterlab/jupyterlab/actions/runs/1698403527

**Comment by jtpio** [comment]
And this one is expected to fail because of too many labels being applied:

image

**Comment by hbcarlos** [comment]
Thanks, @jtpio!!

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by hbcarlos** [comment]
What is missing here to merge it?

**Comment by jtpio** [comment]
Looks like this should be good to go, thanks Carlos!

**Pull request merged**
