### PR TITLE
Add missing print_function import

### PR DESCRIPTION
**Pull request by dhirschfeld**
Partially? fixes https://github.com/conda-forge/jupyterlab-feedstock/pull/45

### CODE REVIEW

**Comment by sccolbert** [comment]
I'm not sure there is consensus yet on whether JLab will be Python 3 only. Given that IPython 6 is Python 3 only, it may not be unreasonable: 
https://github.com/jupyterlab/jupyterlab/issues/2063#issuecomment-296190323

**Comment by dhirschfeld** [comment]
I'm fine with having JLab support py3 only since I've already long ago made the move myself.

It would be just as easy to remove py27 from the CI on conda-forge but I'll let Steve make that call since he seems to be the maintainer of that recipe.

I guess the counter argument is that it really doesn't take much to continue py27 support for at least this release since it's just a one-liner which can easily be removed with any other py2-isms when support is properly dropped.

**Comment by blink1073** [comment]
Given that our `setup.py` explicitly lists Python 2.7 support, I'd consider this a bug for the 0.20 release and we can address the wider issue in https://github.com/jupyterlab/jupyterlab/issues/2096.

**Comment by blink1073** [comment]
Thanks, @dhirschfeld!

**Comment by blink1073** [comment]
@MeeseeksDev backport to 0.20.x

**Pull request merged**
