### PR TITLE
Use jupyter_alabaster_theme in docs

### PR DESCRIPTION
**Pull request by charnpreetsingh**
- renamed tutorial to docs
- removed `sphinx_rtd_theme` and added `jupyter_alabaster_theme` dependency
- commented `html_static_path` as current docs does not use any custom style sheets

Based off from documentation theme work done [here](https://github.com/jupyter/jupyter-alabaster-theme)

### CODE REVIEW

**Comment by ellisonbg** [comment]
The Travis build is failing on the `npm run docs` command in `packages/all-packages`. It is trying to write the typdoc docs to `docs`, which this PR is now using for the Sphinx docs. Not sure of the best way to move Sphinx docs to `docs` without this collision. Maybe we can build the API docs in `docs/api`?

**Comment by blink1073** [comment]
That sounds right, I'll make a PR that moves our API docs.

**Comment by charnpreetsingh** [comment]
Looks like Travis is breaking here: https://github.com/jupyterlab/jupyterlab/blob/8b968bc8e0ec7f96c58ba6009f5809142c0a27c5/scripts/travis_script.sh#L54

**Comment by blink1073** [comment]
:boom:, thanks!

**Pull request merged**
