### PR TITLE
Update sharing config in the jupyterlab metadata.

### LINKED ISSUE #8953: Extensions should be able to specify module sharing options for dependencies
### Problem

In JLab 3.0 right now, there is no way for an extension to specify that certain dependencies should not be bundled, or should be considered singletons, i.e., options in the module federation. It would be very useful if they could to cut down on code size. For example, ipywidget custom widgets should be able to specify that the base widget package is a singleton and not imported (bundled), since it will be provided by the system. (It has to be provided by the system, since it provides a token we use).

### Proposed Solution

Perhaps such information can be listed in the package.json jupyterlab key and used to modify the webpack config when compiling.

### PR DESCRIPTION
**Pull request by jasongrout**
## References

Fixes #8953

## Code changes

This makes the sharing config more powerful to cover common usecases, and makes it simpler to understand and to map to the webpack config.

### CODE REVIEW

**Comment by jasongrout** [comment]
I tested this manually with ipywidgets and it seems each option is working as designed.

**Comment by jasongrout** [comment]
Lint passes now.

**Comment by jasongrout** [comment]
I use this config in the widget cookiecutter: https://github.com/jupyter-widgets/widget-ts-cookiecutter/pull/83/files#diff-ed379f0cb0c8d64f686075d5bee0a9a7R96 (part of https://github.com/jupyter-widgets/widget-ts-cookiecutter/pull/83)

**Comment by vidartf** [comment]
Oh, so no change is needed in ipywidgets packages themselves?

**Comment by jasongrout** [comment]
> Oh, so no change is needed in ipywidgets packages themselves?

ipywidgets doesn't need a change. It's providing the base package to the system, so it definitely needs to import it, and the singleton switch is just about what you are willing to accept, not imposing anything on anyone else.

It's the custom widgets *using* the token that have to say the token package is a singleton (i.e., use the system version, not my own), and to not import it (because someone else will be providing that package to the system, namely the widgets extension).

**Comment by jasongrout** [comment]
This should all probably go into a widgets upgrade guide :)

**Comment by vidartf** [comment]
> the singleton switch is just about what you are willing to accept, not imposing anything on anyone else

Right, but this does mean that we are putting a higher technical burden on widget extension authors (more magical boilerplate for typical defaults in order to enable more esoteric uses elsewhere). It is already quite a barrier to entry for writing high level widget extensions (getting a classic bundle, a lab extension, a CDN bundle, etc), and keeping them up to date. At some point a disting tool might be a more practical place to put the logic rather than keeping it all in the cookiecutters + individual repos.

**Comment by jasongrout** [comment]
You mean a widget-specific build tool that includes this boilerplate?

**Comment by vidartf** [comment]
Yeah, I'll keep it in mind when upgrading some widget extensions now for lab3, and see if I can come up with some pattern of use that would make sense.

**Comment by jasongrout** [comment]
That would be great if we could follow the pattern we're using in jlab, where we have a build tool that automatically creates all the various notebook and lab bundles needed for a widget. +1!

**Pull request merged**
