### PR TITLE
decode url link targets

### LINKED ISSUE #5153: Urls with space aren't rendered correctly
Links to local files that have space in their names aren't rendered as links in jupyter lab. Example:
folder: https://github.com/jupyter-widgets/ipywidgets/tree/master/docs/source/examples
notebook: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Index.ipynb
Same thing with jupyter notebook. Changing space to %20 helps for jupyter notebooks whicle jupyter lab starts to render the text as link, but still can't open the file which it refers to.
example

### PR DESCRIPTION
**Pull request by minrk**
link targets can be escaped urls, but APIs expect unescaped "API path" strings

Example valid and correct markdown links that didn't resolve, but do now:

```markdown
- [link](has%20space) (should resolve to "has space")
- [link](has%25percent) (should resolve to "has%percent")
```

Fixes #5153

I'd love to add a test, but I couldn't figure out how.

### CODE REVIEW

**Comment by jasongrout** [comment]
But first all, thanks @minrk! We really appreciate you diving in to fix this!

**Comment by jasongrout** [comment]
Certainly where @minrk put the logic is closest to where it's actually needed, and doesn't change the API any, so I think it's great to merge this PR and move the logic up the call stack if needed in a later PR too.

**Comment by minrk** [comment]
Thanks for the input! Following the links, I think the right place is in urlResolver, clarifying that the inputs are URLs and the outputs are URLs. This should fix escaping. There are a few places where URLs are passed directly to contents without unescaping and where contents api paths are added to URLs without escaping.

It should work now:

- resolveUrl takes and returns urls
- getDownloadUrl takes and returns urls
- decode before calling contents api / handleLink
- encode after getting path from contents before adding to url

And I added tests that are passing for me locally, which I'm pretty sure would fail on master.

**Comment by blink1073** [comment]
Awesome, do you mind making a new issue to track adding those tests?

**Comment by minrk** [comment]
@blink1073 opened #5389 for the testing

**Pull request merged**
