### PR TITLE
key-bindings to codemirror search in single cell

### PR DESCRIPTION
**Pull request by jess-x**
## References
complementary to https://github.com/jupyterlab/jupyterlab/pull/10067 to address https://github.com/jupyterlab/jupyterlab/issues/2017

## User-facing changes

Use "Accel G" to do search in a single code cell, with codeMirror search

### CODE REVIEW

**Review by goanpeca — APPROVED** [review]
Thanks for working on this @jess-x !

**Comment by mlucool** [comment]
How does replace work with this change?

**Comment by jess-x** [comment]
@mlucool I found this https://github.com/codemirror/CodeMirror/blob/bd1b7d2976d768ae4e3b8cf209ec59ad73c0305a/src/input/keymap.js#L40 in the codemirror codebase, and I tested "Cmd-Alt-F": "replace", "Shift-Cmd-Alt-F": "replaceAll" on JLab, should work

**Comment by goanpeca** [comment]
Any thoughts and comments are appreciated @jupyterlab/committers 😃

**Comment by ivanov** [comment]
How was `H` picked for this? I am concerned that `Cmd-H` is a pretty fundamental "Hiding an Application" shortcut on macs. So either the proposed change would take that native shortcut away, or users intending to use the single cell search mode will end up hiding their browser application by accident if they don't happen to be in edit mode. I don't have a mac to test the PR on at the moment, but I think neither outcome desirable. 

Another question I have is what would this shortcut be on non-mac platforms? `Ctrl-H` brings up history on Firefox and Chrome on non-mac platforms.

**Comment by mlucool** [comment]
> How was H picked for this?

MSFT products like word, outlook, notepad, and VSCode, all use it ([example](https://support.microsoft.com/en-us/office/find-and-replace-text-c6728c16-469e-43cd-afe4-7708c6c779b7)). Sublime [does as well](https://sublime-text-unofficial-documentation.readthedocs.io/en/latest/search_and_replace/search_and_replace.html#replacing-text). Replacing text in the current file in [Jetbrains too](https://www.jetbrains.com/help/rider/Finding_and_Replacing_Text_in_File.html#replace_in_current_file).

**Comment by vidartf** [comment]
On Windows + Firefox `Ctrl-H` shows and hides the "History" side-bar in the browser.

**Comment by krassowski** [comment]
A more general comment: should it open the CodeMirror search, or should it open the notebook-level search with "search in selected cells only" selected? I feel like it would be more consistent.

**Comment by aiqc** [comment]
<kbd>cmd</kbd>+<kbd>h</kbd> successfully triggers the in-cell search on Mac Big Sur (11.2.1) in the Binder provided. It did not hide the browser window. 

It should probably be considered reserved though. Regarding the "f" related suggestions, here are the existing f-based shortcuts `Settings > Advanced Settings Editor > Keyboard Shortcuts`
```json
        {
            "command": "documentsearch:start",
            "keys": [
                "Accel F"
            ],
            "selector": ".jp-mod-searchable"
        },

        {
            "command": "filebrowser:toggle-main",
            "keys": [
                "Accel Shift F"
            ],
            "selector": "body"
        },
```
Layne

**Comment by isabela-pf** [comment]
Thanks for this work @jess-x! It's always great to see you here.

I was thinking `Accel Shift h` might be a good option, but it is already used for History in Firefox and Chrome and takes users to their homepage in Safari. If we are considering high-level browser needs like this as areas we don't want to overlap with, then it won't work either. @aiqc also shows that `f` based shortcuts are taken up too.

Since this is a similar experience as the notebook-wide Find, would it be a bad idea to use that same shortcut but have it triggered only when you are in edit mode in a cell? That's essentially the same behavior happening now (the current shortcut does override the system shortcut for me in Firefox and Chrome), but it may make more sense since it is always for finding, just different types of finding depending on where the focus is.

**Comment by krassowski** [comment]
> Since this is a similar experience as the notebook-wide Find, would it be a bad idea to use that same shortcut but have it triggered only when you are in edit mode in a cell? That's essentially the same behavior happening now (the current shortcut does override the system shortcut for me in Firefox and Chrome), but it may make more sense since it is always for finding, just different types of finding depending on where the focus is.

I would prefer the default find shortcut to open notebook-wide search, as it currently does. It seems to me that the use case of finding something which is "far away" in the notebook is much more common than finding something which is in the same cell. However, it might be useful to expand the "options" bar so that "find in selected cells only" is shown if search begins from edit mode.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Pull request merged**
