### PR TITLE
[WIP] Refactor statusbar

### PR DESCRIPTION
**Pull request by ian-r-rose**
Finishes #5352. This is a big restructuring of the status bar extension to be more idiomatic and in line with the rest of the core codebase.

1. Breaks the `statusbar` extension into two packages, `statusbar` and `statusbar-extension`.
2. Removes the `IDefaultsManager`. This was mostly redundant with the actual `IStatusBar` interface, and I found it pretty confusing. Extension authors should add status items using the `IStatusBar`. One downside of this is that the `IDefaultsManager` handled some logic about enabling and disabling status items via the settings registry. We may want to revisit that, but at the moment all of the status items are individual plugins, so they can be disabled at the application level.
3. Moves several of the status bar items to other packages, where appropriate. For instance, the notebook trust status item is moved to the `notebook-extension`. Several of the status items that are more cross-cutting in their application remain in the `statusbar-extension`.
4. Removes and simplifies various things.
5. Adds a lot of docstrings.

### CODE REVIEW

**Comment by blink1073** [comment]
Still WIP?

**Comment by ian-r-rose** [comment]
Yeah, I think so. It's an improvement right now, but I still want to hack at it a bit.

**Comment by ian-r-rose** [comment]
Though I suppose we could merge and iterate, since this would be a painful rebase...

**Comment by blink1073** [comment]
:+1: for iteration

**Comment by ian-r-rose** [comment]
Okay, merge away then!

**Comment by blink1073** [comment]
Done, thanks!

**Pull request merged**
