### PR TITLE
Upgrade yarn to 1.7.0

### PR DESCRIPTION
**Pull request by gnestor**
Closes https://github.com/jupyterlab/jupyterlab/issues/4585 and adds support for Node 10

### CODE REVIEW

**Comment by jasongrout** [comment]
Do we need the `--ignore-engines` switch with this upgrade? I thought the switch was a workaround before the upgrade.

**Comment by jasongrout** [comment]
> Do we need the --ignore-engines switch with this upgrade? I thought the switch was a workaround before the upgrade.

Similarly, why do we need the `--no-deprecation` switch?

**Comment by gnestor** [comment]
upath package was breaking `jlpm install` and I was seeing a node.js deprecation message related to `Buffer()`.

**Comment by jasongrout** [comment]
The yarn upgrade fixes the update issue, right?

**Comment by gnestor** [comment]
It just retried without both of those flags and `jlpm` and `jlpm build` both work, we just get the following deprecation message:

```
(node:76989) ExperimentalWarning: The fs.promises API is experimental
```

We get this with the `--no-deprecation` flag, too.

**Comment by andreipopovici** [comment]
:+1: Eagerly awaiting this merge and PyPi version bump, since installing extensions is broken until then.

**Comment by gnestor** [comment]
The workaround in the meantime is to downgrade Node to <= 9

**Comment by ian-r-rose** [comment]
Thanks @gnestor and @jasongrout !

**Comment by jasongrout** [comment]
@meeseeksdev backport to 0.32.x

**Pull request merged**
