### PR TITLE
Increase notebook-cell margin in side-by-side mode

### PR DESCRIPTION
**Pull request by jess-x**
## References
Fixes https://github.com/jupyterlab/jupyterlab/issues/11376

## Code changes

When in side-by-side mode, increase top/bottom margins to `3em` & left/right margins to `5%`

## User-facing changes

Before:

https://user-images.githubusercontent.com/22648112/143334708-b1787149-063e-4e10-a603-331b88a71512.mov

After: 

https://user-images.githubusercontent.com/22648112/143334661-2a8c01b1-ce5d-4b5a-b336-61ab16df382b.mov

### CODE REVIEW

**Comment by echarles** [comment]
This looks better with the margins. 2 comments:

1. I see 2 collapsers (the blue vertical lines). I am no more sure if this was already there before. Is this intented?
2. You have set the margin to `margin: 3em;`. Have you tried a '%' instead of a fixed value? Just asking to see if we could have a margin depending on the actual width of the notebook panel.

Screenshot 2021-11-25 at 07 50 08

**Comment by jess-x** [comment]
Screen Shot 2021-11-26 at 2 03 01 PM
This is how `2%` notebook-cell margins look on my screen. I cannot actually decide between this and `3em` by eyeballing the minimal difference they have on my screen, but using '%' does make more intuitive sense to me. Thanks @echarles

**Comment by jess-x** [comment]
> I see 2 collapsers (the blue vertical lines). I am no more sure if this was already there before. Is this intended?

Hmm, the left most ones are the input collapsers and the ones on the right side are output collapsers, I believe. Visually they can be confusing, I see. I could address this separately

**Comment by echarles** [comment]
> Hmm, the left most ones are the input collapsers and the ones on the right side are output collapsers, I believe. Visually they can be confusing, I see. I could address this separately

Yeah, I have been fooled by the input and output collapsers. Let's leave it as they are for now.

**Comment by echarles** [comment]
> This is how 2% notebook-cell margins look on my screen. I cannot actually decide between this and 3em by eyeballing the minimal difference they have on my screen, but using '%' does make more intuitive sense to me. Thanks @echarles

Prolly just set only `margin-left` and `margin-right` instead of `margin`(margin will set the top and bottom, which we don't need here)

I have trid with `margin-left: 5%` and `margin-right: 5%` and sounds to me like giving a better display, especially when you resize the browser to a small viewport.

**Comment by jess-x** [comment]
> Prolly just set only margin-left and margin-right instead of margin(margin will set the top and bottom, which we don't need here)
I have tried with margin-left: 5% and margin-right: 5% and sounds to me like giving a better display, especially when you resize the browser to a small viewport.

I think right now in side-by-side mode, the cells are too clustered together, that's why users are having a harder time focusing outputs with their input cells. I am aware by increasing `margin`, `margin-top` and `margin-bottom` are both increased under the hood. That is an intentional UI/UX decision from me, and I'd argue that's better than just increasing left/right margins. In terms of  `2%` vs `5%`, again I don't have a strong opinion/argument as I don't have access to various screens about different sizes. So it's I think A/B testing that with power users might let us make a more educated decision (if that's possible). With that said, I personally like the current implementation (`margin: 2%`), but feel free to push to this branch if needed :)

**Comment by echarles** [comment]
> I think right now in side-by-side mode, the cells are too clustered together, 

Thx for the reminder. In that case, increasing top and bottom makes sense.

> And I think A/B testing that with power users might let us make a more educated decision (if that's possible). 

True. You have spent more time than me trying the different options. 2% was ok for me also.

Let's wait a bit before merging for anyone wiling to give it a try and provide feedback.

**Comment by fcollonval** [comment]
I tried it on my ultra wide screen. I would not use a percentage for the vertical margin. Even 2% starts to be a lot. And if you close or not a side panel (see below), this changes the displayed cells although the height did not change. So I would use a constant vertical margin not a variable one.

| With filebrowser open | Without file browser |
| --- | --- |
| side-by-side_ | side_by_side_no_filebrowser |

**Comment by echarles** [comment]
> So I would use a constant vertical margin not a variable one.

Makes sense.

**Comment by jess-x** [comment]
@fcollonval @echarles thanks!! I changed top/bottom margins to `3em`, left/right margins to `5%`. On my screen, looks like this right now 
Screen Shot 2021-11-29 at 7 01 49 PM

**Comment by jtpio** [comment]
Thanks @jess-x.

> left/right margins to 5%

@fcollonval how does the 5% look on the wide display?

**Comment by fcollonval** [comment]
> @fcollonval how does the 5% look on the wide display?

| With sidebar | Without sidebar |
| --- | --- |
|wide_screen_with_sidebar | wide_screen_no_sidebar|

**Review by fcollonval — APPROVED** [review]
Thanks @jess-x

**Comment by echarles** [comment]
Thx @jess-x

**Comment by echarles** [comment]
@meeseeksdev please backport to 3.2.x

**Pull request merged**
