### PR TITLE
Make sure current widget is activated on command execution

### PR DESCRIPTION
**Pull request by blink1073**
Adds an `activate` arg for whether to take focus to each of the in console, editor widget and notebook commands, that defaults to `true`.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Looks good, but it seems a bit painful for command authors to have to remember to do this always. Can we move that logic somewhere more global?

**Comment by blink1073** [comment]
What if we had `app.shell.activateWidget(widget: Widget)` that does the right thing no matter where it is in the shell?

**Comment by blink1073** [comment]
The instance tracker doesn't have a handle on the shell, and I don't think it should.  We can't just activate the widget because it might be in a hidden tab.

**Comment by sccolbert** [comment]
this PR (on first glance) seems like it may be overzealous on activating things. Can we have a call about this to get me up to speed?

**Comment by sccolbert** [comment]
The proper signature for `execute` is `execute(args: JSONObject | null)`. Your command is *supposed* to behave well in the presence of `null` args. It seems that the code here assumes the args passed will be correct. It might be fragile. Not comfortable merging this until we talk about it.

**Pull request merged**
