### PR TITLE
WIP: Update XKCD tutorial

### PR DESCRIPTION
**Pull request by saulshanabrook**
* Add link to conda install docs to XKCD, in case people get stuck.

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks!

**Comment by blink1073** [comment]
Whoops, didn't see the wip.  Your last commit didn't go in.

**Comment by blink1073** [comment]
Or maybe it did, checking...

**Comment by blink1073** [comment]
Yeah, the default name and repo are in there.

**Comment by saulshanabrook** [comment]
@blink1073 Thanks!

**Pull request merged**
