### PR TITLE
Update the upgrade script to not replace dev deps to caret

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes https://github.com/jupyterlab/jupyterlab/commit/aee97d8a9577635622e7e2c75714c7d4f7929623#r42794778

cc @jasongrout 

## Code changes

Changes to the extension upgrade script.

The script would otherwise upgrade `devDependencies` such as `typescript`:

```diff
-"typescript": "~3.9.0",
+"typescript": "^3.9.0",
```

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Another option would be to treat `typescript` as a special case. But some other dev dependencies might also want to stick to `~` (for example `rimraf`)

**Comment by jasongrout** [comment]
See also https://github.com/jupyterlab/jupyterlab/commit/aee97d8a9577635622e7e2c75714c7d4f7929623#r42794778 for background

**Comment by jasongrout** [comment]
CC @afshin for review, since he put in #9051, which this is partially reverting.

**Review by afshin — APPROVED** [review]
Cheers!

👍

**Pull request merged**
