### PR TITLE
Improve upgrade extension script

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes https://github.com/jupyterlab/extension-template/issues/36

## Code changes

- Remove `prepare` script when upgrading an extension
- Add more workflows recommended to override
- Better cleaning of the python package name when using the npm package name

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by fcollonval** [comment]
@krassowski if you have seen other things that could be improved let me know.

**Comment by krassowski** [comment]
The only thing that got me was `stylelint` configuration being in `package.json`. The recommend to override list still includes `.stylelintrc`, `.prettierrc` and `.eslintrc.js` even though these are now in `package.json`. I needed to copy the keys over manually - I am not sure if this is because of an answer I given or if this is not handled by the script. Somewhat related but on the template side, I needed to add `selector-class-pattern` to allow JupyterLab style class names.

**Review by krassowski — APPROVED** [review]
As for the changes that are already in, LGTM. Not sure what you think about the lint config situation (an alternative to improving the upgrade script would be to revert the template to have them in individual files).

**Comment by fcollonval** [comment]
The script does not import the styling config from the template (only the `scripts` and `(dev)dependencies` are processed. But I agree with you, I found myself always switching the config for the linter. So I'll push a commit to improve the upgrade script to handle that.

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 4.0.x

**Pull request merged**
