### PR TITLE
Update dependencies, remove `markdown-loader-jest`

### LINKED ISSUE #12736: CVE vulnerabilities in some dependencies
## Description

- `testutils` uses [`markdown-loader-jest`](https://github.com/gpincheiraa/markdown-loader-jest), a 5 years old lib that locks `marked` to ^0.3.9, vulnerable to the severe https://github.com/advisories/GHSA-rrrm-qjm4-v8hf
- Old versions of `package-json` in `buildutils` and `lighthouse` in `testutils` locks `got` to ^9.6.0, vulnerable to https://github.com/advisories/GHSA-pfrx-2q88-qq97
- (Out of scope for now: JLab uses `verdaccio`, which one of its dependancies locks `jsdom` to 15.2.1, vulnerable to https://github.com/advisories/GHSA-f4c9-cqv8-9v98, [open pr in their end](https://github.com/verdaccio/monorepo/pull/592))

Context: I had these vulnerabilities reported by Dependabot on one of my JupyterLab extensions projects.

## Reproduce

N/A

## Expected behavior

Updated dependancies to patch these vulnerabilities.

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version:  989683cb7f83a9fbbe6caea1e1b0cfb9096f8d16

### PR DESCRIPTION
**Pull request by NextFire**
## References

Trying to fix #12736.

## Code changes

- `yarn upgrade`
- bump `lighthouse` to 9.3.0 and `package-json` to ^7.0.0 to upgrade `got`
- remove `markdown-loader-jest` dependency, ~~adding this 3-line loader directly in src~~ (unused)

## User-facing changes

None

## Backwards-incompatible changes

None (?)

### CODE REVIEW

**Comment by fcollonval** [comment]
Thanks @NextFire 

You can actually drop `markdown-loader-jest` it is not used (see when trying https://github.com/jupyterlab/jupyterlab/pull/12584).
For the CI failures, you should be able to solve it by applying https://github.com/jupyterlab/jupyterlab/pull/11638/commits/ca11cb2da4c5a8858579d51db328b471f8d96142

**Comment by krassowski** [comment]
It also looks like it accidentally undoes #12732. Could you reapply your changes on top of it?

**Comment by fcollonval** [comment]
The react types package that needs to be added is not in the metapackage but in [packages/extensionmanager/package.json](https://github.com/jupyterlab/jupyterlab/commit/ca11cb2da4c5a8858579d51db328b471f8d96142#diff-2b81349c4eb8d0a7260a96128581856c57ea197e95216f251df16ed6e16f84e1)

**Comment by fcollonval** [comment]
React types that conflicts come from:

```
=> Found "@types/react-highlighter#@types/react@18.0.14"
info This module exists because "_project_#@jupyterlab#json-extension#@types#react-highlighter" depends on it.
info Disk size without dependencies: "196KB"
info Disk size with unique dependencies: "1.38MB"
info Disk size with transitive dependencies: "1.38MB"
info Number of shared dependencies: 3
=> Found "@types/react-paginate#@types/react@18.0.14"
info This module exists because "_project_#@jupyterlab#extensionmanager#@types#react-paginate" depends on it.
info Disk size without dependencies: "196KB"
info Disk size with unique dependencies: "1.38MB"
info Disk size with transitive dependencies: "1.38MB"
info Number of shared dependencies: 3
```

**Comment by fcollonval** [comment]
Bumping the dependencies results in errors similar to the one seen in https://github.com/jupyterlab/jupyterlab/pull/12715

In particular the failing example case: `error >> Yjs was already imported. This breaks constructor checks and will lead to isssues!`

**Comment by fcollonval** [comment]
Closing in favor of #12776

**Pull request closed without merging**
