### PR TITLE
[WIP] Use yarn throughout, support offline mirroring

### PR DESCRIPTION
**Pull request by bollwyvl**
For https://github.com/jupyterlab/jupyterlab/issues/2065

This is heavily a work in progress, and doesn't include all the testing harness, etc.

Presently, I am still having some issues with the last-mile install of extensions-of-extensions (a la bqplot -> widgets).

### CODE REVIEW

**Comment by sccolbert** [comment]
I don't think extensions should be directly depending on other extensions. That defeats the point of plugin dependencies which can be implemented by unrelated third parties. 

Or did you mean normal dependencies of extensions?

**Comment by jasongrout** [comment]
> I don't think extensions should be directly depending on other extensions. That defeats the point of plugin dependencies which can be implemented by unrelated third parties.

It sounds like he's talking about something like the bqplot plugin, which requires the ipywidgets plugin since it extends the ipywidgets extension (by registering some custom widgets).

It does depend (as an npm dependency) on the ipywidgets plugin so it can require the token provided by ipywidgets.

**Comment by sccolbert** [comment]
If there is never going to be a separate implementation of ipywidgets, then it doesn't need to be a plugin or a token. You can just import it like a normal dependency. Depending on a package which implements a specific token violates the intent of the plugin system. The token should be defined separately from it's implementation.

**Comment by jasongrout** [comment]
Let me be more clear, to make sure we're not misunderstanding each other:

1. The @jupyterlab/nbwidgets npm package implements a JupyterLab plugin and provides to other plugins a way to register custom widgets. Of course, the way to request a service in phosphor is to provide a token, so the token is also exported.
2. The bqplot jlab extension npm package also implements a JupyterLab plugin, and needs a way to register itself, so it imports the @jupyterlab/nbwidgets npm package to get the token.

I think what you're saying is that there should be a *third* npm package that basically just defines and exports the token (along with the interface for what the token is providing), and both packages should import this token. I agree that is technically more correct - likely we will move towards this if/when it appears likely that there will be more than one package implementing widgets. A complicating factor here is that both @jupyterlab/nbwidgets and bqplot import the same underlying jupyter-js-widgets npm package, and those versions should be compatible with each other.

**Comment by sccolbert** [comment]
> I think what you're saying is that there should be a third npm package that basically just defines and exports the token (along with the interface for what the token is providing), and both packages should import this token.

Yes, that's what I mean. But if there will never be another implementation of that functionality, we can probably figure out a way to express it better.

> A complicating factor here is that ...

That's going to be true of several extensions which share a common dependency. And it's something we're trying to handle via `dedupe`. Ultimately, we have to assume packages will not violate semver (or all bets are off). If we *cant* make that assumption, then a pluggable/extensible app is simply not feasible.

**Comment by sccolbert** [comment]
I'd ideally like to avoid the situation where "installing X extensions means we must also install Y extension", because we should never "force" the user to install an extension. Some extensions may fail to load if the require tokens which have not been implemented, but that's okay, and ensures that we can always provide alternative implementations of tokens, without inadvertently bundling default implementations.

**Comment by sccolbert** [comment]
One way to do this may be to just get rid of tokens, and rely on strings to register plugins. We'll lose a bit of type-safety, but will get rid of this "where do I define my token" problem.

**Comment by jasongrout** [comment]
> I'd ideally like to avoid the situation where "installing X extensions means we must also install Y extension", because we should never "force" the user to install an extension. Some extensions may fail to load if the require tokens which have not been implemented, but that's okay, and ensures that we can always provide alternative implementations of tokens, without inadvertently bundling default implementations.

We had a conversation with @sccolbert, @blink1073, @ellisonbg, and @afshin. Some things came out of it: 

1. It's not clear where to define the token. For core plugins, the token is defined in the core package and imported in the extension. For an extension that is exposing a third-party application, though, it's most natural to define the token in the extension package. As Chris points out above, that breaks the idea that a token represents an interface that can be implemented by multiple packages.
2. The token conveys the idea of both an interface and the version of the interface. If we replace a token with a string-based identifier, we still need some way of indicating a version of the interface.
3. Chris is going to think more about this.

**Comment by bollwyvl** [comment]
Happy to put in whatever pattern we want. The current example is:
```
- @jupyterlab/mockextension
- @jupyterlab/mockextension-extension
  - dependencies: {"@jupyterlab/mockextension-extension": "^0.1.0"} 
```

Is something like, so being suggested:
```
- @jupyterlab/mockextension-api
- @jupyterlab/mockextension
  - "dependencies": {"@jupyterlab/mockextension-extension-api": "^0.1.0"} 
- @jupyterlab/mockextension-extension
  - "dependencies": {"@jupyterlab/mockextension-extension-api": "^0.1.0"} 
```

Fine for me! I just want to know what to put in the tests!

**Comment by bollwyvl** [comment]
The yarn upstream PR got merged:
https://github.com/yarnpkg/yarn/pull/3342

Hopefully we'll see this in a forthcoming release!

**Comment by blink1073** [comment]
Nice!

**Comment by blink1073** [comment]
Heads up, yarn 0.27.5 is now available on npm.

**Comment by bollwyvl** [comment]
> @blink1073 Heads up, yarn 0.27.5 is now available on npm.

Awesome, good time to get back on it! I'll start something back up... though happy for any more feedback, re: vendoring in the main repo/package vs moving to separate conda/pip package:
- the `yarn` script itself
  - bump only on `0.x.0` releases (of `jupyterlab`)
- the gold master `yarn.lock`
  - pretty cheap to keep around, though has lots of information theory
- npm package tarballs (~17mb, eek)

I see good arguments for having the _script_ be in the main repo, but still think the _mirror_ should be in another package. This would allow someone to _probably_ get a good experience, if connected to the network. The second package could be the one that carries the run-time `nodejs` dependency, which might be non-trivial to get with, say, `pip`, and could be our generally-recommended installation.

**Comment by blink1073** [comment]
I think having the `yarn` script and lock file as build artifacts of this repo (but not checked in), and having the mirror be separate is a good compromise.

**Comment by blink1073** [comment]
Closing in favor of #3168, thanks for this work!

**Pull request closed without merging**
