### PR TITLE
Use transform to quickly switch between tabs.

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Apply https://github.com/jupyterlab/lumino/pull/231 in JupyterLab

## Code changes

N/A

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by fcollonval — COMMENTED** [review]
please run benchmark

**Comment by fcollonval** [comment]
Benchmark result are surprising for switch-to (aka nb to text editor).

In the animation below, a gain on Chromium is quite obvious: 

hiddenmode_demo

**Comment by fcollonval** [comment]
I updated the [jupyterlab/benchmarks](https://github.com/jupyterlab/benchmarks) to launch manually a more extensive benchmark on more type of notebooks.

So in addition to switching back and forth to an text editor, I did it between two copies of the test notebook. The results presented below are showing a noticeable gain on all scenarii except one switch from notebook to text editor and on closing. 

So should we turn it on (current status) or off by default.

---

## Benchmark report

The execution time (in milliseconds) are grouped by test file, test type and browser.
For each case, the following values are computed: _min_ <- [_1st quartile_ - _median_ - _3rd quartile_] -> _max_.

The mean relative comparison is computed with 95% confidence.

<details><summary>Results table</summary>

| Test file | large_code_100_notebook | large_md_100_notebook |
| --- | --- | --- |
| **open** | | |
| `chromium` | | |
| actual | 2186 <- [2230 - 2249 - 2280] -> 2543 | 1442 <- [1492 - 1510 - 1529] -> 1794 |
| expected | 2160 <- [2212 - 2231 - 2250] -> 2552 | 1437 <- [1492 - 1519 - 1538] -> 1902 |
| Mean relative change | 1.1% ± 0.7% | -0.2% ± 1.4% |
| **switch-from-copy** | | |
| `chromium` | | |
| actual | 152 <- [224 - 246 - 268] -> 2927 | 62 <- [134 - 151 - 194] -> 430 |
| expected | 474 <- [546 - 564 - 591] -> 2156 | 333 <- [383 - 397 - 426] -> 635 |
| Mean relative change | -33.3% ± 6.4% | -59.3% ± 0.7% |
| **switch-to-copy** | | |
| `chromium` | | |
| actual | 148 <- [218 - 241 - 263] -> 452 | 65 <- [134 - 159 - 186] -> 277 |
| expected | 445 <- [536 - 554 - 583] -> 1032 | 324 <- [377 - 388 - 413] -> 603 |
| Mean relative change | -56.9% ± 0.5% | -59.4% ± 0.6% |
| **switch-from-txt** | | |
| `chromium` | | |
| actual | 132 <- [205 - 218 - 231] -> 290 | 49 <- [76 - 82 - 116] -> 319 |
| expected | 118 <- [170 - 181 - 194] -> 462 | 118 <- [157 - 167 - 182] -> 395 |
| Mean relative change | 17.7% ± 1.3% | -40.7% ± 1.5% |
| **switch-to-txt** | | |
| `chromium` | | |
| actual | 117 <- [185 - 203 - 219] -> 404 | 41 <- [65 - 74 - 117] -> 208 |
| expected | 413 <- [478 - 492 - 512] -> 974 | 277 <- [328 - 340 - 356] -> 499 |
| Mean relative change | -59.8% ± 0.5% | -73.7% ± 0.7% |
| **close** | | |
| `chromium` | | |
| actual | 618 <- [686 - 768 - 792] -> 841 | 513 <- [566 - 591 - 607] -> 747 |
| expected | 407 <- [434 - 446 - 455] -> 575 | 341 <- [364 - 378 - 396] -> 560 |
| Mean relative change | 66.9% ± 3.2% | 53.3% ± 3.4% |

Changes are computed with _expected_ as reference.

</details>

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
Looks like there is a small conflict to fix.

**Comment by fcollonval** [comment]
CI error is not related -> merging

**Comment by echarles** [comment]
@fcollonval Any reason to not backport on 3.3.x? It sounds like this could benefit current users looking for more performance.

**Comment by fcollonval** [comment]
I fear the ship has sailed for 3.3.x as this one requires bumping `@lumino/widgets` dependency.

**Comment by mlucool** [comment]
Semi-equivalent user space option discovered by @rtrg
```
%%javascript
function addCss(cssCode) {
  const styleElement = document.createElement("style");
  styleElement.type = "text/css";
  if (styleElement.styleSheet) {
    styleElement.styleSheet.cssText = cssCode;
  } else {
    styleElement.appendChild(document.createTextNode(cssCode));
  }
  document.getElementsByTagName("head")[0].appendChild(styleElement);
}
 
 
addCss(`
.jp-NotebookPanel.jp-Document {
    will-change: transform;
    transform: translateY(0px);
}
 
.jp-NotebookPanel.jp-Document.lm-Widget.lm-mod-hidden {
    transform: translateY(-110%) !important;
    display: block !important;
}
`)
```

**Comment by fcollonval** [comment]
Small comment on the above css trick. I use `scale(0)` instead of `translate` to ensure the _hidden_ element will never be able to catch mouse events.

**Comment by rtrg** [comment]
@fcollonval can that be changed to `scaleX(0)` ?

With `content-visibility` and `contain-intrinsic-height` suggestion [here](https://github.com/jupyterlab/jupyterlab/issues/9757#issuecomment-1065139516) which improves menu interaction performance for large notebooks, if we use `scale(0)` it will try to compute height (as `contain-intrinsic-height: auto 70px;` is used) during transformation.

```
%%javascript
function addCss(cssCode) {
    const style = document.createElement('style');
    style.innerHTML = cssCode;
    document.head.appendChild(style);
}

addCss(`
    .jp-NotebookPanel.jp-Document {
        will-change: transform;
        transform: none !important;
    }
    .jp-NotebookPanel.jp-Document.lm-Widget.lm-mod-hidden {
        transform: scaleX(0) !important;
        display: block !important;
    }
`);

// This uses experimental CSS that is not supported by all browsers.
// By setting content-visibility: auto, when the cell is off-screen,
// style checks are avoided. We set an intrinsic height so that
// scrolling is not too jittery.
addCss(`
    .jp-Cell {
        content-visibility: auto !important;
        contain-intrinsic-height: auto 70px;
    }
`);
```

**Comment by fcollonval** [comment]
@rtrg yes it should work. But reading more on css containment, it sounds worth to try `content-visibility: hidden` on hidden document panel instead of transform since you are already using style rules not available in all browsers.

Ref https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility

**Comment by mlucool** [comment]
My reading is `hidden` would break at least the browser's search.

**Comment by fcollonval** [comment]
> My reading is `hidden` would break at least the browser's search.

I'm not sure to get that comment. The suggestion is to use `content-visibility: hidden` instead of `display: none` on `.jp-NotebookPanel.jp-Document.lm-Widget.lm-mod-hidden`. So the search is anyway expected not to look for the content of hidden notebook panels. The advantage of `content-visibility: hidden` is that it preserves the rendering state in the opposite of `display: none`. So it should speed up the tab switching.

**Comment by mlucool** [comment]
I misunderstood and thought you mean on `.jp-Cell`. You are right - this is worth testing out.

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.4.x

**Pull request merged**
