### PR TITLE
Design work on collapser and cells for the beta

### PR DESCRIPTION
**Pull request by ellisonbg**
* Removes some stale styling of collapser
* Styles collapser in console
* Fixed console styles
* Minor design updates to new cell view

### CODE REVIEW

**Comment by ellisonbg** [comment]
Looks like there is still a rendering problem with the collapser on firefox latest. Working on that now...

**Comment by ellisonbg** [comment]
OK, talked with @blink1073 and @afshin:

* Moved away from changing the width of the collapser on hover, was too flickery. Now using a more traditional mostly flat button design (see screenshots below).
* Narrowed width of collapser to 8px, using minor box shadow and color change on hover.
* Using simpler console design.
* Also starting to use 2px border radius on buttons.

This is ready for review.

Dark theme, active, but not hovered:

screen shot 2017-12-18 at 10 42 34 am

Dark theme, active, input collapser hovered to show minor drop shadow and color change:

screen shot 2017-12-18 at 10 42 42 am

Light theme, active, but not hovered:

screen shot 2017-12-18 at 10 42 49 am

Light theme, active, input collapser hovered to show minor drop shadow and color change:

screen shot 2017-12-18 at 10 42 55 am

**Comment by ellisonbg** [comment]
And here is the console design:

screen shot 2017-12-18 at 10 48 49 am

Dark theme:

screen shot 2017-12-18 at 10 49 26 am

**Comment by blink1073** [comment]
Thanks!

**Pull request merged**
