### PR TITLE
Add tests for mocks and jupyter server

### LINKED ISSUE #8361: Add test suite for testutils
## Description
We need a test suite for testutils, to make sure that logic is sound.
For the mocks, we should at least hit each function

cf #8327.

### PR DESCRIPTION
**Pull request by blink1073**
## References
Fixes #8361 

## Code changes
- Adds a test suite to testutils covering mocks and `JupyterServer`.
- Cleans up the mocks a bit in the process.
- Adds the local package as a reference for `tsconfig.test.json` so we make sure the local package is built when running `build:test`

## User-facing changes
None

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by blink1073** [comment]
...and with that, test refactor is complete. 

image

**Comment by jtpio** [comment]
Thanks @blink1073 for this!

Do you know if there are any plans to release a new version `@jupyterlab/testutils` with the new `JupyterServer`? Or maybe it's better to wait for 3.0?

Some extensions that reuse the testutils package (for example the [debugger](https://github.com/jupyterlab/debugger/issues/445)) could then migrate from `JestApp` to `JupyterServer` as well.

**Comment by blink1073** [comment]
We could have a 2.2 release #8488, but I don't currently have the bandwidth.  Alternatively, we could release an alpha of 3.0 now if you want to use the library.

**Comment by jasongrout** [comment]
>  Alternatively, we could release an alpha of 3.0 now if you want to use the library.

That would be easiest, and probably a nice thing for the community to have a release of master.

**Comment by jtpio** [comment]
> Alternatively, we could release an alpha of 3.0 now if you want to use the library.

That would definitely work :+1:

(btw it's no hurry at all)

**Comment by blink1073** [comment]
Released as `@jupyterlab/testutils@2.2.0-alpha.0"

**Comment by jtpio** [comment]
Awesome, thanks a lot!

**Pull request merged**
