### PR TITLE
Add an optional header to the application shell

### PR DESCRIPTION
**Pull request by commandlinegirl**
This commit adds the ability to show and add widgets to a custom header above the top (menu) panel, [similarly to the bottom panel](https://github.com/jupyterlab/jupyterlab/pull/4752).  It will allow extension authors to add their own customizations, menus, etc. By default, i.e. when it contains no widgets, the header is hidden.

This is an example of how it could be used in an extension:
```
function addHeader(app: JupyterLab) {
  let widget: Widget = new Widget();
  widget.id = 'myheader';
  widget.title.label = 'My Header';
  widget.title.closable = false;

  var main_strip = document.createElement("div");
  main_strip.id = "header_main_strip";
  var navbar = document.createElement("div");
          var left = document.createElement("ul");
          left.id = "header_navbar_left";
                  var projects = document.createElement("li");
                  ...
          left.appendChild(projects);
                  var commit_button = document.createElement("li");
                  ...
          left.appendChild(commit_button);
  navbar.appendChild(left);
  main_strip.appendChild(navbar);
  widget.node.appendChild(main_strip);

  app.shell.add(widget, 'header');
}
```

The feature works well for us and makes the extension code a lot simpler, so we’d like to contribute it back for the community.

### CODE REVIEW

**Comment by jtpio** [comment]
@commandlinegirl this looks interesting. Do you mind posting a screenshot to see what it looks like when enabled?

**Comment by commandlinegirl** [comment]
Sure, I'm attaching a screenshot showing an enabled header. In this example I added some elements that pertain to the whole JupyterLab session, like timeout control (top right corner). 

header_example

**Comment by afshin** [comment]
Thanks for the PR! I requested a review from @tgeorgeux froma  design and UX point of view.

**Comment by commandlinegirl** [comment]
Great, thanks a lot!

**Comment by afshin** [comment]
FYI, we are having the JupyterLab dev team meeting today at 9AM Pacific time: https://calpoly.zoom.us/join (join with the meeting name: `jupyter`). Feel free to join! I'll raise this PR at that meeting.

**Comment by commandlinegirl** [comment]
Great, thanks for the heads-up! I'll be there.

**Comment by jasongrout** [comment]
+1 from me for the idea of having a header.

**Comment by commandlinegirl** [comment]
Merged master, two checks fail (previously three).

**Pull request merged**
