### PR TITLE
Consider indentation for the determination of complete statements

### PR DESCRIPTION
**Pull request by BoPeng**
## References

Remaining issue of #6645 , rebased after #6645 is merged.

When we try to find a complete Python statement, the current add-a-new-line algorithm will take the first complete statement inside `if`, `for`, `while`, `def` etc and stop. 
 
image

## Code changes

When finding a complete statement, it will stop before a line with equal or less indentation. That is to say, when executing from an `if` or `for` block, the entire block will be included. so that
```
if True: <- cursor here
    print(1)

    print(2)

print(3)
```
would yield

image

## Backwards-incompatible changes

non-Python kernels will be affected, which could submit more than one statements if the first statement has smaller indentation.

image

## Potential solution:

It is possible to limit the indentation-aware behavior only to Python kernels but there is no easy way to tell which kernel should be indentation-aware (for example, SoS is based on Python and would like to be treated this way). I personally do not mind the indentation problem with R because that was a bad coding style anyway.

### CODE REVIEW

**Comment by BoPeng** [comment]
One of the tests failed. Does not seem to be relevant though.

image

**Comment by jasongrout** [comment]
We discussed this in the dev meeting last week and decided it assumed too much about coding styles in other kernels. If it was limited to python, or if there was some way for a kernel to opt into the behavior, that would be much better.

Perhaps it's pointing to having better analysis tools on the backend. Perhaps the is_complete requests should be able to look ahead as well as look behind, and tell you where the most logical breaks in the code are (e.g., what if the is_complete mechanism behaved like the autocomplete mechanism, where it takes a block of code and a cursor position, and replies with the boundaries of a "complete" statement the cursor is in).

So for now we'll close this, but if you'd like to open a new issue to the protocol to add backwards-compatible fields to the is complete message spec to help resolve this issue, that would be great.

**Comment by jasongrout** [comment]
Thanks again for pushing the boundaries on the tools to support a more fluid workflow! Let's solve this issue at the protocol level, though, which makes for a much cleaner solution.

**Comment by BoPeng** [comment]
@jasongrout Do you (the team) dislike the behavior in general, or do you think it suits Python but not other kernels like R?

**Pull request closed without merging**
