### PR TITLE
Updates for responsive toolbar

### PR DESCRIPTION
**Pull request by 3coins**
## References

This PR fixes the issue [#10595](https://github.com/jupyterlab/jupyterlab/issues/10595)

## Code changes

Toolbar class has a new default button and a popup. The resize handler is added which keeps track of widths of items and  moves them to the popup if the cumulative width increases toolbar width. Alternatively, if toolbar width is big enough to accommodate any widgets in the popup, they are moved back to the toolbar.

## User-facing changes

Toolbar has a new default button and a popup that stores items that don't fit in the toolbar when the toolbar is resized. 

responsive-toolbar

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks for working on this!

Out of curiosity, what does it look like on mobile devices? For now the toolbar should be scrollable, which has been working quite ok on small screens and lighter interfaces like [RetroLab](https://github.com/jupyterlab/retrolab)

**Comment by 3coins** [comment]
> Thanks for working on this!
> 
> Out of curiosity, what does it look like on mobile devices? For now the toolbar should be scrollable, which has been working quite ok on small screens and lighter interfaces like [RetroLab](https://github.com/jupyterlab/retrolab)

👍 I haven't reviewed it for mobile devices, but I am going to change the implementation to have a vertical menu with a scrollbar. I will add some screenshots for review.

**Comment by 3coins** [comment]
@isabela-pf Do you have any feedback on the design? The consensus in the community meeting was to have a bottom facing chevron with a scrollable popup. Are there existing icons/images available that can be reused?

**Comment by 3coins** [comment]
> Thanks for working on this!
> 
> Out of curiosity, what does it look like on mobile devices? For now the toolbar should be scrollable, which has been working quite ok on small screens and lighter interfaces like [RetroLab](https://github.com/jupyterlab/retrolab)

@jtpio Reviewed scrollbars in toolbar, and discovered that on desktop browsers they don't appear on their own (checked on a Mac) unless hovered on the toolbar; Chrome doesn't show any scrollbar, Firefox shows the scrollbar when hovered. A good scrollbar approach would be to have the scrollbar always show when overflow happens, otherwise notebook users might not know what to do in some browsers. Do not know if this is a system or browser setting and if it can be overridden by CSS. Another issue is that on desktop browsers, [scrollbar-width](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width#browser_compatibility) is not widely supported which ends up with thick scrollbar covering most of the widgets.

### Chrome

https://user-images.githubusercontent.com/289369/126549386-c571876d-95a7-44f4-a469-9be3c024d22c.mov

### Firefox

https://user-images.githubusercontent.com/289369/126549650-cf15fb31-9726-42f1-acd7-78a881444611.mov

**Comment by jtpio** [comment]
Thanks @3coins for investigating this :+1: 

> Chrome doesn't show any scrollbar, Firefox shows the scrollbar when hovered. A good scrollbar approach would be to have the scrollbar always show when overflow happens, otherwise notebook users might not know what to do in some browsers

For reference the scrollbar was added in https://github.com/jupyterlab/jupyterlab/pull/8417. And only on hover so it doesn't take too much space by default.

**Comment by 3coins** [comment]
Closed pul request in favor of new PR - https://github.com/jupyterlab/jupyterlab/pull/10720

**Pull request closed without merging**
