### PR TITLE
Move the file name searcher to the file browser toolbar

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/12347

Move the file searcher to the file browser toolbar.

This will help downstream applications like Notebook 7 reusing the file browser widget be able to customize it more: https://github.com/jupyter/notebook/issues/6341

## Code changes

The file searcher component is now a file browser toolbar item. This has a number of benefits such as being able to reorder it or even hide it from the toolbar.

This avoids making the `_filenameSearcher` a special case component as it is now defined and added in the plugin.

## User-facing changes

Users can now configure whether they want the filename searcher to be displayed, and its position in the toolbar.

**Before**

https://user-images.githubusercontent.com/591645/220415826-f1fee04e-289b-4174-a379-0f7ee7da9ee7.mp4

**After**

https://user-images.githubusercontent.com/591645/220419258-e9149a25-b8cc-4fac-8ece-78c0b664c273.mp4

## Backwards-incompatible changes

Remove the `useFuzzyFilter` setter from the `FileBrowser` class.

image

### CODE REVIEW

**Comment by jtpio** [comment]
bot please update snapshots

**Comment by jtpio** [comment]
cc @krassowski for review since you commented in https://github.com/jupyterlab/jupyterlab/issues/12347#issuecomment-1089394407.

This PR takes the approach of using the `flex-wrap` attribute on the toolbar (instead of a CSS grid), which allows putting the file name searcher on the same line when the file browser is expanded.

**Comment by krassowski** [comment]
Just noting that the width is no longer 100%:

Screenshot from 2023-02-23 20-24-55

**Comment by jtpio** [comment]
Just rebased to fix the conflicts.

**Comment by jtpio** [comment]
> Just noting that the width is no longer 100%:

Right, not sure if it should still be 100% since the search bar can be re-ordered:

image

**Comment by jtpio** [comment]
One more rebase to fix the conflicts following the merge of https://github.com/jupyterlab/jupyterlab/pull/13639.

**Comment by jtpio** [comment]
bot please update snapshots

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio

**Comment by jtpio** [comment]
Thanks @fcollonval for the review.

Merging so it can be part of the next 4.0 alpha release.

Happy to iterate more on styling tweaks in follow-up PRs if needed.

**Pull request merged**
