### PR TITLE
Remove completer class for empty line.

### LINKED ISSUE #1900: Tab at beginning of line opens autocomplete
When I press a tab at the beginning of a line in a cell, it opens the autocomplete dropdown. In Jupyter notebook, it used to indent with 4 spaces.

In Jupyter Notebook if there is no text to the left side (only whitespace) it indents the line rather than opening the autocomplete dropdown.

I'm using current master 7ec5eced4328aa8a284c7357485c09994936767d

### PR DESCRIPTION
**Pull request by ian-r-rose**
Re-fixes #1900.

### CODE REVIEW

**Comment by ssanderson** [comment]
@ian-r-rose it looks like this only fixes the empy line case?  In the classic notebook (and most other text editors), you also get indentation rather than completion if there's only leading whitespace before the cursor on the current line.

**Comment by ian-r-rose** [comment]
I believe the whitespace case is fixed further down in the file.

**Comment by blink1073** [comment]
Appveyor builds seem to be failing starting a few hours ago, seems like gremlins, will take another look tomorrow.

**Comment by ssanderson** [comment]
> I believe the whitespace case is fixed further down in the file.

I assume you mean https://github.com/jupyterlab/jupyterlab/pull/3001/files#diff-472ee5441f1ad3f53f4e4a22d97bf9dbR335 ?  I think that still doesn't handle the case of leading whitespace, followed by cursor, followed by text, which happens commonly when re-indenting parameters to a function, which is actually the case I noticed today.

**Comment by ian-r-rose** [comment]
Ah, your are right @ssanderson! This will require a bit more care...

**Comment by ian-r-rose** [comment]
Okay, this should handle the case of leading whitespace as well.

**Comment by blink1073** [comment]
@ian-r-rose, mind rebasing this to pick up the CI fix from #3020?

**Comment by ian-r-rose** [comment]
Sure thing.

**Comment by blink1073** [comment]
Success, thanks!

**Pull request merged**
