### PR TITLE
Store Y updates

### LINKED ISSUE #12856: KeyError: 'collaborative_ystore_class' when running in collaborative mode
## Description

I'm following the guidelines [here](https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#setting-up-a-local-development-environment) on getting a development environment setup and attempting to run the master branch (66f83a7fffefbad0b30be0484408f93544d63363).

Eveything works fine with
```bash
jupyter lab --dev-mode --watch
```

However, once I switch on collaborative mode via:
```bash
jupyter lab --dev-mode --watch --LabApp.collaborative=True
```
I get this error repeatedly when opening any notebook:

```
[E 2022-07-25 19:58:09.825 ServerApp] Uncaught exception GET /api/yjs/json:notebook:Untitled.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/yjs/json:notebook:Untitled.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/jimgoo/miniconda3/envs/jupyterlab/lib/python3.8/site-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/Users/jimgoo/miniconda3/envs/jupyterlab/lib/python3.8/site-packages/jupyter_server_ydoc/ydoc.py", line 111, in open
        self.ystore_class = self.settings["collaborative_ystore_class"]
    KeyError: 'collaborative_ystore_class'
```

I tried passing `--LabApp.collaborative_ystore_class=JupyterSQLiteYStore` after reviewing [this](https://github.com/jupyterlab/jupyterlab/blob/ef2aa1d84dd9d26eb4881a4ebf9995a778f44aed/jupyterlab/labapp.py#L558) but didn't have any luck.

## Reproduce

Run the above command with collaborative mode, then open any notebook.

## Expected behavior

Should be able to open a notebook in collaborative mode.

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/Users/jimgoo/.cargo/bin
	/Users/jimgoo/miniconda3/condabin
	/Users/jimgoo/miniconda3/envs/jupyterlab/bin
	/Users/jimgoo/git/configs/scripts
	/opt/homebrew/bin
	/opt/homebrew/sbin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/usr/local/go/bin

sys.path:
	/Users/jimgoo/miniconda3/envs/jupyterlab/bin
	/Users/jimgoo/miniconda3/envs/jupyterlab/lib/python38.zip
	/Users/jimgoo/miniconda3/envs/jupyterlab/lib/python3.8
	/Users/jimgoo/miniconda3/envs/jupyterlab/lib/python3.8/lib-dynload
	/Users/jimgoo/miniconda3/envs/jupyterlab/lib/python3.8/site-packages
	/Users/jimgoo/git/jupyterlab

sys.executable:
	/Users/jimgoo/miniconda3/envs/jupyterlab/bin/python

sys.version:
	3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:05:16) 
	[Clang 12.0.1 ]

platform.platform():
	macOS-12.4-arm64-arm-64bit

which -a jupyter:
	/Users/jimgoo/miniconda3/envs/jupyterlab/bin/jupyter

pip list:
	Package                  Version     Editable project location
	------------------------ ----------- ----------------------------
	aiofiles                 0.8.0
	aiosqlite                0.17.0
	anyio                    3.6.1
	appdirs                  1.4.4
	appnope                  0.1.3
	argon2-cffi              21.3.0
	argon2-cffi-bindings     21.2.0
	asttokens                2.0.5
	attrs                    21.4.0
	Babel                    2.10.3
	backcall                 0.2.0
	beautifulsoup4           4.11.1
	bleach                   5.0.1
	build                    0.8.0
	cattrs                   22.1.0
	certifi                  2022.6.15
	cffi                     1.15.1
	cfgv                     3.3.1
	charset-normalizer       2.1.0
	check-manifest           0.48
	codecov                  2.1.12
	coverage                 6.4.2
	debugpy                  1.6.2
	decorator                5.1.1
	defusedxml               0.7.1
	dictpath                 0.1.3
	distlib                  0.3.5
	docutils                 0.19
	entrypoints              0.4
	exceptiongroup           1.0.0rc8
	executing                0.9.0
	fastjsonschema           2.16.1
	filelock                 3.7.1
	html5lib                 1.1
	identify                 2.5.2
	idna                     3.3
	importlib-metadata       4.12.0
	importlib-resources      5.9.0
	iniconfig                1.1.1
	ipykernel                6.15.1
	ipython                  8.4.0
	isodate                  0.6.1
	jedi                     0.18.1
	Jinja2                   3.1.2
	json5                    0.9.8
	jsonschema               4.7.2
	jupyter-client           7.3.4
	jupyter_core             4.11.1
	jupyter-server           1.18.1
	jupyter_server_ydoc      0.1.6
	jupyter-ydoc             0.1.13
	jupyterlab               4.0.0a26    /Users/jimgoo/git/jupyterlab
	jupyterlab-pygments      0.2.2
	jupyterlab-server        2.15.0
	lazy-object-proxy        1.7.1
	MarkupSafe               2.1.1
	matplotlib-inline        0.1.3
	mistune                  0.8.4
	more-itertools           8.13.0
	nb-conda-kernels         2.3.1
	nbclient                 0.6.6
	nbconvert                6.5.0
	nbformat                 5.4.0
	nest-asyncio             1.5.5
	nodeenv                  1.7.0
	notebook-shim            0.1.0
	openapi-core             0.14.2
	openapi-schema-validator 0.2.3
	openapi-spec-validator   0.4.0
	packaging                21.3
	pandocfilters            1.5.0
	parse                    1.19.0
	parso                    0.8.3
	pep517                   0.12.0
	pexpect                  4.8.0
	pickleshare              0.7.5
	pip                      22.2
	platformdirs             2.5.2
	pluggy                   1.0.0
	pre-commit               2.20.0
	prometheus-client        0.14.1
	prompt-toolkit           3.0.30
	psutil                   5.9.1
	ptyprocess               0.7.0
	pure-eval                0.2.2
	py                       1.11.0
	pycparser                2.21
	Pygments                 2.12.0
	pyparsing                3.0.9
	pyrsistent               0.18.1
	pytest                   7.1.2
	pytest-check-links       0.7.1
	pytest-console-scripts   1.3.1
	pytest-cov               3.0.0
	pytest-mock              3.8.2
	pytest-timeout           2.1.0
	pytest-tornasync         0.6.0.post2
	python-dateutil          2.8.2
	pytz                     2022.1
	PyYAML                   6.0
	pyzmq                    23.2.0
	requests                 2.28.1
	requests-cache           0.9.5
	ruamel.yaml              0.17.21
	ruamel.yaml.clib         0.2.6
	Send2Trash               1.8.0
	setuptools               63.2.0
	six                      1.16.0
	sniffio                  1.2.0
	soupsieve                2.3.2.post1
	stack-data               0.3.0
	strict-rfc3339           0.7
	terminado                0.15.0
	tinycss2                 1.1.1
	toml                     0.10.2
	tomli                    2.0.1
	tornado                  6.2
	traitlets                5.3.0
	typing_extensions        4.3.0
	url-normalize            1.4.3
	urllib3                  1.26.11
	virtualenv               20.16.0
	wcwidth                  0.2.5
	webencodings             0.5.1
	websocket-client         1.3.3
	Werkzeug                 2.2.0
	wheel                    0.37.1
	y-py                     0.5.3
	ypy-websocket            0.2.0
	zipp                     3.8.1

conda list:
	# packages in environment at /Users/jimgoo/miniconda3/envs/jupyterlab:
	#
	# Name                    Version                   Build  Channel
	aiofiles                  0.8.0                    pypi_0    pypi
	aiosqlite                 0.17.0                   pypi_0    pypi
	anyio                     3.6.1                    pypi_0    pypi
	appdirs                   1.4.4                    pypi_0    pypi
	appnope                   0.1.3                    pypi_0    pypi
	argon2-cffi               21.3.0                   pypi_0    pypi
	argon2-cffi-bindings      21.2.0                   pypi_0    pypi
	asttokens                 2.0.5                    pypi_0    pypi
	attrs                     21.4.0                   pypi_0    pypi
	babel                     2.10.3                   pypi_0    pypi
	backcall                  0.2.0                    pypi_0    pypi
	beautifulsoup4            4.11.1                   pypi_0    pypi
	bleach                    5.0.1                    pypi_0    pypi
	build                     0.8.0                    pypi_0    pypi
	bzip2                     1.0.8                h3422bc3_4    conda-forge
	ca-certificates           2022.6.15            h4653dfc_0    conda-forge
	cattrs                    22.1.0                   pypi_0    pypi
	certifi                   2022.6.15                pypi_0    pypi
	cffi                      1.15.1                   pypi_0    pypi
	cfgv                      3.3.1                    pypi_0    pypi
	charset-normalizer        2.1.0                    pypi_0    pypi
	check-manifest            0.48                     pypi_0    pypi
	codecov                   2.1.12                   pypi_0    pypi
	coverage                  6.4.2                    pypi_0    pypi
	debugpy                   1.6.2                    pypi_0    pypi
	decorator                 5.1.1                    pypi_0    pypi
	defusedxml                0.7.1                    pypi_0    pypi
	dictpath                  0.1.3                    pypi_0    pypi
	distlib                   0.3.5                    pypi_0    pypi
	docutils                  0.19                     pypi_0    pypi
	entrypoints               0.4                pyhd8ed1ab_0    conda-forge
	exceptiongroup            1.0.0rc8                 pypi_0    pypi
	executing                 0.9.0                    pypi_0    pypi
	fastjsonschema            2.16.1                   pypi_0    pypi
	filelock                  3.7.1                    pypi_0    pypi
	html5lib                  1.1                      pypi_0    pypi
	icu                       70.1                 h6b3803e_0    conda-forge
	identify                  2.5.2                    pypi_0    pypi
	idna                      3.3                      pypi_0    pypi
	importlib-metadata        4.12.0                   pypi_0    pypi
	importlib-resources       5.9.0                    pypi_0    pypi
	iniconfig                 1.1.1                    pypi_0    pypi
	ipykernel                 6.15.1                   pypi_0    pypi
	ipython                   8.4.0                    pypi_0    pypi
	isodate                   0.6.1                    pypi_0    pypi
	jedi                      0.18.1                   pypi_0    pypi
	jinja2                    3.1.2                    pypi_0    pypi
	json5                     0.9.8                    pypi_0    pypi
	jsonschema                4.7.2                    pypi_0    pypi
	jupyter-server            1.18.1                   pypi_0    pypi
	jupyter-server-ydoc       0.1.6                    pypi_0    pypi
	jupyter-ydoc              0.1.13                   pypi_0    pypi
	jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
	jupyter_core              4.11.1           py38h10201cd_0    conda-forge
	jupyterlab                4.0.0a26                  dev_0    <develop>
	jupyterlab-pygments       0.2.2                    pypi_0    pypi
	jupyterlab-server         2.15.0                   pypi_0    pypi
	lazy-object-proxy         1.7.1                    pypi_0    pypi
	libcxx                    14.0.6               h04bba0f_0    conda-forge
	libffi                    3.4.2                h3422bc3_5    conda-forge
	libsodium                 1.0.18               h27ca646_1    conda-forge
	libuv                     1.44.2               he4db4b2_0    conda-forge
	libzlib                   1.2.12               ha287fd2_2    conda-forge
	markupsafe                2.1.1                    pypi_0    pypi
	matplotlib-inline         0.1.3                    pypi_0    pypi
	mistune                   0.8.4                    pypi_0    pypi
	more-itertools            8.13.0                   pypi_0    pypi
	nb_conda_kernels          2.3.1            py38h10201cd_1    conda-forge
	nbclient                  0.6.6                    pypi_0    pypi
	nbconvert                 6.5.0                    pypi_0    pypi
	nbformat                  5.4.0                    pypi_0    pypi
	ncurses                   6.3                  h07bb92c_1    conda-forge
	nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
	nodeenv                   1.7.0                    pypi_0    pypi
	nodejs                    18.6.0               h181ad7c_0    conda-forge
	notebook-shim             0.1.0                    pypi_0    pypi
	openapi-core              0.14.2                   pypi_0    pypi
	openapi-schema-validator  0.2.3                    pypi_0    pypi
	openapi-spec-validator    0.4.0                    pypi_0    pypi
	openssl                   3.0.5                ha287fd2_0    conda-forge
	packaging                 21.3                     pypi_0    pypi
	pandocfilters             1.5.0                    pypi_0    pypi
	parse                     1.19.0                   pypi_0    pypi
	parso                     0.8.3                    pypi_0    pypi
	pep517                    0.12.0                   pypi_0    pypi
	pexpect                   4.8.0                    pypi_0    pypi
	pickleshare               0.7.5                    pypi_0    pypi
	pip                       22.2               pyhd8ed1ab_0    conda-forge
	platformdirs              2.5.2                    pypi_0    pypi
	pluggy                    1.0.0                    pypi_0    pypi
	pre-commit                2.20.0                   pypi_0    pypi
	prometheus-client         0.14.1                   pypi_0    pypi
	prompt-toolkit            3.0.30                   pypi_0    pypi
	psutil                    5.9.1                    pypi_0    pypi
	ptyprocess                0.7.0                    pypi_0    pypi
	pure-eval                 0.2.2                    pypi_0    pypi
	py                        1.11.0                   pypi_0    pypi
	pycparser                 2.21                     pypi_0    pypi
	pygments                  2.12.0                   pypi_0    pypi
	pyparsing                 3.0.9                    pypi_0    pypi
	pyrsistent                0.18.1                   pypi_0    pypi
	pytest                    7.1.2                    pypi_0    pypi
	pytest-check-links        0.7.1                    pypi_0    pypi
	pytest-console-scripts    1.3.1                    pypi_0    pypi
	pytest-cov                3.0.0                    pypi_0    pypi
	pytest-mock               3.8.2                    pypi_0    pypi
	pytest-timeout            2.1.0                    pypi_0    pypi
	pytest-tornasync          0.6.0.post2              pypi_0    pypi
	python                    3.8.13          hd3575e6_0_cpython    conda-forge
	python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
	python_abi                3.8                      2_cp38    conda-forge
	pytz                      2022.1                   pypi_0    pypi
	pyyaml                    6.0                      pypi_0    pypi
	pyzmq                     23.2.0           py38hc61cae3_0    conda-forge
	readline                  8.1.2                h46ed386_0    conda-forge
	requests                  2.28.1                   pypi_0    pypi
	requests-cache            0.9.5                    pypi_0    pypi
	ruamel-yaml               0.17.21                  pypi_0    pypi
	ruamel-yaml-clib          0.2.6                    pypi_0    pypi
	send2trash                1.8.0                    pypi_0    pypi
	setuptools                63.2.0           py38h10201cd_0    conda-forge
	six                       1.16.0             pyh6c4a22f_0    conda-forge
	sniffio                   1.2.0                    pypi_0    pypi
	soupsieve                 2.3.2.post1              pypi_0    pypi
	sqlite                    3.39.2               h40dfcc0_0    conda-forge
	stack-data                0.3.0                    pypi_0    pypi
	strict-rfc3339            0.7                      pypi_0    pypi
	terminado                 0.15.0                   pypi_0    pypi
	tinycss2                  1.1.1                    pypi_0    pypi
	tk                        8.6.12               he1e0b03_0    conda-forge
	toml                      0.10.2                   pypi_0    pypi
	tomli                     2.0.1                    pypi_0    pypi
	tornado                   6.2              py38he5c2ac2_0    conda-forge
	traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
	typing-extensions         4.3.0                    pypi_0    pypi
	url-normalize             1.4.3                    pypi_0    pypi
	urllib3                   1.26.11                  pypi_0    pypi
	virtualenv                20.16.0                  pypi_0    pypi
	wcwidth                   0.2.5                    pypi_0    pypi
	webencodings              0.5.1                    pypi_0    pypi
	websocket-client          1.3.3                    pypi_0    pypi
	werkzeug                  2.2.0                    pypi_0    pypi
	wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
	xz                        5.2.5                h642e427_1    conda-forge
	y-py                      0.5.3                    pypi_0    pypi
	ypy-websocket             0.2.0                    pypi_0    pypi
	zeromq                    4.3.4                hbdafb3b_1    conda-forge
	zipp                      3.8.1                    pypi_0    pypi
	zlib                      1.2.12               ha287fd2_2    conda-forge

conda env:
	name: jupyterlab
	channels:
	  - conda-forge
	  - pyviz
	  - defaults
	dependencies:
	  - bzip2=1.0.8=h3422bc3_4
	  - ca-certificates=2022.6.15=h4653dfc_0
	  - entrypoints=0.4=pyhd8ed1ab_0
	  - icu=70.1=h6b3803e_0
	  - jupyter_client=7.3.4=pyhd8ed1ab_0
	  - jupyter_core=4.11.1=py38h10201cd_0
	  - libcxx=14.0.6=h04bba0f_0
	  - libffi=3.4.2=h3422bc3_5
	  - libsodium=1.0.18=h27ca646_1
	  - libuv=1.44.2=he4db4b2_0
	  - libzlib=1.2.12=ha287fd2_2
	  - nb_conda_kernels=2.3.1=py38h10201cd_1
	  - ncurses=6.3=h07bb92c_1
	  - nest-asyncio=1.5.5=pyhd8ed1ab_0
	  - nodejs=18.6.0=h181ad7c_0
	  - openssl=3.0.5=ha287fd2_0
	  - pip=22.2=pyhd8ed1ab_0
	  - python=3.8.13=hd3575e6_0_cpython
	  - python-dateutil=2.8.2=pyhd8ed1ab_0
	  - python_abi=3.8=2_cp38
	  - pyzmq=23.2.0=py38hc61cae3_0
	  - readline=8.1.2=h46ed386_0
	  - setuptools=63.2.0=py38h10201cd_0
	  - six=1.16.0=pyh6c4a22f_0
	  - sqlite=3.39.2=h40dfcc0_0
	  - tk=8.6.12=he1e0b03_0
	  - tornado=6.2=py38he5c2ac2_0
	  - traitlets=5.3.0=pyhd8ed1ab_0
	  - wheel=0.37.1=pyhd8ed1ab_0
	  - xz=5.2.5=h642e427_1
	  - zeromq=4.3.4=hbdafb3b_1
	  - zlib=1.2.12=ha287fd2_2
	  - pip:
	    - aiofiles==0.8.0
	    - aiosqlite==0.17.0
	    - anyio==3.6.1
	    - appdirs==1.4.4
	    - appnope==0.1.3
	    - argon2-cffi==21.3.0
	    - argon2-cffi-bindings==21.2.0
	    - asttokens==2.0.5
	    - attrs==21.4.0
	    - babel==2.10.3
	    - backcall==0.2.0
	    - beautifulsoup4==4.11.1
	    - bleach==5.0.1
	    - build==0.8.0
	    - cattrs==22.1.0
	    - certifi==2022.6.15
	    - cffi==1.15.1
	    - cfgv==3.3.1
	    - charset-normalizer==2.1.0
	    - check-manifest==0.48
	    - codecov==2.1.12
	    - coverage==6.4.2
	    - debugpy==1.6.2
	    - decorator==5.1.1
	    - defusedxml==0.7.1
	    - dictpath==0.1.3
	    - distlib==0.3.5
	    - docutils==0.19
	    - exceptiongroup==1.0.0rc8
	    - executing==0.9.0
	    - fastjsonschema==2.16.1
	    - filelock==3.7.1
	    - html5lib==1.1
	    - identify==2.5.2
	    - idna==3.3
	    - importlib-metadata==4.12.0
	    - importlib-resources==5.9.0
	    - iniconfig==1.1.1
	    - ipykernel==6.15.1
	    - ipython==8.4.0
	    - isodate==0.6.1
	    - jedi==0.18.1
	    - jinja2==3.1.2
	    - json5==0.9.8
	    - jsonschema==4.7.2
	    - jupyter-server==1.18.1
	    - jupyter-server-ydoc==0.1.6
	    - jupyter-ydoc==0.1.13
	    - jupyterlab-pygments==0.2.2
	    - jupyterlab-server==2.15.0
	    - lazy-object-proxy==1.7.1
	    - markupsafe==2.1.1
	    - matplotlib-inline==0.1.3
	    - mistune==0.8.4
	    - more-itertools==8.13.0
	    - nbclient==0.6.6
	    - nbconvert==6.5.0
	    - nbformat==5.4.0
	    - nodeenv==1.7.0
	    - notebook-shim==0.1.0
	    - openapi-core==0.14.2
	    - openapi-schema-validator==0.2.3
	    - openapi-spec-validator==0.4.0
	    - packaging==21.3
	    - pandocfilters==1.5.0
	    - parse==1.19.0
	    - parso==0.8.3
	    - pep517==0.12.0
	    - pexpect==4.8.0
	    - pickleshare==0.7.5
	    - platformdirs==2.5.2
	    - pluggy==1.0.0
	    - pre-commit==2.20.0
	    - prometheus-client==0.14.1
	    - prompt-toolkit==3.0.30
	    - psutil==5.9.1
	    - ptyprocess==0.7.0
	    - pure-eval==0.2.2
	    - py==1.11.0
	    - pycparser==2.21
	    - pygments==2.12.0
	    - pyparsing==3.0.9
	    - pyrsistent==0.18.1
	    - pytest==7.1.2
	    - pytest-check-links==0.7.1
	    - pytest-console-scripts==1.3.1
	    - pytest-cov==3.0.0
	    - pytest-mock==3.8.2
	    - pytest-timeout==2.1.0
	    - pytest-tornasync==0.6.0.post2
	    - pytz==2022.1
	    - pyyaml==6.0
	    - requests==2.28.1
	    - requests-cache==0.9.5
	    - ruamel-yaml==0.17.21
	    - ruamel-yaml-clib==0.2.6
	    - send2trash==1.8.0
	    - sniffio==1.2.0
	    - soupsieve==2.3.2.post1
	    - stack-data==0.3.0
	    - strict-rfc3339==0.7
	    - terminado==0.15.0
	    - tinycss2==1.1.1
	    - toml==0.10.2
	    - tomli==2.0.1
	    - typing-extensions==4.3.0
	    - url-normalize==1.4.3
	    - urllib3==1.26.11
	    - virtualenv==20.16.0
	    - wcwidth==0.2.5
	    - webencodings==0.5.1
	    - websocket-client==1.3.3
	    - werkzeug==2.2.0
	    - y-py==0.5.3
	    - ypy-websocket==0.2.0
	    - zipp==3.8.1
	prefix: /Users/jimgoo/miniconda3/envs/jupyterlab
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 2022-07-25 21:16:16.075 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[W 2022-07-25 21:16:16.077 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2022-07-25 21:16:16.079 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2022-07-25 21:16:16.082 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[I 2022-07-25 21:16:16.083 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-07-25 21:16:16.222 ServerApp] The module 'nbdime' could not be found (No module named 'nbdime'). Are you sure the extension is installed?
[I 2022-07-25 21:16:16.222 ServerApp] notebook_shim | extension was successfully linked.
[I 2022-07-25 21:16:16.434 ServerApp] [nb_conda_kernels] enabled, 10 kernels found
[I 2022-07-25 21:16:16.450 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-07-25 21:16:16.450 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2022-07-25 21:16:16.451 LabApp] JupyterLab extension loaded from /Users/jimgoo/git/jupyterlab/jupyterlab
[I 2022-07-25 21:16:16.451 LabApp] JupyterLab application directory is /Users/jimgoo/miniconda3/envs/jupyterlab/share/jupyter/lab
[I 2022-07-25 21:16:16.453 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-07-25 21:16:16.453 ServerApp] Serving notebooks from local directory: /Users/jimgoo/git/jupyterlab
[I 2022-07-25 21:16:16.453 ServerApp] Jupyter Server 1.18.1 is running at:
[I 2022-07-25 21:16:16.453 ServerApp] http://localhost:8888/lab?token=7e14b34f09d4bf3ddc87e5f4d0c10840a717c1d0dca4f938
[I 2022-07-25 21:16:16.453 ServerApp]  or http://127.0.0.1:8888/lab?token=7e14b34f09d4bf3ddc87e5f4d0c10840a717c1d0dca4f938
[I 2022-07-25 21:16:16.453 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2022-07-25 21:16:16.456 ServerApp]

    To access the server, open this file in a browser:
        file:///Users/jimgoo/Library/Jupyter/runtime/jpserver-8466-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=7e14b34f09d4bf3ddc87e5f4d0c10840a717c1d0dca4f938
     or http://127.0.0.1:8888/lab?token=7e14b34f09d4bf3ddc87e5f4d0c10840a717c1d0dca4f938
[I 2022-07-25 21:16:20.164 LabApp] Build is up to date
[W 2022-07-25 21:16:34.210 ServerApp] 404 GET /api/kernels/92cb86e1-926c-463a-9c45-1ae181e3fe5c?1658801794204 (::1): Kernel does not exist: 92cb86e1-926c-463a-9c45-1ae181e3fe5c
[W 2022-07-25 21:16:34.210 ServerApp] Kernel does not exist: 92cb86e1-926c-463a-9c45-1ae181e3fe5c
[W 2022-07-25 21:16:34.211 ServerApp] 404 GET /api/kernels/92cb86e1-926c-463a-9c45-1ae181e3fe5c?1658801794204 (::1) 2.63ms referer=http://localhost:8888/lab/tree/Untitled.ipynb
[W 2022-07-25 21:16:35.220 ServerApp] 404 GET /api/kernels/92cb86e1-926c-463a-9c45-1ae181e3fe5c/channels?session_id=bf0152b8-aef6-4340-8020-73286f27bf4e (::1): Kernel does not exist: 92cb86e1-926c-463a-9c45-1ae181e3fe5c
[W 2022-07-25 21:16:35.252 ServerApp] 404 GET /api/kernels/92cb86e1-926c-463a-9c45-1ae181e3fe5c/channels?session_id=bf0152b8-aef6-4340-8020-73286f27bf4e (::1) 36.35ms referer=None
[W 2022-07-25 21:16:35.257 ServerApp] 404 GET /api/kernels/92cb86e1-926c-463a-9c45-1ae181e3fe5c?1658801795253 (::1): Kernel does not exist: 92cb86e1-926c-463a-9c45-1ae181e3fe5c
[W 2022-07-25 21:16:35.257 ServerApp] Kernel does not exist: 92cb86e1-926c-463a-9c45-1ae181e3fe5c
[W 2022-07-25 21:16:35.257 ServerApp] 404 GET /api/kernels/92cb86e1-926c-463a-9c45-1ae181e3fe5c?1658801795253 (::1) 0.95ms referer=http://localhost:8888/lab/tree/Untitled.ipynb
[E 2022-07-25 21:16:35.650 ServerApp] Uncaught exception GET /api/yjs/json:notebook:Untitled.ipynb (::1)
[E 2022-07-25 21:16:42.490 ServerApp] Uncaught exception GET /api/yjs/json:notebook:Untitled.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/yjs/json:notebook:Untitled.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/jimgoo/miniconda3/envs/jupyterlab/lib/python3.8/site-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/Users/jimgoo/miniconda3/envs/jupyterlab/lib/python3.8/site-packages/jupyter_server_ydoc/ydoc.py", line 111, in open
        self.ystore_class = self.settings["collaborative_ystore_class"]
    KeyError: 'collaborative_ystore_class'
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### PR DESCRIPTION
**Pull request by davidbrochart**
## References

Fixes #12856.

This PR has the changes of #12600, except the ones of the `YDocWebSocketHandler` which moved to https://github.com/jupyter-server/jupyter_server_ydoc.

## Code changes

- Updated the RTC documentation.
- Added a `collaborative_ystore_class` trait, with a `SQLiteYStore` default value.
- Pinned `jupyter_server_ydoc>=0.1.8,<0.2.0` to save Y updates into a YStore.

## User-facing changes

By default, a file is created in the current directory under `.jupyter_ystore.db`.

## Backwards-incompatible changes

None.

### CODE REVIEW

**Comment by davidbrochart** [comment]
RTC is broken in JupyterLab HEAD, this PR fixes it.

**Comment by jimgoo** [comment]
> RTC is broken in JupyterLab HEAD, this PR fixes it.

I can conform, this fixed it for me.

**Review by fcollonval — APPROVED** [review]
Thanks @davidbrochart

**Comment by jtpio** [comment]
> By default, a file is created in the current directory under `.jupyter_ystore.db`.

It's not clear whether there was an outcome to the discussion in https://github.com/jupyterlab/jupyterlab/pull/12600 about this new file. But since this fixes the build (and other things), it makes sense to get this in so it can be iterated on.

cc @ellisonbg @echarles for awareness, since they had some comments in https://github.com/jupyterlab/jupyterlab/pull/12600

**Comment by echarles** [comment]
> cc @ellisonbg @echarles for awareness, since they had some comments in https://github.com/jupyterlab/jupyterlab/pull/12600

Thx. Quick question: is that new `.jupyter_ystore.db` file generated in non-RTC mode ? (without the --collaborative flag). I would expect not.

**Comment by davidbrochart** [comment]
> is that new `.jupyter_ystore.db` file generated in non-RTC mode ? (without the --collaborative flag)

No, it's not.

**Comment by jtpio** [comment]
Merging as this fixes the CI.

Feel free to open a new issue here or on the `jupyter_server_ydoc` repo to track further improvements: https://github.com/jupyter-server/jupyter_server_ydoc

Thanks all!

**Pull request merged**
