### PR TITLE
[WIP] Workspaces gui

### PR DESCRIPTION
**Pull request by Madhu94**
This still needs work, but opening a WIP PR to get some early feedback.

Pending work before code review -

- [ ] Styling inputs / form components (maybe with blueprint) to be more consistent with the rest of the app.
- [ ] Think about the user experience of this extension more (like what happens if the user attempts to delete / edit a workspace that is being shared)
- [ ]  A little bit of code cleanup

## References
#6944

## Code changes
Added a new `workspaces-ui-extension` to provide an interface to manage workspaces

## User-facing changes
A new panel to manage workspaces appears in the sidebar.

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by saulshanabrook** [comment]
@Madhu94 Could you add some screenshots of this new UI to the issue description?

**Comment by Madhu94** [comment]
@saulshanabrook I might not have the bandwidth to get back on this for another week or two :-/ If someone else gets to this earlier - please close this if someone else wants to work on it or move forward with this feature.

**Comment by Madhu94** [comment]
@saulshanabrook @jasongrout  It would be nice to get closure here I think. I'd be happy to resume work on this based on @isabela-pf 's mockups in #6944 since I now have the bandwidth to do so.  I'd also be happy to close this out in case you had other plans for this feature

**Comment by isabela-pf** [comment]
#6944 was brought up as an option for [JupyterLab 4.0 planning](https://github.com/jupyterlab/jupyterlab/issues/9647) in this week's JupyterLab team meeting. @Madhu94 I think people are still interested in this work and there has not been any conflicting work or planning. Thanks for returning to this and feel free to let me know if I can help you with anything.

**Comment by Madhu94** [comment]
Awesome, I'll rebase and resume work here!

**Comment by jweill-aws** [comment]
There hasn't been any activity on this pull request in over a year. As part of an effort to clean up this repository's pull requests, I'm closing this request. If you would still like to merge this code in, please reopen the request and resolve any outstanding merge conflicts. All of the code and comments will remain in place. Thank you for being part of the JupyterLab community!

**Pull request closed without merging**
