### PR TITLE
Update ToC UI

### PR DESCRIPTION
**Pull request by marthacryan**
## Code changes

Mostly changes CSS - plus there are a couple of code changes that add class names. 

## User-facing changes
Here's how the ToC currently looks:
image
And here are my updates:
toc

This changes the arrows for collapsing to instead be the blue bar that's used for notebook collapsing, and adds that same bar when an entry is "selected". 

Instead of highlighting the entire entry in gray when hovering, it now just displays the blue bar in a slightly lighter color, and instead of using larger fonts for higher level headers, it uses indentation to show the level of header. (see both below)
image
image

### CODE REVIEW

**Comment by marthacryan** [comment]
@isabela-pf @tgeorgeux Any thoughts on these updates?

**Review by ajbozarth — COMMENTED** [review]
I see no issues from a code perspective, I'll hold off on approval until we get UI/UX feedback from designers though

**Comment by isabela-pf** [comment]
I think this looks nice! I’m curious about the motivation behind the changes since I’m betting it’s not only for looks. Is it because the arrows and clickable region were kind of small before?

My only concern is that this implies a relationship between cells and ToC headers that I don’t think is quite there, since collapsing a ToC navigator doesn’t seem to also collapse the cell the way that UI implies in the notebook. And I don’t know that I think it should, but it might be misleading? I’m not sure if anyone else could see this as a problem, and it certainly fits better than the current UI so I’m happy to go ahead and merge since this doesn’t break anything.

**Comment by marthacryan** [comment]
@isabela-pf Actually it sort of was mostly for looks - part of it was that I've seen a similar bar to the left of the "active" element (the element the user clicked) in other table of contents before. I thought since the notebook already had a bar for the "active" cell of notebooks / for collapsing cells, the behavior was similar enough to use the same one. In terms of the collapsing behavior being confusing, I agree, but I'm also not sure how to get around that since we made an explicit decision to not have the ToC collapse notebook cells. Any ideas are welcome!

**Comment by isabela-pf** [comment]
I don't have a solution right now either, I’m not sure if anyone else could see this as a problem, and it doesn't break anything that I'm aware of, so I think it's worth merging as is if it's ready to go.

I totally agree with the choice to not have ToC controls collapse cells! It does make an unusual interaction with this look though. If you want me to think of solutions, this might have to wait a little longer and I don't want to block this on the single premise of this *could* be confusing. Just let me know if you want me to spend more thought on this now, otherwise I'll put it on my list to return to in the next few weeks with a little more time.

**Comment by jasongrout** [comment]
I find it a little confusing to have no indication if a header can be expanded or not, i.e., if something is being hidden from view. We had such an indication before with the triangles, and in jlab with a collapsed cell, we have a triple dot thing that indicates something is being hidden.

**Comment by marthacryan** [comment]
Good point, I had that thought as well. I added an ellipses button to the right of a ToC entry that's been collapsed and made it so that the blue bar appears next to all collapsed entry, does that seem better? 
newtoc

**Comment by jasongrout** [comment]
> I added an ellipses button to the right of a ToC entry that's been collapsed and made it so that the blue bar appears next to all collapsed entries, does that seem better?

Definitely better, thanks. It does seem a little awkward that the collapsed dot icon is opposite of the collapse/expand bar - is there a way to get it closer so that the indicator and bar are consolidated?

But then I can't help thinking - that's exactly what the triangles did before, and the triangles are a very widely used and well-understood indicator/control for collapsing.

**Comment by marthacryan** [comment]
In terms of the precedent around the icon for collapsing, I think the fact that notebook cells are collapsed using the same blue bar (and ellipses) actually makes this collapsing UI more consistent for JupyterLab users. Also, for other document types that use the ToC (markdown, latex, python) the blue bar is only serving to show the "active" entry - do you think if we were to use the triangle to indicate collapsing that we should still include some kind of bar indicator to highlight an active entry? (I've seen this in the table of contents for other editors and I think it can be useful)

In terms of the placement of the ellipses, I tried moving the ellipses around and it seems a little awkward / out of place to me around the blue bar, although I like the first one I included below the best - what do you think?  
image
image
image

**Comment by marthacryan** [comment]
- Updated the indentation to align the blue bar to the start of the text on entries one level higher
- Updated the collapsed entries to not be marked as "active" (no blue bar next to the collapsed entries, only next to the "active" entry) see below:
image
image

**Comment by marthacryan** [comment]
@jasongrout @isabela-pf Does this look okay at this point?

**Comment by lresende** [comment]
@jasongrout this seems to be getting ready to merge, if this is the case, any chance this can make 3.0?

**Comment by jasongrout** [comment]
Sure, there's still time while we are working on other pieces like the extension manager

**Comment by lresende** [comment]
Tentatively setting 3.0 milestone as discussed above.

**Comment by isabela-pf** [comment]
@marthacryan I think this looks good! Continuing the visual language of the notebook to the ToC is a great idea and I'm glad to see it happening. I don't know where you ended up placing the … to indicate a collapsed section, but I think any of the options we saw at the team meeting last week will work.

**Comment by marthacryan** [comment]
@isabela-pf Great, thanks! I kept the original placement of the ellipses (to the right of the text), but I can move it over to the left if it seems more user-friendly.

**Review by ajbozarth — APPROVED** [review]
UI/UX discussion looks solid so updating to an approve

**Comment by afshin** [comment]
Thanks for all the review + feedback! If we need to iterate on this, let's do it in another PR.

Thank you @marthacryan!

**Pull request merged**
