### PR TITLE
Do not shrink completer's documentation panel

### LINKED ISSUE #15023: When completer documentation panel is enabled, the completer width jumps
## Description

When moving between completion items with/without the documentation panel, the completer width jumps. This is a small CSS flex layout bug, one line fix on the way.

## Reproduce

compelter-resizes-when-doc-panel

## Expected behavior

The left side stays fixed.

## Context

- JupyterLab version: 4.0.05

### PR DESCRIPTION
**Pull request by krassowski**
## References

Fixes #15023

## Code changes

Adds `flex-shrink: 0` on documentation panel.

## User-facing changes

| Before | After |
|---|---|
| compelter-resizes-when-doc-panel | after |

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
Question: is the current 400px width a good default, or should we shrink it? Here are some options (of course we can go for something in between):

| 400px (current) | 350px | 300 px |
|--|--|--|
| Screenshot from 2023-08-26 00-28-17 | Screenshot from 2023-08-26 00-30-52 | Screenshot from 2023-08-26 00-31-21 |

**Comment by krassowski** [comment]
bot please update galata snapshots

**Comment by jtpio** [comment]
> Question: is the current 400px width a good default, or should we shrink it? Here are some options (of course we can go for something in between):

If it was already `400px` before, maybe we can leave it like this for now and then discuss a new default separately?

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
