### PR TITLE
Only Autoinsert Single Completion Items on Tab

### PR DESCRIPTION
**Pull request by edzkite**
## References
Resolves https://github.com/jupyterlab/jupyterlab/issues/8255, without needing a settings change.

## Code changes
Rather than signaling and bailing when the item node is created, we only signal and bail after a tab press is detected, signifying the user explicitly wanting a completion. We also only apply this to the new completions API path by checking for the presence of `completionItems` in the model, and only removing the logic from its item node creation path.

## User-facing changes
Previously, JupyterLab would auto-insert single completions from completer extensions, even if the user did not explicitly trigger a completion via tab. With this change, the completer menu is active even on single suggestions, unless tab is explicitly pressed.

## Backwards-incompatible changes
There should be no backwards incompatible changes. Consumers of the old completer API should not be impacted by this change.

### CODE REVIEW

**Comment by edzkite** [comment]
@telamonian Hey! Just wanted to check in and see if there's any other information I could provide or help with here.

**Comment by echarles** [comment]
With this PR, the end-user behavior is kept. Excellent so far!

jllab-builtin-8375

This is not an exhaustive coverage, but relevant case we want to address with this PR changes.

In terms of source code logic, the mangement of the single item is moved around. I need to make my mind a bit more in the light of the recent changes of the completer API.

The change also provide a test case which is great.

**Comment by echarles** [comment]
Did.a few more tests and all good with this PR.

1. Installed `@krassowski/jupyterlab-lsp` and ran the same end-suer test coverage as the one shown in the screencast of the previous comment - No regression, works as expected (did not record any screencast but can do that if needed). No regression either with the buildin jupyterlab completer as stated in previous comment.
2. Ran completer test with `npx lerna run test --scope \"@jupyterlab/completer\" --concurrency 1 --stream` and all good.
3. CI has failed on JS-services - Ran `services` tests locally and got timeout failures - I then pulled latest master in this branch and also tested master and got same failure. Something may be wrong on my env.
4. The logic to move the one entry completion from `_createIItemNode` to the case where the use types `TAB` sounds good.

@edzkite could you please rebase this branch to latest master and push the changes to trigger CI and have it hopefully fully green. Your changes are not related to the services but would be great to have CI green to merge.

In the meantime I will check where my JS services test failures (timeout) are coming from (prolly on my env, but I see some recent changes on kernel timeout have been brought in master).

**Comment by edzkite** [comment]
@echarles Thanks for the review! I've rebased against master.

**Comment by echarles** [comment]
Thx @edzkite. CI is green now.

LGTM

**Comment by echarles** [comment]
Quick question: 2 tests 'should emit label if there is only one completion item and insert Text is not / is set` are replaced by one test `should insert single completion item on tab`

Does the replacing test cover the 2 initial tests?

**Comment by edzkite** [comment]
No, it only covers the first deleted case (insert Text not set). I can go ahead and add it if you think it'd be valuable?

**Comment by echarles** [comment]
If it is easy to add the missing test, then yes, would be great to add that too. Thx a lot.

**Comment by edzkite** [comment]
@echarles Added!

**Comment by echarles** [comment]
@edithkk Super! CI is still running for docs and usage, but js tests of OK.

This is good to be merged.

**Comment by edzkite** [comment]
@echarles Sweet! Thanks for the review and testing. 

If you could help merge this, that'd be awesome!

**Comment by echarles** [comment]
Thx @blink1073 for the merge.

**Pull request merged**
