### PR TITLE
Fix CodeMirror tooltip positioning and tooltip background

### PR DESCRIPTION
**Pull request by krassowski**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/14857 and background (see below).

This mostly concerns extensions, core lab does not make use of the built-in CodeMirror tooltips. Since extensions may want to let's fix it. Also, it is a trivial change.

## Code changes

- Add background color override for tooltips as currently we override font color (indirectly) but not background
- Configure tooltip positioning to fix it when used in JupyterLab which uses `contain: strict` for performance reasons

## User-facing changes

| Before | After |
|--|--|
|  Screenshot from 2023-07-19 19-54-26 | Screenshot from 2023-07-19 19-53-59 |

## Backwards-incompatible changes

None

### CODE REVIEW

**Review by fcollonval — COMMENTED** [review]
Thanks @krassowski 

in https://github.com/jupyterlab/jupyter-collaboration/blob/a2671b2e226ba8163fb878885305f27ad9c77e3a/packages/collaboration/src/cursors.ts#L432 to allow displaying the user name when collaborating, I also added the parent to be `document.body` so that the tooltip is displayed outside of its containing widget (for the collaboration example that is needed if the cursor is in the editor first line).

Should we bring that one in also by default?

**Comment by krassowski** [comment]
Yes, I think that attaching to body is fine. Though I wonder if we should explore defining [`tooltipSpace`](https://codemirror.net/docs/ref/#view.tooltips^config.tooltipSpace)⁠ function (too or instead).

**Comment by fcollonval** [comment]
> Yes, I think that attaching to body is fine. Though I wonder if we should explore defining [`tooltipSpace`](https://codemirror.net/docs/ref/#view.tooltips%5Econfig.tooltipSpace)⁠ function (too or instead).

Thanks for the pointer I oversight that feat'. I guess it would be nice. I'm gonna approved this as we could do a follow-up with that feature. I let you press forward or merge :wink:

**Review by fcollonval — APPROVED** [review]

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.0.x

**Pull request merged**
