### PR TITLE
Commit JS and Python packages in one commit on release

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/13442

## Code changes

Instead of creating 2 commits on release, 1 for bumping the JS packages, 1 for the Python package, commit everything in a single commit.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
cc @blink1073 just checking if there was a reason for creating two commits in the first place? Or would it be fine to go with just one, as this would fix https://github.com/jupyterlab/jupyterlab/issues/13442?

**Comment by blink1073** [comment]
I can't think of a good reason to prefer two commits, I think a single commit makes sense.

**Comment by jtpio** [comment]
cc @jupyterlab/release for awareness

**Review by blink1073 — APPROVED** [review]
LGTM!

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio 

---

is there a specific reason for holding back a backport to 4.0.x?

**Comment by jtpio** [comment]
> is there a specific reason for holding back a backport to 4.0.x?

Right it should be possible to backport it.

But maybe it could be worth trying it out on a `4.1.x` alpha first.

**Comment by krassowski** [comment]
Was it all fine with alpha releases @fcollonval?

@meeseeksdev please backport to 4.0.x

**Comment by fcollonval** [comment]
Yes it went well

For reference 0ffbf860155e484c093e104efbef8efe5f262708

**Pull request merged**
