### PR TITLE
Tree handler

### PR DESCRIPTION
**Pull request by afshin**
The behavior of this PR will be:

When a user goes to a path that begins with `/lab/tree` that path will be navigated to by the main file browser. This means that if the path is a directory, the file browser opens that directory. If the path is a file, then the file browser navigates to that subfolder and then the file opens and is placed into the active tab panel.

Any state restoration that needs to happen will happen in addition to the path that is in the URL under `/lab/tree/...`

The application will then **change the URL** back to `/lab` but this change will *not* be added to history.

share

Fixes https://github.com/jupyterlab/jupyterlab/issues/1075
Fixes https://github.com/jupyterlab/jupyterlab/issues/2532

Depends on https://github.com/jupyterlab/jupyterlab_launcher/pull/31

### CODE REVIEW

**Comment by ellisonbg** [comment]
Excited about this! Ping @yuvipanda @choldgraf @minrk @willingc as this will allow Binder URLs to point to individual files within JupyterLab.

Question: for some files types, it would be very nice to be able to specify which file handler to use in opening the file. Maybe a URL parameters for that?

**Comment by choldgraf** [comment]
very cool! LMK when it's released and we can bump the jlab version + create a binder-examples example

**Comment by blink1073** [comment]
Turns out this is all we need for `index.html`:

```diff
diff --git a/dev_mode/webpack.config.js b/dev_mode/webpack.config.js
index 80d5ce074..cec22178b 100644
--- a/dev_mode/webpack.config.js
+++ b/dev_mode/webpack.config.js
@@ -109,7 +109,7 @@ module.exports = {
   },
   output: {
     path: path.resolve(buildDir),
-    publicPath: 'lab/static/',
+    publicPath: '{{base_url}}lab/static/',
     filename: '[name].[chunkhash].js'
   },
   module: {
```

**Comment by blink1073** [comment]
cf #3422

**Comment by blink1073** [comment]
This change allows us to run `jupyter lab path/to/foo.csv`:

```diff
diff --git a/jupyterlab/extension.py b/jupyterlab/extension.py
index 338816d..e2608ec 100644
--- a/jupyterlab/extension.py
+++ b/jupyterlab/extension.py
@@ -30,7 +30,7 @@ def load_jupyter_server_extension(nbapp):
     """
     # Delay imports to speed up jlpmapp
     from jupyterlab_launcher import add_handlers, LabConfig
-    from notebook.utils import url_path_join as ujoin
+    from notebook.utils import url_path_join as ujoin, url_escape
     from tornado.ioloop import IOLoop
     from .build_handler import build_path, Builder, BuildHandler
     from .commands import (
@@ -82,6 +82,12 @@ def load_jupyter_server_extension(nbapp):
     page_config['token'] = nbapp.token
     page_config['devMode'] = dev_mode

+    if nbapp.file_to_run:
+        relpath = os.path.relpath(nbapp.file_to_run, nbapp.notebook_dir)
+        uri = url_escape(ujoin('/lab/tree', *relpath.split(os.sep)))
+        nbapp.default_url = uri
+        nbapp.file_to_run = ''
+
     if core_mode:
         app_dir = HERE
         logger.info(CORE_NOTE.strip())
```

**Comment by ellisonbg** [comment]
Is this in a working state to try out?

**Comment by ellisonbg** [comment]
I did a local test:

* Opening a file (`/lab/tree/notebook.ipynb`) worked fine.
* Opening a directory (`/lab/tree/dir`) failed as it tried to treat it as a file.
* Doesn't seem to be populating the history, which is the behavior we talked about.

**Comment by afshin** [comment]
@ellisonbg Thanks for pointing that out! I need to discover if the thing you're querying is a file or a folder and I wasn't doing that.

When I fix that, the only thing remaining is adding the context menu option to the main file browser.

**Comment by ellisonbg** [comment]
It will probably be common to have users type URLs - right now if there is a typo, and a Tornado handler doesn't capture it, the notebook server shows a generic 404 page. We should probably add a generic `/lab/* handler that is last and that just redirects to `/lab`.

**Comment by afshin** [comment]
@ellisonbg re: generic `/lab/*` handler. We talked about this a little bit and it's something we could consider, but we should do it with some thought about the `HTTP` response code that comes back. So even if we serve the main index and the application *works*, we might still want to report a `404` back to the client, *etc.*

Like all of these URL things, our choices might cast a long shadow and it's good to deliberate about the ramifications.

**Comment by blink1073** [comment]
:boom:

**Comment by sputnik62** [comment]
This is fantastic! Exactly the behavior we have been looking for to enable wider use of Jupyter Lab in http://labs.CognitiveClass.ai

**Pull request merged**
