### PR TITLE
Fix the "new view for cell" panel focus issues.

### LINKED ISSUE #3303: Focus for cell mirrors
Notice that cell mirrors don't get activated as the current document widget (and single-document mode applies then to the notebook, even though I clicked on the cell mirror tab). Notice that it *does* get activated when I click inside the cell - not sure how that is happening.

focus

There is some common housekeeping that would be good to abstract out so that it easy to create a top-level dockpanel Panel that handles things like these focus issues for you. I started on something like this in https://github.com/jasongrout/ipywidgets/blob/5542ccf875b238073e8326e044456b563cc51e22/packages/jupyterlab-manager/src/focuspanel.ts, but it still doesn't handle the trackers for the current widget.

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #3303 

- [x] Fix styling so the top-level widget doesn't have a blue border when focused.
- [x] Add tests for the MainAreaWidget

### CODE REVIEW

**Comment by blink1073** [comment]
I think this would be a good point to add a top level widget in `apputils` that handles focus-on-activate and dispose-on-close.

**Comment by blink1073** [comment]
`CellPanel` could extend that widget and use a `PanelLayout` internally instead of being a `Panel`.

**Comment by blink1073** [comment]
Suggested name: `MainAreaWidget`

**Comment by jasongrout** [comment]
Didn't see your comments until after I abstracted it out - but I like your name much better!

**Comment by jasongrout** [comment]
And good point about this not needing to be a panel, it can be a more generic widget.

**Comment by jasongrout** [comment]
The docs test failure looks like it is unrelated.

**Comment by ian-r-rose** [comment]
I can direct you to #3376

**Pull request merged**
