### PR TITLE
Alternative proposal for restart-and-run icon: mashup of restart and fast forward

### PR DESCRIPTION
**Pull request by telamonian**
An alternative proposal for the restart-and-run icon that's more unified with the existing restart icon which it will be placed next to on the toolbar. There was a feeling that the current proposal in #8091 clashes a bit too much with the restart icon: https://github.com/jupyterlab/jupyterlab/pull/8091#issuecomment-606262391

## References

Alternative to #8091

## Code changes

NA

## User-facing changes

Change the restart-and-run icon to:

image

### CODE REVIEW

**Comment by telamonian** [comment]
My one concern is that at display size (16px x 16px) my restart-and-run icon will look too much like the restart icon.

@tgeorgeux I'm probably just retreading ground you've already been over, but do you have any ideas about how I could jazz this up and make it more distinct at small sizes?

**Comment by telamonian** [comment]
I took a second pass at my restart-and-run icon, with an eye to making it look distinct from the restart icon at small sizes:

image

In context, at "real" size on the toolbar, restart and restart-and-run look nicely harmonious next to one another while still being visually distinct:

image

I do think that the sizes and shapes of the "fast-forward" triangles could probably use one last round of tweaks.

**Comment by tgeorgeux** [comment]
I can give it a cleanup pass after the governance meeting tomorrow. I'm
nerding out a bit on the fact that we use a 'refresh' icon to restart the
kernel. I suppose there's some wisdom in not changing what's not broken. I
can also turn the direction of icon over in #8091 , in #7935 I mentioned
I'm not attached to the direction too much, but I agree they should both be
the same direction, as they're the same command.

Let me know what you think.

**Comment by telamonian** [comment]
> I suppose there's some wisdom in not changing what's not broken.

More like "don't re-rebreak what's definitely long-term busted by trying to fix it".

I do think that the icon in this PR is more clearly says "restart plus" than the icon in #8091 (I'm obviously biased, though).

@tgeorgeux I would love if you could do a cleanup pass of my icon. If you then also mirror-flip #8091 we can do some kind of an A/B comparison and then collectively come to a decision which one (if either) to pull in.

**Comment by vidartf** [comment]
> I can give it a cleanup pass after the governance meeting tomorrow. 

Pinging in case you forgot about it ;)

**Comment by goanpeca** [comment]
Hi @telamonian. Is this PR still valid?

Thanks!

**Comment by jweill-aws** [comment]
There hasn't been any activity on this pull request in over a year. As part of an effort to clean up this repository's pull requests, I'm closing this request. If you would still like to merge this code in, please reopen the request and resolve any outstanding merge conflicts. All of the code and comments will remain in place. Thank you for being part of the JupyterLab community!

**Pull request closed without merging**
