### PR TITLE
DO NOT MERGE: Test rebasing 2.3.x on top of 2.2.x

### PR DESCRIPTION
**Pull request by goanpeca**
This is a test PR to check how rebasing 2.3.x on top of 2.2.x would end up.

Needs to have another set of 👀 @echarles.

Checking locally if all runs as expected.

@lresende, yes you were right on the things that got removed. I had to add them on an extra commit.
Thanks!

### CODE REVIEW

**Comment by jasongrout** [comment]
Given the title, I changed this to a draft PR

**Comment by goanpeca** [comment]
>Given the title, I changed this to a draft PR

:+1

**Comment by goanpeca** [comment]
@echarles I checked what was removed with https://github.com/jupyterlab/jupyterlab/pull/9173/files and then compared files on 2.2.x and 2.3.x to check all changes were there.

We might need to also check CSS files, I did not check those

**Comment by goanpeca** [comment]
Ok, I think I got eveything needed in. So this branch should be ready to replace 2.3.x. We will need to rebase the couple of PRs on top of 2.3.x

**Comment by goanpeca** [comment]
Closing as alpha has been released and `2.3.x` branch is now rebased on top of 2.2.x

**Pull request closed without merging**
