### PR TITLE
Fix issue #5349 by using a darker color as background when row selected

### LINKED ISSUE #5349: Dark scheme: Improve code completion dropbox selector contrast
**Describe the bug**
Could you please make more contrast selection row in code completion dropbox (at TAB press)?

image

- OS: Ubuntu LTS 16.04
- Browser Chrome Version 69.0.3497.100
- JupyterLab 0.34.11

### PR DESCRIPTION
**Pull request by Songyu-Wang**
Fixes #5349 

**Screenshots**
If applicable, add before and after screenshots to help show the issue being fixed, or the appearance of a new feature.

Before:
image

After:
image

### CODE REVIEW

**Comment by Songyu-Wang** [comment]
Please note light theme is also changed 
image
Not sure if this is ok

**Comment by blink1073** [comment]
cc @tgeorgeux

**Comment by jasongrout** [comment]
> do you mind trying "-jp-ui-inverse-font-color1", the Brand Color 1 leaves a bit to be desired on the light theme.

I tried it, and it doesn't work. For example, in the light theme the inverse font color is white, so you can't see the selection at all. In the dark theme the inverse font color is black, which is barely discernible against the dark grey background.

Perhaps themes need a new text selection color?

**Comment by jasongrout** [comment]
@tgeorgeux, @Songyu-Wang, how do you feel about extending @Songyu-Wang's original change to match the file browser selected colors at https://github.com/jupyterlab/jupyterlab/blob/a2c5f689bea86cad215ad0715235f86a7e292014/packages/filebrowser/style/index.css#L171-L174

screen shot 2018-09-28 at 1 10 46 am
screen shot 2018-09-28 at 1 10 30 am

**Comment by tgeorgeux** [comment]
That works for me. I think if we make this change, we could also use the brand color/white text in the command palette on active per Issue #1095

**Comment by Songyu-Wang** [comment]
looks good to me

**Comment by jasongrout** [comment]
> we could also use the brand color/white text in the command palette on active per Issue #1095

I think given that we want to use these sorts of things in the command palette, the filebrowser, and now the completer, that we should have a specific 'selected' background and font css variable color we can just apply wherever we want to show things selected in a list.

**Pull request merged**
