### PR TITLE
Adding RTC design document

### PR DESCRIPTION
**Pull request by ellisonbg**
I think we need to step back from the implementation details of real-time collaboration (RTC) and consider what Jupyter users need it to do. Towards this end I have written a set of personas for RTC. This document deliberately avoid getting into implementation details o RTC.

@ian-r-rose @blink1073 @afshin @jasongrout @sccolbert

### CODE REVIEW

**Comment by sccolbert** [comment]
How do you see the implementation working for user stories 1 and 3?

**Comment by ellisonbg** [comment]
We talked about this at the dev meeting today. I will add some additional usage cases and then start to clarify how we can address these usage cases with our current implementation plan.

**Comment by SimonBiggs** [comment]
Sorry if you are not after comments such as these, please let me know if this isn't helpful.

Something I would use it for would be one on one distance tutoring/training. Over the phone conversation while training/tutoring. The person being trained would likely be competent with computers, but may have limited programming experience. There would be a target use case that is being focused on, in my case related to medical physics.

**Comment by ellisonbg** [comment]
Yes! My first usage personal usage case is similar. My 11 year old son is
learning to program and is always wanting me to look at his code when I am
not with him. I will run a shared Jupyter server for him and use this
non-stop ;-)

**Comment by SimonBiggs** [comment]
:) this is an awesome project. Enabling things like that :)

**Comment by ellisonbg** [comment]
I pushed a few changes to these design personas. Once tests pass, I will merge.

**Comment by blink1073** [comment]
I suspect it will need a rebase if you haven't already done so due to the restructuring.

**Comment by ellisonbg** [comment]
OK, this one is ready to go. I was waiting to make sure the docs move didn't conflict, but merging now...

**Pull request merged**
