### PR TITLE
Require jinja2 2.10+ to fix extra escaping

### LINKED ISSUE #6941: Starting jupyterlab in a jupyterhub environment opens in an blank browser
Hi All,
I use Jupyterlab in a jupyterhub environment. The jupyterhub environment itself was installe using ansible. Since yesterday after installation of bokeh and ipywidgets Jupyter lab extensions (I did not upgrade jupyterhub db after installation), I cannot open jupyter lab in a browser at all. 
The versions:
Jupyter lab: 1.0.4
Jupyter notebook: 6.0.0
I tried the solutions offered in an earlier similar thread but nothng seems to work.
I deleted the jupyterhub.sqlite database and then rebuilt it, but it did not change anything.
Would greatly appreciate your guidance how to solve this issue.
Best,
Arindam Basu

### LINKED ISSUE #7053: Jupyterlab shows up as blank when using jupyterhub
# Description

At Airbnb, we want to serve our data scientists with hosted jupyter notebooks with jupyterhub. We are trying to add jupyterlab as an alternative for user interface. Installing into the single-user instances (inside docker), following the steps in https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html , upon replacing the /tree suburl with /lab, we get a blank screen as shown below:

image

image

## Reproduce

Unfortunately, it is difficult to give an MVCE of this problem because we have our own custom jupyterhub code that is not yet open to the public. However, it should not conflict with any jupyterlab things because it's mostly backend. Here's a log of the jupyter single-user output:

```
[D 2019-08-19 23:54:58.960 ray_zhang application:177] Searching ['/efs/home/ray_zhang', '/home/default_user/.jupyter', '/opt/conda/envs/jupyterhub/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2019-08-19 23:54:58.961 ray_zhang application:555] Looking for jupyter_config in /etc/jupyter
[D 2019-08-19 23:54:58.961 ray_zhang application:555] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2019-08-19 23:54:58.961 ray_zhang application:555] Looking for jupyter_config in /opt/conda/envs/jupyterhub/etc/jupyter
[D 2019-08-19 23:54:58.961 ray_zhang application:555] Looking for jupyter_config in /home/default_user/.jupyter
[D 2019-08-19 23:54:58.961 ray_zhang application:555] Looking for jupyter_config in /efs/home/ray_zhang
[D 2019-08-19 23:54:58.962 ray_zhang application:555] Looking for jupyter_notebook_config in /etc/jupyter
[D 2019-08-19 23:54:58.962 ray_zhang application:577] Loaded config file: /etc/jupyter/jupyter_notebook_config.py
[D 2019-08-19 23:54:58.962 ray_zhang application:555] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 2019-08-19 23:54:58.963 ray_zhang application:577] Loaded config file: /usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2019-08-19 23:54:58.963 ray_zhang application:555] Looking for jupyter_notebook_config in /opt/conda/envs/jupyterhub/etc/jupyter
[D 2019-08-19 23:54:58.963 ray_zhang application:577] Loaded config file: /opt/conda/envs/jupyterhub/etc/jupyter/jupyter_notebook_config.json
[D 2019-08-19 23:54:58.963 ray_zhang application:555] Looking for jupyter_notebook_config in /home/default_user/.jupyter
[D 2019-08-19 23:54:58.963 ray_zhang application:555] Looking for jupyter_notebook_config in /efs/home/ray_zhang
[W 2019-08-19 23:54:58.964 ray_zhang notebookapp:1245] server_extensions is deprecated, use nbserver_extensions
[D 2019-08-19 23:54:58.967 ray_zhang config_manager:98] Paths used for configuration of notebook:
    	/home/default_user/.jupyter/nbconfig/notebook.json
[D 2019-08-19 23:54:58.967 ray_zhang config_manager:98] Paths used for configuration of notebook:

[D 2019-08-19 23:54:58.968 ray_zhang config_manager:98] Paths used for configuration of notebook:
    	/home/default_user/.jupyter/nbconfig/notebook.json
[D 2019-08-19 23:54:58.968 ray_zhang config_manager:98] Paths used for configuration of notebook:

[D 2019-08-19 23:54:58.968 ray_zhang config_manager:98] Paths used for configuration of notebook:
    	/home/default_user/.jupyter/nbconfig/notebook.json
[D 2019-08-19 23:54:58.968 ray_zhang config_manager:98] Paths used for configuration of notebook:

[W 2019-08-19 23:54:59.112 ray_zhang login:236] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[D 2019-08-19 23:54:59.115 ray_zhang config_manager:98] Paths used for configuration of jupyter_notebook_config:
    	/etc/jupyter/jupyter_notebook_config.json
[D 2019-08-19 23:54:59.116 ray_zhang config_manager:98] Paths used for configuration of jupyter_notebook_config:
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2019-08-19 23:54:59.116 ray_zhang config_manager:98] Paths used for configuration of jupyter_notebook_config:
    	/opt/conda/envs/jupyterhub/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/opt/conda/envs/jupyterhub/etc/jupyter/jupyter_notebook_config.json
[D 2019-08-19 23:54:59.117 ray_zhang config_manager:98] Paths used for configuration of jupyter_notebook_config:
    	/home/default_user/.jupyter/jupyter_notebook_config.json
[D 2019-08-19 23:54:59.117 ray_zhang __init__:228] [jupyter_nbextensions_configurator] Loading 0.4.1
[D 2019-08-19 23:54:59.117 ray_zhang __init__:233] [jupyter_nbextensions_configurator]   Editing templates path to add /opt/conda/envs/jupyterhub/lib/python3.6/site-packages/jupyter_nbextensions_configurator/templates
[D 2019-08-19 23:54:59.117 ray_zhang __init__:246] [jupyter_nbextensions_configurator]   Editing nbextensions path to add /opt/conda/envs/jupyterhub/lib/python3.6/site-packages/jupyter_nbextensions_configurator/static
[D 2019-08-19 23:54:59.117 ray_zhang __init__:251] [jupyter_nbextensions_configurator]   Adding new handlers
[I 2019-08-19 23:54:59.118 ray_zhang __init__:259] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 2019-08-19 23:54:59.161 ray_zhang extension:155] JupyterLab extension loaded from /opt/conda/envs/jupyterhub/lib/python3.6/site-packages/jupyterlab
[I 2019-08-19 23:54:59.161 ray_zhang extension:156] JupyterLab application directory is /opt/conda/envs/jupyterhub/share/jupyter/lab
[I 2019-08-19 23:54:59.162 ray_zhang notebookapp:1772] Serving notebooks from local directory: /home/ray_zhang/redspot_home
[I 2019-08-19 23:54:59.162 ray_zhang notebookapp:1772] The Jupyter Notebook is running at:
[I 2019-08-19 23:54:59.162 ray_zhang notebookapp:1772] http://(i-07df6a2c840bea0b2 or 127.0.0.1):43953/user/ray_zhang/
[I 2019-08-19 23:54:59.162 ray_zhang notebookapp:1773] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 2019-08-19 23:55:03.696 ray_zhang auth:190] Received request from Hub user {'spawner': 'remote', 'name': 'ray_zhang', 'server': '/user/ray_zhang', 'admin': True, 'pending': None, 'groups': [], 'last_activity': '2019-08-19T18:46:06.926657'}
[D 2019-08-19 23:55:03.699 ray_zhang auth:287] Allowing whitelisted Hub user ray_zhang
[D 2019-08-19 23:55:03.700 ray_zhang handlers:259] Using contents: services/contents
[D 2019-08-19 23:55:03.704 ray_zhang log:48] 200 GET /user/ray_zhang/lab (::ffff:127.0.0.1) 41.71ms
[D 2019-08-19 23:55:03.838 ray_zhang auth:287] Allowing whitelisted Hub user ray_zhang
[D 2019-08-19 23:55:03.839 ray_zhang handlers:772] Path main.818a350c3d8e51c69afb.js served from /opt/conda/envs/jupyterhub/share/jupyter/lab/static/main.818a350c3d8e51c69afb.js
[D 2019-08-19 23:55:03.840 ray_zhang log:48] 304 GET /user/ray_zhang/static/lab/main.818a350c3d8e51c69afb.js (::ffff:127.0.0.1) 1.96ms
[D 2019-08-19 23:55:03.841 ray_zhang auth:287] Allowing whitelisted Hub user ray_zhang
[D 2019-08-19 23:55:03.842 ray_zhang handlers:772] Path vendors~main.16dd8e3ff113bfdf58cc.js served from /opt/conda/envs/jupyterhub/share/jupyter/lab/static/vendors~main.16dd8e3ff113bfdf58cc.js
[D 2019-08-19 23:55:03.842 ray_zhang log:48] 304 GET /user/ray_zhang/static/lab/vendors~main.16dd8e3ff113bfdf58cc.js (::ffff:127.0.0.1) 1.05ms
```

## Expected behavior

See the jupyterlab IDE look upon accessing `/lab` url

## Context

- Operating System and version:

```
root@i-07df6a2c840bea0b2:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

- Browser and version:

Chrome:
```
Version 76.0.3809.100 (Official Build) (64-bit)
```

- JupyterLab version:

```
jupyterlab==1.0.6
jupyterlab-server==1.0.4
```

<details><summary>Troubleshoot Output</summary>
<pre>
root@i-07df6a2c840bea0b2:/home/default_user/redspot_home# /opt/conda/envs/jupyterhub/bin/jupyter troubleshoot
WARNING: The directory '/efs/home/ray_zhang/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
$PATH:
	/opt/conda/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/srv/lib/spark/spark-2.4.0-bin-hadoop2.7/bin

sys.path:
	/opt/conda/envs/jupyterhub/bin
	/opt/conda/envs/jupyterhub/lib/python36.zip
	/opt/conda/envs/jupyterhub/lib/python3.6
	/opt/conda/envs/jupyterhub/lib/python3.6/lib-dynload
	/opt/conda/envs/jupyterhub/lib/python3.6/site-packages

sys.executable:
	/opt/conda/envs/jupyterhub/bin/python

sys.version:
	3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)
	[GCC 7.3.0]

platform.platform():
	Linux-4.4.0-154-generic-x86_64-with-debian-buster-sid

pip list:
	Package                           Version
	--------------------------------- ---------
	alembic                           0.9.3
	asn1crypto                        0.24.0
	attrs                             19.1.0
	backcall                          0.1.0
	bleach                            3.1.0
	boto3                             1.4.4
	botocore                          1.5.95
	certifi                           2019.6.16
	cffi                              1.12.3
	chardet                           3.0.4
	cryptography                      2.7
	datadog                           0.28.0
	decorator                         4.4.0
	deepmerge                         0.0.4
	defusedxml                        0.6.0
	docker                            2.4.2
	docker-pycreds                    0.4.0
	docutils                          0.15.2
	entrypoints                       0.3
	escapism                          1.0.0
	idna                              2.5
	ipykernel                         5.1.1
	ipython                           7.7.0
	ipython-genutils                  0.2.0
	ipywidgets                        7.5.0
	jedi                              0.15.1
	Jinja2                            2.9.6
	jmespath                          0.9.4
	json5                             0.8.5
	jsonschema                        3.0.2
	jupyter-client                    5.3.1
	jupyter-console                   5.2.0
	jupyter-contrib-core              0.3.3
	jupyter-core                      4.5.0
	jupyter-nbextensions-configurator 0.4.1
	jupyterhub                        0.7.2
	jupyterlab                        1.0.6
	jupyterlab-server                 1.0.4
	lxml                              4.4.1
	Mako                              1.1.0
	MarkupSafe                        1.1.1
	mistune                           0.8.4
	mysqlclient                       1.3.12
	nbconvert                         5.4.1
	nbformat                          4.4.0
	nose                              1.3.7
	notebook                          5.7.5
	pamela                            0.3.0
	pandocfilters                     1.4.2
	parso                             0.5.1
	pexpect                           4.7.0
	pickleshare                       0.7.5
	pip                               19.1.1
	prometheus-client                 0.7.1
	prompt-toolkit                    2.0.9
	ptyprocess                        0.6.0
	pycparser                         2.19
	Pygments                          2.4.2
	pyhocon                           0.3.38
	pyOpenSSL                         17.4.0
	pyparsing                         2.4.2
	pyrsistent                        0.15.4
	python-dateutil                   2.8.0
	python-editor                     1.0.4
	PyYAML                            3.12
	pyzmq                             18.1.0
	qtconsole                         4.5.1
	raven                             6.10.0
	requests                          2.18.1
	s3transfer                        0.1.13
	Send2Trash                        1.5.0
	setuptools                        41.1.0
	six                               1.12.0
	SQLAlchemy                        1.1.11
	straitlets                        0.3.1
	terminado                         0.8.2
	testpath                          0.4.2
	tornado                           4.5.1
	traitlets                         4.3.2
	urllib3                           1.21.1
	wcwidth                           0.1.7
	webencodings                      0.5.1
	websocket-client                  0.56.0
	wheel                             0.33.4
	widgetsnbextension                3.5.1

conda list:
	# packages in environment at /opt/conda:
	#
	asn1crypto                0.22.0           py27h94ebe91_1
	ca-certificates           2017.08.26           h1d4fec5_0
	certifi                   2017.7.27.1      py27h9ceb091_0
	cffi                      1.10.0           py27hf1aaaf4_1
	chardet                   3.0.4            py27hfa10054_1
	conda                     4.3.27           py27hff99c7a_0
	conda-env                 2.6.0                h36134e3_1
	cryptography              2.0.3            py27hea39389_1
	enum34                    1.1.6            py27h99a27e9_1
	idna                      2.6              py27h5722d68_1
	ipaddress                 1.0.18           py27h337fd85_0
	libedit                   3.1                  heed3624_0
	libffi                    3.2.1                h4deb6c0_3
	libgcc-ng                 7.2.0                hcbc56d2_1
	libstdcxx-ng              7.2.0                h24385c6_1
	ncurses                   6.0                  h06874d7_1
	openssl                   1.0.2l               h9d1a558_3
	pip                       9.0.1            py27h4c18a59_2
	pycosat                   0.6.2            py27h1cf261c_1
	pycparser                 2.18             py27hefa08c5_1
	pyopenssl                 17.2.0           py27h189ff3b_0
	pysocks                   1.6.7            py27he2db6d2_1
	python                    2.7.13              hfff3488_13
	readline                  7.0                  hac23ff0_3
	requests                  2.18.4           py27hc5b0589_1
	ruamel_yaml               0.11.14          py27h672d447_2
	setuptools                36.5.0           py27h68b189e_0
	six                       1.10.0           py27hdcd7534_1
	sqlite                    3.20.1               h6d8b0f3_1
	tk                        8.6.7                h5979e9b_1
	urllib3                   1.22             py27ha55213b_0
	wheel                     0.29.0           py27h411dd7b_1
	yaml                      0.1.7                h96e3832_1
	zlib                      1.2.11               hfbfcf68_1
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
lab:2 Uncaught SyntaxError: Unexpected token & in JSON at position 6
    at JSON.parse (<anonymous>)
    at Object.getOption (pageconfig.js:44)
    at Module.ANye (index.out.js:13)
    at n (bootstrap:84)
    at Object.0 (main.818a350c3d8e51c69afb.js:1)
    at n (bootstrap:84)
    at r (bootstrap:45)
    at Array.s [as push] (bootstrap:32)
    at vendors~main.16dd8e3ff113bfdf58cc.js:1
lab:1 Error handling response: TypeError: Cannot read property 'corp_email_domain' of undefined
    at chrome-extension://gbknpchijlnmdiejnppjnefniabialca/content_script_compiled.js:401:178
lab:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.</pre>
</details>

### PR DESCRIPTION
**Pull request by blink1073**
## References
Fixes #7053. 

## Code changes
Adds a requirement on `jinja2` 2.10+ to pick up https://github.com/pallets/jinja/pull/718

## User-facing changes
Fixes inability to load JupyterLab due to ill-formatted page config.

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by jasongrout** [comment]
> Fixes #6941.

That was reported with jlab 1.0.4, so I think that may be a separate issue.

**Comment by blink1073** [comment]
Thanks, I just updated the top level description.

**Comment by blink1073** [comment]
Note to self: conda-forge recipe will need an update as well.

**Comment by jasongrout** [comment]
And jupyterlab_server, since it uses the same tojson filter.

**Comment by blink1073** [comment]
PR coming...

**Comment by blink1073** [comment]
https://github.com/jupyterlab/jupyterlab_server/pull/77

**Comment by jasongrout** [comment]
> [ @blink1073 ](/blink1073)
> ` [Add missing whatwg-fetch dependency](/jupyterlab/jupyterlab/pull/7055/commits/25dfadcb315233554d78fa25ab210a9b1276830a)`

Huh. Why did this not complain before? This PR should not have changed this requirement, I think?

**Comment by blink1073** [comment]
Other recent PRs were failing for the same reason.  I think it may have come in transitively before.

**Comment by blink1073** [comment]
Still failing.  `whatwg-fetch` itself hasn't been updated in two years.

**Comment by blink1073** [comment]
`webpack-cli` was updated 3 days ago...

**Comment by jasongrout** [comment]
```
% yarn why whatwg-fetch                                                                 outputconsole
yarn why v1.15.2
[1/4] 🤔  Why do we have the module "whatwg-fetch"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "whatwg-fetch@3.0.0"
info Has been hoisted to "whatwg-fetch"
info Reasons this module exists
   - "workspace-aggregator-3bc6e7ea-abd1-4618-aaa4-5dc09a06097c" depends on it
   - Hoisted from "_project_#@jupyterlab#example-app#whatwg-fetch"
   - Hoisted from "_project_#@jupyterlab#example-notebook#whatwg-fetch"
   - Hoisted from "_project_#@jupyterlab#example-terminal#whatwg-fetch"
   - Hoisted from "_project_#@jupyterlab#example-cell#whatwg-fetch"
   - Hoisted from "_project_#@jupyterlab#example-filebrowser#whatwg-fetch"
   - Hoisted from "_project_#@jupyterlab#example-console#whatwg-fetch"
   - Hoisted from "_project_#fbjs#isomorphic-fetch#whatwg-fetch"
info Disk size without dependencies: "64KB"
info Disk size with unique dependencies: "64KB"
info Disk size with transitive dependencies: "64KB"
info Number of shared dependencies: 0
=> Found "webpack-visualizer-plugin#whatwg-fetch@0.9.0"
info Reasons this module exists
   - "_project_#@jupyterlab#application-top#webpack-visualizer-plugin#react#fbjs" depends on it
   - Hoisted from "_project_#@jupyterlab#application-top#webpack-visualizer-plugin#react#fbjs#whatwg-fetch"
info Disk size without dependencies: "24KB"
info Disk size with unique dependencies: "24KB"
info Disk size with transitive dependencies: "24KB"
info Number of shared dependencies: 0
✨  Done in 1.58s.
```

**Comment by jasongrout** [comment]
The webpack visualizer is new, right? It seems to be getting a very old version of the library, 0.9.0, from about 4 years ago.

**Comment by blink1073** [comment]
Add a new resolution :smile:?

**Comment by blink1073** [comment]
Actually, webpack visualizer is [unmaintained](https://github.com/chrisbateman/webpack-visualizer/issues/61#issuecomment-441326424), we should be using https://github.com/webpack-contrib/webpack-bundle-analyzer.

**Comment by jasongrout** [comment]
> The webpack visualizer is new, right?

It was recently re-enabled: https://github.com/jupyterlab/jupyterlab/pull/6706

**Comment by blink1073** [comment]
@vidartf, the failing test is `def test_build_custom_minimal_core_config(self):`.  Do you mind taking a look at this one?

**Comment by vidartf** [comment]
@blink1073 The coreconfig test uses the `package.json` in staging. Should the changes in `dev_mode/package.json` be propagated? How does the other test builds know to use the dev mode package.json ?

**Comment by blink1073** [comment]
Aha!  The `whatwg-fetch` requirement must come from one of the requirements that wasn't included in the minimal test.

**Comment by blink1073** [comment]
Python tests are passing now, thanks @vidartf!

**Comment by blink1073** [comment]
@jasongrout, it is getting to be the end of my time at the keyboard for today.  I can cut a patch release first thing tomorrow.

**Comment by jasongrout** [comment]
Sounds good. I'm afk myself.

**Comment by blink1073** [comment]
@meeseeksdev backport to 1.0.x

**Comment by blink1073** [comment]
I manually made the `jinja2` dependency change and released `1.0.7`.

**Pull request merged**
