### PR TITLE
Remove '*' prompt from cells that don't execute after an exception

### LINKED ISSUE #4916: Console: incorrect cell status update on interrupt
Interrupting the console's kernel will result in all cells except for the one that's being interrupted being shown as "running" forever:

image

### LINKED ISSUE #5366: UI: cell [*] asterisk is not reset if exception was thrown before
I've noticed a pretty annoying bug, especially for long notebooks.

When we run long-running cells or entire notebook the [*] marks at the left side of cells are not reset if it was an exception somewhere in prior cells.

image

**Desktop (please complete the following information):**

- OS: Linux Mint 18.3
- Browser chrome 69.0
- JupyterLab 0.34.11

### PR DESCRIPTION
**Pull request by reevejd**
Fixes #5366 and fixes #4916 

This PR is based on the [proposed fix here](https://github.com/jupyterlab/jupyterlab/issues/5366#issuecomment-424286069).

### CODE REVIEW

**Comment by jasongrout** [comment]
@reevejd - Thanks!

I'm not sure why you closed this, but thought I'd put down a couple of thoughts.

It looks like runCell now throws an error if the status was not 'ok', which propagates up to runSelected, so now `notebook.update()` is not called.

**Comment by reevejd** [comment]
Hi @jasongrout

I closed the PR by accident. Thanks for the feedback, good points. I've updated my PR accordingly. Are there any other changes you think I should make?

**Comment by jasongrout** [comment]
Works great for me. Good job untangling the logic - it's a bit tricky there. Thanks!

In another PR, it might be nice to switch this to use async/await rather than `.then` and `.catch` - it might make the logic a bit easier to follow.

**Comment by jasongrout** [comment]
(Waiting for appveyor to pass before merging...)

**Pull request merged**
