### PR TITLE
Automatic ids for headers and anchors following headers

### LINKED ISSUE #1592: Automatic anchors for markdown headings
Compared to the classic notebook, where markdown headings automatically had anchors and had clickable links that produced the URL for accessing the anchor, jupyterlab does not allow to refer to a single heading. This is an extremely useful feature for longer notebooks that often even contain a table of contents.

### PR DESCRIPTION
**Pull request by mpacer**
Closes #1592 for the purposes of notebook parity (incl. nice hover styling :) ).

Q: The plan is to eventually _not_ have this horrible approach to defining the ids; I still need to figure that out and isn't needed for feature parity. It'd be nice to be able to isolate the function that determines the id (which can't be done with a simple `.replace(/ /g, '-')` since there's a good deal more logic that needs to be added on. It'll be easy enough to swap out that line. *But* I see that in a lot of cases there are anonymous functions being passed around as arguments, should I be emulating that code pattern to get the more flexible behaviour?

↬ @ian-r-rose for helping me work through the ts aspects of the problem.

### CODE REVIEW

**Comment by michaelpacer** [comment]
NB: this can't use standard anchor link behaviour because internal links would then constantly be opening new tabs which would be terrible if you're just trying to navigate around a document.

**Comment by blink1073** [comment]
Nice Mike!  You can pass an optional function as:

```typescript
function headerAnchors(node: HTMLElement, fn?: (text: string) => text): void
...
if (fn) {
   // use the function
} else {
  // use the default
}
```

**Comment by blink1073** [comment]
Also for consideration: with multiple notebooks on the page, they might be competing for ids.

**Comment by michaelpacer** [comment]
It's worse than just multiple notebooks on the same page. It's more or less the result of aiming at feature parity. If you have more than one heading with the same text in the same notebook you also have conflicting ids.

Also, while there may be *some* way to avoid that in order to make notebooks work as standard markdown we may be stuck with this problem. 

Regardless it sounds like even once the improved header id solution is found for the notebook, more work will be needed to make this fully functional for jupyter lab. Presuming that cross notebook linking is supposed to eventually be.

**Comment by blink1073** [comment]
Some thoughts on this:
- We can pass a uuid derived from the full file path of the current document to the renderer.
- The anchor id includes that uuid.
- The open file command in JLab would parse the `#` suffix, open the file (or activate if already open), add the uuid to the anchor, and then navigate to it.
- If a file gets renamed while its document is open, we have to update its anchor tags.  We can handle this by searching for anchor elements within that document and replacing the previous uuid with the new one.

**Comment by michaelpacer** [comment]
@blink1073 The problem with using a uuid as part of the id is that people will need to include the uuid in their markup, which would sort of ruin the legibility of the document while it's being edited. For example, if I want to link to [the header that I wrote below using `[alt_text](#my-header-example)`](#my-header-example) it would be much nicer to use that text that is directly inferable from the text of the header rather than to have to check after the cell is rendered to see what the id will be and then re-edit the link to work.

# my header example

Cross document linking would seem to be a slightly different task than just getting internal links to work.

Also, the current test failures look like they are arising because it's specifically expecting headers to have no ids. Should I change the test to expect this as part of this PR?

**Comment by michaelpacer** [comment]
Is the reason installation is failing on this due to the fact that by this scheme of generating header ids, we are generating non-unique ids and so it won't install at all? It's unclear to me how to interpret this behaviour.

**Comment by blink1073** [comment]
Mike, just saw this but on my way to dinner, will take a look later.

**Comment by blink1073** [comment]
The uuid would not need to be included in the markup, it would be added to the generated anchor tag during the render step.

**Comment by blink1073** [comment]
Looking into the tests now.

**Comment by michaelpacer** [comment]
So the generated anchor tag would have a unique id separate from the header's id?

**Comment by blink1073** [comment]
I think the header tag should not have an id, just the anchor tag.

**Comment by blink1073** [comment]
Err, the other way around, the header has the id only.

Here is the expected output, which can be pasted into the test `EXPECTED_MD`:

```html
<h1 id="Title-first-level">Title first level<a target="_self" href="#Title-first-level" class="jp-InternalAnchorLink">¶</a></h1>\n<h2 id="Title-second-Level">Title second Level<a target="_self" href="#Title-second-Level" class="jp-InternalAnchorLink">¶</a></h2>\n<h3 id="Title-third-level">Title third level<a target="_self" href="#Title-third-level" class="jp-InternalAnchorLink">¶</a></h3>\n<h4 id="Title-fourth-level">Title fourth level<a target="_self" href="#Title-fourth-level" class="jp-InternalAnchorLink">¶</a></h4>\n<h5 id="Title-fifth-level">Title fifth level<a target="_self" href="#Title-fifth-level" class="jp-InternalAnchorLink">¶</a></h5>\n<h6 id="Title-sixth-level">Title sixth level<a target="_self" href="#Title-sixth-level" class="jp-InternalAnchorLink">¶</a></h6>\n<h1 id="h1">h1<a target="_self" href="#h1" class="jp-InternalAnchorLink">¶</a></h1>\n<h2 id="h2">h2<a target="_self" href="#h2" class="jp-InternalAnchorLink">¶</a></h2>\n<h3 id="h3">h3<a target="_self" href="#h3" class="jp-InternalAnchorLink">¶</a></h3>\n<h4 id="h4">h4<a target="_self" href="#h4" class="jp-InternalAnchorLink">¶</a></h4>\n<h5 id="h6">h6<a target="_self" href="#h6" class="jp-InternalAnchorLink">¶</a></h5>\n<p>This is just a sample paragraph\nYou can look at different level of nested unorderd list ljbakjn arsvlasc asc asc awsc asc ascd ascd ascd asdc asc</p>\n<ul>\n<li>level 1<ul>\n<li>level 2</li>\n<li>level 2</li>\n<li>level 2<ul>\n<li>level 3</li>\n<li>level 3<ul>\n<li>level 4<ul>\n<li>level 5<ul>\n<li>level 6</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n<li>level 2</li>\n</ul>\n</li>\n<li>level 1</li>\n<li>level 1</li>\n<li>level 1\nOrdered list</li>\n<li>level 1<ol>\n<li>level 1</li>\n<li>level 1<ol>\n<li>level 1</li>\n<li>level 1</li>\n<li>level 1<ol>\n<li>level 1</li>\n<li>level 1<ol>\n<li>level 1</li>\n<li>level 1</li>\n<li>level 1</li>\n</ol>\n</li>\n</ol>\n</li>\n</ol>\n</li>\n</ol>\n</li>\n<li>level 1</li>\n<li>level 1\nsome Horizontal line</li>\n</ul>\n<hr>\n<h2 id="and-another-one">and another one<a target="_self" href="#and-another-one" class="jp-InternalAnchorLink">¶</a></h2>\n<p>Colons can be used to align columns.</p>\n<table>\n<thead>\n<tr>\n<th>Tables</th>\n<th>Are</th>\n<th>Cool</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>col 3 is</td>\n<td>right-aligned</td>\n<td>1600</td>\n</tr>\n<tr>\n<td>col 2 is</td>\n<td>centered</td>\n<td>12</td>\n</tr>\n<tr>\n<td>zebra stripes</td>\n<td>are neat</td>\n<td>1</td>\n</tr>\n</tbody>\n</table>\n<p>There must be at least 3 dashes separating each header cell.\nThe outer pipes (|) are optional, and you don\'t need to make the\nraw Markdown line up prettily. You can also use inline Markdown.</p>\n
```

**Comment by blink1073** [comment]
Either way, this is a great first step and I think we should merge and iterate (once the tests pass).

**Comment by michaelpacer** [comment]
An aside for why there are so many prs attempting to solve this… I had a trouble testing this locally which seems to be related to jedi, ipython completion, and ipykernel (@carreau): 

Here's the relevant traceback

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "~/jupyter/ipykernel/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "~/jupyter/ipykernel/ipykernel/kernelbase.py", line 425, in complete_request
    matches = self.do_complete(code, cursor_pos)
  File "~/jupyter/ipykernel/ipykernel/ipkernel.py", line 257, in do_complete
    txt, matches = self.shell.complete('', line, line_cursor)
  File "~/jupyter/ipython/IPython/core/interactiveshell.py", line 1958, in complete
    return self.Completer.complete(text, line, cursor_pos)
  File "~/jupyter/ipython/IPython/core/completer.py", line 1719, in complete
    return self._complete(line_buffer=line_buffer, cursor_pos=cursor_pos, text=text, cursor_line=0)[:2]
  File "~/jupyter/ipython/IPython/core/completer.py", line 1784, in _complete
    cursor_pos, cursor_line, full_text)
  File "~/jupyter/ipython/IPython/core/completer.py", line 1143, in _jedi_matches
    if pre == '.':
UnboundLocalError: local variable 'pre' referenced before assignment
```

Looks like it's a simple declaration issue, but I can't imagine that this wouldn't have turned up in some other set of tests, so I'm having to imagine that this is an integration bug. Has this turned up for anyone else? If not, I'll try to figure out why my system is behaving strangely.

**Comment by blink1073** [comment]
@michaelpacer, I am not using the dev version of ipython.  I sent a PR that makes the tests less brittle (the order of the attributes was different on Windows).

**Comment by mpacer** [comment]
Is that OS specific ordering desirable? It shouldn't matter, but that seems like it would be heinous to hunt down if it causes issues down the line.

**Comment by Carreau** [comment]
which commit of IPython triggers this ? This line can't trigger UnboundError on master:
```
pre = text[offset-1]
if pre == '.':
   ...
```

**Comment by Carreau** [comment]
And that should have been fixed by @ian-r-rose in ipython/ipython#10372 if I understand correctly.

**Comment by ian-r-rose** [comment]
Yes, that should be fixed in IPython master.

**Comment by mpacer** [comment]
Yep — I figured out what was happening! I'd been rebasing as part of a larger command chain and hadn't recognised that the rebase was refused. Apologies for that!

**Comment by blink1073** [comment]
@mpacer, the problem is that `innerHTML` is not guaranteed to print out in a specific order, which is why I updated the tests to avoid using it.  Thanks for this!

**Pull request merged**
