### PR TITLE
Backport PR #11358 on branch 3.3.x (Fix Handling of WebSocket Startup Errors)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #11358: Fix Handling of WebSocket Startup Errors

### CODE REVIEW

**Comment by Zsailer** [comment]
Test failures appear to be unrelated to this PR. I'm verifying locally.

**Comment by jtpio** [comment]
Thanks @Zsailer.

This indeed looks unrelated and should be fixed by https://github.com/jupyterlab/jupyterlab/pull/11846.

**Comment by Zsailer** [comment]
@meeseeksmachine rebase

**Comment by jtpio** [comment]
@meeseeksdev rebase

**Comment by Zsailer** [comment]
I don't think Meeseeks feels like rebasing today 😆

**Pull request merged**
