### PR TITLE
Add save action when exiting unsaved notebook

### PR DESCRIPTION
**Pull request by quangIO**
## References
#8094 Improvement to Save dialog

## Code changes
- Change some promises to async/await.
- Write new function called `dangerDialog` in testutils to click on a warning button in a dialog
- Replace the acceptDialog -> dangerDialog in widgetmanager.spec.ts accordingly

## User-facing changes
The exit dialog now looks like this
exit dialog with 3 button

## Backwards-incompatible changes
Nothing that I am aware of

### CODE REVIEW

**Comment by Juan-132** [comment]
The ‘Discard changes’ button right now is the only button that uses double-word notation. This makes it inconsistent with the Save (Changes) button. (and also quite wide visually).

I would suggest naming the title: Unsaved Changes (instead of Confirm Close)
And the button names in short form: Cancel, Discard, Save

This makes it clear that the buttons are actions with regard to the unsaved changes.

**Comment by Juan-132** [comment]
The subtitle right now is a two part sentence separated by comma. Per https://material.io/design/communication/writing.html#principles  ` Skip unnecessary punctuation` that is not encouraged.

Could we make this into a single sentence like: Do you want to save changes to < filename >? 



,

**Comment by blink1073** [comment]
cc @tgeorgeux for UX input.

**Comment by tgeorgeux** [comment]
@Juan-132 thank you for referencing the Material Guidelines in your feedback, I love to see that!

Screen Shot 2020-04-23 at 1 36 34 PM

The action the user takes to view this warning is closing the document while having unsaved changes in the document. I don't believe we're trying to confirm the close, but we're trying to encouraging saving instead. So I think the warning "Save Before Closing?" more clearly communicates what's at stake here. In essence, we're trying to confirm or deny the save, not the close.


Screen Shot 2020-04-23 at 1 36 45 PM
We can simplify the body sentence to remove the comma, I think we should also include the close as part of that copy: "Save changes to "< filename >" before closing?"

**Comment by Juan-132** [comment]
Great proposal @tgeorgeux !

Maybe a final point worth discussing:
* The discard action now reads: Discard changes
* The save action now reads: Save
This makes the 'Discard changes' button quite wide and prominent in the dialog (and therefor draws attention - while we'd want this to be on the default Save button.)

Is there a way to balance this out more. Two possible solutions from the top of my head:
1. Cancel / Discard changes / Save changes
2. Cancel / Discard / Save

**Comment by quangIO** [comment]
I reworded the prompt:
- Options: `Cancel / Discard / Save`
- Description: Save changes in "< filename >" before closing?
  - If the file is not writable, there will be the Save as option instead of Save
- Title: Save your work.

If there are more suggestions, please let me know.

**Comment by tgeorgeux** [comment]
This looks great to me, @blink1073 do you mind putting eyes over the code before I press the green button?

**Comment by blink1073** [comment]
I'm afk for the night, I'll review in the morning.  Thanks again @quangIO!

**Comment by blink1073** [comment]
Congratulations on you first contribution to JupyterLab @quangIO!

**Comment by Juan-132** [comment]
Excellent work @quangIO !

**Comment by tgeorgeux** [comment]
Kudos to @Juan-132 design work is under-rated! <3<3<3

**Comment by Juan-132** [comment]
You too @tgeorgeux :)

**Pull request merged**
