### PR TITLE
Add changelog for 3.0.6

### PR DESCRIPTION
**Pull request by blink1073**
## References
Update changelog for PRs merged since 3.0.5.

## Code changes
None

## User-facing changes
Updated changelog.

## Backwards-incompatible changes
None

### CODE REVIEW

**Review by jasongrout — APPROVED** [review]
Thanks. This looks great!

**Comment by jasongrout** [comment]
Generated docs look okay too. Thanks!

**Comment by jasongrout** [comment]
@meeseeksdev, backport to 3.0.x

**Comment by jasongrout** [comment]
Is MeeSeeksDev not working?

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.0.x

**Comment by blink1073** [comment]
I think it doesn't understand commas

**Comment by jasongrout** [comment]
ah, makes sense. Uh, I mean: ah makes sense :).

**Pull request merged**
