### PR TITLE
remove Trust Notebook from command palette

### LINKED ISSUE #5354: Remove "Trust Notebook" menu item?
The "Trust Notebook" menu item exists in the command palette. I think it is a sufficiently advanced and not-used feature that perhaps we shouldn't complicate the menu system with this menu item.

I'm bringing this up for discussion for 1.0.

### PR DESCRIPTION
**Pull request by manuel-ruiz-23**
Fixes #5354 

**Screenshots**
screenshot from 2018-11-15 12-22-32
screenshot from 2018-11-15 12-20-54

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks. #5354 is about removing the item from the main menu, but keeping it in the command palette. Can you do that instead?

**Comment by manuel-ruiz-23** [comment]
hahaha yeah sure, I miss understood the issue.

**Comment by manuel-ruiz-23** [comment]
Thanks, now the "Trust notebook" option is removed from the correct menu . 
screenshot from 2018-11-16 10-40-36

**Comment by blink1073** [comment]
Thanks!

**Pull request merged**
