### PR TITLE
Clear breakpoints when disposing an editor

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Partialy address #11467

## Code changes

When disposing an editor handler, the associated breakpoints are cleared.

Minor changes:
- Fix usage of translation
- Use non-nullish operator instead of or operator

## User-facing changes

This clear the breakpoints when a cell is cut or deleted.

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @fcollonval for looking into this.

Wondering if this is a behavior we want for the debugger? I believe it used to be possible to undo a cell deletion are retrieve the previous breakpoints automatically, which was considered convenient. When testing on the Binder for this PR this does not seem to be the case anymore?

https://user-images.githubusercontent.com/591645/147765294-b620d682-4961-4300-a479-23a4483e4823.mp4

**Comment by jtpio** [comment]
> I believe it used to be possible to undo a cell deletion are retrieve the previous breakpoints automatically

Testing on `3.2.5` with this gist: https://gist.github.com/jtpio/6ce26381703355e0ef1da4af742b7f72

Shows that it was indeed the case:

https://user-images.githubusercontent.com/591645/147765460-0ff0e7ed-cc4e-4a71-a19e-e6058049a08b.mp4

**Comment by jtpio** [comment]
Should this be bumped to `3.3.x`?

**Comment by fcollonval** [comment]
Closing as the current approach is conflicting with another feature

**Pull request closed without merging**
