### PR TITLE
margin edit

### PR DESCRIPTION
**Pull request by g547315**

### CODE REVIEW

**Comment by g547315** [comment]
please update galata snapshots

**Comment by g547315** [comment]
please update galata snapshots

**Comment by g547315** [comment]
please update galata snapshots

**Comment by g547315** [comment]
please update galata snapshots

**Comment by g547315** [comment]
please update documentation snapshots

**Comment by g547315** [comment]
please update galata snapshots

**Comment by krassowski** [comment]
Closing as this PR appears to have been a test and is not associated with any issue/has no description. If you would like to continue here, please update the description and re-open :)

**Pull request closed without merging**
