### PR TITLE
Update yarn commands to fix binder

### LINKED ISSUE #14264: Binder build fail on PRs
## Description

```
 ---> 4b2667f29033
Step 47/52 : RUN ./binder/postBuild
 ---> Running in fc72849731c8
+ mkdir _reports_
+ tee _reports_/00_yarn.txt
+ yarn --ignore-scripts --ignore-optional
Unknown Syntax Error: Unsupported option name ("--ignore-scripts").

$ yarn cache clean [--mirror] [--all]
$ yarn cache clean [--mirror] [--all]
$ yarn config get [--json] [--no-redacted] <name>
$ yarn config set [--json] [-H,--home] <name> <value>
$ yarn config unset [-H,--home] <name>
$ yarn set resolution [-s,--save] <descriptor> <resolution>
$ yarn set version from sources [--path #0] [--repository #0] [--branch #0] [--plugin #0] [--no-minify] [-f,--force] [--skip-plugins]
$ yarn set version [--only-if-needed] <version>
$ yarn workspaces list [--since] [-R,--recursive] [--no-private] [-v,--verbose] [--json]
$ yarn --clipanion=definitions
$ yarn help
$ yarn help
$ yarn help
$ yarn <leadingArgument> ...
$ yarn -v
$ yarn -v
$ yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
$ yarn bin [-v,--verbose] [--json] [name]
$ yarn config [-v,--verbose] [--why] [--json]
$ yarn dedupe [-s,--strategy #0] [-c,--check] [--json] [--mode #0] ...
$ yarn exec <commandName> ...
$ yarn explain peer-requirements [hash]
$ yarn explain [--json] [code]
$ yarn info [-A,--all] [-R,--recursive] [-X,--extra #0] [--cache] [--dependents] [--manifest] [--name-only] [--virtuals] [--json] ...
$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
$ yarn link [-A,--all] [-p,--private] [-r,--relative] <destination>
$ yarn unlink [-A,--all] ...
$ yarn node ...
$ yarn plugin import from sources [--path #0] [--repository #0] [--branch #0] [--no-minify] [-f,--force] <name>
$ yarn plugin import <name>
$ yarn plugin remove <name>
$ yarn plugin list [--json]
$ yarn plugin runtime [--json]
$ yarn rebuild ...
$ yarn remove [-A,--all] [--mode #0] ...
$ yarn run
$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
$ yarn up [-i,--interactive] [-E,--exact] [-T,--tilde] [-C,--caret] [-R,--recursive] [--mode #0] ...
$ yarn why [-R,--recursive] [--json] [--peers] <package>
$ yarn workspace <workspaceName> <commandName> ...
$ yarn create [-p,--package #0] [-q,--quiet] <command> ...
$ yarn dlx [-p,--package #0] [-q,--quiet] <command> ...
$ yarn init [-p,--private] [-w,--workspace] [-i,--install]
$ yarn npm audit [-A,--all] [-R,--recursive] [--environment #0] [--json] [--severity #0] [--exclude #0] [--ignore #0]
$ yarn npm info [-f,--fields #0] [--json] ...
$ yarn npm login [-s,--scope #0] [--publish]
$ yarn npm logout [-s,--scope #0] [--publish] [-A,--all]
$ yarn npm publish [--access #0] [--tag #0] [--tolerate-republish] [--otp #0]
$ yarn npm tag add <package> <tag>
$ yarn npm tag list [--json] [package]
$ yarn npm tag remove <package> <tag>
$ yarn npm whoami [-s,--scope #0] [--publish]
$ yarn pack [--install-if-needed] [-n,--dry-run] [--json] [-o,--out #0]
$ yarn patch-commit [-s,--save] <patchFolder>
$ yarn patch [--json] <package>
$ yarn unplug [-A,--all] [-R,--recursive] [--json] ...

real    0m1.565s
user    0m1.509s
sys     0m0.194s
Removing intermediate container fc72849731c8
The command '/bin/sh -c ./binder/postBuild' returned a non-zero code: 1
```

## Reproduce

Try binder badge on https://github.com/jupyterlab/jupyterlab/pull/14109 or https://github.com/jupyterlab/jupyterlab/pull/14205

## Expected behavior

Binder works.

### PR DESCRIPTION
**Pull request by krassowski**
## References

Yarn 3 migration follow-up. Fixes #14264

## Code changes

- fully specifies yarn commands (e.g. `yarn install` instead of `yarn`).
- disables scripts using config (`enableScripts = false`, close enough to `--ignore-scripts` in old yarn but does not disable scripts for current project https://github.com/yarnpkg/yarn/issues/7338#issuecomment-1426863192, https://github.com/yarnpkg/berry/pull/4781),
- removes `ignore-optional` which is not implemented in yarn 3 (and not planned see https://github.com/yarnpkg/berry/discussions/2412)

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @krassowski :+1: 

Just checked on Binder and it is currently giving the following:

image

**Comment by krassowski** [comment]
This now builds but consistently times out indicating that something is wrong:

```
Spawn failed: pod ovh2/jupyter-krassowski-2djupyterlab-2dkn2x4iqk did not start in 300 seconds!
Launch attempt 2 failed, retrying...
```

**Comment by bollwyvl** [comment]
I don't think we can use `--ignore-scripts` anymore, sadly, due to some of the dev tools.

**Comment by krassowski** [comment]
Feel welcome to push to my branch if you see a solution:)

**Comment by bollwyvl** [comment]
trying some stuff on #14272...

**Comment by bollwyvl** [comment]
Working binder :tada: 

Broken rjsf (still draws form):

```
react-dom.development.js:86 Warning: React does not recognize the `hideLabel` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `hidelabel` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at input
    at BaseInputTemplate (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:2162:18)
    at TextWidget (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:3525:23)
    at MergedWidget (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_utils_dist_utils_esm_js.090f94ac0445357ad449.js:2436:26)
    at StringField (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:1873:22)
    at div
    at div
    at div
    at factory (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/packages_ui-components_lib_index_js.2c93f44a9a9fe39bc945.js:649:32)
    at SchemaFieldRender (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:1660:23)
    at SchemaField (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:1854:23)
    at fieldset
    at factory (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/packages_ui-components_lib_index_js.2c93f44a9a9fe39bc945.js:649:32)
    at ObjectField (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:1329:29)
    at div
    at div
    at div
    at factory (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/packages_ui-components_lib_index_js.2c93f44a9a9fe39bc945.js:649:32)
    at SchemaFieldRender (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:1660:23)
    at SchemaField (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:1854:23)
    at div
    at div
    at factory (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/packages_ui-components_lib_index_js.2c93f44a9a9fe39bc945.js:649:32)
    at ArrayField (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:163:24)
    at div
    at div
    at div
    at factory (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/packages_ui-components_lib_index_js.2c93f44a9a9fe39bc945.js:649:32)
    at SchemaFieldRender (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:1660:23)
    at SchemaField (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:1854:23)
    at fieldset
    at factory (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/packages_ui-components_lib_index_js.2c93f44a9a9fe39bc945.js:649:32)
    at ObjectField (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:1329:29)
    at div
    at div
    at div
    at factory (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/packages_ui-components_lib_index_js.2c93f44a9a9fe39bc945.js:649:32)
    at SchemaFieldRender (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:1660:23)
    at SchemaField (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:1854:23)
    at form
    at Form (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/vendors-node_modules_rjsf_core_dist_core_esm_js-node_modules_react-dom_client_js-node_modules-3a33f5.e40f28862142c4ca9c94.js:3631:24)
    at FormComponent (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/packages_ui-components_lib_index_js.2c93f44a9a9fe39bc945.js:796:13)
    at div
    at SettingsFormEditor (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/packages_settingeditor_lib_index_js.7bc079e9c5c7728c784b.js:46:9)
    at div
    at div
    at SettingsPanel (https://hub.gke2.mybinder.org/user/bollwyvl-jupyterlab-fwauwgnx/static/lab/packages_settingeditor_lib_index_js.7bc079e9c5c7728c784b.js:1719:26)
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
validateProperty$1 @ react-dom.development.js:3757
warnUnknownProperties @ react-dom.development.js:3803
validateProperties$2 @ react-dom.development.js:3827
validatePropertiesInDevelopment @ react-dom.development.js:9541
setInitialProperties @ react-dom.development.js:9830
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26593
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

**Comment by fcollonval** [comment]
Closed following the merge of #14273

**Pull request closed without merging**
