### PR TITLE
Prevent focus loss on `mouseout` for `input` elements inside toolbar

### PR DESCRIPTION
**Pull request by AlbertHilb**
This is a refinement of PR #5328.
The code introduced there prevents focus loss caused by `mouseup`, but not by `mouseout`.
This fix works in either case.

Cheers

### CODE REVIEW

**Comment by ian-r-rose** [comment]
I am starting to think that the auto-defocusing of toolbars is more trouble than it is worth. It *may* also cause some accessibility issues. What if we removed this `mouseup`/`mouseout` logic alltogether?

**Comment by blink1073** [comment]
My concern is that we don't have any visual indication that the toolbar has focus, which is the original reason I added the de-focusing behavior.

**Comment by AlbertHilb** [comment]
I'm in favor of removing toolbar auto-defocusing.
In my understanding it is essentially intended to avoid clicking on buttons steal focus from main content.
The same can be achieved, for example, binding button action to `mousedown` event and preventing default.

**Comment by blink1073** [comment]
Ohh, nice, @AlbertHilb, do you mind updating this PR to add that behavior to [ToolbarButton](https://github.com/jupyterlab/jupyterlab/blob/7e67f49160e185b93bfc251c05de050dd65524a6/packages/apputils/src/toolbar.tsx#L434) and remove the de-focus logic?

**Comment by AlbertHilb** [comment]
Done.

**Comment by blink1073** [comment]
Nice, thanks!  It looks like the apputils toolbar tests need updating.

**Comment by blink1073** [comment]
You can run just the toolbar tests as `jlpm test --pattern=src/toolbar.spec.ts` from `tests/test-apputils`.

**Comment by AlbertHilb** [comment]
I only updated non-commented-out tests. Is it ok?

**Comment by ellisonbg** [comment]
I haven’t been following the details of this one in particular, but do want to mention that we have tend to run into subtle side effects when we play with focus manually - Ian also makes a good point about accessibility

**Comment by AlbertHilb** [comment]
I noted also `notebook` has failing tests. I'm going to update those too.

**Comment by ian-r-rose** [comment]
Love to see all that deleted code!

**Comment by AlbertHilb** [comment]
Tests updated.

**Comment by blink1073** [comment]
Thanks!

**Pull request merged**
