### PR TITLE
Update screenshots and text for user interface docs

### PR DESCRIPTION
**Pull request by krassowski**
## References

Addresses https://discourse.jupyter.org/t/items-missing-from-the-left-sidebar/10794

## Code changes

None

## User-facing changes

Docs include updated screenshots and UI descriptions in a few (but not all) places.

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
I think that "Enforce PR label" ( https://github.com/jupyterlab/jupyterlab/pull/11496) should wait for the "Pull Request Labeler" or be re-triggered after labeller finishes. CC @blink1073.

**Review by fcollonval — APPROVED** [review]
Thanks a lot @krassowski - especially for taking the time to update the screenshot (we should definitely automated them...).

**Comment by jtpio** [comment]
It would be great to have a small Galata / Playwright script to take these screenshots. Although we would need a way to add overlays (mouse pointer, arrow)

**Comment by blink1073** [comment]
> I think that "Enforce PR label" ( #11496) should wait for the "Pull Request Labeler" or be re-triggered after labeller finishes. CC @blink1073.

That's a good point, it could be modified to be a dependent workflow, but then both would fail on PRs that end up trying to label all of the sub packages, since the labeler build fails.

**Comment by fcollonval** [comment]
Would it work to set the two jobs in the same workflow file so that it can be triggered even if the labeller fails?

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/items-missing-from-the-left-sidebar/10794/4

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.2.x

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.3.x

**Pull request merged**
