### PR TITLE
Fix missing deduplicate command when using build:core

### PR DESCRIPTION
**Pull request by lresende**
## Code changes

Fix typo on deduplicate command. `deduplicate` should be `yarn-deduplicate`

### CODE REVIEW

**Comment by telamonian** [comment]
Is this what we actually want? What role does `build:core` currently play in the build system? And what is the general policy about when to dedupe?

I for one am fairly confused. In my own workflow, I never run `build:core`, and I only dedupe when there's an obvious problem. Aside from performance issues, is there a good reason not to always dedupe as part of integrity?

**Comment by lresende** [comment]
Good question @telamonian, note that without this fix `build:core` was giving an error `deduplicate not found` and  continuing. This fix mainly address that issue. As for your broader question, I guess I let other chime in.

**Comment by telamonian** [comment]
@saulshanabrook @blink1073 What do you guys think? I'm leaning towards the idea that dedupe should be part of integrity, since it affects the `yarn.lock`

**Comment by saulshanabrook** [comment]
> What do you guys think? I'm leaning towards the idea that dedupe should be part of integrity, since it affects yarn.lock

I don't really know what the dedupe command does. I also don't know when to run `build:core`

**Comment by telamonian** [comment]
>  I also don't know when to run `build:core`

I'm pretty sure that `build:core` is completely useless in the current build system, though anyone please correct me if that's wrong.

`jlpm build:core` builds the jlab bundle in the `staging` dir within the repo itself. So far as I can tell, said bundle will never get loaded by any variation of the `jupyter lab --whatever` cmd, nor does it get used by anything else in the build.

**Comment by jasongrout** [comment]
> `jlpm build:core` builds the jlab bundle in the `staging` dir within the repo itself. So far as I can tell, said bundle will never get loaded by any variation of the `jupyter lab --whatever` cmd, nor does it get used by anything else in the build.

I think that would get used if you did `pip install -e` and `jupyter lab --core-mode` to run from the staging directory.

**Comment by vidartf** [comment]
I think this is intended to run a command similar to the one in the root package. I think we will need some careful digging in the git history to figure out why it ended up like this.

**Comment by blink1073** [comment]
@vidartf is right that it is calling the `deduplicate` script in the root package.  
Staging has an independent `yarn.lock` that is created during the publish process, which is why we explicitly need to deduplicate it here.
The `build:core` command is run as part of the publish process.  The assets in `staging` are also what ends up in `share/jupyter/lab/`.
I think we can close this with no action.

**Comment by lresende** [comment]
So, if I follow the steps on `contributing.md`, and perform:
```
git clone https://github.com/<your-github-username>/jupyterlab.git
cd jupyterlab
pip install -e .
jlpm install
jlpm run build  # Build the dev mode assets (optional)
jlpm run build:core  # Build the core mode assets (optional)
jupyter lab build  # Build the app dir assets (optional)
```

I would get:
```
...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
**error Command "deduplicate" not found.**
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
```

Is this error the expected result? Are there possible side effects related to not performing the deduplication?

**Comment by vidartf** [comment]
@blink1073 I think what @lresende is pointing out is that the `package.json` file in staging does not have the `dedupe` script defined.

**Comment by blink1073** [comment]
Yeah, that's fair.  Copying the script from the root `package.json` to `dev_mode/package.json` makes sense to me.

**Comment by lresende** [comment]
Ok, I going to update the pr with the suggestion above a little later today.

**Comment by blink1073** [comment]
Thanks!

**Pull request merged**
