### PR TITLE
Enable JupyterLab to run as an old notebook server extension

### LINKED ISSUE #8943: Binder bot dev mode does not redirect to JupyterLab
## Description

Looks like the Binder link posted by the bot on new PRs does not redirect to the dev mode lab anymore:

image

## Reproduce

Go to an open PR and click on the Binder link:

image

### PR DESCRIPTION
**Pull request by Zsailer**
## References

Fixes #8943.  

## Code changes

Reinstates `serverextension.py` module to enable jupyterlab to run on classic notebook server.

## User-facing changes

None 

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by blink1073** [comment]
We're going to augment `browser_check` so we can change the command and args used to test  with `jupyter notebook --NotebookApp.default_url=/lab`

**Comment by blink1073** [comment]
Still seeing this on the binder link:

image

**Comment by blink1073** [comment]
@Zsailer were there some local changes to one of the repos that we needed?

**Comment by Zsailer** [comment]
It *might* need jupyter/jupyter_server#303 and jupyterlab/nbclassic#24—though that would only be true is binder installed some extension that was broken...

**Comment by blink1073** [comment]
Hmm, the binder link is now giving:

```
Launching server...
Internal Server Error
```

**Comment by Zsailer** [comment]
I think this was a binder issue... It seems to be launching for me again. Still hitting the same 404s from above.

**Comment by Zsailer** [comment]
I'm actually getting the same 404s when I try a clean install locally... diving into this more.

**Pull request merged**
