### PR TITLE
Upgrade to TypeScript 3.7

### PR DESCRIPTION
**Pull request by jasongrout**
## References

This supersedes #7428.

## Code changes

Upgrade to Typescript 3.7, and use skipLibChecks on the vega extensions (see #7428 for more details).

## User-facing changes

None

## Backwards-incompatible changes

Upgraded Typescript

### CODE REVIEW

**Comment by blink1073** [comment]
There is a newer value of typedoc that supports TS3.7: https://github.com/TypeStrong/typedoc/pull/1129

**Comment by jasongrout** [comment]
> There is a newer version of typedoc that supports TS3.7: [TypeStrong/typedoc#1129](https://github.com/TypeStrong/typedoc/pull/1129)

Oh wow, that has to be a record for typedoc supporting a new release! Nice!

**Comment by jasongrout** [comment]
The doc build seems to work, except for coreutils:

```
[snip]/jupyterlab/packages/coreutils% jlpm run docs
yarn run v1.15.2
$ typedoc src src/plugin-schema.json

Using TypeScript 3.7.2 from /[snip]/jupyterlab/node_modules/typescript/lib
Error: /[snip]/jupyterlab/packages/coreutils/src/settingregistry.ts(23)
 File '/[snip]/jupyterlab/packages/coreutils/src/plugin-schema.json' is not listed within the file list of project ''. Projects must list all files or use an 'include' pattern.
error Command failed with exit code 4.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Not sure what is going on here.

**Comment by jasongrout** [comment]
Also with this config, it seems that one package's docs don't link to other packages (for example if they import and use definitions from another package, I would love if their docs would link to the definitions in the other package). I'm not sure if this is a change, or if it's broken in our current docs anyway.

**Comment by jasongrout** [comment]
> Also with this config, it seems that one package's docs don't link to other packages (for example if they import and use definitions from another package, I would love if their docs would link to the definitions in the other package). I'm not sure if this is a change, or if it's broken in our current docs anyway.

Looks like this is also a problem in the current docs, so no change here on that.

**Comment by jasongrout** [comment]
> For now, I'm skipping building docs for coreutils.

I figured out a way around the problem. It looks like it is a bug upstream in either typedoc or typescript, dealing with the composite build flag and specifying json files to be included as modules.

**Comment by jasongrout** [comment]
Okay, @blink1073 - ready for review again.

**Pull request merged**
