### PR TITLE
Allow Lumino 1.x version for rendermime-interfaces

### LINKED ISSUE #14617: Fix rendermime-interfaces
I just created an extension for jupyterlab v3 from the cookiecutter. I tried to install it before changing anything, and it failed.
```
yarn run v1.21.1
$ jlpm build:lib && jlpm build:labextension:dev
$ tsc --sourceMap
node_modules/@jupyterlab/rendermime/lib/widgets.d.ts:8:31 - error TS2420: Class 'RenderedCommon' incorrectly implements interface 'IRenderer'.
  The types of 'title.owner.layout' are incompatible between these types.
    Type 'import("/home/carlos/Documents/blockly-widgets/jupyterlab_blockly_widgets/node_modules/@lumino/widgets/types/layout").Layout | null' is not assignable to type 'import("/home/carlos/Documents/blockly-widgets/jupyterlab_blockly_widgets/node_modules/@jupyterlab/rendermime-interfaces/node_modules/@lumino/widgets/types/layout").Layout | null'.
      Type 'import("/home/carlos/Documents/blockly-widgets/jupyterlab_blockly_widgets/node_modules/@lumino/widgets/types/layout").Layout' is not assignable to type 'import("/home/carlos/Documents/blockly-widgets/jupyterlab_blockly_widgets/node_modules/@jupyterlab/rendermime-interfaces/node_modules/@lumino/widgets/types/layout").Layout'.
        Property '[Symbol.iterator]' is missing in type 'import("/home/carlos/Documents/blockly-widgets/jupyterlab_blockly_widgets/node_modules/@lumino/widgets/types/layout").Layout' but required in type 'import("/home/carlos/Documents/blockly-widgets/jupyterlab_blockly_widgets/node_modules/@jupyterlab/rendermime-interfaces/node_modules/@lumino/widgets/types/layout").Layout'.

8 export declare abstract class RenderedCommon extends Widget implements IRenderMime.IRenderer {
                                ~~~~~~~~~~~~~~

  node_modules/@jupyterlab/rendermime-interfaces/node_modules/@lumino/widgets/types/layout.d.ts:83:14
    83     abstract [Symbol.iterator](): IterableIterator<Widget>;
                    ~~~~~~~~~~~~~~~~~
    '[Symbol.iterator]' is declared here.
```

The problem is that we updated the dependencies of `@jupyterlab/rendermime-interfaces` to lumino v2 and released it as a minor version (v3.8.0). When creating a new extension for jupyterlab v3 it installs  `@jupyterlab/rendermime-interfaces` v3.8.0 with lumino v2.

We should bump the version of the packages to 4 or maybe allow both versions of Lumino.

_Originally posted by @hbcarlos in https://github.com/jupyterlab/jupyterlab/issues/14335#issuecomment-1553340328_

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #14617
Related to discussion #14335

## Code changes

Allow Lumino to be v1 or v2 in rendermime-interfaces

## User-facing changes

None

> Developer for 3.x extension should be able to resolve to a consistent set of Lumino packages.

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by fcollonval** [comment]
I prefer going this way as it highlights the interface are compatible and because yanking a package on npm does not exist. You can either deprecate it or unpublish it.

**Comment by jtpio** [comment]
Thanks @fcollonval.

Looks like the CI failure might be related? (maybe just a yarn dedup)

image

**Review by krassowski — APPROVED** [review]
LGTM, thank you!

> I would personally go for `oneOf` rather than `inRange`

**Comment by fcollonval** [comment]
CI failures are not related

> Opened https://github.com/jupyterlab/jupyterlab/issues/14643

**Pull request merged**
