### PR TITLE
Update the update-dependency script to accept regexes and version tags

### PR DESCRIPTION
**Pull request by jasongrout**
Run update-dependency -h for help.

```
Usage: update-dependency [options] <package> [versionspec], versionspec defaults to ^latest

Update dependency versions

Options:

  --regex        Package is a regular expression
  --lerna        Update dependencies in all lerna packages
  --path [path]  Path to package or monorepo to update
  -h, --help     output usage information

Examples
--------

  Update the package 'webpack' to a specific version range:

      update-dependency webpack ^4.0.0

  Update all packages to the latest version, with a caret:

      update-dependency --regex '.*' ^latest

  Update all packages starting with '@jupyterlab/' to the version
  the 'latest' tag currently points to, with a caret range:

      update-dependency --regex '^@jupyterlab/' ^latest
    
  Update all packages starting with '@jupyterlab/' in all lerna
  workspaces and the root package.json to whatever version the
  'next' tag for each package currently points to:

      update-dependency --lerna --regex '^@jupyterlab/' next

```

### CODE REVIEW

**Comment by jasongrout** [comment]
This makes the update-dependency script much more useful to other repos, to update the jupyterlab packages, for example.

**Comment by jasongrout** [comment]
For documentation: I'm often having to fiddle with the yarn.lock file, with something like this:

```
git clean -dfx
yarn install
yarn check
yarn-tools fix-duplicates yarn.lock > a
mv a yarn.lock
git clean -dfx
yarn install
```

**Comment by blink1073** [comment]
Yikes, two `git clean`s in there, and a temporary file?  I was hoping we could make that into a simple script you could run on any target yarn.lock file...

**Comment by blink1073** [comment]
The changes to `update:dependency` look great though, nice use of `commander`!

**Comment by jasongrout** [comment]
> Yikes, two `git clean`s in there, and a temporary file? I was hoping we could make that into a simple script you could run on any target yarn.lock file...

I think we could improve yarn-tools a lot, for example not requiring a temporary file, and exiting with an error code when it detects duplicates so we can use it in automated testing.

**Comment by blink1073** [comment]
Nice, good plan!

**Comment by jasongrout** [comment]
> two `git clean`s in there

I'm not absolutely positive those are both needed. I was playing it safe and nuking it from orbit. 

> Monk: You've got to face facts.
> The city is ruined forever.
> It's a total loss.
> Even if we clean up all the garbage tomorrow, we'll never get the stink out.
> It's like the dining room carpet when the cat makes a a B.M.
> on there.
> I mean, what do you? You don't have any choice really.
> You gotta replace the carpet.
> You gotta get rid of the cat.
> And you can never eat in that dining room again, can you? No, you can't.
> But, I do have a plan.
> I have a plan.
> Mayor: Oh, good.
> 
> Monk: Yes sir.
> It just came to me last night in a vision.
> One, we evacuate the city.
> Every man, woman, and child.
> Mayor: Evacuate?
> Monk: Two.
> We burn it down.
> We just burn it.
> Scorched earth.
> Then, just to be safe, we collect all the ashes.
> And what do we do? We burn the ashes Three.
> We bring everybody back and we start over.
> Think of it.
> Just think of it.
> We rebuild San Francisco.
> From scratch.
> Start fresh.
> Everything clean.
> Everything brand new.
> Gonna have that new city smell.
> Fresh off the lot.
> We can even straighten out Lombard Street while we're at it.

(https://www.springfieldspringfield.co.uk/view_episode_scripts.php?tv-show=monk&episode=s05e02)

**Comment by blink1073** [comment]
Poor Lombard Street...

**Pull request merged**
