### PR TITLE
Finishes refactor/design of launcher

### PR DESCRIPTION
**Pull request by ellisonbg**
After:

screen shot 2017-07-04 at 8 03 32 pm

### CODE REVIEW

**Comment by ellisonbg** [comment]
Fixes #2468 

Still some cleanup to the code side, so not ready for merge.

**Comment by blink1073** [comment]
We aren't handling long kernel names well:

<image src="https://user-images.githubusercontent.com/2096628/27872817-a6126abe-616f-11e7-9f75-ba2e3168784a.png" width=300>

**Comment by ellisonbg** [comment]
There is a tooltip that will show the entire kernel name, so we don't need to show the *full* name in the card, but that definitely needs improvement. Will work with Cameron on it today.

**Comment by ellisonbg** [comment]
Merge and iterate!!!

**Pull request merged**
