### PR TITLE
fixes #6649 and #6698: Various build system regressions

### LINKED ISSUE #6649: Jupyterlab dev watch mode doesn't work
After updated to version 1.0.0a8, jupyterlab launched with the command
```
jupyter lab --dev-mode --watch
```
does not work as expected. After each source file change, the system rebuilds, but refreshing the browser doesn't update the app.

My system is:
OS: Ubuntu 18.04
Browser: Firefox 67, Chrome 75
jupyterlab-server: 1.0.0rc0

### LINKED ISSUE #6698: Various minor issues with the build system
I've run into a bunch of issues over the last few months with the build system. I don't mind digging into it and trying to come up with fixes, but first I want to see if the issues I'm having are me problems (ie issues with my own config/env) or everyone problems.

General build system problems:

1. When opening sources in Chromium's devtools, I now only get compliled `.js` files instead of being able to see/debug the actual `.ts` files. I used to just get the `.ts` files without having to do anything special.

2. `jlpm run clean` doesn't fully clean up the existing build. There's been a number of times when I pulled updates from master and my build broke, and the only solution was to completely nuke my repo and start from a new clone; `jlpm run clean` was not sufficient.

Problems with the `--dev-mode --watch` build:

3. The `watch` build polls waaay too often, ends up consuming 100% of a cpu core at all times.

4. `watch` rebuilds files in response to changes, but somehow those rebuilt files aren't visible to my browser until I actually close and restart it; reloading the browser is not sufficient. This started happening sometime in the last few weeks, and is described more in #6649.

I already have fixes for `1)` and `3)`, but like I said, before I make a PR I want to see if anyone else is having these problems.

**Desktop:**

- OS: Mac 10.14.4
- Browser: Chromium 74
- JupyterLab: HEAD

### PR DESCRIPTION
**Pull request by telamonian**
## References

#6649, #6698

## Code changes

- Fixed #6649, in which the `--watch` build broke. This came down to changes in how the "linkedPackages" field in `dev_mode/package.json` is getting populated. I fixed this by adding a more complete "watchedPackages" field to `package.json`.

- Added `poll: 333` to `watchOptions` in `jupyerlab/staging/webpack.config.js` and `dev_mode/webpack.config.js`. This fixes the issue with the `--watch` build polling too aggressively and consuming excessive CPU resources when idle.

- Added `"sourceMap": true` to `"compilerOptions"` in `tsconfigbase.json`. As per the [Webpack docs here](https://webpack.js.org/guides/typescript/#source-maps), this is needed to get sourcemaps that point to the actual `.ts` files, instead of just the compiled `.js` files.

- Following the examples in those [same Webpack docs](), I switched from `devtool: 'source-map'` -> `devtool: 'inline-source-map'` for the dev builds. Not sure if this makes any difference to anything (the source maps look the same either way), but it *does* seem to shave a couple of seconds off of rebuilds.

- Fixed the `jlpm run build:dev:prod` command: this command eventually calls `cd dev_mode && jlpm run build:prod`, which in turn calls:

    ```bash
    node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js --config webpack.prod.config.js
    ```

    This was failing for me since all of my npm modules get installed to `root/node_modules`, whereas `root/dev_mode/node_modules` is for me mostly an empty folder. I fixed this by changing the `webpack.js` path to `../node_modules/webpack/bin/webpack.js`.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by telamonian** [comment]
This now includes a fix for the currently broken `--watch` build (see #6649), but it needs a bit of cleanup before it's ready to merge.

**Comment by jasongrout** [comment]
> This now includes a fix for the currently broken `--watch` build (see #6649), but it needs a bit of cleanup before it's ready to merge.

Thanks! Adding "work in progress" label, then. Please remove when this is ready for review.

**Comment by blink1073** [comment]
I'd like to test watch mode with an extension before merging.  This is an excellent PR though, thanks @telamonian!

**Comment by telamonian** [comment]
`webpack.config.js` was getting crowded, so I moved the custom Webpack plugin definitions to `buildutils/webpack-plugins.ts`. This then caused an issue in the release build (eg `jlpm run build:core`), since it only sees the published version of `@jupyterlab/buildutils` and cannot pick up my changes. As a temporary workaround, I added the plugin definitions directly into `jupyterlab/staging/webpack.config.js`. These can be removed the next time `@jupyterlab/buildutils` is published after this PR.

This PR is done on my end. In the near future there should probably be a conversation about exactly which files should be watched, and how that list changes in the dev vs release builds, but that should probably wait for a future (ie post-1.0.0) PR.

> I'd like to test watch mode with an extension before merging. This is an excellent PR though, thanks @telamonian!

@blink1073 I was actually just about to do that! I'll let you know how it goes.

**Comment by telamonian** [comment]
Even after digging into it, the current behavior of `jupyter lab --watch` w.r.t. linked packages is a bit opaque. @blink1073 Do you think you could walk me through the intended behavior?

**Comment by blink1073** [comment]
The original behavior was that linked packages end up in the linked package metadata in staging/package.json.  The watch script looked for changes in the source folder on disk and copied them to staging/node_modules so it would be picked up by webpack.

**Comment by telamonian** [comment]
Okay, the part I wasn't quite getting before is that the linked packages get added to `${JUPYTERLAB_DIR}/staging/package.json`, not to `<my-repo>/staging/package.json`. I think it's starting to make sense.

**Comment by telamonian** [comment]
I fixed the behavior of the `jupyter lab --watch` command by adding some stuff in `jupyterlab/commands.py` to take care of building the "watchedPackages" field. Currently, if you make changes to a linked (typescipt) package's source files and then rebuild it, `jupyter lab --watch` will correctly pick up those changes. According to the [docs](https://jupyterlab.readthedocs.io/en/latest/developer/extension_dev.html#extension-authoring), this matches the old behavior.

That should wrap things up for this PR, but I still have many questions:

- Is it within the realm of feasibility to get Webpack to pick up on changes to the `*.ts` sources in linked packages?

- In the dev build, how are we configuring Webpack such that it is able to pick up on changes to the `*.ts` sources in the core packages. This seems a little mysterious, especially since we're not using a `ts` loader in `webpack.config.js`.

- As far as I can tell, in the release build "linkedPackages" and "watchedPackages" will always be the same. In the dev build, while "linkedPackages" and "watchedPackages" can be different, it looks like "linkedPackages" was never being used for anything other than determining the ignore list in watch. Given this, would it be safe/reasonable to get rid of "watchedPackages" and just make "linkedPackages" more inclusive for dev builds?

**Comment by blink1073** [comment]
- I think we'd need have imported the .ts files directly in our index for that to work
- We are simultaneously running a tsc watch script on the metapackage, which in turn builds packages that have changed
- Yeah, I think we can collapse linkedPackages and watchedPackages.  We had changed it so that we didn't directly depend on all of the core packages so it was easier to swap them out, but including them in the linkedPackage metadata seems fine.

**Comment by telamonian** [comment]
I rolled "watchedPackages" into "linkedPackages" and then reconfirmed that the `jupyter lab --watch` and `jupyter lab --dev-mode --watch` builds were still working correctly. Everything seems good to go.

> We are simultaneously running a tsc watch script on the metapackage, which in turn builds packages that have changed

In that case, what's stopping us from using that same tsc watch script on each of the linked packages?

**Comment by telamonian** [comment]
Uggggggh, and now the CI is breaking. I suspect it's to do with #6716

**Comment by blink1073** [comment]
@telamonian, more generally, we could run `jlpm run watch` on any linked packages that have a watch script.  That would be pretty cool.

**Comment by telamonian** [comment]
Yeah, I was thinking along those lines too. Taking advantage of what's already set up in the extension's `package.json` would be nice. 

The only downside I can think is that you'd end up with `n` separate `node` processes, with each of them polling. Though as long as your linked extensions don't have too many files it should probably be okay?

**Comment by blink1073** [comment]
I like your idea of targeting Typescript better, then it would be a single build watch.  I think we should save that part for later work though.

**Comment by blink1073** [comment]
I'm going to make another RC with this so we can make sure that the webpack from dev_mode works in app mode as well

**Pull request merged**
