### PR TITLE
[WIP] Make it easier for context menu events to find the relevant widget

### PR DESCRIPTION
**Pull request by jasongrout**
## References

This is stemming from work done in #6060.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Awesome, thanks for working on this @jasongrout.

**Comment by ian-r-rose** [comment]
@jasongrout I was taking a look at #6008, and to do it well would involve some of the ideas you are exploring here. Would you like to (a) move this to 1.0, or (b) bump #6008 or reduce its scope?

**Comment by jasongrout** [comment]
> Would you like to (a) move this to 1.0, or (b) bump #6008 or reduce its scope?

I'd like to do this for 1.0, but didn't consider it a high priority or a blocker. It could be an big pattern change for commands that want to be added to context menus though, so perhaps it should be a 1.0 thing. (For example, notebook actions added to the right click menu probably should use something like this so they work if they were added to the notebook tab as well). What do you think?

**Comment by ian-r-rose** [comment]
> I'd like to do this for 1.0, but didn't consider it a high priority or a blocker. It could be an big pattern change for commands that want to be added to context menus though, so perhaps it should be a 1.0 thing. (For example, notebook actions added to the right click menu probably should use something like this so they work if they were added to the notebook tab as well). What do you think?

I think it would be okay for the tab context menu items to be more application-level commands, and not include specific notebook-level items (at least, not more than there are already). My main priority for this would be to (1) clean up the existing API a bit, and (2) expose a bit more API to allow extensions to reason about what tab-panel their widgets exist in.

**Comment by telamonian** [comment]
I had a thought. It would probably be feasible to register all of the relevant widgets (maybe as part of setting up the various context menus) and toss them all into a `WeakMap` a la
```
wmap.set(widget.node, widget)
``` 

Given a node that's associated with a `contextmenu` event, you could then walk up the DOM until you find a node/widget that's in the map. If `shell` (or any other application-wide singleton) owns the map, you could potentially have just one simple universal function for finding widgets (w.r.t. `contextmenu` events, at least).

@jasongrout If that implementation sounds reasonable to you, would it be alright if I took a crack at it and added the commits to this PR?

**Comment by jweill-aws** [comment]
There hasn't been any activity on this pull request in over a year. As part of an effort to clean up this repository's pull requests, I'm closing this request. If you would still like to merge this code in, please reopen the request and resolve any outstanding merge conflicts. All of the code and comments will remain in place. Thank you for being part of the JupyterLab community!

**Pull request closed without merging**
