### PR TITLE
Switch default notebook windowing mode to 'defer'

### LINKED ISSUE #14455: Default the Notebook Windowing mode to `none` or `defer`?
### Problem

After using the betas and `4.0.0rc0`, the default notebook experience still feels off and sometimes frustrating to work with.

It sometimes feels like a "regression" compared to `3.5.x` or `3.6.x` especially when working with rather small notebooks.

### Proposed Solution

Default `windowingMode` to `none` here:

https://github.com/jupyterlab/jupyterlab/blob/ec07704ef0196e4298692d347c8e32124bc33dfa/packages/notebook-extension/schema/tracker.json#L799-L804

Document how to improve performance by using the other modes (opt-in).

### Additional context

Some of the issues with the default notebook windowing mode that might be related:
- https://github.com/jupyterlab/jupyterlab/issues/13343
- https://github.com/jupyterlab/jupyterlab/issues/14379

This is based on the observation that most notebooks will probably not benefit from the advanced notebook rendering mode. But will instead inherit the issues mentioned above.

This study on millions of notebooks shows the distribution of the number of code cells in a notebook: 

image

https://blog.jetbrains.com/datalore/2020/12/17/we-downloaded-10-000-000-jupyter-notebooks-from-github-this-is-what-we-learned/

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #14455 
Fixes https://github.com/jupyterlab/jupyterlab/issues/14453

## Code changes

Switch default notebook rendering mode to `defer`
- [x] Fix add cell button position - change style rules for non-windowing mode.

## User-facing changes

Avoid poorly handle side-effects of full windowing; namely scrolling experience and iframe state.

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

**Comment by fcollonval** [comment]
bot please update galata snapshots

**Review by afshin — APPROVED** [review]
Thank you!

**Comment by fcollonval** [comment]
> Test failures are due to flakyness

**Pull request merged**
