### PR TITLE
Backport PR #15805 on branch 4.0.x (Fix codemirror highlight for Python builtin)

### PR DESCRIPTION
**Pull request by AllanChain**
Backport PR https://github.com/jupyterlab/jupyterlab/pull/15805: Fix codemirror highlight for Python builtin

~~The binary files changed and Git is unable to resolve it. I just checked out new images.~~

**Edit:** It turns out that the snapshots are slightly different between 4.1.x and 4.0.x

### CODE REVIEW

**Comment by AllanChain** [comment]
@meeseeksdev tag bug

**Comment by AllanChain** [comment]
please update galata snapshots

**Comment by AllanChain** [comment]
please update documentation snapshots

**Comment by krassowski** [comment]
Kind of, these two:

```
    [documentation] › test/documentation/customization.test.ts:17:7 › Default › should use default layout 
    [documentation] › test/documentation/internationalization.test.ts:14:7 › Internationalization › Menu 
```

are failing due to a concurrency issue in test execution which was not fixed on 4.0.x. I guess we can accept the worse snapshots to get a green tick on 4.0.x as it does not matter that much.

**Review by krassowski — APPROVED** [review]
Thank you so much @AllanChain!

**Pull request merged**
