### PR TITLE
Benchmark Notebook Loads

### PR DESCRIPTION
**Pull request by saulshanabrook**
This is a work in progress PR to add the ability to benchmark how long it takes to load and switch between different notebooks in different browsers.

TODO:

- [x] Use [playwright](https://github.com/microsoft/playwright) (cross browser puppeteer) to run headless tests in different browsers
- [x] Add test to load different size notebooks
- [x]  Generate benchmark data, using browser measurement API, to record how long it takes to switch
- [x] add viz of benchmarks
- [x] document script

## References

https://github.com/jupyterlab/jupyterlab/issues/4292

Depends on https://github.com/jupyterlab/jupyterlab/pull/8037

## Code changes

Adds new benchmark package.

## User-facing changes

None, adds some internal docs on how to run benchmarks.

## Backwards-incompatible changes

None.

### CODE REVIEW

**Comment by saulshanabrook** [comment]
I'm starting to get some results!

**Comment by saulshanabrook** [comment]
I love being able to use [Voyager](http://vega.github.io/voyager/) for this kind of thing!

Who wants to write code when you can use drag and drop...

Screen Shot 2020-03-10 at 3 06 49 PM

**Comment by saulshanabrook** [comment]
I am increasing the count here to 10k on chrome to see how that performs. One thing I noticed is that the chrome window is too small, so I need to figure out a way to increase the size to make sure that doesn't cut down the rendering time in some way:

Screen Shot 2020-03-10 at 3 16 16 PM

**Comment by saulshanabrook** [comment]
I added a vega lite file here, which is kinda a nice way to analyze this data without having to install any other libraries!

visualization

Both seem roughly linear.

**Comment by saulshanabrook** [comment]
Screen Shot 2020-03-10 at 3 47 57 PM

**Comment by jasongrout** [comment]
That's nice to quantify the difference between chrome and firefox people have been subjectively commenting on.

**Comment by saulshanabrook** [comment]
My next step here is to test this with plotly outputs, because they have tons of dom nodes per output.

However, to do that I need to get plotly (and ipywidgets) running alongside core so I can tweak it to see how it affects benchmarks. 

I really don't wanna do the whole `add:sibling` thing so I am thinking about adding some CLI flags to let you include other extensions when building the dev bundle. Anyways, that work might have to mess with more of core, so I am thinking this might be a good place to call this PR "done" and merge it in, barring any objections (and as long as it doesn't break anything. Hopefully shouldn't since it adds a new package that isn't referenced anywhere).

**Comment by jasongrout** [comment]
> I really don't wanna do the whole `add:sibling` thing so I am thinking about adding some CLI flags to let you include other extensions when building the dev bundle.

I think a good crowd of people would love to have this capability!

**Comment by saulshanabrook** [comment]
I wasn't awaiting on some promises (thanks `tslint` in CI!) and when I re-ran I got slightly worse numbers (probably very dependent on machine though. I have the newest macbook pro, so would *definitely* be good to run this on lower end devices as well)

Screen Shot 2020-03-12 at 3 14 08 PM

**Comment by saulshanabrook** [comment]
I am merging in https://github.com/jupyterlab/jupyterlab/pull/8037 so I can experiment with using plotly.

**Comment by saulshanabrook** [comment]
I have this working now with plotly plots. It builds 4 plotly plots per notebook, each with 10 * n number of points in there. So what this says, is that on the biggest notebook, 4 plots each with 100k points, it takes between 400 and 600ms to switch to it.

Screen Shot 2020-03-23 at 1 59 19 PM

**Comment by saulshanabrook** [comment]
I need to improve the labeling on this graph, but I wanted to post an updated version because I am now waiting properly for plotly to finish rendering for the timing. 

The `n` for `many-plotly` divided by 100 is the number of plotly outputs on the page. Each with a constant (4) number of points. 

The `n` for `big-plotly` times 10 is the number of points in each plotly graph, with four on the page.

Screen Shot 2020-03-24 at 10 23 41 AM

**Comment by saulshanabrook** [comment]
This is saying that with four plotly plots, each with 10k points, it takes between 300 and 600ms to render.
Screen Shot 2020-03-24 at 11 33 38 AM

**Comment by saulshanabrook** [comment]
Updated the labels:

Screen Shot 2020-03-24 at 12 31 02 PM

**Comment by saulshanabrook** [comment]
Added ability to run custom tests: https://github.com/jupyterlab/jupyterlab/pull/8020/commits/0f7ca3873d4ed0f405fb43560887637b9fab0d83#diff-cd14ea37e0651aa89d918de3c3259c4e

**Comment by saulshanabrook** [comment]
I would like to add some more options to this benchmark suite, but it's already a pretty big PR as is. Thoughts on merging this? AFAIK it shouldn't affect any existing dev or user behavior, it just adds a new package with benchmarking tools in it.

**Comment by blink1073** [comment]
Happy to merge, mind a rebase and squash?

**Comment by echarles** [comment]
"You can not scale what you can not measure". I love this PR.

**Comment by saulshanabrook** [comment]
Thanks all!

> mind a rebase and squash?

Sounds good to me. Just updated the README, this should be good to go if the tests pass.

**Comment by telamonian** [comment]
@saulshanabrook Would you mind picking out and dumping a few of the most informative graphs into an appropriate dir on the team compass? That'll make the data you've collected easier to reference in the future

**Comment by saulshanabrook** [comment]
@telamonian I made a Vega Lite spec and a CSV file. I checked in the Vega Lite spec, but not the CSV file.

I included a screenshot of the graph in the README now.

**Comment by saulshanabrook** [comment]
Merging this in, we can iterate further in the future!

**Comment by saulshanabrook** [comment]
I added partial support for a fixed data table example. The next steps here are to:

1. Manually verify that linking in the local fixed data table extension works and can render CSVs in notebooks
2. Add an example to test this fixed data table benchmark data like the example notebook in the package. Vary the number of cells and keep the length of the CSV the same
3. Add support for testing initial load times as well as switching between notebooks. Start on a blank JupyterLab and open the document and see how long it takes.

**Comment by blink1073** [comment]
> I added partial support for a fixed data table example. The next steps here are to

Does this mean the DOM layout for the notebook itself, or do you mean table outputs?

**Comment by saulshanabrook** [comment]
> Does this mean the DOM layout for the notebook itself, or do you mean table outputs?


Ah good question! For rendering CSV outputs in a datagrid. We have a client who says notebook loading is very slow because they have a bunch of outputs using https://github.com/schrodinger/fixed-data-table-2 that render slowly. Since I am not sure about the performance characteristics of that library, I thought it safest to just test it directly, rendering a bunch of outputs with it and seeing how slow it is, and then to see if the virtualization will be able to help.

**Comment by blink1073** [comment]
Gotcha, thanks for clarifying!

**Comment by saulshanabrook** [comment]
I have added some benchmarks for initial notebook loading as well. 

I want to clean up the graphics a bit, it's still a little confusing to look at.

However, here is the latest version running locally, with the Fixed Data Table mime renderer:


visualization-1



You can see it gets bad quickly. A notebook with 15 cells, each with a 50 x 50k output, takes 6 seconds to open.

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/cripplingly-slow-ui-am-i-the-only-one/5351/6

**Comment by saulshanabrook** [comment]
I am happy now with how the graphs look, I added a mean average line as well as showing each individual point:

Screen Shot 2020-07-24 at 4 01 12 PM

**Comment by echarles** [comment]
Thx a lot @saulshanabrook for this effort. The start vs swtich, the mean average line with  the independent point, make the graph readable and usable.

I will pull this PR and run it locally by tomorrow. I hope to post my graph so we can merge this and iterate.

**Comment by echarles** [comment]
This is result for `longOutput` and `manyOutputs` benchmark on my 2 years-old macbookpro laptop (2,6 GHz Intel 8 Cores i7 16 GB). This is inline with results posted before.

visualization

I will now run the plotly and fixed-data-table benchmark.

**Comment by echarles** [comment]
@saulshanabrook A few thoughts for later iteration

- Any mean to add an option to run in [Headless mode](https://en.wikipedia.org/wiki/Headless_browser) (I read on [playwright](https://github.com/microsoft/playwright) that "`Headless execution is supported for all the browsers on all platforms`")
- Would be good to have a canonical metric so folks can add their result with the version and platform details. We could then roughly compare and see the difference across them.

**Comment by echarles** [comment]
@saulshanabrook  Quick note: After benchmark has been run, the script has launched jlab in normal mode and default browser was opened. I have clicked on the `analysis.vl.json` which gave an error. Then I stopped and launched again jlab. At that point, the graph was shown correctly. Just a detail and maybe related to my env, but worth mentioning it.

**Comment by echarles** [comment]
plotly benmark on my env

visualization (1)

**Comment by blink1073** [comment]
Note: I just merged #8584 which should have an effect on notebook performance.

**Comment by echarles** [comment]
Thx @blink1073 I will take time next week to go deeper into the various params on which we can play to get better performance. This PR will be key to assess with metrics the progress.

**Comment by echarles** [comment]
React Fixed Data Tables benchmark on my env

visualization

**Comment by blink1073** [comment]
My overall point was that it would be good to rebase this PR and post new screenshot so we see the delta :smile:

**Comment by echarles** [comment]
Just merged it. This PR does not contain data (just the mechanics to create them).

I got your point @blink1073. I will open another PR with comparison aggregated metrics (see https://github.com/jupyterlab/jupyterlab/pull/8020#issuecomment-663967281).

We need indeed a way to track how the performance evolve in function of the code change (also to avoid regression).

This is why at some point we could have the benchmark included in the CI.

**Comment by blink1073** [comment]
Sounds good, thanks @echarles

**Comment by mlucool** [comment]
For plotly, the mode matters greatly for performance. Do you know which mode was being used above?
```
import plotly.io as pio
# pio.renderers.default = 'iframe'
# pio.renderers.default = 'plotly_mimetype+notebook'
```

**Comment by echarles** [comment]
The notebook code used to run e.g. `manyPlotly` is https://github.com/jupyterlab/jupyterlab/pull/8020/files#diff-4e6b7c0253d13338f6c42ddb93f7972aR9-R48

I think no specific plotly renderer option has been set. We can easily add more benchmark for this.

**Comment by echarles** [comment]
Link does not seem to show the code block, so pasting it here

```json
makeNotebook([
      {
        cell_type: 'code',
        execution_count: 1,
        metadata: {},
        outputs: [],
        source: [
          'import plotly.graph_objects as go\n',
          `data = list(range(${n}))\n`,
          `fig = go.Figure(data=go.Scatter(y=data, x=data))`
        ]
      },
      ...Array.from({ length: n + 1 }, () => ({
        cell_type: 'code',
        execution_count: 1,
        metadata: {},
        outputs: [
          {
            data: {
              'application/vnd.plotly.v1+json': {
                config: {
                  plotlyServerURL: 'https://plot.ly'
                },
                data: [
                  (points => ({
                    type: 'scatter',
                    x: points,
                    y: points
                  }))(Array.from({ length: 4 }, (_, i) => i))
                ],
                layout: {
                  autosize: true
                }
              }
            },
            metadata: {},
            output_type: 'display_data'
          }
        ],
        source: ['fig']
```

**Comment by saulshanabrook** [comment]
> Any mean to add an option to run in Headless mode (I read on playwright that "Headless execution is supported for all the browsers on all platforms")

I think I found some of the performance different in headless mode? I was worried it was optimizing away some things and so might not be representative. But regardless would be good to try it!

**Pull request merged**
