### PR TITLE
Custom kernel message serializer

### PR DESCRIPTION
**Pull request by DonJayamanne**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/15198

## Code changes

Exposes the message serializer in the ISettings, allowing one to customize how messages are serialized/deserialized based on the server (settings).

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by krassowski — APPROVED** [review]
Thanks @DonJayamanne, this looks good to me!

**Comment by DonJayamanne** [comment]
@krassowski 
Should I mark this as ready for review, or is there something else we need?
I do not think we need tests for this change, and the docs are generated from the ts code.

**Comment by krassowski** [comment]
Addding a unit test ensuring that the serializer can actually be changed can help catch regression if this function gets rewritten (all it takes to break it is to move `...options` one line up) so it could benefit you on the future. Other than that no follow up tasks here.

**Review by fcollonval — APPROVED** [review]
Thanks @DonJayamanne 

I agree that it will be nice to test providing custom de/serializers in a test.

**Pull request merged**
