### PR TITLE
Split buildutils into buildutils and builder

### LINKED ISSUE #8857: Separate out a new builder package
### Problem
We are starting to add a lot of dependencies to `buildutils` that aren't needed for simple utilities like `update:dependency`.  

### Proposed Solution
Create a new top-level `builder` package (`@jupyterlab/builder`) that has the `webpack` config and the `build-extension` script.
 

### Additional context
Also need to move the `source-map-loader` and `html-loader` out of this package and back into `dev_mode`.

### PR DESCRIPTION
**Pull request by jasongrout**
## References

Fixes #8857

## Code changes

The new builder package is used to build extensions. The buildutils now contains repo-specific utilities.

## User-facing changes
Cleaner package for building and less dependencies consumed for people wanting to use our build utilities like `update:dependency`.

## Backwards-incompatible changes
Moves `build` out of `buildutils` and into `builder`.

### CODE REVIEW

**Comment by jasongrout** [comment]
@blink1073 - here is at least a start at splitting off the builder package. Feel free to take over if you'd like.

**Comment by blink1073** [comment]
Thanks, picking this up now

**Comment by blink1073** [comment]
Usage will fail until we cut another release because `@jupyterlab/builder` is not in `jupyterlab/staging/package.json` dependencies.

**Comment by blink1073** [comment]
I released alpha 12

**Comment by jasongrout** [comment]
Thanks!

**Pull request merged**
