### PR TITLE
Move flaky tests to a separate workflow on CI

### PR DESCRIPTION
**Pull request by jtpio**
## References

The long term motivation is to be able to reach a full green CI some time soon.

For now, this change moves some of the known flaky tests to their own workflow, so they can easily be restarted without re-running everything else. The current list includes:

- `js-services`
- `js-apputils` 

image

## Code changes

CI

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
The `js-services` also seem to be timing out locally, so hopefully it should be possible to fix them.

**Comment by jtpio** [comment]
> The `js-services` tests also seem to be timing out locally, so hopefully it should be possible to fix them.

This seems to be reproducible locally when running the `ikernel.spec.ts` tests:

```bash
jlpm run test test/kernel/ikernel.spec.ts 
```

**Comment by jtpio** [comment]
It looks like `js-services` tests might have started timing out in https://github.com/jupyterlab/jupyterlab/pull/9484

image

While they were still passing in the previous PR https://github.com/jupyterlab/jupyterlab/pull/9483

image

Locally, some hints that it might be related to timeouts on kernel restarts:

image

**Comment by jtpio** [comment]
Testing without `ikernel.spec.ts` locally seems to pass:

image

It looks like the issue is with the restart and shutdown logic.

**Comment by jtpio** [comment]
Looks like the services tests are fixed by https://github.com/jupyterlab/jupyterlab/pull/9806.

Rebasing to only keep js-apputils in the flaky group for now.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Pull request merged**
