### PR TITLE
Display the version in the extension manager

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/8686

This help give users better information about their extensions so they don't have to open a new terminal to know the versions.

## Code changes

Update the extension manager widget to display the `installed_version` and `latest_version`.

## User-facing changes

**Before**

image

**After**

image

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
The alternative place to put this would be an "about" button which would allow us to show more version information later. In particular there are often frontend and backend versions (and in case of extensions like lsp multiple frontend versions). Also, the right top-corner could be used for transient timing info as in https://github.com/jupyterlab/jupyterlab/issues/13402#issue-1442541890.

**Comment by jtpio** [comment]
For reference VS Code opens a popup on hover which contains the version and other details:

image

**Comment by jtpio** [comment]
bot please update documentation snapshots

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio

**Comment by jtpio** [comment]
Thanks @krassowski and @fcollonval for the reviews.

@krassowski I'll open a follow-up issue to discuss creating an "About" button. It would be fine moving the version to that about dialog later if needed.

**Comment by jtpio** [comment]
> I'll open a follow-up issue to discuss creating an "About" button.

Opened https://github.com/jupyterlab/jupyterlab/issues/14098

**Pull request merged**
