### PR TITLE
Scroll to cell by ID based on hash fragment

### PR DESCRIPTION
**Pull request by krassowski**
## References

Reference implementation for https://github.com/jupyter/nbformat/issues/317.

Fixes a 4.0-only regression in jumping to headings which had CSS-escapeable characters.

Closes https://github.com/jupyterlab/jupyterlab/issues/12928.

## Code changes

- `setFragment` is now always called for notebook on route change, whether in full windowing mode or not
- removes `CSS.escape` which was no longer correct and breaking jumping to headings with characters that would be escaped (it was useful back then when we were using `querySelector`, see #11517, but not since we migrated to manual searching for heading in #12554)

## User-facing changes

- Links to `#cell-id=my-cell-id` will scroll to the cell with such an id.

## Backwards-incompatible changes

Links to headings starting with `cell id=` will now need to be updated with `heading=` prefix (I don't think there are many headings like that used in the wild).

### CODE REVIEW

**Comment by krassowski** [comment]
please update documentation snapshots

**Comment by krassowski** [comment]
please update documentation snapshots

**Comment by krassowski** [comment]
please update documentation snapshots

**Comment by krassowski** [comment]
Good point. Documentation added, ready for another round of review/merge.

**Review by fcollonval — COMMENTED** [review]
Thanks a lot @krassowski 

The cell properties side panel snapshot is not sized correctly when updated.

> Lately we are having again side panel sizing flakiness :cry: I think this is linked to https://github.com/jupyterlab/jupyterlab/pull/13037 that changes the workspace restoration logic.

**Comment by krassowski** [comment]
please update documentation snapshots

**Comment by fcollonval** [comment]
Kicking the CI

**Comment by krassowski** [comment]
I did not find a quick way to improve that one, so just reverted the assets. The visual tests are passing now but `js-services` are failing - looks unrelated at first glance?

**Comment by fcollonval** [comment]
> looks unrelated at first glance?

I confirm this is not related.

Thanks Mike - merging now.

**Pull request merged**
