### PR TITLE
Add peerDependencies to the shared packages

### LINKED ISSUE #9724: Recommend using peer dependencies to signify JupyterLab compatibility?
We've historically had issues with extensions not being able to convey to the build system what versions of JupyterLab they are compatible with. This is particularly an issue with, for example, custom Jupyter widgets (which don't depend directly on jlab, but only on the jlab extension), and javascript extensions (which also don't depend directly on JupyterLab packages).

I think we should explore using peer dependencies to signify what version of JupyterLab an extension is compatible with, even if it doesn't directly require a JupyterLab package. For example, we could have a peer dependency (or optional dependency?) on some core JupyterLab package, which would at least give errors when building with the wrong version of jlab. The nice thing is that using peer dependencies will not install a separate copy of the jlab package accidentally, avoiding silent problems that cause errors later, i.e., using peer dependencies won't cause a duplicate dependency problem. (Right now we use yarn resolutions *and* a yarn deduplication to work around these issues, but perhaps it is better to recommend using peer dependencies to solve the same deduplication problem.)

We may need to have jupyterlab packages both in peer dependencies and in dev dependencies - not sure.

I think the react community uses similar strategies to for specifying the react version without risk of getting two copies of react.

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes #9724 

Start experimenting with `peerDependencies` added to the shared package configuration by default

If we continue with this we'll want to:

- [x] Add a test extension that specifies `peerDependencies` only (or both `dependencies` and `peerDependencies`)
- [ ] Document this (and recommend `peerDependencies`) 

## Code changes

Add both `dependencies` and `peerDependencies` to the shared packages.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
> Start experimenting with peerDependencies added to the shared package configuration by default

Maybe this could also be experimented with using a custom webpack config in a third-party extension? (haven't checked yet)

https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html?#custom-webpack-config

**Comment by jtpio** [comment]
Checking locally with a new prebuilt extension bootstrapped with the cookiecutter:

```bash
cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts
cd myextension

# activate the jupyterlab dev environment
conda activate jupyterlab

# install the extension
python -m pip install -e .
jupyter labextension develop . --overwrite

# link the builder package in the jupyterlab repo
cd /path/to/jupyterlab/builder
jlpm link

# link to the builder in the extension
jlpm link @jupyterlab/builder

# add lodash to the peerDependencies

# rebuild the extension
jlpm run build

# check `lodash` is in the `shared` scope
cat myextension/labextension/build_log.json | grep lodash -C 10

# start jupyterlab with extensions in dev mode to check the extension is correctly activated
jupyter lab --extensions-in-dev-mode
```

**Comment by goanpeca** [comment]
Is this PR still valid @jtpio ?

Thanks! :)

**Comment by jtpio** [comment]
Yes, but needs a bit more work and thinking.

We could add it to the 4.0 milestone, and maybe move it to 3.2 if there happens to be one.

**Comment by goanpeca** [comment]
>Yes, but needs a bit more work and thinking.

Sounds good! thanks, any discussion that should be carried on the dev meeting, or more on your side :) ?


>We could add it to the 4.0 milestone, and maybe move it to 3.2 if there happens to be one.

Sounds good! thanks a lot

**Comment by jweill-aws** [comment]
There hasn't been any activity on this pull request in over a year. As part of an effort to clean up this repository's pull requests, I'm closing this request. If you would still like to merge this code in, please reopen the request and resolve any outstanding merge conflicts. All of the code and comments will remain in place. Thank you for being part of the JupyterLab community!

**Pull request closed without merging**
