### PR TITLE
Remove unused `IMainMenu` dependency

### PR DESCRIPTION
**Pull request by jtpio**
## References

This (optional) dependency appears to be unused in the `docmanager-extension`.

Follow-up to https://github.com/jupyterlab/jupyterlab/pull/10254

## Code changes

Remove unused dependency.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Hitting this one locally: 

image

Could be that there was an implicit assumption on having the `IMainMenu` used as a dependency in the docmanager extension?

**Comment by fcollonval** [comment]
I'll have a look.

**Comment by fcollonval** [comment]
The bug was due to `SettingsRegistry.pluginChanged` signal being connected before the variables where initialized. This is now corrected.

i took the chance to clean the other packages too.

**Review by jasongrout — APPROVED** [review]
Nice!

**Comment by jtpio** [comment]
Thanks @fcollonval!

**Comment by jasongrout** [comment]
@jtpio - this PR is still draft. Was there more you wanted to do with it before merging?

**Comment by jasongrout** [comment]
>  [@jtpio](/jtpio) [jtpio](/jtpio) marked this pull request as ready for review [7 minutes ago](#event-4853560246)

Oh, sorry, looks my UI hadn't updated yet. Thanks again!

**Pull request merged**
