### PR TITLE
Don't sort context menu items by selector

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Follow-up of https://github.com/jupyterlab/lumino/pull/203 and https://github.com/jupyterlab/lumino/pull/206

- [x] Wait for new release of @lumino/widgets
- [x] Correct context menu items order to put _Paste_ item after _Copy_ and _Cut_ items
- [x] Place the _New..._ items ~~on top of the context menu~~ at the bottom (they will be at the same position as before)
- [x] Remove _New Markdown file_
- [x] Add _New Notebook_ items
- [x] Fix context menu changes due to the new ordering algorithm (in particular ignoring the selector)

The two later tasks will make the context menu more meaningful for JupyterLab as the primary document type is the notebooks and those documents cannot be empty plain text files. The markdown can be added by the `New file` entry while renaming the extension.

> I let the new items at the bottom because looking quickly on various applications, _new_ items are not displayed usually when selecting a folder or a file. They are appearing only when clicking an empty space in the file browser. This goes in the direction of _context_ menu as _new_ items are not directly applying a change on the selected file/folder.

## Code changes

The context menu items will only be sorted by rank.

## User-facing changes

Items order in the context menu are expected to change.

_context menu on file_ (Before / After)
image

_context menu on folder_ (Before / After)
image

_context menu on empty filebrowser space_ (After)

image

> The consequence of this PR is the `Paste` item that appear on top in the last case (it was on the bottom prior to this PR).

## Backwards-incompatible changes

Yes

### CODE REVIEW

**Comment by blink1073** [comment]
Lumino release [done](https://github.com/jupyterlab/lumino/releases/tag/v2021.7.21)

**Comment by krassowski** [comment]
Nice! I guess we could either:
- make a submenu "New", same as in the top-level File menu which would show all three "File", "Notebook", "Markdown", or
- add `isContextMenu` argument and condition on it when creating the label so that it shows as "New Notebook":

https://github.com/jupyterlab/jupyterlab/blob/7c228f11e08b29dd1523116a271a858a70ba14c4/packages/notebook-extension/src/index.ts#L1218-L1232

**Comment by fcollonval** [comment]
Thanks a lot for the review @krassowski I update the label to display `New Notebook`.

**Review by blink1073 — APPROVED** [review]
LGTM, thank you!

**Review by krassowski — APPROVED** [review]
LGTM.

Small note (no action requested): there is a slight inconsistency in how creating the file enters the edit mode on the listing item but creating the notebook does not. It actually makes sense given that for notebook we need to choose kernel first because "Choose kernel" modal blocks user interactions. Maybe we could have `New notebook` → `IPython`/`Xeus`/`R`/`Julia` and then enter the edit mode immediately, but I am not sure if this would be better.

**Comment by fcollonval** [comment]
> we could have `New notebook` → `IPython`/`Xeus`/`R`/`Julia` and then enter the edit mode immediately, but I am not sure if this would be better.

This may be tricky as the user may have multiple environments and so multiple choices even for a single language.

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.4.x

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.4.x

**Pull request merged**
