### PR TITLE
Fix outputarea package from not detecting updates

### PR DESCRIPTION
**Pull request by MFA-X-AI**
## References
https://github.com/jupyterlab/jupyterlab/issues/15633 https://github.com/jupyterlab/jupyterlab/issues/15004
Changes introduced in https://github.com/jupyterlab/jupyterlab/pull/14911

## Code changes

The code updates the renderer retrieval in the OutputArea widget by directly accessing the renderer from the layout.widgets array. 

## User-facing changes

Output panels are still able to display plots as raised in https://github.com/jupyterlab/jupyterlab/issues/14564#issuecomment-1554097391 while still able to detect ongoing output streams.

https://github.com/jupyterlab/jupyterlab/assets/68586800/433dc5cb-3cf5-4a4f-9159-5def7af7b71b

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
Thank you for working on it! Would you be able to take a look at the unit tests (for example in https://github.com/jupyterlab/jupyterlab/blob/main/packages/outputarea/test/ but possible in other packages too) to see if we a test ensuring correct behaviour could be added easily?

**Comment by MFA-X-AI** [comment]
@krassowski looks like the test runs on a different environment than the browser, I can't seem to replicate the original bug. Currently investigating. 

In the mean time, could you rerun the UI test action again for this PR? Seems that it ran into some of the test errors that you ran [here](https://github.com/jupyterlab/jupyterlab/actions/runs/7529540657/attempts/2?pr=15640), wanted to know if it's because of this change or just flaky tests. 

Thanks!

**Comment by MFA-X-AI** [comment]
@krassowski A few changes:
- the updated code preserved the original way of accessing the renderer by having a fallback on panel, but now additionally checking if the `renderModel` exists on the widget (previously `panel.widgets[0]` was always True, even if if it didn't have a renderModel). Although the previous commit didn't seem to break anything, seeing how the outputarea is used everywhere, it's better to be safe. 😅 
- We managed to reproduce the error on the unit test. 🥳 
Turns that it happens in `SimplifiedOutputArea`, as both our extension and the kernel extension example was using it.
Narrowing that down, the new unittest can now catch the mismatch between what is held by the model and what is rendered by the widget.

Here's the output from the pre-fixed outputarea.
```
 outputarea/widget › OutputArea › .execute() › should continuously display delayed outputs

    expect(received).toBe(expected) // Object.is equality

    - Expected  - 1
    + Received  + 3

    - Hello Jupyter! 0
    + Hello Jupyter! 0
    + Hello Jupyter! 1
    + Hello Jupyter! 2
      ↵

      458 |         ].join('\n');
      459 |         await SimplifiedOutputArea.execute(code, widget0, ipySessionContext);
    > 460 |         expect(model0.toJSON()[0].text).toBe(widget0.node.textContent)
          |                                         ^
      461 |       });
      462 |     });
      463 |

      at Object.<anonymous> (test/widget.spec.ts:460:41)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 29 passed, 30 total
Snapshots:   0 total
Time:        47.987 s
Ran all test suites related to changed files.
```

And here with the update:
```
Test Suites: 1 passed, 1 total
Tests:       30 passed, 30 total
Snapshots:   0 total
Time:        47.258 s, estimated 178 s
Ran all test suites related to changed files.
```

Hopefully this is good enough to include in the next release. Thanks!

**Review by krassowski — APPROVED** [review]
Thank you @MFA-X-AI!

As discussed on today's JupyterLab call, I will merge it and release in 4.1.0b1. It looks like it could be backported to 4.0.x - I will open a backport but wait with merging until we hear more feedback from testing of the new beta. Thanks again!

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.0.x

**Pull request merged**
