### PR TITLE
[WIP] Automated UI testing using Galata

### PR DESCRIPTION
**Pull request by mbektas**
- Adds UI testing support using https://github.com/jupyterlab/galata
- Tests are run as part of CI with `ui-tests` workflow added
- After tests are run, a result report is generated and uploaded. It can be accessed in GitHub Actions page. If any of the tests fail, image diffs and failing call-stack can be inspected from report. Simply download the artifact and open `test/report/index.html` for the interactive report.
- Detailed documentation for adding new UI tests is added in `ui-tests/README.md`
- Helper npm scripts and a shell script added to help local development and testing. Usage described in the documentation as well.

## Test Plan
- [x] General UI Tests:
  - Launch screen, toggling Simple Mode, toggling Dark Theme
  - Open and capture main menu and sub menus
  - Open and capture sidebar tabs
  - Move sidebar panel to right
- [x] Notebook Create
  - Create cells for each cell type (raw, markdown, code)
  - Save and capture notebook
  - Toggle Dark Theme
- [x] Notebook Run
  - Upload notebook and image dependency to JupyterLab
  - Check File Browser list for uploaded files
  - Run notebook and capture notebook panel
  - Check numerical cell output values
- [x] Cell editing
  - Create a notebook with couple of cells
  - Modify notebook using operations in Edit menu (cut, copy, paste, delete, select, deselect, move, split, merge)
- [x] Notebook Toolbar
  - Create a notebook with couple of cells
  - Run actions in notebook toolbar
- [x] Table of Contents
  - Create tags
  - Create a notebook with markdown and code cells
  - Select cells and assign tags
  - Show TOC panel, filter using cell types and tags

Below is the capture from a test run:
jlab-galata

### CODE REVIEW

**Comment by mbektas** [comment]
Tried to test in https://github.com/jupyterlab/jupyterlab/pull/10313 but didn't detect the regression. Appears to be because of build steps I use in `ui-tests.yml`. `jlpm && jlpm build && jupyter lab build` is not enough to rebuild jupyterlab with changes in CSS.

**Comment by jtpio** [comment]
Thanks @mbektas!

> jlpm build && jupyter lab build is not enough

Maybe jupyterlab should be started with the `--dev-mode` option for the ui tests? Or is it already the case?

Also would it be possible to do a rebase, as the diff seems to be showing changes from previously merged PRs. Thanks!

**Comment by mbektas** [comment]
> Maybe jupyterlab should be started with the `--dev-mode` option for the ui tests? Or is it already the case?

Sure, I can use `--dev-mode`.
> Also would it be possible to do a rebase, as the diff seems to be showing changes from previously merged PRs. Thanks!

I actually rebased, and after that merged commits showed up :( Is there another way?

**Comment by jtpio** [comment]
> I actually rebased, and after that merged commits showed up :( Is there another way?

hmm I would have expected the rebase to help in that case.

**Comment by jtpio** [comment]
Just checked locally after syncing with the latest:

```bash
# sync the master branch
git fetch upstream
git merge upstream/master

# get the latest from the `ui_tests` branch
git checkout ui_tests
git merge upstream/ui_tests
git rebase master
```

Seems to be giving conflicts:

image

**Comment by jtpio** [comment]
Maybe the following will do the trick:

```bash
git rebase --rebase-merges master
```

Just pushed that to a branch in my fork and the diff looks cleaner?

https://github.com/jupyterlab/jupyterlab/compare/master...jtpio:ui_tests

**Comment by mbektas** [comment]
> ```shell
> git rebase --rebase-merges master
> ```

great! I will try this

**Pull request closed without merging**
