### PR TITLE
Fixes #6734: --extensions, --settings, --static, --all flags for `jupyter lab clean`

### LINKED ISSUE #6734: Clean up the Clean Logic
We need to improve the logic around cleaning.  We should follow the lead of `git clean` and support flags for the `jupyter lab clean` command [here](https://github.com/jupyterlab/jupyterlab/blob/e2fd4c8841a7393f9131fb6b6e8252864a8bd351/jupyterlab/labapp.py#L87).

The current logic only cleans the staging directory: https://github.com/jupyterlab/jupyterlab/blob/e2fd4c8841a7393f9131fb6b6e8252864a8bd351/jupyterlab/commands.py#L357 in the app directory.

I think we should add flags for cleaning:
- The static directory
- The settings directory (for recovery - warn if there are local linked extensions)
- The extensions directory (for recovery)
- The entire app directory (for recovery)

### PR DESCRIPTION
**Pull request by telamonian**

### CODE REVIEW

**Comment by telamonian** [comment]
> Can we please call these options at the end of the `usage` test, in order?

Done! Or did you want to have just one call with all of the options:

```
jupyter lab clean --extensions --settings --static --all
```

?

**Comment by telamonian** [comment]
Now that I think about it, we may want special handling for the `extensions` dir. Anything that gets deleted from a user's app dir will get automatically restored upon `jupyter lab build` *except* for `extensions` (I think). If you delete `extensions` you have to reinstall each one of your extensions.

So maybe `--all` should delete everything but `extensions`, and then `--nuke` (or something) deletes all? I guess in that case `--all` would really be more like `--more` or `--most`

**Comment by blink1073** [comment]
I think the options and the tests are fine as-is, we may want to add a not to `all` to warn you that you'd have to re-install extensions though.

**Comment by telamonian** [comment]
Alright. I won't get too theoretical about it, and I'll add that note

**Pull request merged**
