### PR TITLE
Perf: Update CSS for performance enhancements

### PR DESCRIPTION
**Pull request by goanpeca**
Port performance changes from 2.x branch to master (3.x)

## References

Includes the following work:

- https://github.com/jupyterlab/jupyterlab/pull/8968/files
- https://github.com/jupyterlab/jupyterlab/pull/8970/files
- https://github.com/jupyterlab/jupyterlab/pull/9382/files

### CODE REVIEW

**Comment by echarles** [comment]
@goanpeca Some issue around long line in codemirror has been reported by @afshin on 2.3 release. Not sure if that issue come from the CSS work, but it could be. Also the CSS changes brings very minor improvement compared to the virtual notebook. Worth triple check that we don't break anything.

**Comment by goanpeca** [comment]
>@goanpeca Some issue around long line in codemirror has been reported by @afshin on 2.3 release. Not sure if that issue come from the CSS work, but it could be. Also the CSS changes brings very minor improvement compared to the virtual notebook. Worth triple check that we don't break anything.

Indeed, looking into those.

**Comment by goanpeca** [comment]
## Before

Screen Shot 2021-05-10 at 10 14 12 PM
Screen Shot 2021-05-10 at 10 14 23 PM

## After
Screen Shot 2021-05-10 at 10 08 46 PM
Screen Shot 2021-05-10 at 10 08 53 PM

**Review by echarles — APPROVED** [review]
Tested and reviewed code. LGTM. Thx @goanpeca for working on this. I will leave it open a few days before merging cc/ @afshin

**Pull request merged**
