### PR TITLE
Use nullish operator instead of OR

### LINKED ISSUE #10808: dialog hasClose
hasClose is unconditionally true.(associated with https://github.com/jupyterlab/jupyterlab/pull/7885)
## Description

I want to prevent the modal from closing when clicking outside the modal with hasClose. However, according to this code, the hasClose variable is unconditionally true .

image

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #10808

## Code changes

Use nullish operator instead of OR to deal with falsy value.

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thanks!  CI doesn't appear to be cooperating yet today.

**Comment by blink1073** [comment]
Kicking CI

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.1.x

**Comment by jasongrout** [comment]
Never mind about backporting to 3.1. The code here changed enough from #9884 in 3.1 to make the backport not work.

**Pull request merged**
