### PR TITLE
Fix json schema for kernel status settings

### PR DESCRIPTION
**Pull request by fcollonval**
## References

When review the settings UI, an error was seen in the json schema definition.

## Code changes

Correct json schema for kernel status settings.

## User-facing changes

Correct schema definition

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by krassowski — APPROVED** [review]
LGTM, thanks!

**Comment by krassowski** [comment]
One note: I think the correct target would be 4.0 as this progress circle feature was not backported to 3.2.x

**Comment by fcollonval** [comment]
> One note: I think the correct target would be 4.0 as this progress circle feature was not backported to 3.2.x

Good catch thanks

**Comment by jtpio** [comment]
Thanks!

**Comment by krassowski** [comment]
The relevant feature was backported to 3.3.0 and we are still seeing the error this PR fixed in https://github.com/jupyterlab/jupyterlab/issues/12003 as this PR was not backported yet.

@meeseeksdev please backport to 3.3.x

**Pull request merged**
