### PR TITLE
Add kbd style

### LINKED ISSUE #4374: <kbd> tag does not render in notebook
Using `<kbd></kbd>` in Jupyter notebook renders to a keyboard key markup like <kbd>Ctrl</kbd>. In the Jupyter lab notebook, nothing really happens. Could be related to #1812 .

### PR DESCRIPTION
**Pull request by domoritz**
Fixes #4374. I took inspiration from the GitHub style but modified it to work better with the jupyter variables. 

**Screenshots**

Before
screen shot 2019-02-22 at 14 24 20

After
screen shot 2019-02-22 at 14 25 25

### CODE REVIEW

**Comment by domoritz** [comment]
I tried it in the dark theme and thought that the keys still look good there. yes, they could probably be a bit better but look pretty great already, I think. I'll try your suggestion but won't add new variables at this point.

**Comment by ian-r-rose** [comment]
Sounds good, thanks @domoritz.

**Comment by domoritz** [comment]
screen shot 2019-02-22 at 14 59 21

screen shot 2019-02-22 at 15 00 41

**Comment by domoritz** [comment]
Please just squash this PR into one commit.

**Pull request merged**
