### PR TITLE
Adding "Tags" heading to Pull Request Template

### LINKED ISSUE #7544: Tagging PRs with "Design System CSS" when they change CSS
I've been working on the JupyterLab Design System a lot lately, and @Zsailer pointed out that we should have a way to track changes to CSS so I can incorporate them into our design library.

### PR DESCRIPTION
**Pull request by tgeorgeux**
I've been working on the Design System with @isabela-pf to complete it and @Zsailer to help integrate it with Developer Workflow. I'm proposing we add to the PR template for people to tag if they've made changes to any .css files so I (or any other Designer) have access to a list of anything that may have updated the design system.

I also thought it would be nice to have the PRs tagged to make it easier for triage.

Let me know what you think.

## References

Close #7544

## Code changes

None

## User-facing changes

None

## Backwards-incompatible changes

None

## Adding Relevant Tags 

Tags added!

### CODE REVIEW

**Comment by jasongrout** [comment]
I think we should completely automate tagging that depends on the files touched. People are constantly forgetting to put pkg tags.

Even better is to just improve the search and filtering mechanism to be able to search for PRs modifying a certain group of files. But I think that is out of our hands, whereas listening to changes in a PR and automatically updating tags is more reasonable for us to do.

**Comment by declanvk** [comment]
@jasongrout, I think this github action: https://github.com/actions/labeler might be what you're looking for.

**Comment by jasongrout** [comment]
> @jasongrout, I think this github action: https://github.com/actions/labeler might be what you're looking for.

Yes, exactly!

**Comment by tgeorgeux** [comment]
@declanvk Long time no see! Thanks for pointing us in the right direction.

**Comment by blink1073** [comment]
Closing in favor of #7729

**Pull request closed without merging**
