### PR TITLE
Settings Editor: remove pluginslist grey background

### LINKED ISSUE #14364: Pluginlist in Settings Editor has grey background that reduces text contrast and readability for no good reason
## Description

Pluginlist in Settings Editor (used in both react and non-react versions of the settings editor) has grey background that reduces text contrast and readability for no good reason

## Reproduce

1. Open Settings > Settings Editor
2. Note pluginlist (left side of the Settings Editor split panel)

Screenshot 2023-04-11 at 2 54 02 PM

## Expected behavior

Making pluginlist background white would increase text contrast and readability. This can be done by deleting this line 
https://github.com/jupyterlab/jupyterlab/blob/a4aa5ebfd9b63d873bf676863e35e0aa68765d43/packages/settingeditor/style/base.css#L71

Here's how it would look:
Screenshot 2023-04-11 at 3 00 25 PM

### PR DESCRIPTION
**Pull request by andrii-i**
## References

- Fixes #14364

While in of itself use of grey is a fine stylistic choice, In jupyterlab shading is only used to separate sections with difference in elevation / z-levels. Section with highest elevation is "on top", has no shading and is "connected" to the main content area. Sections with lower elevation are "below" it and are shaded:
image

Sections with same elevation are separated with borders, shading is not used:
image

In settings editor pluginlist is at the same level as settingspanel, there is no visual indication that it is "below" it. So in this context the use of grey is inconsistent and visually confusing:
image

## Code changes

Pluginlist styling

## User-facing changes

Before:
Screenshot 2023-04-12 at 3 41 05 PM
Screenshot 2023-04-12 at 3 49 20 PM

After:
Screenshot 2023-04-12 at 3 40 33 PM
Screenshot 2023-04-12 at 3 40 45 PM

### CODE REVIEW

**Comment by andrii-i** [comment]
Bot please update snapshots

**Review by krassowski — COMMENTED** [review]
Just commenting since my review was requested: I still do not think that we should do that.

**Comment by andrii-i** [comment]
Kicking CI

**Comment by andrii-i** [comment]
please update documentation snapshots

**Comment by andrii-i** [comment]
Please update snapshots

**Comment by andrii-i** [comment]
please update galata snapshots

**Comment by andrii-i** [comment]
Please update snapshots

**Comment by andrii-i** [comment]
Thank you for force-pushing the branch @fcollonval. Previously UI tests unrelated to this change were failing but after this force-push they are green.

**Comment by andrii-i** [comment]
This PR is ready for review, please give it a look.

**Comment by JasonWeill** [comment]
Possible follow-on: the boxes around certain options now have borders that look confusingly similar to the divider between the left panel of the settings widget and the main area. On macOS, the narrow scroll bar track has a slight gray coloring, but I'm wondering whether, as part of this change or as a follow-on to it, we should lighten or delete the box borders indicated by the arrow below.

image

**Comment by andrii-i** [comment]
@JasonWeill Thank you for looking into this. I agree that proposed change makes left panel have the same color as the right panel / settings page. I also agree that settings page visual design is confusing and could use work where readability of the whole screen should be taken in the account but it's out of scope of the issue this PR is solving / this PR. Also in terms of problem space it is closer to other issues related to the settings editor UI rendering via `react-jsonschema-form`:
* https://github.com/jupyterlab/jupyterlab/issues/14010
* https://github.com/jupyterlab/jupyterlab/issues/14009
* https://github.com/jupyterlab/jupyterlab/issues/14006

Let's track your suggestion as a separate issue with `pkg:settingeditor` label. Could you please create it?

**Comment by JasonWeill** [comment]
Opened #16561 to track my proposed enhancement. Thanks!

**Review by JasonWeill — APPROVED** [review]

**Comment by andrii-i** [comment]
Thank you @JasonWeill

**Comment by andrii-i** [comment]
@krassowski could you please give this another look?

**Comment by andrii-i** [comment]
I'm planning to merge this on Friday if no new comments / change requests will come in. Please let me know if you are reviewing or plan to review this and would like more time.

**Comment by krassowski** [comment]
Does the current changeset ensure that the hover effect (https://github.com/jupyterlab/jupyterlab/pull/13384) is preserved?

**Comment by andrii-i** [comment]
@krassowski it was not preserving the hover effect as hover color was matching background color. I have updated the PR to preserve the hover effect by changing PluginList hover color to `--jp-layout-color2`. I used `--jp-layout-color2` because it's the color used for hover in file browser and I have not found a better option in https://github.com/jupyterlab/jupyterlab/blob/7bae8e3238967a0a776028150b49a4903759bc90/packages/theme-light-extension/style/variables.css#L4 or `variables.css` or other themes. 

Screenshot 2024-07-11 at 7 17 38 PM
Screenshot 2024-07-11 at 7 17 57 PM

**Comment by andrii-i** [comment]
Fixed the CI by running prettier and re-running galata and documentation visual tests until they passed (failures were not related to the change). 
@krassowski would you like to give this another look? Should we merge?

**Comment by andrii-i** [comment]
I'm planning to merge this tomorrow / in the upcoming days if no new comments or change requests will come in. Please let me know if you are reviewing or plan to review this and would like more time.

**Comment by andrii-i** [comment]
Thank you everyone for looking into this. @krassowski [suggested](https://github.com/jupyterlab/jupyterlab/pull/14375#issuecomment-2061766871) releasing this as a part of an alpha to allow user testing and feedback.

**Pull request merged**
