### PR TITLE
Update binder link for JupyterLab 0.33

### PR DESCRIPTION
**Pull request by ian-r-rose**

### CODE REVIEW

**Comment by jasongrout** [comment]
When I go to that URL, I keep getting lots of build messages, for a long time, which end in:

```
<something about image build succeeded or something>
Failed to connect to event stream
```

**Comment by ian-r-rose** [comment]
I think binder is having some problems today.

**Comment by jasongrout** [comment]
For everyone else following this, there has been quite a bit of discussion on the binder gitter channel: https://gitter.im/jupyterhub/binder

**Comment by jasongrout** [comment]
cf https://github.com/jupyterhub/mybinder.org-deploy/pull/680

**Comment by blink1073** [comment]
Looks good now, thanks!

**Pull request merged**
