### PR TITLE
fix for focus/information issues in the right-click context menu

### LINKED ISSUE #4529: More context in context menu
There are a number of places in the UI where the phosphor context menu system is more limited than we would want, and it is causing trouble. The context menu is based upon CSS selectors, but if there is more than one node with the same (or intersecting) selectors, we currently have no way of distinguishing which one was clicked on.

This, for instance, is a blocker for moving the file browser over to the application context menu, since we need to know more about which file browser item was clicked upon, and how to get that information in the `Open With` submenu.

It is also a problem with the context menu items in the tabs of the main area (as noted in #4500). If the user right-clicks on a tab that is *not* the currently active one, it shows the right context menus, but the commands operate on the wrong widget. I am not sure the best way to fix this, but it would be nice to be able to get more information to the commands invoked in the context menu about *which* node was clicked.

### PR DESCRIPTION
**Pull request by telamonian**
A potential fix for the context menu focus issues mentioned in #4500 and the more general context menu information issues mentioned in #4529. ~~This is meant as a jumping-off point for discussion in #4529, and not necessarily as a complete PR.~~ 

### Update: the PR has now gone through a few revisions, and I'm reasonably confident in the robustness of the latest version. See recent comments below for details.

The fix works by having the main app (ie the `JupyterLab` object) capture the most recent `contextmenu` event in a `._contextEvent` property. The context menu constructor code can then inspect this property in order to get any information it needs about the menu-initiating event that isn't exposed by the current framework.

In addition to the basic code for handling `._contextEvent`, the current version of my fix also includes a reimplementation of the commands from the document tab context menu that makes full use of the newly available information. This makes it so that the context menu commands operate on the tab you actually right-click on, instead of just always operating on the current active document (which is the behavior in the current `master` branch code).

@blink1073 edit: Fixes https://github.com/jupyterlab/jupyterlab/issues/4945, Fixes #4529.

### CODE REVIEW

**Comment by saulshanabrook** [comment]
> The context menu constructor code can then inspect this property in order to get any information it needs about the menu-initiating event that isn't exposed by the current framework.

Could you explain a little more what sorts of things this enables? Does this PR change any existing behavior?

**Comment by jasongrout** [comment]
@saulshanabrook - here is one answer to your question:

> This makes it so that the commands operate on the tab you actually right-click on, instead of just always operating on the current active document (which is the behavior in the current master branch code).

**Comment by kcramer** [comment]
This focus change also applies to the "Close Other Tabs" and "Close to the Right Of" from #4124 that I implemented.  When I tested it, it worked well.

**Comment by telamonian** [comment]
I took a stab at fixing up the focus fix. I think this version is a bit more generally applicable, and hopefully a bit easier to use too. 

When you right click, the current code exposes the hierarchy of html nodes you clicked on (ie the node directly underneath the mouse pointer plus all of its parents) via the `app.contextMenuNodes` property. Everything else is hidden/private to `app`. Theoretically, the html nodes should contain all of the information required by any context menu setup code, but it'll still be the responsibility of the code for each individual widget to fetch the specific information it needs from said nodes.

**Comment by telamonian** [comment]
@saulshanabrook - To answer your questions, the code in `packages/application/src/index.ts` by itself doesn't change any existing behavior. It just captures some extra information when you right click, and enables access to that information via the `app.contextMenuNodes` property and a couple of convenience methods.

On the other hand the code in `packages/docmanager-extension/src/index.ts` is an example of an implementation in which the new information has been used to improve the behavior of an existing context menu. A `contextMenuWidget` lambda has been added within the `addCommands` function. The remaining code has been modified in a few places in order to take full advantage of this lambda. As **jasongrout** so kindly quoted for me earlier, these modifications make
> it so that the context menu commands operate on the tab you actually right-click on, instead of just always operating on the current active document (which is the behavior in the current master branch code).

No other behavior is changed.

**Comment by blink1073** [comment]
Thanks for this!

**Pull request merged**
