### PR TITLE
Update react-json-tree, replace react-highlighter with react-highlight-words

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- part of #13928

## Code changes

- [x] update `react-json-tree`
- [x] replace unmaintained `react-highlighter` with the (slightly more) maintained `react-highlight-words`
  - [x] removes browser-side duplicates of `escape-string-regexp` and `color-name`
- [x] apply `jp-mod-selected` to highlighted words, use lab vars  
- [x] lazily load json viewer react component
- [x] resolve `yarn.lock`

## User-facing changes

- site should start ever-so-slightly faster 
  - shaves another 67kb (tree) + 18kb (highlither) (gzip, 20kb + 6kb) off the critical path to clearing moon animation
- search results will now match high-contrast themed search results (instead of just hard-coded `yellow`)
  - image
  - image

## Backwards-incompatible changes

- n/a

## Future work

This is still a very unsatisfying experience for structured data editing and viewing.

The current react-based solution is:

- slow
- can't JSON edit
- is not aware of JSON Schema
- can't be deep-linked

A significant overhaul of this should be a part of JupyterLab, including:
- lazy-loaded support for other JSON-compatible files like yaml, toml, json5 (ick)
- JSON schema validation

A customized codemirror-6 based editor with code folding and schema-based linting probably makes the most sense.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Doesn't seem particularly likely the test fails are relevant. Will circle back when the [ui tests](https://github.com/jupyterlab/jupyterlab/actions/runs/4212436502/jobs/7311456401) finish, but otherwise consider this ready to review, and will start digging into our `lodash.*` duplication issues.

**Comment by bollwyvl** [comment]
Hah, well, I guess this wasn't under UI test. A bit out of my interest level for this PR. Will open a follow-up for lodash.

**Review by fcollonval — APPROVED** [review]
Thanks a lot @bollwyvl

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
