### PR TITLE
Upgrade Vega+Vega-Lite

### PR DESCRIPTION
**Pull request by ian-r-rose**
Supersedes #4661.

@domoritz This is a continuation of your PR, where I have reverted the changes to `package.json` and `yarn.lock` in `jupyterlab/staging`. That directory should only make reference to published packages, if I understand it correctly. I think this should fix the build issues we were seeing.

### CODE REVIEW

**Comment by domoritz** [comment]
Thank you!

**Comment by ian-r-rose** [comment]
Thank you! Sorry it took so long...

**Comment by saulshanabrook** [comment]
Will this break Altair support tin JupyterLab? It looks like they don't target Vega 4 yet, only vega 3? https://github.com/altair-viz/altair/blob/master/altair/vega/v3/display.py#L17

Am I understanding things right that with this PR JupyterLab wouldn't have anything to handle the `'application/vnd.vega.v3+json'` mimetype?

**Comment by saulshanabrook** [comment]
I am going to try this with Altair and see if things work.

**Comment by saulshanabrook** [comment]
Nevermind, I forgot that Altair outputs vega lite instead of vega. 
screen shot 2018-06-29 at 1 28 51 pm

**Comment by saulshanabrook** [comment]
This works locally for me with Altair. Thanks for this Ian!

**Comment by ian-r-rose** [comment]
Thanks for checking @saulshanabrook, and thanks @domoritz!

**Pull request merged**
