### PR TITLE
Update server(s), nbclassic, pytest fixtures

### PR DESCRIPTION
**Pull request by afshin**
Updates `jupyter_server`, `jupyterlab_server`, and `nbclassic` dependencies.

Fixes https://github.com/jupyterlab/jupyterlab/issues/9473

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thanks!

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by jasongrout** [comment]
Just curious, do we have to rely on the `[test]` install option for jupyterlab_server? Perhaps our `[test]` option can rely on that, but the normal jupyterlab install can just rely on plain `jupyterlab_server`? I'm not sure what extra things `[test]` brings in, so feel free to ignore or explain why we need the `[test]` on our dependency.

**Comment by jtpio** [comment]
> Perhaps our `[test]` option can rely on that, but the normal jupyterlab install can just rely on plain `jupyterlab_server`?

This seems to be the case in this PR?

- `installs_require`: https://github.com/jupyterlab/jupyterlab/blob/80e657160968c2451bc5bb58b885912296003af0/setup.py#L149
- `in the `test` section of the `extras_require`: https://github.com/jupyterlab/jupyterlab/blob/80e657160968c2451bc5bb58b885912296003af0/setup.py#L162

**Pull request merged**
