### PR TITLE
Fix notebook css

### PR DESCRIPTION
**Pull request by ian-r-rose**
One possible way to fix the toolbar positioning.

### CODE REVIEW

**Comment by blink1073** [comment]
Why the removal of the docmanager changes?

**Comment by ian-r-rose** [comment]
cf discussion in #1639, with apologies to @blink1073 for the release churn.

**Comment by ian-r-rose** [comment]
The change in which div got the scroll bar made it unnecessary.

**Comment by blink1073** [comment]
Ha, two birds with one stone, nice.

**Comment by blink1073** [comment]
Does this preserve performance gains?

**Comment by ian-r-rose** [comment]
So far as I can tell it preserves the gains.

But clearly I cannot be trusted with CSS, so if there is anything here that does not make sense...

**Comment by blink1073** [comment]
No, I tested locally and this seems right.  Easy to forget the knock-on affects of CSS changes.  What a fun rabbit hole it is...

**Comment by blink1073** [comment]
I'll update #3499 to handle scroll in main area widgets as well.

**Comment by blink1073** [comment]
Actually, that PR was accomplishing the layout using the `BoxPanel` and `setStretch()`, which is more flexible.  I think this PR is fine though, because the `NotebookPanel` class will be going away entirely.

**Pull request merged**
