### PR TITLE
Added basic implementation to toggle the placeholder text 

### LINKED ISSUE #15138: Option to disable input placeholder text
### Problem

#13797 added a placeholder text string for `input()` calls. Developers would like the option to disable this.

### Proposed Solution

Add an option to disable the placeholder on inputs.

### Additional context

See also https://github.com/jupyter/notebook/issues/7063.

### PR DESCRIPTION
**Pull request by navdeepgill14**
## References

Closes #15138

## Code changes

1. Introduced a global state variable isPlaceholderVisible in widget.ts to manage the visibility of the placeholder text.
2. Implemented a function toggleGlobalPlaceholderVisibility in widget.ts to toggle the visibility state.
3. Added conditional rendering logic in the cell widget rendering method in widget.ts to show/hide the placeholder based on the isPlaceholderVisible state.

## User-facing changes

1. Users will see a toggle button in the notebook toolbar. Clicking this button will show or hide the placeholder text in the notebook cells.
2. This provides users with the flexibility to choose whether they want to see the placeholder text or not.

## Backwards-incompatible changes

None. The changes introduced are compatible with the existing JupyterLab public APIs and do not break any existing functionality.

### CODE REVIEW

**Comment by krassowski** [comment]
Thanks for starting this. We cannot add a new toolbar button for every setting, this should be rewritten to be a setting in Notebook schema instead. Please do ask if you need pointers.

**Comment by navdeepgill14** [comment]
Thank you for the feedback, @krassowski . I understand the concern about adding too many toolbar buttons. I'll work on moving this functionality to the Notebook schema as a setting. I'm relatively new to this, so I'd appreciate any pointers or guidance you can provide on how to best implement this in the Notebook schema. Thanks for your patience and support!

**Comment by krassowski** [comment]
A recent PR that implemented a new Notebook setting was https://github.com/jupyterlab/jupyterlab/pull/13944 - have a look at which files were modified in there to thread `inputHistoryScope` down.

**Comment by krassowski** [comment]
@navdeepgill14 are you still interested in working on this?

**Comment by krassowski** [comment]
Thank you for starting this @navdeepgill14! I will close this PR to allow anyone else interested in contributing to finish the implementation.

**Pull request closed without merging**
