### PR TITLE
PR: Add slash to publicPath

### PR DESCRIPTION
**Pull request by goanpeca**
Not sure if this is the right fix, but seems to solve the issues for `dev_mode` / `staging`

https://webpack.js.org/configuration/output/#outputpublicpath
```js
module.exports = {
  //...
  output: {
    // One of the below
    publicPath: 'https://cdn.example.com/assets/', // CDN (always HTTPS)
    publicPath: '//cdn.example.com/assets/', // CDN (same protocol)
    publicPath: '/assets/', // server-relative
    publicPath: 'assets/', // relative to HTML page
    publicPath: '../assets/', // relative to HTML page
    publicPath: '', // relative to HTML page (same directory)
  }
};
```
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/8833#issuecomment-675429539

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks!

1. We should never commit to `staging/` - that is done during the release process, and should always reflect the last release, even with bugs.
2. I think the better solution is to use the pageconfig values at runtime. For example, we took care of a similar issue in the federated example. First, we made a new file: https://github.com/jupyterlab/jupyterlab/blob/b8a145acd9ad599d5505384b4c2a39495cb9850c/examples/federated/core_package/publicpath.js
and then we added it to the entry point, before the actual first file:
https://github.com/jupyterlab/jupyterlab/blob/b8a145acd9ad599d5505384b4c2a39495cb9850c/examples/federated/core_package/webpack.config.js#L80

**Comment by goanpeca** [comment]
Thanks @jasongrout, will take a look!

**Comment by goanpeca** [comment]
@jasongrout I tried your suggestions and it did not seem to work. The `htmlWebpackPlugin` does not produce the right script tags, the publicPath on those scripts, is not correctly set.

**Comment by jasongrout** [comment]
You're right. I just pushed a commit that takes both approaches. It sets the static value to what we had before (i.e., a template variable), which is what the html webpack plugin uses. It also sets the dynamic value for all of the dynamically loaded scripts. It seems to work, and it avoids hardcoding the value, which is really important. We have many usecases where that URL changes and we need to be able to adapt.

**Comment by jasongrout** [comment]
I also rebased your commit to take out the edit to staging/

**Comment by goanpeca** [comment]
Thank @jasongrout :-)

**Comment by echarles** [comment]
@goanpeca @jasongrout this works for me in dev mode. When I run `jupyter lab bulid` and launch jlab, I have the old behavior: `<script src="static/lab/main.388032202ecaed589fea.js"></script></body></html>`

**Comment by jasongrout** [comment]
That is expected, until we make another release. `jupyter lab build` works off of the last released js.

**Pull request merged**
