### PR TITLE
Reinstate the labhubapp

### LINKED ISSUE #8704: Bring back the labhub entry point
## Description
We previously had this interface in 1.0.  We removed it in https://github.com/jupyterlab/jupyterlab/pull/7724.  However, based on the feedback from https://github.com/jupyterlab/jupyterlab/pull/8356 and @athornton on [gitter](https://gitter.im/jupyterlab/jupyterlab?at=5f171e82a15ff42fa8e1da20), we need to bring this back in order to pass settings to the lab app.

### PR DESCRIPTION
**Pull request by blink1073**
## References
Fixes #8704

## Code changes
Adds the `labhubapp` code and entry point.

## User-facing changes
This will be the only way to use JupyterLab with JupyterHub until there is a release with https://github.com/jupyterhub/jupyterhub/pull/3128

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by blink1073** [comment]
I opened https://github.com/jupyterlab/jupyterlab/issues/8807 to track the usage of `make_singleuser_app`

**Comment by blink1073** [comment]
@echarles, since @Zsailer is afk today are you able to review this one?

**Comment by echarles** [comment]
@blink1073 Sure, I will review the code.

It would be useful to test on jupyterhub... I can guess how to do that... but I can not find the doc... so here is my first feedback: Could you please update the https://jupyterlab.readthedocs.io/en/stable/user/jupyterhub.html and describe what are the requirements (version compatibility, configuration...).

**Comment by blink1073** [comment]
> It would be useful to test on jupyterhub... I can guess how to do that... but I can not find the doc... so here is my first feedback: Could you please update the https://jupyterlab.readthedocs.io/en/stable/user/jupyterhub.html and describe what are the requirements (version compatibility, configuration...).

Sounds good, I'll update those docs after I meet with Gonzalo.  Note that this PR does install `jupyterhub` and run the `jupyter-labhub` entry point directly in the `usage` test now at least.

**Comment by blink1073** [comment]
@echarles it's getting late for you and I won't be able to get back to this for another hour, I think overall we should shoot to merge this tomorrow and cut the beta tomorrow morning.

**Comment by echarles** [comment]
@blink1073 Thx. I am on this but have still another meeting to participate in 30m. If OK for you I put this at the top of my tomorrow todo and will bring feedback here.

**Comment by blink1073** [comment]
>  If OK for you I put this at the top of my tomorrow todo and will bring feedback here.

👍

**Comment by blink1073** [comment]
I updated the docs

**Comment by blink1073** [comment]
Sweet, thanks @echarles!

**Pull request merged**
