### PR TITLE
PR: Add options to add prefix to strings

### PR DESCRIPTION
**Pull request by goanpeca**
## Code changes

Adds some settings to the Translation-extension package so it is easier to debug localizing strings.

## User-facing changes

Adds some options to the Translation-extension package so it is easier to debug localizing strings.

Screen Shot 2020-09-01 at 21 08 39

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by goanpeca** [comment]
@blink1073 I added some extra options to the schema of the `translation-extension` package. Do you think they make sense and should go in there?

**Comment by goanpeca** [comment]
Pinging @kgoo124 . This should make the migration easier :-)

**Comment by blink1073** [comment]
I think this is good as-is

**Comment by goanpeca** [comment]
Ok, let me rebase and push. Thanks!

**Comment by kgoo124** [comment]
@goanpeca sounds great, thanks for the update

**Comment by goanpeca** [comment]
Rebase and fixed the linting issues @blink1073. Thanks!

**Pull request merged**
