### PR TITLE
Make debugger jest test more robust

### PR DESCRIPTION
**Pull request by fcollonval**
### References

`isAvailable` debugger unit test is failing often on the CI. This makes it more robust.

### Code changes

Mock the session connection instead of creating one.

### User changes

N/A

### Breaking changes

N/A

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thank you!

**Comment by blink1073** [comment]
linter isn't happy

**Comment by blink1073** [comment]
Hmm lint is still not happy

**Comment by fcollonval** [comment]
I don't get the linter error on vdom-extension. It was it also by the release of v4.0.0a8 and locally I'm not getting any error.

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.1.x

**Pull request merged**
