### PR TITLE
UI Tests: Update reference screenshots

### LINKED ISSUE #10371: Visual Regression Tests are failing on CI
## Description

Opening an issue to track the failure of the UI / Visual Regression tests on CI on `master`, which is also happening on new PRs.

Here is an example test run for reference: https://github.com/jupyterlab/jupyterlab/runs/2776114709

image

## Reproduce

Run the UI tests on CI.

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes #10371 

Update the reference screenshot to fix the UI Test CI check failing on master.

Follow-up to https://github.com/jupyterlab/jupyterlab/pull/10127

## Code changes

None

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by blink1073** [comment]
Let's not merge any other PRs until we merge this one to avoid unintentionally adding more regressions.

**Comment by jtpio** [comment]
Tests seem to be passing locally with this new set of reference screenshots:

image

**Comment by jtpio** [comment]
Getting the new screenshots from the CI artifacts after adding `jlpm run test:create-references` to the following, so they are generated on CI:

https://github.com/jupyterlab/jupyterlab/blob/9850b1a0461ae7d32374ca970185bdd12029fa62/.github/workflows/ui-tests.yml#L77


It looks like there might actually be some real regressions, for example the selected cell not being marked anymore:

image

**Comment by jtpio** [comment]
This is indeed visible when pulling the report from the commit (https://github.com/jupyterlab/jupyterlab/commit/d3915f659e76fedd0516da92925431e3e0b3c17b) that merged #10127: 

https://github.com/jupyterlab/jupyterlab/runs/2775919871

We can see the difference before and after:

https://user-images.githubusercontent.com/591645/121357917-7dbcb900-c932-11eb-9f2a-3d62593e4d57.mp4

**Comment by jtpio** [comment]
So I would say we merge this PR when everything is green again to not block other PRs.

We then need to open a new issue to track the visual regression introduced in https://github.com/jupyterlab/jupyterlab/pull/10127 and fix it, and update the reference screenshots one more time.

**Comment by blink1073** [comment]
> So I would say we merge this PR when everything is green again to not block other PRs.
> 
> We then need to open a new issue to track the visual regression introduced in #10127 and fix it, and update the reference screenshots one more time.

Sounds good, thanks @jtpio!

**Review by blink1073 — APPROVED** [review]

**Comment by fcollonval** [comment]
Actually the bug was likely introduced by 
```diff
-  flex: 0 0 var(--jp-cell-collapser-width);
+  display: 0 0 var(--jp-cell-collapser-width);
```
Introduce by the mentioned PR

**Comment by fcollonval** [comment]
I could create a parallel PR to correct that to avoid a round trip of screenshot update?

**Comment by jtpio** [comment]
It would be fine to do the extra round trip I guess, and this could serve as extra documentation of Galata catching regressions.

**Comment by fcollonval** [comment]
Ok, then I'll wait for this one to get merge. Then open a new one with the correction.

**Review by goanpeca — APPROVED** [review]

**Pull request merged**
