### PR TITLE
[WIP] unpin notebook, tornado

### LINKED ISSUE #6131: Unpin tornado dependency
#6123 rolled back our dependency on `notebook` due to some upstream issues with async kernel starts (or possibly tornado 6). We need to identify and fix these issues before making a release.

Edit: we have resolved the immediate issue with notebook in 5.7.8, but issues with tornado 6 remain.

### PR DESCRIPTION
**Pull request by minrk**
This just unpins the dependencies to see what happens; it does not fix whatever compatibility issue may be there, yet.

Fixes #6131

### CODE REVIEW

**Comment by minrk** [comment]
ok, verified that it's working with what will soon be notebook 5.7.7 and the pending terminado release.

@takluyver or @blink1073 is it possible to get a terminado release published to solve the tornado compatibility issue?

**Comment by jasongrout** [comment]
Thanks for working on this @minrk!

**Comment by ian-r-rose** [comment]
I'm still seeing issues with 5.7.7, along the lines of
```python
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/api/kernels/bb699f4d-dd2a-417c-8883-a0adba0a43da/channels?session_id=081a2738-da46-46db-b556-c8de0d7b0dff&token=5ad5f308acfdba227495ff408b73f8ac98fb64fa99ec9ce8', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/notebook/services/kernels/handlers.py", line 241, in get
        yield super(ZMQChannelsHandler, self).get(kernel_id=kernel_id)
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
        value = future.result()
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/notebook/base/zmqhandlers.py", line 297, in get
        yield gen.maybe_future(res)
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
        value = future.result()
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/tornado/websocket.py", line 278, in get
        await self.ws_connection.accept_connection(self)
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/tornado/websocket.py", line 881, in accept_connection
        await self._accept_connection(handler)
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/tornado/websocket.py", line 964, in _accept_connection
        await self._receive_frame_loop()
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/tornado/websocket.py", line 1118, in _receive_frame_loop
        await self._receive_frame()
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/tornado/websocket.py", line 1130, in _receive_frame
        data = await self._read_bytes(2)
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/tornado/websocket.py", line 1124, in _read_bytes
        data = await self.stream.read_bytes(n)
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/tornado/iostream.py", line 436, in read_bytes
        future = self._start_read()
      File "/home/ian/anaconda3/envs/test-tornado/lib/python3.7/site-packages/tornado/iostream.py", line 797, in _start_read
        assert self._read_future is None, "Already reading"
```

**Comment by ian-r-rose** [comment]
Anything I can do to help fix this @minrk? My time in the guts of tornado has not been particularly effective.

**Comment by jasongrout** [comment]
Closing in favor of #6174 (I also cherry-picked the pip freeze commit from here for that PR).

**Comment by jasongrout** [comment]
> ok, verified that it's working with what will soon be notebook 5.7.7 and the pending terminado release.

After upgrading nbconvert, terminado, notebook, and pyzmq, things also seem to work for me. Thanks for your work, @minrk and others, on getting updates to those packages out!

**Comment by minrk** [comment]
Sorry for not being able to finish this one. Thanks folks for finishing it up!

I have seen the "Already reading" message and *suspect* it's a tornado bug, and spent some time chasing it down, but haven't managed to isolate the issue. If it's in our code, I think it's in the fact that we have pre-flight checks in our websocket connection which means that we call `super().get()` significantly later than most WebSocketHandlers.

**Pull request closed without merging**
