### PR TITLE
Switch to dev-mode for ui-tests

### LINKED ISSUE #10528: Docker image for ui-test not using the latest js files
The jupyterlab docker image for ui tests is not building correctly the python package. This is not using the latest version of the js files.

### LINKED ISSUE #10546: Creating a new notebook does not pick up the preferred kernel.
## Description

#10510 change the behavior of JupyterLab when creating a new notebook as it will select `No kernel` by default instead of preferred kernel: (animation show try JLab with latest stable VS master)

default_kernel

> This breaks the UI-tests that assumes the preferred kernel is picked. But it was hidden due to #10528

## Reproduce

1. Create a new notebook File -> New -> Notebook
2. Default selection is `No kernel`

## Expected behavior

When a document has no kernel set, the preferred kernel should be selected by default.

## Context

- Operating System and version:
- Browser and version:
- JupyterLab version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

### PR DESCRIPTION
**Pull request by fcollonval**
Docker jupyterlab image is building dev-mode again so the code is the current one and not the latest available on npm.

Correct regression on not selecting preferred kernel when there is no kernel set

Improve docker by caching the `yarn install` step

## References

Fixes #10528
Fixes #10546 - so UI tests got green

Closes #10511

## Code changes

N/A

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by fcollonval** [comment]
@jtpio would you mind having a look at this one? This is blocking other pr's having UI changes.

**Comment by jtpio** [comment]
Thanks for looking into that one :+1: 

Looks good, and it fixes the visual regression tests so we should indeed get it in.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by fcollonval** [comment]
Thanks for the review @jtpio

**Pull request merged**
