### PR TITLE
Refactor CodeMirror Editor and finish tests

### PR DESCRIPTION
**Pull request by blink1073**
Also makes `CodeEditor.uuid` and `selectionStyle` writable and fixes a bug in `labapp.py`.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Would it make sense to have `CodeEditor.uuid` and `CodeEditor.selectionStyle` be settable rather than readonly? In particular, it would be nice to associate the editor `uuid` with a specific collaborative editing session. If that session has its own `uuid`, then simply having those be the same identifier would be a simplification.

**Comment by blink1073** [comment]
I think `selectionStyle` makes sense to be settable after the fact (and this PR adds that), but do you see a use case for needing to set the `uuid` outside of a constructor arg (it is in `IOptions`)?

**Comment by ian-r-rose** [comment]
In the case of Google Drive integration, an editing session gets its own `uid`, but this is not necessarily known at the time of creation of the widget. It should be possible to establish another mapping between these two `uid`s, but that is not super clean.

**Comment by blink1073** [comment]
Sounds good, updating.

**Comment by ian-r-rose** [comment]
Thanks!

**Pull request merged**
