### PR TITLE
Mimerender tracker

### PR DESCRIPTION
**Pull request by ian-r-rose**
Supersedes #4554.

We currently have no way for extension authors to interact with any documents created by the rendermime extension interface. So if anybody wants to iterate over open PDFs, JSON files, Vega files, rendered Markdown files, etc, they are out of luck.

This adds a top-level `mimeDocumentTracker` to the application object, and allows extension authors to filter those by mimetype.

### CODE REVIEW

**Comment by afshin** [comment]
I was going through your PR and thinking about this ... if we add the factory name that generates a MIME document to that document as a readonly attribute, we can get rid of all the individual trackers and the separate MIME document tracker and we can have a single tracker (the one you call `mimeDocumentTracker`), which would call `restorer.restore(...)` after all the MIME renderers have been created and loaded:
```typescript
restorer.restore(tracker, {
  command: 'docmanager:open',
  args: widget => ({ path: widget.context.path, factory: widget.factory }),
  name: widget => widget.context.path
});
```

**Comment by afshin** [comment]
Or perhaps change the `mimeDocumentTracker` to have type `InstanceTracker<MimeDocument>` instead of `IInstanceTracker<MimeDocument>`.

**Comment by afshin** [comment]
Actually, now that I'm thinking about it more, the `name` function probably also needs to be prefixed with the factory name so that there won't be name collisions when there are multiple views to the same `path`:
```
name: widget => `${widget.factory}:${widget.context.path}`
```
I updated the snippet above as well, but it's worth its own comment in case you only read the email version.

**Comment by ian-r-rose** [comment]
That's a nice idea, I'll give it a shot.

**Comment by ian-r-rose** [comment]
Hmm, after looking at your suggestion @afshin, it does not look so straightforward. The factory name is not available to the `MimeDocument`, and there is some extra threading through of the name. I'll push a commit that does this, and let's decide whether it is an improvement. If not, I can revert it.

**Comment by ian-r-rose** [comment]
Okay, I got the factory name in there using an `AttachedProperty`. Let me know if you think that 
7bcee0b is an improvement, otherwise I'll revert it.

**Comment by ian-r-rose** [comment]
Okay, this should be ready. I think we've landed on a good solution here.

**Comment by afshin** [comment]
How do you feel about just calling the variable `tracker` instead of `mimeDocumentTracker` since it's the only tracker in `mimerenderers.ts`?

**Comment by ian-r-rose** [comment]
Sure.

**Pull request merged**
