### PR TITLE
Test on Python 3.12 on CI

### PR DESCRIPTION
**Pull request by jtpio**
## References

Python 3.12 was released in October 2023: https://www.python.org/downloads/release/python-3120/

## Code changes

- Update the Linux Python tests to test on the latest Python stable release.
- Add trove classifier

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
Wait, it worked initially:

```
+ python -m pip install --pre -U pyzmq
Requirement already satisfied: pyzmq in /opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages (25.1.2)
Collecting pyzmq
  Downloading pyzmq-26.0.0b2-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.2 kB)
Downloading pyzmq-26.0.0b2-cp312-cp312-manylinux_2_28_x86_64.whl (906 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 906.8/906.8 kB 20.6 MB/s eta 0:00:00
Installing collected packages: pyzmq
  Attempting uninstall: pyzmq
    Found existing installation: pyzmq 25.1.2
    Uninstalling pyzmq-25.1.2:
      Successfully uninstalled pyzmq-25.1.2
Successfully installed pyzmq-26.0.0b2
```

but only failed on installation of `jupyterlab/tests/mock_packages/test_no_hyphens` example (which I presume is trying to install the stable version). So maybe waiting for a final release is all we need?

Cross-referencing https://github.com/zeromq/pyzmq/issues/1926

**Comment by jtpio** [comment]
Indeed. These test packages seem to depend on older dependencies, maybe it could be worth updating them (in a separate PR):

https://github.com/jupyterlab/jupyterlab/blob/66ed61006257a2a316d3d10c54e6aebfac9947cc/jupyterlab/tests/mock_packages/test_no_hyphens/pyproject.toml#L5

**Comment by jtpio** [comment]
Looking better after https://github.com/jupyterlab/jupyterlab/pull/16041.

Maybe we could still get this in while waiting for a final release of `pyzmq`.

**Comment by minrk** [comment]
Do you have a link to a build failing because of pyzmq? current stable pyzmq (25.1.2) supports Python 3.12 and has wheels, etc.

**Comment by jtpio** [comment]
It looks like the previous logs were lost after the rebase. Maybe it was just a side effect of https://github.com/jupyterlab/jupyterlab/pull/16041. I'll remove the pre-release install to double check.

**Comment by jtpio** [comment]
Looks like CI is now passing, so https://github.com/jupyterlab/jupyterlab/pull/16041 was probably the right fix.

Not sure why the lint requirement is still pending though, will try to kick CI.

**Comment by jtpio** [comment]
> Not sure why the lint requirement is still pending though, will try to kick CI.

This is because we have this rule currently: 

image

We can update the rule after the merge to specify `Linux (lint, 3.12)`.

**Review by krassowski — APPROVED** [review]
Thank you @jtpio!

**Comment by jtpio** [comment]
I have updated the rule:

image

**Comment by krassowski** [comment]
@jtpio I also did that! Just as I was merging this PR. But now there are two:

image

Even though I only see one in settings:

image

Were you setting the rules on repository or organisation level?

**Comment by krassowski** [comment]
Interestingly, my UI looks a bit different from yours.

**Comment by jtpio** [comment]
> Were you setting the rules on repository or organisation level?

On the repo: https://github.com/jupyterlab/jupyterlab/settings/rules/512352

Also seeing only one there still.

**Comment by krassowski** [comment]
This is super confusing, I do not see anything on https://github.com/jupyterlab/jupyterlab/settings/rules/512352 but I do: https://github.com/jupyterlab/jupyterlab/settings/branch_protection_rules/2453209. I guess we have different GitHub versions.

**Comment by jtpio** [comment]
Maybe one is inferred from the other one?

Should we remove the one from the ruleset then? (https://github.com/jupyterlab/jupyterlab/settings/rules/512352)

**Comment by krassowski** [comment]
I just removed the one that I added from `branch_protection_rules` and now see there is only one check status pending on old PRs so I think it is good now. Thanks!

**Comment by krassowski** [comment]
I noticed that the 3.12 check is expected to pass on all branches as seen in https://github.com/jupyterlab/jupyterlab/pull/16075:

image

I will remove this rule from the ruleset that targets all branches and re-add different rules for `main` and the `4.1.x` and `4.0.x` branches.

**Comment by krassowski** [comment]
Done, looks good now:

image

and:

image

**Comment by jtpio** [comment]
OK thanks. Otherwise maybe there is a way to not include "3.12" in the name of the ruleset, since it's likely to change again later at some point.

**Pull request closed without merging**
