### PR TITLE
Support dynamic toolbar definition

### PR DESCRIPTION
**Pull request by fcollonval**
## References

This addresses mainly the error seen in
https://github.com/jupyterlab/retrolab/pull/319#issuecomment-1017371450

it also allows to change the toolbar definitions from the settings without reloading

## Code changes

The toolbar factory for document widget factory can return either a list of toolbar items or an observable list. When an observable list is returned, the toolbar is updated accordingly.

The toolbar definition built using the settings are returning an observable list.

## User-facing changes

Toolbar definitions can be changed without reloading.

> When changing the definition, toolbar items not added through the settings (like the debug button) won't be positioned as expected - a reload will be needed for that.

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by fcollonval** [comment]
I'll like to target 3.3.x for this one as the toolbar definition from settings has been backported there.

**Comment by fcollonval** [comment]
cc @jtpio

**Comment by jtpio** [comment]
> I'll like to target 3.3.x for this one as the toolbar definition from settings has been backported there.

Sounds good, thanks!

**Review by krassowski — COMMENTED** [review]
Changing ranks works beautifully but I could not get the `disabled` option to work - the item did not disappear neither after saving settings nor after reloading. I see that a filter on `item.disabled` was removed - was this intentional, or just an oversight when refactoring?

**Comment by fcollonval** [comment]
Thanks for the review @krassowski 
This was indeed an unfortunate oversight. I improved the unit tests to cover rank and disabled status update.

**Comment by fcollonval** [comment]
@echarles would you mind reviewing this one? This is the one missing before releasing the 3.3 beta.

**Comment by echarles** [comment]
ranking and disabled work for me. Removing the complete item does not produce the expected result (item being removed), is it expected?

Untitled4

**Comment by fcollonval** [comment]
> ... but I may be misunderstanding the feature. Maybe the settings aims to mutate (rank, disable) the existing toolbar, but is not there to remove any of the existing items?

The settings for the toolbar is taking a similar approach as for the menus and the shortcuts; aka user settings is merged with the default one. Hence the behavior when the user setting is empty.

**Review by echarles — APPROVED** [review]

**Comment by echarles** [comment]
@meeseeksdev please backport to 3.3.x

**Comment by echarles** [comment]
@fcollonval I have merged this PR in master. Backporting to 3.3.x is giving conflict.

**Comment by fcollonval** [comment]
Thanks I'll do the backport

**Comment by jtpio** [comment]
This still seems to be an issue with `3.3.0rc0`, noticed when updating RetroLab to use the latest `3.3.0-rc.0` packages in https://github.com/jupyterlab/retrolab/pull/351: https://github.com/jupyterlab/retrolab/pull/351/commits/dd750da7814043b24404314016970f0b6e4489ef

**Comment by jtpio** [comment]
We still have the workaround in the test on master too: 

https://github.com/jupyterlab/jupyterlab/blob/c7b14eee863dc2b764378be5e9533ea2e7714d89/packages/apputils/test/toolbar.spec.ts#L310-L314

**Comment by fcollonval** [comment]
I tested locally without the workaround. And it worked. But I presume the trouble is on the CI, isn't it?

**Comment by jtpio** [comment]
The tests seem to be passing on the JupyterLab CI without the workaround: https://github.com/jupyterlab/jupyterlab/pull/12096

**Comment by jtpio** [comment]
But normally this is reproducible locally with retro with https://github.com/jupyterlab/retrolab/pull/351 and without the workaround (https://github.com/jupyterlab/retrolab/pull/351/commits/dd750da7814043b24404314016970f0b6e4489ef)

**Pull request merged**
