### PR TITLE
Fix recent breaking changes to normalizePath in filebrowser

### LINKED ISSUE #8382: Filebrowser completely broken in master: can only open a dir if it is a direct child of the jlab root dir
*paths are relative to jlab root dir*

Right now in the master branch, if I try to open a directory at eg `git/jupyterlab`, I get an error modal that says

```
Directory not found

Directory not found: 'git'
```

The error is due to the path getting screwed up somewhere and becoming `git/git/jupyterlab` instead of just `git/jupyterlab`. I believe the offending changes occurred in 46ec0496d43d6ab8ca3aba6 at these lines:

https://github.com/jupyterlab/jupyterlab/blob/46ec0496d43d6ab8ca3aba69b89ef04fe8e65079/packages/filebrowser/src/model.ts#L732-L744

Previously it was instead:

https://github.com/jupyterlab/jupyterlab/blob/36a8da4d6bffea0fd9992a4d88627cffb46fe6a0/packages/filebrowser/src/model.ts#L732-L741

Reverting the changes to `normalizePath` fixes the issue for me.

I'll open a PR with the reversion. Can someone please test this out and confirm both the issue and the solution?

paging @blink1073

### PR DESCRIPTION
**Pull request by telamonian**
## References

the last time this happened:
#6841
#6898
#6900
#6912

fixes #8382
46ec049

## Code changes

reverts recent breaking changes to `normalizePath` (see #8382)

## User-facing changes

unbreaks filebrowser. You can check out the binder build of any of our other recent PRs if you want to see the broken filebrowser in action, eg #8381:

[Binder](https://mybinder.org/v2/gh/nyu-ossd-s20/jupyterlab/show-writable-filebrowser?urlpath=lab-dev)

## Backwards-incompatible changes

NA

### CODE REVIEW

**Comment by telamonian** [comment]
Interestingly, the fix in this PR breaks the current filebrowser CI test. On the other hand, if you try out the binder build from any of our recent PRs, eg #8381:

[Binder](https://mybinder.org/v2/gh/nyu-ossd-s20/jupyterlab/show-writable-filebrowser?urlpath=lab-dev)

you can see for yourself that without this fix the filebrowser is clearly busted

**Comment by telamonian** [comment]
I figured out the problem with the tests and fixed it. To fix it, I always pass in `"/"` as the first arg to `resolve` in `normalizePath`. This effectively short circuits the expansion behavior of `resolve`, and ensures consistent behavior in both the node and browser environments. `resolve` will also ensure that there is always exactly one leading slash on any path it returns, which we then strip off as per the already existing logic.

**Comment by telamonian** [comment]
I added a test to filebrowser that covers `cd`-ing to a nested directory.

I also wanted to refactor `normalizePath` and add some unit tests for it, but I quickly ran into trouble. The current implementation of `normalizePath` is very tangled up in `ContentsManager` and elsewhere. It would be nice if we could figure out the absolute minimal set of behaviors required for `normalizePath` and then write a simplified version of it.

In retrospect, I guess this is what you were trying to do in the first place @blink1073?

**Comment by telamonian** [comment]
After realizing how complete `ContentsManagerMock` is, I went ahead and added some unittests for `normalizePath`. Two caveats:

- the "should not prepend root path to an absolute path" behavior of `normalizePath` seems strange and unnecessary. It would make more sense for us to either raise an error when the `path` arg is absolute, or to aggressively strip any leading `/` from `path`

- in order to be able to call `normalizePath` in the tests, I had to move it from a `Private` namespace into the public API. I think it's worth it so we can have some actual tests to help nail down what is otherwise a somewhat amorphous and fragile function

**Comment by blink1073** [comment]
I agree with raising an error when the `path` arg is absolute.  Otherwise, this looks great, thanks!

**Comment by telamonian** [comment]
`normalizePath` didn't make a ton of sense as part of the public API of `FileBrowserModel`, so I refactored it into `Contents.IManager.resolvePath`. The behavior of `resolvePath` is consistent with `posix-path.resolve`, but its signature is slightly different, so I think the name makes sense. I think it also makes sense to group it with the other drive-aware path handling functions in `Contents.IManager` (`driveName`, `localPath`, etc).

> raising an error when the `path` arg is absolute

As for this, turns out we rely 100% of the time on the current absolute `path` handling

https://github.com/jupyterlab/jupyterlab/blob/6d5240dda71fb3d12814e8b88b09e94e23d42875/packages/filebrowser/src/listing.ts#L935-L946

so for right now, we should leave the relative/absolute path handling as-is here

**Comment by telamonian** [comment]
yeah, the usage tests keep timing out, especially the python 3.5 version for some reason

**Comment by blink1073** [comment]
I think it is related to https://github.com/jupyterlab/jupyterlab_server/pull/88

**Comment by blink1073** [comment]
I'm addressing CI failures in #8433.  Merging this now.

**Pull request merged**
