### PR TITLE
Add `autoStartDefault ` to `getKernelPreference`

### PR DESCRIPTION
**Pull request by aditya211935**
## Code changes
`getDefaultKernel` function requires `autoStartDefault` argument to return `defaultKernel`. This in turn is used to start the notebook with default kernel if no kernel is specified.

However, `autoStartDefault` property is not defined anywhere execept in the original interface. https://github.com/jupyterlab/jupyterlab/blob/b57ec962a7b8cda65bb89a72223f195564f8387a/packages/apputils/src/sessioncontext.tsx#L274

I've added `autoStartDefault` property to `NotebookWidgetFactory` as `true`. This fixes the problem.

## User-facing changes
Previously, on clicking `New Notebook` from file explorer's context menu, the notebook would be opened without any kernel. 
With these changes, the notebook opens with the default kernel.

https://user-images.githubusercontent.com/23213686/178343393-59bae348-9255-4f5e-a4a0-250bfad7dc27.mov

### CODE REVIEW

**Comment by aditya211935** [comment]
@jasongrout Any updates?

**Comment by aditya211935** [comment]
@afshin @fcollonval Any updates?

**Comment by krassowski** [comment]
This would also alleviate a problem currently faced for users of https://github.com/krassowski/jupyterlab-voice-control/issues/5 extension. I am tagging it as a `enhancement` and adding to 4.0 milestone (so we have more time in case if someone comes back with a strong case for the existing behaviour).

@aditya211935 thank you for your contribution. Next time to get the PRs faster through the review please first open an issue describing the problem that you are trying to fix, as recommended and explained in the [contributing guideline](https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#submitting-a-pull-request-contribution).

**Comment by krassowski** [comment]
I think that this PR is compatible with other requests to improve the kernel startup like in: https://github.com/jupyterlab/jupyterlab/issues/12019 in principle. Recently a new draft PR appeared which touches similar ideas in a different user experience path: https://github.com/jupyterlab/jupyterlab/pull/12858 by @a3626a.

**Comment by a3626a** [comment]
@krassowski 
> I think that this PR is compatible with other requests to improve the kernel startup like in: #12019 in principle. Recently a new draft PR appeared which touches similar ideas in a different user experience path: #12858 by @a3626a.

I changed my draft to PR, now. :)

**Comment by krassowski** [comment]
Would you mind updating with the latest master branch (rebase or merge) so we can make sure the tests are passing? At the time of last commit there was something failing with the UI tests (unrelated to this PR).

**Comment by krassowski** [comment]
Thanks! It looks like the visual regression tests are failing and I believe that this is relevant to this change. This is because they await for a dialog window about kernel selection, which is being skipped with this PR.

**Comment by krassowski** [comment]
I think that `autoStartDefault` should be exposed in notebook settings. For now we could default it to `false` (this way tests would not need updating) and if we have more interest, change the default to `true` in a future release.

**Comment by aditya211935** [comment]
@krassowski Sure, will add `autoStartDefault` to notebook settings and default it to false.

**Pull request closed without merging**
