### PR TITLE
Upgrade to Typescript 3.7 RC

### PR DESCRIPTION
**Pull request by jasongrout**
## Code changes

This is a test PR to see how easy it will be to upgrade to Typescript 3.7 in the coming weeks.

## User-facing changes

None

## Backwards-incompatible changes

The Typescript definition files may be backwards incompatible. We remove the vega4 extension and upgrade the vega5 extension to vega-lite 4.0 beta, which supports TS 3.7.

### CODE REVIEW

**Comment by jasongrout** [comment]
I get one error doing `jlpm run build` with this:

We'll pick up the log after the vega packages built, when it is building the meta package:

```bash
$ cd packages/metapackage && jlpm run build
$ tsc -b
../../node_modules/vega-lite/build/src/compile/selection/selection.d.ts:11:10 - error TS2440: Import declaration conflicts with local declaration of 'SelectionComponent'.

11 import { SelectionComponent } from './selection';
            ~~~~~~~~~~~~~~~~~~

../../node_modules/vega-lite/build/src/compile/selection/selection.d.ts:11:10 - error TS2440: Import declaration conflicts with local declaration of 'SelectionComponent'.

11 import { SelectionComponent } from './selection';
            ~~~~~~~~~~~~~~~~~~


Found 2 errors.

error Command failed with exit code 1.
```

**Comment by jasongrout** [comment]
Indeed, here are the first few lines of that file:

```typescript
import { Channel, ScaleChannel } from '../../channel';
import { LogicalOperand } from '../../logical';
import { BrushConfig, SelectionDef, SelectionResolution, SelectionType } from '../../selection';
import { Dict } from '../../util';
import { VgBinding, VgData, VgEventStream, VgSignalRef } from '../../vega.schema';
import { DataFlowNode } from '../data/dataflow';
import { TimeUnitNode } from '../data/timeunit';
import { LayerModel } from '../layer';
import { Model } from '../model';
import { UnitModel } from '../unit';
import { SelectionComponent } from './selection';
export declare const STORE = "_store";
export declare const TUPLE = "_tuple";
export declare const MODIFY = "_modify";
export declare const SELECTION_DOMAIN = "_selection_domain_";
export interface SelectionComponent {
    name: string;
    type: SelectionType;
    events: VgEventStream;
    bind?: 'scales' | VgBinding | {
        [key: string]: VgBinding;
    };
    resolve: SelectionResolution;
    empty: 'all' | 'none';
    mark?: BrushConfig;
    _signalNames: {};
    project?: ProjectComponent[];
    fields?: any;
    timeUnit?: TimeUnitNode;
    scales?: Channel[];
    toggle?: any;
    translate?: any;
    zoom?: any;
    nearest?: any;
}
```
Looking at `node_modules/vega-lite/package.json`, I see that this is vega-lite 2.7.0.

@domoritz - what do you think? Several options come to mind:

1. Drop vega4 support in jlab 2.0 (due in January 2020) (I think that's why we are pulling in vega-lite 2.7.0?)
2. Fix vega-lite 2.7.0 or our build of it
3. Perhaps this is a Typescript issue? If so, report it upstream?

**Comment by domoritz** [comment]
It’s a bug in Vega-Lite 2.7 but we usually do not backport minor fixes. I’d say drop 2.7 from JL 2.

**Comment by jasongrout** [comment]
Will vega-lite 4 be ready by January? Can we move our support to vega-lite 3 and 4?

**Comment by domoritz** [comment]
Yes, our plan is to release in November.

**Comment by jasongrout** [comment]
Okay, thanks. I'll let you/others update jlab 2.0's vega roadmap (whether we just update the existing vega5 extension to vega-lite 4, or whether we need to make a new extension). I'll remove the vega4 extension here.

**Comment by jasongrout** [comment]
> It’s a bug in Vega-Lite 2.7 but we usually do not backport minor fixes. I’d say drop 2.7 from JL 2.

Just curious, would you say that vega-lite 2 is unmaintained at this point?

**Comment by domoritz** [comment]
From version to version, we only break very few things and so I'd say that if there is a bug, you can almost always upgrade.

**Comment by jasongrout** [comment]
Okay, thanks.

I pushed some commits that remove the vega 4 extension and upgrade the vega 5 extension to the latest vega and vega-lite. Now I'm seeing these errors when building JupyterLab, still from our builds of vega

```sh
$ cd packages/metapackage && jlpm run build
$ tsc -b
../../node_modules/vega-lite/build/src/transform.d.ts:10:10 - error TS2440: Import declaration conflicts with local declaration of 'JoinAggregateTransform'.

10 import { JoinAggregateTransform } from './transform';
            ~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/vega-lite/build/src/projection.d.ts:1:10 - error TS2440: Import declaration conflicts with local declaration of 'ProjectionType'.

1 import { ProjectionType } from './vega.schema';
           ~~~~~~~~~~~~~~

../../node_modules/vega-lite/build/src/spec/repeat.d.ts:4:10 - error TS2440: Import declaration conflicts with local declaration of 'RepeatMapping'.

4 import { RepeatMapping } from './repeat';
           ~~~~~~~~~~~~~

../../node_modules/vega-lite/build/src/spec/facet.d.ts:7:10 - error TS2440: Import declaration conflicts with local declaration of 'FacetMapping'.

7 import { FacetMapping } from './facet';
           ~~~~~~~~~~~~

../../node_modules/vega-lite/build/src/bin.d.ts:1:10 - error TS2440: Import declaration conflicts with local declaration of 'BinParams'.

1 import { BinParams } from './bin';
           ~~~~~~~~~

../../node_modules/vega-lite/build/src/legend.d.ts:5:71 - error TS2315: Type 'LegendConfig' is not generic.

5 export declare type LegendConfig = LegendMixins & VlOnlyGuideConfig & VgLegendConfig<number, number, string, Color, FontWeight, FontStyle, Align, TextBaseline, LayoutAlign, LabelOverlap, SymbolShape, number[], Orient, TitleAnchor, LegendOrient> & {
                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/vega-lite/build/src/legend.d.ts:46:33 - error TS2315: Type 'BaseLegend' is not generic.

46 export interface Legend extends BaseLegend<number, number, string, Color, FontWeight, FontStyle, Align, TextBaseline, LayoutAlign, LabelOverlap, SymbolShape, number[], Orient, TitleAnchor, LegendOrient>, LegendMixins, Guide {
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/vega-lite/build/src/axis.d.ts:5:47 - error TS2315: Type 'BaseAxis' is not generic.

5 declare type BaseAxisNoSignals = AxisMixins & BaseAxis<number, number, boolean, number | boolean, string, Color, FontWeight, FontStyle, Align, TextBaseline, LayoutAlign, LabelOverlap, number[], TitleAnchor>;
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/vega-lite/build/src/axis.d.ts:119:63 - error TS2677: A type predicate's type must be assignable to its parameter's type.
  Type 'string | number' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

119 export declare function isAxisProperty(prop: string): prop is keyof Axis;
                                                                  ~~~~~~~~~~


Found 9 errors.
```

**Comment by domoritz** [comment]
I'll update Vega-Lite to Typescript 3.7 to see whether it's a bug on our side.

**Comment by domoritz** [comment]
I fixed the problems we had in our codebase. They weren't really wrong since we just imported a type that was defined in the same file but I can see why we should avoid this.

**Comment by saulshanabrook** [comment]
> I pushed some commits that remove the vega 4 extension and upgrade the vega 5 extension to the latest vega and vega-lite. 

@jasongrout just a reminder that if we remove the vega 4 extension we can get rid of our pre-builds of the vega package since we only have one version to deal with, if we want.

**Comment by jasongrout** [comment]
Thanks.

As an update, Typescript 3.7 final is out now.

**Comment by jasongrout** [comment]
Also, a vega-lite beta was published (https://github.com/vega/vega-lite/releases/tag/v4.0.0-beta.11), so we can update to that and continue working on this.

**Comment by jasongrout** [comment]
This appears to build and run now. Next up is removing the pre-build of the vega stuff.

**Comment by jasongrout** [comment]
@domoritz - just to clarify, we're updating to vega-lite 4 in this PR. Can you see a reason why we'd need to ship vega-lite 3 as well in jlab 2?

**Comment by domoritz** [comment]
Altair still targets Vega-Lite 3 so we might want to still ship it. I think always keeping the last two versions would be good for users.

**Comment by jasongrout** [comment]
@domoritz  - can you release a TS 3.7-compatible version of vega-lite 3 then?

@saulshanabrook - how do you suggest shipping vega-lite 3 and vega-lite 4? Do you think we need the multiple vega infrastructure you set up? IIRC, they both use vega 5.

What do you think should be the default for `.vl`, `.vl.json`, and `.vegalite` file extensions? Or should we have something more intelligent that inspects the file, determines what version of vega-lite the file uses, and invokes the appropriate js library?

**Comment by jasongrout** [comment]
> @saulshanabrook - how do you suggest shipping vega-lite 3 and vega-lite 4? Do you think we need the multiple vega infrastructure you set up? IIRC, they both use vega 5.

I think we'll have to ship several different extensions:

* vega 5 extension
* vega-lite 3 extension (provides vl 3 renderer to system)
* vega-lite 4 extension (provides vl 4 renderer to system)
* vega-lite (provides a rendermime that can handle vl 3 and vl 4 files)

We can't easily combine vega-lite 3 and vega-lite 4 into a single extension since the npm package names (vega-lite) are the same, it's just the versions that are different. Also, we need to deep-inspect file content before deciding how to render it, since the version number is stored inside the file instead of in the extension.

Perhaps we should reconsider shipping vega/vegalite support in core, and instead support these in extensions outside of core? We are already moving vega 4 / vega-lite 2 support out of core with jlab 2.0. I assume we are going to have an outside extension for these anyway?

**Comment by jasongrout** [comment]
> Perhaps we should reconsider shipping vega/vegalite support in core, and instead support these in extensions outside of core? We are already moving vega 4 / vega-lite 2 support out of core with jlab 2.0. I assume we are going to have an outside extension for these anyway?

Thinking more about this:

* (IIRC) No other mimetype we support in core changes anywhere near as fast as vega-lite (or even vega). That means that for other mimetypes, we have some stability about what we support in core through different versions of jlab.
* Updating our vega-lite or possibly vega support every release and removing old versions means that people's saved vega/vl files stop working in core major upgrades (i.e. "upgrading broke my archived files!").
* If we are supporting older versions of vega/vl via external extensions, our answer to "upgrading broke my files" is "install this module to support your archived files". It's much simpler to just always say "install this module for vega/vl support" rather than "it works now with core, but some time in the next year or two, we guarantee we won't support that file format version anymore in core, and you'll have to install this other module".
* Right now (jlab 1.2.2) the vega bundles are a over 1/5 of our minified js that we build. That will probably go down in the next release where they could hopefully share the vega5 implementation instead of bundling vega4 as well, but still, it is a pretty heavy-weight dependency.

**Comment by jasongrout** [comment]
@domoritz - I'm happy to punt the vega discussion to another issue if you can release a vega-lite 3 version that supports ts 3.7, and I'll just upgrade to that for now.

**Comment by saulshanabrook** [comment]
> If we are supporting older versions of vega/vl via external extensions, our answer to "upgrading broke my files" is "install this module to support your archived files". It's much simpler to just always say "install this module for vega/vl support" rather than "it works now with core, but some time in the next year or two, we guarantee we won't support that file format version anymore in core, and you'll have to install this other module".

Maybe this is a good reason to move vega support to a third party extension exclusively?

**Comment by jasongrout** [comment]
> Maybe this is a good reason to move vega support to a third party extension exclusively?

Yes, this is what I'm thinking.

On the other hand, is vega/vega-lite usually just used for interactive graphics? If that is the case, then supporting archived vl files is less of an issue.

**Comment by domoritz** [comment]
Vega/Vega-Lite support in JupyterLab core is super awesome for users. In 99% of the cases, and spec for VL 3 will also work in VL 4. The only difficulty right now is that (as I understand it) mimetypes for Vega-Lite generated by Altair are for a specific version. Is there an easy way to fall back to a newer Vega-Lite mimetype?

**Comment by domoritz** [comment]
So my proposal: ship only the latest version of Vega and Vega-Lite with JL but make Altair charts fall back to the latest renderer in case and old version cannot be found. 

New Vega-Lite (major) versions rarely break previous specifications but we may target a new version of Vega or fix some minor inconsistency. 

How does that sound?

**Comment by jasongrout** [comment]
> Is there an easy way to fall back to a newer Vega-Lite mimetype?

I think the proper way to do this would be for vega-lite to ship a function to convert a vl3 spec to a vl4 spec. 99% of the time it does nothing but change the schema line, apparently. That way people can read vl3 files with the latest version of vega-lite in an officially supported way, rather than a "let's see if it works, maybe" way.

**Comment by jasongrout** [comment]
> I think the proper way to do this would be for vega-lite to ship a function to convert a vl3 spec to a vl4 spec.

Even better would be for the generic vl4 rendering method to silently convert to vl4 and render, so vl4 is able to render older versions of the spec transparently. That would make our lives a *lot* easier (we don't have to worry about versions, we just hand the data to the latest vega-lite), and would be an official supported thing from the vega project, rather than us just guessing that maybe it would work.

**Comment by domoritz** [comment]
> Even better would be for the generic vl4 rendering method to silently convert to vl4 and render, so vl4 is able to render older versions of the spec transparently. That would make our lives a lot easier (we don't have to worry about versions, we just hand the data to the latest vega-lite), and would be an official supported thing from the vega project, rather than us just guessing that maybe it would work.

We already do this for cases where it makes sense. In rare cases, we don't do this for example in Vega-Lite 4 where we are removing support for `rangeStep`.  I don't think we can promise backward compatibility for all future versions but we are making an effort to stay compatible.

**Comment by jasongrout** [comment]
Can you have a function that throws an error or something when it can't convert? Then we could throw the data into your function, and display a warning if it doesn't work.

In other words, we really want something that is officially supported by the library (possibly with errors when it can't do something), rather than just trying a fallback on our own.

**Comment by domoritz** [comment]
We can add that. Can you make sure that Altair can use the latest renderer available and that users can install an extension for a specific version if there is an error that they cannot fix?

**Comment by jasongrout** [comment]
> Can you make sure that Altair can use the latest renderer available

We can open an issue for the Altair project. I'm thinking that on the jlab side, if we find any of the vega-lite mimetypes coming through, we just ask our vega-lite extension to render it, and if it throws an error, we display a message to the user saying that they will need to install an extension to render it.

**Comment by domoritz** [comment]
I think Altair always generates a specific mimetype since jlab does not support multiple mistypes for the same document/file (not sure what the terminology is).  We will update Vega-Lite to show warnings for unsupported properties. Vega-Lite never throws errors when it can just ignore properties.

**Comment by domoritz** [comment]
I filed https://github.com/vega/vega/issues/2149 and https://github.com/vega/vega-lite/issues/5538 to track the changes on the Vega and Vega-Lite side.

**Comment by jasongrout** [comment]
@domoritz - just curious, are you also planning to ship a vl 3 patch release that supports TS 3.7?

**Comment by jasongrout** [comment]
> I think Altair always generates a specific mimetype since jlab does not support multiple mistypes for the same document/file (not sure what the terminology is).

Just to follow up on this - my understanding is that the vega-lite format has the version number embedded in it as the $schema key, so generating a single plot that targets multiple versions of vega-lite isn't possible, right?

**Comment by domoritz** [comment]
> Just to follow up on this - my understanding is that the vega-lite format has the version number embedded in it as the $schema key, so generating a single plot that targets multiple versions of vega-lite isn't possible, right?

The $schema is optional and Vega/Vega-Lite do not even look at the version when parsing a spec. The main issue (as I see it) is that the Vega mimetype has the version baked into it (https://github.com/jupyterlab/jupyterlab/blob/master/packages/vega5-extension/src/index.ts#L35).

**Comment by jasongrout** [comment]
> The $schema is optional and Vega/Vega-Lite do not even look at the version when parsing a spec.

Ah, I didn't realize it was optional.

I think you need a version *somewhere*, otherwise you don't know how to communicate exactly what dialect/version you are speaking. I think what you are saying is that it would be useful to say "this plot compatible with version 3 and version 4"? Who would keep track of that? Altair?

**Comment by domoritz** [comment]
@jasongrout Thanks for taking the time to talk today. I chatted with @kanitw and  Vega-Lite actually maintains backward compatibility to v3 by converting v4 to v3 specs. So let's continue with the plan as we discussed today. You can just use v4 for both VL3 and VL4 specs.

**Comment by jasongrout** [comment]
@domoritz - trying out the current code of this PR (which just calls the current 4.0b11 renderer with whatever v3 document altair gives us) prints out "The input spec uses vega-lite v3.4.0, but the current version of Vega-Lite is 4.0.0-beta.11" to the console as a warning, and then displays some errors rather than graphs, like:

`Javascript Error: Unrecognized transform type: "filter"` for https://altair-viz.github.io/gallery/simple_heatmap.html or https://altair-viz.github.io/gallery/simple_bar_chart.html, or `Javascript Error: Unrecognized transform type: "formula" for https://altair-viz.github.io/gallery/simple_line_chart.html

Screen Shot 2019-11-14 at 6 09 19 AM

**Comment by jasongrout** [comment]
(Again, happy to take this up on another issue in a few weeks when 4.0 ships, if you can release a v3 that supports ts 3.7 :)

**Comment by jasongrout** [comment]
> then displays some errors rather than graphs, like:

Ah, looks like the problem went away when I updated vega-embed and vega to the most recent versions. I can now render lots of altair examples.

I still see the warning message about rendering a vega-lite 3 spec in the console, though. Perhaps that can go away after implementing what we talked about, about being able to explicitly support rendering vl3 documents?

**Comment by jasongrout** [comment]
I did some more testing, and it looks like most of the altair examples work after upgrading vega-embed and vega. However, I'm still seeing issues with charts that involve maps that don't render. For example, https://altair-viz.github.io/gallery/airports_count.html gives

Screen Shot 2019-11-14 at 7 08 26 AM

with a lot of js errors like:
```
ERROR TypeError: "undefined has no properties"
    shape shapes.js:73
    bound markItemPath.js:20
    boundItem Bound.js:80
    transform Bound.js:41
    transform Bound.js:40
    evaluate Transform.js:55
    run Transform.js:33
    evaluate run.js:74
logger.js:3
    log logger.js:3
    error logger.js:24
    logMethod Dataflow.js:114
    evaluate run.js:109
ERROR TypeError: "scene is undefined"
    draw CanvasRenderer.js:113
    draw group.js:91
    visit visit.js:35
    draw group.js:90
    visit visit.js:35
    draw group.js:56
    draw CanvasRenderer.js:115
    _render CanvasRenderer.js:103
    _call Renderer.js:102
    render Renderer.js:105
    renderAsync Renderer.js:132
    evaluate View.js:122
logger.js:3
    log logger.js:3
    error logger.js:24
    logMethod Dataflow.js:114
    evaluate View.js:126
```

**Comment by jasongrout** [comment]
I've opened #7522 (Typescript upgrade) and #7523 (issue for vega-lite upgrade) to supersede this PR. I think we do the vega upgrade in a separate PR after vega-lite 4.0 comes out (or perhaps has an RC or at least is closer to a final release). That would cleanly separate the vega-lite upgrade issues from this Typescript upgrade issue.

**Pull request closed without merging**
