### PR TITLE
Add "Go to Line" and "Find" capabilities to csvviewer

### PR DESCRIPTION
**Pull request by perrinjerome**
## Go to Line

jupyterlab-csvviewer-go-to-line

## Find
jupyterlab-csvviewer-find

Some notes about *find* implementation: 
 * So that we can configure the colours for "cell matching search" and "current cell matching search", I had to refactor a bit to replace the `TextRender`s created for the theme by some `TextRenderConfig` that would allow the search service to build a `TextRenderer` which style the matching cells accordingly.
 * added a unit test faking the cell renderer service to check that the cell matching search text are highlighted.

At the same time, I add a fixup commit for a mistake in #5377

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks for this, @perrinjerome!  I took an initial pass and had a couple of questions:

- Do you mind making a `Dialog.prompt()` static method that uses your prompt widget?  I can see using that a lot!
- It looks like the scroll position logic might not work if the rows are not all uniform height, or am I mistaken?

**Comment by perrinjerome** [comment]
Thanks for feedback @blink1073 

> * Do you mind making a `Dialog.prompt()` static method that uses your prompt widget?  I can see using that a lot!

Good idea. I also felt that such a prompt widget would be a nice to have utility. I'll try to take care of this in the next few days.

> * It looks like the scroll position logic might not work if the rows are not all uniform height, or am I mistaken?

Ah no, it would not work ... but as far as I see csvviewer cells currently always have all same height.

I tried everything I could think of to get cells of different heights and came up with this csv:
```csv
Column A,Colum B
"CELL WITH LOTS OF DATA
CELL WITH LOTS OF DATA
CELL WITH LOTS OF DATA 
CELL WITH LOTS OF DATA",b
a,b
a,b
```

but it still looks like this:

image

So I'm wondering if there a way to have cells with variable height with csvviewer.

Anyway, we can already write this in a way that would still work in this case. Do you think it means we have to take into account the [`sectionSize`](https://github.com/phosphorjs/phosphor/blob/849b2fbbf394d39147242ad1ec958e50d94ce110/packages/datagrid/src/datagrid.ts#L579-L590) of each row ? something like:

```js
  /**
   * Go to line
   */
  goToLine(lineNumber: number) {
    let scrollY = this._grid.scrollY;
    for (let i = scrollY; i < lineNumber - 1; i++) {
      scrollY += this._grid.sectionSize('row', i);
    }
    this._grid.scrollTo(this._grid.scrollX, scrollY);
  }
```

This makes me feel datagrid widget needs an API to do this, also because if this implementation was on DataGrid, DataGrid could take decisions based on the knowledge it has on the data and cell shapes ( for example it should know if all cells have same height and use the same `this._grid.baseRowSize * (lineNumber - 1)` approach as this first implementation ). I noticed this was suggested in https://github.com/phosphorjs/phosphor/issues/285#issuecomment-312141525 .

As a first step, I can update this implementation using this `sectionSize` approach.

**Comment by blink1073** [comment]
Ah, good point regarding the line location.  Mind adding an inline TODO comment pointing to that comment?

**Comment by perrinjerome** [comment]
@blink1073 I think I implemented the changes as we discussed. Thanks again for comments.

I made a Dialog.prompt and simplified a bit, the signature is simple `Dialog.prompt( prompt: string, defaultValue: string | number | boolean)` and the input widget depend on the type. There's no longer the possibility to use different button text or dialog title, but I guess it's not needed in this context, when more control is needed, it's always possible to use `showDialog` .

image

**Comment by blink1073** [comment]
Looks great, thanks again!  Linter caught a few things:

```
ERROR: packages/apputils/src/dialog.ts[730, 24]: == should be ===
ERROR: packages/apputils/src/dialog.ts[736, 24]: == should be ===
ERROR: packages/apputils/src/dialog.ts[765, 31]: == should be ===
ERROR: packages/csvviewer/src/widget.ts[277, 105]: trailing whitespace
```

**Comment by perrinjerome** [comment]
Oh sorry for that, I'll update this soon.

**Comment by perrinjerome** [comment]
I updated (by amending the commits - I hope this way is OK), this time linter should be OK. Thanks !

**Comment by blink1073** [comment]
LGTM, thanks!

**Pull request merged**
