### PR TITLE
Add output prompt overlay for toggling scroll mode

### LINKED ISSUE #5897: Collapsing Output cells - Downgrade from Notebook
Hi,

Is it possible to collapse the output cell in Jupyter Lab, while still showing some of the output?

In **Jupyter notebook** you can click on the white area under `Out[XX]:` to collapse the output:

image

In my opinion, **Jupyter Lab** has two issues here:
 1. To collapse the output one has to click on the blue line on the left of the output cell ("harder" to click there than it is in the notebook, because of the smaller surface area). Clicking anywhere in the white area is more efficient from an UI-point of view.
 2. Once collapsed the output is completely gone. It'd be nice to keep at least some of it (e.g. just show the first few lines, as is the case in jupyter notebook).

image

As for point 2: a compromise could be to introduce several levels of "collapsation": *first click* = show first few lines, *second click* = just show ..., *third click* = show everything again

What do people think? Is there room for improvement?

---

My system:
- Windows 10
- Jupyter Lab 0.35.4

### PR DESCRIPTION
**Pull request by krassowski**
## References

Closes #5897 by implementing the highly upvoted proposal from https://github.com/jupyterlab/jupyterlab/issues/5897#issuecomment-591884430 (thanks @Linusnie).

## Code changes

- adds optional `promptOverlay` option to `OutputArea.IOptions` (off by default as output area does not manage whether the output is scrollable)
- adds `toggleScrolling` signal to `OutputArea` to connect it in code cells.

## User-facing changes

output-scrolling-overlay

## Backwards-incompatible changes

None, this could possibly be backported.

### CODE REVIEW

**Comment by krassowski** [comment]
bot please update snapshots

**Comment by jtpio** [comment]
Kicking CI

**Review by jtpio — COMMENTED** [review]
Just checked on Binder and it looks good, thanks!

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
