### PR TITLE
User defined default viewer take precedence for rendered factory

### LINKED ISSUE #7776: Cannot override the default rendered viewer
In https://github.com/jupyterlab/jupyterlab/pull/6813, @ian-r-rose wrote a nice setting for overriding the default editor for a file. This is used in preferredWidgetFactories to allow a user to control a default editor for the file: https://github.com/jupyterlab/jupyterlab/blob/57cd4545b93606177950e7189d03394b26c63b0c/packages/docregistry/src/registry.ts#L334-L339

However, this override is *not* taken into account when we ask for the default rendered widget factory: https://github.com/jupyterlab/jupyterlab/blob/57cd4545b93606177950e7189d03394b26c63b0c/packages/docregistry/src/registry.ts#L406-L421

This means that we can't set the default renderer for clicking on a file in a rendered markdown, for example. This is confusing since, for example, the setting name is "defaultViewers" (and not defaultEditors or something).

Should we allow a separate override for the default rendered widget?

This came up in https://github.com/mwouts/jupytext/issues/271

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fix #7776

## Code changes

Look first in user overrides list for rendered widget so it takes precedence.

## User-facing changes

Some link may open with a different editor if they change the default viewer settings.

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by krassowski** [comment]
This fixes https://github.com/jupyterlab/jupyterlab/issues/10875 - should we backport it?

**Comment by fcollonval** [comment]
> This fixes #10875 - should we backport it?

I don't think it fixes that issue because this addresses a corner case: the viewer to pick when a local file is opened from a link in a markdown cell for example). Before this PR, the user settings was ignored when looking for the viewer is that case.

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.6.x

**Pull request merged**
