### PR TITLE
Experimental work on autogenerating rendermime extensions

### PR DESCRIPTION
**Pull request by ellisonbg**
Initial work on #2354

### CODE REVIEW

**Comment by ellisonbg** [comment]
@blink1073

**Comment by blink1073** [comment]
Here are my thoughts:

Make a separate package called `rendermime-interfaces` that has:

```
IRenderer - and associated interfaces
IWidgetFactoryOptions
IRendererExtension
    mimeType: string;
    renderer: IRenderer;
    index?: string;
    widgetFactoryOptions?: IWidgetFactoryOptions
    renderTimeout?: number;
```

A mimerenderer extension would export by default an object or an array of objects of IRendererExtension type.

We populate `PageConfig` using the installed extensions that have the `mimeRenderer: true` metadata.
The rendermime extension would get the config and create the rendermime instances for each of these.
The docregistry extension would get the same config and create widget factories for the ones that have widget factory options.  We will create a widget factory that creates a widget factory given a mimeType, renderTimeout, and widgetFactoryOptions.

**Comment by ellisonbg** [comment]
Here is the recent outline of the geojson version of this:

https://github.com/gnestor/jupyter-renderers/blob/master/packages/geojsonviewer/src/widget.ts

**Comment by ellisonbg** [comment]
@blink1073 I think the vega package in this repo is ready for the next steps. But I am having some weird compiler errors:

```
> @jupyterlab/all-packages@0.7.1 build /Users/bgranger/github/jupyterlab/jupyterlab/packages/all-packages
> tsc && node build.js

../vega/src/index.ts(27,24): error TS7016: Could not find a declaration file for module 'vega-embed'. '/Users/bgranger/github/jupyterlab/jupyterlab/node_modules/vega-embed/src/embed.js' implicitly has an 'any' type.
../vega/src/index.ts(192,7): error TS2322: Type '{ mimeType: string; renderer: typeof VegaRenderer; rendererIndex: number; widgetFactoryOptions: {...' is not assignable to type 'IRendererExtension | IRendererExtension[]'.
  Type '{ mimeType: string; renderer: typeof VegaRenderer; rendererIndex: number; widgetFactoryOptions: {...' is not assignable to type 'IRendererExtension[]'.
    Type '{ mimeType: string; renderer: typeof VegaRenderer; rendererIndex: number; widgetFactoryOptions: {...' is not assignable to type 'IRendererExtension'.
      Types of property 'renderer' are incompatible.
        Type 'typeof VegaRenderer' is not assignable to type 'IRenderer'.
          Property 'mimeTypes' is missing in type 'typeof VegaRenderer'.
```

I am doing the same thing as before to type `vega-embed` and I don't see why it isn't picking up the interfaces. Thoughts?

**Comment by blink1073** [comment]
This was the culprit:

```diff
diff --git a/packages/all-packages/src/typings.d.ts b/packages/all-packages/src/typings.d.ts
index 072fc810c..fbb17dec7 100644
--- a/packages/all-packages/src/typings.d.ts
+++ b/packages/all-packages/src/typings.d.ts
@@ -6,3 +6,4 @@
 /// <reference path="../../coreutils/typings/url-parse/url-parse.d.ts"/>
 /// <reference path="../../rendermime/typings/ansi_up/ansi_up.d.ts"/>
 /// <reference path="../../terminal/typings/xterm/xterm.d.ts"/>
+/// <reference path="../../vega/typings/vega-embed/vega-embed.d.ts"/>
```

The other error is because you were passing the `VegaRenderer` class instead of an instance.

**Comment by blink1073** [comment]
Continuing in #2488.

**Pull request closed without merging**
