### PR TITLE
Upgrade yarn in staging to 1.21.1

### LINKED ISSUE #7692: Dev installation instructions incur an error
## Description

`jlpm run build` on a clean pip install prints out an error on current master (023828ac81a932a5a887c43ab369d94b28c32f1e)

## Reproduce

1. `pip install -ve .`
2. `jlpm run build`

Gives an error:

```
(node:35285) UnhandledPromiseRejectionWarning: Error: Cannot find module 'react-json-tree/package.json'
Require stack:
- /[snip]/jupyterlab/buildutils/lib/utils.js
- /[snip]/jupyterlab/buildutils/lib/ensure-repo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at requirePackage (/[snip]/jupyterlab/buildutils/lib/utils.js:305:20)
    at /[snip]/jupyterlab/buildutils/lib/utils.js:280:31
    at Array.forEach (<anonymous>)
    at /[snip]/jupyterlab/buildutils/lib/utils.js:271:27
    at Array.forEach (<anonymous>)
    at Object.getPackageGraph (/[snip]/jupyterlab/buildutils/lib/utils.js:267:25)
```

This stems from a couple of things:
1. react-json-tree is for some reason not hoisted into the root node_modules, but instead lives in `./packages/json-extension/node_modules/react-json-tree`
2. The test at https://github.com/jupyterlab/jupyterlab/blob/023828ac81a932a5a887c43ab369d94b28c32f1e/buildutils/src/utils.ts#L321 fails initially because `Error: Cannot find module '/[snip]/jupyterlab/node_modules/@jupyterlab/json-extension/lib/index.js'. Please verify that the package.json has a valid "main" entry`, so it falls through to the catch. However, it really failed because the json-extension package wasn't built yet, so the `lib/` directory didn't exist.

This error goes away once the json-extension package is built, i.e., the second time `jlpm run build` is run.

I'm not sure why `react-json-tree` is not hoisted to the root node_modules.

### PR DESCRIPTION
**Pull request by jasongrout**
## References

The latest yarn bump in the root package.json to 1.21.1 did not actually upgrade the yarn we ship.

Fixes #7692 

## Code changes

This upgrades the yarn we ship to yarn 1.21.1, using the distribution file https://github.com/yarnpkg/yarn/releases/download/v1.21.1/yarn-1.21.1.js (from the release notes https://github.com/yarnpkg/yarn/releases/tag/v1.21.1)

### CODE REVIEW

**Comment by jasongrout** [comment]
@blink1073 - I think this should be merged before the next beta release.

**Comment by telamonian** [comment]
> The latest yarn bump in the root package.json to 1.21.1 did not actually upgrade the yarn we ship.

I noticed this as well, and wondered what the deal was. Thanks for tackling it

**Comment by jasongrout** [comment]
Thanks @telamonian. @afshin, you were merging things recently. Is there a reason you didn't merge this?

**Comment by afshin** [comment]
No, I just got caught up in other tasks!

**Comment by afshin** [comment]
(And I was only looking at the PRs with green checkboxes and didn't re-run these to see if they pass.)

**Pull request merged**
