### PR TITLE
Add the notebook mime type to the default file type

### PR DESCRIPTION
**Pull request by blink1073**
cf http://jupyter.readthedocs.io/en/latest/reference/mimetype.html#custom-mimetypes-used-in-jupyter-and-ipython-projects

### CODE REVIEW

**Comment by blink1073** [comment]
cc @ian-r-rose

**Comment by ian-r-rose** [comment]
Thanks, @blink1073 .

I noted that there are some slight inconsistencies with the discussion of the Contents API [here](http://jupyter-notebook.readthedocs.io/en/latest/extending/contents.html), especially w/r/t the directory `IFileType`. I'm not sure that the distinction gets used anywhere, though.

**Comment by blink1073** [comment]
I think it is fair that we are more specific on the front end for known file types, distinct from the contents api.

**Comment by ian-r-rose** [comment]
Fair enough.

**Pull request merged**
