### PR TITLE
Consider higher levels when toggling plugin

### LINKED ISSUE #16101: An extension disabled at the sys-prefix level can't be enabled at the user level
## Description
If an extension is enabled at the sys-prefix level, it can't be enabled at the user level. 

## Reproduce

Disable an extension at the sys-prefix level and try to enable it at the user level. 

## Expected behavior
Users should be able to opt into using extensions that have been disabled at the sys-prefix level

## Context

- JupyterLab version: v4.1.5

### PR DESCRIPTION
**Pull request by divyansshhh**
Fixes #16101

### CODE REVIEW

**Comment by divyansshhh** [comment]
This was the initial commit made for jupyterlab/jupyterlab#16102 ([commit link](https://github.com/jupyterlab/jupyterlab/pull/16102/commits/85ec8135e34bb64ac34ca1e751ff47b3ed4d1b0c)).

I think I missed redoing this change while I was adding the _is_locked checks. 

@krassowski can we release another patch with this since this is a blocking change for us? Apologies for the inconvenience.

**Comment by krassowski** [comment]
It looks like having a test sequence in the usage test would help here. Do you have time to add it?

**Comment by divyansshhh** [comment]
> I can wait a bit with releasing 4.2.0rc0 if that works for you

4.2 has a couple of changes we want to take time and test so would want to do thorough testing at our end before we upgrade. A 4.1 patch would be quicker to test. 

> We try not to release too frequently unless there are critical or security bugfixes because users get annoyed by frequent notifications about updates being available.

Yeah I understand but it'd be helpful to release another patch today.

**Comment by divyansshhh** [comment]
> It looks like having a test sequence in the usage test would help here. Do you have time to add it?

Yes I'm adding this

**Review by krassowski — APPROVED** [review]
Thank you @divyansshhh!

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.1.x

**Pull request merged**
