### PR TITLE
Rendermime Enhancements

### LINKED ISSUE #3038: display priority?
jupyter notebook has a display priority array. jupyterlab seems to support displaying through mime renderers.

on jupyterlab, i see PDFs being rendered if my mimebundles contain PDFs and SVGs.

how can i tell jupyterlab that i want it to render SVGs before PDFs?

### PR DESCRIPTION
**Pull request by blink1073**
- [x] Rename `RenderMime` -> `RenderMimeRegistry` and break it out of application into its own extension.
- [x] Add a `defaultRank` parameter to rendermime factories to allow for proper rank separation and allow third party renderers to insert themselves in a known position.
- [x] Move the MathJax typesetter to a plugin and load MathJax dynamically (requires a change to `jupyterlab_launcher`)
- [x] The latex typesetter is now only given the to rendermime registry constructor and is optional
- [x] Ensure that the default rendermime factories can handle a lack of a typesetter
- [x] Provide a list of standard renderers that can be used by examples and third parties
- [x] Use the `html-webpack-plugin` to create [cache-friendly](https://webpack.js.org/guides/caching/) bundles.  In a follow up PR we'll automatically select libraries to put in the vendor bundle.

Fixes #3038

### CODE REVIEW

**Comment by blink1073** [comment]
cc @minrk @jasongrout @sccolbert 

A question remains about what to do about the standard renderers, which I renamed to `standardRendererFactories` in this PR.  Alternatives include moving these to the `JupyterLab` application object static namespace or allowing a renderer to be skipped.

@minrk had said on gitter:

---
I saw the latexTypesetter object, which has an `_initialized` property. If either this object were unavailable or not initialized (whichever makes the most sense), then the latex renderer could be registered but would not be used?
This sounds analogous to what IPython does with formatters, where there is a list of registered formatters, but each formatter also has a `.enabled` property, which can be toggled. So the active formatters are `[f for f in formatters if f.enabled]`.
The latex renderer's `.enabled` could be tied to the availability of the Typesetter, in that case.
---

The renderer factories don't get the TypeSetter until the call to `renderModel`, so we can't have an `enabled` property without some other changes.

**Comment by blink1073** [comment]
cc @vidartf

**Comment by vidartf** [comment]
I just wanted to lay out my use cases for nbdime:
 1. Running external to jupyter lab (lab might not even be installed on system).
 2. Running as a lab extension (WIP).

The rendermimes are here relevant when rendering added/deleted/unchanged cells, or when rendering individual outputs.

The safe behavior would be to just render this using the default/standard renderers. Alternatively, one could want to use a custom renderer order defined in jupyter lab. Whether to use the default or custom order should probably be user setting (on the nbdime side), at least for case 2.

For both standard and custom renderer order, a well-defined API will significantly reduce the maintenance burden in tracking new version of jupyterlab. With regards to the location of `standardRendererFactories`, the only requirement here is that it is available in the library somewhere, preferably in a location that won't pull in any dependencies that would not otherwise be needed.

A point to consider: If jupyterlab adds a new renderer for a previously unsupported MIME-type, should it be considered a breaking change? What version specifier would be natural for nbdime to use for its dependence on the relevant packages in lab (~ or ^) after 1.0, in order to reliably support the use-cases above?

**Comment by blink1073** [comment]
Thoughts:

- add API for multiple latex renderers based on rank
- ‎add fallback latex typesetter that just adds a `<pre>` tag
- ‎leave standard renderers in the `rendermime` package
- ‎make a separate MathJax package that adds the script tag until we can use MathJax 3.0
- ‎use MathJax package in application extension

Then we could add an API that lets you choose the default typesetter, and even change live on a per notebook basis.

**Comment by ian-r-rose** [comment]
Since the notebooks, consoles and documents already clone the application rendermime, it would not be too difficult to set the typesetter for a document on a case-by-case basis already. At the time of writing it, having a setter for the `Rendermime.latexTypesetter` seemed a bit of a kludge, but it does allow for the possibility of live-swapping already.

I do wonder whether there are a lot of people that would want to have multiple LaTeX typesetters in a single application.

**Comment by blink1073** [comment]
As @dhirschfeld pointed out, you might have some notebooks that require MathJax and not others.   If the typesetters aren't registered then you would need some other way to know about the other available ones, and since this was already a registry I think it makes sense to have them there.

**Comment by ian-r-rose** [comment]
Makes sense. The LaTeX typesetter UI could go in the soon-to-exist "View" menu.

**Comment by blink1073** [comment]
Indeed

**Comment by ian-r-rose** [comment]
This is well outside of the scope of this PR, but I have had discussions with @mpacer regarding using the JupyterLab rendermime as a standalone package with `nbconvert` (similar to what I think @vidartf is describing for `nbdime`). In order to do that, we would probably need to build in some notion of running it on the server (using something like `jsdom`?).

**Comment by blink1073** [comment]
I think headless chrome is a more likely candidate than jsdom.

**Comment by flying-sheep** [comment]
hi, so how do I use this now to prevent PDF from rendering in the browser while PDF or SVG is in the mime bundle?

**Comment by blink1073** [comment]
I don't follow the question.  You want to disable PDF rendering entirely?

**Comment by flying-sheep** [comment]
You said this fixes #3038. And #3038 was about being able to configure a display order again.

**Comment by blink1073** [comment]
Ah, you are right.  This PR does not address that issue directly, re-opening.

**Pull request merged**
