### PR TITLE
Add whole-word matching option in search bar

### PR DESCRIPTION
**Pull request by krassowski**
## References

Point (4) in #13756.

## Code changes

- adds `wholeWords` property on search model
- start unit testing search model

## User-facing changes

- Added toggle button in search area to enable whole word matching.
- Increase size of the icons in the buttons. The buttons already were 20px by 20px so previously the click boundaries were not matching the visual indicator boundaries. If we want to reduce the buttons in the future we should modify hte entire button

## Backwards-incompatible changes

New required members of the search model

### CODE REVIEW

**Comment by krassowski** [comment]
please update snapshots

**Comment by krassowski** [comment]
please update galata snapshots

**Comment by fcollonval** [comment]
Kicking the CI

**Review by fcollonval — APPROVED** [review]
Thanks @krassowski 

> I restarted the CI :crossed_fingers:

**Pull request merged**
