### PR TITLE
Remove transient data when serializing output

### PR DESCRIPTION
**Pull request by blink1073**
Fixes https://github.com/jupyterlab/jupyterlab/issues/1698.

### CODE REVIEW

**Comment by blink1073** [comment]
cc @gnestor, can you check this fixes the validation error you saw?

**Comment by gnestor** [comment]
Ya, I'll test now...

**Comment by gnestor** [comment]
After re-running all cells and saving a notebook using this branch, no more notebook validation errors 👍

**Comment by blink1073** [comment]
Thanks, @gnestor!

**Pull request merged**
