### PR TITLE
Expose override urls for static and theme

### LINKED ISSUE #5449: Is there some way to set a CDN url to host the static fiels
I've asked a few times on gitter but didn't get an answer. 

I can see that the jupyterlab_server can take a public_url which can be a CDN url [1], but I can't for the life of me figure out how to set it, in jupyter_notebook_config.py, or other.

Is there some straight forward way to get jupyterlab to host the javascript, css and images files from  a CDN, its for speed as I deploy lab servers for a lot of users?

[1] https://github.com/jupyterlab/jupyterlab_server/blob/master/jupyterlab_server/handlers.py#L113

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #5449

### CODE REVIEW

**Comment by eoinmurray** [comment]
@blink1073 thanks for this! Will check it out later today hopefully

**Comment by eoinmurray** [comment]
@blink1073 how do I use this in jupyter_notebook_config.py?

```
c.LabApp.override_static_url = '<url>'
c.LabApp.override_theme_url = '<url>'
```

or 

```
c.NotebookApp.override_static_url = '<url>'
c.NotebookApp.override_theme_url = '<url>'
```

**Comment by eoinmurray** [comment]
I keep getting:

```
[W 21:57:17.664 LabApp] Config option `override_static_url` not recognized by `LabApp`.
[W 21:57:17.666 LabApp] Config option `override_theme_url` not recognized by `LabApp`.
```

This is with jupyterlab installed using `pip install git+git://github.com/jupyterlab/jupyterlab.git`

**Comment by blink1073** [comment]
Whoops, forgot to tag the traits as configurable, new PR and release on the way!

**Pull request merged**
