### PR TITLE
Do not install optional npm packages

### LINKED ISSUE #2918: Build error for optional canvas package
Can we suppress the build error for the optional canvas package?

```
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.10.0-32-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/joao/anaconda3/envs/jupyterlab-tutorial/share/jupyter/lab/staging/node_modules/canvas
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

```

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #2918.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
I still get `node-gyp` rebuild errors with this PR.

**Comment by blink1073** [comment]
I had to remove node_modules first.

**Comment by ian-r-rose** [comment]
I still get the error with `git clean -fdx && npm install && npm install`

**Comment by blink1073** [comment]
Hmm, I tried the same and I don't get the error.  Can you try with npm 4 (`npm install -g npm@4`)?

**Comment by ian-r-rose** [comment]
npm 4 does not fix the issue, however if I manually include the `--no-optional` flag it does. For some reason it is not picking up the `.npmrc` file.

**Comment by blink1073** [comment]
What does `npm config get no-optional` show in the repo root?

**Comment by ian-r-rose** [comment]
`true`

**Comment by ian-r-rose** [comment]
And yet a bare `npm install` does not fix the issue.

**Comment by blink1073** [comment]
I'm not sure what to do about that.  Does `jupyter lab clean && jupyter lab build` complete without any errors?  That is the primary goal of the PR.

**Comment by ian-r-rose** [comment]
Yes, it builds without errors (I presume due to the explicit `--no-optional` in `commands.py`). In any event, this is more of an annoyance than a real problem. Correct canvas emulation on Linux is not a big deal to me at the moment.

**Pull request merged**
