### PR TITLE
Fix integrity2 test

### PR DESCRIPTION
**Pull request by fcollonval**
Fix integrity2 test

### CODE REVIEW

**Comment by fcollonval** [comment]
This seems to fix the CI issue.

But there is a strange message with `postcss`:

```
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
```

Not it is also displayed in the last passing CI tests on master:
https://github.com/jupyterlab/jupyterlab/runs/3104197742?check_suite_focus=true

**Review by blink1073 — APPROVED** [review]
Thank you!

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.0.x

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.1.x

**Pull request merged**
