### PR TITLE
Use Path.resolve() to get canonical case-sensitive path names

### LINKED ISSUE #9698: Jupyter lab failed to build
## Description
Jupyter lab failed to build

## Reproduce

When I open jupyter-lab, it asks for build:
>JupyterLab build is suggested:
>algorithmx-jupyter needs to be included in build
>ipyturtle2 needs to be included in build
>jupyter-threejs needs to be included in build

Then I ran `jupyter lab build` and got:
>C:\Users\Kevin>jupyter lab build
>[LabBuildApp] JupyterLab 3.0.6
>[LabBuildApp] Building in c:\python\share\jupyter\lab
>[LabBuildApp] Building jupyterlab assets (production, minimized)
>Build failed.
>Troubleshooting: If the build failed due to an out-of-memory error, you
>may be able to fix it by disabling the `dev_build` and/or `minimize` options.
>
>If you are building via the `jupyter lab build` command, you can disable
>these options like so:
>
>jupyter lab build --dev-build=False --minimize=False
>
>You can also disable these options for all JupyterLab builds by adding these
>lines to a Jupyter config file named `jupyter_config.py`:
>
>c.LabBuildApp.minimize = False
>c.LabBuildApp.dev_build = False
>
>If you don't already have a `jupyter_config.py` file, you can create one by
>adding a blank file of that name to any of the Jupyter config directories.
>The config directories can be listed by running:
>
>jupyter --paths
>
>Explanation:
>
>- `dev-build`: This option controls whether a `dev` or a more streamlined
>`production` build is used. This option will default to `False` (i.e., the
>`production` build) for most users. However, if you have any labextensions
>installed from local files, this option will instead default to `True`.
>Explicitly setting `dev-build` to `False` will ensure that the `production`
>build is used in all circumstances.
>
>- `minimize`: This option controls whether your JS bundle is minified
>during the Webpack build, which helps to improve JupyterLab's overall
>performance. However, the minifier plugin used by Webpack is very memory
>intensive, so turning it off may help the build finish successfully in
>low-memory environments.
>
>An error occured.
>RuntimeError: JupyterLab failed to build
>See the log file for details:  C:\Users\Kevin\AppData\Local\Temp\jupyterlab-debug-cztmopjy.log

### Webpack-related problem
@jasongrout suggested the use of `jlpm why webpack` to track the origin of the problem, hence, I ran that command inside the `staging` subdirectory of jupyterlab and obtained this:
>C:\Python\share\jupyter\lab\staging>jlpm why webpack
>yarn why v1.21.1
>[1/4] Why do we have the module "webpack"...?
>[2/4] Initialising dependency graph...
>[3/4] Finding dependency...
>[4/4] Calculating file sizes...
>=> Found "webpack@5.18.0"
>info Has been hoisted to "webpack"
>info Reasons this module exists
>   - Specified in "devDependencies"
>   - Hoisted from "@jupyterlab#builder#webpack"

>info Disk size without dependencies: "5.9MB"
>info Disk size with unique dependencies: "9.7MB"
>info Disk size with transitive dependencies: "22.77MB"
>info Number of shared dependencies: 55
>Done in 0.61s.

## Expected behavior
A successful build was expected since webpack problem was corrected for jupyterlab 3.0.6 (#9651)

## Context
- Operating System and version: Windows 10 Pro
- Browser and Version: Brave v 1.19.88 Chromium: 88.0.4324.96
- JupyterLab version: 3.0.6
- Node.js version: 15.7.0
- Python version: 3.8.5
- All python packages were installed using pip

## Note
I am able to use JupyterLab prebuilt extensions normally. But since `jupyter lab build` fails, I cannot use the source extensions for JupyterLab.

### PR DESCRIPTION
**Pull request by jasongrout**
## References

Fixes #9698

## Code changes

This fixes `jupyter lab build` on Windows when using pip. The underlying problem is in pip (from its dependency distlib) and how it normalizes paths to lowercase when it creates executables for Windows entry points (see https://bitbucket.org/pypa/distlib/issues/143/do-not-normcase-executable-path-when and pypa/pip#6582 (comment)). Basically, when we set the current working directory to a lower-case version of the path, node starts using the lower-case version for its module cache when building JupyterLab. However, the mini-css-extract plugin in JLab asks node to resolve a path for its loader, which uses the canonical case for the path. This leads to Node having two copies of the same modules in its cache (differentiated by the path case), which leads to problems when doing instanceof checks. See the exploration at #9698 for more details.

Until the issue is fixed in distlib/pip, we can work around it by using Path.resolve(), which seems to give back a canonical name (including case) for a path. It’s possible that we should use Path.resolve() many more places in the code, but it seems that this change is minimal enough to at least get the windows build working, and I want to be conservative here. Also note that os.path.realpath does not do this correction on python 3.6, so that's why we are using Path.resolve()

You can see the effect of this change by installing jupyterlab with (current) pip on Windows and running `jupyter lab path`. You’ll notice that the application directory is lowercase before this commit, but normal case after (e.g., the drive letter is uppercase, etc.).

We also revert the directory changing from aee97d8 (#9051). The underlying issue with Windows builds this was trying to fix seems to be the wrong case for the path, which is addressed in the previous commit.

This should have been caught in the Windows CI tests, but we also realized that the windows CI tests were doing nothing (literally). So we updated them, converted them to powershell, and made sure they were failing before the fix here, and passing afterwards.

## User-facing changes

`jupyter lab build` works on Windows when installed with pip

### CODE REVIEW

**Comment by jasongrout** [comment]
The windows test claim to have succeeded, but the log shows they failed, so this needs to be fixed as well.

**Comment by jasongrout** [comment]
It seems that the CI build failure may be because yarn is on d:, and maybe realpath is not correcting the case for a different drive letter?

**Comment by jasongrout** [comment]
> It seems that the CI build failure may be because yarn is on d:, and maybe realpath is not correcting the case for a different drive letter?

Actually, it's because in python 3.6 (which the CI runs) doesn't correct case with realpath. It looks like pathlib Path.resolve() does on python 3.6, though, so I'll switch to that.

**Comment by jasongrout** [comment]
I'm rebasing and reordering the commits to get windows tests working (and failing), then fixing them in the followup commits.

**Comment by jasongrout** [comment]
Looks like we have to check the output of each individual command in powershell. There is an RFC for adding `set -e`-like behavior at https://github.com/PowerShell/PowerShell-RFC/pull/261

**Comment by jasongrout** [comment]
Yay, the windows build failed (correctly)!

Now adding the other commits to fix the build.

**Comment by jasongrout** [comment]
Okay, I think this is ready for review. That was a lot of hours/days to debug a tricky problem. Some points to remember in retrospect:

1. Thanks to everyone who kept insisting they were having errors even though most of us couldn't reproduce them. Turns out it was only an error in a very particular set of circumstances, but it was a problematic issue down at the bottom of the python stack.
2. Spend the time up-front to have good debugging tools. It was a pain early on to do printf-style debugging on a slow Windows VM with an iteration cycle of several minutes. Once I got Chrome debugging working, it was much easier to zero in on the problem.
3. Think about all the confounding factors, and don't stop until you get to a solution that accounts for all of them. It was tempting to stop once we thought we knew how to work around the problem (force npm to always lowercase things, for example). That didn't account for the conda vs pip discrepancy, though, nor the `python -m` discrepancy. It was much more satisfying to keep going until we saw the root of the problem (pip normcases the executable in script files it creates), and fix that for the whole community. Also, once I started playing around with directories, I started noticing some had different case than others, and that was puzzling until we narrowed down the pip/distlib problem.
4. Don't assume your tests are working - check them to be sure. First, the Windows tests were doing literally nothing, then we thought we fixed them, but it turns out they weren't failing when there was an error. To paraphrase [Juvenal](https://en.wikipedia.org/wiki/Quis_custodiet_ipsos_custodes%3F), who tests the tests?
5. Don't forget to think about file case sensitivity. I've been bitten before (rarely, though) by case sensitivity of filenames. Hopefully next time I'll think of it earlier in the process.

**Comment by vidartf** [comment]
Impressive piece of detective work! 👏

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.0.x

**Pull request merged**
