### PR TITLE
Update notebook toolbar example docs

### PR DESCRIPTION
**Pull request by blink1073**
## References
Part of 3.0 release checklist: #8038

## Code changes
Update docs for the notebook toolbar example.

## User-facing changes
Updated docs

## Backwards-incompatible changes
None

### CODE REVIEW

**Review by krassowski — COMMENTED** [review]
Tested locally with 3.0.5, copy-pasting when following the instructions all work fine. The only departure is the default name of the cookiecutter extension (default: `myextension`; example: `my_cookie_cutter_name`), but this will need to be changed by the user anyways and might be better addressed over in the cookiecutter repository if it benefits new developers.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by blink1073** [comment]
@meeseeskdev please backport to 3.0.x

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.0.x

**Pull request merged**
