### PR TITLE
Opening keyboard shortcuts UI result in "destruction" of shortcut settings

### LINKED ISSUE #12056: Opening keyboard shortcuts UI result in "destruction" of shortcut settings
## Description

Opening the newly incorporated keyboard shortcuts settings UI results in dumping of JSON for all possible shortcuts, making it impossible to navigate manually and distinguish between default and user-defined settings.

This is a notable regression as carefully crafted JSON settings of advanced users will be destroyed  (along with any comments they may have written) when they open keyboard shortcuts UI, without touching a single button.

## Reproduce

1. Open settings UI
2. Click Keyboard Shortcuts
3. Wait 2-3 seconds to see that "Restore to defaults" shows up automatically
4. Open JSON Settings Editor (Advanced Settings Editor), see that all default shortcuts were dumped as a big JSON blob:
    Screenshot from 2022-02-15 21-10-10
5. Close and reopen the shortcuts UI, see that all shortcuts are incorrectly shown as "Custom" making it impossible to understand which shortcuts were actually modified.
    Screenshot from 2022-02-15 21-08-19

## Expected behavior

1. Only shortcuts actually modified by user are added to the right panel
2. No change in shortcuts JSON is performed without user interaction

## Context

- Browser and version: Chrome
- JupyterLab version: 3.3

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #12056

## Code changes

react-json-schema-form `Form` component is internally checking for discrepancy between the settings provided and the default built from the schema (see [that line](https://github.com/rjsf-team/react-jsonschema-form/blob/a6d1c32102d534fc1ba155dcb04173c80560dc4a/packages/core/src/components/Form.js#L38)). The trouble for shortcut arises because of `args` that is an optional argument of type object. So within the `Form` component, `args` will always exist when building from the schema. The workaround here is to define a default empty `args` on all shortcuts when transforming them.

## User-facing changes

No more settings changes when the user open the shortcut settings panel.

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
cc @krassowski for review

**Review by krassowski — APPROVED** [review]
LGTM, thanks!

**Comment by jtpio** [comment]
Looks like this needs a lint pass.

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.3.x

**Pull request merged**
