### PR TITLE
Makes restorer parameter optional in toc-extension

### LINKED ISSUE #11444: Make ILayoutRestorer optional in toc-extension
### Problem

`IRetroShell` in RetroLab cannot use the `toc-extension` because the required parameter `restorer` (of type `ILayoutRestorer`) is not accessible. Error:

```
Plugin '@jupyterlab/toc:plugin' failed to activate. index.es6.js:292:25
Error: No provider for: @jupyterlab/application:ILayoutRestorer
```

### Proposed Solution

Make the `restorer` parameter optional in `toc-extension`.

### Additional context

See also PR #11420 which made `labShell` optional in this extension.

### PR DESCRIPTION
**Pull request by jweill-aws**
## References

Fixes #11444 .

## Code changes

Makes the `restorer` parameter in `toc-extension` optional so that shells that do not implement a layout restorer, such as `IRetroShell`, can use this extension.

## User-facing changes

None.

## Backwards-incompatible changes

None.

### CODE REVIEW

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by fcollonval** [comment]
I think we can go a step further and make the widget trackers optional; in particular in retrolab, only one tracker is available per current document, isn't it?

```
    IEditorTracker,
    IMarkdownViewerTracker,
    INotebookTracker,
```

> I'll open a PR because actually the logic should be inverted. The table of content should provide the registry and the generator should be defined in the appropriate packages (INotebookTracker -> notebook, IEditorTrakcer -> fileeditor,...).

**Comment by jtpio** [comment]
Good point :+1: 

Yes let's make a bigger pass on that `toc-extension` to put more dependencies as optional if possible (which can be done as a separate PR)

> The table of content should provide the registry

Making one of the toc plugins return the registry sounds good. Looking at the current state the following logic should probably be in its own plugin too:

https://github.com/jupyterlab/jupyterlab/blob/5755ea86fef3fdbba10cd05b23703b9d60b53226/packages/toc-extension/src/index.ts#L199-L219

**Comment by jweill-aws** [comment]
Per @jtpio and @fcollonval , I've updated this PR to make additional parameters optional.

**Review by fcollonval — APPROVED** [review]
LGTM thanks @jweill-aws

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.2.x

**Pull request merged**
