### PR TITLE
Upgrade xterm.js from 5.1.0 to 5.5.0

### PR DESCRIPTION
**Pull request by krassowski**
## References

- fixes https://github.com/jupyterlab/jupyterlab/issues/15808
- migrates to new packages under new `@xterm` namespace which is important to make sure we get security updates as the old packages (with no namespace) are no longer maintained as these were susceptible to typo-squatting attacks

## Code changes

None

## User-facing changes

- https://github.com/xtermjs/xterm.js/releases/tag/5.2.0:
  - Support for the overline attribute SGR 53/55
  - 15 bug fixes
- https://github.com/xtermjs/xterm.js/releases/tag/5.3.0:
  - The default DOM-based renderer is significantly faster (not used in JupyterLab)
  - Smooth scroll improvements (not enabled it JupyterLab)
  - `minimumContrastRatio` improvements (not enabled in JupyterLab)
  - 12 bug fixes
- https://github.com/xtermjs/xterm.js/releases/tag/5.4.0:
   - 22 bug fixes
- https://github.com/xtermjs/xterm.js/releases/tag/5.5.0:
   - fix for DOM renderer blink animation
   - improve detection of node and browser - this was a blocker for us

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
Blocked on:
- https://github.com/xtermjs/xterm.js/issues/4995

depending on response we might decide to stick to 5.3.x in the meantime

**Comment by krassowski** [comment]
The patch that we need was merged but it is targeting 5.5.0 which is due by May 03, 2024 (https://github.com/xtermjs/xterm.js/milestone/79) so it might not make it for our 4.2.0 release.

**Comment by krassowski** [comment]
On the other hand, we could upgrade to 5.5.0 beta now, and delay our planned 4.2.0 release by two days to get the final 5.5.0 in.

**Comment by krassowski** [comment]
So thanks to an early 5.5.0 release we can include it before beta1 :tada:

**Review by fcollonval — APPROVED** [review]
Thanks @krassowski

**Pull request merged**
