### PR TITLE
Fixes Ctrl+Shift+ArrowLeft/Right shortcuts edit mode

### LINKED ISSUE #11817: Ctrl+Shift+ArrowLeft/Right shortcuts broken in edit mode
## Description

PR #11615 breaks two (really useful) codemirror shortcuts: Ctrl+Shift+ArrowLeft/Right should move the selection to the previous/next word border.

## Reproduce

1. Create a code or markdown cell with a few words
2. Go to edit mode
3. Hit Ctrl+Shift+ArrowLeft or ArrowRight
4. The selection does not change. Instead, all headings collapse / expand if there are heading cells.

## Expected behavior

Ctrl+Shift+ArrowLeft/Right should move the selection to the previous/next word border as in almost all modern editors.

### PR DESCRIPTION
**Pull request by schmidi314**
## References

Fixes #11817

## Code changes

Changed selectors in default keyboard shortcuts.

## User-facing changes

only the bugfix

## Backwards-incompatible changes

none

### CODE REVIEW

**Comment by schmidi314** [comment]
@meeseeksdev tag bugfix

**Comment by schmidi314** [comment]
@meeseeksdev tag bug

**Review by fcollonval — APPROVED** [review]
Thanks a lot for spotting and patching this one @schmidi314

**Comment by jtpio** [comment]
Thanks!

**Comment by jtpio** [comment]
@meeseeksdev please backport to 3.3.x

**Comment by schmidi314** [comment]
@fcollonval @jtpio Is the backporting correct? This bug was introduced with #11615 (I just fixed my own mess) but this one wasn't backported. OK, I only mentioned the bug origin in the very beginning of the issue -- maybe not the best place.

**Comment by jtpio** [comment]
Ah ok thanks for @schmidi314 for the extra context.

If the original change is not on `3.3.x` then we can skip the backport.

**Pull request merged**
