### PR TITLE
[2.2.x] Use block display in Notebook panel

### PR DESCRIPTION
**Pull request by echarles**
Fixes https://github.com/jupyterlab/jupyterlab/issues/8967 for 2.2.x branch

We may also open this for master if we have positive benchmarks results.

### CODE REVIEW

**Comment by echarles** [comment]
cc/ @afshin

**Review by saulshanabrook — CHANGES_REQUESTED** [review]
This looks odd to me in chrome and firefox, the cell indicator is on the right
Screen Shot 2020-10-01 at 1 51 42 PM

**Comment by echarles** [comment]
@saulshanabrook I will check and bring a fix for that by tomorrow. Thx for looking at this.

**Comment by echarles** [comment]
@saulshanabrook I have pushed a fix for this. On my env, notebook is rendered like before on chrome and firefox.

**Review by saulshanabrook — APPROVED** [review]
Works for me, thanks!

**Comment by echarles** [comment]
Looks like we had test failures - Checking this now.

```
  @jupyterlab/notebook
    NotebookActions
      #runAndAdvance()
        ✕ should clear the existing selection
        ✕ should change to command mode
```

**Comment by echarles** [comment]
Oops, those exact same errors were already present in the PR merged prior to the merge of this one, see https://github.com/jupyterlab/jupyterlab/pull/9003 and the CI run on https://github.com/jupyterlab/jupyterlab/pull/9003/checks?check_run_id=1111719238

So the errors are unrelated to the changes of this PR.

```Summary of failed tests

test/actions.spec.ts
  @jupyterlab/notebook
    NotebookActions
      #run()
        ✕ should render all markdown cells on an error
  @jupyterlab/notebook
    NotebookActions
      #runAndInsert()
        ✕ should render all markdown cells on an error
  @jupyterlab/notebook
    NotebookActions
      #runAll()
        ✕ should run all of the cells in the notebok
```

cc/ @saulshanabrook @jasongrout

**Pull request merged**
