### PR TITLE
Console kernel-switching fixes

### PR DESCRIPTION
**Pull request by afshin**

### CODE REVIEW

**Comment by blink1073** [comment]
Some problems persist when you switch kernel and hit cancel.  It looks like the kernel is shut down, but then we still try and send values to the inspector because it is not disposed, yielding an "Error: Kernel is dead" error.

**Comment by afshin** [comment]
@blink1073 Good call. That issue is resolved now.

**Comment by blink1073** [comment]
The current session should not be listed in the dialog, and "switching" to it kills the kernel.

**Comment by blink1073** [comment]
Excellent, thanks!

**Pull request merged**
