### PR TITLE
Allow specifying the root name in JSON repr

### PR DESCRIPTION
**Pull request by dhirschfeld**
Initial attempt to implement nteract/nteract#2580 in JupyterLab.

~~~...unfortunately, it doesn't seem to work :(~~~

### CODE REVIEW

**Comment by dhirschfeld** [comment]
> *Development mode ensures that you are running the JavaScript assets that are built in the dev-installed Python package.*

If only I had read [that sentence](https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md#run-jupyterlab) to start with! :sob:

**Comment by dhirschfeld** [comment]
This appears to work now:

image

Let me know if there are any changes you'd like - it's my first foray into JS/TypeScript so I'm not confident it's the best way to go about it - just happy it works! :smile:

**Comment by dhirschfeld** [comment]
Looks like one test run failed:

image

I'm not too sure why - is that a valid failure?

**Comment by dhirschfeld** [comment]
Looks like it was a random failure.

**Comment by dhirschfeld** [comment]
If there's a patch release imminent it would be great to get this very minor PR in!

c.c. @gnestor

**Comment by gnestor** [comment]
If we pass the `hideRoot` prop to `JSONTree`, it looks like this:

image

**Comment by gnestor** [comment]
This looks pretty good:

image

The last thing you may want to do is provide a default value for `root` in ipython. You can see that we're doing that for `expanded` already: https://github.com/ipython/ipython/blob/master/IPython/core/display.py#L818

**Pull request merged**
