### PR TITLE
Dependabot/npm and yarn/semver regex 3.1.3

### PR DESCRIPTION
**Pull request by Codes-Exe**

### CODE REVIEW

**Comment by fcollonval** [comment]
@Codes-Exe would you mind providing more background on this PR reason.

**Comment by Codes-Exe** [comment]
> @Codes-ExeBu halkla nedeni hakkında daha fazla bilgi gibi bir görünüm müsünüz?

I am sometimes surprised when Mr. fcollonval is trying to close security vulnerabilities.

**Comment by fcollonval** [comment]
I'm not trying to close this; I'm trying to understand the rational for this PR because dependabot is not reporting any security issues on master.

**Comment by fcollonval** [comment]
As the [contribution guide](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/contributing.rst) is stating:

> Generally, an issue should be opened describing a piece of proposed work and the issues it solves before a pull request is opened.

**Comment by Codes-Exe** [comment]
> [Katkı kılavuzunun](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/contributing.rst) belirttiği gibi :
> 
> > Genel olarak, bir çekme talebi açılmadan önce, önerilen bir çalışmayı ve çözdüğü sorunları açıklayan bir konu açılmalıdır.

ok i'll be explanatory thanks

**Pull request closed without merging**
