### PR TITLE
Revert "Merge branch 'commenting-extension' into master"

### PR DESCRIPTION
**Pull request by jtpio**
This reverts commit 740f7796b6aa7b2f78d87b88961dbf348ed9fbb0, reversing
changes made to 6b79e85a380a631c0b71d74162c041d8c175f0e7.

## References

This reverts https://github.com/jupyterlab/jupyterlab/commit/740f7796b6aa7b2f78d87b88961dbf348ed9fbb0 which appears to have been pushed by mistake?

This should fix master.

cc @jweill-aws @echarles 

## Code changes

Revert commit.

### CODE REVIEW

**Comment by jtpio** [comment]
@jweill-aws this looks related to bringing the `jupyterlab-comments` into core? As mentioned in https://github.com/jupyterlab/jupyterlab/issues/12032.

Probably we'll want to discuss this in an issue first (for example in the team compass), and then bring it in with a PR (keeping the commit history if possible).

**Review by echarles — APPROVED** [review]
@jtpio @jweill-aws LGTM

**Review by fcollonval — APPROVED** [review]
Thanks a lot @jtpio

**Comment by jweill-aws** [comment]
So sorry about this! This should have been merged into `jweill-aws/jupyterlab:master`, not `jupyterlab/jupyterlab:master`. Thank you for reverting my mistake.

**Pull request merged**
