### PR TITLE
New multi line search

### PR DESCRIPTION
**Pull request by c00kie123**
## References
#13801 

## Code changes

At `packages/documentsearch/src/searchmodel.ts`, I added the `m` flag to  `const flag = caseSensitive ? 'g' : 'gi';`
forming: `const flag = caseSensitive ? 'gm' : 'gim';`. This will enable multi-line search, allowing the regular expression to match across multiple lines

At `packages/fileeditor/src/searchprovider.ts` and `packages/notebook/src/searchprovider.ts`, I removed the line ` return selection?.search(/\r?\n|\r/g) === -1 ? selection : ;''` By removing this line, the function will always return the selection regardless of whether it is a single-line or multi-line selection

At `packages/documentsearch/src/searchview.tsx`, I replaced `<input `with `<textarea`

### CODE REVIEW

**Comment by krassowski** [comment]
From the failing build logs, the types need to be updated in a few places to reflect the use of `HTMLTextAreaElement`:

```
      ../documentsearch/src/searchview.tsx(93,39): error TS2345: Argument of type 'ChangeEvent<HTMLTextAreaElement>' is not assignable to parameter of type 'ChangeEvent<HTMLInputElement>'.
        Type 'HTMLTextAreaElement' is missing the following properties from type 'HTMLInputElement': accept, align, alt, capture, and 26 more.
      ../documentsearch/src/searchview.tsx(94,41): error TS2345: Argument of type 'KeyboardEvent<HTMLTextAreaElement>' is not assignable to parameter of type 'KeyboardEvent<HTMLInputElement>'.
        Type 'HTMLTextAreaElement' is not assignable to type 'HTMLInputElement'.
      ../documentsearch/src/searchview.tsx(96,9): error TS2322: Type 'RefObject<HTMLInputElement>' is not assignable to type 'LegacyRef<HTMLTextAreaElement> | undefined'.
        Type 'RefObject<HTMLInputElement>' is not assignable to type 'RefObject<HTMLTextAreaElement>'.
          Type 'HTMLInputElement' is missing the following properties from type 'HTMLTextAreaElement': cols, rows, textLength, wrap
      ../documentsearch/src/searchview.tsx(147,48): error TS2345: Argument of type 'KeyboardEvent<HTMLTextAreaElement>' is not assignable to parameter of type 'KeyboardEvent<HTMLInputElement>'.
      ../documentsearch/src/searchview.tsx(148,39): error TS2345: Argument of type 'ChangeEvent<HTMLTextAreaElement>' is not assignable to parameter of type 'ChangeEvent<HTMLInputElement>'.
```

**Comment by andrii-i** [comment]
> Oh thanks for the info! which files do I need to do the update?

Hey @c00kie123! Files you need to are listed in error logs that @krassowski posted

**Comment by c00kie123** [comment]
@krassowski Do I have to change every relevant Input element I find in `searchview.tsx`, like line 56 `inputRef: React.RefObject<HTMLInputElement>;` , to` inputRef: React.RefObject<HTMLTextAreaElement>;`.
Line 60:
```
onKeydown: (e: React.KeyboardEvent<HTMLInputElement>) => void;
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
```
to
```
onKeydown: (e: React.KeyboardEvent<HTMLTextAreaElement>) => void;
  onChange: (e: React.ChangeEvent<HTMLTextAreaElement>) => void;
```
and more. If so, I can proceed to do the changes

**Comment by krassowski** [comment]
Yes. I would recommend following the contribution guideline from documentation to setup a local environment where you can test the  changes by first rebuilding jupyterlab code `jlpm build` and then starting it in dev mode (`jupyter lab --dev-mode`).

**Comment by andrii-i** [comment]
@c00kie123 also wanted wanted to note that you have created a copy of main jupyterlab codebase in your fork [c00kie123:new-multi-line-search](https://github.com/c00kie123/jupyterlab/tree/new-multi-line-search) so feel free to experiment and change whatever you want. If you break something you can roll the changes back or make a new fork

**Comment by c00kie123** [comment]
@krassowski Take a look at the updated searchview.tss

**Comment by krassowski** [comment]
I have fixed the copy-paste issues in cd10e0e and adjusted styling and behaviour for textarea in 259a97b, but this PR still needs tests to ensure it works correctly. Searching definitely works, but it seems that there might be an issue with replace.

I will look at other search bugs first before coming back to this one.

**Comment by krassowski** [comment]
but please update galata snapshots

**Comment by krassowski** [comment]
Kicking CI

**Comment by krassowski** [comment]
Note: the apparent increase in font size seen e.g. on:

Screenshot from 2023-02-20 22-50-37

is not really an increase in `font-size` but a result of application of `font-family` which on CI ends up using Ubuntu font which is slightly larger.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by krassowski** [comment]
Thanks for your contribution on this one @c00kie123! I hope you had an opportunity to follow along on the additional bits that needed to be modified.

Thanks for the merge Jeremy!

**Pull request merged**
