### PR TITLE
[WIP] Extension Resolution

### LINKED ISSUE #1011: Handle compatibility of Lab Extensions
## Problem

Currently, if a Lab extension is built against an incompatible version of JupyterLab, it causes the Application to fail to load with an error similar to the one below due to incompatible versions of `Token` objects.

screen shot 2016-09-29 at 1 26 26 pm
## Proposal
- Special case JupyterLab and perhaps Phosphor in the JupyterLab builder script to be version-less (and perhaps not include them in the bundle).
- Add the JupyterLab semver data to the manifest file, so we can determine whether it is a compatible extension.  
- Force JupyterLab itself to a `devDependency` or a `dependency` of the extension that is being built, and throw an error if it does not exist.
## Precedent

Both VSCode and Atom have an `"engines"` field in their `package.json` to specify a semver range of compatible versions of the application, and that code is expected to be provided by the environment.

https://code.visualstudio.com/docs/extensionAPI/extension-manifest
http://flight-manual.atom.io/hacking-atom/sections/package-word-count/

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #1011.

- Adds dependency resolution of extensions in Python.  Updates the WebPack plugin to output the package structure and a list of included modules in the manifest, and adds a separator comment to the bundle.
- The builder script starts with the base JupyterLab package and handles conflict resolution.  We then add the lab extensions in alphabetical order and reject them if they result in conflicts.
If more than one version of a package is required, we attempt to find the maximum version that satisfies all semver constraints.  If no single package can be found, we accept the conflict with a warning, unless the package has been marked in `package.json` as `"jupyterlab": { "singletonPackages": [] }`.
- We then assemble the singular output bundle and store the bundle and its metadata in `share/jupyter`.
- Adds a `jupyter build_lab` command that is automatically run at startup when needed.  It is needed if the hash of the main build changes or the hashes of the installed lab extensions change. 

Status: All JavaScript parts are done, and the Python conflict algorithm is done.  Final steps are to complete the builder script and update documentation.

### CODE REVIEW

**Comment by blink1073** [comment]
For discussion, how should libraries be marked as singletons?  We want a method to mark both our our package and one or more package dependencies as singletons.  Proposal: add a `jupyterlab`: `singletons`: []` entry.

**Comment by blink1073** [comment]
cc @ellisonbg @jasongrout

**Comment by ellisonbg** [comment]
Yes, I think we should have a config key on the config file to specify that. But we might want to be more descriptive than `singletons` as there may be other singletons in the overall app.

**Comment by blink1073** [comment]
Implemented as `singletonPackages`.  The basic algorithm is done.  The remaining task is be to assemble the actual code blocks, removing duplicates and the ones that were marked as `to_remove`.

**Comment by blink1073** [comment]
Plan is to start with the base tree and then attempt to merge each lab extension tree in alphabetical order.  If a merge fails, reject the extension and move on.

**Comment by blink1073** [comment]
Closing in light of #2011.

**Pull request closed without merging**
