### PR TITLE
Drop `StatusMessage` which is dead code

### PR DESCRIPTION
**Pull request by krassowski**
## References

Part two for #14711

## Code changes

Removes `StatusMessage` which is not used in core and will not be used downstream in LSP extension since a better alternative (`Notification`) is now available for statuses which were previously (poorly) communicated on status bar.

## User-facing changes

None

## Backwards-incompatible changes

This class was not documented and we can say it was not a part of public API.

### CODE REVIEW

**Review by fcollonval — COMMENTED** [review]
Candid question, is the LSP API allowed to be changed within a Lab major version? I forget what was decided.

**Comment by krassowski** [comment]
Most of the public LSP APIs are tagged with alpha/experimental so the answer I would give: yes if tagged as such. But in this case I think this was never a part of the API - it is not exported from `@jupyterlab/lsp`, undocumented, and really not relevant to LSP itself - so I would suggest we remove it before someone starts using it. Unless I am missing something.

**Review by fcollonval — APPROVED** [review]
Thanks @krassowski 

I guess it will be better to backport it to 4.0.x to limit the risk of use?

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 4.0.x

**Pull request merged**
