### PR TITLE
Vertical notebook cell prompts on mobile

### PR DESCRIPTION
**Pull request by jtpio**
## References

Mobile friendly JupyterLab: https://github.com/jupyterlab/jupyterlab/issues/3275

Fixes https://github.com/jupyterlab/jupyterlab/issues/1614

Alternative to https://github.com/jupyterlab/jupyterlab/pull/9433

This also looks closer to the classic notebook (parity).

## Code changes

CSS changes.

### Before

image

### After

image

### CODE REVIEW

**Comment by telamonian** [comment]
nice design, and a very nice tradeoff of (plentiful) vertical space for (scarce) horizontal space on mobile. +1

**Comment by goanpeca** [comment]
Thanks @jtpio for working on this :) 

Indeed a great improvement! My nitpick would be that not having the left borders align looks a bit off.

Screen Shot 2020-12-14 at 11 48 02

Screen Shot 2020-12-14 at 11 48 59

**Comment by telamonian** [comment]
@goanpeca I agree that having the left side of the square bracket and the left side of the cell inbox box *almost*-but-not-quite aligned feels a little clashing. But I'm not 100% on having them be perfectly aligned either. That seems a bit visually monotonous/confusing to me. 

How about we make the execution count and the cell input a bit more visually distinct here by giving them each distinct margins, maybe something like:

image

**Comment by goanpeca** [comment]
>. But I'm not 100% on having them be perfectly aligned either. That seems a bit visually monotonous/confusing to me.

Thanks for the input @telamonian, makes sense as well.

@isabela-pf we need your help and input :)

**Comment by jtpio** [comment]
Thanks all for the feedback.

I'm also a bit bothered by this "almost aligned" prompt, so happy to tweak that!

**Comment by isabela-pf** [comment]
Since the main argument in favor of a indented/unaligned prompt and its cell is how it may help provide more spacing and help each area be visually distinct, I mocked up a few cells in a row.

1. This is the aligned prompt and cell
0-1 long

2. This is the indented/unaligned prompt and cell
0-4 long

I would say both options work. Personally, I think I prefer the aligned prompt and cell because it's easier on my eyes to follow. I also think each cell will feel distinct enough because everything to the right of the the prompt is white space, providing a good buffer between cells. 

Even though it is a small amount, the indented/unaligned prompt and cell does leave a less space for the cell. As discussed above, every little bit of horizontal space is needed in mobile so the aligned might make sense.

**Comment by jtpio** [comment]
Adding to the [3.1](https://github.com/jupyterlab/jupyterlab/milestone/58) to consider it as an incremental UI / UX improvement.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Pull request merged**
