### PR TITLE
Add missing styles to npm packages

### LINKED ISSUE #2001: Some packages do not publish their styles
One example is `apputils`: https://github.com/jupyterlab/jupyterlab/tree/master/packages/apputils

There are likely others.

This means the third parties can't use the packages as libraries because they can't import the styles.

### PR DESCRIPTION
**Pull request by vidartf**
Fixes #2001.

### CODE REVIEW

**Comment by vidartf** [comment]
I went through all the directories in `packages`, and for all packages with a `style` sub-directory checked if there was a corresponding entry in `package.json`.

**Comment by afshin** [comment]
I was just wondering if all styles are basically "public API" or if some styles are simply there for the module to work. But I guess one byproduct of making public things we can inherit from is that the styles they were using need to be accessible regardless of the original thought process of the author.

**Comment by sccolbert** [comment]
It doesn't matter if they are public or private. They have to be published in order for the package to be used as a library.

**Comment by sccolbert** [comment]
@vidartf did you happen check if the `style` dirs contained anything else that needed to be published? For example, some of the `style` dirs have `images` sub dirs and other content which wont be included with a `style/*.css` glob alone.

**Comment by vidartf** [comment]
@sccolbert Yup :)

**Comment by sccolbert** [comment]
👍

**Comment by afshin** [comment]
@sccolbert That's true in our case, but you could have a bundling stage before publishing which puts the CSS assets into a `.js` file ... so it's not always the case that the CSS would have to be published.

**Comment by sccolbert** [comment]
@afshin valid point :)

**Comment by sccolbert** [comment]
Thanks!

**Pull request merged**
