### PR TITLE
Enable using federated extensions in dev mode when a flag is set.

### LINKED ISSUE #9235: Enable dynamic?federated extensions in dev mode
### Problem

For now, the dynamic?federated extensions are forced-disabled in dev_mode

https://github.com/jupyterlab/jupyterlab/blob/f7cb7b5e208d732c8d841ae84d219cbebc97b22a/jupyterlab/labapp.py#L618-L619

Sometimes, like the work done in https://github.com/jupyterlab/jupyterlab/issues/8804, we need those extensions enabled in dev mode

### Proposed Solution

Add a setting/flag like `--extensions-dev-mode` to keep the extensions enable in dev mode,.

### PR DESCRIPTION
**Pull request by jasongrout**
## References

Fixes #9235

## User-facing changes

This is a much easier way to develop extensions against a development install of JupyterLab than the current add:sibling approach. While it may not work all the time, I think it will be helpful sufficiently often that we should make it possible.

### CODE REVIEW

**Comment by jtpio** [comment]
Does that mean linking core packages with `yarn` as mentioned in https://github.com/jupyterlab/jupyterlab/issues/9235#issuecomment-718242992 is not necessary?

Or the federated extension should be built using the dev version of lab to properly populate the shared packages.

**Comment by jasongrout** [comment]
> Does that mean linking core packages with `yarn` as mentioned in [#9235 (comment)](https://github.com/jupyterlab/jupyterlab/issues/9235#issuecomment-718242992) is not necessary?

It depends. If no linking is done, the federated extensions will be built against existing package versions, but will use the dev versions at runtime. If the APIs change, that would be a problem. To fully test, you would indeed need to do some sort of linking so that typescript could do its compile-time checking properly.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by jasongrout** [comment]
I added some help text warning that federated extensions may not work in a dev install if they were compiled against published packages.

**Pull request merged**
