### PR TITLE
Convert to Multiple Packages

### PR DESCRIPTION
**Pull request by blink1073**
cf #1773.

### CODE REVIEW

**Comment by jasongrout** [comment]
@ellisonbg - I think we're still seeing you be lightning fast at applying that `in progress` label (see above) :). I thought you turned that off a while ago. Can you check it?

**Comment by blink1073** [comment]
I think we should separate plugins from the source packages.  Plugins come with a lot of dependencies that are not essential for the use of the source code.  For instance, we have `clipboard` that itself would only depend on `@phosphor/coreutils`, but because it is a plugin, it comes with all of `@phosphor` as well as `@jupyterlab/application`.  I suggest a `packages/` directory, and a `plugins/` directory where the names are `plugin-foo`.  We could then move the clipboard functionality into `@jupyterlab/domutils` and have `@jupyterlab/plugin-clipboard`.

**Comment by jasongrout** [comment]
This is starting to explode the number of packages, and puts us right back where we started in the beginning with core libraries and jlab plugin packages. On the other hand, that's exactly what we did with widgets - a core reusable library, and then various packages integrating that core library into different frameworks.

Given the tools we have now (e.g., lerna), do you see the huge number of packages working out better than it did the other year?

**Comment by sccolbert** [comment]
@jasongrout Yes. Lerna really helps with this. The pain of lots of small packages was entirely to do with them being spread across multiple repos, which prevented the sharing of the build system, and the inability to make changes to multiple (dependent) packages simultaneously. Lerna fixes all of that.

**Comment by blink1073** [comment]
Additionally, we'd preserve the convention that a package exports all of it's modules.

Here's a proposed breakdown for core packages:
coreutils - utilities that are usable from node
domutils - utilities related to the dom but not widgets
helperwidgets (name suggestions welcome) - widgets that are used throughout the app

coreutils - activitymonitor, dates, observable*, etc.
domutils - clipboard, commandlinker, hoverbox, etc.
helperwidgets - hoverwidget, dialog, iframe, vdom, etc.

The existing plugins would all be prefixed as `plugin/plugin-foo` packages.

**Comment by sccolbert** [comment]
> The existing plugins would all be prefixed as plugin/plugin-foo packages.

Do you mean `plugins/plugin-foo`? (missing 's')

**Comment by blink1073** [comment]
Yep, that.

**Comment by blink1073** [comment]
Either way, I think it makes sense to refactor the `common` parts first, so we don't have to release a `common` package that we'll immediately deprecate.

**Comment by blink1073** [comment]
Closing in favor of fixing up the source file alignment first.

**Pull request closed without merging**
