### PR TITLE
fixes #4609 - Inconsistent font size of codeblocks in titles of markdown documents.

### LINKED ISSUE #4609: Inconsistent font size of codeblocks in titles of markdown documents.
Font size of codeblocks of jupyterlab is inconsistent with jupyter notebook.

In jupyter notebook the font size of codeblock matched the title size, however jupyterlab does not.

Here's the following markdown rendered in both jupyterlab and jupyter notebook.

```markdown
# Hello `Codeblock`!
## Hello `Codeblock`!
### Hello `Codeblock`!
#### Hello `Codeblock`!
##### Hello `Codeblock`!
```

jupyterlab_codeblock

jupyter_notebook_codeblock

Jupyter versions 

```
jupyter==1.0.0
jupyter-client==5.0.0
jupyter-console==5.1.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.3.3
jupyter-core==4.3.0
jupyter-highlight-selected-word==0.1.0
jupyter-latex-envs==1.4.1
jupyter-nbextensions-configurator==0.2.8
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5
```

### PR DESCRIPTION
**Pull request by jirivrany**

### CODE REVIEW

**Comment by jzf2101** [comment]
@jasongrout @tgeorgeux do either of you have any thoughts before we merge?

**Comment by jirivrany** [comment]
Thanks @gnestor, you are right the inherit is a better option. 

Currently, there is a following set of rules for given selector combination pre and code 
```
.jp-RenderedHTMLCommon pre,
.jp-RenderedHTMLCommon code {
  border: 0;
  background-color: var(--jp-layout-color0);
  color: var(--jp-content-font-color1);
  font-family: var(--jp-code-font-family);
  font-size: var(--jp-code-font-size);
  line-height: var(--jp-code-line-height);
  padding: 0px;
}
```
And so It can be changed to:
```
.jp-RenderedHTMLCommon pre,
.jp-RenderedHTMLCommon code {
  border: 0;
  background-color: var(--jp-layout-color0);
  color: var(--jp-content-font-color1);
  font-family: var(--jp-code-font-family);
  font-size: inherit;
  line-height: var(--jp-code-line-height);
  padding: 0px;
}
```
I did a test with normal code block and the font-size looks fine.
screen_fixed

**Comment by gnestor** [comment]
Looks good @jirivrany 👍

I'm restarting the Appveyor build because it looks like it failed due to an unrelated error

**Comment by jirivrany** [comment]
Thank you @tgeorgeux I'm glad to help. Is there anything that I can do with the failing CI @gnestor ? Integrity check on my machine is ok and locals test are passing too.

**Comment by gnestor** [comment]
We are experiencing an issue with Appveyor that's affecting all builds right now. I restarted the Travis build because that looks like it's unrelated.

**Comment by gnestor** [comment]
@jirivrany We just fixed the Appveyor issue. Can you rebase from current master and push?

**Comment by gnestor** [comment]
@jirivrany I just fixed the rebase 👍

**Comment by jirivrany** [comment]
@gnestor  thank you. I'm not very experienced with rebasing, usually I use only normal merge. I used following commands:
```
git rebase upstream/master
git pull 
git push
```
What is the correct sequence? For the next time.

**Comment by jzf2101** [comment]
Are we ready to merge?

**Comment by ian-r-rose** [comment]
Yep, pending CI we should be good.

**Comment by ian-r-rose** [comment]
@jirivrany A rebase typically goes like:
```bash
git checkout master
git pull upstream master
git checkout feature-branch
git rebase master
```
This replays the commits on `feature-branch` on top of `master`. If you are lucky there will not be any conflicts. If there are conflicts, you will need to resolve them by hand.

**Comment by jirivrany** [comment]
Thanks @ian-r-rose - will do it next time.

**Comment by jzf2101** [comment]
Thx again @jirivrany

**Pull request merged**
