### PR TITLE
Added split-cell multicursor

### LINKED ISSUE #7207: Make split cell work for multicursor
Right now, splitting cells only works for one cursor at a time. It would be good if you could split the cells in multiple spots.

Here's a PR for the same issue for jupyter notebooks https://github.com/jupyter/notebook/pull/4824

### PR DESCRIPTION
**Pull request by bthayer2365**
## References

fixes #7207
Same as https://github.com/jupyter/notebook/pull/4824

## Code changes

Prior code only split using the active cursor while this takes into account both cursors and selections. Essentially, it uses cursors as delimiters and ensures that text in selections ends up in the same cell.

Similar to before, the last cell created contains the output of the split cell and gets selected after the operation is complete. The action is also undoable, just like before.

## User-facing changes

The user can now use multicursor to split the cell in multiple locations.

### CODE REVIEW

**Comment by bthayer2365** [comment]
Sorry for the force push, I accidentally added a `.rej` file that was automatically created

**Comment by blink1073** [comment]
Thanks again, works as advertised!

**Comment by blink1073** [comment]
@meeseeksdev backport to 1.x

**Comment by bthayer2365** [comment]
Happy to help!

**Pull request merged**
