### PR TITLE
Modular running extension

### LINKED ISSUE #5728: Make running extension support third-party sessions
[Running extension](https://github.com/jupyterlab/jupyterlab/tree/6004961882cff0fc2a3bc75361fceef645a3a4a1/packages/running) is showing running kernel and terminal sessions.
I'm developing an extension integrating... sort of remote desktop sessions into JupyterLab and would like to add them to the Running tab, but the list of session types is currently hardcoded in the running extension.

### PR DESCRIPTION
**Pull request by recamshak**
Fixes #5728

I didn't know about the above issue and the related PR https://github.com/jupyterlab/jupyterlab/pull/4724 until I was ready to submit the PR. However #4724 is more ambitious and AFAIU it does not directly solve this issue. So maybe this PR is still relevant?

With this PR it should be easy to add a section in the running panel for any extension.

### CODE REVIEW

**Comment by vidartf** [comment]
Just to address this: I think this is a good thing! That being said, there is currently CI issues that are delaying review/merge of a bunch of PRs across the repo that we're working to fix. So don't lose heart over the delays :)

**Comment by vidartf** [comment]
@recamshak I think if you rebase on / merge master to resolve the merge conflicts, the CI can now complete, and people will have time to review :)

**Comment by Queuecumber** [comment]
@vidartf Since the author is unresponsive I took over this PR at #6895 please have a look there

**Comment by jasongrout** [comment]
To be fair, it's been months since they've had input from reviewers, and they've only had 24 hours to respond.

**Comment by Queuecumber** [comment]
Whichever one gets merged is a win. Since we haven't heard from @recamshak since Feb and I can work on this as much as I want this removes uncertainty for me.

**Comment by jasongrout** [comment]
> Since we haven't heard from @recamshak since Feb and I can work on this as much as I want this removes uncertainty for me.

Yes, please, go ahead. And @recamshak, thanks for your work on this, sorry for the delays while we were focusing on 1.0 issues, and please let us know if you want to help with this moving forward.

**Comment by recamshak** [comment]
@Queuecumber @jasongrout Sorry for the late reply. @Queuecumber Thank you for you work on solving the merge issues!

**Comment by jasongrout** [comment]
Closing, replaced by #6895 which preserves these commits and adds the merge commit to bring it up to the current codebase.

**Pull request closed without merging**
