### PR TITLE
Add ability to hide the header bar in simple mode

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Partially addressed https://github.com/jupyterlab/jupyterlab/issues/2031
Fixes https://github.com/jupyterlab/jupyterlab/issues/9135

toggle_header

## Code changes

A new flag keeping track of the visibility status of the header bar in simple has been added to the shell as well as a new command to add that feature in the `View->Appearance` menu.

The skip link widget is placed directly on the shell root layout as we don't want to hide it with the header bar.
This required to use a wrapper to be able to use the same position and styling.

## User-facing changes

Ability to show/hide the header bar in simple mode

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thank you!

**Comment by jtpio** [comment]
Nice!

**Comment by jtpio** [comment]
Looks like the check release step is also failing on other PR: https://github.com/jupyterlab/jupyterlab/pull/11108/checks?check_run_id=3660731054

**Comment by jtpio** [comment]
Looks pretty good on Binder with a single notebook open:

image

Now if we add a way to set a max width to the main document, it will be a good step towards https://github.com/jupyterlab/jupyterlab/issues/9869

**Comment by fcollonval** [comment]
> Now if we add a way to set a max width to the main document, it will be a good step towards #9869

:+1:

**Comment by fcollonval** [comment]
The check release and benchmark tests are failing due to npm unable to install some packages. The underlying image has probably been updated...

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
> The check release and benchmark tests are failing due to npm unable to install some packages. The underlying image has probably been updated...

Looks like this issue is relevant: https://github.com/Automattic/node-canvas/issues/1902

image

**Comment by jtpio** [comment]
Looks like check release passes after a restart:

image

**Comment by jtpio** [comment]
CI all green, this should be good to go!

**Pull request merged**
