### PR TITLE
Loosen pin on jupyter-packaging

### PR DESCRIPTION
**Pull request by afshin**
## References
Fixes https://github.com/jupyterlab/jupyterlab/issues/9992

## Code changes
Loosens pin on `jupyter_packaging`, since the API will not change until 1.0.

## User-facing changes
None

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by jasongrout** [comment]
> Loosens pin on `jupyter_packaging`, since the API will not change until 1.0.

Plus a bunch of changes about testing browsers? Are those intended for this PR?

**Comment by afshin** [comment]
> Plus a bunch of changes about testing browsers? Are those intended for this PR?

D'oh! Sorry about that. I updated the PR.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.0.x

**Pull request merged**
