### PR TITLE
Make override urls configurable

### PR DESCRIPTION
**Pull request by blink1073**
Follow up to https://github.com/jupyterlab/jupyterlab/pull/5462

### CODE REVIEW

**Comment by blink1073** [comment]
cc @eoinmurray

**Comment by blink1073** [comment]
Released as 0.35.2

**Comment by eoinmurray** [comment]
Still isn't working for me, I think its related to

https://github.com/jupyterlab/jupyterlab_server/blob/master/jupyterlab_server/handlers.py#L206

```
    if config.static_dir:
        public_path = ujoin(base_url, config.public_url + '(.*)')
```

Since base_url is always '/' even if I set it to "" using `--NotebookApp.base_url=""` so my public url always starts with '/' and then doesnt work?

**Comment by eoinmurray** [comment]
I always get the following if I set the override_static_url to anything:

```
⚡ ~: jupyter lab --dev-mode --no-browser --LabApp.override_static_url='https://<something>.cloudfront.net' --NotebookApp.base_url=""
```

screen shot 2018-10-17 at 19 44 29

**Comment by vidartf** [comment]
Normally, I would debug such issues by the "Network" tab in the developer tools. Then you can see the content of the reply from the static url. Maybe the reply is malformed?

**Comment by eoinmurray** [comment]
Indeed, no matter what I set `--LabApp.override_static_url` to the response for the vendors.js and main.js files is the html content of the index, so its pointing to the wrong place. So the reponse is malformed, but it seems not to be fetching the correct links.

screen shot 2018-10-18 at 12 06 59

**Comment by eoinmurray** [comment]
Exact same thing happens if I point the static url to itself on localhost, `--LabApp.override_static_url='http://localhost:8888'`

**Comment by eoinmurray** [comment]
None of these work either, same error

- `--LabApp.override_static_url='localhost:8888'`
- `--LabApp.override_static_url='localhost:8888/'`
- `--LabApp.override_static_url='localhost:8888/lab/static'`
- `--LabApp.override_static_url='localhost:8888/lab/static/'`
- `--LabApp.override_static_url='http://localhost:8888'`
- `--LabApp.override_static_url='http://localhost:8888/'`
- `--LabApp.override_static_url='http://localhost:8888/lab/static'`
- `--LabApp.override_static_url='http://localhost:8888/lab/static/'`

**Comment by blink1073** [comment]
Yikes, I'll try that locally when I get back to my dev machine and see if I can write a test case for this as well.

**Comment by blink1073** [comment]
Oof, this is a lot more insidious than I thought.   We need to affect what HTMLWebpackPlugin uses for the paths to the main bundles.  I tried making that `{{page_config.publicUrl}}`, but it adds a slash to that, giving us a url like `/lab/static//main.js` (with two slashes), which the server can't handle.  I can't yet figure out how to fix this behavior...

**Pull request merged**
