### PR TITLE
Update lumino dependencies

### LINKED ISSUE #7762: Allow extension authors to use `lm-` prefix or `p-`
## Description
Take advantage of https://github.com/jupyterlab/lumino/pull/20 to allow extension authors to either keep using `p-` prefixed CSS attributes or use the new `lm-` attributes.

### PR DESCRIPTION
**Pull request by blink1073**
## References
Fixes #7762

## Code changes
Bump lumino dependencies to latest to allow extension authors to switch to the new `lm-` or continue to use `p-` selectors if desired.

## User-facing changes
None

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by jasongrout** [comment]
We should also switch to `lm-` as an example, right?

**Comment by afshin** [comment]
This appears to be working, but I see a split-second huge flash of the launcher icon every time I load/reload the page. I don't know if this is caused by the CSS changes in this PR or if it exists in `master`.

I will investigate later today. If anybody has seen what I'm talking about in another branch, please mention it.

**Comment by jasongrout** [comment]
I asked about that flash in the dev meeting a week or two ago. Max said he
knew what the problem was, that the svg icons had the wrong intrinsic
sizes. Tim said he would also look at it.

**Comment by afshin** [comment]
Thanks Jason, good to know. This is ready for review then. It's :+1: from
me but I added my own changes to it.

**Pull request merged**
