### PR TITLE
Backport of "Allow empty notebook" (#13141)

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Is this ready for review?

**Comment by SylvainCorlay** [comment]
Great!

**Review by hbcarlos — APPROVED** [review]
Thanks, @martinRenou. LGTM!

There are some errors on the dev console but they are not related to this PR. I already opened a PR to fix them here #13308

**Review by fcollonval — APPROVED** [review]
Thanks @martinRenou

**Pull request merged**
