### PR TITLE
Clean up log console api a bit

### PR DESCRIPTION
**Pull request by jasongrout**
## References

CC @mbektasbbg 

## Code changes

This cleans up the api for the log console a bit to conform to conventions we've used elsewhere in the code, such as:

* passing open options, like is done for creating consoles
* simplifying the name `activeSource` to simply `source`
* Move max entry limit to the log itself, not just the viewers
* Fix scrolling to match common log viewer behavior, i.e., when at the bottom, it tails the log, but if you scroll up, it just leaves the scroll position alone.

and many more.

- [x] Remove (or at least make optional non-default) logging of all notebook output
- [x] Check sources by explicitly checking for null rather than using truthiness, to guard against an empty source string (we get better typescript checking by explicitly checking against null)

## User-facing changes

None

## Backwards-incompatible changes

Only in an unreleased package

### CODE REVIEW

**Comment by jasongrout** [comment]
@mbektasbbg - if these look good to you, I'll merge and release a 1.2 release candidate.

**Comment by jasongrout** [comment]
@mbektasbbg - I think the functionality is the same now from the user's perspective. Can you review these changes? I'm happy to hop on a call to go over these together if you'd like.

**Comment by mbektasbbg** [comment]
@jasongrout lets have a call to go over the changes as you suggested

**Comment by jasongrout** [comment]
Yeah, I tried to make things consistent with how we are using that info color elsewhere, but it doesn't look so good in a dark theme.

**Comment by jasongrout** [comment]
Thanks @mbektasbbg!

Would you mind looking at the last two commits as well? I simplified the status bar components, and switched the highlight colors to the brand colors.

It seems that it is really hard to highlight something in the status bar because the status bar does not use straight CSS, so you don't get good CSS inheritance.

**Comment by mbektasbbg** [comment]
hi @jasongrout thanks for further enhancements, flash color is much better now. However, there is an issue I started noticing with the flash state. to reproduce:
- When log console is open, generate new messages from notebook. Log count increases but doesn't flash
- Now close log console, status bar now shows flashed state. It shouldn't, because user already saw the messages

**Comment by telamonian** [comment]
@jasongrout Your use of `DefaultIconReact` looks correct to me. You'll probably want to inspect the icon live and make sure the appearance/style/CSS is all correct.

The only thing to note is that `DefaultIconReact` will be deprecated by the work being done in #7299, but not until Jlab `v2.0`.

**Comment by jasongrout** [comment]
I changed the notification/display tracking to use a new version instead of the old unread message tracking. It's a bit complicated, but came from the fact that the output area's display is linked to the underlying output area model, and not linked to the log itself, so you had basically two paths of signals, one for the log display and the other for log notification, and sometimes those were mixed up in the wrong order. It's possible the older unread message system would work if the order of notifications was carefully considered.

I think this current approach still isn't quite as correct as I'd like. There is still an assumption about what the output area is displaying vs the actual version source.

**Comment by jasongrout** [comment]
> * When log console is open, generate new messages from notebook. Log count increases but doesn't flash
> 
> * Now close log console, status bar now shows flashed state. It shouldn't, because user already saw the messages

I think this works now.

**Comment by jasongrout** [comment]
Okay, I think this is good to go now. I left in the notebook output logging so it is easy to test, but we can remove that before merging.

@blink1073 - Would you rather we added a setting somewhere for the notebook to log all output to the log console (default to off)? I think we don't need it for now, but you feel it is really needed, we can add it.

**Comment by jasongrout** [comment]
ping @mbektasbbg for review. My plan is once this is merged, backport it and release another 1.2 alpha, so we can try the ipywidgets changes needed to use it.

**Comment by mbektasbbg** [comment]
@jasongrout I just pulled the latest, rebuilt and tested. Previous issue I reported is gone and I haven't seen any other issues, everything is working great! and with better behavior.

**Comment by mbektasbbg** [comment]
I just noticed that log console tab doesn't have an icon anymore. is that intentional or did I miss a build step?

**Comment by jasongrout** [comment]
> I just noticed that log console tab doesn't have an icon anymore. is that intentional or did I miss a build step

Argh, this probably happened when I moved to the new icon system so we'd have better-themed icons. I'll check into it.

**Comment by jasongrout** [comment]
@telamonian - f34ca0d makes it so that the log console icon shows up in the tab. However, it's always the same color in every theme, which doesn't look very good. Is there a way to get the icon for the tab to change colors in the different themes?

**Comment by jasongrout** [comment]
Let's address the icon color issue in a different PR. This is getting be enough as-is. I'll remove the nb output logging and merge. Thanks @mbektasbbg!

@blink1073 - still would love your thoughts about including the nb output logging.

**Comment by jasongrout** [comment]
@meeseeksdev backport to 1.x

**Pull request merged**
