### PR TITLE
Fixing missed first keystroke on Ctrl+F 

### PR DESCRIPTION
**Pull request by itsmevichu**
Fixes https://github.com/jupyterlab/jupyterlab/issues/16928

### CODE REVIEW

**Comment by itsmevichu** [comment]
The issue can be summarized as follows:

1. Press Ctrl+F and search for a term, such as "test."
2. Press Ctrl+F again and type "test." Only "est" is entered.
3. Repeat the previous step, and again only "est" is entered. After one more repetition, "test" appears.

The underlying cause:
- The issue is caused by the useEffect hook. When you first enter "test" and press Ctrl+F, the initial value becomes "test," triggering the useEffect. This causes the first letter, "t," to be selected, and typing the remaining "est" replaces the "t."
- When you press Ctrl+F again and type "test," the initial will now become "est," which triggers useEffect again, causing the "t" to be skipped, so only "est" appears.
- In the third attempt, pressing Ctrl+F and typing "test" doesn’t trigger useEffect because the initial value is still "est" (no change). So, the full "test" appears.
- This cycle keeps happening

https://github.com/jupyterlab/jupyterlab/blob/e0db5da7884f1fdcd8d2c0a79f8b0c66aa8b862e/packages/documentsearch/src/searchview.tsx#L99-L135

@krassowski Any idea on the above issue? I don’t understand the purpose of useEffect here—everything seems to work fine without it.

**Comment by krassowski** [comment]
I recall it is needed to allow populating the search box with selected text, see how these related tests are now failing:

```
    [jupyterlab] › test/jupyterlab/file-search.test.ts:65:5 › Populate search box with selected text 
    [jupyterlab] › test/jupyterlab/notebook-search.test.ts:104:7 › Notebook Search › Populate search box with selected text 
```

**Comment by krassowski** [comment]
Maybe `initialValue` should be ignored after initial render?

**Comment by itsmevichu** [comment]
@krassowski The issue arises when the search input has no initialValue, causing the previously searched term ('searchExpression') to be set as the initialValue. Since both the component re-render and useEffect depend on initialValue, pressing Ctrl+F on an already selected search input and typing 't' updates the initialValue, triggers a re-render, and resets the defaultValue in the input box, overwriting 't' with initialValue 'test'. To address this, I have made changes  to avoid frequent updates to initialValue during consecutive Ctrl+F actions; and also handled the pre-population without the use of initialValue.

**Comment by krassowski** [comment]
Note: visual regression failures and unit test failures are unrelated (https://github.com/jupyterlab/jupyterlab/issues/17012), it's due ot a very recent release of `httpx`.

**Review by krassowski — APPROVED** [review]
Thank you @itsmevichu!

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.3.x

**Pull request merged**
