### PR TITLE
Fix failing `js-apputils` check on CI

### PR DESCRIPTION
**Pull request by jtpio**
## References

Attempt at fixing https://github.com/jupyterlab/jupyterlab/issues/11886

### CODE REVIEW

**Comment by jtpio** [comment]
Pinning to `jupyter_client==7.1.0` (previous release` makes the `js-apputils` check pass: 

image

**Comment by Zsailer** [comment]
this should be fixed in jupyter_client==7.1.2

**Comment by krassowski** [comment]
7.1.2 landed 1 hour ago on conda-forge and indeed tests are now passing as seen on https://github.com/jupyterlab/jupyterlab/pull/11879 :tada: thank you both!

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter/jupyter_client/pull/740. Thanks!

**Pull request closed without merging**
