### PR TITLE
Adding extension to shared modules list

### PR DESCRIPTION
**Pull request by mnowacki-b**
## References
Addition to: https://github.com/jupyterlab/jupyterlab/pull/8772

## Code changes

Adding top level module to shared scope

### CODE REVIEW

**Comment by blink1073** [comment]
Exit criteria:

```
jlpm run build:utils
jlpm run build:packages
cd examples/federated
jlpm run build
python main.py
```

Right click on markdown file and `Open With -> (Federated)...`

**Comment by mnowacki-b** [comment]
We experience some issues with static url prefix. All scripts except `bundle.js` would load form incorrect prefix and result in a 404 error.
To fix it we made some adjustments to the federated example.

Screen Shot 2020-08-11 at 4 02 47 PM

**Comment by blink1073** [comment]
It looks like the test is hanging.  I'd also recommend rebasing to pick up any changes from #8800

**Comment by mnowacki-b** [comment]
Thanks! I will take a look at those hanging tests.

**Comment by jasongrout** [comment]
The federation example works when we test it by hand. I'd think that whether or not the CI examples test passes, we merge this and take up fixing the CI test in another PR, so we can also move forward with testing our new webpack configuration in another alpha release.

**Comment by jasongrout** [comment]
Actually, now it seems to error on the translation extension not exporting a plugin or something.

**Comment by blink1073** [comment]
What is the console error?

**Comment by jasongrout** [comment]
> What is the console error?

The translation error is fixed in my last commit. Somehow the non-extension package made it into the list of extensions.

**Comment by blink1073** [comment]
Yeah, because we didn't have a way to verify.  😀.  Happy for you to merge and release

**Pull request merged**
