### PR TITLE
Support windows-like paths

### LINKED ISSUE #5051: Support Windows Paths
...as often (almost always) it won't fit and the most important part, the filename itself, is currently being truncated:

image

### PR DESCRIPTION
**Pull request by briansgo**
Fixes #5051

BEFORE: 
When you open a file from `File > Open From Path...`, if the path uses backslashes `\` (e.g. Windows paths) the filename displays the whole file path instead of just the name of the file.
shutter_005

AFTER: 
Even if you use backslashes, the filename displays only the name and not the whole file path.
shutter_003
shutter_004

Tested in:
Windows 10 - Google Chrome
Ubuntu 18.04.1 - Google Chrome

### CODE REVIEW

**Comment by jasongrout** [comment]
How does this deal with filenames that actually have a backslash in them?

**Comment by briansgo** [comment]
Sorry, I thought backslashes were not allowed in filenames 
Is there a way in jupyterlab to detect the current OS? So the replacement only happens when using Windows.

**Comment by jasongrout** [comment]
We can have backslashes in macOS and unix.

I thought the path handling logic conformed to the interface provided by the notebook server, which I thought standardized on forward slashes as the path separator, so you wouldn't have to worry about the OS the notebook server is running on. I'm close to having a windows machine to reproduce what you are seeing.

**Comment by briansgo** [comment]
I added a function to detect the operating system, so the replacement only takes place on Windows machines, this way the filenames with backslashes on other OS won't be affected.

**Comment by jasongrout** [comment]
As follow-up, @saulshanabrook and I had an important question that has implications about where this should be fixed: https://github.com/jupyterlab/jupyterlab/issues/5051#issuecomment-457414399

**Comment by jasongrout** [comment]
Reopening per the conversation on #5051. Basically, the change needed now is to key this replacement off of an explicit user setting, not off of the browser operating system.

**Comment by vidartf** [comment]
Ideal scenario: If the server exposed its path segment separators (`os.path.sep` + `os.path.altsep` on Python), we could use that to normalize paths.

**Comment by dhirschfeld** [comment]
IIUC on Windows a forward slash is always a valid path separator so I'm unsure why you can't simply condition on the operating system and instead require a setting?

**Comment by vidartf** [comment]
@dhirschfeld I'm sorry, I don't understand your question. Would you mind rephrasing/expanding it?

**Comment by jasongrout** [comment]
> IIUC on Windows a forward slash is always a valid path separator so I'm unsure why you can't simply condition on the operating system and instead require a setting?

I think he's talking about the PR and responding to https://github.com/jupyterlab/jupyterlab/pull/5626#issuecomment-495703673

The issue is that the conditioning off the operating system is done in the browser, but the server may be on an completely different computer and OS, and each kernel could also be on a different computer/OS (so the paths printed in errors could again use different separators). All in all, that's a lot of moving pieces, each of which could change a user assumption of how it "should" work. That's why I think an explicit setting is better than trying to guess what a user intends.

**Comment by vidartf** [comment]
> The issue is that the conditioning off the operating system is done in the browser, but the server may be on an completely different computer and OS, and each kernel could also be on a different computer/OS (so the paths printed in errors could again use different separators).

Hmm. Yes I see. Originally I was thinking that any path would ultimately have to be a file path *on the server*, and that therefore the server separators would be the relevant info. However, I guess this does not necessarily hold if there are other content managers in effect. It might still make for a pretty sane default.

**Comment by jasongrout** [comment]
The one thing we know is that the server API expects network-style paths (forward slashes), starting from server root. That's the one constant we have across all OSs, and the one thing that is a consistent user expectation (i.e., browsers *always* use network-style paths, even on Windows). Whether we translate windows-style paths into network-style paths is harder to guess if we should do, because its harder to guess what the user might intend as a default because their expectations might be based on the kernel, server, or browser operating system, each of which could be different.

**Comment by dhirschfeld** [comment]
I guess ideally the open file dialog would have a little normalise paths button which became active if it detected forward slashes. Failing that a global setting would probably suffice.

**Comment by jasongrout** [comment]
> I guess ideally the open file dialog would have a little normalise paths button which became active if it detected forward slashes.

Ah, that's an interesting idea. We could definitely detect backslashes. I wouldn't want to assume that backslashes are path separators, but we could give the user a helpful option.

**Comment by vidartf** [comment]
Normalize button seems like the best option here (maybe normalize + submit in one go?), :+1:

**Comment by jasongrout** [comment]
Moving to 1.1. If someone can work on this, please post here so people know work is progressing.

**Comment by jasongrout** [comment]
Closing this, since we've now come up with a different way of approaching the problem (thanks to everyone that participated in the discussion, and especially to @briansgo for opening the PR). I'll open an issue summarizing the new design.

**Comment by jasongrout** [comment]
I opened https://github.com/jupyterlab/jupyterlab/issues/6932

**Pull request closed without merging**
