### PR TITLE
Bump package version following #11386

### PR DESCRIPTION
**Pull request by fcollonval**
## References

As mentionned in https://github.com/jupyterlab/jupyterlab/pull/11386#issuecomment-982742580 by @jtpio, the major version should be updated following the API break

I'm unsure I did it correctly (I ran `jlpm bump:major:js mainmenu`) as everything got bumped.

## Code changes

 - @jupyterlab/builder@4.0.0-alpha.0
 - @jupyterlab/buildutils@4.0.0-alpha.0
 - @jupyterlab/template@4.0.0-alpha.0
 - @jupyterlab/application-top@4.0.0-alpha.0
 - @jupyterlab/example-app@4.0.0-alpha.0
 - @jupyterlab/example-cell@4.0.0-alpha.0
 - @jupyterlab/example-console@4.0.0-alpha.0
 - @jupyterlab/example-federated@3.0.0-alpha.0
 - @jupyterlab/example-filebrowser@4.0.0-alpha.0
 - @jupyterlab/example-notebook@4.0.0-alpha.0
 - @jupyterlab/example-terminal@4.0.0-alpha.0
 - @jupyterlab/example-federated-core@3.0.0-alpha.0
 - @jupyterlab/example-federated-md@3.0.0-alpha.0
 - @jupyterlab/example-federated-middle@3.0.0-alpha.0
 - @jupyterlab/example-federated-phosphor@3.0.0-alpha.0
 - @jupyterlab/galata@5.0.0-alpha.0
 - @jupyterlab/mock-extension@4.0.0-alpha.0
 - @jupyterlab/mock-consumer@4.0.0-alpha.0
 - @jupyterlab/mock-provider@4.0.0-alpha.0
 - @jupyterlab/mock-token@4.0.0-alpha.0
 - @jupyterlab/application-extension@4.0.0-alpha.0
 - @jupyterlab/application@4.0.0-alpha.0
 - @jupyterlab/apputils-extension@4.0.0-alpha.0
 - @jupyterlab/apputils@4.0.0-alpha.0
 - @jupyterlab/attachments@4.0.0-alpha.0
 - @jupyterlab/cells@4.0.0-alpha.0
 - @jupyterlab/celltags-extension@4.0.0-alpha.0
 - @jupyterlab/celltags@4.0.0-alpha.0
 - @jupyterlab/codeeditor@4.0.0-alpha.0
 - @jupyterlab/codemirror-extension@4.0.0-alpha.0
 - @jupyterlab/codemirror@4.0.0-alpha.0
 - @jupyterlab/completer-extension@4.0.0-alpha.0
 - @jupyterlab/completer@4.0.0-alpha.0
 - @jupyterlab/console-extension@4.0.0-alpha.0
 - @jupyterlab/console@4.0.0-alpha.0
 - @jupyterlab/coreutils@6.0.0-alpha.0
 - @jupyterlab/csvviewer-extension@4.0.0-alpha.0
 - @jupyterlab/csvviewer@4.0.0-alpha.0
 - @jupyterlab/debugger-extension@4.0.0-alpha.0
 - @jupyterlab/debugger@4.0.0-alpha.0
 - @jupyterlab/docmanager-extension@4.0.0-alpha.0
 - @jupyterlab/docmanager@4.0.0-alpha.0
 - @jupyterlab/docprovider-extension@4.0.0-alpha.0
 - @jupyterlab/docprovider@4.0.0-alpha.0
 - @jupyterlab/docregistry@4.0.0-alpha.0
 - @jupyterlab/documentsearch-extension@4.0.0-alpha.0
 - @jupyterlab/documentsearch@4.0.0-alpha.0
 - @jupyterlab/extensionmanager-extension@4.0.0-alpha.0
 - @jupyterlab/extensionmanager@4.0.0-alpha.0
 - @jupyterlab/filebrowser-extension@4.0.0-alpha.0
 - @jupyterlab/filebrowser@4.0.0-alpha.0
 - @jupyterlab/fileeditor-extension@4.0.0-alpha.0
 - @jupyterlab/fileeditor@4.0.0-alpha.0
 - @jupyterlab/help-extension@4.0.0-alpha.0
 - @jupyterlab/htmlviewer-extension@4.0.0-alpha.0
 - @jupyterlab/htmlviewer@4.0.0-alpha.0
 - @jupyterlab/hub-extension@4.0.0-alpha.0
 - @jupyterlab/imageviewer-extension@4.0.0-alpha.0
 - @jupyterlab/imageviewer@4.0.0-alpha.0
 - @jupyterlab/inspector-extension@4.0.0-alpha.0
 - @jupyterlab/inspector@4.0.0-alpha.0
 - @jupyterlab/javascript-extension@4.0.0-alpha.0
 - @jupyterlab/json-extension@4.0.0-alpha.0
 - @jupyterlab/launcher-extension@4.0.0-alpha.0
 - @jupyterlab/launcher@4.0.0-alpha.0
 - @jupyterlab/logconsole-extension@4.0.0-alpha.0
 - @jupyterlab/logconsole@4.0.0-alpha.0
 - @jupyterlab/mainmenu-extension@4.0.0-alpha.0
 - @jupyterlab/mainmenu@4.0.0-alpha.0
 - @jupyterlab/markdownviewer-extension@4.0.0-alpha.0
 - @jupyterlab/markdownviewer@4.0.0-alpha.0
 - @jupyterlab/mathjax2-extension@4.0.0-alpha.0
 - @jupyterlab/mathjax2@4.0.0-alpha.0
 - @jupyterlab/metapackage@4.0.0-alpha.0
 - @jupyterlab/nbconvert-css@4.0.0-alpha.0
 - @jupyterlab/nbformat@4.0.0-alpha.0
 - @jupyterlab/notebook-extension@4.0.0-alpha.0
 - @jupyterlab/notebook@4.0.0-alpha.0
 - @jupyterlab/observables@5.0.0-alpha.0
 - @jupyterlab/outputarea@4.0.0-alpha.0
 - @jupyterlab/pdf-extension@4.0.0-alpha.0
 - @jupyterlab/property-inspector@4.0.0-alpha.0
 - @jupyterlab/rendermime-extension@4.0.0-alpha.0
 - @jupyterlab/rendermime-interfaces@4.0.0-alpha.0
 - @jupyterlab/rendermime@4.0.0-alpha.0
 - @jupyterlab/running-extension@4.0.0-alpha.0
 - @jupyterlab/running@4.0.0-alpha.0
 - @jupyterlab/services@7.0.0-alpha.0
 - @jupyterlab/settingeditor-extension@4.0.0-alpha.0
 - @jupyterlab/settingeditor@4.0.0-alpha.0
 - @jupyterlab/settingregistry@4.0.0-alpha.0
 - @jupyterlab/shared-models@4.0.0-alpha.0
 - @jupyterlab/shortcuts-extension@4.0.0-alpha.0
 - @jupyterlab/statedb@4.0.0-alpha.0
 - @jupyterlab/statusbar-extension@4.0.0-alpha.0
 - @jupyterlab/statusbar@4.0.0-alpha.0
 - @jupyterlab/terminal-extension@4.0.0-alpha.0
 - @jupyterlab/terminal@4.0.0-alpha.0
 - @jupyterlab/theme-dark-extension@4.0.0-alpha.0
 - @jupyterlab/theme-light-extension@4.0.0-alpha.0
 - @jupyterlab/toc-extension@6.0.0-alpha.0
 - @jupyterlab/toc@6.0.0-alpha.0
 - @jupyterlab/tooltip-extension@4.0.0-alpha.0
 - @jupyterlab/tooltip@4.0.0-alpha.0
 - @jupyterlab/translation-extension@4.0.0-alpha.0
 - @jupyterlab/translation@4.0.0-alpha.0
 - @jupyterlab/ui-components-extension@4.0.0-alpha.0
 - @jupyterlab/ui-components@5.0.0-alpha.0
 - @jupyterlab/vdom-extension@4.0.0-alpha.0
 - @jupyterlab/vdom@4.0.0-alpha.0
 - @jupyterlab/vega5-extension@4.0.0-alpha.0
 - @jupyterlab/example-services-browser@4.0.0-alpha.0
 - node-example@4.0.0-alpha.0
 - @jupyterlab/example-services-outputarea@4.0.0-alpha.0
 - @jupyterlab/testutils@4.0.0-alpha.0

## User-facing changes

N/A

## Backwards-incompatible changes

Acknowledge the API break --> bumping everything it looks...

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @fcollonval for the follow-up.

> I'm unsure I did it correctly (I ran jlpm bump:major:js mainmenu) as everything got bumped.

Just to double check, maybe this was a typo as the script appears to be `bump:js:major` in:

https://github.com/jupyterlab/jupyterlab/blob/014091f21d00bd1c940105744d945a61a7b23e6a/package.json#L51

Which gives the following output when running it locally in dry run mode:

```
$ jlpm bump:js:major mainmenu --dry-run
yarn run v1.21.1
$ node buildutils/lib/bump-js-major.js mainmenu --dry-run
Would run:
lerna version premajor --preid=alpha --force-publish=mainmenu,apputils-extension,metapackage,codemirror-extension,console-extension,csvviewer-extension,fileeditor-extension,help-extension,mainmenu-extension,notebook-extension,terminal-extension,translation-extension --no-push
Done in 2.42s.
```

**Comment by jtpio** [comment]
An alternative would be to do the full bump now, since this will be the case with #11537 anyway.

Although it's nice to only bump what is needed, so it makes more sense when looking at the git history later.

**Comment by fcollonval** [comment]
Thanks @jtpio for catching the use of a wrong script.

Actually the result is similar.

I think the trouble comes from that cycle dependency: `lerna WARN ECYCLE @jupyterlab/apputils -> @jupyterlab/testutils -> @jupyterlab/notebook -> @jupyterlab/cells -> @jupyterlab/apputils`

**Comment by jtpio** [comment]
OK thanks for checking.

So this might be similar to https://github.com/jupyterlab/jupyterlab/pull/10420#issuecomment-909036232 in the end, where all the packages were also bumped.

Ideally we could find a way to remove that circular dependency if possible.

But given that https://github.com/jupyterlab/jupyterlab/pull/11537 will be part of 4.0, we could just bump everything now to keep things simple.

**Comment by fcollonval** [comment]
> Ideally we could find a way to remove that circular dependency if possible.

It is tricky as testutils is providing mock for apputils and for notebook/cells.

One way could be to move the mock of apputils in apputils and still expose them as public API in testutils. So the API stay the same but testutils is not used anymore by apputils.

**Comment by jtpio** [comment]
Thanks for looking into it.

> One way could be to move the mock of apputils in apputils and still expose them as public API in testutils. So the API stay the same but testutils is not used anymore by apputils.

Thinking we could track that in a separate issue, as this would still be useful to fix the cyclic dependency.

And finish https://github.com/jupyterlab/jupyterlab/pull/11537 which will take care of the version bump in one go, as a replacement for this PR.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyterlab/pull/11537.

I opened https://github.com/jupyterlab/jupyterlab/issues/11630 as follow-up.

**Pull request closed without merging**
