### PR TITLE
Change "Export Notebook As" to "Save and Export Notebook As"

### PR DESCRIPTION
**Pull request by bsyouness**
When JLab exports to pdf, it saves the file before the export which different from what other famous programs do (Microsoft suite). This PR changes the phrasing to make it clear that the project state gets saved when the export is performed.
@jasongrout per our discussion.

### CODE REVIEW

**Comment by krassowski** [comment]
Heads up: with the 3.1.8 release we now have all that is needed for announcing support for translations. If we decide to do that we should freeze the strings for 3.1.x and target PRs like this one for 3.2.

**Review by jtpio — APPROVED** [review]
Makes sense, thanks!

**Comment by jtpio** [comment]
We might want to check the reference UI screenshots are still valid though, since this updates a user-facing string.

**Comment by jtpio** [comment]
> We might want to check the reference UI screenshots are still valid though, since this updates a user-facing string and the galata check seems to be failing: https://github.com/jupyterlab/jupyterlab/pull/10904/checks?check_run_id=3413073674

@bsyouness would you mind updating to the new reference screenshot, which can be found on CI here? 

https://github.com/jupyterlab/jupyterlab/actions/runs/1163289065

**Comment by jtpio** [comment]
Rebased to pick up the CI fixes from https://github.com/jupyterlab/jupyterlab/pull/10980

**Comment by jtpio** [comment]
> Rebased to pick up the CI fixes from #10980

TODO:

- [ ] Still need to update the screenshots with the ones from the CI run

**Comment by blink1073** [comment]
Please don't merge this until the release-in-progress has finished

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.2.x

**Pull request merged**
