### PR TITLE
Fix restart cancellation

### LINKED ISSUE #3696: Pressing "Cancel" after pressing "Restart Kernel and Run All Cells"
When you press "Cancel" after pressing "Restart Kernel and Run All Cells" this results in the Kernel not being reset, however all cells are still run.

When pressing cancel my natural expectation was that it would cancel the whole request and do neither Restart Kernel or Run All Cells.

Cheers,
Simon

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes #3696

### CODE REVIEW

**Comment by blink1073** [comment]
Is there a reason we can't check for `null` to determine whether the kernel was restarted?  I would rather not make another set of major releases for beta1.

**Comment by ian-r-rose** [comment]
When would we check for `null`? As far as I know, the restarted kernel looks the same to the services user as the un-restarted kernel (same `id`, etc).
That is to say, whether the user says "Yes, restart the kernel" or, "No, don't restart the kernel", they both get the same `Kernel.IConnection` back.

**Comment by ian-r-rose** [comment]
I am not sure how crucial this is for another beta1, so maybe it is okay to hold off on it, as well.

**Comment by blink1073** [comment]
LGTM, thanks!

**Pull request merged**
