### PR TITLE
Keep overflow of CodeMirror editors

### PR DESCRIPTION
**Pull request by krassowski**
## References

A naive attempt at #10625. Likely not good enough and likely will break things. Just giving it a try.

## Code changes

Overflow CodeMirror editors.

### CODE REVIEW

**Comment by krassowski** [comment]
A different solution is likely needed, this seems to break too many things.

**Comment by hbcarlos** [comment]
What does it break?
I'm trying it out, and everything looks good.

**Comment by krassowski** [comment]
For example see the code cell with `maxwells` overflowing beyond the right edge:

Screenshot from 2021-07-27 20-24-53

My initial assessment was that we would need to physically move the caret label in DOM, but maybe I am wrong and maybe we could patch this with CSS only.

**Comment by hbcarlos** [comment]
> My initial assessment was that we would need to physically move the caret label in DOM, but maybe I am wrong and maybe we could patch this with CSS only.

I tried different things with CSS, and I don't see a solution.
How would you move the caret label?

**Pull request closed without merging**
