### PR TITLE
codemirror: add config options to style selection

### LINKED ISSUE #5528: Should allow user to style the codemirror selection
**Describe the bug**
Now it's lack the config options to style the codemirror selection, there are [commonly used addons for codemirror](https://codemirror.net/doc/manual.html#addons) to style these:

selection/active-line.js
selection/mark-selection.js
selection/selection-pointer.js

**Expected behavior**
The `selection` addons for codemirror should be included and set to a basic default config options.

**Screenshots**

image

**Desktop (please complete the following information):**

- JupyterLab [<=0.35]

### PR DESCRIPTION
**Pull request by futurist**
Fixes #5528

Below is a demo to use these options:

**Screenshots**

DEMO

### CODE REVIEW

**Comment by blink1073** [comment]
cc @tgeorgeux for UX input.

**Comment by futurist** [comment]
@tgeorgeux Can you review this PR? need any update please kindly let me know.

**Comment by blink1073** [comment]
Yeah I think making the highlighting configurable is fair.

**Comment by futurist** [comment]
@tgeorgeux I think the point is when user switching theme, the selection style should not mess up the theme style? If this is the case, I suggest the default value for these three options should be `false`, that case nothing changed except for after the user styling their selections, then manually turn on.

**Comment by futurist** [comment]
@tgeorgeux The latest commit set all these options `false` as default, please have a check.

**Comment by tgeorgeux** [comment]
@futurist I don't mind turning them on by default. 

What I was addressing with my earlier comment is to add those options to the code mirror tab in the advanced settings editor. See the screenshot:

screen shot 2018-11-20 at 9 59 21 am

In order to add these options to the advanced settings editor, you will need to build out the relevant schema in these files:
jupyterlab/packages/codemirror-extension/schema/commands.json
jupyterlab/packages/codemirror-extension/src/index.ts

Also, CI stuff isn't my specialty but it looks like the appveyor build is breaking. @blink1073 are tests at 100 right now?

**Comment by blink1073** [comment]
Appveyor has been flaky...

**Comment by futurist** [comment]
@tgeorgeux  I've pushed new commits, and think below really make sense:

image

**Comment by blink1073** [comment]
LGTM, thanks!

**Comment by tgeorgeux** [comment]
Thank you so much @futurist !

**Pull request merged**
