### PR TITLE
Refresh yarn.lock in preparation for 3.1

### PR DESCRIPTION
**Pull request by jasongrout**
## Code changes

This refreshes the yarn.lock file to the latest versions of requested dependencies. I created these changes by deleting the yarn.lock and then installing with `pip install -ve .`.

The idea here is that before doing a minor, we should upgrade to the latest versions of our dependencies to pick up bugfixes and stay current on our dependencies.

### CODE REVIEW

**Comment by jasongrout** [comment]
I'll flag that this seems to upgrade typedoc from the beta we had been using. IIRC, we have to fixate on that particular beta because it implements something we need, so we should remove the `~` maybe from that dependency version.

One nice thing about refreshing yarn.lock is that it helps us debug and maybe correct our version requirements.

**Comment by blink1073** [comment]
This picked up a conflict from #10515

**Comment by jasongrout** [comment]
> This picked up a conflict from #10515

I've rebased this on master and re-refreshed the file.

**Comment by jasongrout** [comment]
Converting to draft while there are still test failures.

**Comment by jasongrout** [comment]
I think everything is good except for errors with storybook. I'm not sure (a) if we are really using it, and (b) if an upgrade will be that easy (seems like there is lots of configuration needed to change?), and (c) if keeping it the same version is feasible (it seems it relies on webpack 4 right now?)

If anyone knows anything about our storybook configuration and can help, it would be much appreciated. The error is 

> info => Cleaning outputDir: /home/runner/work/jupyterlab/jupyterlab/packages/ui-components/storybook-static
ERR! Error: You have both a "main" and a "config". Please remove the "config" file from your configDir (/home/runner/work/jupyterlab/jupyterlab/packages/ui-components/.storybook/config)

https://github.com/jupyterlab/jupyterlab/pull/10516/checks?check_run_id=3024551288#step:11:678

**Comment by jasongrout** [comment]
When I downgrade `@storybook/react` and `@storybook/addon-actions` to their previous versions (6.0.20), I still see the error above, which is confusing since it seemed to work before. Is there another storybook package required somewhere that is triggering that error message?

**Comment by jasongrout** [comment]
Funny enough, when I try running the steps in the integrity2 test locally with master checked out, I get the same error.

**Comment by jasongrout** [comment]
I think all the relevant errors are now dealt with:

1. I restricted the lint version ranges so that we didn't get gratuitous formatting changes by just refreshing the yarn.lock.
2. Typedoc was complaining about several null-checking issues (one of which is being fixed upstream). For now, since it is just the docs, I turned off null checking for typedoc.
3. I restricted the version of storybook to what we had installed. It seemed any movement of that version triggered the error mentioned above, and I didn't have time or inclination right now to track down how to upgrade the storybook configuration.

All in all, this brings us up to current versions (within the required ranges we've specified) of nearly all of our dependencies.

**Review by blink1073 — APPROVED** [review]
Changes LGTM, thanks!  Looks like the UI failure is relevant.

**Comment by jasongrout** [comment]
>  Looks like the UI failure is relevant.

Indeed. It looks like when a single launcher tab is open, the close button on the tab is not there. This PR then actually matches up with the 3.0 behavior: no close X when the single Launcher tab is open, but Xs appear when there is more than one tab.

Here is the latest 3.0 release:
Screen Shot 2021-07-09 at 8 46 21 AM

Here is current master:
Screen Shot 2021-07-09 at 9 03 06 AM

Here is after this PR:
Screen Shot 2021-07-09 at 8 52 51 AM

I'll update the reference screenshots, since I think the current master behavior is (a) not consistent with 3.0, and (b) worse (since clicking on the visible X does nothing).

**Comment by jasongrout** [comment]
I refreshed the yarn.lock one more time (picked up two new patch releases in dependencies since yesterday), and reordered commits so the history makes more sense (put the yarn refresh before the fixes to problems from the refresh).

**Comment by blink1073** [comment]
Thanks again!

**Comment by jasongrout** [comment]
Thanks!

**Pull request merged**
