### PR TITLE
Bump xtermjs to latest

### PR DESCRIPTION
**Pull request by yuvipanda**
Seems to improve deadkeys behavior in Safari but not Firefox

## References

Ref https://github.com/jupyterlab/jupyterlab/issues/10990

## Code changes

Bumps version of xtermjs. LMK if I should remove the yarn-lock changes.

## User-facing changes

Brings in added features from almost last two years - https://github.com/xtermjs/xterm.js/releases
has list. 

## Backwards-incompatible changes

No breaking changes

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @yuvipanda.

Looks like the UI tests failures might be relevant: 

image
 
Maybe we can simply update the reference snapshots if these are minor visual differences.

**Comment by fcollonval** [comment]
please update snapshots

**Comment by yuvipanda** [comment]
Are there docs on how to do that? I haven't used snapshot based testing like this before :(

**Comment by fcollonval** [comment]
> Are there docs on how to do that? I haven't used snapshot based testing like this before :(

As pixel diff is tricky (for JLab OS is not neutral), we have a job to update them by commenting ```please update ... snapshots``` on a PR (as I did in the previous comment).

It will commit the new snapshots; usually I need to update the commit as some are noisy update.

**Comment by yuvipanda** [comment]
@fcollonval lololololol i thought you were asking me to update them, not a bot... :D

**Comment by fcollonval** [comment]
> @fcollonval lololololol i thought you were asking me to update them, not a bot... :D

Sorry for that  - I should have commented I updated the snapshots...

**Comment by fcollonval** [comment]
The job _Linux Tests / examples_ failure seems legit:

```
error >> Yjs was already imported. This breaks constructor checks and will lead to isssues!
```

**Review by fcollonval — APPROVED** [review]
CI is back to green

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.4.x

**Comment by yuvipanda** [comment]
yay! Thank you so much for this, @fcollonval!

**Comment by fperez** [comment]
Big thanks @yuvipanda @fcollonval for moving this forward!

I can confirm that with this, Safari's behavior is now correct (it wasn't in 3.4.3). Chrome seems OK even in 3.4.3, and as Yuvi noted, Firefox seems to still have issues.

But given both Chrome and Safari now handle dead keys correctly, I'm willing to chalk it to a Firefox bug/limitation for now.

Great to see this improvement!

**Pull request merged**
