### PR TITLE
Drop the `moment` dependency

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/13269

This will help reduce the size of the bundles, which will be particularly helpful in downstream applications like JupyterLite.

This might also help with localization (fixes a TODO).

## Code changes

- [x] Drop the `moment` dependency in favor of using native browser APIs.
- [x] Drop `Time.format()`? -> maybe we can keep it around for now, but drop support for the `timeFormat` parameter which had a default value
- [x] Update migration guide

image

## User-facing changes

Some user facing strings might change.

## Backwards-incompatible changes

Yes if we decide to drop support for `Time.format()` (removing the exported function), and replace the internal use of `Time.format()` by `Intl.DateTimeFormat()`

### CODE REVIEW

**Comment by jtpio** [comment]
bot please update documentation snapshots

**Comment by jtpio** [comment]
bot please update snapshots

**Comment by jtpio** [comment]
bot please update snapshots

**Comment by jtpio** [comment]
bot please update snapshots

**Comment by jtpio** [comment]
The UI tests documentation failure is expected as some user facing strings are changed, for example "a day ago" -> "yesterday": 

image

Also the "UI in Chinese" failed because it does not find `README.md` on the page:

https://user-images.githubusercontent.com/591645/213411414-d65410fa-3e10-4b6b-9d74-a3ae5c9bdcbc.mp4

Which looks like a valid issue when trying to reproduce in dev mode:

image

**Comment by jtpio** [comment]
Will try to update the snapshots again with the bot.

**Comment by jtpio** [comment]
bot please update documentation snapshots

**Comment by jtpio** [comment]
One more kick (https://github.com/jupyterlab/jupyterlab/issues/13505).

**Review by fcollonval — CHANGES_REQUESTED** [review]
Thanks @jtpio 

To fix the CI you only need to drop the unwanted changes to galata/test/documentation/general.test.ts-snapshots/file-formats-html-display-documentation-linux.png
https://github.com/jupyterlab/jupyterlab/pull/13469/files#diff-9f79052c539324287f8df1779707857e4e41bc23fc336393de60dcbadf0b8cd9

**Comment by jtpio** [comment]
Ah thanks good catch.

**Comment by jtpio** [comment]
CI back to green.

Ping @fcollonval in case you would like to have another look.

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio

**Pull request merged**
