### PR TITLE
Context menu plugin schema

### PR DESCRIPTION
**Pull request by jtpio**
## References

Follow-up to https://github.com/jupyterlab/jupyterlab/pull/10624 based on the comment by @fcollonval: https://github.com/jupyterlab/jupyterlab/pull/10624#issuecomment-882502570

## Code changes

Move settings schema to a different plugin.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Looks good on Binder:

image

image

**Comment by jtpio** [comment]
@fcollonval this should be ready for review

The shortcuts have been moved to `commands.json` since there is also a `commands` plugin. Which means `main.json` should not be necessary anymore.

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio 

> `main.json` should not be necessary anymore

As it does not contain any settings properties that a user may have customized in the previous stable version, I agree fully.

**Comment by blink1073** [comment]
This one needs a rebase

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.1.x

**Pull request merged**
