### PR TITLE
Commands options

### LINKED ISSUE #6989: Allow custom apps to reuse build system
I've recently been experimenting with creating a custom lab app (https://github/com/vidartf/phoila). Mostly, I found the system to be configurable (some bits more easily than others), but the one bit I ended up having to monkey patch was [`_get_core_data`](https://github.com/jupyterlab/jupyterlab/blob/1365152c1da22b47920b6b3838e539590a300c83/jupyterlab/commands.py#L1731-L1735). This function supplies the core configuration of the build, but is an internal function that is impossible to configure (it uses a hard-coded local path).

Would there be any disagreement to making this path configurable?

### PR DESCRIPTION
**Pull request by vidartf**
## References

Fixes #6989 (the last bit).

## Code changes

Three distinct changes:
1. **Some test utilities** (`pytest --quick` and `pytest --slow`)
2. **Refactor commands.py to use `options`:**

   This makes it easier to add new kwargs to `_AppHandler` later on without having to update all API functions (still minor change, but makes it clear that argument order is not significant, and less developer work, and also ensures the APIs are more consistent).

   Con: Lack of argument name checking. Possible solution: Use a namedtuple (with `defaults`) to specify all supported options (Python >= 3.7, or 3.x with small polyfill).

   Also: `options` is possibly a too generic name. Maybe `apphandler_options` or `app_options`?

3. **Add _AppHandler option `use_sys_dir`:**

   This allows API users to specify that the `sys_dir` argument should not be used (or rather, set to the same as the `app_dir`).

## User-facing changes

This is a change for python library users, as it deprecates an old API, and allows for new behavior (pt 3).

## Backwards-incompatible changes

None, but gives a deprecation warning for the old APIs.

### CODE REVIEW

**Comment by blink1073** [comment]
What if we had a `HasTraits` object, but allowing you to pass an instance or a simple dictionary that is used to initialize that object?  It think `app_options` and `AppOptions` are good names.

**Comment by vidartf** [comment]
@blink1073 I would *like* it to be in, but I am also in principle against adding new features between an RC and final, so I won't push it.

**Comment by blink1073** [comment]
Can we move the `_ensure_logger` logic into `AppOptions` as a default value?

**Comment by blink1073** [comment]
Perhaps make _AppHandler extend AppOptions and also audit the places we were handling kwargs where we don't need to anymore (like all the places we call _ensure_logger that could instead use app.logger)

**Comment by vidartf** [comment]
> Perhaps make _AppHandler extend AppOptions and also audit the places we were handling kwargs where we don't need to anymore (like all the places we call _ensure_logger that could instead use app.logger)

Won't this just make it a full-circle, so that we are back at having to pass everything as keyword arguments?

**Comment by blink1073** [comment]
Not if you override `__init__`  :wink:

**Comment by blink1073** [comment]
Did we say this was ready as-is?

**Comment by vidartf** [comment]
I think we agreed on the strategy, so it should be OK unless you spot any logic errors in the code.

**Comment by blink1073** [comment]
LGTM, thanks!

**Pull request merged**
