### PR TITLE
Improve kernels pane in running sidebar

### PR DESCRIPTION
**Pull request by afshin**
This PR:
- Updates the `notebook:create-new` command to support passing in an optional `kernelId` to create a new notebook that uses an existing kernel instance.
- Adds a context menu to the kernels pane in the running sidebar that allows users to:
  - Create a new code console for the given kernel
  - Create a new notebook for the given kernel
  - Switch to an existing session connection for the given kernel
  - Shut down the given kernel
-  Adds a collapsible list of connected sessions beneath each kernel in the running kernels pane
- Displays the icon in the kernel spec's `resources` instead of displaying the Jupyter icon when possible

## References
- #13779
- #13792 

## User-facing changes

https://user-images.githubusercontent.com/159529/214585918-6dd246d2-7eb6-4fc4-bc24-2c73b01b462e.mov

## Backwards-incompatible changes
N/A

### CODE REVIEW

**Comment by afshin** [comment]
bot please update documentation snapshots

**Comment by afshin** [comment]
bot please update documentation snapshots

**Comment by afshin** [comment]
bot please update snapshots

**Comment by afshin** [comment]
bot please update snapshots

**Review by fcollonval — CHANGES_REQUESTED** [review]
thanks @afshin 

You gonna have to update the selector in the UI documentation tests to make them succeed before asking for an update of the snapshots.

**Comment by afshin** [comment]
@fcollonval, thanks for the review!

The only place I'm finding a selector in the docs is for `#jp-running-sessions`, which still exists. I think I am not looking in the right place 🫤

**Comment by jtpio** [comment]
Thanks @afshin for working on this!

I just tried the latest changes on this branch it's looking good.

Quick question: should a new console started with "New Console for Notebook" also be listed under the kernel? Similar to when a separate console is started and then its kernel changed to an existing one:

https://user-images.githubusercontent.com/591645/215058318-bb272a14-68a8-40dd-b685-79548c3f1f4e.mp4

**Comment by jtpio** [comment]
> I think it should appear in the list as well.

Same here. In the example above I would expect the new console started from the `Untitled.ipynb` notebook to also be listed under the kernel, with `Untitled.ipynb` as the name and with the console icon.

**Comment by fcollonval** [comment]
> The only place I'm finding a selector in the docs is for `#jp-running-sessions`, which still exists. I think I am not looking in the right place 🫤

To fix some tests with the first PR, I changed some selectors to use the text content (it is considered better for integration tests). There are two places:

https://github.com/jupyterlab/jupyterlab/blob/0250b696b12c1421931cbf6588253d8a2de5bde0/galata/test/documentation/general.test.ts#L144

https://github.com/jupyterlab/jupyterlab/blob/0250b696b12c1421931cbf6588253d8a2de5bde0/galata/test/documentation/general.test.ts#L465

As now the text is `Python 3 (ipykernel)`, it is similar to the text use in the kernel status of the notebook. So the selector should be something like:

```ts
page.locator('#jp-running-sessions >> text="Python 3 (ipykernel)"')
```

> If you want to read more about the selection in playwright, the doc is over [there](https://playwright.dev/docs/other-locators)

**Comment by afshin** [comment]
bot please update snapshots

**Comment by fcollonval** [comment]
bot please update documentation snapshots

**Review by fcollonval — APPROVED** [review]
Thanks @afshin

**Comment by jtpio** [comment]
Looks good, thanks!

**Pull request merged**
