### PR TITLE
Update the extension builder to @jupyterlab/extension-builder.

### LINKED ISSUE #1103: 404 on frontpage
As a first time user, I have tried installing Jupyterlabs from source. Installing
a recent version (3bc0451c8592c47f561d7841b09fdcf4ded129bd) on Linux
[Fedora release 23 (Twenty Three)] works without problems. When starting
jupyter-lab, the webpage shows

"""404 : Not Found
You are requesting a page that does not exist!
"""

with the console output [1] in debug mode. This seems very much like a 
bug. Please let me know if additional information is required.

Martin

[1]
engelenvaart $ jupyter-lab --debug
[D 17:32:22.762 LabApp] Searching [u'/data2/marberi/source/jupyterlab', '/home/marberi/.jupyter', '/data2/marberi/anaconda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 17:32:22.762 LabApp] Looking for jupyter_config in /etc/jupyter
[D 17:32:22.763 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 17:32:22.763 LabApp] Looking for jupyter_config in /data2/marberi/anaconda/etc/jupyter
[D 17:32:22.763 LabApp] Looking for jupyter_config in /home/marberi/.jupyter
[D 17:32:22.763 LabApp] Looking for jupyter_config in /data2/marberi/source/jupyterlab
[D 17:32:22.764 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 17:32:22.764 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 17:32:22.765 LabApp] Looking for jupyter_notebook_config in /data2/marberi/anaconda/etc/jupyter
[D 17:32:22.765 LabApp] Looking for jupyter_notebook_config in /home/marberi/.jupyter
[D 17:32:22.765 LabApp] Looking for jupyter_notebook_config in /data2/marberi/source/jupyterlab
/data2/marberi/anaconda/lib/python2.7/site-packages/IPython/paths.py:49: UserWarning: Ignoring ~/.config/ipython in favour of ~/.ipython. Remove ~/.config/ipython to get rid of this message
  'get rid of this message').format(cu(xdg_ipdir), cu(ipdir)))
[I 17:32:23.004 LabApp] Serving notebooks from local directory: /data2/marberi/source/jupyterlab
[I 17:32:23.004 LabApp] 0 active kernels 
[I 17:32:23.005 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 17:32:23.005 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 17:32:23.780 LabApp] Using contents: services/contents
[W 17:32:23.826 LabApp] 404 GET /lab (::1) 47.59ms referer=None
[D 17:32:25.004 LabApp] 304 GET /custom/custom.css (::1) 1.84ms
Created new window in existing browser session.
[12056:12056:1017/173225:ERROR:broker_posix.cc(41)] Invalid node channel message

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #1103

### CODE REVIEW

**Comment by jasongrout** [comment]
@ellisonbg - how come we have a new 'in progress' tag added to PRs on open? If anything, shouldn't it be our 'status: Work in progress' label?

**Comment by blink1073** [comment]
Also, where do we go to set that up?  I couldn't find the setting.

**Comment by jasongrout** [comment]
ping @blink1073 for review.

**Comment by blink1073** [comment]
👍 (didn't review because of the `in progress` label).

**Pull request merged**
