### PR TITLE
Updates to the kernel panel of the "running" sidebar

### PR DESCRIPTION
**Pull request by afshin**
This PR changes the behavior and user experience of the running kernels sidebar panel. The UX needs a further review and this PR will need further iterations before we arrive at a happy state.

- Instead of showing "sessions" from `api/sessions` (each "session" might be better described as "kernel connection", i.e., the notebook or console that is connected to a live kernel), the panel shows all of the active **kernels**.
- When a running kernel is clicked on, it opens all of the "sessions" connected to it, e.g., if a kernel has a console and a notebook session associated with it, both are opened when the user clicks on it.
- This fixes a bug where multiple connections (i.e., multiple "sessions" in the API's usage of the term) are listed as individual "kernels" incorrectly. With this PR, only one kernel is listed, with this panel being an accurate reflection of a request to `api/kernels` instead of `api/sessions`
- The `KernelManager` instance that is used internally by the `ServiceManager` to underlie the `SessionManager` has been exposed as `ServiceManager#kernels`
- Fixes a bug in the `KernelManager` that caused it to ignore changed kernels when they were refreshed.

## References
Fixes https://github.com/jupyterlab/jupyterlab/issues/13779

## User-facing changes
The running kernels section has changed.

#### Before
before

#### After
after

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Great! It seems the UI regression screenshots should be re-generated.

**Comment by krassowski** [comment]
bot please update galata snapshots

**Comment by krassowski** [comment]
The bot action ([run](https://github.com/jupyterlab/jupyterlab/actions/runs/3933460196/jobs/6727178238)) is failing on canvas-node 18 incompatibility. I will merge master to pull https://github.com/jupyterlab/jupyterlab/pull/13783 in.

**Comment by krassowski** [comment]
Oh, it's a draft. I will wait in that case.

**Comment by afshin** [comment]
The bug still exists, I haven't pushed the fix yet. So far I've just pushed a small optimization to make fewer API requests.

**Review by SylvainCorlay — APPROVED** [review]

**Review by afshin — COMMENTED** [review]
bot please update galata snapshots

**Comment by fcollonval** [comment]
bot please update documentation snapshots

**Comment by fcollonval** [comment]
New snapshots look flaky due to the number of connections.

Let's kicking the CI and see what happen.

**Comment by afshin** [comment]
Will having connections visible here make the CI unstable forever? Should we reconsider having it there?

**Comment by fcollonval** [comment]
As expected the tests are flaky, I'll look to improve that.

**Comment by afshin** [comment]
Yeah you're right. Cheers!

**Comment by fcollonval** [comment]
bot please update documentation snapshots

**Review by afshin — COMMENTED** [review]
bot please update documentation snapshots

**Comment by afshin** [comment]
The documentation failure is because the first cell is missing the blue line (indicating focus):

Screenshot 2023-01-22 at 23 23 07

Here is an animation of the actual vs. expected snapshot:

https://user-images.githubusercontent.com/159529/213945981-d4584f1d-de96-4843-8896-a5b43b8fc25b.mov

I don't think this issue (if it is an issue) was created by this PR.

**Comment by afshin** [comment]
bot please update documentation snapshots

**Review by fcollonval — APPROVED** [review]

**Pull request merged**
