### PR TITLE
Command to insert text

### PR DESCRIPTION
**Pull request by dLamSlo8**
## References
#4519 

## Code changes

- Added interface function for any code editor to insert text.
- Added individual commands for console, notebook, and full editor to be able to insert text.
- Added a general command that will allow for inserting text in all the contexts mentioned above at once.

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks for working on this @dLamSlo8!  Do you mind adding tests for the codeeditor, notebook and console changes?

**Comment by dLamSlo8** [comment]
@blink1073 Hi, I currently have the tests for codeeditor and console, but am unable to get the notebook tests working. For these commands, I realized it requires the editor to be focused first, and when attempting to focus the currently active cell in the notebook tests using cell.editor.focus(), it fails to do so, and thus my tests can't work properly. Do you have an idea as to why that might be the case? In, for example, the console test when I focus the prompt cell, it does actually focus the cell and thus I can insert text.

**Comment by blink1073** [comment]
Here's what we did in similar tests: https://github.com/jupyterlab/jupyterlab/blob/cd046aa212d9a5a26fd430ea625a2b8e52dafa52/tests/test-notebook/src/widget.spec.ts#L1240

**Comment by jasongrout** [comment]
I'm looking at this too (hoping we can get it in for 2.1). Looking at the API, it looks like the content and selection are stored in the model, though view-specific things are in the editor. I think we don't have any other methods on the widget now that explicitly change the text.

Two thoughts about the current API:

1. Since it is replacing the selected text (as mentioned in the docs), perhaps it would be better to be called replaceSelection (which is the method name in the CodeMirror API as well: https://codemirror.net/doc/manual.html#replaceSelection)

2. Perhaps this should be a method on the model, where the actual text content is? If we did that, we'd have to also manipulate the selection manually). Or perhaps for now, since it is immediately useful, we keep the method on the editor, and as we develop the model more for real-time collaboration, we transition such methods to the model over time?

**Comment by jasongrout** [comment]
And I realize I was the one proposing these sorts of names and designs in the other issue. This is more a self-critical look at my design and architecture suggestions there than a commentary on your implementation, which seems to do a great job of implementing the thoughts there.

What do you think about the name change and/or putting the methods on the model? I'm particularly not sure if moving things to the model is the right thing to do at this point...

**Comment by saulshanabrook** [comment]
@jasongrout will push a rename and then this will be good to go.

**Comment by jasongrout** [comment]
This should now work as a keyboard shortcut:

```json5
{
    command: "notebook:replace-selection",
    selector: ".jp-Notebook:focus",
    keys: ["Accel '"],
    args: {text: 'ABC'}
}
```

Rather than have a hardcoded function that provides a single command for notebooks, consoles, and editors (which seemed unnecessarily limiting?), I introduced a utility command that lets you compose commands. This will run through each command and execute the first enabled one. For example, here is how to have a single keyboard shortcut to insert text in the console, the file editor, or the notebook, whichever happens to be focused.

```json5
{
    command: "apputils:run-first-enabled",
    selector: "body",
    keys: ["Accel '"],
    args: {
        commands: [
            "console:replace-selection",
            "fileeditor:replace-selection",
            "notebook:replace-selection",
            ],
            args: {text: 'AAA'}}
}
```

**Comment by jasongrout** [comment]
I think this is ready for a functional review. I see a few places the docs could be cleaned up, and I haven't looked at the test issues pointed about above.

**Comment by jasongrout** [comment]
> I currently have the tests for codeeditor and console, but am unable to get the notebook tests working.

@dLamSlo8 - did you push your tests to this branch? Would you mind doing so?

**Comment by jasongrout** [comment]
> This works for me. Had to remove `:focus` modifier on notebook though for Jason's example.

Yes, that sounds right. I copied that selector from the command-mode shortcuts, but in this case the editor is actually the one selected.

**Pull request merged**
