### PR TITLE
Creates a new accordion panel with toolbar in the ui-components package

### PR DESCRIPTION
**Pull request by hbcarlos**
## References
Solves #11325

## Code changes
This PR Creates a new widget based on the `AccordionPanel` that uses panels with toolbar in the accordion widget.
Moves part of the already existing logic in the `@jupyterlab/debugger` package to the `@jupyterlab/ui-components` package so we can reuse it everywhere. It also removes some fixes that were moved upstream.

## User-facing changes

Styling is more consistent with the other panels:

image

## Backwards-incompatible changes

```ts
export interface ISidebar extends Panel
```

This implies that it exposes `addWidget`, `insertWidget`, `widgets` instead of `addItem`, `insertItem` and `items`. To be more coherent to a Lumino `Panel` widget API. It should not impact downstream extension, as they are unlikely to add panels to the debugger sidebar.

### CODE REVIEW

**Comment by fcollonval** [comment]
@hbcarlos most of the logic I want is in. But I still have some issues with the latest commit:
- [ ] Click on toolbar items trigger (un-)collapse
- [ ] Styling of the header
- [ ] Check styling in dark mode

I'll look into it tomorrow.

**Comment by hbcarlos** [comment]
Wow, looks fantastic. Thanks for working on this @fcollonval

**Review by fcollonval — APPROVED** [review]

**Comment by fcollonval** [comment]
@trungleduc would you mind reviewing this PR as I contributed quite extensively on this one?

**Comment by trungleduc** [comment]
Hello @fcollonval, I will do it.

**Review by trungleduc — COMMENTED** [review]
It looks neat @hbcarlos @fcollonval! I only add some minor comments above.

**Comment by fcollonval** [comment]
Thanks for the review @trungleduc

**Pull request merged**
