### PR TITLE
Rename Selenium Check to Browser Check

### PR DESCRIPTION
**Pull request by saulshanabrook**
Cleanup from https://github.com/jupyterlab/jupyterlab/pull/4735 which removes need for selenium.

### CODE REVIEW

**Comment by blink1073** [comment]
We should also rename this file to something more generic like "browser_check".  The knock-on effect is that other repos using `jupyterlab.selenium_check` in CI will need updating.  

https://github.com/search?q=org%3Ajupyterlab+selenium_check&type=Code

**Comment by saulshanabrook** [comment]
And some more references in other repos we could send PRs to https://github.com/search?q=%22-m+jupyterlab.selenium_check%22&type=Code

**Comment by blink1073** [comment]
Did you want to make the changes in this PR?  We also need to update the name of the variable used [here](https://github.com/jupyterlab/jupyterlab/blob/56de6c0f45e3545e6d54fba51be7e364de8e9bb7/dev_mode/index.js).

**Comment by saulshanabrook** [comment]
Yep, thanks for the reminder.

**Comment by saulshanabrook** [comment]
You think it's worth it to change the name? I didn't realize that changing how this worked (from selenium to chrome debug protocol) would be breaking.

**Comment by blink1073** [comment]
I think so.  It was a mistake to tie it to a particular tool to begin with.  Now is as good a time as any to correct that mistake.

**Comment by jasongrout** [comment]
Putting into the 0.33 milestone, feel free to adjust.

**Comment by jasongrout** [comment]
@saulshanabrook - should this go into 0.33?

**Comment by saulshanabrook** [comment]
@jasongrout Yeah.

**Comment by saulshanabrook** [comment]
I kept the `selenium_check.py` file but it just aliases the `browser_check.py` file so that existing code that runs those tests won't break. It should print a deprecation warning, however, if you use the old file. If CI tests pass, this is good to go for me.

**Comment by ian-r-rose** [comment]
Thanks @saulshanabrook

**Comment by ian-r-rose** [comment]
Looks like a real test failure. I don't think a `DeprecationWarning` should be `raise`d.

**Comment by saulshanabrook** [comment]
Thanks @ian-r-rose for reviewing.

**Pull request merged**
