### PR TITLE
Update minimum notebook version

### LINKED ISSUE #5246: labapp.py # AttributeError: 'LabApp' object has no attribute 'quit_button'
update jupyterlab with pip - after that i get this error.
After removing the line 206 - the app runs normaly

```
Traceback (most recent call last):
  File "/home/rened/anaconda3/bin/jupyter-lab", line 11, in <module>
    sys.exit(main())
  File "/home/rened/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/rened/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/rened/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/rened/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "/home/rened/anaconda3/lib/python3.6/site-packages/jupyterlab/labapp.py", line 206, in init_webapp
    *settings['page_config_data']['quit_button'] = self.quit_button*
AttributeError: 'LabApp' object has no attribute 'quit_button'
```

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #5246

### CODE REVIEW

**Comment by jasongrout** [comment]
Not everyone can update to the most recent version of the notebook. I'll look into if there is a way to support older versions still.

**Comment by blink1073** [comment]
We could add a shim over the old option name.

**Comment by jasongrout** [comment]
That would be great.

**Comment by blink1073** [comment]
To be clear, I am not volunteering to do so.  I am finishing up another task and them I'm afk for the long weekend.

**Comment by blink1073** [comment]
Closing in favor of #5252

**Pull request closed without merging**
