### PR TITLE
Use setRelativeSizes to set initial width of side panel.

### LINKED ISSUE #5314: sidebar - separate default width from minimum width
For sidebar extensions, like the File browser, the minimum width also ends up the default width. We changed that to a variable and shrank it over in #5245, but it would be nice to have a default width be different from the minimum.

### PR DESCRIPTION
**Pull request by ellisonbg**
Fixes #5314

This makes the initial width of the L sidebar separate from its minimum size:

* Uses `SplitPanel.setRelativeSizes` to size the L panel and dock panel using relative sizes. The current ratio or 1:3, which makes the L sidebar around 300px on a 1280 wide screen (close to what 0.34 was).
* Users can make it narrower, down to the max of the min-size of the stacked panel children. This does mean that extensions can create sidebar content that has a larger min-size and that will be respected (this PR doesn't change that, just clarifying).
* This sizing approach should only be used the first time a user loads lab. From then on, the application state should save the width the user has set interactively (there is a separate bug preventing this from working).
* Ran into a couple of other bugs in the sidebar related to this that I will open issues for (they were pre-existing).

Future things to investigate:

* Do some actual design work to answer the underlying questions:
  - What are the design considerations for setting the initial width of the L/R sidebar?
  - What is an appropriate static or relative width based on those considerations?
  - Should different sidebar panels have different min-size values?
  - Is static or relative sizing more appropriate?
* Implementation question:
  - How to set the initial width of the R side panel in a relative manner?
* Fix pre-existing bugs:
  - Width of side panels is not preserved in the application state
  - Moving a panel to the R side collapses the L one

**Screenshots**

Current master with a 250px sidebar width on a 1280px wide MacBook Pro screen:

screen shot 2018-10-02 at 12 49 36 pm

Proposed change on a 1280px wide MacBook Pro Screen (this is very close to the 300px width from previous versions of lab):

screen shot 2018-10-02 at 12 50 08 pm

Proposed change on a crazy wide browser window to show how the relative sizing is working:

screen shot 2018-10-02 at 12 52 05 pm

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks. Certainly a lot to think about!

For an initial go at this, why set the right size to 0? Why not set it to 1 to be symmetric? (if someone puts a panel over to the right side, I'd imagine they'd expect it to be the same width).

**Comment by jasongrout** [comment]
Also, since we now have the default and minimum width decoupled, can we make the default width something more like 100-150px?

**Comment by ellisonbg** [comment]
OK, pushed the following changes:

* Made the relative sizing of the L/R sidepanels symmetric.
* Reduced the relative sizes of the L/R sidepanels slightly. In practice, this ends up being something in the middle of the 250px and 300px setting. May need some fine tuning, but I got to this point by testing with browser windows at a wide range of sizes, trying to find something that works well "on average"
* At the request of @jasongrout I reduced the min-size of the L/R sidebars further to 150px.

**Comment by jasongrout** [comment]
Thanks! I'll take it for a spin and merge. Thanks for spending time on this.

**Comment by jasongrout** [comment]
I bumped the minimum width to 180px. I noticed that at 150px, the buttons in the filebrowser overflowed and disappeared, and the shutdown buttons in the running tab overwrote the filenames.

150px:

screen shot 2018-10-02 at 7 57 18 pm
screen shot 2018-10-02 at 7 57 28 pm


180px:

screen shot 2018-10-02 at 7 59 12 pm

screen shot 2018-10-02 at 7 59 21 pm

**Comment by ellisonbg** [comment]
+1

**Comment by jasongrout** [comment]
Waiting for tests to pass before merging...

**Pull request merged**
