### PR TITLE
Manually refresh on codemirror undo/redo.

### LINKED ISSUE #5872: Undoing and redoing autocompletion make the editor blank
I'm using JupyterLab 0.35.4 .
Each of Undoing, redoing and autocompletion works well.
But undoing and redoing autocompletion make the editor blank, sometimes (especially when the text file is large).

autocompletion 
undo_auto2
undo_auto3
and undo(ctrl+z)
undo_auto4

Then, editor is blank.
Editor returns to normal, after clicking editor.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes some issues with codemirror rendering upon undo/redo with completions. `refresh()` is potentially an expensive call, but I couldn't figure out another way to fix this. I'm not sure of the underlying cause, which is likely deep in the CodeMirror renderer. Fixes #5872 .

I also see some issues around cursor placement with completions. Specifically, invoking the completer resets the text editor content, and that can cause the editor to lose cursor position. But that is orthogonal to this problem.

## References

#5872 

## Code changes

Manual call to `Editor.refresh()` on redo/undo.

## User-facing changes

Fix of some intermittent rendering issues upon undo/redo.

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jasongrout** [comment]
Do you know why codemirror isn't handling this itself? Are we still using codemirror's undo?

**Comment by jasongrout** [comment]
In other words, should we be opening or searching for a codemirror issue?

**Comment by ian-r-rose** [comment]
Yes, we are still using codemirror's undo. Let me see if I can reproduce on the official demo.

**Comment by ian-r-rose** [comment]
Ah, this is hard to reproduce on the demo because it involves programmatic resetting of the editor content, as is done in the `completer`.

**Comment by jasongrout** [comment]
Can you at least add a TODO note that this is a workaround and deserves deeper investigation and point to the issue/pr?

**Comment by ian-r-rose** [comment]
Yeah, I'll spend a few more minutes seeing if I can figure out what's going on, otherwise will add a TODO note.

**Comment by blink1073** [comment]
Should we make `.refresh()` internally use a `Debouncer`?

**Comment by ian-r-rose** [comment]
That seems reasonable. Any thoughts on a good interval?

**Comment by blink1073** [comment]
250ms?

**Comment by jasongrout** [comment]
Closing in deference to #6409.

**Comment by ian-r-rose** [comment]
I guess this is your answer @jasongrout?

**Comment by jasongrout** [comment]
Sorry, didn't mean to be heavy-handed. I thought your other solution was much better, and that you had diagnosed what the real issue was. If you want to do this in the meantime as a workaround, that's fine too.

**Comment by ian-r-rose** [comment]
Nope, not a problem, I like the other solution better as well :)

**Pull request closed without merging**
