### PR TITLE
Fix a wrong argument when calling 'renderMimeVariable'

### PR DESCRIPTION
**Pull request by brichet**
The debugger tree view calls the `debugger:render-mime-variable` command with the `variablesReference` argument instead of the `frameId`.
This PR fixes it.

## Code changes

Arguments of  `debugger:render-mime-variable` command called in tree view with the `Render Variable` button.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
Would you be able to add a test for this (jest or galata, whichever is easier)?

**Comment by fcollonval** [comment]
@brichet do you have time to add the tests?

**Comment by brichet** [comment]
@krassowski @fcollonval yes, I can add a test on the rich variable inspector

**Review by fcollonval — APPROVED** [review]
Thanks @brichet

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.6.x

**Pull request merged**
