### PR TITLE
feat: prompt to save files before rebuild

### LINKED ISSUE #7372: Prompt to save files before rebuild
Hopefully title describes it well. Before a rebuild is triggered (e.g., when installing an extension), the user should be prompted to save all changes. Otherwise, the user might discover that all unsaved progress is lost after rebuilding and relaunching JupterLab.

### PR DESCRIPTION
**Pull request by RedTn**
## References

Closes #7372

## Code changes

Updated the existing dialogs for build success to now allow a "save and reload" function. Cancel button also reloads but does not save. Clicking outside the dialog, or the 'x' button closes the dialog without reloading or saving.

## User-facing changes

Implemented the UI as suggested by @isabela-pf, with a slight tweak to the location of the 'x' button. Getting the button to appear in the top-left requires a bit more hacking, the dialog uses padding to achieve the borders and inserting an element there will be tricky.

Before:
image

After: 
image

## Backwards-incompatible changes

Unsure

### CODE REVIEW

**Comment by RedTn** [comment]
I'm not entirely sure why the test was canceled 
image
I'm seeing from the other PRs (merged & opened) that this was canceled for others.
Feel free to let me know if this is something I need to fix before this can be merged, thanks!

**Comment by telamonian** [comment]
Nice work.

@tgeorgeux I don't know, what do you think? On which side should a dialog box's "feck off" button be placed?

**Comment by RedTn** [comment]
> Nice work. Don't worry about the usage test, it has standing issues.
> 
> @tgeorgeux I don't know, what do you think? On which side should a dialog box's "feck off" button be placed?

open to new suggestions on where to place it

**Comment by telamonian** [comment]
@RedTn

@tgeorgeux is jlab's resident UI/UX designer. Us code monkeys generally try to get his input on non-trivial (or at least non-obvious) questions of aesthetics.

**Comment by RedTn** [comment]
i don't believe there is an "X" button for any other dialogs, not from a quick ctrl+f search nor in my jlab usage. I think the "X" has been implied from most of the dialogs having a "cancel" button, but from the UX it looks like "reload without saving" is behaving as a pseudo-cancel in this case

**Comment by tgeorgeux** [comment]
I think top right is the correct placement for the "X" button, I would right align it with the buttons and top align it with the "Build Complete". 

I am not sure the X communicates clearly what will happen if you dismiss the dialogue @telamonian is there any situation where one would want to keep the current JupyterLab window open after building without reloading?

**Comment by RedTn** [comment]
I can update the placement of the "X" button if we know for sure we want to keep it @telamonian

**Comment by telamonian** [comment]
> is there any situation where one would want to keep the current JupyterLab window open after building without reloading?

@tgeorgeux I can think of a few. The most obvious one would be when you're editing a file, the dialog box pops up, and you want to keep editing the file, but don't want to save the changes. The X in this case makes your problem/annoyance go away. Which I like! Though we may want to then add something that will do another build check in 15 min, or something.

@RedTn I've tested out your dialog box (out of curiosity, how were you testing the dialog/making pictures? It was not easy to summon the build dialog from dev-mode), and I think that once you implement @tgeorgeux's suggested tweaks this PR will be good to go from a UI/UX perspective.

My one remaining problem is the `IButton.reload: boolean` property you added. Everything about the `Dialog` and `IButton` api is already a tangled mess, and I am loathe to make it worse. At the very least, `reload` is not a good name for "the second button action" property, since presumably there's plenty of contexts in which a dialog box can be opened and in which `reload` in not a relevant action.

If you can refactor away `IButton.reload` somehow, I think that would be best. But I'd settle for a decent rename, from `reload` to something more generic and `Dialog`-y

**Comment by tgeorgeux** [comment]
I am hesitant to leave the X button (or the cancel option) in at all. It seems to me to be a small upside with a potentially large downside. But I am not opposed to merging this out and trying it this way in the slightest. 

Thanks again for doing this @RedTn !

**Comment by RedTn** [comment]
image

New dialog. As for testing, I had to comment out alot of statements to force the dialog to pop up, otherwise jupyterlab keeps recompiling when I didn't want it to.

**Comment by tgeorgeux** [comment]
That looks great. I'm +1 to merge.

**Comment by isabela-pf** [comment]
Sorry for the delay replying to this thread. I'm following up to clarify the thought behind some of the design choices made originally on #7372. 
@tgeorgeux mentioned
> I am not sure the X communicates clearly what will happen if you dismiss the dialogue

At one point it came down to choosing between having three button options in the dialog (cancel, reload without saving, and save and reload) or letting the cancel option be part of dismissing the dialog (the X being the standard option). I haven't found other dialogs in JupyterLab that allow for three buttons, so it seemed like both these options would go beyond existing JupyterLab conventions, but all three options do need to be represented. 

I thought the X to close dialog might be a choice that would serve JupyterLab longer term because it is still standard UI and other dialogs could benefit from it. I was worried that a three button option would encourage dialogs with way too many buttons in the future.

I don't want to slow this down since I saw Tim said he's good to merge, and I think this is a good chance to test if the X will be clear enough in a dialog. I am curious why people think the right side is the best placement for the X, if anyone wants to reply.

**Comment by jasongrout** [comment]
> I am curious why people think the right side is the best placement for the X, if anyone wants to reply.

As a guess: on windows and windows-like window managers, the X is in the top right. Our tabs (and usually tabs in general) have the X on the right. The kernel listing has "shutdown" on the right.

(I personally like having a window manager where "close" is on the left and "minimize"/"maximize" is on the right so I don't mistakenly close something, but I don't think that's standard anywhere...)

**Comment by blink1073** [comment]
Congratulations on your first contribution to JupyterLab @RedTn!

**Pull request merged**
