### PR TITLE
Align extension migration docs with the latest extension template

### PR DESCRIPTION
**Pull request by jtpio**
## References

Follow-up to https://github.com/jupyterlab/jupyterlab/pull/16414

There is another place in the docs where the `copier` dependencies are mentioned: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#upgrading-extension-using-the-upgrade-script

## Code changes

Extension migration docs update.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
Do we also want to update the pip variant dependencies defined in:

https://github.com/jupyterlab/jupyterlab/blob/963cbd6e76fd3a7b4be640662405e62a68268376/pyproject.toml#L124-L130

And then line below to say `--trust`:

https://github.com/jupyterlab/jupyterlab/blob/963cbd6e76fd3a7b4be640662405e62a68268376/jupyterlab/upgrade_extension.py#L344

**Comment by jtpio** [comment]
Yes that makes sense, thanks!

**Review by krassowski — APPROVED** [review]
Thank you!

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.2.x

**Pull request merged**
