### PR TITLE
[2.2.x] Add content-visibility on Cell CSS class

### PR DESCRIPTION
**Pull request by echarles**
Fixes https://github.com/jupyterlab/jupyterlab/issues/8969 for 2.2.x branch

We may also open this for master if we have positive benchmarks results.

### CODE REVIEW

**Comment by echarles** [comment]
cc/ @afshin

**Comment by echarles** [comment]
Just to confirm, the is only supported in Chrome 85+ https://developers.google.com/web/updates/2020/08/nic85

**Review by saulshanabrook — APPROVED** [review]
This works for me locally! Looks good.

**Comment by echarles** [comment]
Thx a bunch @saulshanabrook for the review and merge. Much appreciated!

**Pull request merged**
