### PR TITLE
Add license-webpack-plugin

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- for #9518
 
## Code changes

Adds `LicenseWebpackPlugin` to:
- `@jupyterlab/builder`
- the main `jupyterlab/staging` build template
- `dev_mode` 

This is rather _expensive_ from a build perspective, but hand-made open source license finding is _way more expensive_ in human time. This plugin could also be reserved just for production builds.

The `static` shows this ends up being 400kb and 8600+ lines, but this will only increase the tarball size by a bit, as its all very compressible.

## User-facing changes

- Users would be able to peruse the licenses of the software they are running in their browser by opening `http://localhost:8888/static/lab/third-party-licenses.txt` and the similar file for federated extensions.

## Backwards-incompatible changes

N/A though I guess it's possible that an extension could have a `third-party-licenses.txt` with which this would conflict... i guess it could be made more explicit, e.g. `jupyterlab-third-party-licenses.txt`.

## Follow-on

- Add a _Help_ menu item to render the core third-party license file and a discovery mechanism to also include all the licenses from federated extensions
- Add some teeth to it, to block builds based on SPDX identifiers (e.g. AGPL) which are troublesome for downstreams
- Add this to the right field on the conda-forge feedstock :P

### CODE REVIEW

**Comment by bollwyvl** [comment]
Actually, thinking about it more: having the licenses as a structured data file is probably more useful than a text dump (or markdown, though that would be easy as well)... looking into it, it's relatively easy to add a `renderLicenses` parameter to the plugin options, and given the number of places this appears, may make sense to hoist to a `WPPlugin` in `builder`... currently having some issues getting it to build on core, probably need some series of `jlpm link`s...

**Comment by bollwyvl** [comment]
And oof: another finding: ehm, none of our npm distributions include licenses :P

**Comment by bollwyvl** [comment]
Merged in the 3.0.1 changes... still think this needs addressing...

**Comment by vidartf** [comment]
> This is rather expensive from a build perspective, but hand-made open source license finding is way more expensive in human time. This plugin could also be reserved just for production builds.

I would say that limiting this to only production builds makes sense (dev builds should not normally be disted).

**Comment by bollwyvl** [comment]
Getting into the parts of the build that I just kinda hand-wave and leave for others... :blush:

**Comment by afshin** [comment]
It looks like we need to increase the timeout here to accommodate the longer build time:

https://github.com/jupyterlab/jupyterlab/blob/1d91d7aa92ddb04eba2e71883d3ba9569e7bb752/jupyterlab/pytest_plugin.py#L106

**Comment by bollwyvl** [comment]
Looks like this was a performance regression fixed in the newest version... will push shortly with a re-solve.

**Comment by bollwyvl** [comment]
Oh, windows. 

```
ERROR in   HookWebpackError: ENOENT: no such file or directory, open '\package.json'
```

I don't what to do.... i really, really don't care to debug windows issues on lab builds anymore, having lost too much of the last couple years to it.

**Review by blink1073 — APPROVED** [review]
Fantastic, thanks @bollwyvl!

**Comment by vidartf** [comment]
> 
> 
> Oh, windows.
> 
> ```
> ERROR in   HookWebpackError: ENOENT: no such file or directory, open '\package.json'
> ```
> 
> I don't what to do.... i really, really don't care to debug windows issues on lab builds anymore, having lost too much of the last couple years to it.

Can I get away with not debugging issues on Linux as well then? :)

**Comment by jasongrout** [comment]
Just to be clear, was this error in windows fixed by Darian in the commit above, before the merge?

**Comment by afshin** [comment]
@jasongrout That seems to be the case, yes 😂

**Comment by bollwyvl** [comment]
Aw dang, missed this in the churn, thanks so much folks! Super save @afshin! I look forward to shipping absurdly large license files for all my extensions (_looks at lsp and groans_).

> @vidartf Can I get away with not debugging issues on Linux as well then? :)

We've all hustled a lot over the years to keep the 80% market share happy, and your work over on jupyter_client was sterling. But I feel like in the federated module era, "production" webpack issues are not really a thing that has to work _work_ on an underpowered windows CI box with admin rights to fix long paths, etc.... a lot of users won't have something that looks like that. 

I guess I should follow this up with putting licenses in all the packages to squash the remaining warnings, and adding that to integrity...

**Comment by vidartf** [comment]
> But I feel like in the federated module era, "production" webpack issues are not really a thing that has to work work on an underpowered windows CI box with admin rights to fix long paths, etc...

I fully agree that not aspects need to work, agreed. So I have no qualms about skipping certain tests when the stack is being difficult.

**Comment by bollwyvl** [comment]
Uhoh... doing as full-a-build-as-i-can doesn't result in any `third-party-licenses.txt` being created...

**Comment by bollwyvl** [comment]
Ah, they are ending up in 
```
$PREFIX/share/jupyter/lab/static/third-party-licenses.txt
$PREFIX/share/jupyter/lab/staging/build/third-party-licenses.txt
```

these however do not end up in the `whl` or `tar.gz`... hmm....

**Comment by bollwyvl** [comment]
oooohhh, is this because the `sdist` and `bdist_whl` actually use the published npm packages, and that hasn't happened yet? can i fake it with `verdaccio` or something? `jlpm link`?

**Comment by blink1073** [comment]
I'll cut a new alpha

**Comment by bollwyvl** [comment]
no, nm... i had (surprise) some dirty state. Blowing _everything_ away i am getting them:
```
...
adding 'jupyterlab-3.1.0a0.data/data/share/jupyter/lab/static/third-party-licenses.txt'
adding 'jupyterlab-3.1.0a0.data/data/share/jupyter/lab/themes/@jupyterlab/theme-dark-extension/index.css'
adding 'jupyterlab-3.1.0a0.data/data/share/jupyter/lab/themes/@jupyterlab/theme-dark-extension/index.js'
adding 'jupyterlab-3.1.0a0.data/data/share/jupyter/lab/themes/@jupyterlab/theme-light-extension/index.css'
adding 'jupyterlab-3.1.0a0.data/data/share/jupyter/lab/themes/@jupyterlab/theme-light-extension/index.js'
adding 'jupyterlab-3.1.0a0.dist-info/LICENSE'
adding 'jupyterlab-3.1.0a0.dist-info/METADATA'
adding 'jupyterlab-3.1.0a0.dist-info/WHEEL'
adding 'jupyterlab-3.1.0a0.dist-info/entry_points.txt'
adding 'jupyterlab-3.1.0a0.dist-info/top_level.txt'
adding 'jupyterlab-3.1.0a0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel

```

**Comment by blink1073** [comment]
Went ahead and released anyway: https://pypi.org/project/jupyterlab/3.1.0a1/

**Comment by bollwyvl** [comment]
Somebody else hit the `\package.json` issue with module federation:

https://github.com/xz64/license-webpack-plugin/issues/95

**Comment by xz64** [comment]
@bollwyvl  Hi, I am the developer of license-webpack-plugin. There's a chance you may still run into the same issue with v2.3.12. If this happens, can you send me some steps to reproduce the issue on this issue ( https://github.com/xz64/license-webpack-plugin/issues/95 ) ? It would help me ensure I am fixing all the scenarios.

**Comment by bollwyvl** [comment]
@xz64 thanks for stopping by! I was only seeing the `\package.json` error on windows, and have no idea which steps created them, unfortunately, as linux was working at that time.

Over on #9779, I'm doing some more work on it, and have bumped to 2.3.13, and have yet to encounter the error, but we have some other build stuff that might be hiding my changes from me.

We're building a number of webpack excursions:
- a local development system (built from source and upstream npm packages)
- a tool for extension authors (built from source and upstream npm packages)
- a production app to be released (built from npm packages)
- a (mostly deprecated) end-user tool for rebuilding everything (built from npm packages, but maybe local stuff)

Each of these can be built with a lot of options (minimize, production, etc.) We're currently trying to ensure that production builds of all of the a above include license metadata (on #9779 i'm moving it to JSON).

I think the problem arose in the test of the last one on windows, but can't be entirely sure.

**Pull request merged**
