### PR TITLE
Update base.css

### PR DESCRIPTION
**Pull request by siddartha-10**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/12727

### CODE REVIEW

**Comment by siddartha-10** [comment]
@fcollonval this issue is based on "Inconsistent font size in settings #12727" It was a good first issue so instead of me creating a branch and then making a pull request it seemed like i directly used the master branch and then committed so then I had to go back and make new branch then make a PR.
basically this is my first PR. Sorry if i am not clear.

**Comment by fcollonval** [comment]
> this issue is based on "Inconsistent font size in settings #12727" It was a good first issue so instead of me creating a branch and then making a pull request it seemed like i directly used the master branch and then committed so then I had to go back and make new branch then make a PR.
basically this is my first PR. Sorry if i am not clear.

Thanks for your contribution. When opening a PR, we provide a template that we expect contributor to fill to provide information on the PR (like related issue, what has changed, some screenshots before / after,...). I updated the first comment to add the issue.

Note: as you reverted your changes in the second commit, this PR does not change anything yet. Was the reversion intentional? Do you need help?

**Comment by siddartha-10** [comment]
> > this issue is based on "Inconsistent font size in settings #12727" It was a good first issue so instead of me creating a branch and then making a pull request it seemed like i directly used the master branch and then committed so then I had to go back and make new branch then make a PR.
> > basically this is my first PR. Sorry if i am not clear.
> 
> Thanks for your contribution. When opening a PR, we provide a template that we expect contributor to fill to provide information on the PR (like related issue, what has changed, some screenshots before / after,...). I updated the first comment to add the issue.
> 
> Note: as you reverted your changes in the second commit, this PR does not change anything yet. Was the reversion intentional? Do you need help?

@fcollonval As i mentioned in the above comment that at first i didn't create a new branch and directly committed the changes to the master branch the changes have been made with me making a PR. Then I reverted my changes and made another commit from my branch and made a PR

**Comment by fcollonval** [comment]
> Then I reverted my changes and made another commit from my branch and made a PR

Then you need to reset that branch to keep only the first commit [65b11c8](https://github.com/jupyterlab/jupyterlab/pull/12783/commits/65b11c81ec5ca52884b736a67914c718f6700e06) because right now your branch siddarth does not contain any changes (the second commit revert the first one) - you can see at the top of the PR that the files changed count is equal to zero.

**Comment by siddartha-10** [comment]
> > Then I reverted my changes and made another commit from my branch and made a PR
> 
> Then you need to reset that branch to keep only the first commit [65b11c8](https://github.com/jupyterlab/jupyterlab/pull/12783/commits/65b11c81ec5ca52884b736a67914c718f6700e06) because right now your branch siddarth does not contain any changes (the second commit revert the first one) - you can see at the top of the PR that the files changed count is equal to zero.

@fcollonval can you help me reset that branch to keep the first commit or should i create a new branch and then do the changes again and create another PR

**Comment by siddartha-10** [comment]
> Sure ensure to be on the `siddarth` branch then run the following git command:
> 
> ```
> git reset --hard 65b11c81ec5ca52884b736a67914c718f6700e06
> ```
> 
> Then force push the branch with:
> 
> ```
> git push --force-with-lease
> ```

@fcollonval i have done the first command but i am getting this error while running the second command.
remote: Permission to siddartha-10/jupyterlab.git denied to siddartha1018.
fatal: unable to access 'https://github.com/siddartha-10/jupyterlab.git/': The requested URL returned error: 403

**Comment by fcollonval** [comment]
What operating system are you using?

**Comment by siddartha-10** [comment]
> What operating system are you using?

Windows

**Comment by fcollonval** [comment]
How did you installed git? Did you used https://gitforwindows.org/?

**Comment by siddartha-10** [comment]
> How did you installed git? Did you use https://gitforwindows.org/?

Yep i installed using the above mentioned link

**Comment by fcollonval** [comment]
Do you see any mention of `credential.helper` when you execute `git config --list`?

**Comment by fcollonval** [comment]
ok then I don't get why you are not prompt to provide your credentials...

I will try to reset your branch.

**Comment by siddartha-10** [comment]
> ok then I don't get why you are not prompt to provide your credentials...
> 
> I will try to reset your branch.

I am trying just give me sometime. It must be problem with the user name i believe.

**Comment by fcollonval** [comment]
Ok it seems you succeeded to push.

**Comment by siddartha-10** [comment]
> Ok it seems you succeeded to push.

yeah

**Review by fcollonval — APPROVED** [review]
Thanks and congratulations on your first PR @siddartha-10 

> CI failure is not related

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.4.x

**Comment by siddartha-10** [comment]
> Thanks and congratulations on your first PR @siddartha-10
> 
> > CI failure is not related

@fcollonval Thank you so much for helping me out. Is there a way that i could contact you personally if yes please provide more info.

**Comment by fcollonval** [comment]
You can reach me on https://gitter.im if you want.

**Pull request merged**
