### PR TITLE
add codemirror simple mode addon

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- derived from https://github.com/jupyterlab/jupyterlab/issues/9044#issuecomment-702457156

## Code changes

Adds `codemirror/addon/mode/simple` (8kb) to the "blessed" CodeMirror plugins shipped by default.

This would allow a downstream to use the very terse (e.g. JSON-serializable) codemirror [simple mode](https://codemirror.net/demo/simplemode.html), and would make a fine candidate for a short example in https://github.com/jupyterlab/extension-examples

At present, even with #9067, this is not possible without significant hacks (see #9044).

This also adds the `codemirror/typings/codemirror.d.ts`, and extends it with an opinionated `defineSimpleMode` that optionally uses generics to statically validate whether unknown states and tokens are used: it can't tell whether states/tokens _aren't_ used/are reachable, but I'll take it!

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by jasongrout — APPROVED** [review]

**Comment by jasongrout** [comment]
This makes a lot of sense to me!

**Comment by bollwyvl** [comment]
the first fail maybe looks spurious?
- https://github.com/jupyterlab/jupyterlab/pull/9123/checks?check_run_id=1196620592#step:9:3282

Let me know if this would need anything else! I promise a nice extension example using it :yum:!

**Comment by bollwyvl** [comment]
Ah, `simple` is not included in `@types/codemirror`. I've done [partial typings](https://github.com/robots-from-jupyter/robotkernel/blob/master/src/jupyterlab_robotmode/src/mode.ts#L75-L105) for it before...

**Comment by bollwyvl** [comment]
Here's a more thorough typing. The fun thing here is using the optional generics, it will give completion/linting when a transition to a non-existent state is given, or if it emits a token for which you had not planned.

I'm not the super-handiest with some of the deeper ways of getting this kind of behavior with `.ts.d`, but it's sure nice when it works!

```ts
  export interface ISimpleMode<T> extends CodeMirror.Mode<T> {
    dontIndentStates?: T[];
  }

  /**
   * An implementation of the CodeMirror simple mode object
   * https://github.com/codemirror/CodeMirror/blob/master/addon/mode/simple.js
   *
   * Optionally generic over [S]tate names and [T]okens
   */
  interface ISimpleState<S, T> {
    /**
     * The regular expression that matches the token. May be a string or a
     * regex object. When a regex, the ignoreCase flag will be taken into
     * account when matching the token. This regex has to capture groups when
     * the token property is an array. If it captures groups, it must capture
     * all of the string (since JS provides no way to find out where a group
     * matched).
     */
    regex: string | RegExp;
    /**
     * An optional token style. Multiple styles can be specified by separating
     * them with dots or spaces. When this property holds an array of token styles,
     * the regex for this rule must capture a group for each array item.
     */
    token?: T | T[] | null | (T | null)[];
    /**
     * When true, this token will only match at the start of the line.
     * (The ^ regexp marker doesn't work as you'd expect in this context because
     * of limitations in JavaScript's RegExp API.)
     */
    sol?: boolean;
    /**
     * When a next property is present, the mode will transfer to the state
     * named by the property when the token is encountered.
     */
    next?: S;
    /**
     * Like next, but instead replacing the current state by the new state, the
     * current state is kept on a stack, and can be returned to with the pop
     * directive.
     */
    push?: S;
    /**
     * When true, and there is another state on the state stack, will cause the
     * mode to pop that state off the stack and transition to it.
     */
    pop?: boolean;
    /**
     * Can be used to embed another mode inside a mode. When present, must hold
     * an object with a spec property that describes the embedded mode, and an
     * optional end end property that specifies the regexp that will end the
     * extent of the mode. When a persistent property is set (and true), the
     * nested mode's state will be preserved between occurrences of the mode.
     */
    mode?: {
      spec: string;
      end?: string | RegExp;
      persistent?: boolean;
    };
    /**
     * When true, this token changes the indentation to be one unit more than
     * the current line's indentation.
     */
    indent?: boolean;
    /**
     * When true, this token will pop one scope off the indentation stack.
     */
    dedent?: boolean;
    /**
     * If a token has its dedent property set, it will, by default, cause lines
     * where it appears at the start to be dedented. Set this property to false
     * to prevent that behavior.
     */
    dedentIfLineStart?: boolean;

    /**
     * The meta property contains global information about the mode. It
     * can contain properties like lineComment, which are supported by
     * all modes, and also directives like dontIndentStates, which are
     * specific to simple modes.
     */
    meta?: ISimpleMode<S>;
  }

  /** A string-keyed set of simple state lists */
  export type TSimpleStates<S = string, T = any> = {
    [key: string]: ISimpleState<S, T>[];
  };

  export interface ISimpleMeta<S, T> {
    meta: ISimpleMode<S>;
  }

  export type TTopSimpleState<S, T> = Partial<TSimpleStates<S, T> & ISimpleMeta<S, T>>;

  function simpleMode<S, T>(config: any, states: TTopSimpleState<S, T>): void;

  function defineSimpleMode<S, T>(
    name: string,
    states: TTopSimpleState<S, T>
  ): void;

```

**Comment by bollwyvl** [comment]
Current non-lint [apputils kernel fail](https://github.com/jupyterlab/jupyterlab/pull/9123/checks?check_run_id=1220381674#step:9:3267) looks spurious...

**Comment by bollwyvl** [comment]
Ok, down to examples and link check flake... this is probably good to go, pending review!

**Review by afshin — APPROVED** [review]
Thank you!

👍

**Pull request merged**
