### PR TITLE
[Do not merge] Try installing tornado 6 from master.

### PR DESCRIPTION
**Pull request by ian-r-rose**
## References

#6131 
Experimenting with unpinning tornado

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Uh oh: `tornado.websocket.WebSocketClosedError`

**Comment by ian-r-rose** [comment]
:green_apple: :green_book: :green_heart: :green_salad: :greenland: :frog: :four_leaf_clover: :leaves: :palm_tree: :christmas_tree: :deciduous_tree: :evergreen_tree: :tanabata_tree: :snake: :lizard: :crocodile: :cactus: :shirt:

**Comment by jasongrout** [comment]
Are those all the green emojis?

**Comment by ian-r-rose** [comment]
At least a bunch of them, with apologies to @bollwyvl

**Comment by ian-r-rose** [comment]
Closing in favor of #6694

**Pull request closed without merging**
