### PR TITLE
Add language and tab editor settings

### LINKED ISSUE #2351: No syntax highlighting for Dockerfile, Makefile, etc
If I create a file with an extension such as "main.c" or "main.py" or 'main.rb' I get syntax highlighting for it.

However, if I create a 'Dockerfile' or 'Makefile', I do not get syntax highlighting.

Poking around, it looks like the mode is being detected properly (in `mode.ts`) but somehow this isn't set or loaded in CodeMirror?

### PR DESCRIPTION
**Pull request by blink1073**
Partially addresses #2382.  Fixes #2351.

<image src="https://user-images.githubusercontent.com/2096628/27033567-8ab868fa-4f3f-11e7-8b3d-9cf53c8d00e1.png" width=400>

<image src="https://user-images.githubusercontent.com/2096628/26938081-c6cab8c0-4c38-11e7-979f-0876297b0e14.png" width=400>

### CODE REVIEW

**Comment by ellisonbg** [comment]
Great! A few possible changes:

* Group the items in the `Editor` menu by whether or not they are per file or global. I would put the per file ones at the top, then a separator, and then the global/settings ones.
* Maybe only include 1,2,4,8 space indent options?
* Add the indent options to the `Editor` command palette.

I did test with a dockerfile and a Makefile and it completely solves the pain point with those file types!

**Comment by blink1073** [comment]
Updated

**Comment by yuvipanda** [comment]
Hey what about us who use 3 spaces?

**Comment by yuvipanda** [comment]
(just kidding, thank you for getting this in!)

**Comment by blink1073** [comment]
\me throws shoe

**Pull request merged**
