### PR TITLE
Fixed up names for high contrast styles, added red

### PR DESCRIPTION
**Pull request by telamonian**
## References

Some minor tweaks to the high contrast styles made during the course of upgrading some extensions to jlab 2.0. Made the high contrast style names clearer, and added `jp-contrast-red`

### CODE REVIEW

**Comment by jasongrout** [comment]
This is backwards incompatible since it changes css variable names in a theme. Did you want to wait until 3.0 for this to merge?

**Comment by jasongrout** [comment]
(to fix this, leave the existing theme variable names there, perhaps with a deprecation note)

**Comment by telamonian** [comment]
@jasongrout Done. All of the removed CSS has been added back in and marked DEPRECATED

**Comment by jasongrout** [comment]
> @jasongrout Done. All of the removed CSS has been added back in and marked DEPRECATED

Thanks. It was added back to ui-components, but it should be added back to the themes, since that is where it was a public api.

**Comment by telamonian** [comment]
> it should be added back to the themes, since that is where it was a public api.

You are not wrong. Alright, since part of my goal here was to tidy up some obfuscated CSS in the themes (and not to make a bigger mess), and since this definitely isn't critical for anything, I think I'll just mark this PR WIP and leave it for 3.0

**Review by krassowski — COMMENTED** [review]
It looks like opportunity missed for 3.0. Still can go into 3.1 I guess. Otherwise needs to wait for 4.0. I have no opinion on deprecation method. 

@agoose77 one of your extensions will need to update [this fragment](https://github.com/agoose77/jupyterlab-markup/blob/1a08d8a35728481821e66f7d4677fde1e11ba44b/src/plugin.ts#L27) once this is merged.

**Comment by agoose77** [comment]
> It looks like opportunity missed for 3.0. Still can go into 3.1 I guess. Otherwise needs to wait for 4.0. I have no opinion on deprecation method.
> 
> @agoose77 one of your extensions will need to update [this fragment](https://github.com/agoose77/jupyterlab-markup/blob/1a08d8a35728481821e66f7d4677fde1e11ba44b/src/plugin.ts#L27) once this is merged.

Thanks for the ping, really appreciate it.

**Comment by jweill-aws** [comment]
There hasn't been any activity on this pull request in over a year. As part of an effort to clean up this repository's pull requests, I'm closing this request. If you would still like to merge this code in, please reopen the request and resolve any outstanding merge conflicts. All of the code and comments will remain in place. Thank you for being part of the JupyterLab community!

**Comment by krassowski** [comment]
Regarding PR cleanup effort: maybe we should keep PRs which are assigned to a milestone (at least other than "Future") open and review on Wednesday meetings before release?

**Pull request closed without merging**
