### PR TITLE
Make codemirror use contenteditable mode everywhere

### PR DESCRIPTION
**Pull request by yuvipanda**
This makes accessibility for screen readers
and other accessibility devices better than
it is now. It still isn't fully functional or
usable, but much better than what it is now.

From http://www.w4a.info/2019/hackathon/

### CODE REVIEW

**Comment by yuvipanda** [comment]
I don't understand why the tests or failing, or what the logs mean :( Help!

**Comment by ian-r-rose** [comment]
This is cool @yuvipanda, I didn't reallize it was this simple to enable `contenteditable` in CodeMirror 5. Do you have any insight as to the tradeoffs with this option? In the CodeMirror 6 [design docs](https://codemirror.net/6/design.html) it discuses how one of the main motivations of the rewrite is to better support `contenteditable`, so I'm wondering whether might be some unintended consequences here. In particular, the design doc says

> Since a fake selection is not going to work well on mobile, we tried to bolt a mode that uses contentEditable onto the existing architecture a few years ago. This works, sometimes, on some mobile browsers, but never really got solid, because the codebase wasn't really built for it.

> And that's one of the things the rewrite addressed. By using contentEditable from the ground up, and stealing some ideas from ProseMirror, we're able to do a lot better than CodeMirror 5.

I think we should also keep an eye on performance. One of the biggest issues we have run into is that codemirror is expensive to refresh, and this can cause problems when moving notebook tabs around. It would be interesting to do some perf testing here.

I'm not sure of the cause of the failure just yet, but this is a pretty major change to a foundational component, so I'm not necessarily *too* surprised there are some issues.

**Comment by ian-r-rose** [comment]
Looks like the tests are failing with this error:
```javascript
this.cm.display.wrapper.ownerDocument.getSelection is not a function
```

Seems like a bug in CodeMirror to me:
https://github.com/codemirror/CodeMirror/blob/c18094eab567211f73050beaa5c3fcceb2133888/src/input/ContentEditableInput.js#L114-L116

**Comment by yuvipanda** [comment]
Yeah I suspect this is a large amount of work nobody has the time for, with marginal at best returns. Let's wait for code mirror 6 or Monaco

**Comment by jasongrout** [comment]
> or Monaco

FYI, it's not clear at all that monaco has a better accessibility story.

**Comment by yuvipanda** [comment]
@jasongrout oh? When I tried out nteract+monaco with the accessibility folks at Berkeley, they found it much more useful than codemirror...

**Comment by jasongrout** [comment]
> When I tried out nteract+monaco with the accessibility folks at Berkeley, they found it much more useful than codemirror...

That's *great* to hear! I thought I looked at it at one point a long time ago and monaco wasn't very accessible. I'm glad it's better than that.

**Comment by yuvipanda** [comment]
@jasongrout yeah, Microsoft put a ton of people working specifically on it. xterm.js is accessible due to work from the same set of people. All for vscode...

**Comment by yuvipanda** [comment]
@jasongrout see https://github.com/Microsoft/monaco-editor/wiki/Monaco-Editor-Accessibility-Guide for more info

**Comment by jasongrout** [comment]
Here is an interesting firefox bug dealing with screenreaders and codemirror: https://bugzilla.mozilla.org/show_bug.cgi?id=919711

**Pull request closed without merging**
