### PR TITLE
Target Typescript compilation to es2015

### LINKED ISSUE #4461: Switch TS to output es2015 code
According to https://kangax.github.io/compat-table/es6/, current browser versions (chrome, firefox, safari, edge) support nearly all es2015 features. I think we should experiment with switching our typescript to output es2015 code. We should probably also upgrade to TS 2.8 while we're at it.

One huge advantage this gives us is *much* more readable async/await compiled code, since the compiled code can natively use generators.

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #4461.

### CODE REVIEW

**Comment by jasongrout** [comment]
@ian-r-rose - I'm running into errors with, for example, this line:

https://github.com/jupyterlab/jupyterlab/blob/3bff3578c796dd50bb3814e3e187f717eb10c659/packages/mainmenu-extension/src/index.ts#L536

How can I index into the extender (which is an IMenuExtender), and why does that give me a string?

**Comment by ian-r-rose** [comment]
I think we should be able to specify the type more strictly with the new conditional mapped types of Typescript 2.8. [Here](
https://www.typescriptlang.org/play/#src=%2F**%0D%0A%20*%20Stub%20interface%0D%0A%20*%2F%0D%0Ainterface%20IExtender%20%7B%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20New%20class%20with%20a%20string%2C%20a%20number%2C%20and%20a%20function%0D%0A%20*%2F%0D%0Aclass%20Extender%20implements%20IExtender%20%7B%0D%0A%20%20%20%20noun%3A%20string%3B%0D%0A%20%20%20%20rank%3A%20number%3B%0D%0A%20%20%20%20func%3A%20()%20%3D%3E%20void%3B%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20A%20type%20that%20corersponds%20to%20the%20string%20properties%20of%20the%20generic%20T%20(e.g.%2C%20'noun')%0D%0A%20*%2F%0D%0Atype%20StringProps%3CT%3E%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%20extends%20string%20%3F%20K%20%3A%20never%20%7D%5Bkeyof%20T%5D%3B%0D%0A%2F**%0D%0A%20*%20A%20type%20that%20corersponds%20to%20the%20string%20properties%20of%20the%20generic%20T%20(e.g.%2C%20'func')%0D%0A%20*%2F%0D%0Atype%20FuncProps%3CT%3E%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%20extends%20Function%20%3F%20K%20%3A%20never%20%7D%5Bkeyof%20T%5D%3B%0D%0A%0D%0Aconst%20ex%20%3D%20new%20Extender()%3B%0D%0Aex.noun%20%3D%20'dog'%3B%0D%0Aex.rank%20%3D%201%3B%0D%0Aex.func%20%3D%20()%20%3D%3E%20%7B%20console.log('hello')%3B%20%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20Return%20the%20label%20specified%20by%20the%20user.%0D%0A%20*%2F%0D%0Afunction%20extractLabel%3CE%20extends%20IExtender%3E(thing%3A%20E%2C%20label%3A%20StringProps%3CE%3E)%20%7B%0D%0A%20%20%20%20return%20thing%5Blabel%5D%3B%0D%0A%7D%0D%0A%0D%0A%2F**%20%0D%0A%20*%20Return%20the%20function%20specified%20by%20the%20user.%0D%0A%20*%2F%0D%0Afunction%20extractFunc%3CE%20extends%20IExtender%3E(thing%3A%20E%2C%20func%3A%20FuncProps%3CE%3E)%20%7B%0D%0A%20%20%20%20return%20thing%5Bfunc%5D%3B%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20Call%20the%20function%20specified%20by%20the%20user.%0D%0A%20*%20%0D%0A%20*%20NOTE%3A%20I%20think%20this%20should%20pass%2C%20since%20we%20know%20that%20thing%5Bfunc%5D%0D%0A%20*%20is%20a%20function%2C%20but%20the%20TS%20compiler%20complains!%0D%0A%20*%2F%0D%0Afunction%20callFunc%3CE%20extends%20IExtender%3E(thing%3A%20E%2C%20func%3A%20FuncProps%3CE%3E)%20%7B%0D%0A%20%20%20%20thing%5Bfunc%5D()%3B%0D%0A%7D%0D%0A%0D%0A%0D%0Aconsole.log(extractLabel(ex%2C%20'noun'))%3B%0D%0AextractFunc(ex%2C%20'func')()%3B%0D%0AcallFunc(ex%2C%20'func'))
is an example in the TS playground.

I actually think there are some bugs with the implementation in TS 2.8.3 (shown in the example), but they are possible to work around.

**Comment by jasongrout** [comment]
Looks like typedoc needs to be upgraded too. Typedoc 0.9.0 uses ts 2.4, 0.10 uses ts 2.7 (which doesn't compile our code just yet). Investigating...

**Comment by jasongrout** [comment]
I took out the small enhancements we made to the main menu find function at put them at #4468, which was causing the problems with older versions of typescript that typedoc was using.

Now the changes in this PR are *only* about the es2015 target, and hopefully are simpler and pass the tests.

**Comment by jasongrout** [comment]
Tests look like they are passing now.

On the larger issue, this requires a major version bump for everything, including services, coreutils, rendermime-interfaces, and observables, which have already reached 1.0 or later.

What it gives us is proper iterator support (for iterating es2015 data structures, for example), that we didn't have available before (for example `for of` iteration of a set).

What it gives us in the generated code is much better code for async/await (good enough that I think we can start using async/await where ever we want in the codebase without making debugging too difficult), and code in the browsers that uses es2015 features such as arrow functions, es6 classes, `let`, `const`, and many other things.

@ellisonbg - Thoughts?

**Comment by jasongrout** [comment]
From @Carreau - stats on jupyter.org show that IE+Edge = 6% and IE 11 itself little under 3% 'market share'

**Comment by jasongrout** [comment]
Looks like my worries were overblown. Jupyter notebook (even version 4) officially does *not* support IE 11 (partly because of its buggy flexbox implementation). We do not need to worry about IE 11 support for widgets either, then. So definitely +1 on migrating to es2015 output.

**Comment by saulshanabrook** [comment]
> Looks like typedoc needs to be upgraded too. Typedoc 0.9.0 uses ts 2.4, 0.10 uses ts 2.7 (which doesn't compile our code just yet). Investigating...

How did you work around this? I can't build the docs in #4512 because it won't handle some JSX things, because the typescript is too old. However, there doesn't seem to be a version of typedoc that support TS 2.6 (what we are using). If I upgrade to that version of typedoc, then it can't compile some other code.

Is the best route to upgrade the whole codebase to 2.7 and upgrade typedoc?

**Comment by jasongrout** [comment]
> How did you work around this?

I didn't. I left the ts version the same.



> Is the best route to upgrade the whole codebase to 2.7 and upgrade typedoc?

I think so.

**Pull request merged**
