### PR TITLE
Add kernel and session architecture diagram

### LINKED ISSUE #7809: Add kernel and session architecture diagram
There is currently a good overview of the different kernel related concepts in the [services README.md](https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/README.md#overview)

I wonder whether there could also be a diagram that explains how all the different components talk to each other. Maybe something similar to the one posted in https://github.com/jupyterlab/jupyterlab/pull/7252#issuecomment-539489451:

image

Maybe the exact same diagram could be used, unless some of the inner details have changed.

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes #7809.

Add a diagram to the `@jupyterlab/services` README file to show an overview of the different components.

Largely inspired by Jason's sketch in https://github.com/jupyterlab/jupyterlab/pull/7252#issuecomment-539489451.

Source for the diagram (draw.io): https://drive.google.com/open?id=1k6VkeXJ6aJYSverBH4a9GeBcqLRWN2J8

architecture

## Code changes

None

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
cc @jasongrout 

The source is a draw.io diagram, so we can easily tweak it and make changes if needed.

**Comment by jasongrout** [comment]
Thanks for cleaning this up!

I'd suggest two things: Changing "Websockets" to "Websocket" (since it is only one websocket for each kernel connection), and putting the diagram source file in the repo.

**Comment by jtpio** [comment]
Thanks for the input!

There is now the source diagram in xml format, that can be imported on draw.io directly.

**Comment by jasongrout** [comment]
Nice! You can go to draw.io file menu, select "open from url", and paste in the raw github url, and it opens great.

**Comment by vidartf** [comment]
Should there be a dotted line between `KernelConnection` and `KernelModel` similar to what there is between `SessionConnection` and `SessionModel`? This is maybe a roundabout way of asking what that dotted line represents.

**Comment by jasongrout** [comment]
> Should there be a dotted line between `KernelConnection` and `KernelModel` similar to what there is between `SessionConnection` and `SessionModel`?

Yes, see https://github.com/jupyterlab/jupyterlab/blob/91d4abf003836e01c1f3e5b2541aba3f6740e94e/packages/services/src/kernel/kernel.ts#L54-L57 Can you or @jtpio open an issue (or maybe just a PR)?

**Comment by jasongrout** [comment]
> This is maybe a roundabout way of asking what that dotted line represents.

Dotted line here means "contains a reference to" - probably should have an arrow too like the other containments signified by arrows.

The distinction here between dotted and solid arrows is the lifecycle. SessionContext creates a SessionConnection and manages its lifecycle. Likewise for sessionconnection and kernelconnection. When a session context dies, it takes down the session connection and kernel connection, but not the kernelmodel. However, when a kernel model dies, it takes down the kernel connection (but not the session connection or session context).

**Pull request merged**
