### PR TITLE
Observablemap selections

### PR DESCRIPTION
**Pull request by ian-r-rose**
Implements editor selections using an ObservableMap.

### CODE REVIEW

**Comment by blink1073** [comment]
You're on :fire:!

**Comment by ian-r-rose** [comment]
I always enjoy a PR with net deletions.

**Comment by blink1073** [comment]
https://www.youtube.com/watch?v=Q8rNb1BAXxU

**Comment by ellisonbg** [comment]
Wow, this is beautiful!!!

**Pull request merged**
