### PR TITLE
Adding SUSE SLES 15 and openSUSE as supported platforms

### PR DESCRIPTION
**Pull request by alfsuse**
I do work for SUSE and we'd like to be listed in the supported platforms

Fixes #

**Screenshots**
If applicable, add before and after screenshots to help show the issue being fixed, or the appearance of a new feature.

### CODE REVIEW

**Comment by alfsuse** [comment]
> I fixed a few typos in a follow-up commit. Does it look good to you?
> 
> Does SUSE really use `py -3` instead of `python3`? It seems odd to follow the windows convention, but I don't know SUSE...

HI @jasongrout  no probably was my bad typo that leads to confusion. When using SUSE you don't have to explicitly type "python3" or "py -3" but just the pip command so the actual command is simply "sudo pip install jupyterlab"  or "pip install jupyterlab" . Sorry for the confusion.

**Comment by jasongrout** [comment]
> When using SUSE you don't have to explicitly type "python3" or "py -3" but just the pip command so the actual command is simply "sudo pip install jupyterlab" or "pip install jupyterlab" . Sorry for the confusion.

Ah. That's the case for the other linux distributions as well. There are specific reasons for using `python3 -m pip` instead of just using `pip3` that I have forgotten (@minrk or @blink1073, do you remember why it is a good idea to use `python3 -m pip` instead of just `pip3`?)

In that case, perhaps we just add OpenSUSE to the list of distributions above, then, and use the existing install instructions.

**Comment by jasongrout** [comment]
Note that the `python -m pip` way of using pip is used in the official pip examples at https://docs.python.org/3/installing/index.html#basic-usage

And one more thing to double-check - does pip automatically come with python 3 in openSUSE? IIRC, pip comes with python 3.4 or later, which means that we may not need the pip installation step at all now that we require python 3, unless the distributions actually strip out the pip that comes with python.

**Comment by alfsuse** [comment]
Totally agree sound more simple and clear just add SUSE ( we got both the openSUSE and SUSE Linux enterprise sever)

Inviato da iPhone

Il giorno 4 mar 2019, alle ore 17:39, Jason Grout <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Note that the python -m pip way of using pip is used in the official pip examples at https://docs.python.org/3/installing/index.html#basic-usage

And one more thing to double-check - does pip automatically come with python 3 in openSUSE? IIRC, pip comes with python 3.4 or later, which means that we may not need the pip installation step at all now that we require python 3, unless the distributions actually strip out the pip that comes with python.

**Comment by ian-r-rose** [comment]
Looks good to me, thanks @alfsuse!

@jasongrout I suspect the purpose of `python -m pip` is to cut down on possible `PATH` issues, where a `pip` for the wrong python environment is found.

**Pull request merged**
