### PR TITLE
Fix the examples, migrate to jupyterlab_server

### PR DESCRIPTION
**Pull request by jasongrout**
Depends on https://github.com/jupyterlab/jupyterlab_server/pull/58

This greatly simplifies the example app as well to use as much of jupyterlab_server as we can.

### CODE REVIEW

**Comment by jasongrout** [comment]
Ready for review now.

**Comment by blink1073** [comment]
Launching this app actually launches the core JupyterLab app, because it is already installed as a server extension on `/lab`.

**Comment by jasongrout** [comment]
It definitely launches the example app for me (I can see the difference when I remove plugins like the faq plugin, for example). Nevertheless, I'll move the example app to a different URL to show how it can be done.

**Comment by blink1073** [comment]
What does "Jupyter serverextension list" show for you?

**Comment by jasongrout** [comment]
I made the example app be served from a different directory, just to make *sure* there is no overlap. As I looked into it further, it seemed that there were some weird interactions, perhaps some files being served by the lab extension, some not.

Depends on https://github.com/jupyterlab/jupyterlab_server/pull/59

**Comment by jasongrout** [comment]
There are other PRs with the same failing test in the docs component, which doesn't appear to be related to this PR.

**Comment by blink1073** [comment]
This is still hitting `/lab/api/build` on startup...

**Comment by blink1073** [comment]
I bumped the server dep.

**Comment by blink1073** [comment]
Coming from this: https://github.com/jupyterlab/jupyterlab/blob/master/packages/application-extension/src/index.tsx#L97

**Comment by jasongrout** [comment]
> Coming from this: https://github.com/jupyterlab/jupyterlab/blob/master/packages/application-extension/src/index.tsx#L97

Thanks. I think that's the only url endpoint actually provided by jupyterlab, not jupyterlab_server. I think probably the most elegant solution is figuring out a way to put it in its own plugin that can be included in jlab, but not in custom remixes that don't have the build step. 

However, there still is the issue of whether the service manager should be the one to provide the capabilities, or not. To address the issue of the service manager, some options are:

A. the service manager is only for server handlers provided by the notebook server or the jupyterlab_server package, and other server endpoints are on their own. In this case, the service manager can expose some lower-level functions to help with url routing or other things needed in communicating with an endpoint. Then a separate jupyterlab extension handles all communication with the build check endpoint.
B. the service manager provides a registration system for extending itself, and takes care of some basic url routing infrastructure like prepending the lab namespace, etc. The jupyterlab package registers an object to handle communication with the build check endpoint.
C. the service manager actually includes something for managing the build check endpoint, configured with a new page config setting of build_check_url or something, which defaults to empty (i.e., off) for jupyterlab_server.

**Comment by jasongrout** [comment]
It looks like C. is already implemented: there is a buildAvailable option in the page config that is (should be) checked before attempting to do anything build related. I'll dive deeper.

**Comment by jasongrout** [comment]
Just to be sure, I also did a build with `pip install -ve ` of the jupyterlab source, then doing `jlpm install; jlpm run build; jlpm run build:examples`, and I still didn't see any hits of any `/lab` urls.

**Comment by blink1073** [comment]
`pip install -ve` does not install the server extension.  I ran the same as above, but used `pip install -v .` and I'm getting: `[D 02:39:59.253 ExampleApp] 200 GET /lab/api/build?1537256398238 (::1) 1013.00ms`

**Comment by jasongrout** [comment]
I think what is going on is:

A. The new example app inherits from the notebook app
B. The notebook app loads whatever server extensions are enabled
C. The jupyterlab server extension by default says that the build endpoint is available (i.e., adds that information to the webapp settings page_config
D. When the example app writes out the page config, it also writes out this buildAvailable page config variable, which the frontend then interprets.

In the long run, I think the rebuild logic should be a completely separate plugin in jlab, so example apps like this just don't include that logic in the js side, so it doesn't matter if it is in the build config or not. In the short term, I'll explicitly remove the buildAvailable entry from the page config in the example.

**Comment by jasongrout** [comment]
@blink1073, can you try again? My last commit explicitly sets the build availability to false, overriding what the jlab server extension is doing.

**Comment by jasongrout** [comment]
@blink1073, just pushed a better approach - to disable the Jupyter config system for the example app, so that whatever is installed or configured for the server does not affect the example app.

**Comment by blink1073** [comment]
Looks great, thanks!

**Pull request merged**
