### PR TITLE
[WIP] more fixes for kernel tests

### PR DESCRIPTION
**Pull request by jasongrout**
This pulls in the tests changes from #4724. Likely there will be things to fix, as those tests were also modified to work with the changes in that PR. But there were also fixes for the asynchronous test flakiness that these changes hope to address.

### CODE REVIEW

**Comment by jasongrout** [comment]
The tests pass locally for me with these changes. I'm confused by the failures here. I think it's best to pause this work until we can discuss more fully exactly what is happening with the tests.

**Comment by blink1073** [comment]
tornado 6 related perhaps?

**Comment by jasongrout** [comment]
Oh, perhaps. Good thing to check, for sure.

**Comment by afshin** [comment]
Closing for now because it seems to have been superseded by more test work, recently.

**Comment by jasongrout** [comment]
Superseded now with the recent kernel refactor work.

**Pull request closed without merging**
