### PR TITLE
Add scroll margin to headings for better alignment

### LINKED ISSUE #15670: "Notebook scrolls to heading" test fails subtly
Since recent fixes in ToC this test: "Table of Contents scrolling to heading › Notebook scrolls to heading" fails by positioning the heading slightly off:

| Actual | Expected |
|--|--|
| image |  image |

### PR DESCRIPTION
**Pull request by krassowski**
## References

Fixes #15670

## Code changes

Fixes a regression caught by visual tests in which after scrolling to a heading, the target heading was too close to the edge of the notebook (with no margin, and with the cell toolbar buttons cut off).

This regression was a result of a security-related PR fixing the ToC implementation, which meant that the fallback code path which was giving us extra padding was no longer used, see https://github.com/jupyterlab/jupyterlab/issues/15670#issuecomment-1912900548 for details.

## User-facing changes

The cell toolbar buttons are fully available after scrolling to a heading; the heading is easier to read as there is more margin.

| Before security fix | After security fix | This PR |
|--|--|--|
| image | image | image |

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
This needs to be backported to 4.0.x but without the test case because we kept the old behaviour of scrolling to the bottom of the cell in the 4.0.x backport of https://github.com/jupyterlab/jupyterlab/pull/15386.

**Comment by krassowski** [comment]
CI is so green again :green_heart:

**Review by JasonWeill — APPROVED** [review]
Change looks good, verified behavior in Chrome and Firefox ESR on macOS.

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.0.x

**Pull request merged**
