### PR TITLE
Toc: Run nested code cells directly from markdown headings

### PR DESCRIPTION
**Pull request by jess-x**
## References

Improves Toc run cells feature https://github.com/jupyterlab/jupyterlab/issues/10581

## Code changes

- Removed runNestedCodeCells function
- Added new run cells logic, which references nested code cells from notebookTracker, not Toc headings

## User-facing changes

- Enable run nested cells feature when code cells headings are hidden in Toc

## Backwards-incompatible changes

N/A

Edit: 
Thx @andrewfulton9 for suggesting `notebookTracker` :)

### CODE REVIEW

**Review by goanpeca — APPROVED** [review]
Thanks for working on this @jess-x 🚀

**Comment by jess-x** [comment]
Thank you @goanpeca.

Pinging @marthacryan, how do these changes look?

**Review by marthacryan — APPROVED** [review]
Haven't tried running this locally but the code looks good to me! Thanks!

**Comment by krassowski** [comment]
Should we consider back-porting this to 3.2, as this fixes two issues that I consider bugs, or is it not worth it given that we hopefully will have 4.0 within next few months?

**Comment by blink1073** [comment]
Ah, it is probably the `package.json` file causing a conflict

**Pull request merged**
