### PR TITLE
dirty cell: Store the code source as true source of output

### LINKED ISSUE #10424: Default value for dirty cell _incorrect_
## Description

When opening a notebook that contain outputs, the dirty state is not turn on when editing the code. It is only turn on when the cell has been first executed

Peek 2021-06-16 10-24

This raises the question of the default value for the dirty state (or to be more precise of the _executed_code). As the dirty state is not (yet?) saved in the notebook, I would suggest using as default value (aka when loading the notebook from file):
- _executed_code === null if the cell has no output (match current behavior)
- _executed_code === input code if the cell has a output (not the current behavior)

cc @martinRenou 

## Reproduce

1. Open the examples/notebooks/OutputExamples.ipynb
2. Execute the all notebook
3. Save it
4. Close it
5. Reopen it
6. Modify a cell that has an output
7. The dirty status is not triggered

## Expected behavior

Dirty status is triggered for cells with outputs at initial load

## Context

- JupyterLab version: master

### LINKED ISSUE #10431: The dirty indicator does not get cleared up after reverting changes
## Description

As a user I often write code and then decide to revert it / that I should modify a different cell. In the state as for 3.1.0a13 the dirty indicator remains after reverting the change, which is more distracting than helpful. I would like the indicator to go away if I revert my code cell to previous state.

Originally suggested in my review in https://github.com/jupyterlab/jupyterlab/pull/10296#pullrequestreview-670497942.

## Reproduce

1. Open notebook, write `1` in a cell
2. Execute cell
3. Change value of that cell to `2`
4. See dirty indicator gets set
5. Press <kbd>Ctrl</kbd> + <kbd>z</kbd> or manually revert value of the cell to `1`
6. See dirty indicator remains

## Expected behavior

I would like the dirty indicator to go away. This is how dirty indicators work in other applications I use.

## Context

- Browser and version: Chrome
- JupyterLab version: 3.1.0a13

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #10424
Fixes #10431

## Code changes

Code cell with outputs in the notebook will be loaded from the file with the input content as the true source that resulted in the outputs.

This make the dirty status a bit more natural although the best will be to store the dirty status in the notebook format.

## User-facing changes

Dirty status is activated when editing a cell with initial output.

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by fcollonval** [comment]
Peek 2021-06-17 16-35

**Comment by krassowski** [comment]
I think it fixes #10424 but not #10431.

**Comment by krassowski** [comment]
I think these errors in console are relevant. To reproduce create a notebook with a (non-empty?) code cell, do NOT run it, save notebook and refresh JupyterLab:

error-console

There will be as many errors as such code cells.

```js
index.es6.js:211 Error: Can only call getValue for an ObservableValue
    at ModelDB.getValue (/user/fcollonval-jupyterlab-i85e1zbd/lab-dev/static/lab/packages_observables_lib_index_js.953159417b0b892ce0f2.js:304)
    at CodeCellModel.get executionCount [as executionCount] (/user/fcollonval-jupyterlab-i85e1zbd/lab-dev/static/lab/packages_cells_lib_index_js.76a74b036d6715c13e9f.js:1182)
    at CodeCellModel.onGenericChange (/user/fcollonval-jupyterlab-i85e1zbd/lab-dev/static/lab/packages_cells_lib_index_js.76a74b036d6715c13e9f.js:1293)
    at invokeSlot (/user/fcollonval-jupyterlab-i85e1zbd/lab-dev/static/lab/jlab_core.4ce36f7fa5554ca95073.js:21849)
    at Object.emit (/user/fcollonval-jupyterlab-i85e1zbd/lab-dev/static/lab/jlab_core.4ce36f7fa5554ca95073.js:21806)
    at Signal.emit (/user/fcollonval-jupyterlab-i85e1zbd/lab-dev/static/lab/jlab_core.4ce36f7fa5554ca95073.js:21489)
    at ObservableString.set text [as text] (/user/fcollonval-jupyterlab-i85e1zbd/lab-dev/static/lab/packages_observables_lib_index_js.953159417b0b892ce0f2.js:1122)
    at new CellModel (/user/fcollonval-jupyterlab-i85e1zbd/lab-dev/static/lab/packages_cells_lib_index_js.76a74b036d6715c13e9f.js:809)
    at new CodeCellModel (/user/fcollonval-jupyterlab-i85e1zbd/lab-dev/static/lab/packages_cells_lib_index_js.76a74b036d6715c13e9f.js:1108)
    at ContentFactory.createCodeCell (/user/fcollonval-jupyterlab-i85e1zbd/lab-dev/static/lab/packages_notebook_lib_index_js.1ddd6340688e252ace56.js:3201)
```

**Comment by fcollonval** [comment]
> I think it fixes #10424 but not #10431.

Oh ja, I click on wrong button in VS Code so it reference your issue. Sorry I'll correct it.

Thanks for testing. I look into the error.

**Comment by fcollonval** [comment]
@krassowski I check #10431 with this PR, it does not seem to happen any more. Could you confirm it?

**Review by krassowski — APPROVED** [review]
Indeed, it fixes both. Thank you!

**Pull request merged**
