### PR TITLE
Add `crossorigin="anonymous"` to GitHub images

### LINKED ISSUE #16388: Add `crossorigin` `anonymous` to images in extension manager
Using cross origin restrictions on server breaks fetching images from remote URLs, for for example in the Extension Manager sidebar the icons of extensions fetched from GitHub will not display correctly. We should be able to fix this by adding `crossorigin="anonymous"` to the image elements (I am not sure if this already works with all browsers).

_Originally posted by @krassowski in https://github.com/jupyterlab/jupyterlab/issues/16382#issuecomment-2134556325_

### PR DESCRIPTION
**Pull request by krassowski**
## References

Fixes #16388

## Code changes

```diff
+ crossOrigin="anonymous"
```

## User-facing changes

Images in the extension manager display properly when using restricted cross origin policy (e.g. to allow extensions to use `SharedArrayBuffer`).

## Backwards-incompatible changes

None

### CODE REVIEW

**Review by jtpio — APPROVED** [review]
Thanks!

**Review by jtpio — COMMENTED** [review]
Ah actually it looks like the failing UI tests are relevant:

image

**Comment by krassowski** [comment]
[this is a test, I will revert the snapshots later] bot please update snapshots

**Comment by krassowski** [comment]
[this is a test, I will revert the snapshots later] bot please update snapshots

**Comment by krassowski** [comment]
[this is a test, I will revert the snapshots later] bot please update snapshots

**Comment by krassowski** [comment]
Closing for now, once I find a solution without side effects I will open a new one.

**Pull request closed without merging**
