### PR TITLE
Persistent side-by-side ratio setting

### PR DESCRIPTION
**Pull request by echarles**
Fixes https://github.com/jupyterlab/jupyterlab/issues/12157

Follow-up of Follow-up of https://github.com/jupyterlab/jupyterlab/pull/12608

New PR that only pulls the needed changes (looks like the branch of https://github.com/jupyterlab/jupyterlab/pull/12608 had issues).

### CODE REVIEW

**Comment by echarles** [comment]
@fcollonval this is ready for review. The 2 failing tests are not related to these changes.

**Review by fcollonval — APPROVED** [review]
Thanks @echarles

**Comment by echarles** [comment]
@fcollonval here we go :)

**Comment by echarles** [comment]
@meeseeksdev please backport to 3.3.x

**Comment by echarles** [comment]
@meeseeksdev please backport to 3.4.x

**Pull request merged**
