### PR TITLE
Fix override url

### PR DESCRIPTION
**Pull request by blink1073**
Follow up to #5503

### CODE REVIEW

**Comment by eoinmurray** [comment]
Great, having a look now

**Comment by blink1073** [comment]
Do you mean you're trying locally?

**Comment by eoinmurray** [comment]
Is dev-mode required for this to work?

**Comment by blink1073** [comment]
Yes, until we cut a new release with it

**Comment by eoinmurray** [comment]
Ah ok sure, seems to work well for me, I think its then just a matter of taking the dev_mode/static folder and hosting on s3 and then using cloudfront to host those files.

I think this is a good solution as the vendors~main file can get quite large, especially with extensions installed, any idea when the release might come?

**Comment by blink1073** [comment]
I'll cut a release later today

**Comment by eoinmurray** [comment]
Even with that release, its not working without the --dev-mode flag

**Comment by eoinmurray** [comment]
`jupyter lab --LabApp.override_static_url='http://0.0.0.0:8000/'` and `python -m http.server` in the static dir, but it still tries to fetch from http://localhost:8888/lab/static/vendors~main.aeebdbd4a5d862502cba.js

**Comment by blink1073** [comment]
Yikes, this one is a bear...  I might not get a chance to look at it again until the weekend.

**Comment by eoinmurray** [comment]
@blink1073 thanks for the help and working on this!, we've implemented it a kyso minifying frontend assets and serving with Cloudfront and we ended up with a great first load experience.

**Pull request merged**
