### PR TITLE
Add @jupyterlab/json package

### LINKED ISSUE #6927: Reusable JSON component
The `@jupyterlab/json-extension` extension uses a [component](https://github.com/jupyterlab/jupyterlab/blob/97bc2ca68a8f66f3158fb50853218f037b0ecb25/packages/json-extension/src/component.tsx#L33) to render a JSON blob as a tree, and also the possibility to use a filter.

It would be great to make this part reusable so other extensions could reuse the same component without depending on the extension package.

How about extracting it to a `@jupyterlab/json` package?

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes #6927.

So the JSON renderer can be reused from other extensions:

```typescript
import { JSONComponent } from '@jupyterlab/json';
```

## Code changes

- Move the `Component` part of the `@jupyterlab/json-extension` package to `@jupyterlab/json`
- Rename `Component` to `JSONComponent` for better readability

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jasongrout** [comment]
Adding work-in-progress since this is a draft PR right now.

**Comment by jtpio** [comment]
There must be something missing for this new package to be picked up correctly:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@jupyterlab%2fjson: Not found".
```

https://dev.azure.com/jupyterlab/jupyterlab/_build/results?buildId=2995

**Comment by jasongrout** [comment]
Setting as 3.0 so we don't block 2.0, but it would be great if this could get into 2.0 too!

**Comment by jtpio** [comment]
No problem.

Since it's a new package, does it have to published to npm first so the tests can pass?

**Comment by blink1073** [comment]
@jtpio did you want to revive this?  The referenced failing build is gone, so we can't debug.

**Comment by jtpio** [comment]
We can close it for now since it has become a bit stale.

**Pull request closed without merging**
