### PR TITLE
Update more dev dependencies

### PR DESCRIPTION
**Pull request by jtpio**
## References

Follow-up to #14216 

## Code changes

Update more dev dependencies, followed by a lint run:

```shell
jlpm
jlpm run lint
```

- Bump to TypeScript 5.0.3
- Bump to typedoc 0.23.28
- Remove [stylelint-config-prettier](https://github.com/prettier/stylelint-config-prettier#readme) as those rules are deprecated since stylelint v15

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
Should we revive this effort before beta1?

**Comment by jtpio** [comment]
Ah yes, I thought it was merged already :)

**Comment by fcollonval** [comment]
@brichet I remove all possible yarn warnings. Would you mind having a look at this one?

**Comment by brichet** [comment]
I wonder if there are not too many package with a peer dependency to react.
According to https://github.com/jupyterlab/jupyterlab/actions/runs/4576078368/jobs/8079732024?pr=14304#step:4:598 (for example), some peer dependencies has been adding without warning from yarn (but maybe there were others warnings at others builds).
Perhaps the following packages do not need the peer dependency to `react`:
```
application
apputils,
attachement
cell-toolbar
codemirror
completer
console
csvviewer,
docregistry
hub-extension
imageviewer-extension
imageviewer
inspector-extension
inspector
javascript-extension
launcher-extension
lsp
mainmenu
markdownviewer
markedparser-extension
mathjax-extension
metadataform
nbconvert-css
outputarea
rendermime-extension
rendermime
running-extension
terminal
theme-dark-extension
theme-light-extension
tooltip-extension
tooltip
translation
ui-components-extension
```

**Comment by fcollonval** [comment]
> I wonder if there are not too many packages with a peer dependency to react. According to https://github.com/jupyterlab/jupyterlab/actions/runs/4576078368/jobs/8079732024?pr=14304#step:4:598 (for example), some peer dependencies has been adding without warning from yarn (but maybe there were others warnings at others builds). 

Actually as soon as you add a peer dependency to a package all the packages dependent on it are gonna complained that they are missing it. So the propagation of `react` is required.

**Comment by krassowski** [comment]
Should we close this since https://github.com/jupyterlab/jupyterlab/pull/14339 was merged?

**Pull request closed without merging**
