### PR TITLE
Downgrade to yarn 1.6.0.

### LINKED ISSUE #4793: Downgrade yarn to 1.6.0
Yarn 1.7 (and yarn 1.8) gives us node 10 support, but unfortunately also has a serious bug: https://github.com/yarnpkg/yarn/issues/5935

We discussed this today, and decided to downgrade back to yarn 1.6 until the bug is fixed.

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #4793

This avoids the bug in yarn noted at https://github.com/yarnpkg/yarn/issues/5935, where a system path can override local paths. This bug can break executing commands from yarn in pipenv environments, for example.

### CODE REVIEW

**Comment by hadim** [comment]
Are you planning to upgrade to 1.8.0 before the next release? Because I still have [this issue](https://github.com/jupyter-widgets/ipywidgets/issues/2061#issuecomment-397117346) with jupyterlab-0.33.0rc0 (and so the bundled yarn 1.6.0).

**Comment by jasongrout** [comment]
We need to see if the serious yarn 1.8 bug noted above affects users building JLab, or just developers. If it affects users, we'll upgrade yarn when 1.9 is released with a fix. If the bug only affects developers, I'd be okay with upgrading and working around the problem for now.

**Comment by jasongrout** [comment]
By the way, that issue is solved by using node 9 or earlier. For example, node lts should work.

**Comment by hadim** [comment]
Ok thank you. Ues I have downgraded node and it works. It just misleading since node 10 is the version shipped with conda forge.

**Comment by bollwyvl** [comment]
>
> I'll take a look. I don't see how the symlinks approach will play in
Redmond, however...

**Comment by jasongrout** [comment]
@bollwyvl - thanks again for taking a look at the yarn bug!

**Pull request merged**
