### PR TITLE
implement @jupyterlab/completer plugins in examples/notebook

### PR DESCRIPTION
**Pull request by mattma**
Use completer in Examples/Notebook. See [2172](https://github.com/jupyterlab/jupyterlab/issues/2172) for details.

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks for this!  I'll review it on Monday.

**Comment by mattma** [comment]
@blink1073 Thanks for your help too!

**Comment by blink1073** [comment]
Looks good!  I sent a PR against yours with a couple of minor changes.

**Comment by blink1073** [comment]
Thanks!

**Pull request merged**
