### PR TITLE
use setdefault for buildAvailable and buildCheck

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

#7368

## Code changes

Favors pre-configured `buildAvailable` and `buildCheck` for passing to `page_config`. This allows specifying...

```json
{
  "LabApp": {
    "tornado_settings": {
      "page_config_data": {
        "buildCheck": false,
        "buildAvailable": false,
      }
    }
  }
}
```

...such that nodejs memory, cpu overhead, and noise on the console is reduced. #7368 calls this out for the automated testing case: I have run into this a number of times myself, both in testing, and when kernel-side packages "helpfully" put labextensions in places I don't want... e.g. I want `FancyLab` to use the extension (pre-built, and tested, out-of-band) and `JupyterLab` to be as-distributed.

If watch mode is used, this will still be clobbered. Feature? I explicitly _didn't_ introduce that as a configuration-preferred feature (or dev_mode or anything else that already has a traitlet). The argument could be made that these should be hoisted, too, but this answers an immediate need.

## User-facing changes

Users/admins/re-packagers can configure a "normal" startup to not invoke node (by means other than not installing node).

## Backwards-incompatible changes

None. These settings (and everything else in `page_config`) have always been configurable... just would always be re-written by various places here and in `jupyterlab_server`.

### CODE REVIEW

**Comment by bollwyvl** [comment]
So the other thing in `page_config` that I've often have wanted to change is `app_name` and `app_version`. I usually end up having to overload `Lab*App` in a few places, anyway, but perhaps some day that won't be necessary.

These values appear to be deeply bound with [`LabConfig`](https://github.com/jupyterlab/jupyterlab_server/blob/8f6cee4ecccc9b1877f5c04db8bf3e199e508c3a/jupyterlab_server/handlers.py#L123) over on `jupyterlab_server`, as just a lonely `HasTraits`, and get forcefully re-set a few places. Making `LabConfig` a `LoggingConfigurable` seems a bit much, as most of the stuff you can't really monkey with. Probably not appropriate on this PR, but hoisting that to the `nbapp` might be appropriate, or even reading it off `page_config`, I suppose.

**Comment by bollwyvl** [comment]
welp, don't see how i can fix [this](https://dev.azure.com/jupyterlab/jupyterlab/_build/results?buildId=3553&view=logs&jobId=6f807910-43ed-5cd8-ceaa-1aba4c5928ae&taskId=e833abef-9a43-57f4-3f21-3da357678b41&lineStart=868&lineEnd=869&colStart=1&colEnd=1) short of breaking the link.

```
(line    7) broken    ***/releases/tag/v1.2.0 - 404 Client Error: Not Found for url: ***/releases/tag/v1.2.0
```

Seems like an `--ignore-patterns` for `pytest-check-links` would be handy...

**Comment by bollwyvl** [comment]
Ah, it is [known](https://github.com/jupyterlab/jupyterlab/pull/7331#issuecomment-541263078).

**Comment by jasongrout** [comment]
> Ah, it is [known](https://github.com/jupyterlab/jupyterlab/pull/7331#issuecomment-541263078).

Yeah, maybe it wasn't worth it to try to save yet one more PR...

**Comment by bollwyvl** [comment]
@jasongrout @katsar0v No worries all, it's totally understandable if this didn't make the release train :train2: ! Happy to help proceed: in the meantime, should this have a test?

**Comment by bollwyvl** [comment]
Hooray 1.2!

Along with the shiny new tag, I've also updated the docs reflecting the intent of #7368. Still not sure how to go about testing this, as there isn't a lot of implicit coverage around the extension code paths... I guess it could be a (cheap) CLI test...

**Comment by bollwyvl** [comment]
Seeing a lot of fail generally on the JS tasks... probably not my fault?

**Comment by telamonian** [comment]
@bollwyvl I've seen the same set of intermittent failures in `test-console` and `test-services` before. I actually did come up with a fix for the failures in `test-console` in #7271, but it's unfinished, partially because it's *really* hard to be certain that something fixes an uncommon intermittent failure.

I kicked the tests (for some reason the normal rerun isn't working, so I closed and reopened the PR). I'll bet they pass this time, or at least that a different set will fail.

**Comment by bollwyvl** [comment]
so close!

**Comment by bollwyvl** [comment]
re-pushed with `master` merged in... just got bit by this _again_ when testing some stuff, would really love to see this make it through. C'mon :rocket: !

**Comment by blink1073** [comment]
:shipit:

**Pull request merged**
