### PR TITLE
fix: use process/browser module as real polyfill

### PR DESCRIPTION
**Pull request by maartenbreddels**
For the ipywebrtc/jupyter-webrtc widget, I need the real process polyfill. Would this be ok?

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Not sure how to fix the failures.

**Comment by jasongrout** [comment]
Can you specify the polyfill in your package.json, or use the frontend package directly, or is it for a dependency that you don't control? See https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

**Comment by jasongrout** [comment]
> Can you specify the polyfill in your package.json, or use the frontend package directly, or is it for a dependency that you don't control? See https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

@maartenbreddels, just pinging you on these questions.

**Comment by maartenbreddels** [comment]
Thanks Jason l, no we can't do that because it is already mocked by jupyter lab. So lab should not provide it at all, or provide the real one (like this pr does)

**Comment by jasongrout** [comment]
Ah, sorry, I didn't catch that the real problem is that we only provide a partial implementation.

**Comment by jasongrout** [comment]
@maartenbreddels - I pushed some simplifications to this PR. Do my changes still work for your usecase?

**Review by jasongrout — APPROVED** [review]

**Review by blink1073 — APPROVED** [review]

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.0.x

**Pull request merged**
