### PR TITLE
Add show trailing whitespace option to Notebook and Text Editor

### PR DESCRIPTION
**Pull request by richardkang112**
## References

Possible fix to #1281 

Please tell me what you think.

## User-facing changes

Added `showTrailingSpace` to Notebook and Text Editor Advanced Settings Editor

`showTrailingSpace: true`

VDt9zFyDmr
## Backwards-incompatible changes

None. Please let me know if there is any.

### CODE REVIEW

**Comment by krassowski** [comment]
That's very nice! We are currently thinking about moving to CodeMirror 6 (https://github.com/jupyterlab/jupyterlab/issues/10370). Do you think that it would be still possible to retain this addition when moving to CodeMirror 6?

**Comment by richardkang112** [comment]
@krassowski I think we might need to write a custom extension to implement this feature in CodeMirror 6. Official CodeMirror 6 extensions don't include the `showTrailingSpace` feature yet, but it was one of the official addons in the previous versions of CodeMirror.

**Comment by krassowski** [comment]
I have quite mixed feelings on adding new CodeMirror 5 functionality if we will have to write it from scratch for 4.0, but.. there was some discussion last week that we might have 3.2 and in that case this PR could be released in 3.2. CC @goanpeca for 3.2 planning.

**Comment by fcollonval** [comment]
Hey one question regarding the UI. Is the red underline a good visual indicator? It may confuse users especially if they have LSP extension installed (e.g. there are no popup to give the reason of the red underline).

cc @krassowski

**Comment by krassowski** [comment]
> Hey one question regarding the UI. Is the red underline a good visual indicator? It may confuse users especially if they have LSP extension installed (e.g. there are no popup to give the reason of the red underline).

Indeed. There are two alternatives that are universally accepted:
- [interdot](https://en.wikipedia.org/wiki/Interpunct#In_mathematics_and_science): · (`&middot;`)
- blank: ␣ (`&blank;`)

I think the middot might be a good solution.

**Comment by richardkang112** [comment]
@fcollonval @krassowski The latest commit changes the red underline highlighting to middot.

image

**Comment by fcollonval** [comment]
Thanks @richardkang112 Would you mind resolving the conflict please?

**Comment by richardkang112** [comment]
@fcollonval The conflict is resolved.
@krassowski Thank you for catching the typo!

**Review by fcollonval — APPROVED** [review]
LGTM 

Thanks @richardkang112

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.2.x

**Pull request merged**
