### PR TITLE
fix for contextual help layout

### PR DESCRIPTION
**Pull request by rvalieris**
## References

fix for #6928

rationale is on the issue.

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks for finding the issue, filing the issue, tracking down the fix, and submitting a PR!

**Comment by jasongrout** [comment]
CC @afshin as well

**Comment by jasongrout** [comment]
Ah, I figured out why display:flex was there. The default content depends on it to center the content vertically: https://github.com/jupyterlab/jupyterlab/blob/52a33052af241f9eebbda6ab7d43c01296644621/packages/inspector/style/base.css#L50-L51

 I think it's probably even better to not center vertically? Then people looking at the top of the tab for content don't miss the function. But we probably should go ahead and delete the relevant items in the default-content css (or just add back in the display:flex there)

**Comment by jasongrout** [comment]
Could you put in one more PR to add `display:flex` back into `.jp-Inspector-default-content`? I should have caught this before merging this PR. That will restore the current behavior, so we don't need to have a discussion about how to change the current behavior of the default content.

**Comment by rvalieris** [comment]
opened https://github.com/jupyterlab/jupyterlab/pull/6935 !

**Comment by rvalieris** [comment]
oh wait my bad I confused the classes, I will change the commit on the PR there

**Comment by jasongrout** [comment]
Thanks!

**Comment by blink1073** [comment]
@meeseeksdev backport to 1.0.x

**Pull request merged**
