### PR TITLE
Use correct hub restart URL

### PR DESCRIPTION
**Pull request by mahendrapaipuri**
## Code changes

Seems like `hub` extension is never taking the `restartUrl` for the current single user server. This PR corrects it by using the `restartUrl` of current single user server when config parameters are found. If not, `restartUrl` will be set to spawn page.

## User-facing changes

Users will be able to restart their servers instead of redirecting to spawn page

## Backwards-incompatible changes

NA

@krassowski Does it make sense? I think it was a regression introduced in [this PR](https://github.com/advisories/GHSA-44cc-43rp-5947).

### CODE REVIEW

**Comment by krassowski** [comment]
Makes sense, thank you for catching this! I think we should add a test for this (and for the issue that was patched by https://github.com/advisories/GHSA-44cc-43rp-5947) - are you happy to add a test here or would you like help in setting it up (I see that hub-extension does not have a tests folder yet so you may need to use `jlpm create:test` or copy the directory structure from another package and update `package.json` accordingly)

**Comment by mahendrapaipuri** [comment]
Cheers @krassowski ! Sure, I will it a go and try to add a test.

**Comment by mahendrapaipuri** [comment]
@krassowski Added a basic unit test for `hub-extension` with my limited `jest` skills. Let me know what do you think!

**Comment by mahendrapaipuri** [comment]
@krassowski Ahhh, by mistake I synced the JupyterLab's `main` directly into the source branch of PR instead of forked `main`. Is it ok or should I clean it up and rebase?

**Comment by krassowski** [comment]
It's ok, we do squash merges anyways.

**Comment by krassowski** [comment]
Can you add `js-hub-extension` line to `.github/workflows/linuxjs-tests.yml` so that these tests are run on CI?

**Comment by mahendrapaipuri** [comment]
@krassowski Done! Thought test discovery is automatic.

**Review by krassowski — APPROVED** [review]
Thank you @mahendrapaipuri!

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.2.x

**Comment by guyq1997** [comment]
This still does not work for me. Even with the 4.2.4 Version.
The restartURL is still /hub/spawn.

**Comment by mahendrapaipuri** [comment]
@guyq1997 If your single user server is running, `/hub/spawn/<user>` should automatically redirect to that running server at `/user/<user>/lab`. I can verify it on our deployment using JupyterLab 4.2.4

**Comment by guyq1997** [comment]
@mahendrapaipuri 
Thanks a lot for your response! What if the Server is stopped by the Idle Culler, and the dialog tells user to start it again? The current server will not be opened. This is also important. Because users always want to get back to the server, where they were.

**Comment by mahendrapaipuri** [comment]
> What if the Server is stopped by the Idle Culler, and the dialog tells user to start it again?

If you are using default server, hitting the URL `/hub/spawn/<user>` should trigger a new spawn which should eventually spawn a new single user server. However, if you have named servers enabled and a spawner form (to configure your single user servers), it might be tricky to start a new spawn directly from single user server as we need a `_xsrf` token and current spawner config to submit spawn data which single user server might not have access to.

**Pull request merged**
