### PR TITLE
[WIP] Databus

### PR DESCRIPTION
**Pull request by saulshanabrook**
This is a new PR which extends https://github.com/jupyterlab/jupyterlab/pull/5734 and will close https://github.com/jupyterlab/jupyterlab/issues/5548 and close https://github.com/jupyterlab/jupyterlab/issues/5831

- [x] Figure out how to integrate with docregistry
  - [x] Figure out what multiple mimetypes on filetypes do
  - [x] Figure out how the mimerender extensions interact with filetypes
- [x] Add extension for databus that exposes data registry and converters
- [x] Add converter from URL to string
- [x] Add concept of "Viewer" and "ViewerRegistry"
- [x] Add CSV viewer using existing CSV viewer.
- [x] ~~Expose converters in UX~~
- [x] Expose viewers in UX
- [x] Change visualizers and resolvers to just be converters
  - [x] Call them `viewers` and `resolvers`
- [x] Change converters to take in URL as well as data. This will allow widget created for CSV viewer to contain URL in id.
- [x] Add notebook support. 
- [x] Add simple insertion of code snippets from data
- [x] Add separate file mimetype, between unknown and URL 
- [ ] Refactors
  - [x] **Add some abstraction of mimetype -> data + type of data, so we can create converts from/to it with more type safety.**
  - [ ] Remove async iterator
  - [ ] Switch internal representation to be nested map url -> mimetype -> data.
- [ ] Fix bugs
  - [x] **When you close a dataset widget it disposes of it so you can't reopen it**
  - [ ] Allow registering multiple datasets from filebrowser
  - [x] Insert snippet wrong path
  - [ ] **Make other yaml files use regular viewer**
  - [ ] **Remove flash of widget**
  - [x] If you create a viewer around some data  that isn't serialized, you can't load it on reload
  - [x] If you create a viewer around URL you should be able to see it on reload
  - [ ] Add public API to get active file in filebrowser, so that we aren't relying on events. Right now after some amount of time it is updated and we get wrong file tracked. 
- [x] **Switch name to "data registry"**
  - [x] Change `DataRegistry` to be `DataSetRegistry`.  
  - [x] Change `dataregistry.ts` to be `datasets.ts`
  - [x] Change `databus.ts` to `registry.ts`
  - [x] Switch package named to `dataregistry`
- [x] Add "active" URL tracking (what is the URL of the active file/document/etc)
- [x] Locally develop with comments & metadata installed
- [x] Remove explicit data registrations on startup
- [x] Move those to notebook in demo repo
- [x] Add viewer for all datasets to open comments when they are registered
- [x] Add auto register option to mimetype. 
- [ ] Add tests
- [ ] Add documentation
- [x] Add `datareg.yml` file to with list of mimetypes and URLs 1
- [ ] Fix components according to style guidelines
  - [ ] Look at using https://github.com/react-cosmos/react-cosmos
- [ ] Add type dispatching for Python 
- [ ] Add custom vega loader that uses databus
- [x] Rebase off master
- [x] Write introduction (4-5 sentences)
  - [x] Who wants to use this
  - [x] Why would they want to use it
  - [x] How will it impact our community

---

Secondary

- [x] ~~Highlight used dataset in explorer, in open activity~~
- [x] ~~Switch viewers to have ID, and then add icon and label in some other registry.~~
- [x] ~~Add file icons~~
- [ ] Voyager viewer

### CODE REVIEW

**Comment by saulshanabrook** [comment]
**Notes**


How to get files into dataregistry:

* Add new file types for every file type, that opens in data registry "Open with... JSON (Data Registry)"
* Add converters between files datasets and and their mimetypes
* Or custom add file handlers for different data types

Converters:

* Allow manual conversion between datasets in data registry (i.e. make a new one based on old one)

How to render things from data registry:

* Want to reuse rendermime
* Have a mapping from mimetype to rendermime. 
* Need also to get "data" for mimetype, i.e. like in mimebundle
* Final mimetype ("text/csv") should be same as in mimebundle?

DataViewer:

* `IRenderer`? But should we just allow one mimetype instead of mimebundle?
* `IRendererFactory` Allows passing in links etc.

New structure...


Questions from meeting:
* Can we "open file" and just get URL instead of text?

**Comment by dhirschfeld** [comment]
> *"Open with... JSON (Data Registry)"*

*Opening* something with the Data Registry doesn't strike me as the right terminology - to me Push to Databus, Pop/Copy/Clone/Open from Databus seem more appropriate?
`</bikeshed>`

**Comment by saulshanabrook** [comment]
screen shot 2019-01-25 at 8 53 26 am

I have added a very preliminary data explorer widget, and the ability to add datasets from the file browser.

**Comment by saulshanabrook** [comment]
I have refactored the implementation, so that the file enters the data registry as just the file path, and then converts are responsible for parsing it's file type and figuring out it's mime type.

I also have switched the conversions to do graph traversal.

screen shot 2019-01-31 at 9 10 55 pm

**Comment by saulshanabrook** [comment]
We talked about this at the Jupyter meeting this week and took a few notes on the broad overview. The conclusion was that we will punt on these questions for now and continue developing as third party extensions so others can start experimenting with it and we can continue iterating on API. 

We will also separate core API into another package so that Vega can use it.  

# Data sources

1. Remote SQL database talking from the frontend
4. Getting whole content from a URL
	5. CSV
	6. JSON
	7. Image
	8. Natural language
	9. Video
	10. Audio
	11. Maps
4. Use HTTP range to get dynamic content 
5. Data format specific APIs. Protocol and transport.
	6. Arrow RPC
	7. HDF5
	8. SQL
	9. Redis
	10. Dataset from National weather service API
11. In kernel memory
	12. Pandas dataframe
12. In browser memory (multiple extensions using one dataset)
13. Streaming data
	14. Bloomberg API
	15. Logging system
16. Typescript Interface or Type
17. Data that changes
	17. IpyWidgets
	18. Real time data store
19. Comments or metadata about a dataset as a dataset itself
20. Larger than memory binary datasets 

## What context / Principles?

1. Not intended to be persistent data catalogue
	2. Dont have to worry about serialization/persistence
3. Human perspective on data, not a machine perspective


## Workflows:
1. Editing plotly chart

## What do we do with datasets?
1. Add references to another system
2. Add code snippets

## Questions:

1. Should data be editable or immutable?
2. How does this relate to the docmanager?


## Conclusions
->

**Comment by saulshanabrook** [comment]
Currently I am moving the work from this PR to a separate repo: https://github.com/jupyterlab/jupyterlab-data-explorer/pull/8. Once that is complete, I will close this PR.

**Comment by saulshanabrook** [comment]
Work has now moved over to https://github.com/jupyterlab/jupyterlab-data-explorer

Please open an issue there if you have questions.

**Comment by vidartf** [comment]
Should we keep the branch, or OK to clean up?

**Pull request closed without merging**
