### PR TITLE
Clicking outside dialog content is dismissing the dialog[8193]

### PR DESCRIPTION
**Pull request by ggbhat**
## References
#8193 

Dialog was getting closed always even when dialog has not having **cancel** button.

## Code changes
Added condition to check dialog having CANCEL button on escape/mouse click event.

## User-facing changes
User has to click OK/dismiss to close dialog without CANCEL button added.
Force the user to take some action and not just dismiss the dialog.

## Backwards-incompatible changes

NO

### CODE REVIEW

**Comment by jasongrout** [comment]
Can you add a test around [here](https://github.com/jupyterlab/jupyterlab/blob/d49039f57e24836fd4a17c75607e5ab8819f23dd/packages/apputils/test/dialog.spec.tsx#L175)?

**Comment by jasongrout** [comment]
Note that this doesn't prevent someone from explicitly calling `Dialog.reject`, it only prevents escape and clicking outside the dialog from calling `Dialog.reject`.

While I think this PR is okay (to prevent dismissal by common user actions), should we put this logic here to prevent even programmatic dismissal of the dialog? https://github.com/jupyterlab/jupyterlab/blob/d49039f57e24836fd4a17c75607e5ab8819f23dd/packages/apputils/src/dialog.ts#L175-L186

On the other hand, I'm afraid that overriding the .reject method will have a lot of ramifications, since dismissing a dialog seems like it is a fundamental part of the architecture. It would be great to get some feedback from someone who understands deeply the architecture of the dialog logic.

**Comment by ggbhat** [comment]
I agree with you @jasongrout , We need more expert comment on this. Most of the front end frameworks have settings for escape/clickoutsideclose while creating dialog. May we can implement same here as well. 
@tgeorgeux  Need your help on this..

**Comment by lresende** [comment]
@ajbozarth Would this help with the pipeline submission issue we are seeing in Elyra?

**Comment by goanpeca** [comment]
Is this PR still valid @ggbhat ?

Thanks! :) 

--- 


Pinging @isabela-pf

**Comment by jweill-aws** [comment]
This PR was not merged, but #10049 was, and it fixes the same issue. Closing.

**Pull request closed without merging**
