### PR TITLE
Turn on accessibility in xterm.js

### PR DESCRIPTION
**Pull request by yuvipanda**
This makes it work with screen readers much much better.

See https://github.com/xtermjs/xterm.js/pull/1182 for more
information.

This adds extra DOM nodes that are live updated for each line
in the terminal, but I think it should be ok given the other
DOM nodes we have :)

From http://www.w4a.info/2019/hackathon/

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Thanks @yuvipanda! Is there any reason that we might want to let this option be configurable? Are there any performance or browser compatibility issues? If so, we may want to add this to the `ITerminal.IOptions` interface. Otherwise, I think this can go in as is.

**Comment by yuvipanda** [comment]
@ian-r-rose from reading the PR, there's no reason (other than if you're worried about the DOM node overhead) for it to be configurable at the JupyterLab user level. Adding it to ITerminal.IOptions (with default to True) might make sense so other components can turn it off if needed. I'll do that now.

**Comment by ian-r-rose** [comment]
Yeah, I agree, there shouldn't need to be much reason for this to be configurable at the user level. Might be worthwhile at the component level.

**Comment by yuvipanda** [comment]
@ian-r-rose done.

**Comment by ian-r-rose** [comment]
Awesome, thanks @yuvipanda!

**Pull request merged**
