### PR TITLE
Move the context menu building logic to a separate plugin

### PR DESCRIPTION
**Pull request by jtpio**
## References

Move the context menu building logic from the `main` plugin to a separate plugin.

This was added in https://github.com/jupyterlab/jupyterlab/pull/10373 and is new in `3.1.0rc1`.

Downstream distributions defining their own `main` plugin would otherwise not pick up that logic, which leads to issues such as:

- https://github.com/jupyterlite/jupyterlite/issues/265
- https://github.com/jupyterlab/retrolab/issues/182

## Code changes

Move the context menu building logic to a separate plugin.

## User-facing changes

None for JupyterLab users.

Downstream applications can reuse the plugin as is.

## Backwards-incompatible changes

None

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.1.x

**Comment by fcollonval** [comment]
@jtpio as you move the context menu in its own plugin, would it make sense to move the settings schema to that plugin too instead of reading it from `main`:

Current context menu property: https://github.com/jupyterlab/jupyterlab/blob/9ac769ecec3adb74c4664df7a622720be3ed999d/packages/application-extension/schema/main.json#L54
Current settings plugin id used to gather the context menu definition: https://github.com/jupyterlab/jupyterlab/blob/9ac769ecec3adb74c4664df7a622720be3ed999d/packages/application-extension/src/index.tsx#L1053

**Comment by jtpio** [comment]
Ah thanks @fcollonval for catching this, makes total sense :+1: 

I can open a follow-up PR to fix this.

**Comment by fcollonval** [comment]
> I can open a follow-up PR to fix this.

If you could make it, it will be great.

**Pull request merged**
