### PR TITLE
pyproject.toml: clarify build system version

### PR DESCRIPTION
**Pull request by adamjstewart**
See https://github.com/jupyter/jupyter-packaging/issues/120

### CODE REVIEW

**Review by fcollonval — APPROVED** [review]
Thanks @adamjstewart

**Comment by jtpio** [comment]
A follow-up to this would be to update `jupyter_packaging>=0.10,<2` to as mentioned in https://github.com/jupyter/jupyter-packaging/pull/121

**Comment by adamjstewart** [comment]
> A follow-up to this would be to update `jupyter_packaging>=0.10,<2` to as mentioned in [jupyter/jupyter-packaging#121](https://github.com/jupyter/jupyter-packaging/pull/121)

Unless the build no longer works with 0.9 or requires features introduced in 0.10, I see no reason to change the lower bound. As for the upper bound, I'm happy to change that if you want me to, was just trying to keep the behavior the same until told otherwise.

**Comment by jtpio** [comment]
Thanks @adamjstewart.

I pushed a small commit to update to `jupyter_packaging>=0.9,<2`

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
