### PR TITLE
Added support for namespace packages in labextensions.

### PR DESCRIPTION
**Pull request by mellesies**
## References
Fix for issue #10149

## Code changes
Added logic to search for namespace packages if no regular packages can be found.

## User-facing changes
None

## Backwards-incompatible changes
None

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by blink1073** [comment]
@meesseksdev please backport to 3.0.x

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.0.x

**Comment by bollwyvl** [comment]
Awesome, thanks!

**Pull request merged**
