### PR TITLE
Client session should dispose the session it owns when it is disposed.

### LINKED ISSUE #7144: Notebook with widgets don't run twice
## Description

Notebooks with widgets can be ran only once. 

## Reproduce

1. Open a notebook with at least 1 component
2. Close it
3. Reopen it
4. The debugger should show 2 similar errors 'Uncaught (in promise) Error: Comms are disabled on this kernel connection'

I've been using a simple notebook, such as:
```
from ipywidgets import Button
btn = Button(description='test')
display(btn)
```

See 'Browser Output' below for screenshots

## Expected behavior

Opening a notebook after being closed should allow code cells to run.

## Context

- Operating System and version: Win 10
- Browser and version: Chrome 76.0.3809.132
- JupyterLab version: 1.1.1

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext\Library\mingw-w64\bin
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext\Library\usr\bin
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext\Library\bin
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext\Scripts
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext\bin
        ...\AppData\Local\Continuum\anaconda3\condabin
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0
        C:\WINDOWS\System32\OpenSSH
        ...\AppData\Local\Microsoft\WindowsApps
        ...\AppData\Roaming\npm
        C:\Program Files\cmder\vendor\git-for-windows\cmd
        C:\Program Files\cmder\vendor\git-for-windows\mingw64\bin
        C:\Program Files\cmder\vendor\git-for-windows\usr\bin
        C:\Program Files\cmder

sys.path:
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext\Scripts
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext\python37.zip
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext\DLLs
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext\lib
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext\lib\site-packages

sys.executable:
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext\python.exe

sys.version:
        3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.17763-SP0

where jupyter:
        ...\AppData\Local\Continuum\anaconda3\envs\jupyterlab-ext\Scripts\jupyter.exe

pip list:
        Package             Version
        ------------------- ---------
        appdirs             1.4.3
        arrow               0.14.6
        asn1crypto          0.24.0
        astroid             2.2.5
        attrs               19.1.0
        backcall            0.1.0
        bifrostNotebooksApi 0.3
        binaryornot         0.4.4
        black               19.3b0
        bleach              3.1.0
        bokeh               1.2.0
        certifi             2019.6.16
        cffi                1.12.3
        chardet             3.0.4
        Click               7.0
        colorama            0.4.1
        cookiecutter        1.6.0
        cryptography        2.7
        decorator           4.4.0
        defusedxml          0.5.0
        entrypoints         0.3
        fileCrawler         0.5
        future              0.17.1
        idna                2.8
        ipykernel           5.1.2
        ipython             7.7.0
        ipython-genutils    0.2.0
        ipywidgets          7.5.0
        isort               4.3.21
        jedi                0.15.1
        Jinja2              2.10.1
        jinja2-time         0.2.0
        json5               0.8.5
        jsonschema          3.0.2
        jupyter-client      5.3.1
        jupyter-core        4.4.0
        jupyterlab          1.1.1
        jupyterlab-server   1.0.6
        lazy-object-proxy   1.4.1
        lxml                4.4.0
        MarkupSafe          1.1.1
        mccabe              0.6.1
        mistune             0.8.4
        nbconvert           5.6.0
        nbformat            4.4.0
        notebook            6.0.1
        numpy               1.17.1
        olefile             0.46
        packaging           19.0
        pandas              0.24.2
        pandocfilters       1.4.2
        parso               0.5.1
        pickleshare         0.7.5
        Pillow              6.1.0
        pip                 19.2.3
        poyo                0.5.0
        prometheus-client   0.7.1
        prompt-toolkit      2.0.9
        pycparser           2.19
        Pygments            2.4.2
        pylint              2.3.1
        pyOpenSSL           19.0.0
        pyparsing           2.4.2
        pyrsistent          0.15.4
        PySocks             1.7.0
        python-dateutil     2.8.0
        pytz                2019.2
        pywinpty            0.5.5
        PyYAML              5.1.2
        pyzmq               18.0.2
        requests            2.22.0
        Send2Trash          1.5.0
        setuptools          41.2.0
        six                 1.12.0
        terminado           0.8.2
        testpath            0.4.2
        toml                0.10.0
        tornado             6.0.3
        traitlets           4.3.2
        typed-ast           1.4.0
        urllib3             1.25.3
        wcwidth             0.1.7
        webencodings        0.5.1
        wheel               0.33.6
        whichcraft          0.6.0
        widgetsnbextension  3.5.1
        win-inet-pton       1.1.0
        wincertstore        0.2
        wrapt               1.11.2
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>

image

The error happens here:
image

</pre>
</details>

### PR DESCRIPTION
**Pull request by jasongrout**
## References

Fixes #7144

Follow-up from #6929 

## Code changes

In #6929, we made it so that only one kernel connection is able to handle comms. When you open a notebook, it creates a context which creates a client session which creates a session which creates a kernel connection which handles comms. When you close a notebook, it sees that there are no other widgets using that context, so it disposes the context, which disposes the client session, which does *not* dispose the session. Hence the js kernel connection object stays around. When you open the notebook again, it again creates a context which creates a client session which creates a session which creates a kernel connection. However this new kernel connection, in deciding whether it should be able to handle comms, looks for any other kernel connection that is already handling comms, and finds the old kernel connection still around, so the new kernel connection does *not* handle comms. This then completely breaks widgets.

This PR makes it so that the client session disposes the session (which then disposes the original kernel in our situation above). That means that when the new kernel connection is created, it sees that there is no other connection handling comms, so it says it can handle comms.

A ramification is that this causes an issue with the session manager list of sessions, which should reflect which sessions are active on the server. When a session is disposed, it emits a terminated signal, which in turn causes the session model to be deleted from the session manager’s list, indicating that the session does not exist on the server when it in fact does. We have conflated deleting the js object with the server-side session terminating. The net result of this is that the session in the list of running sessions and the green session indicator on a filename both disappear until the next server session poll, at which point they are restored to accurately reflect what sessions are active on the server.

To solve this ramification issue, we do not automatically delete the session model, but instead refresh our session list from the server, to make sure our session model list accurately reflects what is on the server.

## User-facing changes

Fixes #7144

## Backwards-incompatible changes

(Hopefully) none.

### CODE REVIEW

**Comment by jasongrout** [comment]
@blink1073 - this fixes a major issue with 1.1.1 preventing people from upgrading to 1.1.1. I tried to be as minimal as possible in a fix. I'd like to push out 1.1.2 with this. Can you review it?

**Comment by jasongrout** [comment]
Investigating test failures, which may be relevant.

**Comment by jasongrout** [comment]
@blink1073 - I'm not sure I'm going to get to finish this today, so 1.1.2 may have to wait until Monday. Don't wait up for me :).

**Comment by blink1073** [comment]
@meeseeksdev backport to 1.1.x

**Comment by jasongrout** [comment]
Thanks!

**Pull request merged**
