### PR TITLE
Kernel banner

### LINKED ISSUE #3323: Kernel About Dialog
I think we should have a `Kernel -> About` menu item that brings up a dialog with the contents of the current kernel's `banner`.  This is related to https://github.com/jupyterlab/jupyterlab/pull/3311.

In the classic notebook this is part of `Help -> About`.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes #3323 
image
image
image

I was talking withe @jasongrout about the possibility of having static (rather than dynamically populated) submenus for each kernel. This would aid discoverability, but the downside is that we would need to start and then stop test kernels in order to get the relevant information for those menus. Thoughts?

### CODE REVIEW

**Comment by blink1073** [comment]
I'm -1 on starting all the kernels, which could be expensive in both memory and CPU and have side effects.

**Comment by jasongrout** [comment]
-1 on preemptively starting all of the kernels just to populate the help menu.

We have a different design idea that would only start kernels when the user requested information for that specific kernel.

**Comment by blink1073** [comment]
Is the intent here to show information about all of the kernels that have been loaded as opposed to the "current" kernel?  The latter is what I had had in mind.

**Comment by blink1073** [comment]
Then you wouldn't need to start a separate kernel at all but query the current one.

**Comment by ian-r-rose** [comment]
This only looks at the current kernel. The other talk was more speculative.

**Comment by blink1073** [comment]
This is great, thanks!

**Pull request merged**
