### PR TITLE
Link background colors and ui font colors in the style

### PR DESCRIPTION
**Pull request by HaudinFlorence**
## References
Fixes https://github.com/jupyterlab/jupyterlab/issues/13152

## Code changes

Link background colors and ui font colors in the different css files

## User-facing changes

Colors in the interface may change slightly.

## Backwards-incompatible changes

Normally changes should not be backwards-incompatible.

### CODE REVIEW

**Comment by fcollonval** [comment]
bot please update snapshots

**Comment by HaudinFlorence** [comment]
bot please update snapshots

**Comment by HaudinFlorence** [comment]
bot please update snapshots

**Comment by HaudinFlorence** [comment]
bot please update snapshots

**Pull request closed without merging**
