### PR TITLE
Update @lumino dependencies

### PR DESCRIPTION
**Pull request by jtpio**
## Code changes

Update `@lumino/widgets`, `@lumino/application` and `@lumino/datagrid` to the latest versions.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks. Is there something specific we are getting with this update, or are you doing it as just general good practice? Why only these Lumino libraries?

**Comment by jtpio** [comment]
The main motivation came from developing a prebuilt extension against the JupyterLab source in dev mode.

The extension was using the latest version of `@lumino/widgets` which is `1.18.0` at the moment. And the core `@jupyterlab` packages are on `1.16.1`. This lead to TypeScript issues when compiling the prebuilt extensions as there were multiple versions of the `@lumino/widgets`.

I remember seeing a similar issue a while ago with a different extension but still related to `@lumino/widgets`. Maybe it was with `1.16` and `1.17`

```
Types of property 'title' are incompatible.
```

**Comment by jtpio** [comment]
But it would make sense to also update the `@lumino` dependencies, as a general good practice indeed.

I can push more changes to also update the others.

**Comment by jtpio** [comment]
Actually the other `@lumino` dependencies already seem to be up-to-date.

**Comment by jasongrout** [comment]
> The extension was using the latest version of `@lumino/widgets` which is `1.18.0` at the moment. And the core `@jupyterlab` packages are on `1.16.1`. This lead to TypeScript issues when compiling the prebuilt extensions as there were multiple versions of the `@lumino/widgets`.

I thought we had things set up so that a prebuilt extension would load JLab's Lumino packages, and just complain if JLab's Lumino package was not satisfactory, but use it anyway. If a prebuilt extension was bundling its own version of Lumino, that would be a problem needing fixing too.

**Comment by jtpio** [comment]
> I thought we had things set up so that a prebuilt extension would load JLab's Lumino packages, and just complain if JLab's Lumino package was not satisfactory, but use it anyway

For the module federation? Sounds like this should be the case yes.

I think the case mentioned above is more related to the TS compilation and the type definitions of `@lumino/widgets`?

**Comment by krassowski** [comment]
I think that the issue is at compilation time here not at runtime. I saw issues like that (I don't remember if this was lumino or something else) when upgrading to 3.0 but `rm -rf node_modules` and a clean install fixed that for me.

**Comment by jasongrout** [comment]
> I think the case mentioned above is more related to the TS compilation and the type definitions of `@lumino/widgets`?

> I think that the issue is at compilation time here not at runtime. I saw issues like that (I don't remember if this was lumino or something else) when upgrading to 3.0 but `rm -rf node_modules` and a clean install fixed that for me.

Ah, sounds like it might be more a yarn upgrade/deduplication/lock issue? Or somehow installing twice on top of another thing ends up accidentally getting two copies.

So while upgrading I think is a good thing (though for a minor release, not for a patch release), I don't think it solves the underlying problem as much as cleaning your repo and installing the npm packages fresh, making sure there are no duplicates in your yarn.lock.

**Comment by jasongrout** [comment]
The biggest hesitation I have with this is that a prebuilt extension compiled with 3.1 (with this upgrade) I think will throw console warnings in 3.0 because the prebuilt extension will require, for example, `@lumino/widgets` `^1.18.0`, but 3.0 only provides `1.16.1`.

This isn't a problem unique to us, of course. Lots of times you have to compile software against the earliest versions of a library so that it is compatible with the earliest version and later versions. So perhaps the best practice will be to compile your prebuilt extension against 3.0 always, and in general compiling against 3.x means the prebuilt extension will work with version 3.x or later.

**Comment by jasongrout** [comment]
> The biggest hesitation I have with this is that a prebuilt extension compiled with 3.1 (with this upgrade) I think will throw console warnings in 3.0 because the prebuilt extension will require, for example, `@lumino/widgets` `^1.18.0`, but 3.0 only provides `1.16.1`.

Note that this just causes warnings now, but with https://github.com/jupyterlab/jupyterlab/pull/9500 this would be a show-stopping error.

**Pull request merged**
