### PR TITLE
Temporary fix for release checker pinning vega-embed

### PR DESCRIPTION
**Pull request by fcollonval**
## References

#11563

## Code changes

Forbid using version of vega-embed more recent than 6.20.2

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by jtpio** [comment]
Nice, thanks @fcollonval. CI is now green.

According to https://github.com/vega/vega-embed/issues/806, this looks like an issue that should be fixed upstream and not here in the `jupyterlab` repo? If so then we can then keep the temporary pin.

**Comment by fcollonval** [comment]
I agree it should be fixed upstream. But I don't know how quick they will figure out the way forward.

**Comment by jtpio** [comment]
Probably the switch to `npx` prevents looking up the `node_modules` from the top-level monorepo.

**Comment by jtpio** [comment]
OK let's get that one in for now to have a green CI and not block the merge of other PRs.

I have updated the title of https://github.com/jupyterlab/jupyterlab/issues/11563 so keep track of the pin

**Comment by jtpio** [comment]
@meeseeksdev please backport to 3.2.x

**Comment by fcollonval** [comment]
Fixed upstream (and reverted in #11578) before backport so no need to backport

**Pull request merged**
