### PR TITLE
Avoid activating the non-current widget after navigating to cwd

### PR DESCRIPTION
**Pull request by gnestor**
Fixes https://github.com/jupyterlab/jupyterlab/issues/5987

### CODE REVIEW

**Comment by gnestor** [comment]
Instead of activating a widget by path (since there can be multiple widgets with that path), this just activates the shell's current widget. 

@ian-r-rose make sense?

**Comment by gnestor** [comment]
Thanks @jupyterlab-dev-mode!

**Comment by choldgraf** [comment]
so cool! cc @Carreau I bet he'd like this...maybe some inspiration for meeseecks

**Comment by ian-r-rose** [comment]
Thanks @gnestor, this does indeed fix the problem (testing these on binder is fun!).

I wonder: do we need to activate the current widget at all? I mean, it is already the current one, and we are reacting to a `currentChanged` signal. Is it enough to just fire-and-forget `Private.navigateToPath`?

**Comment by Carreau** [comment]
Nice ! Ian mentioned GitHub action today in a video call. Hope I had more time to check it out.

**Comment by ian-r-rose** [comment]
It was much more difficult to get deployed than it was to write! The actual action is only about 10 lines of code (starting from a probot template):
https://github.com/ian-r-rose/jupyterlab-dev-mode-bot/blob/3375ecc3562bb9ff1fca4dc9a1dfd6c2a0dfd87f/src/index.ts#L4-L14

**Comment by gnestor** [comment]
> I wonder: do we need to activate the current widget at all? I mean, it is already the current one, and we are reacting to a `currentChanged` signal. Is it enough to just fire-and-forget `Private.navigateToPath`?

If we don't activate the widget, it doesn't highlight the file in the filebrowser 😕

**Comment by ian-r-rose** [comment]
Ah, right! Makes sense

**Pull request merged**
