### PR TITLE
Benchmark tests broken following update of NodeJS in ubuntu image

### LINKED ISSUE #11606: Benchmark tests broken following update of NodeJS in ubuntu image
## Description

[Benchmark tests](https://github.com/jupyterlab/jupyterlab/actions/workflows/benchmark.yml) are failing due to an update of NodeJS in the ubuntu image that is incompatible with CML action (to publish the benchmark image).

```
Error: The module '/usr/local/lib/node_modules/@dvcorg/cml/node_modules/mmmagic/build/Release/magic.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 83.
```

## Reproduce

Execute a benchmark job

## Expected behavior

No error

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #11606

## Code changes

This avoid raising an error if the script fails to publish the image report to CML. The consequence will be that the report comment won't display the benchmark image (but the image is still available as part of the workflow artifacts).

### CODE REVIEW

**Review by fcollonval — COMMENTED** [review]
please run benchmark

**Comment by fcollonval** [comment]
This fix the CI but creates a boring report...

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
> NODE_MODULE_VERSION 93

93 corresponds to node 16. We could also bump to that version in the benchmarks test?

**Comment by jtpio** [comment]
Merging for now since this fixes the benchmark report as a PR comment.

**Comment by fcollonval** [comment]
> 93 corresponds to node 16. We could also bump to that version in the benchmarks CI workflow?

The trouble is the cml installation that does not apparently use the specified version of node JS but rather one it finds on the os. As GitHub recently added nodejs 16 to the Ubuntu 20.04 image, that breaks CML. This is not related to our code. I opened an issue upstream. No answer yet

**Pull request merged**
