### PR TITLE
Handle notebook kernel in busy state on page reload

### PR DESCRIPTION
**Pull request by karlaspuldaro**
## References
Addresses #9010

## Code changes
Add  kernel status `connecting` as one of the busy display states in the KernelStatus Widget for the notebook toolbar

## User-facing changes
Similar to how classic notebook displays busy kernel status on a page refresh containing a busy kernel, we are handling a kernel hanging on a `connecting` state to be displayed as `busy`, therefore rendering the black circle in the notebook toolbar.
Before these changes, the kernel status circle was being rendered as `idle` on a connecting hanging state, even when  executing code cells.

### CODE REVIEW

**Comment by karlaspuldaro** [comment]
@skukhtichev could you test this PR and let me know if it that's the expected behaviour you were proposing?
I left the `console.log` statement for kernel status info uncommented for debugging purposes.

**Comment by lresende** [comment]
Thank you @karlaspuldaro, I believe this does make the user experience around the issue described in #9010 behave the same as in classic jupyter notebook. Having said that, at some point we should really think about the use case described in https://github.com/jupyter/notebook/pull/4110 where we could use a better session handler, but this would probably come in as a separate discussion and different issue/pr.

**Comment by lresende** [comment]
@jasongrout could you please take a quick look at this. Also, what is the process to merge this into JupyterLab 2.x in order to get this available in the next 2.x release?

**Comment by jasongrout** [comment]
My quick thought on this is: when the kernel is connecting (i.e., we are not receiving kernel messages), we don't know if it is idle or busy. We should have a third visual state showing that the kernel state is unknown.

**Comment by skukhtichev** [comment]
@karlaspuldaro I tested JupyterLab from the branch with the fix and I see that the kernel is shown as busy after reloading the page. I can also listen for incoming kernel messages while the kernel is in busy state by executing `session.anyMessage.connect((sender, msg) => {console.log(msg)})`.

**Comment by jasongrout** [comment]
To elaborate - we separated the kernel state into a [connection status and a kernel status](https://github.com/jupyterlab/jupyterlab/blob/14bcbea1dfa08f0d34bbd1731cbe54cb74780bf3/packages/services/src/kernel/kernel.ts#L72-L80). When the kernel status is not connected, the kernel status is "unknown": https://github.com/jupyterlab/jupyterlab/blob/14bcbea1dfa08f0d34bbd1731cbe54cb74780bf3/packages/services/src/kernel/kernel.ts#L869-L885 https://github.com/jupyterlab/jupyterlab/blob/14bcbea1dfa08f0d34bbd1731cbe54cb74780bf3/packages/services/src/kernel/messages.ts#L514-L541

We combined these status states into a single combined state in https://github.com/jupyterlab/jupyterlab/commit/f4ff2af30f5cde3f2265cf5bd527abab9fe95b8d

However, I think we should still distinguish for the user states where we know what the kernel is doing (busy/idle, etc), and connection states where we are still trying to find out what the kernel is doing (connecting, initializing, etc.).

**Comment by karlaspuldaro** [comment]
Thank you @jasongrout for the info and suggestion, I agree adding the kernel connection state to the status bar will be helpful.

**Comment by karlaspuldaro** [comment]
Update on this:

I've done some further investigation beyond the combined `kernelDisplayStatus` and found  the bug might be a little deeper in the backend.
Reloading the page with a busy kernel, it gets stuck trying to connect to a websocket which never gets completed, falling into a WS buffer, in a loop between `connecting` to `connected` connection states.
In this situation the kernel status remains `unknown`, because in `kernel/default.ts`, neither `_updateStatus` or  `_handleMessage` are  being called.

1 - Is it expected to create so many new websockets on a page reload with a previous busy kernel?
image

2 - Why `_updateStatus` or  `_handleMessage`  aren't being called in this case? What should be a default kernel status when it is `connected`?

3 - UI visual states:
While the toolbar kernel status circle would display `connecting`, the status bar would be `unknown`.
The toolbar widget is only listening to `sessionContext.statusChanged` (not also `sessionContext.connectionStatusChanged`, as the status bar does), hence the message mismatch in both visual states.
Connecting the toolbar widget to `connectionStatusChanged` and fixing the backend status messaging issues above should solve the problem.

@jasongrout thoughts?

**Comment by jasongrout** [comment]
> 1 - Is it expected to create so many new websockets on a page reload with a previous busy kernel?

With one notebook open? No, I'd expect one websocket connection for each kernel connection (i.e., each frontend thing talking to a kernel)




> 2 - Why `_updateStatus` or `_handleMessage` aren't being called in this case? What should be a default kernel status when it is `connected`?

I'm not sure / don't remember off the top of my head. I really wish I had time right now to dive into this with you.


> 3 - UI visual states:
> While the toolbar kernel status circle would display `connecting`, the status bar would be `unknown`.
> The toolbar widget is only listening to `sessionContext.statusChanged` (not also `sessionContext.connectionStatusChanged`, as the status bar does), hence the message mismatch in both visual states.
> Connecting the toolbar widget to `connectionStatusChanged` and fixing the backend status messaging issues above should solve the problem.

I thought the toolbar listened to the combined status? The combined status signal might still be helpful here, if we changed the toolbar widget to recognize the "connecting" status as a third distinct state to display.

**Comment by karlaspuldaro** [comment]
There are cases where we have kernel `connected` but the status is `unknown` (when it falls into the loop where it tries to connect on reload but never gets completed), therefore I also added the `unknown` status as busy to the status bar, since the kernel might be figuring out its connection.
In this case the status bar kernel status can either show `Unknown` or `Connecting` whenever it receives an updated signal from the existing combined status in session context.

The toolbar circle LabIcon is not being properly updated with the status title msg, I asked about this on gitter. Right now `labicon.element()` checks for the element id, if it exists (eg. the black circle icon is in the DOM) it won't update it. If there isn't a way to update the labicon props, I can edit the `element` function to also check for them, not just the element id.

Also I created a new issue on lab (#9133) about the websocket bug.

**Comment by karlaspuldaro** [comment]
@jasongrout This PR is ready for final review.
Let me know if you have a different opinion on my comments above about the status behaviour.

I found a workaround to update the title displayed in the kernel circle labicon by removing it first  - otherwise the `element()` function would just ignore it because it already exists in the DOM. 
If there is no better way to update the labicon props, should I create a new issue to enhance the `element()` function?

**Review by afshin — APPROVED** [review]
Thank you!

👍

**Pull request merged**
