### PR TITLE
Manually trigger benchmark tests instead of running them on `pull_request_review`

### PR DESCRIPTION
**Pull request by jtpio**
## References

Hoping to fix https://github.com/jupyterlab/jupyterlab/issues/15089

And progressively get CI to pass again consistently.

The benchmarks checks have been failing for many months on CI.

These jobs are run on PR approval, and may take a very long time to complete. Which means that in theory a maintainer would have to wait again for a new job to complete (and succeed) before hitting the merge button. Overall this adds a lot of maintenance fatigue and makes it difficult to merge PRs. To the point that it seems that it's just been ignored for the past months?

## Code changes

Run the benchmark on `schedule` instead of `pull_request_review` to get these runs out of the review workflow.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
**> To the point that it seems that it's just been ignored for the past months?

More like only looked on manually for changes which could introduce memory leaks.

Though this does not fix the underlying issue.

**Comment by jtpio** [comment]
Should we trigger these benchmarks when the special "please run benchmarks" sentence is used then? (like for updating Galata snapshots).

This would already help avoid running these workflows by default, and only when they are needed.

**Comment by krassowski** [comment]
Maybe depending on label would be better? Currently benchmarks cover mostly the `pkg:notebook`, maybe a few select others?

**Review by krassowski — APPROVED** [review]

**Comment by jtpio** [comment]
> Maybe depending on label would be better? Currently benchmarks cover mostly the `pkg:notebook`, maybe a few select others?

Yes I guess that can make sense. Although since these benchmarks take a while a run, maybe a maintainer would be interested in running them only at different points in time, not necessarily for each commit?

**Comment by jtpio** [comment]
Thanks @krassowski for the review!

Merging this PR as an incremental improvement towards #15089. We can look into fixing the benchmark workflow and add more triggers as part of #15089.

**Pull request merged**
