### PR TITLE
Ignore empty stdout data when logging in verdaccio

### LINKED ISSUE #16448: "Check release" CI job fails (due to verdaccio timeouts?)
## Description

"Check release" CI job sometimes fails (due to verdaccio timeouts?) for example: https://github.com/jupyterlab/jupyterlab/actions/runs/9397213995/job/25879957029?pr=16447

Restarting helps
 

```
Running hooks for before-build-python
Starting verdaccio on port 4873 in /tmp/verdaccio
...............................................
Verdaccio started
Logging in
stdout: Username:
Passing username...
stderr: npm notice Log in on http://0.0.0.0:4873/
stdout: Password:
Passing password...
stdout:
Uncaught exception [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Unexpected prompt: """.] {
  code: 'ERR_UNHANDLED_REJECTION'
}
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/bin/jupyter-releaser", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py", line 118, in invoke
    util.run(hook)
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 94, in run
    raise e
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 86, in run
    process = tee(cmd, **kwargs)
              ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/tee.py", line 159, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'node buildutils/lib/local-repository start' returned non-zero exit status 1.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/actions/populate_release.py", line 40, in <module>
    run_action("jupyter-releaser build-python")
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/actions/common.py", line 25, in run_action
    _run(target, *args, **kwargs)
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 94, in run
    raise e
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 86, in run
    process = tee(cmd, **kwargs)
              ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/tee.py", line 159, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'jupyter-releaser build-python' returned non-zero exit status 1.
```

</details>

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #16448

## Code changes

Ignore empty stdout message when feeding prompt on verdaccio login.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by fcollonval** [comment]
Ok ignoring empty stdout is doing the job. 

The log when logging in to verdaccio are

```sh
Verdaccio started
Logging in
stdout: Username:
Passing username...
stderr: npm notice Log in on http://0.0.0.0:4873/
stdout: Password:
Passing password...
stdout:
Ignoring empty stdout.
stdout:
Ignoring empty stdout.
stdout: Logged in on http://0.0.0.0:4873/.
```

And ci is back to green

Cc @krassowski @jtpio

**Review by krassowski — APPROVED** [review]
Thanks so much @fcollonval!

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.0.x
@meeseeksdev please backport to 4.1.x
@meeseeksdev please backport to 4.2.x

**Comment by krassowski** [comment]
@meeseeksdev please backport to 3.6.x

**Pull request merged**
