### PR TITLE
Backport PR #15262 on branch 4.0.x (Fix connection loop issue with standalone foreign document in LSP)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #15262: Fix connection loop issue with standalone foreign document in LSP

### CODE REVIEW

**Comment by krassowski** [comment]
@JasonWeill CI failures are unrelated, it looks like something in the runner's environment changed leading failures on `hatchling` level, see https://github.com/jupyterlab/jupyterlab/issues/15692; we can restart once this is fixed.

**Comment by krassowski** [comment]
Restarting CI after new hatchling release

**Comment by JasonWeill** [comment]
please update documentation snapshots

**Comment by krassowski** [comment]
@JasonWeill there should be no snapshot changes for this PR. The updates for snapshots are basically flaky runs showing up. There is a PR https://github.com/jupyterlab/jupyterlab/pull/15578 backporting fixes for this but it still needs more work.

**Comment by JasonWeill** [comment]
@krassowski Reverted; sorry about the confusion

**Comment by JasonWeill** [comment]
@krassowski Should I wait until #15578 is merged before I merge this change?

**Comment by krassowski** [comment]
No, but I would like to test it with `jupyterlab-lsp` extension to ensure that users would not be affected by this change; it is likely that some mitigation may be needed.

**Review by krassowski — APPROVED** [review]
Thanks. It looks like this does not break jupyterlab-lsp further than it was broken by earlier backports. It might break source installs but I will deal with it on my side.

**Pull request merged**
