### PR TITLE
Update Lumino to latest versions

### LINKED ISSUE #11412: In JupyterLab 3.2.2 can't use Arrows shortcuts
## Description
Hi all,
I apologise in advance if this was already under your radar. I searched for a similar issue but can't find any. 

In JupyterLab 3.2.2, I can't make use of Arrows to execute cell commands. 
For instance, moving between cells using ArrowUp or ArrowDown doesn't work, and I need to use the J/K keys combination instead.

The ArrowUp/ArrowDown events scroll the page instead.

## Reproduce
Open a notebook, and use ArrowUp or ArrowDown to move between existing cells, or Shift-ArrowUp/Shift-ArrowDown to select multiple cells.

The equivalent with J/K keys would work.

## Expected behavior
I expect to be able to use/modify Arrows shortcuts to execute commands such as selecting cells and activating cells.
 
In JupyterLab 3.2.1 Arrows are working well.

## Context

- Operating System and version: Tested on CentOS7 and MacOS Big Sur
- Browser and version: Chrome v 95 and Microsoft Edge Version 95 on Mac OS
- JupyterLab version: 3.2.2

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### PR DESCRIPTION
**Pull request by jasongrout**
## References

This pulls in some bugfixes from Lumino, such as fixing arrow key shortcuts.

Fixes #11412

## Code changes

Update Lumino to latest versions, which should be backwards compatible.

## User-facing changes

Keyboard shortcuts are now displayed according to platform conventions. 

## Backwards-incompatible changes

I think this is backwards compatible, and fixes a big bug in 3.2.x.

### CODE REVIEW

**Review by fcollonval — COMMENTED** [review]
UI regressions sound legit. You probably want to merge #11388 and rebase to ease upgrading snapshots?

**Comment by jasongrout** [comment]
One of the failures is interesting: `Error: HttpError: Validation Failed. Issues cannot have more than 100 labels:`

**Comment by jtpio** [comment]
Just rebased onto the latest

**Comment by jtpio** [comment]
The UI Tests fail because the keyboard shortcut changed from `Del` to `Delete`:

image

Updating the snapshots in the next commit.

**Review by fcollonval — APPROVED** [review]
LGTM thanks @jasongrout and @jtpio 

The remaining CI failure is acceptable.

**Pull request merged**
