### PR TITLE
Join cells source lines with empty string.

### LINKED ISSUE #2751: Jupyterlab Google drive extension adds blank lines to code,
Hi there,
When I try to open a .ipynb in my personal Google Drive, it adds new (blank) lines each line of code in every cell. Even if it is a new .ipynb it still adds the blank lines in every cell.

I am using
JupyterLab version - 0.26.4

and used 
```bash
jupyter labextension install @jupyterlab/google-drive 
```
to activate the plugin 

Any idea what is happening?

Thanks
test

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes #2751.

Since this is a change to the notebook, we may hold off on this until #2540 lands, so until then, consider this supporting material for #2751.

### CODE REVIEW

**Comment by blink1073** [comment]
Legitimate test failures:

```
FAILED TESTS:
  cells/model
    CellModel
      #constructor()
        ✖ should accept a base cell argument with a multiline source
          Firefox 54.0.0 (Linux 0.0.0)
        expected 'foobarbaz' to equal 'foo\nbar\nbaz'
        Assertion.prototype.assert@webpack:///~/expect.js/index.js:96:0 <- build/bundle.js:5359:13
        Assertion.prototype.equal@webpack:///~/expect.js/index.js:216:0 <- build/bundle.js:5479:5
        @webpack:///build/cells/model.spec.js:57:0 <- build/bundle.js:85921:17
        
      #toJSON()
        ✖ should always return a string source
          Firefox 54.0.0 (Linux 0.0.0)
        expected { cell_type: 'raw', source: 'foobarbaz', metadata: {} } to sort of equal { cell_type: 'raw',
          source: 'foo\nbar\nbaz',
          metadata: {} }
        Assertion.prototype.assert@webpack:///~/expect.js/index.js:96:0 <- build/bundle.js:5359:13
        Assertion.prototype.eql@webpack:///~/expect.js/index.js:230:0 <- build/bundle.js:5493:5
        @webpack:///build/cells/model.spec.js:189:0 <- build/bundle.js:86053:17
        
```

**Comment by ian-r-rose** [comment]
Sure, we can merge this or not, since it will quickly be deprecated. Will we be able to handle this case in `coreutils/nbformat` with the new approach?

**Comment by blink1073** [comment]
We'll be using `string` everywhere there is currently a `multilinestring` in `nbformat`, so implementations will have to serialize as a string (the notebook contents manager already does because nbformat is joining the strings).

**Comment by blink1073** [comment]
The Travis failures will be fixed by https://github.com/jupyterlab/jupyterlab/pull/2755.

**Comment by blink1073** [comment]
Not sure what's going on with Appveyor all of a sudden, investigating.

**Comment by ian-r-rose** [comment]
I see a passing Appveyor build.

**Comment by blink1073** [comment]
Yep, I had restarted it.

**Comment by blink1073** [comment]
Thanks!

**Pull request merged**
