### PR TITLE
Backport PR #12609: Fix the side-by-side cell resize handle 

### PR DESCRIPTION
**Pull request by echarles**
Hi, this is @echarles I have manually backported https://github.com/jupyterlab/jupyterlab/pull/12609 to 3.4.x

### CODE REVIEW

**Comment by echarles** [comment]
CI has not picked up. Closing/Reopening.

**Comment by echarles** [comment]
@fcollonval CI is green. This backport is ready to be mergeD.

**Review by fcollonval — APPROVED** [review]
Thanks

**Comment by echarles** [comment]
Super. Thx @fcollonval

**Pull request merged**
