### PR TITLE
Rewrite `markdownviewer` as a standard extension

### LINKED ISSUE #3940: The Markdown preview is slow
The whole JupyterLab is very responsive and fast, but the Markdown preview is very slow, it feels it takes like 1s to update the preview after I press a key to modify the source. 

I mentioned it on [Twitter](https://twitter.com/OndrejCertik/status/966085118057054208) and @Carreau [replied](https://twitter.com/Mbussonn/status/966100972291334144) that it's probably because it does a full render every-time, and a solution is to use a diff-aware Markdown renderer.

So I am opening up an issue for this.

### PR DESCRIPTION
**Pull request by AlbertHilb**
Fixes #3940, #5748

I rewrote `markdownviewer` as a standard extension and I added a section in the Settings Editor dedicated to it. Users now can:

- customize how markdown is rendered setting the family and the size of the font, and the height and the width of the text line.
- choose whether to hide the document YALM front matter (if present): a metadata block placed at the top of the document, beginning with a line of three dashes and ending with a line of three dashes (---) or three points (...).
- change the render timeout.

Cheers

### CODE REVIEW

**Comment by AlbertHilb** [comment]
Hi @ian-r-rose, I guess I can merge now, right?

**Comment by ian-r-rose** [comment]
@AlbertHilb normally we try to review and merge each other's PRs.

Can you move that one command from the docmanager-extension to the markdownviewer-extension?

**Comment by AlbertHilb** [comment]
> Can you move that one command from the docmanager-extension to the markdownviewer-extension?

Sure! Sorry for the oversight. :grimacing:

> normally we try to review and merge each other's PRs.

Got it. :blush:

**Comment by ian-r-rose** [comment]
> Sure! Sorry for the oversight. :grimacing: 

No need for apologies! Just flagging it!

**Comment by AlbertHilb** [comment]
Hi @ian-r-rose, I moved the command.

**Pull request merged**
