### PR TITLE
Fix contrast on the plugin list, add screenshots to catch regressions

### LINKED ISSUE #13660: Labels in settings are hard to read on HEAD
## Description

This is a regression introduced in https://github.com/jupyterlab/jupyterlab/pull/13276 (not caught by the UI tests)

Screenshot from 2022-12-24 19-33-17

`--jp-content-font-color1` (contrast 14.21) was replaced by `--jp-ui-font-color2` (contrast 4.42). It probably was meant to be `--jp-ui-font-color1` and is a simple copy-paste error.

### PR DESCRIPTION
**Pull request by krassowski**
## References

Fixes #13660

## Code changes

- `--jp-ui-font-color1` → `--jp-ui-font-color2`
- add screenshots test in galata test

## User-facing changes

Better contrast

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
please update galata snapshots

**Comment by krassowski** [comment]
please update galata snapshots

**Comment by krassowski** [comment]
please update galata snapshots

**Review by fcollonval — APPROVED** [review]
Thanks @krassowski

**Pull request merged**
