### PR TITLE
Restore workspace and open _tree_ path

### LINKED ISSUE #10876: workspace is restored instead of loading requested document via `/tree/notebook.ipynb`
## Description

Using `/user-redirect/...` does not get the user to the destination **if** the workspace is not **empty** (i.e. a notebook was already opened previously). Instead of opening the requested URL, the user is sent to his restored workspace.

If the workspace has been cleaned (closing all tabs and terminals, leaving only the launcher) before using the `/user-redirect/...` URL, then the redirection works as expected.

## Reproduce

There are many scenarios that are impacted by this bug. Here are several ways to reproduce this issue:

1. Start your jupyterlab session. Open notebook `A.ipynb`. 
URL is `https://[hubname]/user/[user-id]/lab/tree/A.ipynb`
Change URL to `https://[hubname]/user-redirect/lab/tree/B.ipynb`, press [ENTER]
=> `A.ipynb` is still displayed.
If workspace is emply, then redirection works as expected.

2. Using a jupyterhub: log in and Open notebook `A.ipynb` and then logout.
Add `?next=/user-redirect/lab/tree/B.ipynb` to the hub URL and log in again
=> `A.ipynb` is still displayed.
If workspace is emply, then redirection works as expected.

3. Using nbgitpuller server extension - basically the same as above, but there is a little difference: when nbgitpuller has to clone the repository (first time the URL is used), then the redirection works. However, when the repository is already available in the user's workspace, then the redirection fails and the user is sent to his workspace.
If workspace is emply, then redirection works as expected.

Note: you need a patched version of nbgitpuller for jupyterlab 3.1.x, see https://github.com/jupyterhub/nbgitpuller/pull/193

## Expected behavior

I expect the user to be **always** sent to the specified `/user-redirect/...` URL.

I expect the events to happen **always** in the following order:
1. The workspace (tabs, etc.) is restored first
2. The `/user-redirect/...` redirection happens

## Context

- Operating System and version:  Gentoo Linux (same behavior on other OSes)
- Browser and version:  Google Chrome Version 92.0.4515.159 (Official Build) (64-bit) (Same behavior with Firefox)
- JupyterLab version:  3.1.x (tested with 3.1.6 and 3.1.7)

<details><summary>Troubleshoot Output</summary>
<pre>
n/a
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
When running JupyterLab with `--debug` parameter, no warning or errors are displayed.
We can see from the logs that the `/user-redirect/...` URL is processed first,
then we can see a GET on the workspace URL.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
No javascript errors or warnings are visible.
</pre>
</details>

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #10876

## Code changes

Forbid setting `pageconfig.treePath` before the tree resolver is done.

Add integration tests for workspaces.

## User-facing changes

When opening a file from a _tree path_, the user will see the file in its restored session.

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thank you!

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.2.x

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.1.x

**Comment by gentaliti** [comment]
@blink1073 is there a plan to blackport this to 3.0.x?

**Pull request merged**
