### PR TITLE
Export Command Ids

### LINKED ISSUE #1401: Command ids should be exported and handled uniformly
We are currently handling command ids in an ad-hoc fashion.  They should be exported from an index file as an object so that they can be referenced from multiple places and not just copied around.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #1401.

### CODE REVIEW

**Comment by jasongrout** [comment]
So is the official API the string, or the exported value? In other words, if you change the string, but don't change the exported name, is that considered a breaking change?

**Comment by blink1073** [comment]
The API is the value.  If the string changes, that would be a patch release.

**Comment by jasongrout** [comment]
> If the string changes, that would be a patch release.

A major release, right? It would be a backwards-incompatible change to change the name of a command.

**Comment by blink1073** [comment]
True, for shortcuts that were specified in JSON.

**Comment by blink1073** [comment]
If we didn't have that, the JavaScript consumers would just get the latest string.

**Comment by afshin** [comment]
I think this is a good idea 👍

**Pull request merged**
