### PR TITLE
Support for output search

### PR DESCRIPTION
**Pull request by mlucool**
## References
Fixes: #6768 

## Code changes
This is the first pass at search which can search output in a generic way. This commit does this on a best effort through walking and manipulating the DOM. There are limitations, including the inability to handle that to a user `<span><b>foo</b>bar</span>` should be searched as `foobar`. This also will not handle SVGs and does not expose a way to delegate search to output presenters. Still, this works well on stdout/stderr type messages, tables, etc.

## User-facing changes
Search will now include output of code cells, this allows users to look for `foo` in both input and output. Unlike cod cells, replace will be ignored here.

Before:
image

After:
image

Example showing it working on pandas output:
image

### CODE REVIEW

**Comment by mlucool** [comment]
cc @aschlaep @jasongrout

**Comment by mlucool** [comment]
Ping @aschlaep @jasongrout

**Comment by afshin** [comment]
Considering how minimal the use of `lodash` is in this particular PR, I would suggest not using it at all. All of the uses seem available already in `ArrayExt` in `@phosphor/algorithm` https://phosphorjs.github.io/phosphor/api/algorithm/modules/arrayext.html

**Comment by telamonian** [comment]
I'm seeing an issue whereby certain search highlighting never gets cleared. For example, if I search for "i" and then "invalid" repeatedly, this happens:

image

**Comment by telamonian** [comment]
Following @afshin's suggestion, I replaced the uses of `lodash` with `@phosphor/algorithm`. I tested and the PR's behavior is unaffected by the change, including the highlighting bug I mentioned in the previous post.

**Comment by mlucool** [comment]
Thanks @telamonian. I seeing if I can figure out a way to fix that bug. Just so you have some understanding:
image

This is what the DOM looks like before we mutate it for highlight. Now when we highlight we wrap some text in a span and save the old node to replace. In this case the `i` in the last `invalid` causes problems because it's saving some node state that had already been mutated.

I.e. it stores this partially mutated node instead of a true original node:
image

**Comment by mlucool** [comment]
@telamonian This has been fixed. Can you try again?

**Comment by mlucool** [comment]
@telamonian

It seems the only issue remaining is that searching more of the dom continues to reduce performance. 

What do people think of using this little space to add in the option via a dropdown menu for: In/Out/All
image

**Comment by mlucool** [comment]
@telamonian - any more thoughts on this to move it forward? Is there a favorite option that we should do to get this merged?

**Comment by mlucool** [comment]
@telamonian I have added the ability to do this in the UI as I think users may want to flip back and forth.

While I think the expanded UI needs a little UX work (I didn't know how to easily turn a button into a dropdown menu), it is totally functional:

Default:
image

Expanded:
image

**Comment by telamonian** [comment]
Thank you for continuing to push forward on this.

I agree that the UI definitely needs a bit of work. The two input/four state thing is confusing even me a little.

Since it's tomorrow, I'll bring this up at the weekly dev meeting and see what @tgeorgeux (our UI/UX guy) and the rest of the community thinks. You're welcome to join, if you'd care to; it's at noon ET, and the link is [here](https://github.com/jupyterlab/jupyterlab#weekly-dev-meeting).

**Comment by tgeorgeux** [comment]
@telamonian I've mocked up a simple UI that allows different actions in an options menu.

[Mockup](https://www.figma.com/proto/kDMQ092Twv8bCO5ozUiFCH/pull-request-7258-Support-for-output-search.?node-id=1%3A27&viewport=-686%2C255%2C0.9179583787918091&scaling=min-zoom)

[Design Files](https://www.figma.com/file/kDMQ092Twv8bCO5ozUiFCH/pull-request-7258-Support-for-output-search.?node-id=0%3A1)

**Comment by jasongrout** [comment]
Would it be possible to have the options open while searching, perhaps as a panel below the find/replace lines? That would allow content-specific widgets, not just a set of options. For example, I can imagine a map search showing a thumbnail of the entire map, and you being able to draw a rough region to filter find results.

For example, in vs code, the sidebar search has three dots to expand a filtering mechanism:
Screen Shot 2019-11-20 at 2 42 42 PM
Screen Shot 2019-11-20 at 2 42 54 PM

**Comment by tgeorgeux** [comment]
@jasongrout Something like this:

[Option 2 Prototype](https://www.figma.com/proto/kDMQ092Twv8bCO5ozUiFCH/pull-request-7258-Support-for-output-search.?node-id=4%3A328&viewport=-139%2C256%2C0.6013386249542236&scaling=min-zoom)
[Option 2 Design Files](https://www.figma.com/file/kDMQ092Twv8bCO5ozUiFCH/pull-request-7258-Support-for-output-search.?node-id=4%3A328)

**Comment by telamonian** [comment]
Summary of the relevant bits of today's dev meeting:

- output search is notebook specific, and we want our basic filesearch UI to be simple and content agnostic. Thus, extra options like output search will be hidden behind an `...` button
- the output search option makes most sense as a single binary (eg "Search cell outputs" checkbox). We can expand this later if people come to us with use cases for output only search
- searching/highlighting output makes sense in terms of "find", but doesn't make much sense in terms of "find + replace". Thus, output search should automatically be disabled when the "replace" form is revealed (ie when the caret on the left of the search UI is clicked)

@tgeorgeux Your option 2 both looks good and satisfies the above-listed reqs, so I think we should move forward with that.

@mlucool Does this sound good to you? If it seems like too much of a lift, I'd be fine with doing the implementation myself for the new UI

**Comment by jasongrout** [comment]
@tgeorgeux - can you show us what it looks like with the replace line expanded?

**Comment by jasongrout** [comment]
Also, would it make more sense to have the option panel the same width as the find/replace lines?

**Comment by telamonian** [comment]
@jasongrout I kind of like that it only takes up as much space as needed (plus a little margin for style). It allows for (at least slightly) more visibility of a user's actual document.

**Comment by jasongrout** [comment]
> @jasongrout I kind of like that it only takes up as much space as needed (plus a little margin for style). It allows for (at least slightly) more visibility of a user's actual document.

Yes, but the idea is that the content is contributing that section, so different content will have different sizes for that panel. That can be jarring if different content has different widths, whereas I think it looks much better if the width is uniform and the thing the content has control of is the height.

**Comment by mlucool** [comment]
Thanks @telamonian for bringing this up in today's meeting. Sorry I couldn't make it.

> Thus, extra options like output search will be hidden behind an ... button

That makes sense.

> the output search option makes most sense as a single binary (eg "Search cell outputs" checkbox). We can expand this later if people come to us with use cases for output only search

Is there a strong reason for not letting users search only output? While I agree that option may be the least used one, it's easy to think of a few cases when I would choose that.

> searching/highlighting output makes sense in terms of "find", but doesn't make much sense in terms of "find + replace".

While it doesn't make much sense now. We may want this in the future to replace input in an output cell (e.g. jupyter widgets).

**Comment by telamonian** [comment]
@mlucool 

> Is there a strong reason for not letting users search only output? While I agree that option may be the least used one, it's easy to think of a few cases when I would choose that.

The strong(ish) reason is to keep UI clutter/complexity to a minimum, which I think is something we should prioritize in the first pass at this new feature.

> > searching/highlighting output makes sense in terms of "find", but doesn't make much sense in terms of "find + replace".
> 
> While it doesn't make much sense now. We may want this in the future to replace input in an output cell (e.g. jupyter widgets).

Again, this goes back to keeping the UI/outputs as simple and intelligible as possible. If a use case does develop in the future we can always drop this restriction, or even make it context sensitive.

**Comment by mlucool** [comment]
> The strong(ish) reason is to keep UI clutter/complexity to a minimum, which I think is something we should prioritize in the first pass at this new feature.

Makes sense

**Comment by tgeorgeux** [comment]
> @tgeorgeux - can you show us what it looks like with the replace line expanded?

Find And Replace

>Yes, but the idea is that the content is contributing that section, so different content will have different sizes for that panel. That can be jarring if different content has different widths, whereas I think it looks much better if the width is uniform and the thing the content has control of is the height.

With one option
Find And Replace - One Option
With Two
Find And Replace - Two Options
With more...
Find And Replace - Four Options

**Comment by saulshanabrook** [comment]
I am re-reading through this conversation and the code, in the hope of moving this forward. Going back to the impetus of adding a toggle for searching outputs from @mlucool:

> It seems the only issue remaining is that searching more of the dom continues to reduce performance.

It seems like adding the toggle is a work around for performance issues. If we could resolve the performance issues, @mlucool do you think we could just keep it on by default?

**Comment by mlucool** [comment]
> It seems like adding the toggle is a work around for performance issues. If we could resolve the performance issues, @mlucool do you think we could just keep it on by default?

I think the toggle is required in general. There are times you only want to search input. Still, if the performance issue were solved*, my personal preference is the default output is searched and you can toggle this off.

*W.r.t performance, it would have to have similar performance to native find with 100s of cells to consider the performance issue solved.

**Comment by saulshanabrook** [comment]
@tgeorgeux Do you know of anywhere else in the app we have similar styles for checkboxes I could look at to inspire this?

**Comment by saulshanabrook** [comment]
My TODO:

- [ ] Style fixes
  - [ ] Disable outputs filter on non notebooks
  - [ ] disable showing filter button when no filters enabled
  - [ ] Align icon view with tim's mockup
  - [ ] Align text to tim's mockup
- [ ] Fix bug max found https://github.com/jupyterlab/jupyterlab/pull/7258#issuecomment-547165826

**Comment by mlucool** [comment]
>  Fix bug max found #7258 (comment)
That was fixed in https://github.com/jupyterlab/jupyterlab/pull/7258#issuecomment-547196673. Are you still able to reproduce?

**Comment by saulshanabrook** [comment]
@mlucool Nope, just missed that message, thank you!

**Comment by telamonian** [comment]
> It seems like adding the toggle is a work around for performance issues. If we could resolve the performance issues, @mlucool do you think we could just keep it on by default?

I looked into this before I initially pushed forward on making this toggle-able. I didn't write anything down before, so this comment will in part be for my own notes.

Getting to native search performance will require access to the browser's native search capabilities, which there's apparently no good way to do right now:

- [`window.find()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/find) doesn't do what we would need, isn't standardized, and apparently is [very](https://bugs.chromium.org/p/chromium/issues/detail?id=695564) [buggy](https://bugzilla.mozilla.org/show_bug.cgi?id=672395)

- There was a proposed [`findText`](http://w3c.github.io/findtext/) API that we might have been able to work with, but it's apparently been discontinued

In the future, we'll improve performance in general for large notebooks by using some kind of pagination scheme (eg `react-window`). Output search may end up being kind of a blocker for pagination though, since fundamentally in order to do output search correctly we have to search *rendered* DOM nodes. Not sure how to resolve that yet.

In any case, that all is probably better dealt with in future PRs, which is why a toggle for this feature is needed for now.

Other refs:
https://w3c.github.io/selection-api/
https://w3c.github.io/editing/execCommand.html

**Comment by saulshanabrook** [comment]
@telamonian Thank you max for that in depth explanation! Yep, I am good to move forward on adding the toggles, I am working on styling them right now.

(Another option in the future would be to search the un-rendered output instead of the rendered dom nodes, which I imagine we could have more flexibility in how we implement, but let's postpone that for another issues)

**Comment by saulshanabrook** [comment]
We talked about this in our weekly meeting. We agreed that long term it makes sense to clean up all styles to align them with Tim's styles as well as adding a pluggable mechanism for defining new options. However, in this PR we can move forward on just having passable styles and making sure the user behavior is correct. The changes we need are:

- [ ] Remove "Show ouputs" totally from text editor version
- [ ] Make sure text is part of label for show outputs
- [ ] Grey out text when its disabled as well
- [ ] Disable search outputs when find and replace is open
- [ ] Add background UI color of 3 to ... button when it is open

**Comment by jasongrout** [comment]
>   * Remove "Show ouputs" totally from text editor version

I would say:

> Remove "Show ouputs" totally from anything but the notebook

(which may technically be equivalent in the current design)

**Comment by jasongrout** [comment]
Also:

- [ ] Delete "Search Options" header

**Comment by saulshanabrook** [comment]
@jasongrout, thanks! Yep sounds good.

**Comment by tgeorgeux** [comment]
[ ] Make label clickable to toggle checkbox.

I know this is sort of covered by the 'grey out lable' check-box but I'd like to make sure this gets in as well.

**Comment by saulshanabrook** [comment]
@tgeorgeux any other commits you wanna push before this is ready to go in?

**Comment by tgeorgeux** [comment]
Let it go. I will open any new changes in a new PR. I think next step is to
Port it to the new UI package

**Comment by saulshanabrook** [comment]
I was about to merge this in this morning, but last night I had another thought. My understanding (but please correct me if I am wrong here) is that implementing find and replace in JupyterLab is mostly about the *replace* half. Otherwise, we can mostly use the browser's find and replace. Which seems like it will always be more performant.

So I wonder if your goal, @mlucool, of searching outputs might be better served by just using the native search. You could rebind JupyterLab's find and replace to another hot key, so that you could access both easily. What do you think?

Otherwise, we can merge this in, but I am just trying to exhaust all other options since it does add a non trivial amount of logic we will have to maintain and additional UI complexity.

**Comment by afshin** [comment]
@saulshanabrook:
> implementing find and replace in JupyterLab is mostly about the *replace* half

I think the *find* part is just as important. And IDE typically has several search options as well, like regular expression match, case sensitivity, word or substring match, etc. In JupyterLab, in particular, we'll likely want things like inputs only, outputs only, etc. on the find side.

**Comment by jasongrout** [comment]
> I think the _find_ part is just as important.

Yes. We have more context than the browser, so theoretically can offer more targeted, smarter search. Things like finding a place on a map view, finding a value in a datamodel where only a window is shown in the browser, etc.

**Comment by saulshanabrook** [comment]
Alright, sounds good @jasongrout and @afshin. If there are no objections then, we can merge this in.

**Comment by jasongrout** [comment]
>  If there are no objections then, we can merge this in.

(I haven't evaluated this PR, and probably won't be able to soon, so don't wait for my approval. I just wanted to chime in on your comment.)

**Comment by saulshanabrook** [comment]
Cool. Please tag me on any bugs or issue about this or future search filtering things.

**Pull request merged**
