### PR TITLE
✏️ Fix minor typos in docs for extensions.

### PR DESCRIPTION
**Pull request by tiangolo**
## User-facing changes

✏️ Fix minor typos in docs for extensions.

### CODE REVIEW

**Comment by blink1073** [comment]
Congrats on your your first and second contributions to JupyterLab!

**Comment by tiangolo** [comment]
Thanks! :rocket:

**Comment by tiangolo** [comment]
And thanks for the invite! :smile: :nerd_face: :rocket:

**Comment by blink1073** [comment]
Welcome!

**Pull request merged**
