### PR TITLE
Simplify application context menu cache, rename to be clearer.

### PR DESCRIPTION
**Pull request by ian-r-rose**
This function is still a bit of a hack, but a useful one at times. This tries to simplify it and make it a bit clearer.

### CODE REVIEW

**Comment by jasongrout** [comment]
@ian-r-rose - it seems that composedPath is now pretty well supported. What do you think about using it? https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath

**Comment by ian-r-rose** [comment]
Sure, I'll try that.

**Comment by jasongrout** [comment]
```diff
diff --git a/packages/application/src/frontend.ts b/packages/application/src/frontend.ts
index c9bd3196c..637bab0f4 100644
--- a/packages/application/src/frontend.ts
+++ b/packages/application/src/frontend.ts
@@ -115,17 +115,7 @@ export abstract class JupyterFrontEnd<
     ) {
       return undefined;
     }
-    // This one-liner doesn't work, but should at some point in the future
-    // `return this._contextMenuEvent.composedPath() as HTMLElement[];`
-    // cf. (https://developer.mozilla.org/en-US/docs/Web/API/Event)
-    let node = this._contextMenuEvent.target as HTMLElement;
-    do {
-      if (test(node)) {
-        return node;
-      }
-      node = node.parentNode as HTMLElement;
-    } while (node.parentNode && node !== node.parentNode);
-    return undefined;
+    this._contextMenuEvent.composedPath().find(test);
   }
 
   /**
```

**Comment by jasongrout** [comment]
Or maybe even simpler:


```patch
diff --git a/packages/application/src/frontend.ts b/packages/application/src/frontend.ts
index c9bd3196c..dda4d7aea 100644
--- a/packages/application/src/frontend.ts
+++ b/packages/application/src/frontend.ts
@@ -109,22 +109,9 @@ export abstract class JupyterFrontEnd<
   contextMenuHitTest(
     test: (node: HTMLElement) => boolean
   ): HTMLElement | undefined {
-    if (
-      !this._contextMenuEvent ||
-      !(this._contextMenuEvent.target instanceof HTMLElement)
-    ) {
-      return undefined;
+    if (this._contextMenuEvent) {
+      this._contextMenuEvent.composedPath().find(test);
     }
-    // This one-liner doesn't work, but should at some point in the future
-    // `return this._contextMenuEvent.composedPath() as HTMLElement[];`
-    // cf. (https://developer.mozilla.org/en-US/docs/Web/API/Event)
-    let node = this._contextMenuEvent.target as HTMLElement;
-    do {
-      if (test(node)) {
-        return node;
-      }
-      node = node.parentNode as HTMLElement;
-    } while (node.parentNode && node !== node.parentNode);
     return undefined;
   }
 ```

**Comment by jasongrout** [comment]
Or perhaps we want to filter event targets to be just html elements? `return this._contextMenuEvent.composedPath().filter(x => x instanceof HTMLElement).find(test);` or something...

**Comment by ian-r-rose** [comment]
Yeah, I think we should filter.

**Comment by ian-r-rose** [comment]
Okay, updated.

**Comment by jasongrout** [comment]
Nice! Does it actually work too? (I didn't test it...)

**Comment by ian-r-rose** [comment]
Hmm, it seems to have some problems.

**Comment by ian-r-rose** [comment]
`composedPath()` is returning an empty array some of the time, for reasons I don't know. I may back out that last commit, as nice as it looks.

**Comment by jasongrout** [comment]
Okay, that's fine. Your version was pretty nice too. I liked the way you simplified it down to a do-while.

**Pull request merged**
