### PR TITLE
Toc running cell indicator

### PR DESCRIPTION
**Pull request by andrewfulton9**
## References

Related to #10452

TODO:

- [x] Update doc string
- [x] Update screencast
- [x] Add UI tests

## Code changes

- Make the notebook toc generator as a class so it clarify it
- Store a running cells array in that new generator class (as it does not make really sense in the options container)  
  It got updated by listening to the `NotebookActions.executionScheduled/executed` signals.
- Use a three state `isRunning` attribute on the heading to distinguish: _Idle_, _Scheduled_, _Running_
- Set `data-running` attribute on the toc item with the `isRunning` status
- Use pure CSS to define the indicator, so that it can be tuned easily.
- Add '*' to the scheduled/running prompts if code cell are displayed.

## User-facing changes

Adds indicator to ToC headings if they or a cell in their section is scheduled to run, or running.

toc_running_status

## Backwards-incompatible changes

`Registry.IOptionsManager` is now a _interface_ not a _abstract class_ to be coherent with the naming (and that nothing was defined in it).

### CODE REVIEW

**Review by fcollonval — DISMISSED** [review]
From the implementation point of view, we should avoid crowding the metadata; especially with transient information that have no meaning in the file. So I would recommend using the execution signals as used by the execution indicator: https://github.com/jupyterlab/jupyterlab/blob/e4e323992d24f6c5e48d181381e23c547b665b15/packages/notebook/src/actions.tsx#L96

**Comment by andrewfulton9** [comment]
Thanks for the feedback!

> * What is displayed if multiple cells are queued for execution?

There will be a circle on each section that has pending or executing cells. I couldn't figure out a way to differentiate between the two unfortunately. It could be assumed the top most cell if the one that's running, but only if cells are run in order. 

> * If the running cell(s) are collapsed, is there an execution indicator?

Yes, the execution indicator will still be on the section in the ToC. If the ToC sections are collapsed, the indicator will be on the highest visible level.

> From the implementation point of view, we should avoid crowding the metadata; especially with transient information that have no meaning in the file. So I would recommend using the execution signals as used by the execution indicator:

I just pushed up some edits that remove the use of metadata, using a new `OptionsManager` attribute that holds an array of running cells to track which ones are scheduled for execution. It responds a little slower, but it keeps metadata clear. What do you think about this method, @fcollonval?

**Comment by fcollonval** [comment]
The new approach looks great @andrewfulton9 
Regarding how to deal with queued vs currently running cell, I will play a bit with this PR. But I'm convinced we can figure out the status by looking at the order in the running cells array. 

I'll look to that this week.

**Comment by fcollonval** [comment]
Thanks Andrew for merging my changes. I listed the 3 remaining tasks and updated the initial comment to reflect the current status. Do you want to tackle adding UI tests?

**Comment by andrewfulton9** [comment]
I have tested the new changes and everything looks good to me. Thanks for the additions @fcollonval!

**Comment by fcollonval** [comment]
@jweill-aws would you mind reviewing this one?

**Comment by jweill-aws** [comment]
@fcollonval I've reviewed this including on Binder. I'm not authorized to merge this PR, but it looks good to me. Thanks @andrewfulton9 !

**Comment by andrewfulton9** [comment]
@meeseeksdev please backport to 3.3.x

**Comment by echarles** [comment]
@meeseeksdev please backport to 3.3.x

**Pull request merged**
