### PR TITLE
Fix verdaccio start up with nodejs 18.14.0

### PR DESCRIPTION
**Pull request by fcollonval**
## References

The CI release test is failing very often recently

## Code changes

Bump verdaccio

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by fcollonval** [comment]
This does not solve the issue

There is a redundancy between check_release and release_test. The later is more complete as it test the release assets. But the former is closer to the release process as it uses the releaser. So it would be good to add a job in the check_release workflow that test the package as done in the release_test and drop that one.

**Comment by jtpio** [comment]
> So it would be good to add a job in the check_release workflow that test the package as done in the release_test and drop that one.

This sounds good. I think the `release_test` predates the releaser and was kept because it indeed tests more things.

**Comment by fcollonval** [comment]
The issue is due to the removal of `npm bin` in npm 9: https://docs.npmjs.com/cli/v9/using-npm/changelog#-breaking-changes

I don't know why it did not fail for previous nodejs 18 version - I guess the command was silently failing.

**Comment by fcollonval** [comment]
Ok I found the culprit, with NodeJS v18.14.0 npm has been bump from v8 to v9:

image

Ref: https://nodejs.org/en/download/releases/

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.6.x

**Pull request merged**
