### PR TITLE
PR: Add shim for safari missing idlecallback calls

### PR DESCRIPTION
**Pull request by goanpeca**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/9983

### CODE REVIEW

**Comment by jasongrout** [comment]
Should a polyfill like this just be at the top level, rather than inside a some other scope?

**Comment by goanpeca** [comment]
>Should a polyfill like this just be at the top level, rather than inside a some other scope?

Maybe 🤷🏼, except is not a polyfill:

https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API#falling_back_to_settimeout

>This isn't a polyfill, since it's not functionally identical; 

Still, maybe it should be moved indeed. Where should I put this @jasongrout  :) ?

**Comment by jasongrout** [comment]
> This isn't a polyfill, since it's not functionally identical;

Oh :). I suppose in this context it doesn't matter if it is a polyfill or not, in that it is providing substitute functionality in the same function name.

Typically we'll put these "polyfills" in the main function namespace so they are set once when the module is imported. For example, here we polyfill the global fetch at the top of the module: https://github.com/jupyterlab/jupyterlab/blob/36db8f75655d487d06cabe6b0fd5ecb0ca5c7d54/packages/services/src/serverconnection.ts#L21

**Comment by echarles** [comment]
@goanpeca Looks good to me. Before merging, can you confirm it works fine on your Safari?

**Comment by goanpeca** [comment]
>Looks good to me. Before merging, can you confirm it works fine on your Safari?

It works on my safari, I did the checks. If someone else could also check, that would be great :)

**Review by blink1073 — APPROVED** [review]
Thanks!  I verified locally as well.  CI failures are unrelated.

**Comment by echarles** [comment]
Thx @goanpeca and @blink1073

**Pull request merged**
