### PR TITLE
Always check local packages against abspath

### PR DESCRIPTION
**Pull request by mlucool**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/10661

## Code changes

Move relative paths to abs paths for local extensions

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by blink1073** [comment]
Kicking CI

**Comment by mlucool** [comment]
@blink1073 do you know if the failing tests are likely real issues or CI issues?

**Comment by blink1073** [comment]
Since it is cross-platform I would say they are real issues, path handling tends to be a thorny issue.

**Comment by afshin** [comment]
@mlucool I rebased this and ran again, it does look like the CI failures might actually be related to this path change?

**Comment by mlucool** [comment]
I suspect it's the tests themselves, but really not sure.

OSX:
> error "../../../../../../../../work/jupyterlab/extensions/jupyterlab-mock-extension-4.0.0-alpha.9-1c8a5f81f3eaccceb3163f9e55e4d97a56596242.tgz": Tarball is not in network and can not be located in cache (["/Users/runner/work/jupyterlab/extensions/jupyterlab-mock-extension-4.0.0-alpha.9-1c8a5f81f3eaccceb3163f9e55e4d97a56596242.tgz","/Users/runner/Library/Caches/Yarn/v6/.tmp/c13f11be152c10e33b06bba7491c1435/.yarn-tarball.tgz"])

Windows:
> error "d:/a/jupyterlab/extensions/jupyterlab-mock-extension-4.0.0-alpha.9-4fd1d693cb22532494f9a98ef0e8aef35744ece8.tgz": Tarball is not in network and can not be located in cache (["d:\\a\\jupyterlab\\extensions\\jupyterlab-mock-extension-4.0.0-alpha.9-4fd1d693cb22532494f9a98ef0e8aef35744ece8.tgz","C:\\Users\\runneradmin\\AppData\\Local\\Yarn\\Cache\\v6\\.tmp\\0b3a5bd8151eff8b0a092d5ab005d8bb\\.yarn-tarball.tgz"])

**Comment by fcollonval** [comment]
[a1f2318](https://github.com/jupyterlab/jupyterlab/pull/10662/commits/a1f2318188ab36604003cbe2b5164ba0c55846eb) solves #10661

**Comment by fcollonval** [comment]
Remaining CI failures are not related.

**Review by jtpio — APPROVED** [review]
Thanks all!

**Comment by jtpio** [comment]
@meeseeksdev please backport to 3.4.x

**Pull request merged**
