### PR TITLE
Remove the notebook 5.1 check for large uploads

### LINKED ISSUE #9601: Remove 15MB upload limit
## Description

There is a hardcoded 15MB upload limit in new version of jupytelab, please fix it.

image

## Reproduce

1. install jupyterlab==3.0.3
2. Go to jupyterlab
3. Upload a file which > 15MB

## Expected behavior

 I downgrade jupyterlab to version 2.0.0, It works.

image
image

## Context

- Operating System and version: Ububtu 20.04
- Browser and version: Google Chrome 87.0.4280.88
- JupyterLab version: jupyterlab==3.0.3

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/games
        /usr/local/games

sys.path:
        /usr/local/bin
        /usr/lib/python38.zip
        /usr/lib/python3.8
        /usr/lib/python3.8/lib-dynload
        /usr/local/lib/python3.8/dist-packages
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.8.5 (default, Jul 28 2020, 12:59:40)
        [GCC 9.3.0]

platform.platform():
        Linux-5.4.0-60-generic-x86_64-with-glibc2.29

which -a jupyter:
        /usr/local/bin/jupyter

pip list:
        Package                Version
        ---------------------- --------------------
        acme                   1.11.0
        alembic                1.4.3
        anyio                  2.0.2
        argon2-cffi            20.1.0
        async-generator        1.10
        attrs                  19.3.0
        Automat                0.8.0
        Babel                  2.9.0
        backcall               0.2.0
        beautifulsoup4         4.9.3
        bleach                 3.2.1
        blinker                1.4
        certbot                1.11.0
        certbot-dns-cloudflare 1.11.0
        certbot-dns-powerdns   0.2.0
        certifi                2019.11.28
        certipy                0.1.3
        cffi                   1.14.4
        chardet                3.0.4
        Click                  7.0
        cloud-init             20.2
        cloudflare             2.8.15
        colorama               0.4.3
        command-not-found      0.3
        ConfigArgParse         1.2.3
        configobj              5.0.6
        constantly             15.1.0
        cryptography           2.8
        dbus-python            1.2.16
        decorator              4.4.2
        defusedxml             0.6.0
        distro                 1.4.0
        distro-info            0.23ubuntu1
        dns-lexicon            3.5.3
        dnspython              2.1.0
        entrypoints            0.3
        filelock               3.0.12
        future                 0.18.2
        httplib2               0.14.0
        hyperlink              19.0.0
        idna                   2.8
        importlib-metadata     1.5.0
        incremental            16.10.1
        ipykernel              5.4.2
        ipython                7.19.0
        ipython-genutils       0.2.0
        jedi                   0.18.0
        Jinja2                 2.10.1
        josepy                 1.5.0
        Js2Py                  0.70
        json5                  0.9.5
        jsonlines              2.0.0
        jsonpatch              1.22
        jsonpointer            2.0
        jsonschema             3.2.0
        jupyter-client         6.1.11
        jupyter-core           4.7.0
        jupyter-server         1.2.1
        jupyter-telemetry      0.1.0
        jupyterhub             1.3.0
        jupyterlab             3.0.3
        jupyterlab-pygments    0.1.2
        jupyterlab-server      2.1.1
        keyring                18.0.1
        language-selector      0.1
        launchpadlib           1.10.13
        lazr.restfulclient     0.14.2
        lazr.uri               1.0.3
        Mako                   1.1.3
        MarkupSafe             1.1.0
        mistune                0.8.4
        mock                   4.0.3
        more-itertools         4.2.0
        nbclassic              0.2.6
        nbclient               0.5.1
        nbconvert              6.0.7
        nbformat               5.0.8
        nest-asyncio           1.4.3
        netifaces              0.10.4
        notebook               6.1.6
        oauthlib               3.1.0
        packaging              20.8
        pamela                 1.0.0
        pandocfilters          1.4.3
        parsedatetime          2.6
        parso                  0.8.1
        pcp                    5.0
        pexpect                4.8.0
        pickleshare            0.7.5
        pip                    20.3.3
        prometheus-client      0.9.0
        prompt-toolkit         3.0.10
        ptyprocess             0.7.0
        pyasn1                 0.4.2
        pyasn1-modules         0.2.1
        pycparser              2.20
        Pygments               2.7.3
        PyGObject              3.36.0
        PyHamcrest             1.9.0
        pyjsparser             2.7.1
        PyJWT                  1.7.1
        pymacaroons            0.13.0
        PyNaCl                 1.3.0
        pyOpenSSL              19.0.0
        pyparsing              2.4.7
        pyRFC3339              1.1
        pyrsistent             0.15.5
        pyserial               3.4
        python-apt             2.0.0+ubuntu0.20.4.3
        python-dateutil        2.8.1
        python-debian          0.1.36ubuntu1
        python-editor          1.0.4
        python-json-logger     2.0.1
        pytz                   2020.5
        PyYAML                 5.3.1
        pyzmq                  20.0.0
        requests               2.22.0
        requests-file          1.5.1
        requests-toolbelt      0.9.1
        requests-unixsocket    0.2.0
        ruamel.yaml            0.16.12
        ruamel.yaml.clib       0.2.2
        SecretStorage          2.3.1
        Send2Trash             1.5.0
        service-identity       18.1.0
        setuptools             45.2.0
        simplejson             3.16.0
        six                    1.14.0
        sniffio                1.2.0
        soupsieve              2.1
        speedtest              0.0.1
        SQLAlchemy             1.3.22
        ssh-import-id          5.10
        systemd-python         234
        terminado              0.9.2
        testpath               0.4.4
        tldextract             3.1.0
        tornado                6.1
        traitlets              5.0.5
        Twisted                18.9.0
        tzlocal                2.1
        ubuntu-advantage-tools 20.3
        ufw                    0.36
        unattended-upgrades    0.1
        urllib3                1.25.8
        wadllib                1.3.3
        wcwidth                0.2.5
        webencodings           0.5.1
        wheel                  0.34.2
        zipp                   1.0.0
        zope.component         4.6.2
        zope.deferredimport    4.3.1
        zope.deprecation       4.4.0
        zope.event             4.5.0
        zope.hookable          5.0.1
        zope.interface         4.7.1
        zope.proxy             4.3.5
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Nothing shown
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Cannot upload file (>15 MB). ubuntu-20.04.1-live-server-amd64.iso
upload @ jlab_core.a6bd38f47ff66b08e9e2.js:formatted:28380
(anonymous) @ jlab_core.a6bd38f47ff66b08e9e2.js:formatted:27880
_onInputChanged @ jlab_core.a6bd38f47ff66b08e9e2.js:formatted:27880

image
</pre>
</details>

# My comment

It's hardcoded 15MB upload limit in frontend. 
I use jupyterlab as a server management tool instead of a python environment cuz browser is much more convenient than FileZilla.
I need to to upload large file usually, and my server & my browser can handle it. 
Maybe we can configure it instead?

image
=================
image

### PR DESCRIPTION
**Pull request by jasongrout**
## References

Fixes #9601

## Code changes

In JLab 3, we are using Jupyter Server, which unfortunately advertises its own version as the notebook version (1.2.1, for example). This trips up this notebook version test.

Since we do not support the notebook server for JupyterLab 3, we can eliminate the version check entirely.

I also normalized the spelling of 'canceled' in the error message to what we are using elsewhere in jlab.

## User-facing changes

Large uploads (>15MB) are supported in JLab 3.

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by blink1073** [comment]
Ah, there is one failing test that is relevant: https://github.com/jupyterlab/jupyterlab/pull/9616/checks?check_run_id=1697725231#step:9:145

**Comment by jasongrout** [comment]
> Ah, there is one failing test that is relevant: https://github.com/jupyterlab/jupyterlab/pull/9616/checks?check_run_id=1697725231#step:9:145

All green now except for the ever-failing services test.

**Comment by jasongrout** [comment]
@blink1073 - if you could re-review after the test changes above, that would be great. Thanks!

**Comment by blink1073** [comment]
Looks good now, thanks!

**Comment by krassowski** [comment]
It seems that lab installations using JupyterHub are still running on `notebook` rather than on  `jupyter_server`, a thing that causes problem to the lsp extension users as when I ported it I assumed I do not need `notebook` integration anymore (which JupyterLab itself kept). Would this affect the notebook version check and this workaround for legacy installations?

 https://github.com/jupyterhub/jupyterhub/commit/f69ef9f846b2b65d708d43101b51f4340e8b0b0b

**Comment by jasongrout** [comment]
I was under the assumption that jlab 3 only ran on Jupyter server, not on notebook. Am I wrong?

**Comment by jasongrout** [comment]
If I am wrong, then yes indeed this check would need to be added back, if we supported notebook < 5.1

**Comment by krassowski** [comment]
My very likely wrong impression is that it runs under whatever is available. I came to think that after the users reports from JupyterHub users (running JupyterLab 3.0 for whom our server extension for `jupyter_server` is not picked up, but the older one for `notebook` is), seeing the commit mentioned above and based on that JupyterLab ships with JSON for both `notebook` and `jupyter_server`: https://www.github.com/jupyterlab/jupyterlab/tree/master/setup.py

**Comment by blink1073** [comment]
JupyterHub uses the classic notebook by default, but can be configured to use Jupyter server using an environment variable.  JupyterLab can still also run on the classic notebook.

**Comment by krassowski** [comment]
So the lack of hard breakage [seems to be biting the hub users](https://github.com/krassowski/jupyterlab-lsp/issues/375#issuecomment-761036700) when they try to use an extension with a server component (of note while lab ships both `jupyter_notebook_config.d` and `jupyter_server_config.d`, extensions only ship `jupyter_server_config.d` - see [the cookiecutter](https://github.com/jupyterlab/extension-cookiecutter-ts/blob/4485c8daca8562f858b4f96bbbb4a34f52cb3f5a/%7B%7Bcookiecutter.python_name%7D%7D/setup.py#L41-L44)). This is probably going to bite `jupyterlab-git` an others too.

Would it be wise to remove `jupyter_notebook_config.d` and break early to prevent some weird configurations? The current situation will lead to bug reports accumulating on extensions repositories I think and they may not have resources to provide hub support (let alone some exotic deployments).

Or, is it intentional to support notebook and should the cookicutter and extensions and this PR be updated?

**Comment by jasongrout** [comment]
> JupyterLab can still also run on the classic notebook.

Uh-oh. I assumed otherwise. I hope this isn't the only place where I made that assumption.

We'll need to put this 5.1 check in if JupyterLab still runs on notebook 5.0. Do we support notebook 5.0, or do we at least assume notebook>=5.1?

**Comment by jasongrout** [comment]
Another fix is in #9628 that re-enables the block on notebook < 5.1.

**Pull request merged**
