### PR TITLE
Manual backport of #10720, #10790, #11108

### PR DESCRIPTION
**Pull request by 3coins**
## References
Manual backport of PRs: [#10720](https://github.com/jupyterlab/jupyterlab/pull/10720), [#10790](https://github.com/jupyterlab/jupyterlab/pull/10790), [#11108](https://github.com/jupyterlab/jupyterlab/pull/11108)

### CODE REVIEW

**Comment by 3coins** [comment]
@blink1073 
I just rebased from 3.2.x branch and pushed. How do I fix the i18n tests?

**Comment by blink1073** [comment]
The i18n and UI checks are broken on this branch, I haven't had a chance to fix i18n, and we still need to backport Galata integration.  We can ignore them here

**Review by blink1073 — APPROVED** [review]
Thank you!

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/ann-jupyterlab-3-2/11248/1

**Pull request merged**
