### PR TITLE
Add changelog for 0.34

### LINKED ISSUE #5034: Changelog for 0.34
This issue is for changelog entries for the 0.34 release. Please comment here with a changelog entry, and note whether the entry should be in the breaking changes section of the changelog. Breaking changes should give the user an idea of how to migrate code, if possible. Changelog entries may be more than one line, and may contain code samples.

The changelog is written in Markdown. Here is the format:

<pre>
* Description of change. ([#99999](https://github.com/jupyterlab/jupyterlab/issues/99999))
  ```
  Code example, if needed, indented 2 spaces
  ```
</pre>

In the release process for 0.34, we'll sweep through this issue to create the changelog for 0.34. We're adding changelog entries here rather than in individual PRs so that we don't create unnecessary conflicts between PRs editing the same file.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #5034

### CODE REVIEW

**Comment by ian-r-rose** [comment]
This looks good to me. Happy to merge or wait for @jzf2101 to sign off.

**Comment by jasongrout** [comment]
Looks good to me too. Let's merge this (given JCon starting and people traveling), and submit followup PRs if needed.

**Comment by jasongrout** [comment]
Is there a patch update that is needed? Right now, our stable docs won't show this since it isn't in a release. If we publish 0.34.1, the changelog will show up.

**Comment by jasongrout** [comment]
Of course, I just noticed some rendering issues with the changelog, so I'm submitting a followup pr.

**Comment by jzf2101** [comment]
Yes! I'm happy with it sorry about the delay

**Pull request merged**
