### PR TITLE
Update dependencies for beta

### PR DESCRIPTION
**Pull request by blink1073**
## References
Updates dependencies ahead of our beta release

## Code changes
- Bump all `lumino` dependencies
- Bump `react` dependencies to 16.13
- Bump `jupyterlab_server` dependency

## User-facing changes
None

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by blink1073** [comment]
Taking a break, stuck on a typings issue with `jest`, very frustrating.

```typescript
src/flakyIt.ts:33:3 - error TS2593: Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha` and then add `jest` or `mocha` to the types field in your tsconfig.

33   test(name, async () => {
     ~~~~
```

**Comment by blink1073** [comment]
Stopping for the day, I'm out of steam.

**Comment by jasongrout** [comment]
I updated a lot more dependencies, via `npx yarn@1.19.1 upgrade-interactive` (see https://github.com/yarnpkg/yarn/issues/7807).

**Comment by jasongrout** [comment]
Handing it back to you, @blink1073 - the last commit, ea33b, casts a few things to `any` to ignore real errors so we can compile, so it should probably be reverted and fixed correctly.

**Comment by blink1073** [comment]
I carried the baton a bit more, but I'm off for the weekend

**Comment by jasongrout** [comment]
> I carried the baton a bit more, but I'm off for the weekend

Is this the last blocker for a beta?

**Comment by blink1073** [comment]
I believe so yes

**Comment by jasongrout** [comment]
Opened up https://github.com/jupyterlab/jupyterlab/issues/8929 for fixing the FIXMEs from ea33b6d

**Comment by jasongrout** [comment]
Laying the baton back down for now. I'll put a note here when I start working on it again, but in the meantime, feel free to pick it up if you want.

**Comment by blink1073** [comment]
I had to still skip the Windows build tests, I opened https://github.com/jupyterlab/jupyterlab/issues/8936.
I had to downgrade `css-loader` to 3.x, because the page was hitting an infinite loop while loading the Blueprint styles.

**Comment by blink1073** [comment]
There were some [breaking changes](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#-breaking-changes) in `css-loader` from 3->4 that we'd need to address before upgrading, I say we defer.

**Comment by blink1073** [comment]
Publishing the beta now

**Pull request merged**
