### PR TITLE
Add percent decoding to `username` & `initials`

### PR DESCRIPTION
**Pull request by HoseonRyu**
## References
See this issue - [#11820](https://github.com/jupyterlab/jupyterlab/issues/11820).

## Code changes
- Added the function `decodeURIComponent` at the definition of `name`.
- Applied samely to `initials`.
- Edited comments.

### CODE REVIEW

**Review by fcollonval — APPROVED** [review]
LGTM @HoseonRyu thanks for the fix

**Comment by hbcarlos** [comment]
Looks great! Thank you @HoseonRyu!

@fcollonval Can we backport this to 3.1, 3.2, and 3.3?

**Comment by krassowski** [comment]
1. @hbcarlos Is there a way to add a test case for this one?
2. Do we really need `lib0/environment` dependency here, or could we use standard way of parsing URL? (Which could possibly simplify the test case as we would not need to mock `lib0/environment`).

**Comment by hbcarlos** [comment]
> Is there a way to add a test case for this one?

Not sure yet how, but yes we should add a test for this one.
I will take care of all the tests once we have the final API for documents. I added a reference to your comment on the RTC issue.

> Do we really need `lib0/environment` dependency here, or could we use standard way of parsing URL?

Yes, we can use a standard way to parse the URL. Can we keep it as it is for now and I'll change I for 4.0?

**Comment by fcollonval** [comment]
> Can we backport this to 3.1, 3.2, and 3.3?

The policy is to backport only on the current stable branch (to not increase extensively the maintenance bandwidth). The only exception is a security fix.

**Comment by HoseonRyu** [comment]
@fcollonval Then... do I have to open another PR to apply this to `3.2`? That was my first goal.

**Comment by fcollonval** [comment]
> @fcollonval Then... do I have to open another PR to apply this to `3.2`? That was my first goal.

I got my answer on the chat. We will backport this to 3.2.x and 3.3.x. And you don't need to do it manually I'll trigger a bot (that usually succeeds at picking up the changes).

Thanks again for the fix.

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.3.x

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.2.x

**Pull request merged**
