### PR TITLE
images and videos for files docs

### LINKED ISSUE #3777: Gonna take a shot at "files.html" animations
@ian-r-rose @Carreau I still don't think I have youtube access. I'm going to upload them to my own account and then we can swap the links whenever we get that figured out.

http://jupyterlab-tutorial.readthedocs.io/en/latest/user/files.html is the page I'm working on. Just giving a note here so that we don't duplicate efforts

### PR DESCRIPTION
**Pull request by choldgraf**
This adds videos + screenshots to the `files` documentation. Here's a live example:

http://predictablynoisy.com/jupyterlab-1/user/files.html

Notes:

* We can upload these to the Jupyter account whenever we get access figured out, but from the user's perspective nothing would change since we're *only* showing the embedded video and nothing else.
* Once this gets merged I'll make a PR with the videos to the `jupyter-media` repo.

cc @ian-r-rose 

closes #3777

### CODE REVIEW

**Comment by ian-r-rose** [comment]
For the most part, we have been trying to take screenshots using the `jupyterlab-demo` repo as the root of the file system. I don't know whether that is the "official" recommendation, though.

**Comment by choldgraf** [comment]
....that information should really be documented in the devdocs somewhere :-P


do you want me to re-create all of these images/videos with the `jupyterlab-demo` repo in there?

**Comment by blink1073** [comment]
FWIW I like these as-is and don't think they need to be redone.  Thanks @choldgraf!

**Comment by ian-r-rose** [comment]
Agreed, it should be documented (if indeed we want to do that). I don't have strong opinions on it, no need to recreate from my perspective.

**Comment by ian-r-rose** [comment]
@choldgraf Looks to me like you have YouTube access now

**Comment by choldgraf** [comment]
I do, yep! I'll re-upload the videos to the jupyter account and update the links...that didn't take too long. In the future I'll use the demo repository, and at some point we can change the videos that are on this page, but IMO that isn't as high-priority as getting the other videos/screenshots filled in so we can 🚢 this thing!

**Comment by ian-r-rose** [comment]
Agreed

**Comment by choldgraf** [comment]
ok, just updated the PR with new youtube links that map to the jupyter account

**Comment by ian-r-rose** [comment]
Thanks!

**Pull request merged**
