### PR TITLE
Allow safe inline CSS styles in Markdown

### LINKED ISSUE #1812: JupyterLab removing HTML style attribs
In Jupyter Notebook I can make a markdown cell with 

```html
<img src="resources/a.png" height="200px" width=" 200px" style="display: inline-block;"/> VS <img src="resources/b.png" height="200px" width=" 200px" style="display: inline-block;"/>
```
and it rendered nicely as:
```
Pic1 VS Pic2
```
In JupyterLab this does not work anymore and it shows instead:

```
    Pic1
     VS
    Pic2
```

### PR DESCRIPTION
**Pull request by biermeester**
Fixes #1812 and #5183

This pull request makes it possible to add `style` attributes to HTML tags embedded in Markdown cells.

The CSS properties and their values inside the `style` attribute will be sanitized: if they are not allowed, or malformed, they will get stripped silently.

This update also allows for the embedding of encoded image data inside the `src` attribute of image tags.

Most CSS properties and their values are supported. The missing (safe) ones will be added in the near future.

There's bound to be some errors in the (great number of) regular expressions used to sanitize the CSS values. Don't hesitate to open an issue and mention me if some CSS you think is valid is not working as expected.

### CODE REVIEW

**Comment by blink1073** [comment]
This looks great, thanks!  Can we also add `line-height`, `text-align`, and `color`?  For reference, here are the allowed attributes in [caja](https://github.com/google/caja/blob/1056be89dad487f9178d89f462fe5cb207c7e604/src/com/google/caja/lang/css/css3-defs.json).

**Comment by blink1073** [comment]
Also `rowspan` and `colspan` as previously [requested](https://github.com/jupyterlab/jupyterlab/issues/1812#issuecomment-375940637).

**Comment by biermeester** [comment]
Thanks, I'll see if I can rework the caja configuration.

**Comment by biermeester** [comment]
I've been looking at caja's allowed css properties, but to convert all those to regular expressions for sanitize is quite a bit of work. Are there any css properties that we definitely don't want people to use?

**Comment by blink1073** [comment]
@biermeester, I would suggest either writing a script to scrape the caja fields or stick with what we have and whitelist more as they are requested and are individually evaluated.

**Comment by blink1073** [comment]
Looks like the rebase caught a bunch of other commits.

**Comment by biermeester** [comment]
Oops, will do a little cleanup today.

**Comment by blink1073** [comment]
Bravo, @biermeester, thank you!  Can you share the script(s) you used for extraction as a gist perhaps for posterity in case we need to do this again for HTML 6.0  :wink:?

**Comment by biermeester** [comment]
Extracting the tags and attributes was pretty trivial. I'm still working on converting the CSS property value syntax into Regular Expressions, which is a lot less trivial :)

I'll make sure to share the code snippets that I used to help extract/transform the data when I'm done.

**Comment by blink1073** [comment]
Great, thank you!

**Comment by ellisonbg** [comment]
I haven't followed the PR closely - the only thing I want us to make sure of is that we are not allowing any tags or attribute/styles that have security vulnerabilities. @biermeester can you comment on that aspect of this PR?

**Comment by biermeester** [comment]
I've  been working off of [Google Caja](https://github.com/google/caja/tree/1056be89dad487f9178d89f462fe5cb207c7e604/src/com/google/caja/lang/css) to make sure css properties (or property values) that are deemed unsafe/disruptive will get filtered out by sanitize-html. 

There's only a few of such properties/values, and since sanitize-html requires me to white-list everything that is allowed, I've been working on quite some regular expressions to do so. 

I'm not even sure if the end result will be workable, performance wise. Some testing will need to be done.

**Comment by biermeester** [comment]
I've added CSS value validation for most of the allowed CSS properties. I've removed some properties for now (e.g. animation properties) and simplified others, but I will probably add/extend those in the near future.

I was a bit worried about how the performance would be, but until now I don't see any ill effects. 

I used the following script to extract information from Caja's Json definitions: https://gist.github.com/biermeester/9437f13d3735e65ba013c947ea59021f

A demo notebook can be found here: https://gist.github.com/biermeester/83802c33fb8483d25bcff6b59ce1353d

Next up is going to a be a test case extension, that will make sure that harmful CSS gets filtered out.

**Comment by blink1073** [comment]
I think a test in test-rendermime that reads from your example notebook and verifies stripped properties would work nicely.

**Comment by blink1073** [comment]
Or at the sanitizer test level, whichever is easier.

**Comment by blink1073** [comment]
This looks like a legitimate failure:

```
lerna ERR! ERROR in bundle.js from UglifyJs
lerna ERR! Legacy octal escape sequences are not allowed in strict mode [/home/travis/build/jupyterlab/jupyterlab/packages/apputils/lib/sanitizer.js:41,0][bundle.js:105459,22]
```

**Comment by biermeester** [comment]
Weird, local tests seemed to run fine. Thanks for the heads-up, I'll have a look.

**Comment by blink1073** [comment]
It shows up when you run "build:prod".

**Comment by blink1073** [comment]
Thanks again, @biermeester!  I'll come back to reviewing this after the 0.34 release process.

**Comment by blink1073** [comment]
@biermeester, this is great!  Do you mind updating the top level comment for posterity?

**Comment by biermeester** [comment]
Done. Is there also some piece of the documentation you would like me to update?

**Comment by blink1073** [comment]
Nope, this is perfect, thank you!

**Pull request merged**
