### PR TITLE
Implement log console levels

### LINKED ISSUE #7386: Log console default to logging all notebook output?
Below is a simple plugin that will log all notebook output to a log console. I think it's too noisy to turn on by default, and the log console should default to just displaying explicit messages that you *won't* see in a notebook (like the ipywidgets unhandled messages). However, @blink1073 [thinks](https://gitter.im/jupyterlab/jupyterlab?at=5da7c712894dee56e557bb05) that the log console appears to be broken without something like this.

So should we (a) turn something like this on by default, or (b) provide it as an option, but not turned on by default?

```typescript
import {
  JupyterFrontEnd,
  JupyterFrontEndPlugin
} from '@jupyterlab/application';
import { ILoggerRegistry } from '@jupyterlab/logconsole';
import { INotebookTracker, NotebookPanel } from '@jupyterlab/notebook';
import { KernelMessage } from '@jupyterlab/services';
import { nbformat } from '@jupyterlab/coreutils';

/**
 * The Log Console extension.
 */
export const logNotebookOutput: JupyterFrontEndPlugin<void> = {
  activate: activateNBOutput,
  id: 'logconsole:nboutput',
  requires: [ILoggerRegistry, INotebookTracker],
  autoStart: true
};

function activateNBOutput(
  app: JupyterFrontEnd,
  loggerRegistry: ILoggerRegistry,
  nbtracker: INotebookTracker
) {
  function registerNB(nb: NotebookPanel) {
    nb.context.session.iopubMessage.connect(
      (_, msg: KernelMessage.IIOPubMessage) => {
        if (
          KernelMessage.isDisplayDataMsg(msg) ||
          KernelMessage.isStreamMsg(msg) ||
          KernelMessage.isErrorMsg(msg) ||
          KernelMessage.isExecuteResultMsg(msg)
        ) {
          const logger = loggerRegistry.getLogger(nb.context.path);
          logger.rendermime = nb.content.rendermime;
          const data: nbformat.IOutput = {
            ...msg.content,
            output_type: msg.header.msg_type
          };
          logger.log({ type: 'output', data });
        }
      }
    );
  }
  nbtracker.forEach(nb => registerNB(nb));
  nbtracker.widgetAdded.connect((_, nb) => registerNB(nb));
}
```

### PR DESCRIPTION
**Pull request by jasongrout**
## References

Fixes #7386

## Code changes

Adds the notion of a log message severity level and ways to set the log to filter on these levels.

TODO:
- [x] Remove the cycling of log levels for the notebook output logging, i.e., revert 
f11300a 

## User-facing changes

Added a log level toolbar select to set the current log filtering mode, as well as coloring and tooltips for the timestamps to indicate log severity using the theme colors. Here are some screenshots showing how different severity levels are handled:

Screen Shot 2019-10-24 at 11 21 18 AM
Screen Shot 2019-10-24 at 11 22 54 AM
Screen Shot 2019-10-24 at 11 23 11 AM
Screen Shot 2019-10-24 at 11 23 24 AM
Screen Shot 2019-10-24 at 11 23 34 AM
Screen Shot 2019-10-24 at 11 23 50 AM

Here is what happens by default:

* For messages that are handled by the notebook, we display at `info` severity. The idea is that the user will see these elsewhere, and they are by far the most common things, so let's not overwhelm the user with information they already know.
* For messages that are not handled by the notebook (probably few and far between), log normal messages to `warning` (as in "Warning: you haven't seen this output, but you might want to") and log error messages to `error` (as in "Error: here is an error you have not seen")

(for ipywidgets, we'll do the same as the latter: normal messages get logged at warning level, error messages get logged at error level, since people won't see those messages by default either).

I think that is the best balance between giving the information to the user, and making it useful and actionable by not overwhelming them with things they already can see.

## Backwards-incompatible changes

None for any released packages.

This does change the logging api for the unreleased log console package to include a level for each message.

### CODE REVIEW

**Comment by jasongrout** [comment]
This is still a work in progress, but shows the rudimentary functionality already.

**Comment by blink1073** [comment]
I did a quick pass of the current state, I like the direction.

**Comment by blink1073** [comment]
I think it should say "Level:" or some other label.  Even though I knew what to expect I had to think about what the dropdown meant.

image

**Comment by jasongrout** [comment]
> I think it should say "Level:" or some other label. Even though I knew what to expect I had to think about what the dropdown meant.

+1. I was following the pattern for the cell type dropdown initially. I'll look at adding a label to the left.

**Comment by blink1073** [comment]
It also isn't updating when I change it - it stays showing as "Warning".  Do we want to add an indicator of the log level between the timestamp and the message (like "[D]")?

**Comment by jasongrout** [comment]
> Do we want to add an indicator of the log level between the timestamp and the message (like "[D]")?

Oh, good idea. I already am setting the color and title of the timestamp based on the log level. Check out the commit I just pushed, which for testing purposes cycles the notebook outputs between log levels, to see what it looks like currently.

**Comment by blink1073** [comment]
Pulling

**Comment by jasongrout** [comment]
I like the idea of inserting an information message in the log when the level changes, so you can easily see when the log switched filtering levels.

**Comment by jasongrout** [comment]
Probably like the timestamp, it would be a critical message so it displays always.

**Comment by jasongrout** [comment]
Or perhaps we should have a highest-priority message type that is "Log metadata messages" or something, for timestamps and these level change messages.

**Comment by blink1073** [comment]
I would think that would replace the "Add Timestamps" and be a radio button.

**Comment by blink1073** [comment]
Er, check box.

**Comment by blink1073** [comment]
I'm not sure about setting colors, that can get dicey with theming and accessibility

**Comment by jasongrout** [comment]
> I'm not sure about setting colors, that can get dicey with theming and accessibility

I'm using the theme info/warning/error colors :)

**Comment by jasongrout** [comment]
> I would think that would replace the "Add Timestamps" and be a radio button.

I'm not sure what you mean here.

**Comment by blink1073** [comment]
I mean replace "+ Add Timestamps" with "[ ] Show log metadata" (with a checkbox)

**Comment by jasongrout** [comment]
Ah, I think you don't understand what that button does. It inserts a checkpoint in the log, not sets a setting for the viewer.

**Comment by jasongrout** [comment]
I changed the name to "Add checkpoint" and added a new (private) log severity level for log metadata messages like a checkpoint or a level switch.

**Comment by jasongrout** [comment]
I also added some screenshots in the initial description.

**Comment by jasongrout** [comment]
Add @tgeorgeux for UX review.

**Comment by jasongrout** [comment]
I also added about 60 tests for the logconsole package.

**Comment by jasongrout** [comment]
ping @blink1073 for review - once this is approved, we can merge, backport, and cut the 1.2 RC.

**Comment by blink1073** [comment]
- It is printing stdout on the warning level.  
- Should tracebacks be shown at the error  level?  Right now nothing is shown. 
- I expected stderr to be shown on the error level, but I can also see how they'd be emitted at the warning level
- Not all of the messages are shown.  They seem to fail randomly to display.  I will print the same thing several times and about one in three do not get shown.  This is with stdout and stderr.

**Comment by jasongrout** [comment]
> * It is printing stdout on the warning level.
> 
> * Should tracebacks be shown at the error  level?  Right now nothing is shown.
> 
> * I expected stderr to be shown on the error level, but I can also see how they'd be emitted at the warning level
> 
> * Not all of the messages are shown.  They seem to fail randomly to display.  I will print the same thing several times and about one in three do not get shown.  This is with stdout and stderr.

Sounds like all of this has to do with the severity level rotation I introduced so you could easily check all severity levels (see https://github.com/jupyterlab/jupyterlab/pull/7406#issuecomment-545726100, https://github.com/jupyterlab/jupyterlab/pull/7406#issuecomment-546041647, and the TODO still at the top). I'll go ahead and revert that cycling now so you can test that too.

**Comment by jasongrout** [comment]
@blink1073 - I've now reverted the automatic severity cycling I had in for debugging. Now what I implemented at https://github.com/jupyterlab/jupyterlab/pull/7406/files#diff-e8882401a823c162a5b87e72e58d3298R64-R73 takes effect:

* For messages that are handled by the notebook - only display at `info` levels. The idea is that the user will see these elsewhere, and they are by far the most common things, so let's not overhwelm the user with information they already know.
* For messages that are *not* handled by the notebook (probably few and far between), log normal messages to warning (as in "Warning: you haven't seen this output, but you might want to" and log error messages to error (as in "Error: here is an error you have not seen")

For ipywidgets, we'll do the same as the latter: normal messages get logged at warning level, error messages get logged at error level.

I think that is the best balance between giving the information to the user, and making it useful and actionable by not overwhelming them with things they already can see.

**Comment by jasongrout** [comment]
I don't know how to restart failed checks (I tried using the GitHub UX, but it didn't seem to do anything), so I pushed some whitespace changes to start a new CI run.

**Comment by mbektasbbg** [comment]
@jasongrout I built and tested, this is looking great. I have some design related comments:
- I was expecting levels to be just a filter, but they are acting as a lower limit. So, if level is set to `Error` and there are `Info` logs received, there is no way to see those info logs. I was expecting changing log level would just be filtering to that level. Also, I was hoping to combine logs from different levels (selecting both `Warning` and `Error`)
- Do we need `Critical` and `Debug` levels? What would be the difference between Error and Critical? How would `Debug` be used in released product?
- Google Chrome and Visual Studio have 3 levels and they can be combined
vs
chrome

- I noticed an issue with drop-down, when you hover on the label it highlights the dropdown but clicking label doesn't open the drop-down. Not specific to these changes I think, but still worth mentioning.
LogLevels

**Comment by jasongrout** [comment]
> I was expecting levels to be just a filter, but they are acting as a lower limit. So, if level is set to `Error` and there are `Info` logs received, there is no way to see those info logs. I was expecting changing log level would just be filtering to that level. Also, I was hoping to combine logs from different levels (selecting both `Warning` and `Error`)

All log messages are shown interleaved, sorted by timestamp. The dropdown controls the *log* filtering level, not the *view* filtering level. I think this is a fairly standard approach for logs (c.f. Python, Java logging, etc.), since storing all informational or debug messages can quickly overwhelm the system. (Filtering a view is also apparently a common approach, as you've pointed out.)

>  * Do we need `Critical` and `Debug` levels? What would be the difference between Error and Critical? How would `Debug` be used in released product?

I adopted the levels from the Python logging system. I also looked at the Java logging system, which essentially has similar levels. I'm not very opinionated about these.

VS code looks like it has 4 levels? errors, warnings, info, and verbose?

> * I noticed an issue with drop-down, when you hover on the label it highlights the dropdown but clicking label doesn't open the drop-down. Not specific to these changes I think, but still worth mentioning.

Interesting. Likely this is standard browser behavior because the label is explicitly tied to the dropdown for accessibility.

**Comment by jasongrout** [comment]
>     * Also, I was hoping to combine logs from different levels (selecting both `Warning` and `Error`)

The level you choose in the dropdown is the least important level to log. So you'll see that level and more important levels. (so selecting 'warning' shows critical, error, and warning messages).

**Comment by mbektasbbg** [comment]
> VS code looks like it has 4 levels? errors, warnings, info, and verbose?

If you are referring to capture I attached, that was from Google Chrome actually. Yes you are right, I was thinking Verbose was to enable the other three but indeed it is a separate one. Looks like there are so many flavors of log levels :)

> Likely this is standard browser behavior because the label is explicitly tied to the dropdown for accessibility.

It turns out label hover changing state of dropdown is standard behavior. However, clicking the label is supposed to set focus to dropdown, interestingly it is not happening here.

**Comment by blink1073** [comment]
I'm good with the overall behavior now, but agree with @mbektasbbg about the label click behavior.

**Comment by jasongrout** [comment]
> clicking the label is supposed to set focus to dropdown, interestingly it is not happening here.

Turns out that the generic toolbar code was too aggressive about focusing the parent widget. This is fixed in the latest commit.

**Comment by blink1073** [comment]
@meeseeksdev backport to 1.x

**Comment by wabiloo** [comment]
Hi. Quick question...
I'm running JupyterLab 1.2.3.
How do I add my own debug logs for viewing in the log console, from my python code?

I tried 
```
import logging
logging.debug("test")
```
and made sure that the dropdown in the log view is set to "Debug".

Other than .warning and .critical, no other method seems to be reflected in the logs

**Comment by jasongrout** [comment]
Great question. This log is for front end things, so JLab extensions can log messages. One way to make it available to the kernel is to write a python package that sends log messages to JLab (perhaps as comm messages?) and also a JLab extension that takes those messages and puts them in the JLab log.

**Comment by jasongrout** [comment]
Or perhaps this would be a great mimerender project. Define a mimetype for the rich display that renders the content to the JLab log.

**Comment by jasongrout** [comment]
(short answer is that you can't do it right now. The above two comments give two ways you or someone else could extend JLab to make it possible.)

**Comment by agoose77** [comment]
@wabiloo I've written an extension to do this [here](https://github.com/agoose77/jupyterlab-log-renderer). Let me know what you find!

**Comment by jasongrout** [comment]
Nice! Thanks for sharing!

**Pull request merged**
