### PR TITLE
Custom script to upgrade `staging/yarn.lock`

### LINKED ISSUE #14924: Wrong yarn.lock in released 4.0.4
## Description

Since the release of 4.0.4, integration tests are failing; see for examples: 
- https://github.com/jupyterlab/extension-template/actions/runs/5777728638/job/15658220778?pr=39
- https://github.com/jupyterlab-contrib/jupyter-archive/actions/runs/5777706952/job/15658204740?pr=118

The reason is that the galata xpath selector to check for the _Launcher_ tab is not valid any longer as a consequence of https://github.com/jupyterlab/lumino/pull/606 (the selector was using `jp-Activity` class that is now gone).

---

The underlying painful bug is that the yarn.lock got modify to pull the latest version of @lumino instead of keeping the one in the dev yarn.lock. This is the reason the CI is green and we did not capture that bug :cry:

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #14924

## Code changes

- Custom upgrade yarn.lock file to only allow version change for _@jupyterlab/*_ packages
- Remove broken `buildutils/src/dependency_graph.ts`

This will ensure that the release version is using the same lock version as the dev mode (except for jupyterlab packages that are bumped as part of the release process).

## User-facing changes

None

## Backwards-incompatible changes

None (the next 4.0.x release will have downgraded packages - in particular for lumino).

### CODE REVIEW

**Comment by jtpio** [comment]
> the next 4.0.x release will have downgraded packages

Should this PR revert the changes to `staging/yarn.lock`? Probably not as this should be done as part of the release process in the next patch release with this fix.

**Comment by fcollonval** [comment]
As the main branch is not targeting 4.0.x, I guess it does not matter much. What about I'll applied it locally on 4.0.x and copy the diff as comment on this PR before moving forward as I think it will be good for multiple people to look at the consequence of it.

**Comment by fcollonval** [comment]
<details><summary>Here is the patch that will be applied on 4.0.x as a consequence of this</summary>
    
    diff --git a/jupyterlab/staging/yarn.lock b/jupyterlab/staging/yarn.lock
    index 8487f4aa95..6460089644 100644
    --- a/jupyterlab/staging/yarn.lock
    +++ b/jupyterlab/staging/yarn.lock
    @@ -2404,13 +2404,13 @@ __metadata:
       linkType: hard
         
     "@lumino/application@npm:^2.0.1":
    -  version: 2.2.1
    -  resolution: "@lumino/application@npm:2.2.1"
    +  version: 2.1.1
    +  resolution: "@lumino/application@npm:2.1.1"
       dependencies:
    -    "@lumino/commands": ^2.1.3
    -    "@lumino/coreutils": ^2.1.2
    -    "@lumino/widgets": ^2.3.0
    -  checksum: a33e661703728440bc7d2ddb4674261f4de0d20eb8c9846646cbd6debac03b5c65e78d739a500903550fd83b8f47b47fa82ec178c97bc9967ca3ac4014075cde
    +    "@lumino/commands": ^2.1.1
    +    "@lumino/coreutils": ^2.1.1
    +    "@lumino/widgets": ^2.1.1
    +  checksum: 442a047e43a85b48189d15a5a322f39cac01b9bee7b252aa76579c53e503f2cf2100f2e3aff61cd1d92fef07f04c0a3a6680c475890e0923456e296ceb79a692
       languageName: node
       linkType: hard
     
    @@ -2424,50 +2424,50 @@ __metadata:
       linkType: hard
     
     "@lumino/commands@npm:^2.0.1":
    -  version: 2.1.3
    -  resolution: "@lumino/commands@npm:2.1.3"
    +  version: 2.1.1
    +  resolution: "@lumino/commands@npm:2.1.1"
       dependencies:
    -    "@lumino/algorithm": ^2.0.1
    -    "@lumino/coreutils": ^2.1.2
    -    "@lumino/disposable": ^2.1.2
    -    "@lumino/domutils": ^2.0.1
    -    "@lumino/keyboard": ^2.0.1
    -    "@lumino/signaling": ^2.1.2
    -    "@lumino/virtualdom": ^2.0.1
    -  checksum: e4e3ee279f2a5e8d68e4ce142c880333f5542f90c684972402356936ecb5cf5e07163800b59e7cb8c911cbdb4e5089edcc5dd2990bc8db10c87517268de1fc5d
    +    "@lumino/algorithm": ^2.0.0
    +    "@lumino/coreutils": ^2.1.1
    +    "@lumino/disposable": ^2.1.1
    +    "@lumino/domutils": ^2.0.0
    +    "@lumino/keyboard": ^2.0.0
    +    "@lumino/signaling": ^2.1.1
    +    "@lumino/virtualdom": ^2.0.0
    +  checksum: a076244e9c4f7a3c6dab02642fdd38dbbaab6e5754acaeeb84a5195dc5c2fc19343ba754c3a0f89c9b60f16c61cb793301cdb6e8d69bdc30e18ed7e32f40d524
       languageName: node
       linkType: hard
     
     "@lumino/coreutils@npm:^2.0.0":
    -  version: 2.1.2
    -  resolution: "@lumino/coreutils@npm:2.1.2"
    -  checksum: 7865317ac0676b448d108eb57ab5d8b2a17c101995c0f7a7106662d9fe6c859570104525f83ee3cda12ae2e326803372206d6f4c1f415a5b59e4158a7b81066f
    +  version: 2.1.1
    +  resolution: "@lumino/coreutils@npm:2.1.1"
    +  checksum: dfdeb2b0282caae17b6c3edfebadf4ce7c75fc879fa60cacfef9b154412f4b35e4ffd95b1833b99d8dacb99aaaa04513570129ae2024c3f33e2677a01f0576ce
       languageName: node
       linkType: hard
     
     "@lumino/datagrid@npm:^2.0.1":
    -  version: 2.2.0
    -  resolution: "@lumino/datagrid@npm:2.2.0"
    +  version: 2.1.1
    +  resolution: "@lumino/datagrid@npm:2.1.1"
       dependencies:
    -    "@lumino/algorithm": ^2.0.1
    -    "@lumino/coreutils": ^2.1.2
    -    "@lumino/disposable": ^2.1.2
    -    "@lumino/domutils": ^2.0.1
    -    "@lumino/dragdrop": ^2.1.3
    -    "@lumino/keyboard": ^2.0.1
    -    "@lumino/messaging": ^2.0.1
    -    "@lumino/signaling": ^2.1.2
    -    "@lumino/widgets": ^2.3.0
    -  checksum: dcd6e06500c05b0f30b9924a25a2cc4c1cb98b8432f488148e74e98a7fe092a1f19cadbdc9edfbede9e2030d30b84e5633e40753fbe8d6bbb120d3336d3675ff
    +    "@lumino/algorithm": ^2.0.0
    +    "@lumino/coreutils": ^2.1.1
    +    "@lumino/disposable": ^2.1.1
    +    "@lumino/domutils": ^2.0.0
    +    "@lumino/dragdrop": ^2.1.1
    +    "@lumino/keyboard": ^2.0.0
    +    "@lumino/messaging": ^2.0.0
    +    "@lumino/signaling": ^2.1.1
    +    "@lumino/widgets": ^2.1.1
    +  checksum: 01ed80f36b31449d16302197549ae091d8ea07d124e5dbfda271c35462bce7f6f56d54978b6b3174d9332b9ee4219568ab3f7308b26ff1df88e9fce748bd5448
       languageName: node
       linkType: hard
     
     "@lumino/disposable@npm:^2.0.0":
    -  version: 2.1.2
    -  resolution: "@lumino/disposable@npm:2.1.2"
    +  version: 2.1.1
    +  resolution: "@lumino/disposable@npm:2.1.1"
       dependencies:
    -    "@lumino/signaling": ^2.1.2
    -  checksum: ac2fb2bf18d0b2939fda454f3db248a0ff6e8a77b401e586d1caa9293b3318f808b93a117c9c3ac27cd17aab545aea83b49108d099b9b2f5503ae2a012fbc6e2
    +    "@lumino/signaling": ^2.1.1
    +  checksum: ed6cdfe13f3346178a087690d4e7baeccaed7e73ca23cb239765202409f5c01b4729a4058b4717f963462ee9ef2e5cb14ad1974e3163741267290edc3715c85c
       languageName: node
       linkType: hard
     
    @@ -2479,12 +2479,12 @@ __metadata:
       linkType: hard
     
     "@lumino/dragdrop@npm:^2.0.0":
    -  version: 2.1.3
    -  resolution: "@lumino/dragdrop@npm:2.1.3"
    +  version: 2.1.1
    +  resolution: "@lumino/dragdrop@npm:2.1.1"
       dependencies:
    -    "@lumino/coreutils": ^2.1.2
    -    "@lumino/disposable": ^2.1.2
    -  checksum: d5f7eb4cc9f9a084cb9af10f02d6741b25d683350878ecbc324e24ba9d4b5246451a410e2ca5fff227aab1c191d1e73a2faf431f93e13111d67a4e426e126258
    +    "@lumino/coreutils": ^2.1.1
    +    "@lumino/disposable": ^2.1.1
    +  checksum: 68c896afc44476b11a501e5b30ec55db06c2648a45f078713a111b2bf3b2e9171a7c5478ff6bdeb771a7c1e397fe3bba7bc5eadb4fe3e1294851d677f811b5b8
       languageName: node
       linkType: hard
     
    @@ -2506,13 +2506,13 @@ __metadata:
       linkType: hard
     
     "@lumino/polling@npm:^2.0.0":
    -  version: 2.1.2
    -  resolution: "@lumino/polling@npm:2.1.2"
    +  version: 2.1.1
    +  resolution: "@lumino/polling@npm:2.1.1"
       dependencies:
    -    "@lumino/coreutils": ^2.1.2
    -    "@lumino/disposable": ^2.1.2
    -    "@lumino/signaling": ^2.1.2
    -  checksum: fa9b401e6dbeb8f31d7e3ba485e8ef1e0c92b3f2da086239c0ed49931026f5d3528709193c93e031e35ac624fb4bbbfcdcbaa0e25eb797f36e2952e5cd91e9e3
    +    "@lumino/coreutils": ^2.1.1
    +    "@lumino/disposable": ^2.1.1
    +    "@lumino/signaling": ^2.1.1
    +  checksum: 69177b26d5fc541e72533cbe7d7f7999eea541d392f1082d20dbd9e1797e7d46fba47bae9c65c06f9ccb2780cbae636e9354d9bf4423b5e1020754d4b07d4f6b
       languageName: node
       linkType: hard
     
    @@ -2524,12 +2524,12 @@ __metadata:
       linkType: hard
     
     "@lumino/signaling@npm:^2.0.0":
    -  version: 2.1.2
    -  resolution: "@lumino/signaling@npm:2.1.2"
    +  version: 2.1.1
    +  resolution: "@lumino/signaling@npm:2.1.1"
       dependencies:
    -    "@lumino/algorithm": ^2.0.1
    -    "@lumino/coreutils": ^2.1.2
    -  checksum: ad7d7153db57980da899c43e412e6130316ef30b231a70250e7af49058db16cadb018c1417a2ea8083d83c48623cfe6b705fa82bf10216b1a8949aed9f4aca4e
    +    "@lumino/algorithm": ^2.0.0
    +    "@lumino/coreutils": ^2.1.1
    +  checksum: 283ad4239b8577f68aca3d0b2606f73cc1c775f84cab25cf49aa6cd195f0d87949ef43fdff03b38b5a49ebbf2468581c6786d5f8b6159a04b2051260be5eab86
       languageName: node
       linkType: hard
     
    @@ -2543,21 +2543,21 @@ __metadata:
       linkType: hard
     
     "@lumino/widgets@npm:^2.0.1":
    -  version: 2.3.0
    -  resolution: "@lumino/widgets@npm:2.3.0"
    +  version: 2.1.1
    +  resolution: "@lumino/widgets@npm:2.1.1"
       dependencies:
    -    "@lumino/algorithm": ^2.0.1
    -    "@lumino/commands": ^2.1.3
    -    "@lumino/coreutils": ^2.1.2
    -    "@lumino/disposable": ^2.1.2
    -    "@lumino/domutils": ^2.0.1
    -    "@lumino/dragdrop": ^2.1.3
    -    "@lumino/keyboard": ^2.0.1
    -    "@lumino/messaging": ^2.0.1
    -    "@lumino/properties": ^2.0.1
    -    "@lumino/signaling": ^2.1.2
    -    "@lumino/virtualdom": ^2.0.1
    -  checksum: a8559bd3574b7fc16e7679e05994c515b0d3e78dada35786d161f67c639941d134e92ce31d95c2e4ac06709cdf83b0e7fb4b6414a3f7779579222a2fb525d025
    +    "@lumino/algorithm": ^2.0.0
    +    "@lumino/commands": ^2.1.1
    +    "@lumino/coreutils": ^2.1.1
    +    "@lumino/disposable": ^2.1.1
    +    "@lumino/domutils": ^2.0.0
    +    "@lumino/dragdrop": ^2.1.1
    +    "@lumino/keyboard": ^2.0.0
    +    "@lumino/messaging": ^2.0.0
    +    "@lumino/properties": ^2.0.0
    +    "@lumino/signaling": ^2.1.1
    +    "@lumino/virtualdom": ^2.0.0
    +  checksum: e2ad4a97d6ec43e5e1863c2a521b6b8cb7a708a470c1e78b0f34ff4ad8b9fca191597586c3033233a29ff0fa14b62aeef5ea2fe66af3058d39e711c6af129cf4
       languageName: node
       linkType: hard
     
    @@ -3865,12 +3865,12 @@ __metadata:
       linkType: hard
     
     "chalk@npm:^4.1.0":
    -  version: 4.1.2
    -  resolution: "chalk@npm:4.1.2"
    +  version: 4.1.0
    +  resolution: "chalk@npm:4.1.0"
       dependencies:
         ansi-styles: ^4.1.0
         supports-color: ^7.1.0
    -  checksum: fe75c9d5c76a7a98d45495b91b2172fa3b7a09e0cc9370e5c8feb1c567b85c4288e2b3fded7cfdd7359ac28d6b3844feb8b82b8686842e93d23c827c417e83fc
    +  checksum: 5561c7b4c063badee3e16d04bce50bd033e1be1bf4c6948639275683ffa7a1993c44639b43c22b1c505f0f813a24b1889037eb182546b48946f9fe7cdd0e7d13
       languageName: node
       linkType: hard
     
    @@ -5095,15 +5095,15 @@ __metadata:
       linkType: hard
     
     "fast-glob@npm:^3.0.3":
    -  version: 3.3.0
    -  resolution: "fast-glob@npm:3.3.0"
    +  version: 3.2.7
    +  resolution: "fast-glob@npm:3.2.7"
       dependencies:
         "@nodelib/fs.stat": ^2.0.2
         "@nodelib/fs.walk": ^1.2.3
         glob-parent: ^5.1.2
         merge2: ^1.3.0
         micromatch: ^4.0.4
    -  checksum: 20df62be28eb5426fe8e40e0d05601a63b1daceb7c3d87534afcad91bdcf1e4b1743cf2d5247d6e225b120b46df0b9053a032b2691ba34ee121e033acd81f547
    +  checksum: 2f4708ff112d2b451888129fdd9a0938db88b105b0ddfd043c064e3c4d3e20eed8d7c7615f7565fee660db34ddcf08a2db1bf0ab3c00b87608e4719694642d78
       languageName: node
       linkType: hard
     
    @@ -7996,7 +7996,7 @@ __metadata:
       languageName: node
       linkType: hard
     
    -"semver@npm:7.5.0":
    +"semver@npm:7.5.0, semver@npm:^7.3.2, semver@npm:^7.3.5, semver@npm:^7.3.8":
       version: 7.5.0
       resolution: "semver@npm:7.5.0"
       dependencies:
    @@ -8007,7 +8007,7 @@ __metadata:
       languageName: node
       linkType: hard
     
    -"semver@npm:7.5.1, semver@npm:^7.3.2, semver@npm:^7.3.5, semver@npm:^7.3.8":
    +"semver@npm:7.5.1":
       version: 7.5.1
       resolution: "semver@npm:7.5.1"
       dependencies:
    @@ -8611,7 +8611,14 @@ __metadata:
       languageName: node
       linkType: hard
     
    -"tslib@npm:^2.0.3, tslib@npm:^2.1.0, tslib@npm:^2.5.0, tslib@npm:~2.5.0":
    +"tslib@npm:^2.0.3, tslib@npm:^2.1.0, tslib@npm:^2.5.0":
    +  version: 2.6.0
    +  resolution: "tslib@npm:2.6.0"
    +  checksum: c01066038f950016a18106ddeca4649b4d76caa76ec5a31e2a26e10586a59fceb4ee45e96719bf6c715648e7c14085a81fee5c62f7e9ebee68e77a5396e5538f
    +  languageName: node
    +  linkType: hard
    +
    +"tslib@npm:~2.5.0":
       version: 2.5.0
       resolution: "tslib@npm:2.5.0"
       checksum: ae3ed5f9ce29932d049908ebfdf21b3a003a85653a9a140d614da6b767a93ef94f460e52c3d787f0e4f383546981713f165037dc2274df212ea9f8a4541004e1
    @@ -8642,9 +8649,9 @@ __metadata:
       linkType: hard
     
     "typanion@npm:^3.8.0":
    -  version: 3.12.1
    -  resolution: "typanion@npm:3.12.1"
    -  checksum: a2e26fa216f8a1dbd2ffbaacb75b1e2dc042a0356e9702fba05a968cad95d9f661b24e37f6c6d8c3adad2c8582c99fca4826ff26a2d07cd2ae617ea87e6187eb
    +  version: 3.14.0
    +  resolution: "typanion@npm:3.14.0"
    +  checksum: fc0590d02c13c659eb1689e8adf7777e6c00dc911377e44cd36fe1b1271cfaca71547149f12cdc275058c0de5562a14e5273adbae66d47e6e0320e36007f5912
       languageName: node
       linkType: hard
     
</details>

**Comment by fcollonval** [comment]
The change for `tslib` and `semver` will be removed when applying the deduplication command.

So it will correctly keep lumino packages under the tested versions.

**Comment by fcollonval** [comment]
CI failure are not related.

**Comment by fcollonval** [comment]
Merging so I can do a release of 4.0.x

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 4.0.x

**Comment by jtpio** [comment]
> CI failure are not related.

Should we track these failures in a new issue?

As a follow-up to https://github.com/jupyterlab/jupyterlab/pull/14886. I was hoping https://github.com/jupyterlab/jupyterlab/pull/14886 would reduce the number of failed so we can be back to a CI that is green most of the time.

**Comment by fcollonval** [comment]
The one remaining is likely transient - I have seen it failing recently: https://github.com/jupyterlab/jupyterlab/actions/workflows/galata.yml. And the change here should not have an impact; but sure a new issue can be opened.

**Comment by jtpio** [comment]
The motivation here would be to reduce maintenance burden on other maintainers as well, so that if they see the green button and CI passing they can merge the PR with more confidence.

**Comment by fcollonval** [comment]
Yes I know, just being tired to be the only one doing PR to get it green lately.

**Pull request merged**
