### PR TITLE
Upgrade `jlpm` to yarn 3.4.1

### PR DESCRIPTION
**Pull request by brichet**
This PR follows https://github.com/jupyterlab/jupyterlab/pull/10929 by @telamonian, to upgrade `jlpm` commands to yarn 3.x.

## References

- Fixes https://github.com/jupyterlab/jupyterlab/issues/13552
- Closes https://github.com/jupyterlab/jupyterlab/pull/10929

Also related to:
- https://github.com/jupyter-server/jupyter_releaser/pull/491
- https://github.com/jupyterlab/maintainer-tools/pull/180

## Code changes

Changes in the installation and tests scripts, and in the config files.

## User-facing changes

Should no.

## Backwards-incompatible changes

No API change.

### CODE REVIEW

**Comment by jtpio** [comment]
I guess we can ignore the failing "Reject changes to staging / staging-check" CI check this time and leave it as is because of the new config files affecting the `staging` folder.

**Comment by brichet** [comment]
> I guess we can ignore the failing "Reject changes to staging / staging-check" CI check this time and leave it as is because of the new config files affecting the `staging` folder.

Yes you're right, at least the `yarn.js` file. 
And since the `yarn.lock` file has a different structure, all `python` tests also fail (comparing the new created one to the `staging` one). I hope these tests will not fail after a release.

**Comment by jtpio** [comment]
Should there also be a draft PR to update to yarn 3 on conda-forge? https://github.com/jupyterlab/jupyterlab/pull/14064

Just to prepare and foresee potential issues there.

**Comment by fcollonval** [comment]
bot please update galata snapshots

**Comment by fcollonval** [comment]
> Just to prepare and foresee potential issues there.

With yarn 3, the yarn asset needs to be versioned within the code repository - see for example in Lumino: https://github.com/jupyterlab/lumino/tree/main/.yarn/releases

I guess this is the reason nobody pushed it on conda-forge.

**Comment by jtpio** [comment]
> No API change.

Since this changes the underlying `yarn` used by `jlpm`, maybe it could be mentioned in the extension migration guide: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#extension-development-changes

**Comment by bollwyvl** [comment]
Ugh.

https://github.com/conda-forge/yarn-feedstock/pull/43

Not happy about this.

I'm still _highly_ in favor of shipping a well-behaved and versioned, `pip install`able wrapper for this that doesn't require the terrifying `corepack` dance, under a _non_ conflicting global name (probably still `jlpm`) so that we can give people something _simple_ to start with.

I don't like the `$npm_blah` in all of the `package.json/scripts`, as it definitely suggests this is going to ratchet up complexity, where something "works on my computer with my specific magic corepack," but not anywhere else.

As discussed elsewhere, _not_ shipping this 2mb slug in `jupyterlab` would be _ideal_, but having _something_ someone can `pip install` that will "just work" with "any given" nodejs, and is more supportable than the upstream which can't decide _how_ you should actually install it.

And why stop at 3.x? 4.x is in RC and even shinier, with no particular timeline, but a huge raft of breaking changes.

**Comment by fcollonval** [comment]
> Not happy about this.

@bollwyvl what are you not happy with, the bump of jlpm to be yarn 3 in this PR or the conda recipe?

**Comment by bollwyvl** [comment]
> not happy with

Welp: we went with `yarn` ne `jlpm` originally to simply the landscape for end users, unwittingly thrown into becoming nodejs developers, as it was much more reasonable to support a single,  predictable version than dealing with... whatever came out next week. But it still kinda worked with `npm`.

> yarn 3

`yarn>1` seems to make things _more_ complex, and _less_ compatible with other package managers, relying on more _still_ experimental features.

I'm can't advocate for any other specific package manager, as they all have show-stopping warts along the way, but _knowing_ this will break a bunch of workflows is dissatisfying. 

Of them, many appear to be unmaintained, even if they are faster, written in rust, solve world peace, whatever. `pnpm` seems the most-maintained and -promising, but does not have a single-file distribution, and relies on a bunch of opaque binaries, and _also_ relies on `corepack` shenanigans.

>  this PR

Note the current latest version is `yarn 3.4.1`, and this PR should probably follow suit... **with** a hard rebase so we don't get _another_ (couple) 2mb js slugs in the repo.

Aside from bug fixes, etc. `yarn 3.4.x` has better compatibility with [`typescript 5.0.0rc`](https://github.com/yarnpkg/berry/blob/master/CHANGELOG.md#compatibility-1), which we've _already_ decided to go with, but again, there's no way to anticipate when a `yarn 4.x` final is coming.

> the conda recipe

This particular aspect is... fine. Shipping `yarn 3.4.1` and its various shell wrappers is... fine. But upstream published a `4.0rc` as a non-pre-release, which means the feedstock won't get automated PRs `yarn 3.x`, now, or after `yarn 4.0` final, so it's going to be a lot of manual work to keep `yarn 3.x` working.

Meanwhile, going straight to 4.x would ensure all of the [additional breaking changes](https://github.com/yarnpkg/berry/issues/3591) are dealt with _now_, rather than at some point in the future, but there's no telling if it will be a) finished by the time `jupyterlab 4.x` is in users and devs hands, or b) will be maintained during the whole life of `jupyterlab 4.x`.

**Comment by fcollonval** [comment]
Thanks Nick, to try to sum up the actions forward, we should

- Decide if we go with yarn 4-rc hoping for a final release for Lab 4.0.0 (as we are doing for TypeScript 5) or stick to yarn 3
- If sticking to yarn 3 bump to the latest version in this PR

Is that correct?

**Comment by bollwyvl** [comment]
Yes. The nickle fix, if we're not sticking with `yarn 1`, is how this PR gets _one_ copy checked into the repo of `yarn 3.4.x`... or `yarn 4.x` knowing we will incur another copy in some number of days/weeks/months. 

_or_, 

We make the call that all `nodejs`-related stuff is no longer part of the public API of `pip install jupyterlab`, and have a separate `pip`-installable package, e.g. `jupyterlab-build` (which can _require_ `nodejs >=14` (or whatever we support) on `conda-forge`). 

Ideally such a package would: 
- work in `pyproject.toml#/build-system` and only bring the absolute minimum
  - parts of `jupyterlab` and `jupyterlab_server` would need to factored out
- have a version indepdent from `jupyterlab`
  - wider `jupyterlab` support than "exactly one major version"
    - e.g. `jupyterlab 3.7.x` and `jupyterlab 4.x`
- the `yarn.js` "binary" and `jlpm` wrapper
  - ship an initial version that matches `juptyerlab 3.6.x` (e.g. `yarn 1`)
  - initially a "transition" version with _both_ `yarn.js` versions (buh, but at least you won't accidentally need a `rust` nightly compiler)

Ideally, this would support extension authors in the transition from `jupyterlab 3` to `jupyterlab 4`.

**Comment by bollwyvl** [comment]
There is now also a `rc-4.x` branch on conda-forge:

**Comment by fcollonval** [comment]
I started a very early draft PR extracting the builder logic in the hatch-jupyter-builder package; to see if the level of complexity to do the extraction.

https://github.com/jupyterlab/hatch-jupyter-builder/pull/107

It is not finished - just move code and try to cut to the minimal requirements for now.

The main required trick seems to be the load of `LabApp` traitlets without depending on `jupyterlab`.

**Comment by bollwyvl** [comment]
> hatch-jupyter-builder

I don't see a build-backend-specific thing as being the path forward: it's fine if `hatch-jupyter-builder` depends on whatever the eventual thing is, but it needs to be generally available _outside_ of the murky magical hatch build environment for e.g. `jupyter labextension develop`, and not require recursive descent into ten layers of docs.

>  the load of LabApp traitlets without depending on jupyterlab.

Yep. Also `jupyterlab_server` has some of the plumbing, as well.

A `traitlets`, and _maybe_ `jupyter-core` dependency is fine, and probably to be expected. But `jupyterlab_server`, etc. are too much.

So maybe there's a `jupyterlab_core` which only gets to depend on `jupyter_core`, which then provides mixins consumed by `jupyterlab`, `jupyterlab_server` and `jupyterlab_builder`.

**Comment by bollwyvl** [comment]
Here's a strawman view of how the multi-package approach could work:

```mermaid
graph TB;

subgraph build-or-dev-time-only
    hatch_jupyter_builder
    jupyterlab_builder
end

subgraph end-user-run-time
    jupyterlab
    notebook
    jupyterlab_server
    jupyter_server
    babel
    tornado

    subgraph all-the-time
        jupyterlab_core
        jupyter_core
        traitlets
        platformdirs
        jsonschema
        json5
    end

end

jupyterlab_builder --> nodejs((nodejs))
jupyterlab --> jupyterlab_server;
hatch_jupyter_builder --> jupyterlab_builder;
jupyterlab_builder(jupyterlab_builder NEW) --> jupyterlab_core;
jupyterlab_core --> json5;
jupyter_server --> tornado;
jupyterlab_server --> jupyterlab_core;
jupyterlab_server --> babel;
jupyter_server --> jupyter_core;
jupyterlab_core(jupyterlab_core NEW) --> jupyter_core;
jupyterlab_core --> jsonschema;
jupyter_core --> traitlets;
jupyter_core --> platformdirs;
jupyter_core -.-> pywin32((pywin32));
notebook --> jupyterlab_server;
jupyterlab_server --> jupyter_server;
```

**Comment by bollwyvl** [comment]
Also: damn: we should just add mermaid to JupyterLab:

https://mermaid.js.org/config/usage.html#example-of-a-marked-renderer

It's supported by GitHub and GitLab, and a couple of the chat providers.

Guess I have a few hours to sneak that any before Feb 28, anywhere on earth lol.

**Comment by brichet** [comment]
bot please update galata snapshots

**Comment by brichet** [comment]
Ui tests and check link should pass.
There was no snapshot to update.

**Comment by brichet** [comment]
bot please update galata snapshots

**Comment by brichet** [comment]
Kicking the CI

**Comment by brichet** [comment]
Thanks @fcollonval for fixing the build in Windows

**Review by fcollonval — APPROVED** [review]
Thanks @brichet

**Pull request merged**
