### PR TITLE
test for 400% zoom low vision support

### PR DESCRIPTION
**Pull request by j264415**
## References

Related PR - [#14766](https://github.com/jupyterlab/jupyterlab/pull/14766): 400% Zoom screen usability enhancements - Updated

## Code changes

Added test for galata screenshot to make sure that - when zoomed in at 400% zoom at 1280px - the important parts of the Jupyterlab application are shown for low vision users only at a high zoom level. 

## User-facing changes

None

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by j264415** [comment]
please update galata snapshots

**Comment by j264415** [comment]
please update galata snapshots

**Comment by j264415** [comment]
please update galata snapshots

**Comment by krassowski** [comment]
Is the goal of this shapshot to test whether "Help" on menu bar is visible for this zoom and screen width? If this is the case could you rename the snapshot/test to reflect it and trim the height of the screenshot so that only the menu bar is visible?

**Comment by j264415** [comment]
please update galata snapshots

**Comment by j264415** [comment]
> Is the goal of this shapshot to test whether "Help" on menu bar is visible for this zoom and screen width? If this is the case could you rename the snapshot/test to reflect it and trim the height of the screenshot so that only the menu bar is visible?

Hi @krassowski please look at the changes i have made in response to this feedback. Any more changes need please let me know. 
Thank you

**Comment by krassowski** [comment]
Thanks! Can you merge this PR into #14766 and then update snapshots over there to demonstrate that it solves the issue? It would reduce back and forth between the PRs.

**Comment by j264415** [comment]
@krassowski All done!

**Comment by JasonWeill** [comment]
Closing in favor of #14766.

**Pull request closed without merging**
