### PR TITLE
New token providing `IWidgetOpener`

### LINKED ISSUE #12965: open a new view is broken
## Description

https://github.com/jupyterlab/jupyterlab/pull/12349 breaks the clone view command because the opener is no more defined in the plugin adding the commands

## Reproduce

1. Open a notebook
2. Right click on the notebook tab
3. Select `New view for notebook`
4. Nothing happen an error is emitted in the console

## Expected behavior

No error
It seems the solution would be to provide the opener as a plugin to be requested by the plugin adding the commands.

## Context

- JupyterLab version: master

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #12965

## Code changes

New plugin exporting a new token `IWidgetOpener` (formerly `DocumentManager.IWidgetOpener`)

## User-facing changes

Restore cloning a view

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @fcollonval for looking into this.

Looks like this is subset of https://github.com/jupyterlab/jupyterlab/pull/12701. We could get that one in first and then rebase https://github.com/jupyterlab/jupyterlab/pull/12701 on top of the new changes afterwards.

**Comment by fcollonval** [comment]
@jtpio do you have time to finish #12701? Happy to do the review then.

**Comment by fcollonval** [comment]
Closing as this is not gonna work because opener and document manager have a cyclic relationship. So a better fix seems to be exposing the opener from the document manager.

**Comment by jtpio** [comment]
Right this was also one observation when working on https://github.com/jupyterlab/jupyterlab/pull/12701 which made it stall a bit.

I'll try to get back to it soon.

**Pull request closed without merging**
