### PR TITLE
Fix save as in collaborative mode

### LINKED ISSUE #14107: SaveAs not working in collaborative mode
## Description

When using Jupyterlab 3.6.1 in collaborative mode the SaveAs function does not work. 

## Reproduce

1. Start `jupyter lab --collaborative`
2. Create a new notebook, add some python code and execute it.
3. Make a trivial change
4. Use File->SaveAs and enter a new name 

## Expected behavior

A new file with the new name should appear.

## Context

This occurs on Linux (RHEL7), with a current chrome browser in Jupyterlab 3.6.1.

The corresponding log output:

When creating a new file and editing it:
````
[I 2023-03-01 11:09:28.234 ServerApp] Creating new notebook in /work
[I 2023-03-01 11:09:28.241 ServerApp] Saving Untitled1.ipynb
[I 2023-03-01 11:09:28.310 ServerApp] Request for Y document 'work/Untitled1.ipynb' with room ID: json:notebook:d6e0fbaa-bac9-4f0b-93e6-cace852250d8
[I 2023-03-01 11:09:29.411 ServerApp] Saving Untitled1.ipynb
[I 2023-03-01 11:09:31.546 ServerApp] Kernel started: 8fa35f65-5eca-4596-ac09-b6c367c7c25a
[I 2023-03-01 11:09:32.603 ServerApp] Saving Untitled1.ipynb
[I 2023-03-01 11:09:33.421 ServerApp] Connecting to kernel 8fa35f65-5eca-4596-ac09-b6c367c7c25a.
[I 2023-03-01 11:09:33.434 ServerApp] Connecting to kernel 8fa35f65-5eca-4596-ac09-b6c367c7c25a.
[I 2023-03-01 11:09:33.448 ServerApp] Connecting to kernel 8fa35f65-5eca-4596-ac09-b6c367c7c25a.
[I 2023-03-01 11:09:34.466 ServerApp] Saving Untitled1.ipynb
[I 2023-03-01 11:09:37.222 ServerApp] Processed 47 Y patches in one minute
[I 2023-03-01 11:09:37.225 ServerApp] Connected Y users: 5
[I 2023-03-01 11:09:39.730 ServerApp] Saving Untitled1.ipynb
[I 2023-03-01 11:09:42.148 ServerApp] Saving Untitled1.ipynb
````

Immediately afterwards when using SaveAs (with filename `Untitled5.ipynb`):
````
[W 2023-03-01 11:09:55.945 ServerApp] 404 GET /api/contents/work/Untitled5.ipynb?1677665395941 (129.129.244.78): file or directory does not exist: 'work/Untitled5.ipynb'
[W 2023-03-01 11:09:55.947 ServerApp] wrote error: "file or directory does not exist: 'work/Untitled5.ipynb'"
    Traceback (most recent call last):
      File "/applications/conda/envs/analysis_forge/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/applications/conda/envs/analysis_forge/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 122, in get
        self.contents_manager.get(
      File "/applications/conda/envs/analysis_forge/lib/python3.10/site-packages/jupytext/contentsmanager.py", line 199, in get
        return self.super.get(path, content, type, format)
      File "/applications/conda/envs/analysis_forge/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 410, in get
        raise web.HTTPError(404, four_o_four)
    tornado.web.HTTPError: HTTP 404: Not Found (file or directory does not exist: 'work/Untitled5.ipynb')
[W 2023-03-01 11:09:55.950 ServerApp] 404 GET /api/contents/work/Untitled5.ipynb?1677665395941 (6b2281a6360549d48932d325f548dff8@129.129.244.78) 6.05ms referer=http://ra-c-069.psi.ch:8888/lab/tree/work/Untitled1.ipynb
[I 2023-03-01 11:09:57.467 ServerApp] Saving Untitled1.ipynb
````

### PR DESCRIPTION
**Pull request by hbcarlos**
Fixes #14107

## References
This PR was started in #14130 as a fix for lab v3.6. I am opening a new PR because we must also fix it in lab v4.

## Code changes
After saving the document with a different name, we do not rename the document in memory. Instead, we close it and open the new one.

## User-facing changes
In collaborative mode, we can not rename the document in memory. After a "Save As" action, we need to open the new document and close the old one. By closing the document and opening the new one, we are losing the state of the old document. Most editors do this, and, in my opinion, it is the most predictable behavior.

See https://github.com/jupyterlab/jupyterlab/pull/14130 for more context.

## Screencast

https://user-images.githubusercontent.com/26092748/224733083-bc40840e-cd91-4bf3-8527-cb144b263e0c.mov

### CODE REVIEW

**Review by fcollonval — DISMISSED** [review]
thanks @hbcarlos

**Comment by fcollonval** [comment]
Sorry for the last minute notice, but there is a bug due to the drive name appearing in the _Save As..._ dialog:

Peek 2023-03-15 16-39

I think it is better to solve it within this PR.

**Comment by hbcarlos** [comment]
Hey @fcollonval! I changed the dialog not to show the drive name and updated jupyter_collaboration to fix the issue.


https://user-images.githubusercontent.com/26092748/225440254-685e47f1-0927-4900-9546-3738884ad6ec.mov

**Review by fcollonval — APPROVED** [review]
Thanks @hbcarlos 

I checked on binder with RTC and locally

> CI failures are not related

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.6.x

**Pull request merged**
