### PR TITLE
Switch from hub to gh CLI

### LINKED ISSUE #15212: `hub` GitHub CLI tool has been removed on October 2nd
## Description

`hub` cli has been removed on October 2nd: https://github.com/actions/runner-images/issues/8362

Some of our jobs are gonna break; like https://github.com/jupyterlab/jupyterlab/actions/runs/6392711780/job/17350524454

> The best fix is to migrate to the new [GitHub CLI](https://cli.github.com)

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #15212

## Code changes

None

> Switch from hub to gh CLI in CI jobs

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Review by krassowski — APPROVED** [review]
Thank you!

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.0.x

**Comment by krassowski** [comment]
@meeseeksdev please backport to 3.6.x

**Comment by fcollonval** [comment]
In fact we are not using it on 3.6.x. So the backport is not needed, sorry for the confusion

**Pull request merged**
