### PR TITLE
Fix code mirror sizing

### PR DESCRIPTION
**Pull request by SimonBiggs**
RE: https://github.com/jupyterlab/jupyterlab/pull/3188

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks for the fresh PR!  I rebased and made a couple of clean ups.  I tested in Firefox and Chrome, looks good!  Will merge when CI passes.

**Comment by SimonBiggs** [comment]
You're welcome :)

**Comment by SimonBiggs** [comment]
By the way, how did you make the test pass? I couldn't work out what I had done wrong... Granted, I didn't try too hard at that point as it was quite late.

**Comment by blink1073** [comment]
The `packages/` had failed to build because we detected that an import was missing in one of the `package.json` files.  We didn't see it because it was in the `install` phase on Travis.  So when the `test:build` script tried to run, it could not find the built files in `packages/`, making it look like the tests were failing.   That's why we moved the package integrity check to the first step in the `script` process in https://github.com/jupyterlab/jupyterlab/pull/3216.

**Comment by SimonBiggs** [comment]
Makes sense. So when I included Widgets I didn't also add widgets to the
package.json.

**Comment by blink1073** [comment]
Yep, the integrity script makes sure we are not just working because of the monorepo.

**Comment by SimonBiggs** [comment]
Uhuh! :) Thanks for the clarification. I wasn't even thinking about
package.json or the fact that each of these packages needs to stand by
itself. I would have been chasing my tail.

**Comment by SimonBiggs** [comment]
As an aside, how different will the model API be after the refactor? Is it
worth me trying to implement it now for my extension? Or would it be better
to wait until the refactor is finished?

**Comment by blink1073** [comment]
I think it will be different enough that waiting makes sense.

Sent from phone

________________________________

**Comment by SimonBiggs** [comment]
:) thanks for that. I'll focus on documenting and refactoring/tidying up
the extension until the new model API comes out.

**Pull request merged**
