### PR TITLE
Rework services terminal code

### PR DESCRIPTION
**Pull request by jasongrout**
## References

Following up on #7252, this refactors the terminal code to follow the same patterns as the kernel and session code now does.

## Code changes

Reworks the services terminal interface.

## Backwards-incompatible changes

As in #7252, lots of APIs change for terminals.

- [x] Fix tests

### CODE REVIEW

**Comment by jasongrout** [comment]
windows js failures, for the record:

```
@jupyterlab/test-services: FAIL tests/test-services/src/session/manager.spec.ts (155.015s)
@jupyterlab/test-services:   ● session/manager › SessionManager › #startNew() › should start a session
@jupyterlab/test-services:     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
@jupyterlab/test-services:       at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
@jupyterlab/test-services: FAIL tests/test-services/src/kernel/ikernel.spec.ts (455.147s)
@jupyterlab/test-services:   ● Kernel.IKernel › #status › should get a busy status
@jupyterlab/test-services:     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
@jupyterlab/test-services:       at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
@jupyterlab/test-services:           at runMicrotasks (<anonymous>)
@jupyterlab/test-services:   ● Kernel.IKernel › #status › should get a busy status
@jupyterlab/test-services:     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
@jupyterlab/test-services:       at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
@jupyterlab/test-services:   ● Kernel.IKernel › #requestExecute() › should send and handle incoming messages
@jupyterlab/test-services:     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
@jupyterlab/test-services:       at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
@jupyterlab/test-services:           at runMicrotasks (<anonymous>)
```

**Comment by jasongrout** [comment]
Again a failure:

```
@jupyterlab/test-outputarea:   ● outputarea/widget › OutputArea › #future › should clear existing outputs
@jupyterlab/test-outputarea:     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
@jupyterlab/test-outputarea:       at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
```

**Comment by jasongrout** [comment]
This time:

```
@jupyterlab/test-services: FAIL tests/test-services/src/session/manager.spec.ts (155.963s)
@jupyterlab/test-services:   ● session/manager › SessionManager › #ready › should resolve when the manager is ready
@jupyterlab/test-services:     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
@jupyterlab/test-services:       at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
@jupyterlab/test-services: FAIL tests/test-services/src/kernel/ikernel.spec.ts (694.443s)
@jupyterlab/test-services:   ● Kernel.IKernel › #status › should get a dead status
@jupyterlab/test-services:     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
@jupyterlab/test-services:       at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
@jupyterlab/test-services:           at runMicrotasks (<anonymous>)
@jupyterlab/test-services:   ● Kernel.IKernel › #status › should get a dead status
@jupyterlab/test-services:     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
@jupyterlab/test-services:       at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
@jupyterlab/test-services:   ● Kernel.IKernel › #info › should get the kernel info
@jupyterlab/test-services:     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
@jupyterlab/test-services:       at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
@jupyterlab/test-services:   ● Kernel.IKernel › #info › should get the kernel info
@jupyterlab/test-services:     : Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error:
@jupyterlab/test-services:       370 | 
@jupyterlab/test-services:       371 |   describe('#info', () => {
@jupyterlab/test-services:     > 372 |     it('should get the kernel info', async () => {
@jupyterlab/test-services:           |     ^
@jupyterlab/test-services:       373 |       const name = (await defaultKernel.info).language_info.name;
@jupyterlab/test-services:       374 |       const defaultSpecs = specs.kernelspecs[specs.default];
@jupyterlab/test-services:       375 |       expect(name).to.equal(defaultSpecs.language);
@jupyterlab/test-services:       at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
@jupyterlab/test-services:       at Suite.<anonymous> (tests/test-services/src/kernel/ikernel.spec.ts:372:5)
@jupyterlab/test-services:       at Suite.<anonymous> (tests/test-services/src/kernel/ikernel.spec.ts:371:3)
@jupyterlab/test-services:       at Object.<anonymous> (tests/test-services/src/kernel/ikernel.spec.ts:25:1)
@jupyterlab/test-services:   ● Kernel.IKernel › #sendShellMessage() › should handle out of order messages
@jupyterlab/test-services:     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
@jupyterlab/test-services:       at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
@jupyterlab/test-services:           at runMicrotasks (<anonymous>)
@jupyterlab/test-services: FAIL tests/test-services/src/kernel/comm.spec.ts (22.943s)
@jupyterlab/test-services:   ● jupyter.services - Comm › Kernel › #registerCommTarget() › should call the provided callback
@jupyterlab/test-services:     : Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.Error:
@jupyterlab/test-services:       106 | 
@jupyterlab/test-services:       107 |     describe('#registerCommTarget()', () => {
@jupyterlab/test-services:     > 108 |       it('should call the provided callback', async () => {
@jupyterlab/test-services:           |       ^
@jupyterlab/test-services:       109 |         const promise = new PromiseDelegate<
@jupyterlab/test-services:       110 |           [Kernel.IComm, KernelMessage.ICommOpenMsg]
@jupyterlab/test-services:       111 |         >();
@jupyterlab/test-services:       at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
@jupyterlab/test-services:       at Suite.<anonymous> (tests/test-services/src/kernel/comm.spec.ts:108:7)
@jupyterlab/test-services:       at Suite.<anonymous> (tests/test-services/src/kernel/comm.spec.ts:107:5)
@jupyterlab/test-services:       at Suite.<anonymous> (tests/test-services/src/kernel/comm.spec.ts:69:3)
@jupyterlab/test-services:       at Object.<anonymous> (tests/test-services/src/kernel/comm.spec.ts:50:1)
```

**Comment by jasongrout** [comment]
Again, documenting the failures:

```
@jupyterlab/test-services: FAIL tests/test-services/src/kernel/ikernel.spec.ts (577.353s)
@jupyterlab/test-services:   ● Kernel.IKernel › #sendInputReply() › should send an input_reply message
@jupyterlab/test-services:     Timeout - Async callback was not invoked within the 240000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 240000ms timeout specified by jest.setTimeout.
@jupyterlab/test-services:       at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
@jupyterlab/test-services:           at runMicrotasks (<anonymous>)
@jupyterlab/test-services:   ● Kernel.IKernel › #sendInputReply() › should fail if the kernel is dead
@jupyterlab/test-services:     Timeout - Async callback was not invoked within the 240000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 240000ms timeout specified by jest.setTimeout.
@jupyterlab/test-services:       at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
```

**Comment by jasongrout** [comment]
Finally passed that windows js test!

**Comment by blink1073** [comment]
Sorry, this picked up a couple of merge conflicts.

**Comment by jasongrout** [comment]
Fixed the merge conflicts and one null check issue.

**Comment by blink1073** [comment]
LGTM, thanks!

**Pull request merged**
