### PR TITLE
Update yarn.lock

### PR DESCRIPTION
**Pull request by gnestor**
This is a continuation of https://github.com/jupyterlab/jupyterlab/pull/6706.

This just commits changed to yarn.lock.

### CODE REVIEW

**Comment by jasongrout** [comment]
That is a *lot* to change from adding one dependency. How did so much get updated? I thought we were basically trying to lock down the yarn.lock now that we are in the RC stage.

It appears there are lots of duplicates now as well - did you deduplicate the yarn.lock file?

**Comment by vidartf** [comment]
@jasongrout I am only seeing the addition of 6-7 deps, and no duplication. What duplication are you seeing?

**Comment by jasongrout** [comment]
Wow, I'm also just seeing a few updates. What I thought I saw was the yarn.lock file basically totally being updated. I'm not sure if I was somehow looking at a different PR, or if there was some issue with GitHub. Okay, never mind, sorry, I withdraw my objection.

**Comment by vidartf** [comment]
Cosmic rays ;)

**Pull request merged**
