### PR TITLE
Do not refresh codeeditor on update-request

### PR DESCRIPTION
**Pull request by echarles**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/9383

## Code changes

Remove in `codeeditor/src/widget.ts`

```
   protected onUpdateRequest(msg: Message): void {
      if (this.isVisible) {
       this._hasRefreshedSinceAttach = true;
      this.editor.refresh();  
     }
   }
```

## User-facing changes

None - To be confirmed by @goanpeca 

## Backwards-incompatible changes

None - To be confirmed based on the tests runs.

### CODE REVIEW

**Comment by jasongrout** [comment]
This looks like it is part of a system where it tries to be intelligent about when to do the refresh, so it may be more complicated than just deleting these lines of code. Where else is that parameter used, and why do we not need to reset it and refresh anymore?

I know a lot of thought has gone into exactly when a codemirror is refreshed (and this caching attribute that is set here is evidence of a system that tries to not refresh *all* of the time). With this code deleted, when is it still refreshed?

**Comment by echarles** [comment]
@jasongrout I am with you on the need to understand what we are doing. I have just for now naively removed the block of code reponsible for forced layout. Now to understand why this has been introduced, i would need to go back in history.

Anyone else has hints here?

At some point, if no impact can be identified, I would say we could merge even if we don't know why it was introduced. In that case, the `_hasRefreshedSinceAttach` attributed could be completely removed.

**Comment by echarles** [comment]
Looks like it has been introduced in https://github.com/jupyterlab/jupyterlab/pull/7672

**Comment by goanpeca** [comment]
@echarles I tested this and this seem to raise issues.

For the test notebook with ~200 cells, I get ~200 refreshes.

image

If I test this branch, the cells bellow the scroll window are displayed like this

image

**Comment by echarles** [comment]
Gosh. The initial changes were on master and I ported it to 2.3.x with a large number of cells to be rendered directly (in my settings). I can confirm the issue you raise.

To fix this, I have added an explicit call to editor.refresh() when rendering a placeholder cell to a real cell. @goanpeca Could you check on your env?

**Comment by goanpeca** [comment]
@echarles and @jasongrout I have tested this and works as expected. I could not see any harmful issues form the removal of that code path. Also run the notebooks tests locally and all seem to run fine:

```
✨  Done in 279.79s.
+ jlpm run clean
yarn run v1.21.1
$ rimraf lib && rimraf tsconfig.tsbuildinfo
✨  Done in 0.96s.
+ [[ js-notebook == docs ]]
+ [[ js-notebook == integrity ]]
+ [[ js-notebook == integrity2 ]]
+ [[ js-notebook == usage ]]
+ [[ js-notebook == nonode ]]
```

**Review by goanpeca — APPROVED** [review]
I could not find any ill effects of removing the code for this PR.

**Comment by echarles** [comment]
Thx @goanpeca Before going further with a merge. I will check other edge cases related to readonly notebooks

**Comment by ellisonbg** [comment]
I am very nervous about this. Over the years we have found a range of unexepected situations where we needed to call refresh. A lot of these were related to situations that cause CodeMirror to need to recompute its dimensions and adjust its layout. This includes:

* Copy/pasting text into a CM editor such that the height of the editor changes or the line wrapping changes.
* Resizing the width of the CM editor due to panels/tabs/etc resizing.
* Hide/show/collapse type of events.
* Creating new CM editors in certain situations.

These have been some of the most painful bugs for users and most subtle to fix and test (I am not confident we are testing for all these cases currently). We have also run into subtle issues where these behaviors vary across CM versions and browsers in surprising ways.

As a result of this, I think we need to assume that any code related to this is highly tuned to cover these edge cases and behaviors. I don't think it means we can't change or improve this, but we have to chase down and understand all the edge cases first.

**Comment by goanpeca** [comment]
@echarles do we wan to retake this and finish (or do more testing)

Thanks! :)

**Pull request closed without merging**
