### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by jasongrout**
## References

See https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository

## Code changes

Adds code scanning from GitHub. Let's see if it gives anything interesting?

### CODE REVIEW

**Comment by jasongrout** [comment]
Results are under the Security tab: https://github.com/jupyterlab/jupyterlab/security/code-scanning?query=tool%3ACodeQL+is%3Aopen+ref%3Arefs%2Fpull%2F9119%2Fhead

**Comment by telamonian** [comment]
haha, more than half of the complaints are about problems in our vendored copy of yarn at `jupyterlab/staging/yarn.js`

**Comment by jasongrout** [comment]
I think the current list of issues (https://github.com/jupyterlab/jupyterlab/security/code-scanning?query=tool%3ACodeQL+is%3Aopen+ref%3Arefs%2Fpull%2F9119%2Fhead) is a legitimate list to look at, so I think this is ready for review/merge. I've had it ignore paths that were causing spurious issues (such as `node_modules`, our copy of yarn, etc.)

**Review by blink1073 — APPROVED** [review]
Thanks!

**Pull request merged**
