### PR TITLE
Set overflow to visible for output widget

### LINKED ISSUE #1743: Set overflow differently `.jp-Output-result`
Right now `.jp-Output-result` has `overflow: auto`. It should likely be `visible` as ipywidgets end up scrolling. See discussion  in https://github.com/ipython/ipywidgets/issues/1128

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #1743.

### CODE REVIEW

**Comment by blink1073** [comment]
cc @jasongrout, does this address https://github.com/ipython/ipywidgets/issues/1128?

**Comment by sccolbert** [comment]
I'm not sure this is what we want.

**Comment by sccolbert** [comment]
If the content doesn't fit the output area, the output area should either grow or scroll. In what case should the output content overflow into the input area of the next cell below it, or over the right boundary of the notebook?

**Comment by afshin** [comment]
@sccolbert D'oh! I missed your comment and just jumped to the CSS. If we need to change this, we can do it in another PR.

**Comment by sccolbert** [comment]
Yeah. I have a feeling this is not the right fix.

**Pull request merged**
