### PR TITLE
Change compilation target from ES2017 to ES2018

### PR DESCRIPTION
**Pull request by afshin**
This PR updates JupyterLab 4's TypeScript compilation `target` from its current value (`ES2017`) to `ES2018` to support native `AsyncIterable` instances (e.g., instances and sub-classes of `Poll` or classes that are composed with it).

cf.:
- https://github.com/jupyterlab/lumino/pull/388
- https://github.com/jupyterlab/lumino/pull/386

Resolves https://github.com/jupyterlab/jupyterlab/issues/13052

### CODE REVIEW

**Review by afshin — COMMENTED** [review]
please update snapshots

**Review by afshin — COMMENTED** [review]
please update snapshots

**Comment by afshin** [comment]
please update snapshots

**Comment by fcollonval** [comment]
> FYI at least one update job was triggered: https://github.com/jupyterlab/jupyterlab/actions/runs/2993206934

**Review by fcollonval — APPROVED** [review]
Thanks @afshin

**Pull request merged**
