### PR TITLE
Remove bottom border for tabBar.

### LINKED ISSUE #6521: Tabs in main work area have extra border.
**Describe the bug**

Tabs of activities in the main work area should have a borderless transition to the activity toolbar below. The tab itself now has a bottom border. As we fix this we should be very careful to understand how this happened - I am guessing we were fixing another bug. This was handled in the past by making the tab was made 1px taller, and then moved down 1px to hide that border. Should be tested in light/dark theme.

**To Reproduce**

Open any activity in the main work area.

**Screenshots**

Screen Shot 2019-06-09 at 1 09 05 PM

### PR DESCRIPTION
**Pull request by ian-r-rose**
## References

Fixes #6521

### CODE REVIEW

**Comment by jasongrout** [comment]
Screenshot showing the bottom border is fixed, and #6492 is still fixed:

Screen Shot 2019-06-10 at 11 36 20 AM


However, notice that there aren't borders on the sides of the tabs anymore in the dark theme, like there are on the light theme, so you can see where one tab ends and another begins:

Screen Shot 2019-06-10 at 11 37 59 AM

**Comment by jasongrout** [comment]
> there aren't borders on the sides of the tabs anymore in the dark theme

Not sure if this is from this PR or an existing issue.

**Comment by jasongrout** [comment]
Looks like the side border is there, just that the border is `#414141`, while the tab background is `#424242`, so the border is not distinguishable.

**Comment by jasongrout** [comment]
> Looks like the side border is there, just that the border is `#414141`, while the tab background is `#424242`, so the border is not distinguishable.

Never mind, seems like there was a caching issue? In reality, it looks like the tabs have background `var(--jp-layout-color2)` and border `var(--jp-border-color1)`, and both are `--md-grey-800` in the dark theme: 
https://github.com/jupyterlab/jupyterlab/blob/d69ce4947da79d82d27f2d3fecb70b66acbaecbe/packages/theme-dark-extension/style/variables.css#L93-L94
https://github.com/jupyterlab/jupyterlab/blob/d69ce4947da79d82d27f2d3fecb70b66acbaecbe/packages/theme-dark-extension/style/variables.css#L203-L206

**Comment by jasongrout** [comment]
@ellisonbg - this pr looks fine. Do you or @ian-r-rose want to take a look at the color issue I pointed above, or should we merge this and open a new issue?

**Comment by ian-r-rose** [comment]
@jasongrout I'm a little reticent to change the theme border colors -- that is likely to have some subtle and wide-ranging implications. I brought something similar up in #6153 and we decided to back off of the change. Or do you mean something different?

**Comment by jasongrout** [comment]
This now passing, so I'll merge this and open a follow-up.

**Comment by jasongrout** [comment]
> Or do you mean something different?

Well, clearly something is wrong in the dark theme since `--jp-layout-color2` and `--jp-border-color2` are the same color.

And something seems off for tabs to be using the layout color 2, but border color 1.

I'll post my suggestion on a new issue.

**Comment by jasongrout** [comment]
I opened #6527

**Pull request merged**
