### PR TITLE
Fix code/content/ui font-size change

### PR DESCRIPTION
**Pull request by FoSuCloud**
## References

fix [incr-font-size is not work #13598 ](https://github.com/jupyterlab/jupyterlab/issues/13598)

## Code changes

When initializing the thememanager of apputils, modify the key- > attribute dict function (_initOverrideProps)of the initialization override, overwrite description

image

## User-facing changes

nothing

## Backwards-incompatible changes

nothing

### CODE REVIEW

**Comment by FoSuCloud** [comment]
bot please add bug label

**Comment by FoSuCloud** [comment]
@bot add bug

**Comment by FoSuCloud** [comment]
It seems that I don't have the authority to add tags. How can I apply for adding bug tags?

**Comment by FoSuCloud** [comment]
bot please update snapshots

**Comment by FoSuCloud** [comment]
bot please labeled bug

**Comment by krassowski** [comment]
> It seems that I don't have the authority to add tags. How can I apply for adding bug tags?

I added it but you can also tag with help of `@meeseeksdev` bot see [Tagging Issues with Labels](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#tagging-issues-with-labels).

**Comment by krassowski** [comment]
> bot please update [...]

I restarted the UI tests I think these are just flaky rather than needing update.

However, would you be happy to try adding an UI test which would test increasing font size following the reproduction steps from your issue?

**Comment by FoSuCloud** [comment]
@meeseeksdev tag enhancement

**Comment by FoSuCloud** [comment]
@meeseeksdev untag enhancement

**Comment by FoSuCloud** [comment]
> > 机器人请更新[...]
> 
> 我重新启动了 UI 测试，我认为这些只是不稳定而不需要更新。
> 
> 但是，您是否乐意尝试添加一个 UI 测试，该测试将按照您的问题的复制步骤测试增加的字体大小？



> > bot please update [...]
> 
> I restarted the UI tests I think these are just flaky rather than needing update.
> 
> However, would you be happy to try adding an UI test which would test increasing font size following the reproduction steps from your issue?

I'd be happy to try to add this UI test.

**Review by fcollonval — COMMENTED** [review]
Thanks @FoSuCloud 
it works great.

If you want to add a test for this, I would advice you to start by copying the following test:

https://github.com/jupyterlab/jupyterlab/blob/a51b7d9df2b4e24d39b2333e22f46a96d004bfa6/galata/test/galata/fixture.spec.ts#L38

A good place to add the test would be `galata/test/jupyterlab/settings.test.ts`.

**Comment by FoSuCloud** [comment]
> Yes, I was trying to add a ui test, but executing the ui test keeps failing
https://github.com/jupyterlab/jupyterlab/issues/14127
Would you like to help see what the problem is?

**Comment by FoSuCloud** [comment]
> 谢谢@FoSuCloud 它很好用。
> 
> 如果你想为此添加一个测试，我建议你从复制以下测试开始：
> 
> https://github.com/jupyterlab/jupyterlab/blob/a51b7d9df2b4e24d39b2333e22f46a96d004bfa6/galata/test/galata/fixture.spec.ts#L38
> 
> 添加测试的好地方是`galata/test/jupyterlab/settings.test.ts`.



> 谢谢@FoSuCloud 它很好用。
> 
> 如果你想为此添加一个测试，我建议你从下面的测试开始：
> 
> https://github.com/jupyterlab/jupyterlab/blob/a51b7d9df2b4e24d39b2333e22f46a96d004bfa6/galata/test/galata/fixture.spec.ts#L38
> 
> 添加测试的好地方是`galata/test/jupyterlab/settings.test.ts`。

thanks for your advice

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.6.x

**Pull request merged**
