### PR TITLE
Fix border-radius does not follow css variable

### LINKED ISSUE #13288: some border-radius does not follow css variable
## Description

Some css definition does not follow css variable

## Reproduce

1. Go to 'Settings'
2. Click on 'Settings Editor'
3. Scroll down to `Input`
4. See the border radius does not follow the css variable `--jp-border-radius`

image

## Expected behavior

the border radius follow the css variable `--jp-border-radius`

## Context

https://github.com/jupyterlab/jupyterlab/blob/70fdbd5ab3e8687cbb03f21f3b5142d15319c03a/packages/settingeditor/style/base.css#L214

there are some other packages' border-radius does not follow css variables too

### PR DESCRIPTION
**Pull request by vthinkxie**
fix #13288

## User-facing changes

Before
image

After
image

### CODE REVIEW

**Review by fcollonval — COMMENTED** [review]
Thanks @vthinkxie 

Would you mind providing a screenshot before/after?

**Comment by vthinkxie** [comment]
> Thanks @vthinkxie
> 
> Would you mind providing a screenshot before/after?

sure, I just add the screenshot in the PR description

**Review by fcollonval — APPROVED** [review]
Thanks @vthinkxie

**Comment by fcollonval** [comment]
CI failure is not related

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.6.x

**Pull request merged**
