### PR TITLE
Update to Playwright 1.26

### PR DESCRIPTION
**Pull request by jtpio**
## References

As noticed in https://github.com/jupyter/notebook/pull/6533#issuecomment-1235566388, overriding `appPath` in a custom downstream config does not seem possible anymore with newer versions of Playwright.

This seems related to the Playwright 1.18.0 release which introduced breaking changes to the configuration options: https://github.com/microsoft/playwright/releases/tag/v1.18.0

## Code changes

- [x] Bump to the latest version of Playwright
- [x] Use `{ option: true }` as suggested in the playwright release notes to make a fixture parametrized in the config file

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Review by fcollonval — APPROVED** [review]
Thanks @jtpio

**Comment by fcollonval** [comment]
The visual regression seems legit. The link underline is not exactly the same:

image
image

I guess this is a consequence of the newer browser version.

**Comment by fcollonval** [comment]
bot please update galata snapshots

**Comment by jtpio** [comment]
CI all green now, thanks @fcollonval.

**Comment by jtpio** [comment]
> CI all green now, thanks @fcollonval.

Ah actually looks like the checks were not triggered:

image

Gonna kick the CI now.

**Comment by jtpio** [comment]
All good now.

**Pull request merged**
