### PR TITLE
More license updates

### PR DESCRIPTION
**Pull request by bollwyvl**
[![binder-badge]][binder]

[binder-badge]: https://mybinder.org/badge_logo.svg
[binder]:
  https://mybinder.org/v2/gh/bollwyvl/jupyterlab-meta/more-license-work?urlpath=lab/tree/README.md

## References

- follow-on of #9519

## Code changes

- [x] bumps root `LICENSE` year... [happy early lunar new year :dragon: :fireworks:](https://www.google.com/search?&q=lunar+new+year)
- [x] removes extra per-package licenses
  - `lerna publish` picks them up instead of the root license, it's just another thing to keep in sync
  - we don't have any forks of anything in here, so otherwise should just demand it complies with the main license
- [x] bump to federated module-aware `license-webpack-plugin@2.3.12`
- [x] make license choices into a custom plugin in builder
  - [x] keep the file name in one place
  - [x] emit JSON instead of txt
    - this is _roughly_ informed by the [SPDX schema](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/schemas/spdx-schema.json), but it doesn't really meet our needs as a primary source
      - however, SPDX might be a useful report format
  - [x] use everywhere
- [ ] figure out what to do about license report TS types
  - [x] for now, duplicated in `@jupyterlab/builder` and `@jupyterlab/help` :pouting_cat: 
  - [ ] better would probably be a new package, e.g. `@jupyterlab/builder-types`, but :sleepy: 

### Moved to https://github.com/jupyterlab/jupyterlab_server/pull/161
- [x] add a `jupyter lab licenses` CLI which spits out markdown
  - [x] `--json`
  - [x] `--csv`
  - [x] `--full-text` also includes the full license text 
  - [x] `--bundle` regex to limit whether it's just core, or everything
- [x] add a `lab/api/licenses` route
  - [x] lazily find all the `third-party-licenses.txt` (or hopefully JSON)
  - [x] spit them out as a JSON blob
  - [x] offer some params, e.g. `format=markdown`, `bundles=.*`, `full_text=0`

## User-facing changes

- adds a _Help &raquo; Licenses_
  - [x] basic SplitPanel with a TabBar, DataGrid and plain-old-HTML viewer <br/>  Screenshot from 2021-02-22 16-33-46
  - [x] add report downloads to toolbar <br/> 
Screenshot from 2021-02-28 23-28-00

## Backwards-incompatible changes

n/a unless:
- someone was refering to the translation licenses
- someone used `third-party-licenses.txt` from the `a1` release

### CODE REVIEW

**Comment by bollwyvl** [comment]
Actually, in looking at the API route: it's possible to get the raw JSON back out of the license webpack, so `third-party-licenes.json`. I'm thinking we should probably just generate that, forgoing any template, as it would be more useful for every use case _except_ perhaps generating the license report. To that end, since it's now touching the python side of the house, the `LicensesManager` could also drive a CLI:

```
jupyter lab licenses
```

shows all the licenses

```
jupyter lab liceneses @some/extension @some/other-extensioin-*
```

shows just those licenes.

Also, with the JSON, it might make more sense to use a DataGrid...

**Comment by bollwyvl** [comment]
Gah, so I'm in that spot again where the `@jupyterlab/builder` gets pulled from npmjs, and not the local copy... can't remember what i did to make it work...

**Comment by bollwyvl** [comment]
So this is getting pretty good for `dev_mode`... about the only thing to add might be the version of the bundle e.g. `@jupyterlab/top`, itself. And tests, of course!

I also had started with a schema, but didn't find anywhere else that python side of the house used schema, so I've backed that off... but it's probably worth doing at some point.

As this has already gotten to be a rather fat PR (and tests will increase its girth), it might make sense to do the client piece, `@jupyterlab/licenses-extension` in a separate PR. Given that the very first bundle has >200 rows in it, I am more convinced a DataGrid is the right way to go... it can also offer the raw download of the various report formats (JSON, CSV, Markdown).

**Comment by bollwyvl** [comment]
Another question is whether the routes, manager, etc. belong in `jupyterlab_server`... this seems like a thing that a Lab-adjacent app would probably want, and all the federated extension code/types are defined over there anyway...

**Comment by goanpeca** [comment]
Hi @bollwyvl. Is this ready for another round of reviews?

Also needs a rebase.

Thanks!

**Comment by blink1073** [comment]
Thanks Nick, I'll take a lot at both PRs next week.  Have a good weekend!

**Review by blink1073 — APPROVED** [review]
Very nice, thank you!

**Comment by blink1073** [comment]
Looks like this need a lint pass.  The `release_check` job will fail until we make a new alpha release, which I will do immediately after merging this PR.

**Comment by bollwyvl** [comment]
I missed one last warning `yadda yadda is missing a return annotation` on the new file, but figure i'll wait to see if i broke anything else...

**Comment by blink1073** [comment]
Thanks again!  I'm cutting an alpha with this now.

**Comment by blink1073** [comment]
https://github.com/jupyterlab/jupyterlab/releases/tag/v3.1.0a11

**Comment by bollwyvl** [comment]
conda-forge PR in 5... 4... 3... https://github.com/conda-forge/jupyterlab-feedstock/pull/279

**Pull request merged**
