### PR TITLE
Align search icon in filter box

### LINKED ISSUE #14249: "Filter files" search icon is not vertically centered
In the file browser, the search icon beside "filter files by name" is aligned closer to the top of the containing box. It should be centered within the box.

Screen Shot 2023-03-20 at 3 07 27 PM

## Context

- Operating System and version: Chrome Version 110.0.5481.177 (Official Build) (x86_64)
- Browser and version: macOS
- JupyterLab version: 4.0.0a37

### PR DESCRIPTION
**Pull request by bikash30851**
## References

Fixes #14249

## Code changes

<p> Kept the search icon inside a flexbox and centered the icon with justify-content center and align-items center</p>

## Backwards-incompatible changes

---
[fcollonval] Edit to link associated issue.

### CODE REVIEW

**Review by fcollonval — CHANGES_REQUESTED** [review]
Thanks @bikash30851 

It does not seem to solve the issue:

| Before | After |
| --- | --- |
| Before | image |

Switching `top: 0;` by `bottom: 1px` seems to do the trick.

> Small GitHub tip, when creating a PR I recommend you to use  [special keyword](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) to automatically linked an issue with the PR.

**Comment by bikash30851** [comment]
@fcollonval Thank you for pointing that out and for the tip. 

I have made the change that you suggested. 

Please let me know if I could assist with anything else.

**Review by fcollonval — COMMENTED** [review]
Thanks @bikash30851 

FYI as the style is impacting integration tests are failing. So I'm gonna trigger a bot action to update the reference screenshots to fix them. The new snapshots will be pushed to your branch with new commits.

**Comment by fcollonval** [comment]
bot please update snapshots

**Comment by fcollonval** [comment]
Kicking the CI

**Comment by bikash30851** [comment]
Is there anything I could do to help with the testing?

**Review by krassowski — APPROVED** [review]
Thank you @bikash30851

**Comment by fcollonval** [comment]
> CI failure are not related

**Pull request merged**
