### PR TITLE
Revert name file feature

### PR DESCRIPTION
**Pull request by jess-x**
## References
Reverts https://github.com/jupyterlab/jupyterlab/pull/10043 as there has not been a stable solution
per discussion https://github.com/jupyterlab/jupyterlab/pull/10594#issuecomment-878478854

## Code changes

- Deleted changes introduced in https://github.com/jupyterlab/jupyterlab/pull/10043

## User-facing changes
- Name file feature is removed

## Backwards-incompatible changes

- Removed the `renamed` attribute from public API

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thank you for working on this feature!  Sorry we had to bump it to next release

**Comment by blink1073** [comment]
Ah, it looks like there are 2 images that need to be updated for the  [visual regression tests](https://github.com/jupyterlab/jupyterlab/pull/10609/checks?check_run_id=3049761265)

**Comment by jess-x** [comment]
Oh I see, I think it's the image of opened-menu needed to be updated. I am not sure how though.

**Comment by blink1073** [comment]
You can replace the existing images with the ones in the `screenshots` directory you get when you download and open the `ui-test-output.zip` file.

**Comment by jess-x** [comment]
@blink1073, I just replaced the images, sorry that took longer because I forgot to clean up the schema

**Comment by blink1073** [comment]
Failure is related to in-progress beta release, let's proceed so we can get #9488 finished

**Comment by jess-x** [comment]
Thank you for the patience :)

**Pull request merged**
