### PR TITLE
Upload notebooks as regular files

### LINKED ISSUE #5059: Cannot upload .ipynb file > 15 MB with JupyterLab 0.33.6 whereas it works with Jupyter 5.6.0
Dear Team,

Our users warned us on a limitation related to .ipynb file uploads : they can't upload .ipynb files larger than 15 MB.

screenshot from 2018-08-06 17-30-27

We did some tests on our side and we discovered that : 
- JupyterLab **0.33.6** supports upload of files (not .ipynb) > **15 MB**
- Jupyter **5.6.0** supports upload of all files (including .ipynb) > **15 MB**

It seems that the limitation is caused by the code below : 
https://github.com/jupyterlab/jupyterlab/blob/f87028deb9c9fee0591f95ddc81a5ed1fea2ab45/packages/filebrowser/src/model.ts#L380

Can you help sorting out this issue ?

Best Regards,
Mike

### PR DESCRIPTION
**Pull request by saulshanabrook**
fixes #5059

### CODE REVIEW

**Comment by blink1073** [comment]
Test failures look legitimate:

```
lerna ERR! FAILED TESTS:
lerna ERR!   filebrowser/model
lerna ERR!     FileBrowserModel
lerna ERR!       #upload()
lerna ERR!         newer notebook version
lerna ERR!           ✖ should upload a large .ipynb file of size 1048575
lerna ERR!             HeadlessChrome 0.0.0 (Linux 0.0.0)
lerna ERR!           Error: Invalid response: 400 Bad Request
lerna ERR!               at __1.ServerConnection.makeRequest.then.response (webpack:////home/travis/build/jupyterlab/jupyterlab/packages/services/lib/contents/index.js?:460:23)
lerna ERR! 
lerna ERR!           ✖ should upload a large .ipynb file of size 1048576
lerna ERR!             HeadlessChrome 0.0.0 (Linux 0.0.0)
lerna ERR!           Error: Invalid response: 400 Bad Request
lerna ERR!               at __1.ServerConnection.makeRequest.then.response (webpack:////home/travis/build/jupyterlab/jupyterlab/packages/services/lib/contents/index.js?:460:23)
lerna ERR! 
lerna ERR!           ✖ should upload a large .ipynb file of size 1048577
lerna ERR!             HeadlessChrome 0.0.0 (Linux 0.0.0)
lerna ERR!           Error: Invalid response: 400 Bad Request
lerna ERR!               at __1.ServerConnection.makeRequest.then.response (webpack:////home/travis/build/jupyterlab/jupyterlab/packages/services/lib/contents/index.js?:460:23)
lerna ERR! 
lerna ERR!           ✖ should upload a large .ipynb file of size 2097152
lerna ERR!             HeadlessChrome 0.0.0 (Linux 0.0.0)
lerna ERR!           Error: Invalid response: 400 Bad Request
```

**Comment by saulshanabrook** [comment]
OK this *should* pass now.

I also changed it the upload from doing manual base64 encoding to using `FileReader.readAsDataURL`.

**Comment by saulshanabrook** [comment]
I tested this locally on a 90MB notebook and it worked (thanks to https://github.com/jupyterlab/jupyterlab-statusbar you can actually see the progress).

**Comment by saulshanabrook** [comment]
This should also close https://github.com/jupyterlab/jupyterlab/issues/5038, I tried the attached file there and it uploads properly for me.

**Comment by blink1073** [comment]
Works great, thanks!  I do love a net negative line change...

**Pull request merged**
