### PR TITLE
Change IRunningItem to expect ILabIcon instead of LabIcon

### LINKED ISSUE #7956: Should IRunningItem require LabIcon?
It seems the `IRunningItem` demanding a concrete `LabIcon` is a bit of an impedance mismatch, and may make it less portable to alternate implementations, if that's the intent of there being a `ILabIcon` in the first place...

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- fixes #7956
  - if it even needs fixing...

## Code changes

One `I`!

## User-facing changes

None

## Backwards-incompatible changes

Probably not any.

### CODE REVIEW

**Comment by blink1073** [comment]
cc @telamonian.  We would need to make `.react` a property of `LabIcon.ILabIcon` for this to work, does that seem reasonable?

**Comment by telamonian** [comment]
I need to think about/investigate this a little bit.

> We would need to make `.react` a property of `LabIcon.ILabIcon` for this to work, does that seem reasonable?

Kind of? But not entirely. For the abstract interface I think it might make more sense to have a more generic `.jsx` property instead (for one thing, I'd like LabIcon to eventually play nicely with the [lumino jsx from @lumino/vdom](https://github.com/jupyterlab/lumino/pull/45)). I haven't worked through all of the implications yet.

Honestly I was hoping to put off the next round of refinements to LabIcon's typings/interfaces until we actually start working on the 3.0 branch. I'm also not super familiar with IRunningItem. Is this a critical mis-typing (like the issue with IRenderMime)?

**Comment by jasongrout** [comment]
Sounds like this is more involved than a patch release? Taking off 2.0 and pushing to at least 2.1, though @telamonian may want to push it to 3.0, it sounds like.

**Comment by blink1073** [comment]
@telamonian will you be able to look at this for 3.0?

**Pull request closed without merging**
