### PR TITLE
Run Python tests on MacOS with Python 12, replace `canvas` with `jest-canvas-mock`

### PR DESCRIPTION
**Pull request by krassowski**
## References

- Runs some of the MacOS tests with Python 3.12 to reproduce and tests against https://github.com/jupyterlab/jupyterlab/issues/16311
- Replaces `canvas` with `jest-canvas-mock` to fix https://github.com/jupyterlab/jupyterlab/issues/16311 by getting rid of the compilation requirement

## Code changes

None

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by krassowski** [comment]
It looks like vega5 needs it to. Should we just add it to @jupyterlab/testing package or is there value in only having this in individual packages?

**Comment by krassowski** [comment]
@ericsnekbytes you may want to try out this branch - it is passing on CI already

**Comment by ericsnekbytes** [comment]
@krassowski Just built this locally and it worked :) Thanks for your work on this!

**Comment by krassowski** [comment]
Great! Can you tick the "Approve" on GitHub review just so that it does not show up as unreviewed later?

**Review by ericsnekbytes — APPROVED** [review]
Successfully tested this locally.

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.2.x to address https://github.com/jupyterlab/jupyterlab/issues/16415

**Comment by krassowski** [comment]
@meeseeksdev please backport to 4.2.x

**Comment by krassowski** [comment]
Backporting to 3.6.x too because currently the CI is failing completely as seen in https://github.com/jupyterlab/jupyterlab/pull/16463

@meeseeksdev please backport to 3.6.x

**Pull request merged**
