### PR TITLE
Restore padding on main dock panel

### LINKED ISSUE #10387: Visual regression: border of the main area shrank
## Description

The main area border is now smaller which looks less appealing and strange. <s>My hunch is that this is caused by #10127</s>.

## Reproduce

**Before (stable):**

Screenshot from 2021-06-11 11-50-39

**After (master):**

Screenshot from 2021-06-11 13-07-44

## Expected behavior

The visuals are restored.

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fixes #10387 

## Code changes

N/A

## User-facing changes

Restore 5px padding on main dock panel

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Comment by fcollonval** [comment]
Before:



After:

| Multiple document | Single document |
| --- | --- |
| image | image
 |

UI are expected to fail.

Stable version



> Credit for capture goes to @krassowski

**Comment by goanpeca** [comment]
>ui-tests/reference-output/screenshots/general_dark_theme.png

Should we declare these files as binary to avoid having to diff and any conflicts in the future?

**Comment by fcollonval** [comment]
> Should we declare these files as binary (gitignore)to avoid having to diff and any conflicts in the future?

I'm not sure. If there are conflicts, this means they have been changed on master. So the PR needs to be rebased else UI tests wil fail when merging, no?

**Comment by krassowski** [comment]
Diffing them via the GitHub interface is delightful by the way:


diff-github

I think we should continue reviewing them. Which brings me to a questions: @fcollonval do you happen to have ipykernel prerelease installed or was it picked up somewhere else?

**Comment by fcollonval** [comment]
> do you happen to have ipykernel prerelease installed or was it picked up somewhere else?

Jeremy switch the CI to use the pre-release of ipykernel to test the debugger: https://github.com/jupyterlab/jupyterlab/pull/10359/files#r649835430

**Comment by jtpio** [comment]
Yes updating to the `ipykernel` prerelease in that PR introduced a couple of visual changes.

From https://github.com/jupyterlab/jupyterlab/pull/10359#issuecomment-859448661:

image

**Comment by jtpio** [comment]
> I guess I am not sure how the process is currently working for the UI tests,

@goanpeca there are some instructions in https://github.com/jupyterlab/jupyterlab/tree/master/ui-tests and https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#visual-regression-and-ui-tests.

Usually we don't need to modify the reference screenshots unless there is an intentional visual change a PR wants to bring.

This PR fixes a regression that was not caught at the time because the visual regression tests were not in place yet.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Pull request merged**
