### PR TITLE
lazy load of vim mode

### PR DESCRIPTION
**Pull request by ibdafna**
## References

This PR implements issue #6511, lazy load of vim mode.

Thank you @blink1073 for pointing out where in the code this should be implemented.

**Important:** I had to add a basic vim.d.ts type declaration type file to the node_modules/@types/codemirror/keymap folder as jlpm wouldn't compile otherwise. The compiling issue only happens when the conditional `import('xyz)` command is used. Regular `import 'xyz'` gives this warning but does not cause any compiling issues.

## Code changes

vim.js is now only loaded when vim mode is selected.

## User-facing changes

No visual changes.

## Backwards-incompatible changes

None that I can see.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
cc @jwkvam

**Comment by blink1073** [comment]
You should be able to use `// @ts-ignore` before the import line.

**Comment by ibdafna** [comment]
> You should be able to use `// @ts-ignore` before the import line.

@blink1073 Thanks! Will implement and update.

**Comment by ibdafna** [comment]
Should I add `.done()` to the `import()` command to get rid of the ESLint error, or would you suggest other refactoring?

**Comment by blink1073** [comment]
Ah, it needs to be `void import ()` to show that we purposely ignore the promise.

**Comment by jwkvam** [comment]
Thanks for the heads up!

**Comment by ian-r-rose** [comment]
@jwkvam I don't think this should cause any issues with `jupyterlab_vim`, but it's worth keeping an eye on.

**Comment by blink1073** [comment]
I kicked the Usage test, but it was unrelated.

**Comment by blink1073** [comment]
Thanks again @ibdafna!

**Pull request merged**
