### PR TITLE
Remove unused IRouter dependency from the hub extension

### PR DESCRIPTION
**Pull request by jtpio**
## Code changes

Removed the dependency on `IRouter` for the hub extension as it doesn't appear to be used.

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Actually the router could be used to navigate to `/logout` instead of:

https://github.com/jupyterlab/jupyterlab/blob/23755988bb1e15ec8473ea6b241735bbd1a9ac9a/packages/hub-extension/src/index.ts#L86

**Comment by jasongrout** [comment]
> Actually the router could be used to navigate to `/logout` instead of:

We don't need the base url?

**Comment by jtpio** [comment]
I think the redirect takes care of it: https://github.com/jupyterhub/jupyterhub/blob/72a38a599d3c623177fa0bb850ca47e5444f31ee/jupyterhub/singleuser.py#L116-L122

Otherwise yes we could still use the base url.

**Comment by jtpio** [comment]
Happy to leave it as it is (removing the dependency on `IRouter`).

This is ready to go.

**Pull request merged**
