### PR TITLE
Load theme as extension

### LINKED ISSUE #2165: Split default-theme into multiple packages
We have a `default-theme` that contains the theme assets (icons, images), and light/dark theme CSS variables. This layout is going to make is really difficult to build custom themes. We should split it into packages:

* `theme-assets` = everything but the variables.css
* `theme-light` = the light theme
* `theme-dark` = the dark theme

@blink1073 I am thinking we should also have each individual package throw its CSS on the page separately?

### PR DESCRIPTION
**Pull request by ellisonbg**
Split out `default-theme` into `theme-assets` and `theme-light-extension` and load it as an extension. Fixed #2165 and replaces #2169

### CODE REVIEW

**Comment by ellisonbg** [comment]
I will try to rebase this, but working on some code review first...

**Comment by ellisonbg** [comment]
I have this rebased and mostly working, but there remain some questions/issues:

* Some files in the theme-assets package are not being loaded (svgs) onto the page.
* Right now I am still doing an explicit `require('@jupyterlab/theme-assets/style/index.css');` index.js of jupyterlab. Should the CSS of the `theme-assets` npm package be imported somewhere else (like in application?). Or should it be an extension and import its own CSS?

@blink1073 would love to chat in the morning about these few things...

**Comment by blink1073** [comment]
I think the theme itself should import those assets.

**Comment by blink1073** [comment]
I've be available starting at 9:45 Pacific to chat.

**Comment by blink1073** [comment]
Both of the new extensions should have the `jupyterlab: extension: true` metadata in their `package.json` for consistency.

**Comment by ellisonbg** [comment]
@blink1073 @jasongrout OK I think this is ready for review and merge. It does a couple of things:

* Separates the theme into multiple packages: 1) `theme-assets` is a pure NPM package with just the theme assets (images/icons) and 2) `theme-light-extension` which is a Jlab extension that imports the theme assets and has only the CSS variables for the theme.
* Fixes other build related things in master causing images not to show up.
* I have also separated out the dark theme as an extension, but it is not really working yet.

One this is merged I will open issues to track the next steps:

* Get the dark theme working again.
* Adding ability for a user to change themes easily.

**Comment by blink1073** [comment]
I noticed that the examples needed to be updated, which led to the discovery that they must now explicitly import styles from `@jupyterlab/application`, even the ones that are not using the application.  We end up with the following imports to get what we have before in `default-theme`:

```
import '@jupyterlab/theme-assets/style/index.css';
import '@jupyterlab/theme-light-extension/style/index.css';
import '@jupyterlab/application/style/index.css';
```

It also seems odd to import from an extension in the examples, since they are not applications.
What if we had a `theming` package which included the assets, the CSS that is currently in application, and the light/dark theme definitions (but not the extensions).   Then the examples could import from the theming package.

**Comment by blink1073** [comment]
Rebased and continued in https://github.com/jupyterlab/jupyterlab/pull/2283.

**Pull request closed without merging**
