### PR TITLE
Do not fail on deduplicate and ignore optional

### PR DESCRIPTION
**Pull request by blink1073**
## References
cf https://github.com/jupyterlab/jupyterlab/issues/6974 

## Code changes
Ignore optional deps and do not fail if there are any duplicate packages in yarn-dedupe.

## User-facing changes
Less scary-looking messages about node-gyp.

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by blink1073** [comment]
cc @vidartf

**Comment by vidartf** [comment]
Xref previous ignore optional discussion here: https://github.com/jupyterlab/jupyterlab/issues/7003

The dedupe fix LGTM. Should the yarn.lock in staging be regenerated without the optional dependencies?

**Comment by blink1073** [comment]
Sounds good.  My dev setup is currently broken.  I'm going to spend this morning putting Linux on my laptop.

**Comment by blink1073** [comment]
Let's save the manual dedupe for a follow-up, so we can backport this.

**Comment by blink1073** [comment]
@meeseeksdev backport to 1.0.x

**Pull request merged**
