### PR TITLE
Fix dotted extension lookup

### PR DESCRIPTION
**Pull request by blink1073**
cf https://github.com/jupyterlab/jupyterlab/issues/1453#issuecomment-274947397.

### CODE REVIEW

**Comment by gnestor** [comment]
This PR broke doc rendering for extensions!!

**Comment by blink1073** [comment]
I'll fix this in the morning.

**Comment by gnestor** [comment]
👌

**Comment by blink1073** [comment]
Here's what I'm seeing locally running master of JupyterLab, geojson, table, and json.  It looks like maybe the table and json renderers have conflicting versions of React?

image

**Comment by blink1073** [comment]
I had used the example table schema data from here: http://frictionlessdata.io/guides/json-table-schema/

**Comment by gnestor** [comment]
The spec has changed slightly, see https://github.com/gnestor/jupyterlab_table/blob/master/jupyterlab_table/__init__.py#L34-L41. Here's an example you can use for testing:

```json
{
	"resources": [{
		"schema": {
			"fields": [{
					"type": "any",
					"name": "Date"
				},
				{
					"type": "number",
					"name": "Open"
				},
				{
					"type": "number",
					"name": "High"
				},
				{
					"type": "number",
					"name": "Low"
				},
				{
					"type": "number",
					"name": "Close"
				},
				{
					"type": "integer",
					"name": "Volume"
				},
				{
					"type": "number",
					"name": "Adj Close"
				}
			]
		},
		"data": [{
				"Date": "2000-03-01",
				"Adj Close": 33.68,
				"Open": 89.62,
				"Low": 88.94,
				"Volume": 106889800,
				"High": 94.09,
				"Close": 90.81
			},
			{
				"Date": "2000-03-02",
				"Adj Close": 34.63,
				"Open": 91.81,
				"Low": 91.12,
				"Volume": 106932600,
				"High": 95.37,
				"Close": 93.37
			}
		]
	}]
}
```

**Comment by blink1073** [comment]
Works for me now with that example.

**Comment by blink1073** [comment]
I can open the `.table.json` file with an Editor, JSON, or Table viewer, and the default is the Table.

**Comment by gnestor** [comment]
Ok, then something must be screwy with my local install... 🤔

**Comment by gnestor** [comment]
...and all of my labextensions got wiped! That explains it 👍

**Pull request merged**
