### PR TITLE
Fix UI tests

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Some UI tests are failing recently. This fixes the documentation broken due to a change in the underlying renderered map. And update the two tests waiting for the kernel indicator to be idle before comparing snapshots.

## Code changes

None

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by bollwyvl** [comment]
Look at that alley!

But seriously: why even keep that under screenshot test? It's basically guaranteed to break again. Seems like blanking out that DOM before the screenshot would be a lot more stable.

**Comment by bollwyvl** [comment]
Some other options:
- apply a heavy [gaussian blur](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/blur) to the map elements. 
- ship a set of custom tiles with the tests
  - this would likely be the most robust

**Comment by fcollonval** [comment]
bot please udpate documentation snapshots

**Comment by fcollonval** [comment]
bot please update documentation snapshots

**Comment by fcollonval** [comment]
bot please update documentation snapshots

**Pull request merged**
