### PR TITLE
Update metadata recorded to align better with jupyter protocol

### PR DESCRIPTION
**Pull request by mlucool**
This enables more kernel types to have their metadata recorded. Specifically, R and Julia did not match the same metadata as IPyKernel and the 5.0 spec did not require date in the header.

## References

Fixes: deshaw/jupyterlab-execute-time#14

## Code changes

Default dates to now for messages that do not have dates set in the header. No longer requires non-spec metadata.

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by jasongrout — APPROVED** [review]
Thanks, this looks good.

**Comment by mlucool** [comment]
@meeseeksdev backport to 2.3.x

**Comment by mlucool** [comment]
@jasongrout can you backport this for me?

**Comment by jasongrout** [comment]
@meeseeksdev backport to 2.2.x

**Pull request merged**
