### PR TITLE
Use an absolute URL for the logo.

### LINKED ISSUE #4232: Jupyter Logo Not Working for all Latest RTD
Homepage:

screen shot 2018-03-23 at 17 13 08

versus other page:

screen shot 2018-03-23 at 17 13 17

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes #4232

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Pinging @jasongrout for a look.

**Comment by ian-r-rose** [comment]
image

**Comment by ian-r-rose** [comment]
I kept the initial name as "Docs", as when I tried "JupyterLab" it seemed pretty redundant, and "JupyterLab Documentation" was really busy.

It's unfortunate that I had to copy-paste such a large block of the template, but I didn't see a way around that.

**Comment by jasongrout** [comment]
Thanks. I was thinking the breadcrumbs could be `Jupyter >> JupyterLab >> Interface` or something.

**Comment by jasongrout** [comment]
But I'm okay with merging this and iterating on it in the future.

**Comment by ian-r-rose** [comment]
Visually, it looked like a lot to me: we had `Jupyter*` at least four times across the top of the page.

**Comment by jasongrout** [comment]
Good point. We could do `Jupyter >> Lab >> Interface` ... I don't think we've used "Lab" by itself, though.

Again, let's iterate on the design in the future.

**Pull request merged**
