### PR TITLE
Fix watch mode

### PR DESCRIPTION
**Pull request by blink1073**
Our previous iteration was interfering with node module resolution.  We noticed this because the [vega3-extension](https://github.com/jupyterlab/jupyter-renderers/pull/15) was depending on an incompatible version of `vega-embed`, but ended up with the version used by the `vega2-extension` because it was in `staging/node_modules/vega-embed`.

cc @gnestor

### CODE REVIEW

**Comment by blink1073** [comment]
cc @bollwyvl

**Comment by gnestor** [comment]
It seems to be working for me. I'm still having trouble rendering vega3 but I can see that it's now using vega-embed 3 vs. 2 👍

Is there a reason why vega-embed is a top-level dependency in jupyterlab app? https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/package.json#L72-L77 

Is it used outside of vega2-extension? Or is it just because of the issue with vega-embed 2 where the app consuming it has to add its dependencies?

**Comment by blink1073** [comment]
The intent of having those there is to have a single spot to look for what dependencies JupyterLab core is using for extension authors.   There was actually a bug where we were only adding the deps for extensions and not all of the Jlab packages (fixed in 56fd3e0).  

From the [extensions_dev](https://github.com/jupyterlab/jupyterlab/blob/c44e12d4fc71ed5fb8d322503b8a4e847f4a1105/docs/extensions_dev.md) docs: " If your extension depends on JupyterLab packages, it should be compatible with the dependencies in the jupyterlab/package.app.json file."

**Comment by blink1073** [comment]
Perhaps that is too far and we should only include the singleton packages and the JupyterLab packages?

**Comment by blink1073** [comment]
Yeah I'm leaning toward that approach.

**Pull request merged**
