### PR TITLE
Update to TypeScript 4.9

### PR DESCRIPTION
**Pull request by jtpio**
## References

See the announcement blog post: https://devblogs.microsoft.com/typescript/announcing-typescript-4-8

## Code changes

- [x] Update `typescript` to `4.9`
- [x] Fix some typings
- [x] Update `@codemirror` packages
- [x] Update `vega-lite` to a new release so it includes https://github.com/vega/vega-lite/pull/8473
- [x] Update more dependencies?

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Currently failing to build `@jupyterlab/galata` with:

```
 ../node_modules/vega-lite/build/src/channeldef.d.ts(63,66): error TS2344: Type 'T' does not satisfy the constraint 'SignalRef | ExprRef | FieldDef<any, any> | DatumDef<string, SignalRef | DateTime | ExprRef | PrimitiveValue> | ValueDef<...>'.
    Type 'T' is not assignable to type 'DatumDef<string, SignalRef | DateTime | ExprRef | PrimitiveValue>'.
  ../node_modules/vega-lite/build/src/channeldef.d.ts(63,97): error TS2344: Type 'T' does not satisfy the constraint 'SignalRef | ExprRef | FieldDef<any, any> | DatumDef<string, SignalRef | DateTime | ExprRef | PrimitiveValue> | ValueDef<...>'.
```

**Comment by jtpio** [comment]
> Currently failing to build `@jupyterlab/galata` with:

cc @fcollonval as this looks related to the use of `vega-lite` to generate the benchmark reports.

**Comment by fcollonval** [comment]
I opened https://github.com/vega/vega-lite/issues/8465

**Comment by jtpio** [comment]
We're still waiting for https://github.com/vega/vega-lite/pull/8473.

In the meantime TS 4.9 was released: https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/

We can probably update to 4.9 directly in this PR after rebasing and fixing the conflicts.

**Comment by jtpio** [comment]
Just updated to 4.9.

Maybe we should try to find a way to move forward with this since https://github.com/vega/vega-lite/pull/8473 hasn't been merged yet.

**Comment by fcollonval** [comment]
Unfortunately all documentation I can find on the internet are mentioning that it is not possible to override type definition.

**Comment by fcollonval** [comment]
We could also take this as an opportunity to move the `vega-extension`, `vdom` and `vdom-extension` to the [jupyter-renderers](https://github.com/jupyterlab/jupyter-renderers) as there are no reason we should favor shipping those formats by default.

A good addition doing that could be then to use the new notification system to inform a user, he can install an additional package for better outputs if we detect a output with the related mimetype.

**Comment by jtpio** [comment]
I think it's only the use in the galata package that is causing problems.

`vega5-extension`builds fine:

image

**Comment by jtpio** [comment]
> `vega5-extension` is using `skipLibCheck` disappointed

oh wow I thought we had `"skipLibCheck": false` everywhere in the code base.

I can confirm this then fails to compile when disabling the option:

image

**Comment by jtpio** [comment]
> `vega5-extension` is using `skipLibCheck` disappointed

This seems to have been there for a long time according to the git history: https://github.com/jupyterlab/jupyterlab/commit/4029c1336bdf17f7074f36f6c5a1303520234e2d

> Typscript 3.7 throws some errors when compiling Vega-lite 2 and 3, so we turn off lib checks.

> This was investigated much more deeply in https://github.com/jupyterlab/jupyterlab/pull/7428, where we deleted the vega 4 extension and upgraded the vega 5 extension to vega-lite 4.0b11. The vega-lite upgrade was not going smoothly, so we moved it to a separate issue and redid the Typescript upgrade by just using the skipLibCheck flag.

**Comment by jtpio** [comment]
Pushing a commit with `"skipLibCheck": true` for now (https://github.com/jupyterlab/jupyterlab/pull/13028/commits/b7fc8a3585f3491e7afcb833e69f197d36d7921b), so we can make progress and see there is anything else to do to perform this update.

**Comment by jtpio** [comment]
Also opened https://github.com/jupyterlab/jupyterlab/issues/13525 to track the removal of `skipLibCheck` in existing packages.

**Comment by jtpio** [comment]
Looks like https://github.com/vega/vega-lite/pull/8473 just got merged :tada: 

I'll update this PR with the vega-lite pre-release and remove the `skipLibCheck`.

**Comment by jtpio** [comment]
bot please update snapshots

**Comment by jtpio** [comment]
Just squashed everything into 1 commit to make future (if neeed) rebases easier.

**Comment by jtpio** [comment]
TypeScript 5 is coming: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/

**Comment by jtpio** [comment]
I won't have the bandwidth to rebase and resume this PR over the coming week. So if anyone would like to step in and take over that would be greatly appreciated, thanks!

Maybe it would be easier to start over in a new PR to avoid the rebase, and cherry-pick the changes.

**Comment by jasongrout** [comment]
I submitted a quick PR at https://github.com/jupyterlab/jupyterlab/pull/13925 to look at upgrading to TS 5.0 beta. Thanks to all the work here, that PR was much easier!

**Comment by jtpio** [comment]
Closing in favor of https://github.com/jupyterlab/jupyterlab/pull/13925

**Pull request closed without merging**
