### PR TITLE
fix: Markdown cell generates duplicate toc content (#12312)

### LINKED ISSUE #12312: Markdown cell generates duplicate toc content
## Description

When editing in markdown cell， press several ENTERs in the content will generate duplicate titles
fe3f9598522b6946b3d1328111a30360

## Reproduce

1. open a .ipynb file
2. new a markdown cell
3. enter something
4. press ENTER or ENTERs

## Expected behavior

Produces the correct toc

## Context

- Operating System and its version: macOS 0.15.7

### PR DESCRIPTION
**Pull request by yangql176**
## References

Fixes #12312

## Code changes
image

Heading pushing should be When "line" is not empty, and if there is no heading, heading's text should be "line".  

## User-facing changes
before
fe3f9598522b6946b3d1328111a30360

after
image

## Backwards-incompatible changes

none

### CODE REVIEW

**Comment by fcollonval** [comment]
Thanks @yangql176 - this looks good but I would like the CI to be fixed (independent of this PR) just to be sure.

**Comment by yangql176** [comment]
> Thanks @yangql176 - this looks good but I would like the CI to be fixed (independent of this PR) just to be sure.

Sure！

**Comment by yangql176** [comment]
> Thanks @yangql176 - this looks good but I would like the CI to be fixed (independent of this PR) just to be sure.

error An unexpected error occurred: "https://registry.yarnpkg.com/@jupyterlab%2fapplication/-/application-4.0.0-alpha.8.tgz: Request failed \"404 Not Found\"".

This failed.

https://registry.yarnpkg.com/@jupyterlab/application/-/application-4.0.0-alpha.8.tgz
This would work.

**Comment by fcollonval** [comment]
Sorry @yangql176 I was a bit short in explanation. The errors are related to a failure when releasing a new alpha version based on the master branch. So there were nothing you could do about it. Now that they are fixed, I restarted your failing tests to check this PR is ok.

**Comment by yangql176** [comment]
> explanation

Sure!! Thanks!

**Review by fcollonval — APPROVED** [review]
Thanks @yangql176

**Comment by fcollonval** [comment]
@meeseeksdev please backport to 3.3.x

**Pull request merged**
