### PR TITLE
remove false Python2 support claim from README

### PR DESCRIPTION
**Pull request by ivanov**

### CODE REVIEW

**Comment by ivanov** [comment]
@blink1073's change back in #5119 is the August date that I'm referring to here.

**Comment by ivanov** [comment]
Re-pushed an ammended commit to say "Python 3.5 or higher is required" instead of just "Python 3.5" is required.

**Comment by jasongrout** [comment]
Thanks!

I noticed the bullets changed back to `*`. Was that a manual change, or a change from prettier?

**Comment by jasongrout** [comment]
In fact, do you want to just make it more succinct, and just say that we (i.e., currently) require Python 3.5 or higher, and not mention the date of the change?

**Comment by ivanov** [comment]
As far as the bullets, that certainly wasn't me (and I'm surprised that made it in there). Want me to take that out?

**Comment by blink1073** [comment]
IIRC this was a change in prettier.  Thanks for catching this @ivanov!

**Comment by jasongrout** [comment]
Looks like it's a prettier error: https://travis-ci.org/jupyterlab/jupyterlab/jobs/436304242#L695

Can you run lint and commit and push?

**Pull request merged**
