### PR TITLE
Upgrade `jlpm` cmd to yarn 3.x

### PR DESCRIPTION
**Pull request by telamonian**
I followed the migration guide, and suprisingly it mostly seems to work. Needs way more testing/poking at

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks for starting this!

Looks like there a couple of conflicts to fix for the CI to be triggered.

**Comment by telamonian** [comment]
up to 42/63 checks passing as of 4388e02. Woo!

**Comment by blink1073** [comment]
Needs another rebase from #10796

**Comment by telamonian** [comment]
> Needs another rebase from #10796

that's gonna happen a lot. Both `package.json` and `yarn.lock` underwent large scale formatting changes, so any other PR that touches either of those is going to trigger the need for yet another rebase (YAR?)

**Comment by blink1073** [comment]
YAR indeed.  Happy to merge this sooner than later to avoid the churn

**Comment by telamonian** [comment]
@blink1073 There's still a couple of chewy issues that probably boil down to pathing but aren't obvious how to fix:

1. win and mac tests fail at first run of `ensure-buildutils.js` (which happens as part of `pip install`), while linux tests run `ensure-buildutils.js` just fine
  - specifically, the first call to `npm run build` in the `buildutils` pkg (where the relevant script is `"build": "tsc"`) fails on win and mac
  - error:
    ```
           ➤ YN0000: │ @jupyterlab/repo-top@workspace:. STDERR sh: tsc: command not found
    ```

2. the "dynamic" installation of `playwright` that happens as part of `browser_check.py` is no longer producing a functional install
  - the existing code for this is here:
    https://github.com/jupyterlab/jupyterlab/blob/93c79b6e26bb982ee6ec66ec3e24d8839e68fba0/jupyterlab/browser_check.py#L147-L157
  - running a browser check will eventually result in: 
    ```
    Error: Cannot find module 'playwright'`
    ```
which is raised from a `require('playwright');` call in `browser_check.js`

**Comment by blink1073** [comment]
ACK, I can take a look but probably not until Tuesday

**Comment by telamonian** [comment]
I seem to have been able to fix the `tsc` bug by changing various scripts such as `"build": "tsc"` to `"build": "yarn run tsc"`. Similarly, I was able to fix the  `browser_check.py` bug by changing the subprocess call from `node ...` to `jlpm node ...`:

```python
await run_async_process(["jlpm", "node", "browser-test.js", url], cwd=target) 
```

**Comment by telamonian** [comment]
I've solved the issues above, but I've run into another major snag: `jupyter lab build` hangs the CI. It'll run for 30+ minutes and do nothing. I've tried adding the `--minimize=False` flag and a bunch of other tweaks, but it just doesn't work.

On the other hand, `jupyter lab build` runs just fine locally. Somehow it seems to be panicking the CI container

**Comment by telamonian** [comment]
> I've solved the issues above, but I've run into another major snag: `jupyter lab build` hangs the CI ...On the other hand, `jupyter lab build` runs just fine locally.

Okay, so I finally got to the bottom of the mysterious silent CI-only test failure. Turns out that Yarn v2.x+ sets some extra strict config ONLY in CI environments, not on the desktop, specifically:

```
➤ YN0000: enableImmutableInstalls       true
➤ YN0000: enableInlineBuilds            true
```

Immutable installs set to true means that `yarn.lock` files are not allowed to change when `yarn` or `yarn install` is run. The weird part is that that wasn't the error message, instead there was no error message, the `yarn install` command that runs as part of `jupyter lab build` simply hung for 30+ minutes.

Anyhow, setting the env var `YARN_ENABLE_IMMUTABLE_INSTALLS=0`, or just properly generating the `yarn.lock` file for the app dir so that running `jupyter lab build` doesn't cause any changes to said lockfile, fixes the issue

**Comment by telamonian** [comment]
I've now burnt down all of the test failures. All CI tests are now passing, aside from an unrelated issue that I've already posted a fix for (jupyterlab/jupyterlab_server#207).

So this is now technically working! Yaaay

**Comment by telamonian** [comment]
from @blink1073 on gitter:

> we shouldn't use `yarn` for any commands since a yarn executable could exist
> should be `jlpm run`

Basically, the issue is  whether we should use `foo: yarn run <bin>` or `foo: jlpm run <bin>` in our many, many `package.json` scripts. I've been thinking about this, and here's the pros and cons:

- `foo: yarn run <cmd>`:
  - pro:
    - if called as `yarn run foo`, the script can potentially still work even before `jlpm` is installed (which happens when `pip install jupyterlab` is first run)
  - con:
    - could potentially lead to `yarn` path/executable confusion
      - this is mostly mitigated by the `yarnPath` setting in the `.yarnrc.yml` and `jupyterlab/staging/.yarnrc.yml` config files
- `foo: jlpm run <cmd>`
  - pro:
    - (might?) help to ensure that the same yarn executable is called in all circumstances
  - con:
    - would create a restriction that `pip install .` has to be run before most `package.json` scripts
      - this restriction does not exist in current master for many top level packages such as `buildutils`

So I think really we could go either way with `yarn run` vs `jlpm run`. Guess I'll see what people think at the dev meeting this wednesday

**Pull request closed without merging**
