### PR TITLE
Update to `@jupyter/ydoc` v2.0.1

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/15951

## Code changes

- Bump to `@jupyter/ydoc@2.0.1`

## User-facing changes

Should be none.

## Backwards-incompatible changes

None according to https://github.com/jupyterlab/jupyterlab/issues/15951#issuecomment-1993797311

### CODE REVIEW

**Comment by jtpio** [comment]
Examples failure appears to be unrelated: https://github.com/jupyterlab/jupyterlab/issues/15985

UI tests failure too: https://github.com/jupyterlab/jupyterlab/issues/14947

**Comment by jtpio** [comment]
cc @davidbrochart it's looking good according to CI

**Review by krassowski — APPROVED** [review]
Thanks!

**Comment by davidbrochart** [comment]
I just saw that `jupyter-collaboration` still pins [@jupyter/ydoc ^1.1.0-a0](https://github.com/jupyterlab/jupyter-collaboration/blob/fab7f19be92adf7c0adb1e449da16419f9dafc5f/packages/collaboration-extension/package.json#L58), so this PR won't play well if we don't do the same in `jupyter-collaboration`, right?
I opened https://github.com/jupyterlab/jupyterlab/pull/15982.

**Pull request merged**
