### PR TITLE
Carry end-to-end tests on docker

### PR DESCRIPTION
**Pull request by fcollonval**
## Code changes

JupyterLab is installed on docker as a user would do.
That image is handled from another image containing galata.

This makes the setup independent of the CI or the local host. So reference can be generated locally.  
Moreover this uses a JupyterLab installation closer to the user installation.

> The only drawback seen for now is the rights on the created output files by galata. The umask has been set to 0000, so they can be removed by the host user. Unfortunately that mask is not applied on report assets copied from the galata package. Hence the user will need `sudo rm -rf` to remove the _report_ folder.

## User-facing changes

N/A

## Backwards-incompatible changes

N/A

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
LGTM, thanks!  I think we should wait for @mbektas or @jtpio to review as well

**Comment by jtpio** [comment]
Thanks! Makes sense for better reproducibility.

The only downside might be the added complexity of adding `docker` to the contributor toolbox, which was until now not needed.

**Comment by mbektas** [comment]
very good, thanks! overall process is taking a bit longer but I think it is worth it. I tested locally on Mac OS as well, tests ran fine!

**Review by mbektas — APPROVED** [review]

**Comment by fcollonval** [comment]
Thanks for the review @mbektas

**Pull request merged**
