### PR TITLE
Update the Classic Notebook FAQ section in the documentation

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/12115

## Code changes

- [x] Make the "What will happen to the Classic Notebook?" section more visible in the docs
- [x] Remove the "JupyterLab Releases" section since it was mentioning the early beta releases and 1.0 and might still confuse users that JupyterLab is not yet ready for use and extensions

## User-facing changes

Documentation update:

https://jupyterlab--14070.org.readthedocs.build/en/14070/getting_started/overview.html

image

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
This can previewed on https://jupyterlab--14070.org.readthedocs.build/en/14070/getting_started/overview.html

**Comment by echarles** [comment]
Docs CI is failing (launched 2 times) with

```
copying images... [ 98%] user/images/toc/includeOutput.gif
copying images... [100%] images/notebook-heading-anchor-link.png

copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build finished with problems, 2 warnings.
make: *** [Makefile:23: html] Error 1
Error: Process completed with exit code 2.
```

**Comment by jtpio** [comment]
Thanks for the catch, should be fixed by https://github.com/jupyterlab/jupyterlab/pull/14070/commits/4e58dbd4548e85a720e5ea031babe947bd2d693f.

**Review by echarles — APPROVED** [review]
LGTM Thx @jtpio

**Pull request merged**
