### PR TITLE
Workaround invasive use of tex mode inside of code elements and blocks

### LINKED ISSUE #6774: Markdown syntax highlighting bug due to a dollar sign ($) within a code block
**Describe the bug**

The syntax highlighting breaks down once a dollar sign is used within a code block (see the attached image). I tried using syntax highlighting (e.g. specifying `bash` after the triple backticks), but it doesn't help.

[Screen Shot 2019-07-06 at 17.20.40.pdf](https://github.com/jupyterlab/jupyterlab/files/3365050/Screen.Shot.2019-07-06.at.17.20.40.pdf)

**To Reproduce**

1. Create a new Markdown file and open it with the editor in Jupyter lab.
2. Type the following code:

```
# Hello

Sample code:

    ```
    echo $HOME
    ```

# Next section

Note: no syntax highlighting above.

```

3. See error (the section title is not highlighted after the dollar sign).

**Expected behavior**
The syntax highlighting of the `# Next section` and any supporting code below.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome 75
- JupyterLab 1.0.1

** Potentially related cases (jupyter notebook)

https://github.com/jupyterlab/jupyterlab/issues/1834

#5266
#547

### PR DESCRIPTION
**Pull request by krassowski**
## References

Fixes #6774

## Code changes

Prevent multiplexing mode from applying tex mode inside of code blocks by re-delegating parsing in those instances back to `gfmMode` parser.

## User-facing changes

| before | after |
|--------|-------|
| Screenshot from 2021-08-18 14-28-10  | Screenshot from 2021-08-18 14-28-32 |
| Screenshot from 2021-08-18 14-24-45 | Screenshot from 2021-08-18 14-33-34 |
| Screenshot from 2021-08-18 14-20-25  | Screenshot from 2021-08-18 14-20-42 |
| Screenshot from 2021-08-18 14-20-31  | Screenshot from 2021-08-18 14-20-50 |

## Backwards-incompatible changes

None

### CODE REVIEW

**Review by goanpeca — APPROVED** [review]
🚀

**Comment by krassowski** [comment]
I added two visual tests, one for latex highlighting and one for the bug being fixed:

image

image

**Comment by fperez** [comment]
Thx so much @krassowski for this! Big, big improvement to something that's been nagging many of us for a while. Much appreciated!

I'm far from an expert in the Codemirror TS code, but from a quick look at the changes, given how limited in scope they are, this looks very good - the actual functional changes are tight and simple, and most of the new code in the PR is tests and examples. So from a semi-outsider view, this looks solid, thanks again!

**Comment by blink1073** [comment]
@meeseeksdev please backport to 3.1.x

**Pull request merged**
