### PR TITLE
Add translation to filebrowser example

### PR DESCRIPTION
**Pull request by kgoo124**
## Code changes

Update the file browser example to showcase translations.

### CODE REVIEW

**Comment by kgoo124** [comment]
@goanpeca ready for review

**Review by goanpeca — APPROVED** [review]
Great work @kgoo124 ! 

All checks out 👍

**Review by goanpeca — APPROVED** [review]

**Comment by kgoo124** [comment]
@blink1073 ready for merge!

**Comment by kgoo124** [comment]
@blink1073 ready for merge!

**Comment by jasongrout** [comment]
ping @goanpeca about merging

**Comment by goanpeca** [comment]
Will take a look at it today @jasongrout !

**Comment by goanpeca** [comment]
@kgoo124 thanks for working on this. There seems to be a small package.json conflict. Could you merge with latest master?

**Comment by goanpeca** [comment]
Now that I am co-author I feel bad about merging this myself 😆

**Comment by jasongrout** [comment]
> @jasongrout now that I am co-author I feel bad about merging this myself 😆

I think an integrity check doesn't disqualify you from merging. However, if you approve, I'm happy to merge if that makes you feel more comfortable. Thanks!

**Pull request merged**
