### PR TITLE
Use stricter CSS selector for main area tab context menu so the commands don't show up elsewhere.

### LINKED ISSUE #6619: Impossible action on tab bar of L/R side panel
The tabs in the L/R side panel are not closable, but we are showing all the actions for closing tabs in the context menu:

Screen Shot 2019-06-18 at 1 01 11 PM

We are probably using too broad of a CSS selector for the context menu items that is causing them to show up for all tabs, rather than just those in the main work area.

### PR DESCRIPTION
**Pull request by ian-r-rose**
## References
Fixes #6619. This was an unintended consequence of #6052.

## Code changes

Uses a more specific CSS selector for application tab-oriented commands to only apply to the DockPanel.

## User-facing changes

More correct context menu items.

## Backwards-incompatible changes

None.

### CODE REVIEW

**Comment by jasongrout** [comment]
It needs to be more specific than this. In general, it shouldn't just be phosphor classes, but specific JLab classes. For example, we use phosphor tabs in ipywidgets that would satisfy this selector.

**Comment by ian-r-rose** [comment]
Good point. I've tightened it further. Unfortunately, this ties it pretty strongly to the specific DOM structure of the dock panel, but I didn't really see a way around that.

**Comment by jasongrout** [comment]
That works. Or @mbektasbbg and I thought this might work: `#jp-main-dock-panel p-DockPanel-tabBar.jp-Activity p-TabBar-tab`

**Comment by jasongrout** [comment]
(the thought behind the above structure is that it is anchoring us to JupyterLab classes that *we* add specifically on the things we are trying to narrow down to, without fixing us on the DOM structure of the tab bar itself)

**Comment by ian-r-rose** [comment]
That makes sense as well, and is perhaps less sensitive to possible changes in the underlying DOM.

**Comment by jasongrout** [comment]
> perhaps less sensitive to possible changes in the underlying DOM.

Plus it's probably a better pattern for people to mimic.

**Comment by jasongrout** [comment]
> That makes sense as well, and is perhaps less sensitive to possible changes in the underlying DOM.

Did you want to make this change, then?

**Comment by ian-r-rose** [comment]
For some reason I haven't been able to determine yet, your suggested selector is not doing the job: something is not matching just yet.

Also, I'm a bit concerned that we don't actually intend to add `jp-Activity` to the tabs. The intention is for that to be on the body of the main area widget, and it seems that tabs are getting it as well. It's not necessarily a problem, since that class has not styling, but seems potentially a problem.

**Comment by jasongrout** [comment]
> I'm a bit concerned that we don't actually intend to add `jp-Activity` to the tabs.

Oh, that does seem troubling.

**Pull request merged**
