### PR TITLE
Exported files saved in current directory by default

### PR DESCRIPTION
**Pull request by Madhu94**
Fixes # https://github.com/jupyterlab/jupyterlab/issues/4563

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks @Madhu94! I tagged this as 'needs discussion', since it is a big behavior change (download the export, vs save into the current folder).

Does your current code work for, say, exporting to pdf? It seems that it is working with the file as text, which may not work for binary files.

CC @ellisonbg for ux input about what we want the "Export" option to do - download or save to the current directory.

**Comment by Madhu94** [comment]
> Does your current code work for, say, exporting to pdf? It seems that it is working with the file as text, which may not work for binary files.

I'll check this today. The branch needs a rebase too.

**Comment by Madhu94** [comment]
You were right; I wasn't handled non text cases - got it working now. I noticed a weird thing - the nbconvert POST handler was returning `text/latex` as the pdf file's Content-Type. I'll mark this PR as WIP until I check over in the nbconvert repo if this was intentional.

**Comment by jasongrout** [comment]
> I noticed a weird thing - the nbconvert POST handler was returning `text/latex` as the pdf file's Content-Type.

That does seem like a bug. Thanks for catching that!

**Comment by Madhu94** [comment]
Created https://github.com/jupyter/nbconvert/pull/972. Should we wait on the nbconvert PR or go ahead with discussing if this one should be merged or not?

**Comment by MSeal** [comment]
We're planning on doing an nbconvert release by early April if that helps with timing.

**Comment by jweill-aws** [comment]
There hasn't been any activity on this pull request in over a year. As part of an effort to clean up this repository's pull requests, I'm closing this request. If you would still like to merge this code in, please reopen the request and resolve any outstanding merge conflicts. All of the code and comments will remain in place. Thank you for being part of the JupyterLab community!

**Pull request closed without merging**
