### PR TITLE
fix examples

### PR DESCRIPTION
**Pull request by wolfv**
Fixes jupyterlab examples (don't seem to build out of the box for me).

Cheers!

Wolf

### CODE REVIEW

**Comment by saulshanabrook** [comment]
I was able to build the examples and start them OK. Themes seem to load.

I ran:

```bash
jlpm run 
jlpm run build:examples
cd examples/cell/
python main.py
```

These paths I think were set intentionally to the unbuilt themes so that the examples build the themes themselves, see https://github.com/jupyterlab/jupyterlab/pull/5505

This PR breaks the current tests which rely on not having the themes built before. 

Could you help me reproduce the examples failing?

**Comment by wolfv** [comment]
Hi Saul, thanks for looking at this.
I was using `npm run build` which, at least for the notebook example, doesn't seem to do the right thing.
Maybe the build command in package.json should use `jlpm`?

**Comment by saulshanabrook** [comment]
`jlpm` should give you the same as `npm`... I will try the notebook example again just to make sure.

**Comment by wolfv** [comment]
Hi Saul, 

thanks! I'm curious how it goes.

**Comment by jasongrout** [comment]
@wolfv - does `jlpm` work for you on the master branch (without this PR)?

**Comment by jasongrout** [comment]
> @wolfv - does `jlpm` work for you on the master branch (without this PR)?

@wolfv - any update on this?

**Comment by wolfv** [comment]
Yes it works, feel free to close this!

**Pull request closed without merging**
