### PR TITLE
Use jupyter-packaging as setupbase

### PR DESCRIPTION
**Pull request by blink1073**
Fixes https://github.com/jupyterlab/jupyterlab/issues/1493

### CODE REVIEW

**Comment by blink1073** [comment]
cc @gnestor

**Comment by blink1073** [comment]
cc @willingc @minrk @ellisonbg

**Comment by gnestor** [comment]
@blink1073 Is this importing the jupyter-packaging package or just using the same code as it?

**Comment by blink1073** [comment]
@gnestor, this uses a local copy pending https://github.com/jupyter/jupyter-packaging/pull/5 and a release of that package.

**Comment by blink1073** [comment]
Rebase is too messy at this point, will re-attack at another time.

**Pull request closed without merging**
