### PR TITLE
Update to TypeScript 4.4

### PR DESCRIPTION
**Pull request by jtpio**
## References

Try updating to the latest TypeScript stable version.

Blog post: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/

## Code changes

Dependency update.

## User-facing changes

None

## Backwards-incompatible changes

Probably declarations have changed, so good to do the update for 4.0.

### CODE REVIEW

**Comment by fcollonval** [comment]
@lumino/virtualdom is hit by the [`lib.d.ts` changes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#breaking-changes) in 4.4

**Comment by fcollonval** [comment]
Typescript is moving to extract the dom type definition in a separate `@types/web` package to be able to handle backwards compatibility. The separation is expected to happen for TS 4.5. Version 0.0.1 of `@types/web` is the dom lib version shipped with TS 4.3.

Ref:
- https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029
- https://www.npmjs.com/package/@types/web

**Comment by blink1073** [comment]
This should work now if you upgrade `@lumino/widgets` to pick up https://github.com/jupyterlab/lumino/pull/237

**Comment by blink1073** [comment]
You'll probably need to upgrade all packages in the release: https://github.com/jupyterlab/lumino/pull/238

**Comment by jtpio** [comment]
The first issue is gone after updating to newer `@lumino` packages.

And now facing a `RangeError: Maximum call stack size exceeded` error:

image

**Comment by jtpio** [comment]
Closing in favor of https://github.com/jupyterlab/jupyterlab/pull/11594

**Pull request closed without merging**
