### PR TITLE
Pin puppeteer to fix browser_check in CI

### LINKED ISSUE #8244: Browser Check is Broken in CI
## Description
Puppeteer v3 does not yet work in the Azure build [environments](https://github.com/puppeteer/puppeteer/issues/5674), and it is affecting anyone that uses our browser check in CI.  cf https://github.com/jupyterlab/extension-cookiecutter-ts/issues/60#issuecomment-616191849.

## Reproduce
- Install JupyterLab in an Azure build environment (GitHub Actions or Azure Pipelines)
- Run `python -m jupyterlab.browser_check`.

The solution is to pin `puppeteer` to `^2` in the [browser check](https://github.com/jupyterlab/jupyterlab/blob/f0153e0258b32674c9aec106383ddf7b618cebab/jupyterlab/browser_check.py#L147).  This should be backported to 2.1.x and 1.2.x.

### PR DESCRIPTION
**Pull request by blink1073**
## References
Fixes #8244 

## Code changes
Pins the version of puppeteer to avoid taking a new dependency on libgbm1.

## User-facing changes
Extension authors using `browser_check` for CI will have their builds fixed.

## Backwards-incompatible changes
None

### CODE REVIEW

**Comment by blink1073** [comment]
All GH Actions tests are passing, merging.

**Comment by blink1073** [comment]
@meeseeksdev backport to 1.2.x.

**Comment by blink1073** [comment]
@meeseeksdev please backport to 1.2.x

**Comment by blink1073** [comment]
@meeseeksdev please backport to 2.1.x

**Comment by saulshanabrook** [comment]
Thank you Steve!

**Pull request merged**
