### PR TITLE
[WIP] Use single global comm for vdom-extension

### PR DESCRIPTION
**Pull request by gnestor**
When using the new event handler feature in vdom, it's easy to run into the following issue:

```
[E 14:25:56.106 LabApp] Uncaught exception GET /api/kernels/9b07598f-f972-4154-ba02-24cb223a0891/channels?session_id=88cc0759-6744-4d7e-b503-a266628ea10b&token=4431ca05d2bf9e8fb5e2ad681db65b61716cf52fee8b2f8e (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/9b07598f-f972-4154-ba02-24cb223a0891/channels?session_id=88cc0759-6744-4d7e-b503-a266628ea10b&token=4431ca05d2bf9e8fb5e2ad681db65b61716cf52fee8b2f8e', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/grant/anaconda/lib/python3.6/site-packages/tornado/websocket.py", line 546, in _run_callback
        result = callback(*args, **kwargs)
      File "/Users/grant/anaconda/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 276, in open
        self.create_stream()
      File "/Users/grant/anaconda/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 130, in create_stream
        self.channels[channel] = stream = meth(self.kernel_id, identity=identity)
      File "/Users/grant/anaconda/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 33, in wrapped
        r = method(*args, **kwargs)
      File "/Users/grant/anaconda/lib/python3.6/site-packages/jupyter_client/ioloop/manager.py", line 22, in wrapped
        socket = f(self, *args, **kwargs)
      File "/Users/grant/anaconda/lib/python3.6/site-packages/jupyter_client/connect.py", line 563, in connect_stdin
        return self._create_connected_socket('stdin', identity=identity)
      File "/Users/grant/anaconda/lib/python3.6/site-packages/jupyter_client/connect.py", line 543, in _create_connected_socket
        sock = self.context.socket(socket_type)
      File "/Users/grant/anaconda/lib/python3.6/site-packages/zmq/sugar/context.py", line 146, in socket
        s = self._socket_class(self, socket_type, **kwargs)
      File "/Users/grant/anaconda/lib/python3.6/site-packages/zmq/sugar/socket.py", line 59, in __init__
        super(Socket, self).__init__(*a, **kw)
      File "zmq/backend/cython/socket.pyx", line 328, in zmq.backend.cython.socket.Socket.__init__
    zmq.error.ZMQError: Too many open files
```

as a result of connecting to too many comms. This is because each event handler was registering its own comm channel.

The simple solution is to register a single, global comm channel for all vdom components to use and include a unique id in the payloads. This PR makes the necessary changes in vdom-extension.

Once https://github.com/jupyterlab/jupyterlab/pull/5670 is merged and this is rebase, this PR mostly simplifies the event handling logic in vdom-extension, as well as using a constant `vdom` comm target name and debouncing the sending of comm messages.

This depends on the following PRs and should wait until they are merged (and maybe released):

- [ ] https://github.com/nteract/vdom/pull/86
- [x] https://github.com/nteract/nteract/pull/4044/files

### CODE REVIEW

**Comment by jasongrout** [comment]
Is this using kernel comm channels (i.e., https://jupyter-client.readthedocs.io/en/latest/messaging.html#custom-messages)? Kernel comm channels don't actually open up a new zmq channel. They basically are just comm ID values for routing a comm message over the iopub/shell channels.

**Comment by jasongrout** [comment]
Was each handler opening its own kernel connection? Each kernel connection (IIRC) opens a new URL up.

**Comment by gnestor** [comment]
Thanks for this comment @jasongrout. I assumed that calling `session.connectToComm` was responsible for this error but it appears that `Session.connectTo` was! Every event handler was _connecting to_ to the notebook's session and in doing that it was creating a new session and network connection. It just so happens that the hack I was using to access the current session's path (`options.resolver._session.path`) also provides the session's kernel (`options.resolver._session.kernel`), so in https://github.com/jupyterlab/jupyterlab/pull/5670/commits/157a60a9c31ce05bae43ee1218c8083ecd79ab6a I was able omit the `Session.connectTo` bits and no more "zmq.error.ZMQError: Too many open files" errors! 

I'm going to do some more testing, but it looks like we can probably close this, unless there is some benefit in using one comm channel vs. many comm channels.

**Comment by gnestor** [comment]
This doesn't seem necessary anymore, closing...

**Pull request closed without merging**
